kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-payments
  namespace: agents
spec:
  rules:

    - alert: TransferSuccessRateLow
      expr: |
        # Successful/Cancelled/Unavailable transfer outcomes below 50%
        (sum by(provider) (increase(tink_agent_transfer_total{provider_type!="test", outcome=~"completed|cancelled|unavailable"}[1h]))
          / sum by(provider) (increase(tink_agent_transfer_total{provider_type!="test"}[1h]))) < 0.5
        # # At least this many attempts
        and sum by(provider) (increase(tink_agent_transfer_total{provider_type!="test"}[1h])) > 5
      for: 5m
      labels:
        severity: urgent
        priority: P3
        who: payments
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Transfer success rate is below 50% actual % is <{ $value }> for <{ $labels.className }> ( <{ $labels.provider }> )            the last 1h. More than 5 attempts.
        tags: <{ $labels.provider }> , *#payments*

    {{- if .Values.Environment }}
    {{- if eq .Values.Environment "production" }}
    - alert: TransferFailedOutcomeThresholdIsPassedForSwedenTier2Banks
      expr: sum by (provider, outcome) (increase(tink_agent_transfer_total{market="SE", provider!~".*(nordea|seb|swedbank|handelsbanken).*", outcome="failed"}[1h])) >= 5
      labels:
        severity: urgent
        who: payments
        priority: P4
      annotations:
        description: Check overall trend for this provider to assess the impact. https://grafana.global-production.tink.network/d/NMhMIXRGz/se-trends-from-aggregation-service-pov?orgId=1&from=now-12h&to=now
        summary: Threshold exceed for ( <{ $labels.provider }> ) for transfers with outcome ( <{ $labels.outcome }> ).

    - alert: TransferFailedOutcomeThresholdIsPassedForSwedenTier1Banks
      expr: sum by (provider, outcome) (increase(tink_agent_transfer_total{market="SE", provider=~".*(nordea|seb|swedbank|handelsbanken).*", outcome="failed"}[1h])) >= 5
      labels:
        severity: urgent
        who: payments
        priority: P3
      annotations:
        description: Check overall trend for this provider to assess the impact. https://grafana.global-production.tink.network/d/NMhMIXRGz/se-trends-from-aggregation-service-pov?orgId=1&from=now-12h&to=now
        summary: Threshold exceed for ( <{ $labels.provider }> ) for transfers with outcome ( <{ $labels.outcome }> ).
    {{- end }}
    {{- end }}
