kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-payments
  namespace: agents
spec:
  rules:

    - alert: TransferSuccessRateLow
      expr: |
        # Successful/Cancelled/Unavailable transfer outcomes below 50%
        (sum by(className) (increase(tink_agent_transfer_total{provider_type!="test", outcome=~"completed|cancelled|unavailable"}[1h]))
          / sum by(provider) (increase(tink_agent_transfer_total{provider_type!="test"}[1h]))) < 0.5
        # # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{provider_type!="test"}[1h])) > 5
      for: 5m
      labels:
        severity: urgent
        priority: P3
        who: payments
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Transfer success rate is below 50% actual % is <{ $value }> for <{ $labels.className }> the last 1h. More than 5 attempts.
        tags: <{ $labels.className }> , *#payments*

    {{- if .Values.Environment }}
    {{- if eq .Values.Environment "production" }}
    - alert: TransferFailedOutcomeThresholdIsPassedForSwedenTier2Banks
      expr: sum by (className, outcome) (increase(tink_agent_transfer_total{market="SE", className!~".*(nordea|seb|swedbank|handelsbanken).*", outcome="failed"}[1h])) >= 5
      labels:
        severity: urgent
        who: payments
        priority: P4
      annotations:
        description: Check overall trend for this provider to assess the impact. https://grafana.global-production.tink.network/d/NMhMIXRGz/se-trends-from-aggregation-service-pov?orgId=1&from=now-12h&to=now
        summary: Threshold exceed for ( <{ $labels.className }> ) for transfers with outcome ( <{ $labels.outcome }> ).

    - alert: TransferFailedOutcomeThresholdIsPassedForSwedenTier1Banks
      expr: sum by (provider, outcome) (increase(tink_agent_transfer_total{market="SE", provider=~".*(nordea|seb|swedbank|handelsbanken).*", outcome="failed"}[1h])) >= 5
      labels:
        severity: urgent
        who: payments
        priority: P3
      annotations:
        description: Check overall trend for this provider to assess the impact. https://grafana.global-production.tink.network/d/NMhMIXRGz/se-trends-from-aggregation-service-pov?orgId=1&from=now-12h&to=now
        summary: Threshold exceed for ( <{ $labels.provider }> ) for transfers with outcome ( <{ $labels.outcome }> ).
    {{- end }}
    {{- end }}
