#!/bin/bash

APP=$(echo "$DPKG_MAINTSCRIPT_PACKAGE" | sed 's/tink-backend-//')
USER=tink-backend-$APP

# Linux users and groups has a length limit of 32 characters
# tink-backend-aggregation-controller is trimmed to tink-backend-aggregation-control
USER=${USER:0:32}

USER_HOME=/usr/share/tink-backend-$APP
HEAPDUMPS=/var/tmp/tink/heapdumps/tink-backend-$APP

if [ "$1" = configure ]; then
    adduser --system \
            --quiet \
            --home "$USER_HOME" \
            --no-create-home \
            --disabled-password \
            --group "$USER" || true

    mkdir -p "$HEAPDUMPS" || exit 1
    chown "$USER": "$HEAPDUMPS"
    chmod 700 "$HEAPDUMPS"
fi

systemctl daemon-reload
systemctl enable tink-backend-$APP

if [ -f /etc/tink/$APP-server.yml ]; then
    systemctl start tink-backend-$APP
fi
