java_library(
    name = "enums",
    srcs = glob(["src/main/**/*.java"]),
    visibility = [
        "//src/aggregation:__subpackages__",
        "//src/aggregation/aggregationcontroller_api:__subpackages__",
        "//src/integration:__subpackages__",
    ],
    deps = [
        "//src/libraries/account_identifier",
        "//third_party:com_google_guava_guava",
        "//third_party:org_apache_commons_commons_lang3",
    ],
)
