load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "parsingrules",
    srcs = glob(
        ["*.java"],
    ),
    data = [
    ],
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/agents/framework/wiremock/utils/parsingrules/parsingoperations",
    ],
)
