java_library(
    name = "access_logging",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/auth",
        "//third_party:com_google_guava_guava",
        "//third_party:org_slf4j_jul_to_slf4j",
    ],
)
