package se.tink.backend.aggregation.agents.nxgen.serviceproviders.banks.bankdata.fetcher.rpc;

import com.fasterxml.jackson.databind.ObjectMapper;

public class GetAccountsResponseTestData {
    public static GetAccountsResponse getTestData() throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        return mapper.readValue(TEST_DATA, GetAccountsResponse.class);
    }

    private static final String TEST_DATA =
            "{"
                    + "\"accounts\": [{"
                    + "\"regNo\": \"1111\","
                    + "\"accountNo\": \"0001111111\","
                    + "\"accountType\": 0,"
                    + "\"balance\": 10.0,"
                    + "\"bicSwift\": \"RINGDK11\","
                    + "\"currencyCode\": \"DKK\","
                    + "\"drawingRight\": 0.0,"
                    + "\"iban\": \"DK1111710001111111\","
                    + "\"name\": \"Basiskonto\","
                    + "\"overdraft\": false,"
                    + "\"transfersToAllowed\": true,"
                    + "\"transfersFromAllowed\": false,"
                    + "\"editNameAllowed\": false,"
                    + "\"yearToDayPayout\": 0.0,"
                    + "\"yearToDayDeposit\": 0.0,"
                    + "\"accountOwner\": \"Olsen Brothers\","
                    + "\"allShadowAccountsInactive\": false,"
                    + "\"ownAccount\": true,"
                    + "\"amountAtDisposal\": 0.0,"
                    + "\"amountAtDisposalToBeShown\": false,"
                    + "\"totalReservation\": 0.0,"
                    + "\"totalShadowAccountBalance\": 0.0,"
                    + "\"priority\": 0,"
                    + "\"mastercard\": false,"
                    + "\"regNoAsInt\": 1111,"
                    + "\"accountNoAsLong\": 1111111,"
                    + "\"accountOwnerRefNo\": 1111111"
                    + "}, {"
                    + "\"regNo\": \"1111\","
                    + "\"accountNo\": \"0001111111\","
                    + "\"accountType\": 0,"
                    + "\"balance\": 0.0,"
                    + "\"bicSwift\": \"RINGDK11\","
                    + "\"currencyCode\": \"DKK\","
                    + "\"drawingRight\": 0.0,"
                    + "\"iban\": \"DK1111110001111111\","
                    + "\"name\": \"Investeringskonto\","
                    + "\"overdraft\": false,"
                    + "\"transfersToAllowed\": true,"
                    + "\"transfersFromAllowed\": true,"
                    + "\"editNameAllowed\": true,"
                    + "\"yearToDayPayout\": 0.0,"
                    + "\"yearToDayDeposit\": 0.0,"
                    + "\"accountOwner\": \"Olsen Brothers\","
                    + "\"allShadowAccountsInactive\": false,"
                    + "\"ownAccount\": true,"
                    + "\"amountAtDisposal\": 0.0,"
                    + "\"amountAtDisposalToBeShown\": false,"
                    + "\"totalReservation\": 0.0,"
                    + "\"totalShadowAccountBalance\": 0.0,"
                    + "\"priority\": 0,"
                    + "\"mastercard\": false,"
                    + "\"regNoAsInt\": 1111,"
                    + "\"accountNoAsLong\": 1111111,"
                    + "\"accountOwnerRefNo\": 1111111"
                    + "}],"
                    + "\"mastercardAgreements\": []"
                    + "}";
}
