package se.tink.backend.aggregation.agents.nxgen.serviceproviders.banks.bankdata.fetcher.rpc;

import com.fasterxml.jackson.databind.ObjectMapper;

public class GetTransactionsResponseTestData {

    public static GetTransactionsResponse getTestData() throws Exception {
        ObjectMapper mapper = new ObjectMapper();

        return mapper.readValue(TEST_DATA, GetTransactionsResponse.class);
    }

    private static final String TEST_DATA =
            "{"
                    + "\"numOfTransactions\": 2,"
                    + "\"lstTransactions\": [{"
                    + "\"account\": {"
                    + "\"regNo\": \"1111\","
                    + "\"accountNo\": \"0001111111\""
                    + "},"
                    + "\"splits\": [{"
                    + "\"transactionSplitId\": 111111111,"
                    + "\"amount\": 10.0000,"
                    + "\"categoryId\": 459"
                    + "}],"
                    + "\"identifier\": \"2017-09-18-02.57.36.729033\","
                    + "\"currency\": \"DKK\","
                    + "\"balance\": -20.00,"
                    + "\"unCleared\": false,"
                    + "\"flagged\": false,"
                    + "\"balanced\": false,"
                    + "\"message\": false,"
                    + "\"attachment\": false,"
                    + "\"tags\": [],"
                    + "\"text\": \"Oprettelse af Basiskonto\","
                    + "\"mainAmount\": -10.00,"
                    + "\"valeurDate\": \"18.09.2017\","
                    + "\"transactionDate\": \"18.09.2017\","
                    + "\"stoppable\": false,"
                    + "\"newMaxSplitAmount\": 10.00,"
                    + "\"parentCategoryId\": 411,"
                    + "\"split\": false,"
                    + "\"partial\": false,"
                    + "\"outOfSyncTransaction\": false,"
                    + "\"status\": 1,"
                    + "\"canVerify\": false,"
                    + "\"reservation\": false"
                    + "}, {"
                    + "\"account\": {"
                    + "\"regNo\": \"1111\","
                    + "\"accountNo\": \"0001111111\""
                    + "},"
                    + "\"splits\": [{"
                    + "\"transactionSplitId\": 111111111,"
                    + "\"amount\": 10.0000"
                    + "}],"
                    + "\"identifier\": \"2017-09-17-00.05.58.215494\","
                    + "\"currency\": \"DKK\","
                    + "\"balance\": -10.00,"
                    + "\"unCleared\": false,"
                    + "\"flagged\": false,"
                    + "\"balanced\": false,"
                    + "\"message\": false,"
                    + "\"attachment\": false,"
                    + "\"tags\": [],"
                    + "\"text\": \"MasterDebit-Årlig Standard\","
                    + "\"mainAmount\": -10.00,"
                    + "\"valeurDate\": \"17.09.2017\","
                    + "\"transactionDate\": \"17.09.2017\","
                    + "\"stoppable\": false,"
                    + "\"newMaxSplitAmount\": 10.00,"
                    + "\"parentCategoryId\": 411,"
                    + "\"split\": false,"
                    + "\"partial\": false,"
                    + "\"outOfSyncTransaction\": false,"
                    + "\"status\": 1,"
                    + "\"canVerify\": false,"
                    + "\"reservation\": false"
                    + "}],"
                    + "\"reservedAmount\": 0,"
                    + "\"moreTransactionsAvailable\": false,"
                    + "\"accountBalance\": {"
                    + "\"balance\": -20.00,"
                    + "\"available\": 0.00"
                    + "}"
                    + "}";
}
