load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "annotation",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_google_inject_guice",
    ],
)
