alias(
    name = "client",
    actual = "//src/integration/tpp_secrets_service/client/src/main/java/se/tink/backend/integration/tpp_secrets_service/client:tpp-secrets-service-client",
    visibility = ["//visibility:public"],
)

alias(
    name = "entities",
    actual = "//src/integration/tpp_secrets_service/client/src/main/java/se/tink/backend/integration/tpp_secrets_service/client/entities:entities",
    visibility = ["//visibility:public"],
)

alias(
    name = "utils",
    actual = "//src/integration/tpp_secrets_service/client/src/main/java/se/tink/backend/integration/tpp_secrets_service/client/entities/utils:utils",
    visibility = ["//visibility:public"],
)
