alias(
    name = "client",
    actual = "//src/integration/tpp_secrets_service/client/src/main/java/se/tink/backend/integration/tpp_secrets_service/client:tpp-secrets-service-client",
    visibility = ["//visibility:public"],
)
