load("@tink_backend//tools/bzl:junit_strict.bzl", "junit_test")

java_library(
    name = "currency",
    srcs = glob(["*.java"]),
    data = [],
    visibility = ["//visibility:public"],
    deps = [
    ],
)
