package se.tink.backend.agents.rpc;

import java.util.EnumSet;

public enum CredentialsStatus {
    CREATED,
    AUTHENTICATING,
    UNCHANGED,
    UPDATING,
    UPDATED,
    AWAITING_MOBILE_BANKID_AUTHENTICATION,
    AWAITING_THIRD_PARTY_APP_AUTHENTICATION,
    AWAITING_SUPPLEMENTAL_INFORMATION,
    AWAITING_OTHER_CREDENTIALS_TYPE,
    AUTHENTICATION_ERROR,
    NOT_IMPLEMENTED_ERROR,
    TEMPORARY_ERROR,
    HINTED,
    PERMANENT_ERROR,
    DELETED,
    METRIC,
    DISABLED,
    SESSION_EXPIRED;

    public static final EnumSet<CredentialsStatus> FAILED_OPERATION_STATUSES = EnumSet.of(
    UNCHANGED, TEMPORARY_ERROR, AUTHENTICATION_ERROR);
}
