java_library(
    name = "executor-utils",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/concurrency",
        "//src/libraries/log",
        "//third_party:com_google_guava_guava",
    ],
)
