partnerId-description: |2
  The client Id is a public identifier that identifies Tink to the Nordea Partner service.
partnerId-example: |2
  "bf873fdc-035b-48ef-a616-3b3c3fc243df"
baseUrl-example: |2
  "https://private.nd.test.nordea.se/api/dbf/ca/partners-service-common-v2"
nordeaSigningPublicKey-description: |2
  The public key that will be used to verify the signed JWE tokens those are received
  from Nordea during authentication as supplemental information. This should be the X509
  base64 encoded public key.
nordeaSigningPublicKey-example: |2
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg8UDNd14d/Idf5i6D0IzK/sYa5dHd6dufyfjFGX6Y+NEu7vR91mT2M5pskvRlIfNgWQLdrYVuKqN2ZSlDd66QM0ML3D+5d+fWPPsCZ6mvXr3HNRduUgTqruUwNl/JgL1MHSq2FstFpT+lT5JR+C6mi6POKLtiXaUtA/44wXTmfxSQKSTpsSBVNS93WLfOA4gKqG6FnO7QiauedMQWScMpBzUo+cC3Y1tIndVnm2DOJtkZ3PgiGqnsjD3sHbfJj0ASsnNtQ+29j3x/QkxfPr6ASOywn/QjKsklxEd7fKYL7R5DCHn5Jfa/MKnjwSxMAx3+LRoqGqqogU7ubiGwideoQIDAQAB"
nordeaEncryptionPublicKey-description: |2
  The public key that will be used to encrypt Tinks JWE tokens those are included in the
  headers. This should be the X509 base64 encoded public key.
nordeaEncryptionPublicKey-example: |2
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzTHUSrVhLcbA59fdf+utR2w1MdWTG0fUnsmJa9YlgaI3mVFQDlKXc0+oflTqLnIMDchn74a74sPbCZ20Tv3U8upFZ8WPZlqjGlGRv5OVGf5yHxaybjS0kpByhLaZZrRzeC2AGXL9FJ/V2wyUz+RQLWWf3/VQcTjMXxoMOxIYY/3mOla2TgU/Xsa5SNEVaYvsoysrVqMA6YZqGfdLzNSU8tbVrC0j1SvWXmW+8fjXHR+HY7T4EyJTw/pqfrk8s5KIBijgQDhOv7AvACOb1AkykljFQ182bTZv6gzBBGc2DALA7IKG4oq0bzMgn77w7zRkVpnOQTwHIBybhvsdPvgmlwIDAQAB"
tinkSingingPrivateKey-description: |2
  The private key that will be used to sign Tinks JWE tokens those are included in the headers.
  This should be the PKCS8 base64 encoded private key.
tinkSingingPrivateKey-example: |2
  "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDjrbE3UIx4Kqkipvs0waSmfiDY////truncated/////u9o9oj3Pi6QDrruYjWSeOlnVhiQ=="
tinkSingingPublicKey-description: |2
  The public key that will be used by Nordea to verify the signed JWE tokens sent by Tink.
  This should be the X509 base64 encoded public key.
tinkSingingPublicKey-example: |2
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA462xN1CMeCqpIqb7NMGkpn4g2CZWYVpWqAW5UqMCojLcX+lpy72JTHgcEYvBpq7tTq8cR0HvAb2xagQ+273KRvhuvMCrPyi8UEH8QIgSiGceaivqu6hK7ieemvoh0cOaQnkL54PSdVUIlmGm0/BOInmgviS+Lwi6IHCORTdYsxSafNH/n98qkOUJLluRtP/XyRWLpHL/mTB2t+foCsrTlCWAxvyxXn+R+JDd6c8UZO4V0gxrYoKTmx4T0rW9AuC+mzPKIM4CfHeuTf65zRm+nhUNjvnZZC+34YQeFFEhbaV77io8CJBOc8Yz2RayPlfuqumkwCpjA6N1zgj6XUGTVwIDAQAB"
tinkEncryptionPrivateKey-description: |2
  The private key that will be used by Tink to decrypt JWE tokens those are received from
  Nordea during authentication as supplemental information. This should be the PKCS8 base64
  encoded private key.
tinkEncryptionPrivateKey-example: |2

  "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDjrbE3UIx4Kqkipvs0waSmfiDY////truncated/////u9o9oj3Pi6QDrruYjWSeOlnVhiQ=="
tinkEncryptionPublicKey-description: |2
  The public key that will be used by Nordea to encrypt JWE tokens before sending them as
  supplemental information. This should be the X509 base64 encoded public key.
tinkEncryptionPublicKey-example: |2
  "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqHJbKfWjKYnnY8jwMWq0VKU/EGb/+mi8D2fZdlU5f2QiFxvIj8du7hBt5Pju9xjowzFd1oLsW3uI1AIV/KUAhhB7Lr4Q2cAt7IQQdWZg9lYYez+qssYq5ytyMfBHwHsqRv6zBKaMiXkZ0A8VCFaoSZgF867IT9l094qdbhH92XKkNlaH8AHplSl9v22U8YdzWomIpy8HV1OpKcvHfJY1pHH+/1iO6bER661LG2fRXMCtCQXro9pHsPzZm+eJ0qKBx4jy2+obPU5qu0hT0XGz4zPIOIr+I5xvG0GVWbrZHmDDmA1EBvGPT+yQjXWBtpws3AHzZoPX/Bbt73Ky4lBGzwIDAQAB"
kid-description: |2
  From https://tools.ietf.org/html/rfc7515#section-4.1.4: The "kid" (key ID) Header Parameter
  is a hint indicating which key was used to secure the JWS. This parameter allows originators
  to explicitly signal a change of key to recipients. The structure of the "kid" value is
  unspecified. Its value MUST be a case-sensitive string.
keyId-example: |2
  "tink-nordea-kid"