package se.tink.backend.aggregation.agents.nxgen.es.banks.bbva.fetcher.creditcard.entities;

public class CreditCardEntityTestData {

    static String CREDIT_CARD_TRANSACTION =
            "{\n"
                    + "      \"id\": \"111111111111_111111_111111_11111111111111111111111adadad11111111111111111111111111111111111_AA\",\n"
                    + "      \"operationKey\": \"123123****2314   123123123123123123\",\n"
                    + "      \"contract\": {\n"
                    + "        \"id\": \"AA1231231231231231231231231231231231XXXXXXXXX\",\n"
                    + "        \"counterPart\": \"0615\",\n"
                    + "        \"bank\": {\n"
                    + "          \"id\": \"0182\"\n"
                    + "        },\n"
                    + "        \"branch\": {\n"
                    + "          \"id\": \"2495\"\n"
                    + "        },\n"
                    + "        \"formats\": {\n"
                    + "          \"bocf\": \"01822495061500000023261568\",\n"
                    + "          \"iuc\": \"00000000000000000271023383\",\n"
                    + "          \"pan\": \"123123****1234\"\n"
                    + "        },\n"
                    + "        \"product\": {\n"
                    + "          \"name\": \"DESPUES ORO BBVA\"\n"
                    + "        }\n"
                    + "      },\n"
                    + "      \"transactionDate\": \"2019-09-06T00:00:34.000+0200\",\n"
                    + "      \"transactionTypeIndicator\": \"C\",\n"
                    + "      \"concept\": {\n"
                    + "        \"id\": \"0005\",\n"
                    + "        \"name\": \"FACTURA VENTA\"\n"
                    + "      },\n"
                    + "      \"amount\": {\n"
                    + "        \"currency\": {\n"
                    + "          \"id\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"amount\": -5246.0\n"
                    + "      },\n"
                    + "      \"holderAmount\": {\n"
                    + "        \"currency\": {\n"
                    + "          \"id\": \"EUR\"\n"
                    + "        },\n"
                    + "        \"amount\": -509.21\n"
                    + "      },\n"
                    + "      \"valueDate\": \"2019-09-09T00:00:00.000+0200\",\n"
                    + "      \"terminalId\": \"00726235\",\n"
                    + "      \"maximumFeeAmount\": {\n"
                    + "        \"currency\": {\n"
                    + "          \"id\": \"EUR\"\n"
                    + "        },\n"
                    + "        \"amount\": 14.14\n"
                    + "      },\n"
                    + "      \"minimumTimeLimit\": 3,\n"
                    + "      \"maximumTimeLimit\": 36,\n"
                    + "      \"virtualTpvIndicator\": \"V\",\n"
                    + "      \"operationTypeIndicator\": \"C\",\n"
                    + "      \"customizableIndicator\": \"1\",\n"
                    + "      \"exchangeValue\": 0.094237,\n"
                    + "      \"cardCdepenCode\": \"000000001\",\n"
                    + "      \"purchaser\": {\n"
                    + "        \"id\": \"948001\",\n"
                    + "        \"reference\": \"74383769250110005901729\"\n"
                    + "      },\n"
                    + "      \"commission\": {\n"
                    + "        \"currency\": {\n"
                    + "          \"id\": \"EUR\"\n"
                    + "        },\n"
                    + "        \"amount\": 0.0\n"
                    + "      },\n"
                    + "      \"shop\": {\n"
                    + "        \"id\": \"000000000\",\n"
                    + "        \"name\": \"NORDIC LIGHT HOTEL CNP\",\n"
                    + "        \"address\": \"STOCKHOLM\",\n"
                    + "        \"industry\": {\n"
                    + "          \"id\": \"7011\",\n"
                    + "          \"name\": \"CASAS DE HUESPEDES Y MOTELES\"\n"
                    + "        },\n"
                    + "        \"activitySector\": {\n"
                    + "          \"id\": \"0015\",\n"
                    + "          \"name\": \"VIAJES\"\n"
                    + "        },\n"
                    + "        \"activitySubSector\": {\n"
                    + "          \"id\": \"0014\",\n"
                    + "          \"name\": \"HOTEL\"\n"
                    + "        },\n"
                    + "        \"country\": \"SE\"\n"
                    + "      },\n"
                    + "      \"cardTransactionDate\": \"2019-09-06T00:00:00.000+0200\",\n"
                    + "      \"paymentMethod\": {\n"
                    + "        \"id\": \"1U01506U4000\"\n"
                    + "      },\n"
                    + "      \"humanCategory\": {\n"
                    + "        \"id\": \"15\",\n"
                    + "        \"name\": \"Transporte y viajes\"\n"
                    + "      },\n"
                    + "      \"humanSubcategory\": {\n"
                    + "        \"id\": \"57\",\n"
                    + "        \"name\": \"Hoteles\"\n"
                    + "      },\n"
                    + "      \"customPaymentInformation\": {\n"
                    + "        \"interests\": {\n"
                    + "          \"rate\": 0.0\n"
                    + "        },\n"
                    + "        \"expirationDate\": \"2019-10-31T00:00:00.000+0100\"\n"
                    + "      },\n"
                    + "      \"stillCustomizable\": true,\n"
                    + "      \"status\": {\n"
                    + "        \"id\": \"7\",\n"
                    + "        \"name\": \"Consolidado\"\n"
                    + "      },\n"
                    + "      \"isContractHolder\": true,\n"
                    + "      \"visible\": true,\n"
                    + "      \"processingType\": \"01B\",\n"
                    + "      \"paymentType\": {\n"
                    + "        \"id\": \"4\"\n"
                    + "      },\n"
                    + "      \"statement\": {\n"
                    + "        \"id\": \"45\",\n"
                    + "        \"initialDate\": \"2019-09-01T00:00:00.000+0200\",\n"
                    + "        \"endDate\": \"2019-09-30T00:00:00.000+0200\",\n"
                    + "        \"statementDate\": \"2019-09-01T00:00:00.000+0200\"\n"
                    + "      }\n"
                    + "    }";
}
