java_library(
    name = "filter",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_google_guava_guava",
        "//third_party:com_sun_jersey_jersey_client",
    ],
)
