load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "parsingoperations",
    srcs = glob(
        ["*.java"],
    ),
    data = [
    ],
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
        "@aggregation//:com_google_guava_guava",
    ],
)
