#!/bin/bash

# Pre push hook that prevents pushing of commits that have malformatted code.
set -e

handle_result()
{
    if [ $? -ne 0 ]; then
        echo "-->"
        echo "--> Java file(s) listed above are incorrectly formatted. Execute the following bazel command:"
        echo "--> bazel run :format"
        echo "--> You can also install the Intellij plugin google-java-format, configuring code style to AOSP:"
        echo "--> IntelliJ IDEA -> Preferences -> Other Settings -> google-java-format"
        echo "--> It is also recommended to enable 'Save actions' so that formatting is automatically done on save."
        echo "-->"
        exit 1
    fi
}

trap handle_result EXIT

./bazel-wrapper build //tools/format:google-java-format 1>/dev/null

# Commit hash right before this branch diverged from master
branch_point=$(git merge-base upstream/master HEAD)

diffing_java_files=$(find $(git diff $branch_point HEAD --diff-filter='ACMR' --name-only) -type f -name "*.java")

if [ ! -z "$diffing_java_files" ]; then
    echo $diffing_java_files | xargs -n500 bazel-bin/tools/format/google-java-format --aosp --dry-run --set-exit-if-changed
fi
