load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "consent",
    srcs = glob(["*.java"]),
    visibility = ["//src/agent_sdk:__subpackages__"],
)
