package se.tink.backend.aggregation.agents.nxgen.se.banks.handelsbanken.fetcher.investment.entities;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.Map;
import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.se.banks.handelsbanken.HandelsbankenSEConstants.AccountPayloadKeys;
import se.tink.backend.aggregation.nxgen.core.account.investment.InvestmentAccount;
import se.tink.libraries.serialization.TypeReferences;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class HandelsbankenSEFundHoldingsUserTest {
    private static final String CUSTODY_ACCOUNT_JSON =
            "{\n"
                    + "  \"_links\": {\n"
                    + "    \"fund-holdings\": {\n"
                    + "      \"href\": \"https://m2.handelsbanken.se/app/priv/fund/fundHoldings/get?includeMinors=false&authToken=aaaaaaaaaaaa\",\n"
                    + "      \"gaScreenName\": \"Savings / Security holdings summary / Fund holdings\"\n"
                    + "    }\n"
                    + "  },\n"
                    + "  \"links\": [\n"
                    + "    {\n"
                    + "      \"rel\": \"fund-holdings\",\n"
                    + "      \"href\": \"https://m2.handelsbanken.se/app/priv/fund/fundHoldings/get?includeMinors=false&authToken=aaaaaaaaaaaa\",\n"
                    + "      \"type\": \"application/json\",\n"
                    + "      \"gaScreenName\": \"Savings / Security holdings summary / Fund holdings\"\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"custodyAccountNumber\": null,\n"
                    + "  \"iskAccountNumber\": null,\n"
                    + "  \"accountNumberFormatted\": \"\",\n"
                    + "  \"type\": \"FUND_SUMMARY\",\n"
                    + "  \"title\": \"Fondinnehav\",\n"
                    + "  \"infoText\": null,\n"
                    + "  \"marketValue\": {\n"
                    + "    \"amount\": 551598.34,\n"
                    + "    \"amountFormatted\": \"551 598,34\",\n"
                    + "    \"unit\": \"SEK\",\n"
                    + "    \"currency\": \"SEK\"\n"
                    + "  },\n"
                    + "  \"performance\": {\n"
                    + "    \"changeAmount\": {\n"
                    + "      \"amount\": 384666.9,\n"
                    + "      \"amountFormatted\": \"384 666,90\",\n"
                    + "      \"unit\": \"SEK\",\n"
                    + "      \"currency\": \"SEK\"\n"
                    + "    },\n"
                    + "    \"changePercentage\": {\n"
                    + "      \"quantityFormatted\": \"230,43\",\n"
                    + "      \"unit\": \"%\"\n"
                    + "    },\n"
                    + "    \"changeDirection\": \"POSITIVE\"\n"
                    + "  },\n"
                    + "  \"pensionSystemStr\": null\n"
                    + "}";

    private static final String USER_FUND_HOLDINGS_JSON =
            "{\n"
                    + "  \"ownerName\": null,\n"
                    + "  \"part\": {\n"
                    + "    \"ipIdfr\": \"44567188\",\n"
                    + "    \"ipFullNm\": \"***MASKED***\"\n"
                    + "  },\n"
                    + "  \"hasWithdrawal\": false,\n"
                    + "  \"fundHoldingSummary\": {\n"
                    + "    \"currency\": \"SEK\",\n"
                    + "    \"purchaseValue\": 166931.44,\n"
                    + "    \"marketValue\": 551598.34,\n"
                    + "    \"marketValueFormatted\": \"551 598,34\",\n"
                    + "    \"change\": 384666.9,\n"
                    + "    \"changeFormatted\": \"384 666,90\",\n"
                    + "    \"changePercentage\": 230.43406323,\n"
                    + "    \"changePercentageFormatted\": \"230,43\",\n"
                    + "    \"monthlySavings\": 0,\n"
                    + "    \"monthlySavingsFormatted\": \"0\",\n"
                    + "    \"monthlySavingsText\": \"Totalt månadssparande: 0 kr/mån\",\n"
                    + "    \"untreatedTransactions\": false\n"
                    + "  },\n"
                    + "  \"fundHoldingList\": [\n"
                    + "    {\n"
                    + "      \"shbFund\": true,\n"
                    + "      \"isin\": \"SE0001466368\",\n"
                    + "      \"currency\": \"SEK\",\n"
                    + "      \"companyName\": \"Xact Kapitalförvaltning AB\",\n"
                    + "      \"financialInstrumentName\": \"Handelsbanken Sve Index Cri A1 SEK\",\n"
                    + "      \"fundName\": \"Handelsbanken Sve Index Cri A1 SEK\",\n"
                    + "      \"externalFundId\": \"0P00001DF8\",\n"
                    + "      \"externalFundMsg\": null,\n"
                    + "      \"monthlySavings\": 0,\n"
                    + "      \"monthlySavingsFormatted\": \"0\",\n"
                    + "      \"monthlySavingsText\": \"\",\n"
                    + "      \"recurringTransferHeader\": null,\n"
                    + "      \"recurringTransferValueText\": null,\n"
                    + "      \"hasWithdrawal\": false,\n"
                    + "      \"fundHoldingDetail\": {\n"
                    + "        \"_links\": {\n"
                    + "          \"purchase-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=PURCHASE&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Search and purchase / Funds / Fund details / Buy\"\n"
                    + "          },\n"
                    + "          \"swap-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SWAP&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Swap\"\n"
                    + "          },\n"
                    + "          \"sell-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SELL&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Sell\"\n"
                    + "          },\n"
                    + "          \"new-recurring-saving-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=NEW_RECURRING_SAVING&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Fund holdings / Recurring saving / Create\"\n"
                    + "          }\n"
                    + "        },\n"
                    + "        \"links\": [\n"
                    + "          {\n"
                    + "            \"rel\": \"purchase-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=PURCHASE&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Search and purchase / Funds / Fund details / Buy\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"sell-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SELL&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Sell\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"swap-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SWAP&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Swap\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"new-recurring-saving-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=NEW_RECURRING_SAVING&fundOrFundAccountId=xxxxxxxxxxxx1&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Fund holdings / Recurring saving / Create\"\n"
                    + "          }\n"
                    + "        ],\n"
                    + "        \"availableGuardian\": false,\n"
                    + "        \"averageValueOfCost\": {\n"
                    + "          \"amount\": 97.6161,\n"
                    + "          \"amountFormatted\": \"97,62\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"account\": \"111222333\",\n"
                    + "        \"accountFormatted\": \"111 222 333\",\n"
                    + "        \"fundBelongingType\": \"GUARDIAN\",\n"
                    + "        \"holdingId\": 3,\n"
                    + "        \"holdingUnits\": 1609.8364,\n"
                    + "        \"holdingUnitsFormatted\": \"1 609,8364\",\n"
                    + "        \"isin\": \"SE0001466368\",\n"
                    + "        \"marketValueFormatted\": \"523 695,87\",\n"
                    + "        \"marketValueCurrency\": \"SEK\",\n"
                    + "        \"openForPurchase\": true,\n"
                    + "        \"openForSell\": true,\n"
                    + "        \"price\": {\n"
                    + "          \"amount\": 325.31,\n"
                    + "          \"amountFormatted\": \"325,31\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"purchaseValue\": {\n"
                    + "          \"amount\": 157145.99,\n"
                    + "          \"amountFormatted\": \"157 145,99\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"totalChange\": {\n"
                    + "          \"percentage\": 233.2544,\n"
                    + "          \"percentageFormatted\": \"233,25\",\n"
                    + "          \"amountFormatted\": \"366 549,88\",\n"
                    + "          \"changeDirection\": \"POSITIVE\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"recurringSavingsSummaryText\": \"\"\n"
                    + "      },\n"
                    + "      \"recurringSavingsDetailList\": [\n"
                    + "\n"
                    + "      ],\n"
                    + "      \"fundUntreatedTransactionList\": [\n"
                    + "\n"
                    + "      ]\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"shbFund\": true,\n"
                    + "      \"isin\": \"SE0000356065\",\n"
                    + "      \"currency\": \"SEK\",\n"
                    + "      \"companyName\": \"Handelsbanken Fonder AB\",\n"
                    + "      \"financialInstrumentName\": \"Handelsbanken Svenska Småb A1 SEK\",\n"
                    + "      \"fundName\": \"Handelsbanken Svenska Småb A1 SEK\",\n"
                    + "      \"externalFundId\": \"0P00000F8N\",\n"
                    + "      \"externalFundMsg\": null,\n"
                    + "      \"monthlySavings\": 0,\n"
                    + "      \"monthlySavingsFormatted\": \"0\",\n"
                    + "      \"monthlySavingsText\": \"\",\n"
                    + "      \"recurringTransferHeader\": null,\n"
                    + "      \"recurringTransferValueText\": null,\n"
                    + "      \"hasWithdrawal\": false,\n"
                    + "      \"fundHoldingDetail\": {\n"
                    + "        \"_links\": {\n"
                    + "          \"purchase-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=PURCHASE&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Search and purchase / Funds / Fund details / Buy\"\n"
                    + "          },\n"
                    + "          \"swap-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SWAP&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Swap\"\n"
                    + "          },\n"
                    + "          \"sell-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SELL&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Sell\"\n"
                    + "          },\n"
                    + "          \"new-recurring-saving-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=NEW_RECURRING_SAVING&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Fund holdings / Recurring saving / Create\"\n"
                    + "          }\n"
                    + "        },\n"
                    + "        \"links\": [\n"
                    + "          {\n"
                    + "            \"rel\": \"purchase-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=PURCHASE&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Search and purchase / Funds / Fund details / Buy\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"sell-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SELL&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Sell\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"swap-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SWAP&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Swap\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"new-recurring-saving-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=NEW_RECURRING_SAVING&fundOrFundAccountId=yyyyyyyyyyyy&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Fund holdings / Recurring saving / Create\"\n"
                    + "          }\n"
                    + "        ],\n"
                    + "        \"availableGuardian\": false,\n"
                    + "        \"averageValueOfCost\": {\n"
                    + "          \"amount\": 166.2645,\n"
                    + "          \"amountFormatted\": \"166,26\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"account\": \"222333444\",\n"
                    + "        \"accountFormatted\": \"222 333 444\",\n"
                    + "        \"fundBelongingType\": \"GUARDIAN\",\n"
                    + "        \"holdingId\": 1,\n"
                    + "        \"holdingUnits\": 4.7241,\n"
                    + "        \"holdingUnitsFormatted\": \"4,7241\",\n"
                    + "        \"isin\": \"SE0000356065\",\n"
                    + "        \"marketValueFormatted\": \"9 903,03\",\n"
                    + "        \"marketValueCurrency\": \"SEK\",\n"
                    + "        \"openForPurchase\": true,\n"
                    + "        \"openForSell\": true,\n"
                    + "        \"price\": {\n"
                    + "          \"amount\": 2096.28,\n"
                    + "          \"amountFormatted\": \"2 096,28\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"purchaseValue\": {\n"
                    + "          \"amount\": 785.45,\n"
                    + "          \"amountFormatted\": \"785,45\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"totalChange\": {\n"
                    + "          \"percentage\": 1160.8097,\n"
                    + "          \"percentageFormatted\": \"1 160,81\",\n"
                    + "          \"amountFormatted\": \"9 117,58\",\n"
                    + "          \"changeDirection\": \"POSITIVE\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"recurringSavingsSummaryText\": \"\"\n"
                    + "      },\n"
                    + "      \"recurringSavingsDetailList\": [\n"
                    + "\n"
                    + "      ],\n"
                    + "      \"fundUntreatedTransactionList\": [\n"
                    + "\n"
                    + "      ]\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"shbFund\": false,\n"
                    + "      \"isin\": \"LU0417597712\",\n"
                    + "      \"currency\": \"SEK\",\n"
                    + "      \"companyName\": \"Rhenman Partners\",\n"
                    + "      \"financialInstrumentName\": \"Healthcare Equity L/S RC1 SEK\",\n"
                    + "      \"fundName\": \"Rhenman Partners Healthcare Equity L/S RC1 SEK\",\n"
                    + "      \"externalFundId\": \"0P0000KGRO\",\n"
                    + "      \"externalFundMsg\": null,\n"
                    + "      \"monthlySavings\": 0,\n"
                    + "      \"monthlySavingsFormatted\": \"0\",\n"
                    + "      \"monthlySavingsText\": \"\",\n"
                    + "      \"recurringTransferHeader\": null,\n"
                    + "      \"recurringTransferValueText\": null,\n"
                    + "      \"hasWithdrawal\": false,\n"
                    + "      \"fundHoldingDetail\": {\n"
                    + "        \"_links\": {\n"
                    + "          \"purchase-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=PURCHASE&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Search and purchase / Funds / Fund details / Buy\"\n"
                    + "          },\n"
                    + "          \"swap-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SWAP&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Swap\"\n"
                    + "          },\n"
                    + "          \"sell-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SELL&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Sell\"\n"
                    + "          },\n"
                    + "          \"new-recurring-saving-context\": {\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=NEW_RECURRING_SAVING&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"gaScreenName\": \"Savings / Fund holdings / Recurring saving / Create\"\n"
                    + "          }\n"
                    + "        },\n"
                    + "        \"links\": [\n"
                    + "          {\n"
                    + "            \"rel\": \"purchase-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=PURCHASE&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Search and purchase / Funds / Fund details / Buy\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"sell-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SELL&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Sell\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"swap-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=SWAP&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Search and purchase / Funds / Fund details / Swap\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"rel\": \"new-recurring-saving-context\",\n"
                    + "            \"href\": \"https://m2.handelsbanken.se/app/priv/fund/orderContext?contextType=NEW_RECURRING_SAVING&fundOrFundAccountId=ODUzODU0MjAz&authToken=aaaaaaaaaaaa\",\n"
                    + "            \"type\": \"application/json\",\n"
                    + "            \"gaScreenName\": \"Savings / Fund holdings / Recurring saving / Create\"\n"
                    + "          }\n"
                    + "        ],\n"
                    + "        \"availableGuardian\": false,\n"
                    + "        \"averageValueOfCost\": {\n"
                    + "          \"amount\": 302.9793,\n"
                    + "          \"amountFormatted\": \"302,98\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"account\": \"333444555\",\n"
                    + "        \"accountFormatted\": \"333 444 555\",\n"
                    + "        \"fundBelongingType\": \"GUARDIAN\",\n"
                    + "        \"holdingId\": 2,\n"
                    + "        \"holdingUnits\": 29.705,\n"
                    + "        \"holdingUnitsFormatted\": \"29,7050\",\n"
                    + "        \"isin\": \"LU0417597712\",\n"
                    + "        \"marketValueFormatted\": \"17 999,44\",\n"
                    + "        \"marketValueCurrency\": \"SEK\",\n"
                    + "        \"openForPurchase\": true,\n"
                    + "        \"openForSell\": true,\n"
                    + "        \"price\": {\n"
                    + "          \"amount\": 605.94,\n"
                    + "          \"amountFormatted\": \"605,94\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"purchaseValue\": {\n"
                    + "          \"amount\": 9000.0,\n"
                    + "          \"amountFormatted\": \"9 000,00\",\n"
                    + "          \"unit\": \"SEK\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"totalChange\": {\n"
                    + "          \"percentage\": 99.9938,\n"
                    + "          \"percentageFormatted\": \"99,99\",\n"
                    + "          \"amountFormatted\": \"8 999,44\",\n"
                    + "          \"changeDirection\": \"POSITIVE\",\n"
                    + "          \"currency\": \"SEK\"\n"
                    + "        },\n"
                    + "        \"recurringSavingsSummaryText\": \"\"\n"
                    + "      },\n"
                    + "      \"recurringSavingsDetailList\": [\n"
                    + "\n"
                    + "      ],\n"
                    + "      \"fundUntreatedTransactionList\": [\n"
                    + "\n"
                    + "      ]\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"minor\": false\n"
                    + "}";

    @Test
    public void testFundSubAccounts() {
        CustodyAccount custodyAccount =
                SerializationUtils.deserializeFromString(
                        CUSTODY_ACCOUNT_JSON, CustodyAccount.class);
        FundHoldingsUser response =
                SerializationUtils.deserializeFromString(
                        USER_FUND_HOLDINGS_JSON, FundHoldingsUser.class);
        final InvestmentAccount investmentAccount = response.toAccount(custodyAccount);

        assertNotNull(investmentAccount.getPayload());
        final Map<String, String> fundAccountNumbers =
                SerializationUtils.deserializeFromString(
                        investmentAccount.getPayload().get(AccountPayloadKeys.FUND_ACCOUNT_NUMBER),
                        TypeReferences.MAP_OF_STRING_STRING);
        assertEquals(3, fundAccountNumbers.size());
        assertEquals("111222333", fundAccountNumbers.get("SE0001466368"));
        assertEquals("222333444", fundAccountNumbers.get("SE0000356065"));
        assertEquals("333444555", fundAccountNumbers.get("LU0417597712"));
    }
}
