load("//tools/bzl:junit.bzl", "junit_test")

java_library(
    name = "connectivity_errors",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@tink_backend//src/libraries/connectivity_errors/proto:java_proto",
    ],
)
