java_library(
    name = "simple-http-server",
    visibility = ["//visibility:public"],
    exports = [
        "@tink_backend_shared_libraries//libraries/simple-http-server:simple-http-server",
    ],
)

java_library(
    name = "health-check-handler",
    visibility = ["//visibility:public"],
    exports = [
        "@tink_backend_shared_libraries//libraries/health-check-handler:health-check-handler",
    ],
)


