load("@rules_codeowners//tools:codeowners.bzl", "codeowners")

codeowners(
    name = "libraries_default_owners",
    teams = [
        "@tink-ab/aggregation-agent-platform-maintainer",
    ],
    visibility = ["//:__pkg__"],
)
