java_library(
    name = "v62",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "//src/libraries/date",
        "//src/libraries/i18n",
        "//src/libraries/identity_data",
        "//src/libraries/strings",
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:com_fasterxml_jackson_core_jackson_core",
        "//third_party:com_google_guava_guava",
        "//third_party:com_sun_jersey_jersey_core",
        "//third_party:org_slf4j_slf4j_api",
    ],
)
