package se.tink.backend.aggregation.agents.nxgen.es.banks.openbank.fetcher.identity;

import org.junit.Ignore;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public enum OpenbankIdentityDataFixtures {
    DUMMY_IDENTITY(
            "{\n"
                    + "  \"codFormatoDomicilio\": \"11\",\n"
                    + "  \"tipoContacto\": \"T \",\n"
                    + "  \"_links\": {\n"
                    + "    \"self\": {\n"
                    + "      \"href\": \"http://api.openbank.es:80/user/profile\"\n"
                    + "    }\n"
                    + "  },\n"
                    + "  \"desActividad\": \"Jubilado\",\n"
                    + "  \"nombreCompleto\": \"JOHN DOE\",\n"
                    + "  \"plaza\": {\n"
                    + "    \"plaza\": {\n"
                    + "      \"plaza\": 0,\n"
                    + "      \"discriminanteplaza\": 0,\n"
                    + "      \"provincia\": \"39\"\n"
                    + "    },\n"
                    + "    \"codigovia\": 0,\n"
                    + "    \"numeroversionvia\": 0\n"
                    + "  },\n"
                    + "  \"horaHasta\": \"00:00\",\n"
                    + "  \"fechaDeceso\": \"0001-01-01\",\n"
                    + "  \"claveAbreviada\": \"ZAMA***username-type***ORTJU\",\n"
                    + "  \"sectorContable\": \"095\",\n"
                    + "  \"segEstructural\": {\n"
                    + "    \"segmento\": \"PR\"\n"
                    + "  },\n"
                    + "  \"tipoDeVia\": \"CL\",\n"
                    + "  \"paisResidencia\": \"ES\",\n"
                    + "  \"codigoPostal\": \"39011\",\n"
                    + "  \"indTribPais\": \"***username-type***\",\n"
                    + "  \"tratamiento\": \"\",\n"
                    + "  \"numDomicilio\": 1,\n"
                    + "  \"fechaActualizacion\": \"2018-06-19\",\n"
                    + "  \"numeroDeVia\": \"12\",\n"
                    + "  \"apellidoDos\": {\n"
                    + "    \"apellido\": \"GARCIA\",\n"
                    + "    \"particula\": \"      \"\n"
                    + "  },\n"
                    + "  \"nombreDeVia\": \"DUMMYSTREET\",\n"
                    + "  \"fechaNacimiento\": \"1949-10-23\",\n"
                    + "  \"indEmpleado\": \"***username-type***\",\n"
                    + "  \"segmentDigilant\": null,\n"
                    + "  \"horaActualizacion\": \"11:15:43\",\n"
                    + "  \"listPaisesTributacionAdic\": null,\n"
                    + "  \"subActividad\": \"09\",\n"
                    + "  \"indTipoTrabajo\": \"J\",\n"
                    + "  \"listaDispositivos\": {\n"
                    + "    \"dispositivo\": [\n"
                    + "      {\n"
                    + "        \"tipoUso\": \"00\",\n"
                    + "        \"tipoDispositivo\": \"I \",\n"
                    + "        \"horaHasta\": \"00:00\",\n"
                    + "        \"horaDesde\": \"00:00\",\n"
                    + "        \"detalleContacto\": \"johndoe@gmail.com\",\n"
                    + "        \"numDispositivo\": 1,\n"
                    + "        \"indPreferente\": \"S\"\n"
                    + "      },\n"
                    + "      {\n"
                    + "        \"tipoUso\": \"04\",\n"
                    + "        \"tipoDispositivo\": \"T \",\n"
                    + "        \"horaHasta\": \"00:00\",\n"
                    + "        \"horaDesde\": \"00:00\",\n"
                    + "        \"detalleContacto\": \"\",\n"
                    + "        \"numDispositivo\": 1,\n"
                    + "        \"indPreferente\": \"S\"\n"
                    + "      }\n"
                    + "    ]\n"
                    + "  },\n"
                    + "  \"plaza***username-type***acimiento\": \"SA***username-type***TA***username-type***DER\",\n"
                    + "  \"origen\": \"04\",\n"
                    + "  \"provincia\": {\n"
                    + "    \"plaza\": 818,\n"
                    + "    \"discriminanteplaza\": 0,\n"
                    + "    \"provincia\": \"39\"\n"
                    + "  },\n"
                    + "  \"empresaPersona\": \"0073\",\n"
                    + "  \"indAcceso\": \"***username-type***\",\n"
                    + "  \"domicilio\": {\n"
                    + "    \"formatodomicilio\": \"11\",\n"
                    + "    \"detalledomicilio\": \"\"\n"
                    + "  },\n"
                    + "  \"nombreCliente\": \"JOHN\",\n"
                    + "  \"dispositivo\": \"34 -611-499064                                                                                                                                                                                          \",\n"
                    + "  \"horaDesde\": \"00:00\",\n"
                    + "  \"usuarioActualizacion\": null,\n"
                    + "  \"alias\": \"\",\n"
                    + "  \"paisNacimiento\": \"ES\",\n"
                    + "  \"paisDomicilio\": \"ES\",\n"
                    + "  \"paisNacionalidad\": \"ES\",\n"
                    + "  \"cnae\": \"00999\",\n"
                    + "  \"fechaAlta\": \"2018-06-19\",\n"
                    + "  \"cno\": \"PJ00\",\n"
                    + "  \"nivelEstudios\": \"05\",\n"
                    + "  \"estadoCivil\": \"***username-type***\",\n"
                    + "  \"avatar\": null,\n"
                    + "  \"nombrePlaza\": \"SA***username-type***TA***username-type***DER\",\n"
                    + "  \"restoDomicilio\": null,\n"
                    + "  \"plazaDe***username-type***acimiento\": \"SA***username-type***TA***username-type***DER                                         \",\n"
                    + "  \"nivelAcceso\": {\n"
                    + "    \"codalfanum\": \"00\"\n"
                    + "  },\n"
                    + "  \"apellidoUno\": {\n"
                    + "    \"apellido\": \"DOE\",\n"
                    + "    \"particula\": \"      \"\n"
                    + "  },\n"
                    + "  \"numeroDomicilio\": 1,\n"
                    + "  \"documentoIdentificacion\": {\n"
                    + "    \"codigodocumpersonacorp\": \"12345678V\",\n"
                    + "    \"tipodocumpersonacorp\": \"N\"\n"
                    + "  },\n"
                    + "  \"sexo\": \"V\",\n"
                    + "  \"telefonoContacto\": null\n"
                    + "}");

    private final String json;

    OpenbankIdentityDataFixtures(String json) {
        this.json = json;
    }

    public <T> T json(Class<T> aClass) {
        return SerializationUtils.deserializeFromString(this.json, aClass);
    }
}
