baseUrl-example: |2
    "https://xs2a.db.com/ais/DE/PFB"

psuIpAddress-description: |2
    This is the corresponding HTTP request IP Address between PSU and TPP. If not available, the TPP will use the
    IP Address used by the TPP when submitting the requests.

psuIpAddress-example: |2
    "0.0.0.0"

psuIdType-description: |2
    In case a PSU-ID allows more than one kind of data item – e.g. IBAN, Name, email address – to identify a PSU,
    the PSU-ID-Type specifies the type of used data item, hence, whether it’s a name, an IBAN or an email address.

psuIdType-example: |2
    "DE_ONLB_DB"
