
package se.tink.backend.aggregation.agents.creditcards.rikskortet.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobileWS_v2Soap", targetNamespace = "http://edenred.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileWSV2Soap {


    /**
     * 
     * @param distance
     * @param longitude
     * @param latitude
     * @return
     *     returns se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.ArrayOfRestaurantInfo
     */
    @WebMethod(operationName = "GetRestaurants", action = "http://edenred.se/GetRestaurants")
    @WebResult(name = "GetRestaurantsResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "GetRestaurants", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetRestaurants")
    @ResponseWrapper(localName = "GetRestaurantsResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetRestaurantsResponse")
    public ArrayOfRestaurantInfo getRestaurants(
        @WebParam(name = "latitude", targetNamespace = "http://edenred.se/")
        long latitude,
        @WebParam(name = "longitude", targetNamespace = "http://edenred.se/")
        long longitude,
        @WebParam(name = "distance", targetNamespace = "http://edenred.se/")
        long distance);

    /**
     * 
     * @param distance
     * @param longitude
     * @param latitude
     * @return
     *     returns se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.RestaurantInfo
     */
    @WebMethod(operationName = "GetRandomRestaurant", action = "http://edenred.se/GetRandomRestaurant")
    @WebResult(name = "GetRandomRestaurantResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "GetRandomRestaurant", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetRandomRestaurant")
    @ResponseWrapper(localName = "GetRandomRestaurantResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetRandomRestaurantResponse")
    public RestaurantInfo getRandomRestaurant(
        @WebParam(name = "latitude", targetNamespace = "http://edenred.se/")
        long latitude,
        @WebParam(name = "longitude", targetNamespace = "http://edenred.se/")
        long longitude,
        @WebParam(name = "distance", targetNamespace = "http://edenred.se/")
        long distance);

    /**
     * 
     * @param login
     * @param longitude
     * @param latitude
     * @param password
     * @param restaurantId
     * @return
     *     returns se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.RestaurantDetails
     */
    @WebMethod(operationName = "GetRestaurantDetails", action = "http://edenred.se/GetRestaurantDetails")
    @WebResult(name = "GetRestaurantDetailsResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "GetRestaurantDetails", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetRestaurantDetails")
    @ResponseWrapper(localName = "GetRestaurantDetailsResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetRestaurantDetailsResponse")
    public RestaurantDetails getRestaurantDetails(
        @WebParam(name = "restaurantId", targetNamespace = "http://edenred.se/")
        int restaurantId,
        @WebParam(name = "latitude", targetNamespace = "http://edenred.se/")
        long latitude,
        @WebParam(name = "longitude", targetNamespace = "http://edenred.se/")
        long longitude,
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password);

    /**
     * 
     * @param distance
     * @param longitude
     * @param latitude
     * @return
     *     returns se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.ArrayOfOfferDetails
     */
    @WebMethod(operationName = "GetOffers", action = "http://edenred.se/GetOffers")
    @WebResult(name = "GetOffersResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "GetOffers", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetOffers")
    @ResponseWrapper(localName = "GetOffersResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetOffersResponse")
    public ArrayOfOfferDetails getOffers(
        @WebParam(name = "latitude", targetNamespace = "http://edenred.se/")
        long latitude,
        @WebParam(name = "longitude", targetNamespace = "http://edenred.se/")
        long longitude,
        @WebParam(name = "distance", targetNamespace = "http://edenred.se/")
        long distance);

    /**
     * 
     * @param login
     * @param password
     * @param offerId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UseOffer", action = "http://edenred.se/UseOffer")
    @WebResult(name = "UseOfferResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "UseOffer", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.UseOffer")
    @ResponseWrapper(localName = "UseOfferResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.UseOfferResponse")
    public boolean useOffer(
        @WebParam(name = "offerId", targetNamespace = "http://edenred.se/")
        int offerId,
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password);

    /**
     * 
     * @param login
     * @param password
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "DisableCard", action = "http://edenred.se/DisableCard")
    @WebResult(name = "DisableCardResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "DisableCard", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.DisableCard")
    @ResponseWrapper(localName = "DisableCardResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.DisableCardResponse")
    public boolean disableCard(
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password);

    /**
     * 
     * @param login
     * @param password
     * @return
     *     returns se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.AccountDetails
     */
    @WebMethod(operationName = "GetAccountDetails", action = "http://edenred.se/GetAccountDetails")
    @WebResult(name = "GetAccountDetailsResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "GetAccountDetails", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetAccountDetails")
    @ResponseWrapper(localName = "GetAccountDetailsResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetAccountDetailsResponse")
    public AccountDetails getAccountDetails(
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password);

    /**
     * 
     * @param login
     * @param password
     * @return
     *     returns se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.Transaction
     */
    @WebMethod(operationName = "GetTransactions", action = "http://edenred.se/GetTransactions")
    @WebResult(name = "GetTransactionsResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "GetTransactions", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetTransactions")
    @ResponseWrapper(localName = "GetTransactionsResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetTransactionsResponse")
    public Transaction getTransactions(
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password);

    /**
     * 
     * @param login
     * @param longitude
     * @param latitude
     * @param password
     * @return
     *     returns se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.ArrayOfRestaurantInfo
     */
    @WebMethod(operationName = "GetFavourites", action = "http://edenred.se/GetFavourites")
    @WebResult(name = "GetFavouritesResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "GetFavourites", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetFavourites")
    @ResponseWrapper(localName = "GetFavouritesResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.GetFavouritesResponse")
    public ArrayOfRestaurantInfo getFavourites(
        @WebParam(name = "latitude", targetNamespace = "http://edenred.se/")
        long latitude,
        @WebParam(name = "longitude", targetNamespace = "http://edenred.se/")
        long longitude,
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password);

    /**
     * 
     * @param login
     * @param password
     * @param restaurantId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "PutFavourite", action = "http://edenred.se/PutFavourite")
    @WebResult(name = "PutFavouriteResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "PutFavourite", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.PutFavourite")
    @ResponseWrapper(localName = "PutFavouriteResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.PutFavouriteResponse")
    public boolean putFavourite(
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password,
        @WebParam(name = "restaurantId", targetNamespace = "http://edenred.se/")
        int restaurantId);

    /**
     * 
     * @param login
     * @param password
     * @param restaurantId
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "RemoveFavourite", action = "http://edenred.se/RemoveFavourite")
    @WebResult(name = "RemoveFavouriteResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "RemoveFavourite", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.RemoveFavourite")
    @ResponseWrapper(localName = "RemoveFavouriteResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.RemoveFavouriteResponse")
    public boolean removeFavourite(
        @WebParam(name = "login", targetNamespace = "http://edenred.se/")
        String login,
        @WebParam(name = "password", targetNamespace = "http://edenred.se/")
        String password,
        @WebParam(name = "restaurantId", targetNamespace = "http://edenred.se/")
        int restaurantId);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "TimeoutTest", action = "http://edenred.se/TimeoutTest")
    @WebResult(name = "TimeoutTestResult", targetNamespace = "http://edenred.se/")
    @RequestWrapper(localName = "TimeoutTest", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.TimeoutTest")
    @ResponseWrapper(localName = "TimeoutTestResponse", targetNamespace = "http://edenred.se/", className = "se.tink.backend.aggregation.agents.creditcards.rikskortet.soap.TimeoutTestResponse")
    public boolean timeoutTest();

}
