load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "source_info",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:lombok_libs",
    ],
)
