load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "source_info",
    srcs = glob(["*.java"]),
    extdeps = [
        "//third_party:lombok_libs",
    ],
    visibility = ["//visibility:public"],
)
