keyId-description: |2
  keyId must be formatted as keyId="SN=XXX,CA=YYY" where XXX is the serial number of the signing certificate in hexadecimal encoding and YYY is the ful Distinguished Name of the Certificate Authority having certificate

keyId-example: |2
  "SN=6AEB4444FBAAD267,CA=O=PSDNO-FSA-ABCA,L=Trondheim,C=NO\"

certificate-description: |2
  The certificate used for signing the request in base64 encoding.

certificate-example: |2
  "MIFFTzCCAzegAkIBAgMJANnQVDLqktJUMA0GCS....8WLZOX3YxNoH4k=="

tppId-description: |2
  "TPP identifier"

tppId-example: |2
  "PSDNO-FSA-ABCA"
