load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "agent",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/i18n",
    ],
)
