package se.tink.backend.aggregation.agents.nxgen.se.banks.swedbank.loan;

import org.junit.Ignore;

@Ignore
public class SwedBankSELoansFetcherTestData {
    public static final String ENGAGEMENT_OVERVIEW =
            "{\n"
                    + "  \"transactionAccounts\": [\n"
                    + "    {\n"
                    + "      \"selectedForQuickbalance\": false,\n"
                    + "      \"links\": {\n"
                    + "        \"next\": {\n"
                    + "          \"method\": \"GET\",\n"
                    + "          \"uri\": \"/v5/engagement/transactions/9999999999999999999999999999999999\"\n"
                    + "        }\n"
                    + "      },\n"
                    + "      \"name\": \"Servicekonto\",\n"
                    + "      \"priority\": \"2\",\n"
                    + "      \"id\": \"9999999999999999999999999999999999\",\n"
                    + "      \"currency\": \"SEK\",\n"
                    + "      \"details\": {\n"
                    + "        \"links\": {\n"
                    + "          \"next\": {\n"
                    + "            \"method\": \"GET\",\n"
                    + "            \"uri\": \"/v5/engagement/account/9999999999999999999999999999999999\"\n"
                    + "          }\n"
                    + "        }\n"
                    + "      },\n"
                    + "      \"balance\": \"12 599,17\",\n"
                    + "      \"accountNumber\": \"4 701 392-9\",\n"
                    + "      \"clearingNumber\": \"9999-9\",\n"
                    + "      \"fullyFormattedNumber\": \"9999-9,4 701 392-9\",\n"
                    + "      \"originalName\": \"Servicekonto\",\n"
                    + "      \"availableForFavouriteAccount\": true,\n"
                    + "      \"availableForPriorityAccount\": true\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"transactionDisposalAccounts\": [],\n"
                    + "  \"loanAccounts\": [],\n"
                    + "  \"savingAccounts\": [],\n"
                    + "  \"cardAccounts\": [],\n"
                    + "  \"supplementaryCardAccounts\": [],\n"
                    + "  \"accessToHSB\": false,\n"
                    + "  \"showCreditCardLink\": true,\n"
                    + "  \"errorFetchingCreditCards\": false,\n"
                    + "  \"debitCards\": [],\n"
                    + "  \"showCreditCardIncreaseLimitLink\": true,\n"
                    + "  \"eligibleForOverdraftLimit\": true\n"
                    + "}";
    public static final String MAMBERSHIP_CONSUMTION_LOAN_DETAILS =
            "{\n"
                    + "  \"loanDetail\": {\n"
                    + "    \"type\": \"KRF\",\n"
                    + "    \"interestRate\": {\n"
                    + "      \"current\": \"6,666 %\"\n"
                    + "    },\n"
                    + "    \"amortizationOnDueDate\": {\n"
                    + "      \"currencyCode\": \"SEK\",\n"
                    + "      \"amount\": \"1 000,00\"\n"
                    + "    },\n"
                    + "    \"amortizationPlan\": \"Rak\",\n"
                    + "    \"paymentIntervalAmortization\": \"Månadsvis\",\n"
                    + "    \"paymentIntervalInterest\": \"Månadsvis\",\n"
                    + "    \"collaterals\": [],\n"
                    + "    \"borrowers\": [\n"
                    + "      {\n"
                    + "        \"name\": \"Loan Taker\",\n"
                    + "        \"customerNumber\": \"66666666-6666\"\n"
                    + "      },\n"
                    + "      {\n"
                    + "        \"name\": \"Loan Taker 2\",\n"
                    + "        \"customerNumber\": \"77777777-7777\"\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"showFutureLoanPayments\": true,\n"
                    + "    \"showHistoricalPayments\": true\n"
                    + "  },\n"
                    + "  \"upcomingInvoice\": {\n"
                    + "    \"totalAmount\": {\n"
                    + "      \"currencyCode\": \"SEK\",\n"
                    + "      \"amount\": \"2 222,00\"\n"
                    + "    },\n"
                    + "    \"dueDate\": \"2017-09-30\",\n"
                    + "    \"expenses\": [\n"
                    + "      {\n"
                    + "        \"description\": \"Amorteringsbelopprivatep\",\n"
                    + "        \"amount\": {\n"
                    + "          \"currencyCode\": \"SEK\",\n"
                    + "          \"amount\": \"1 111,00\"\n"
                    + "        }\n"
                    + "      },\n"
                    + "      {\n"
                    + "        \"description\": \"Räntebelopp\",\n"
                    + "        \"amount\": {\n"
                    + "          \"currencyCode\": \"SEK\",\n"
                    + "          \"amount\": \"333,00\"\n"
                    + "        }\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"remark\": \"Aviserad\"\n"
                    + "  },\n"
                    + "  \"links\": {\n"
                    + "    \"next\": {\n"
                    + "      \"method\": \"GET\",\n"
                    + "      \"uri\": \"/v5/lending/loan/MEMBERSHIPOVERVIEW/payment\"\n"
                    + "    }\n"
                    + "  },\n"
                    + "  \"loan\": {\n"
                    + "    \"name\": \"Medlemslån SACO\",\n"
                    + "    \"account\": {\n"
                    + "      \"name\": \"Medlemslån SACO\",\n"
                    + "      \"accountNumber\": \"111 111 111-1\",\n"
                    + "      \"clearingNumber\": \"2222-2\",\n"
                    + "      \"fullyFormattedNumber\": \"2222-2,111 111 111-1\"\n"
                    + "    },\n"
                    + "    \"accountForPayment\": {\n"
                    + "      \"name\": \"Transaktionskonto\",\n"
                    + "      \"accountNumber\": \"333 333 333-3\",\n"
                    + "      \"clearingNumber\": \"2222-2\",\n"
                    + "      \"fullyFormattedNumber\": \"2222-2,333 333 333-3\"\n"
                    + "    }\n"
                    + "  },\n"
                    + "  \"loanLender\": \"Swedbank AB (publ)\",\n"
                    + "  \"interestSpecifications\": [\n"
                    + "    {\n"
                    + "      \"interest\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"888,80\"\n"
                    + "      },\n"
                    + "      \"amount\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"77 777,00\"\n"
                    + "      },\n"
                    + "      \"interestRate\": \"6,666 %\",\n"
                    + "      \"periodDateFrom\": \"2017-09-01\",\n"
                    + "      \"periodDateTo\": \"2017-09-30\"\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"debt\": {\n"
                    + "    \"currencyCode\": \"SEK\",\n"
                    + "    \"amount\": \"-99 999,00\"\n"
                    + "  }\n"
                    + "}";
    public static String CONSUMPTION_LOANS =
            "   {\n"
                    + "      \"name\": \"Medlemslån SACO\",\n"
                    + "      \"id\": \"MEMBERSHIPLOAN\",\n"
                    + "      \"account\": {\n"
                    + "        \"accountNumber\": \"555 555 555-5\",\n"
                    + "        \"clearingNumber\": \"7777-7\",\n"
                    + "        \"fullyFormattedNumber\": \"7777-7,555 555 555-5\"\n"
                    + "      },\n"
                    + "      \"interestRate\": \"9,999 %\",\n"
                    + "      \"debt\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"-88 888,00\"\n"
                    + "      },\n"
                    + "      \"links\": {\n"
                    + "        \"next\": {\n"
                    + "          \"method\": \"GET\",\n"
                    + "          \"uri\": \"/v5/lending/loan/MEMBERSHIPLOAN\"\n"
                    + "        }\n"
                    + "      }\n"
                    + "    }, {\n"
                    + "      \"name\": \"Privatlån Direkt\",\n"
                    + "      \"id\": \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\",\n"
                    + "      \"account\": {\n"
                    + "        \"accountNumber\": \"777 777 777-7\",\n"
                    + "        \"clearingNumber\": \"5555-5\",\n"
                    + "        \"fullyFormattedNumber\": \"5555-5,777 777 777-7\"\n"
                    + "      },\n"
                    + "      \"interestRate\": \"8,800 %\",\n"
                    + "      \"debt\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"-44 444,00\"\n"
                    + "      },\n"
                    + "      \"links\": {\n"
                    + "        \"next\": {\n"
                    + "          \"method\": \"GET\",\n"
                    + "          \"uri\": \"/v5/lending/loan/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\"\n"
                    + "        }\n"
                    + "      }\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"name\": \"Privatlån Direkt\",\n"
                    + "      \"id\": \"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\",\n"
                    + "      \"account\": {\n"
                    + "        \"accountNumber\": \"999 999 999-9\",\n"
                    + "        \"clearingNumber\": \"6666-6\",\n"
                    + "        \"fullyFormattedNumber\": \"6666-6,999 999 999-9\"\n"
                    + "      },\n"
                    + "      \"interestRate\": \"7,700 %\",\n"
                    + "      \"debt\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"-77 777,00\"\n"
                    + "      },\n"
                    + "      \"links\": {\n"
                    + "        \"next\": {\n"
                    + "          \"method\": \"GET\",\n"
                    + "          \"uri\": \"/v5/lending/loan/zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz\"\n"
                    + "        }\n"
                    + "      }\n"
                    + "    }";
    public static String CAR_LOAN =
            " {\n"
                    + "      \"name\": \"Billån\",\n"
                    + "      \"account\": {\n"
                    + "        \"name\": \"Billån\",\n"
                    + "        \"accountNumber\": \"1212121212\",\n"
                    + "        \"clearingNumber\": \"23232\",\n"
                    + "        \"fullyFormattedNumber\": \"2323121212\"\n"
                    + "      },\n"
                    + "      \"debt\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"-61 616,00\"\n"
                    + "      }\n"
                    + "    }";
    public static final String OVERVIEW_OF_LOANS =
            "{\n"
                    + "  \"collaterals\": [\n"
                    + "    {\n"
                    + "      \"description\": \"SOME ADDRESS\",\n"
                    + "      \"loans\": [\n"
                    + "        {\n"
                    + "          \"name\": \"BOLÅN\",\n"
                    + "          \"id\": \"ffffffffffffffffffffffffffffffffffffffff\",\n"
                    + "          \"account\": {\n"
                    + "            \"accountNumber\": \"444 444 444-7\",\n"
                    + "            \"clearingNumber\": \"8803-9\",\n"
                    + "            \"fullyFormattedNumber\": \"8803-9,444 444 444-7\"\n"
                    + "          },\n"
                    + "          \"interestRate\": \"1,111 %\",\n"
                    + "          \"debt\": {\n"
                    + "            \"currencyCode\": \"SEK\",\n"
                    + "            \"amount\": \"-333 000,00\"\n"
                    + "          },\n"
                    + "          \"links\": {\n"
                    + "            \"next\": {\n"
                    + "              \"method\": \"GET\",\n"
                    + "              \"uri\": \"/v5/lending/loan/MORTGAGE\"\n"
                    + "            }\n"
                    + "          }\n"
                    + "        },\n"
                    + "        {\n"
                    + "          \"name\": \"BOLÅN\",\n"
                    + "          \"id\": \"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\",\n"
                    + "          \"account\": {\n"
                    + "            \"accountNumber\": \"000 000 001-0\",\n"
                    + "            \"clearingNumber\": \"9999-9\",\n"
                    + "            \"fullyFormattedNumber\": \"9999-9,000 000 001 0\"\n"
                    + "          },\n"
                    + "          \"interestRate\": \"1,230 %\",\n"
                    + "          \"debt\": {\n"
                    + "            \"currencyCode\": \"SEK\",\n"
                    + "            \"amount\": \"-456 789,00\"\n"
                    + "          },\n"
                    + "          \"links\": {\n"
                    + "            \"next\": {\n"
                    + "              \"method\": \"GET\",\n"
                    + "              \"uri\": \"/v5/lending/loan/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\"\n"
                    + "            }\n"
                    + "          }\n"
                    + "        },\n"
                    + "        {\n"
                    + "          \"name\": \"BOLÅN\",\n"
                    + "          \"id\": \"cccccccccccccccccccccccccccccccccccccccc\",\n"
                    + "          \"account\": {\n"
                    + "            \"accountNumber\": \"676 767 676-7\",\n"
                    + "            \"clearingNumber\": \"3333-9\",\n"
                    + "            \"fullyFormattedNumber\": \"3333-9,676 767 676-7\"\n"
                    + "          },\n"
                    + "          \"interestRate\": \"5,555 %\",\n"
                    + "          \"debt\": {\n"
                    + "            \"currencyCode\": \"SEK\",\n"
                    + "            \"amount\": \"-321 500,00\"\n"
                    + "          },\n"
                    + "          \"links\": {\n"
                    + "            \"next\": {\n"
                    + "              \"method\": \"GET\",\n"
                    + "              \"uri\": \"/v5/lending/loan/cccccccccccccccccccccccccccccccccccccccc\"\n"
                    + "            }\n"
                    + "          }\n"
                    + "        },\n"
                    + "        {\n"
                    + "          \"name\": \"BOLÅN\",\n"
                    + "          \"id\": \"dddddddddddddddddddddddddddddddddddddddd\",\n"
                    + "          \"account\": {\n"
                    + "            \"accountNumber\": \"123 123 123-1\",\n"
                    + "            \"clearingNumber\": \"8899-9\",\n"
                    + "            \"fullyFormattedNumber\": \"8899-9,123 123 123-1\"\n"
                    + "          },\n"
                    + "          \"interestRate\": \"0,010 %\",\n"
                    + "          \"debt\": {\n"
                    + "            \"currencyCode\": \"SEK\",\n"
                    + "            \"amount\": \"-838 300,00\"\n"
                    + "          },\n"
                    + "          \"links\": {\n"
                    + "            \"next\": {\n"
                    + "              \"method\": \"GET\",\n"
                    + "              \"uri\": \"/v5/lending/loan/dddddddddddddddddddddddddddddddddddddddd\"\n"
                    + "            }\n"
                    + "          }\n"
                    + "        },\n"
                    + "        {\n"
                    + "          \"name\": \"BOLÅN\",\n"
                    + "          \"id\": \"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\",\n"
                    + "          \"account\": {\n"
                    + "            \"accountNumber\": \"546 546 546-7\",\n"
                    + "            \"clearingNumber\": \"2112-9\",\n"
                    + "            \"fullyFormattedNumber\": \"2112-9,546 546 546-7\"\n"
                    + "          },\n"
                    + "          \"interestRate\": \"1,430 %\",\n"
                    + "          \"debt\": {\n"
                    + "            \"currencyCode\": \"SEK\",\n"
                    + "            \"amount\": \"-350 117,00\"\n"
                    + "          },\n"
                    + "          \"links\": {\n"
                    + "            \"next\": {\n"
                    + "              \"method\": \"GET\",\n"
                    + "              \"uri\": \"/v5/lending/loan/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\"\n"
                    + "            }          }\n"
                    + "        }\n"
                    + "      ],\n"
                    + "      \"moreCollateralsExists\": false,\n"
                    + "      \"totalDebt\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"-1 234 567,00\"\n"
                    + "      }\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"ongoingLoans\": [],\n"
                    + "  \"mortgageLoanCommitments\": [\n"
                    + "    {\n"
                    + "      \"id\": \"ffffffffffffffffffffffffffffffffffffffff\",\n"
                    + "      \"links\": {\n"
                    + "        \"next\": {\n"
                    + "          \"method\": \"GET\",\n"
                    + "          \"uri\": \"/v5/lending/loan/mortgageloancommitment/ffffffffffffffffffffffffffffffffffffffff\"\n"
                    + "        }\n"
                    + "      }\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"mortgageCalculatorLink\": \"https://lana44.s14.tde.swedbank.net/app/lana/bolanelofte/oinloggad/guide?bankId=08999\",\n"
                    + "  \"carLoans\": [\n"
                    + CAR_LOAN
                    + "  ],\n"
                    + "  \"eligibleForCarLoan\": true,\n"
                    + "  \"consumptionLoans\": ["
                    + CONSUMPTION_LOANS
                    + "],\n"
                    + "  \"links\": {\n"
                    + "    \"next\": {\n"
                    + "      \"method\": \"GET\",\n"
                    + "      \"uri\": \"/v5/lending/mortgageLoan/overview\"\n"
                    + "    }\n"
                    + "  }\n"
                    + "}";
    public static final String MOTGAGE_DETAILS =
            "{\n"
                    + "  \"loanDetail\": {\n"
                    + "    \"type\": \"SPI\",\n"
                    + "    \"termsAndConditions\": {\n"
                    + "      \"changeType\": \"UPDATE\",\n"
                    + "      \"renewalTakesEffectDate\": \"2025-12-24\",\n"
                    + "      \"links\": {\n"
                    + "        \"next\": {\n"
                    + "          \"method\": \"GET\",\n"
                    + "          \"uri\": \"/v5/lending/mortgageLoan/ffffffffffffffffffffffffffffffffffffffff/renewal/baseinfo\"\n"
                    + "        }\n"
                    + "      }\n"
                    + "    },\n"
                    + "    \"interestRate\": {\n"
                    + "      \"current\": \"2,000 %\",\n"
                    + "      \"deviation\": \"-0,120\",\n"
                    + "      \"listPrice\": \"2,450 %\",\n"
                    + "      \"deviationExpireDate\": \"2022-12-24\"\n"
                    + "    },\n"
                    + "    \"amortizationOnDueDate\": {\n"
                    + "      \"currencyCode\": \"SEK\",\n"
                    + "      \"amount\": \"1 500,00\"\n"
                    + "    },\n"
                    + "    \"amortizationPlan\": \"Rak\",\n"
                    + "    \"paymentIntervalAmortization\": \"Månadsvis\",\n"
                    + "    \"paymentIntervalInterest\": \"Månadsvis\",\n"
                    + "    \"fixedInterestPeriod\": \"5 år\",\n"
                    + "    \"interestFixedToDate\": \"2025-12-24\",\n"
                    + "    \"remainingRepaymentTime\": 37,\n"
                    + "    \"collaterals\": [\n"
                    + "      {\n"
                    + "        \"type\": \"Bostadsrätt\",\n"
                    + "        \"description\": \"QUITE LONG ADDRESS LINE WITH TOWN\"\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"borrowers\": [\n"
                    + "      {\n"
                    + "        \"name\": \"Borrower Name 1\",\n"
                    + "        \"customerNumber\": \"19831212-0555\"\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"showFutureLoanPayments\": true,\n"
                    + "    \"showHistoricalPayments\": true\n"
                    + "  },\n"
                    + "  \"upcomingInvoice\": {\n"
                    + "    \"totalAmount\": {\n"
                    + "      \"currencyCode\": \"SEK\",\n"
                    + "      \"amount\": \"1 111,00\"\n"
                    + "    },\n"
                    + "    \"dueDate\": \"2016-07-23\",\n"
                    + "    \"expenses\": [\n"
                    + "      {\n"
                    + "        \"description\": \"Amorteringsbelopp\",\n"
                    + "        \"amount\": {\n"
                    + "          \"currencyCode\": \"SEK\",\n"
                    + "          \"amount\": \"1 500,00\"\n"
                    + "        }\n"
                    + "      },\n"
                    + "      {\n"
                    + "        \"description\": \"Räntebelopp\",\n"
                    + "        \"amount\": {\n"
                    + "          \"currencyCode\": \"SEK\",\n"
                    + "          \"amount\": \"1 000,00\"\n"
                    + "        }\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"remark\": \"Preliminär\"\n"
                    + "  },\n"
                    + "  \"links\": {\n"
                    + "    \"next\": {\n"
                    + "      \"method\": \"GET\",\n"
                    + "      \"uri\": \"/v5/lending/loan/ffffffffffffffffffffffffffffffffffffffff/payment\"\n"
                    + "    }\n"
                    + "  },\n"
                    + "  \"loan\": {\n"
                    + "    \"name\": \"Bolån\",\n"
                    + "    \"account\": {\n"
                    + "      \"name\": \"Bolån\",\n"
                    + "      \"accountNumber\": \"555 555 555-2\",\n"
                    + "      \"clearingNumber\": \"3333-9\",\n"
                    + "      \"fullyFormattedNumber\": \"3333-9,555 555 555-2\"\n"
                    + "    },\n"
                    + "    \"accountForPayment\": {\n"
                    + "      \"name\": \"Privatkonto\",\n"
                    + "      \"accountNumber\": \"987 987 987-4\",\n"
                    + "      \"clearingNumber\": \"4444-6\",\n"
                    + "      \"fullyFormattedNumber\": \"4444-6,987 987 987-4\"\n"
                    + "    }\n"
                    + "  },\n"
                    + "  \"loanLender\": \"SWEDBANK HYPOTEK AB (PUBL)\",\n"
                    + "  \"interestSpecifications\": [\n"
                    + "    {\n"
                    + "      \"interest\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"5 555,00\"\n"
                    + "      },\n"
                    + "      \"amount\": {\n"
                    + "        \"currencyCode\": \"SEK\",\n"
                    + "        \"amount\": \"999 999,00\"\n"
                    + "      },\n"
                    + "      \"interestRate\": \"1,222 %\",\n"
                    + "      \"periodDateFrom\": \"2016-07-23\",\n"
                    + "      \"periodDateTo\": \"2016-08-23\"\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"debt\": {\n"
                    + "    \"currencyCode\": \"SEK\",\n"
                    + "    \"amount\": \"-666 000,00\"\n"
                    + "  }\n"
                    + "}";
}
