#!/bin/bash

# This script wraps `bazel` and makes sure that it exits if tests fail.

set -e
TEMPFILE=$(mktemp)

set +e

# If bazelisk is installed, use it.
if [ -x "$(command -v bazelisk)" ]; then
    bazelisk $@ 2>&1 | tee "$TEMPFILE"
else
    bazel $@ 2>&1 | tee "$TEMPFILE"
fi

STATUS=$?
if [ $STATUS -ne 0 ]; then
    rm "$TEMPFILE"
    exit $STATUS
fi

! grep -qE 'ERROR|FAILED|NO STATUS' "$TEMPFILE"
STATUS=$?
rm "$TEMPFILE"
exit $STATUS
