kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-payments-it
  namespace: agents
spec:
  #-------------------------------------------------------------------------------------------------------------------
  # Temporary errors alerts
  #-------------------------------------------------------------------------------------------------------------------
  rules:
    - alert: payments_success_rates_lower_than_20_temp_errors_it
      expr: |
        # Temporary errors when executing payments outcomes greater than 80%
        (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.temporaryErrors }} }[1h]))
        / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) > 0.8
        # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h])) > 5
      for: {{ .Values.p1WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P1
        who: connectivity-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Payments success rate is below 20% due to temporary errors, actual % is <{ value | humanizePercentage }> for <{ $labels.className }> the last 1h. More than 5 attempts.
        tags: {{ .Values.tags }}

    - alert: payments_success_rates_between_40_and_20_due_to_temp_errors_it
      expr: |
        # Temporary errors when executing payments outcomes greater than 60%
        (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.temporaryErrors }} }[1h]))
        / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) > 0.6
        # Temporary errors when executing payments outcomes lower than 80%
        and (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.temporaryErrors }} }[1h]))
            / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) < 0.8
        # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h])) > 5
      for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P2
        who: connectivity-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Payments success rate is between 20% and 40% due to temporary errors, actual % is <{ value | humanizePercentage }> for <{ $labels.className }> the last 1h. More than 5 attempts.
        tags: {{ .Values.tags }}

    - alert: payments_success_rates_between_60_and_40_due_to_temp_errors_it
      expr: |
        # Temporary errors when executing payment outcomes greater than 40%
        (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.temporaryErrors }} }[1h]))
        / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) > 0.4
        # Temporary errors when executing payment outcomes lower than 60%
        and (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.temporaryErrors }} }[1h]))
            / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) < 0.6
        # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h])) > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P3
        who: connectivity-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Payments success rate is between 40% and 60% due to temporary errors, actual % is <{ value | humanizePercentage }> for <{ $labels.className }> the last 1h. More than 5 attempts.
        tags: {{ .Values.tags }}

        #-------------------------------------------------------------------------------------------------------------------
        # Bank side errors alerts
        #-------------------------------------------------------------------------------------------------------------------

    - alert: payments_success_rates_lower_than_20_due_to_bank_errors_it
      expr: |
        # Bank sider errors when executing payments outcomes greater than 80%
        (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.bankErrors }} }[1h]))
        / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) > 0.8
        # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h])) > 5
      for: {{ .Values.p1WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P1
        who: connectivity-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Payments success rate is below 80% due to bank side errors, actual    is <{ value | humanizePercentage }> for <{ $labels.className }> the last 1h. More than 5 attempts.
        tags: {{ .Values.tags }}

    - alert: payments_success_rates_between_20_and_80_due_to_bank_errors_it
      expr: |
        # Bank side errors when executing payment outcomes greater than 40%
        (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.bankErrors }} }[1h]))
        / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) > 0.4
        # Bank side errors when executing payment outcomes lower than 80%
        and (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.bankErrors }} }[1h]))
            / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) < 0.8
        # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h])) > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: {{ .Values.p3WaitTimeBeforeFiringAlert }}
        who: connectivity-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Payments success rate is between 40% and 80% due to bank side errors, actual % is <{ value | humanizePercentage }> for <{ $labels.className }> the last 1h. More than 5 attempts.
        tags: {{ .Values.tags }}

        #-------------------------------------------------------------------------------------------------------------------
        # Authentication errors and cancelled payments alerts
        #-------------------------------------------------------------------------------------------------------------------

    - alert: payments_success_rates_below_80_due_to_auth_errors_it
      expr: |
        # Auth errors when executing payments outcomes greater than 80%
        (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.cancelled }} }[1h]))
        / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) > 0.8
        # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h])) > 10
      for: {{ .Values.p1WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P1
        who: connectivity-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Payments success rate is below 80% due to auth errors actual % is <{ value | humanizePercentage }> for <{ $labels.className }> the last 1h. More than 10 attempts.
        tags: {{ .Values.tags }}

        #-------------------------------------------------------------------------------------------------------------------
        # All errors alerts
        #-------------------------------------------------------------------------------------------------------------------

    - alert: payments_success_rates_below_80
      expr: |
        # Various errors when executing payments outcomes greater than 80%
        (sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test", {{ .Values.allErrors }} }[1h]))
        / sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h]))) > 0.8
        # At least this many attempts
        and sum by(className) (increase(tink_agent_transfer_total{ market="IT", provider_type!="test" }[1h])) > 10
      for: {{ .Values.p1WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P1
        who: connectivity-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Payments success rate is below 80% due to various errors, actual % is <{ value | humanizePercentage }> for <{ $labels.className }> the last 1h. More than 10 attempts.
        tags: {{ .Values.tags }}
