load("//tools/bzl:junit.bzl", "junit_test")

junit_test(
    name = "qrcode",
    srcs = glob(["**/*.java"]),
    data = [
    ],
    tags = [
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/utils/qrcode",
        "//third_party:org_assertj_assertj_core",
    ],
)
