java_library(
    name = "cli_print_utils",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_google_guava_guava",
        "//third_party:com_google_http_client_google_http_client",
    ],
)
