//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.03.20 at 11:40:02 AM CET
//

@jakarta.xml.bind.annotation.XmlSchema(
        namespace = "urn:iso:std:iso:20022:tech:xsd:camt.052.001.02",
        elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.tink.backend.aggregation.agents.utils.camt.camt_052_001_02;
