java_library(
    name = "camt",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@aggregation//:com_sun_xml_ws_jaxws_rt",
        "@aggregation//:jakarta_xml_bind_jakarta_xml_bind_api",
        "@aggregation//:jakarta_xml_ws_jakarta_xml_ws_api",
    ],
)
