package se.tink.backend.core;

public enum FraudDetailsContentType {
    IDENTITY,
    ADDRESS,
    COMPANY_ENGAGEMENT,
    REAL_ESTATE_ENGAGEMENT,
    CREDITS,
    NON_PAYMENT,
    DOUBLE_CHARGE,
    LARGE_EXPENSE,
    SCORING,
    FREQUENT_ACCOUNT_ACTIVITY,
    LARGE_WITHDRAWAL,
    INCOME
}
