package se.tink.backend.core;

import java.io.Serializable;

import javax.persistence.IdClass;

@IdClass(SubscriptionPk.class)
public class SubscriptionPk implements Serializable {
    private static final long serialVersionUID = -3090221844117493661L;
    private SubscriptionType type;
    private String userId;

    public SubscriptionPk() {
    }

    public SubscriptionPk(String userId, SubscriptionType type) {
        this.setUserId(userId);
        this.setType(type);
    }

    // Auto-generated by Eclipse.
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        SubscriptionPk other = (SubscriptionPk) obj;
        if (type != other.type) {
            return false;
        }
        if (userId == null) {
            if (other.userId != null) {
                return false;
            }
        } else if (!userId.equals(other.userId)) {
            return false;
        }
        return true;
    }

    public SubscriptionType getType() {
        return type;
    }

    public String getUserId() {
        return userId;
    }

    // Auto-generated by Eclipse.
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((type == null) ? 0 : type.hashCode());
        result = prime * result + ((userId == null) ? 0 : userId.hashCode());
        return result;
    }

    public void setType(SubscriptionType type) {
        this.type = type;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

}
