package se.tink.backend.aggregation.agents.nxgen.be.openbanking.belfius.apiClient;

import org.junit.Ignore;

@Ignore
public class BelfiusApiClientData {

    static final String TRANSACTION_RESPONSE =
            "{\n"
                    + "    \"transactions\": {\n"
                    + "        \"booked\": [\n"
                    + "            {\n"
                    + "                \"transaction_ref\": \"090548887U406\",\n"
                    + "                \"transaction_seqnumber\": \"EUR001\",\n"
                    + "                \"counterparty_info\": \"Somecounterparty Person\",\n"
                    + "                \"communication\": \"JDB 511122\",\n"
                    + "                \"communication_type\": \"FREETEXT\",\n"
                    + "                \"remittance_info\": \"SEPA CREDIT TRANSFER from PSD2Company\",\n"
                    + "                \"counterparty_account\": \"BE39000000076000\",\n"
                    + "                \"amount\": 12.25,\n"
                    + "                \"currency\": \"EUR\",\n"
                    + "                \"execution_date\": \"2020-07-30\"\n"
                    + "            },\n"
                    + "            {\n"
                    + "                \"transaction_ref\": \"090548887U406\",\n"
                    + "                \"transaction_seqnumber\": \"EUR001\",\n"
                    + "                \"counterparty_info\": \"Somecounterparty Person\",\n"
                    + "                \"communication\": \"JDB 511122\",\n"
                    + "                \"communication_type\": \"FREETEXT\",\n"
                    + "                \"remittance_info\": \"SEPA CREDIT TRANSFER from PSD2Company\",\n"
                    + "                \"counterparty_account\": \"BE39000000076000\",\n"
                    + "                \"amount\": 12.25,\n"
                    + "                \"currency\": \"EUR\",\n"
                    + "                \"execution_date\": \"2020-07-30\"\n"
                    + "            },\n"
                    + "            {\n"
                    + "                \"transaction_ref\": \"090548887U406\",\n"
                    + "                \"transaction_seqnumber\": \"EUR001\",\n"
                    + "                \"counterparty_info\": \"Somecounterparty Person\",\n"
                    + "                \"communication\": \"JDB 511122\",\n"
                    + "                \"communication_type\": \"FREETEXT\",\n"
                    + "                \"remittance_info\": \"SEPA CREDIT TRANSFER from PSD2Company\",\n"
                    + "                \"counterparty_account\": \"BE39000000076000\",\n"
                    + "                \"amount\": 12.25,\n"
                    + "                \"currency\": \"EUR\",\n"
                    + "                \"execution_date\": \"2020-07-30\"\n"
                    + "            }\n"
                    + "        ],\n"
                    + "        \"next_page_key\": \"DUMMY_NEXT_PAGE_KEY\"\n"
                    + "    },\n"
                    + "    \"_links\": {\n"
                    + "        \"self\": {\n"
                    + "            \"href\": \"/accounts/f2533843-785d-4499-b92f-61711101feed/transactions\"\n"
                    + "        },\n"
                    + "        \"next\": {\n"
                    + "            \"href\": \"/accounts/f2533843-785d-4499-b92f-61711101feed/transactions?next=DUMMY_NEXT_PAGE_KEY\"\n"
                    + "        },\n"
                    + "        \"account\": {\n"
                    + "            \"href\": \"/accounts/f2533843-785d-4499-b92f-61711101feed\"\n"
                    + "        }\n"
                    + "    }\n"
                    + "}\n";
}
