load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "testclasses",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
        "//third_party:com_google_inject_guice",
    ],
)
