package se.tink.backend.common.application.field;

import com.google.common.collect.ImmutableMap;
import se.tink.libraries.i18n.LocalizableKey;
import se.tink.backend.core.enums.ApplicationFieldName;
import se.tink.libraries.application.ApplicationFieldOptionValues;

public class ApplicationFieldStrings {

    public static final ImmutableMap<String, LocalizableKey> FIELD_LABELS = ImmutableMap.<String, LocalizableKey>builder()
            .put(ApplicationFieldName.ASSESSED_VALUE, new LocalizableKey("Assessed value"))
            .put(ApplicationFieldName.ASSET_NAME, new LocalizableKey("Name of asset"))
            .put(ApplicationFieldName.ASSET_VALUE, new LocalizableKey("Value of asset"))
            .put(ApplicationFieldName.ALIMONY_AMOUNT_PER_MONTH, new LocalizableKey("Amount per month"))
            .put(ApplicationFieldName.MONTHLY_AMORTIZATION, new LocalizableKey("How much do you amortize per month?"))
            .put(ApplicationFieldName.BAILMENT, new LocalizableKey("Did you bail someone loan?"))
            .put(ApplicationFieldName.BAILMENT_AMOUNT, new LocalizableKey("Bail Amount"))
            .put(ApplicationFieldName.CADASTRAL, new LocalizableKey("Cadastral"))
            .put(ApplicationFieldName.CO_APPLICANT_ADDRESS, new LocalizableKey("Does your co-applicant live at the same address as you?"))
            .put(ApplicationFieldName.CO_APPLICANT_ALIMONY_AMOUNT, new LocalizableKey("Amount per month"))
            .put(ApplicationFieldName.CO_APPLICANT_CSN_LOAN, new LocalizableKey("Does you co-applicant have a csn loan?"))
            .put(ApplicationFieldName.CO_APPLICANT_PAYING_ALIMONY, new LocalizableKey("Is your co-applicant paying alimony?"))
            .put(ApplicationFieldName.CO_APPLICANT_POSTAL_CODE, new LocalizableKey("Postal code"))
            .put(ApplicationFieldName.CO_APPLICANT_RECEIVING_ALIMONY, new LocalizableKey("Does your co-applicant receive alimony for any children?"))
            .put(ApplicationFieldName.CO_APPLICANT_RECEIVING_ALIMONY_COUNT, new LocalizableKey("Number of children"))
            .put(ApplicationFieldName.CO_APPLICANT_TOWN, new LocalizableKey("Town"))
            .put(ApplicationFieldName.CO_APPLICANT_STREET_ADDRESS, new LocalizableKey("Street address"))
            .put(ApplicationFieldName.COLLECTOR_ACCOUNT_FOR_MONEY_WITHDRAWAL, new LocalizableKey("Account for money withdrawal"))
            .put(ApplicationFieldName.COLLECTOR_INITIAL_DEPOSIT, new LocalizableKey("How much are you planning to deposit when opening the account?"))
            .put(ApplicationFieldName.COLLECTOR_MONEY_WITHDRAWAL, new LocalizableKey("How often will you withdrawal money from the account?"))
            .put(ApplicationFieldName.COLLECTOR_SAVINGS_CONFIRMATION, new LocalizableKey("I confirm that I have read and accept the Collector Save Agreement and that I have received information about state-provided guarantee of deposits."))
            .put(ApplicationFieldName.COLLECTOR_SAVINGS_FREQUENCY, new LocalizableKey("How often will you deposit money to the account?"))
            .put(ApplicationFieldName.COLLECTOR_SAVINGS_PURPOSE, new LocalizableKey("What is the main purpose of your savings?"))
            .put(ApplicationFieldName.COLLECTOR_SAVINGS_SOURCES, new LocalizableKey("How will the money generally be deposited?"))
            .put(ApplicationFieldName.COLLECTOR_SAVINGS_SOURCES_REASON, new LocalizableKey("Where does the money that will be deposited into the account mainly come from?"))
            .put(ApplicationFieldName.COMPANY_NAME, new LocalizableKey("Company name"))
            .put(ApplicationFieldName.CSN_LOAN_AMOUNT, new LocalizableKey("Total CSN amount"))
            .put(ApplicationFieldName.CSN_MONTHLY_COST, new LocalizableKey("Monthly cost for student loan"))
            .put(ApplicationFieldName.CURRENT_LOANS, new LocalizableKey("Current loans"))
            .put(ApplicationFieldName.DEFAULT_POSTAL_CODE, new LocalizableKey("Postal code"))
            .put(ApplicationFieldName.DEFAULT_STREET_ADDRESS, new LocalizableKey("Street address"))
            .put(ApplicationFieldName.DEFAULT_TOWN, new LocalizableKey("Town"))
            .put(ApplicationFieldName.DEFERRED_AMOUNT, new LocalizableKey("Deferred amount"))
            .put(ApplicationFieldName.EMAIL, new LocalizableKey("Email"))
            .put(ApplicationFieldName.EMPLOYEE_SINCE, new LocalizableKey("Employee since (YYYY-MM)"))
            .put(ApplicationFieldName.PROFESSION, new LocalizableKey("Profession"))
            .put(ApplicationFieldName.SBAB_EMPLOYEE_SINCE, new LocalizableKey("Employee since (YYYY-MM)"))
            .put(ApplicationFieldName.EMPLOYER_NAME, new LocalizableKey("Employer name"))
            .put(ApplicationFieldName.EMPLOYER_OR_COMPANY_NAME, new LocalizableKey("Employer or Company name"))
            .put(ApplicationFieldName.EMPLOYMENT_TYPE, new LocalizableKey("What is your main occupation?"))
            .put(ApplicationFieldName.ESTIMATED_MARKET_VALUE, new LocalizableKey("Market value"))
            .put(ApplicationFieldName.FIRST_NAME, new LocalizableKey("First name"))
            .put(ApplicationFieldName.HAS_CO_APPLICANT, new LocalizableKey("Have you taken the loan together with someone else?"))
            .put(ApplicationFieldName.HAS_CSN_LOAN, new LocalizableKey("Do you have a student loan from CSN?"))
            .put(ApplicationFieldName.HAS_DEFERED_CAPITAL_GAINS_TAX, new LocalizableKey("Have you requested deferral of capital gains tax?"))
            .put(ApplicationFieldName.HOUSE_PURCHASE_PRICE, new LocalizableKey("How much did you purchase the house for?"))
            .put(ApplicationFieldName.HOUSEHOLD_ADULTS, new LocalizableKey("Is there another adult in the household?"))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_BAILMENT, new LocalizableKey("Have your co-applicant bailed someones loan?"))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_BAILMENT_AMOUNT, new LocalizableKey("Total bail amount"))
            .put(ApplicationFieldName.HOUSEHOLD_CHILDREN, new LocalizableKey("Are there any children in the household?"))
            .put(ApplicationFieldName.HOUSEHOLD_CHILDREN_COUNT, new LocalizableKey("Number of children"))
            .put(ApplicationFieldName.HOUSEHOLD_CHILDREN_ALIMONY_COUNT, new LocalizableKey("Number of children you get alimony for"))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_DEFERRAL_CAPITAL_GAIN_TAX, new LocalizableKey("Have your co-applicant requested deferral of capital gains tax?"))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_DEFERRAL_CAPITAL_GAIN_TAX_AMOUNT, new LocalizableKey("Total amount of deferral capital gain tax"))
            .put(ApplicationFieldName.APPLICANT_NUMBER_OF_CHILDREN_PAYING_ALIMONY_FOR, new LocalizableKey("Number of children"))
            .put(ApplicationFieldName.CO_APPLICANT_NUMBER_OF_CHILDREN_PAYING_ALIMONY_FOR, new LocalizableKey("Number of children"))
            .put(ApplicationFieldName.HOUSEHOLD_NUMBER_OF_CHILDREN_TO_RECEIVE_CHILD_BENEFIT_FOR, new LocalizableKey("Number of children you get child benefits from"))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_OTHER_LOANS, new LocalizableKey("Does your co-applicant have any other loans?"))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_OTHER_LOAN_AMOUNT, new LocalizableKey("Total amount of all loans"))
            .put(ApplicationFieldName.HOUSING_COMMUNITY_NAME, new LocalizableKey("Name of the housing community"))
            .put(ApplicationFieldName.LAST_NAME, new LocalizableKey("Last name"))
            .put(ApplicationFieldName.MUNICIPALITY, new LocalizableKey("Municipality"))
            .put(ApplicationFieldName.MONTHLY_OPERATING_COST, new LocalizableKey("Monthly operating cost"))
            .put(ApplicationFieldName.IS_PEP, new LocalizableKey("Are you, a family member or a close associate in a political exposed position?"))
            .put(ApplicationFieldName.LIVING_AREA, new LocalizableKey("Living area (m²)"))
            .put(ApplicationFieldName.LOAN_AMOUNT, new LocalizableKey("Loan debt / used credit"))
            .put(ApplicationFieldName.LOAN_LENDER, new LocalizableKey("Bank / credit institution"))
            .put(ApplicationFieldName.MONTHLY_HOUSING_COMMUNITY_FEE, new LocalizableKey("Monthly fee"))
            .put(ApplicationFieldName.MONTHLY_INCOME, new LocalizableKey("Monthly income"))
            .put(ApplicationFieldName.MORTGAGE_PRODUCT, new LocalizableKey("Move the loan directly"))
            .put(ApplicationFieldName.MORTGAGE_COMPARISONS, new LocalizableKey("Banks not connected"))
            .put(ApplicationFieldName.MORTGAGE_SECURITY_POSTAL_CODE, new LocalizableKey("Postal code"))
            .put(ApplicationFieldName.MORTGAGE_SECURITY_PROPERTY_TYPE, new LocalizableKey("Property type"))
            .put(ApplicationFieldName.MORTGAGE_SECURITY_STREET_ADDRESS, new LocalizableKey("Street address"))
            .put(ApplicationFieldName.MORTGAGE_SECURITY_TOWN, new LocalizableKey("Town"))
            .put(ApplicationFieldName.NAME, new LocalizableKey("Name"))
            .put(ApplicationFieldName.NUMBER_OF_ROOMS, new LocalizableKey("Number of rooms"))
            .put(ApplicationFieldName.ON_OWN_BEHALF, new LocalizableKey("Are you filling out the application on your own behalf?"))
            .put(ApplicationFieldName.OTHER_LOAN, new LocalizableKey("+ Add loan"))
            .put(ApplicationFieldName.OTHER_PROPERTY_APARTMENT_MARKET_VALUE, new LocalizableKey("Market value"))
            .put(ApplicationFieldName.OTHER_PROPERTY_APARTMENT_LOAN_AMOUNT, new LocalizableKey("Total loan amount"))
            .put(ApplicationFieldName.OTHER_PROPERTY_APARTMENT_MONTHLY_FEE, new LocalizableKey("Monthly fee"))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_ASSESSED_VALUE, new LocalizableKey("Assessed value"))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_GROUND_RENT, new LocalizableKey("Ground rent (quarterly)"))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_LABEL, new LocalizableKey("House label"))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_LOAN_AMOUNT, new LocalizableKey("Total loan amount"))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_MARKET_VALUE, new LocalizableKey("Market value"))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_MUNICIPALITY, new LocalizableKey("Municipality"))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_OPERATING_COST, new LocalizableKey("Operating cost"))
            .put(ApplicationFieldName.OTHER_PROPERTY_VACATION_HOUSE_ASSESSED_VALUE, new LocalizableKey("Assessed value"))
            .put(ApplicationFieldName.OTHER_PROPERTY_VACATION_HOUSE_MARKET_VALUE, new LocalizableKey("Market value"))
            .put(ApplicationFieldName.OTHER_PROPERTY_VACATION_HOUSE_LOAN_AMOUNT, new LocalizableKey("Total loan amount"))
            .put(ApplicationFieldName.OTHER_PROPERTY_TENANCY_MONTHLY_RENT, new LocalizableKey("Monthly rent"))
            .put(ApplicationFieldName.PAYING_ALIMONY, new LocalizableKey("Are you paying alimony?"))
            .put(ApplicationFieldName.PERSONAL_NUMBER, new LocalizableKey("Social security number (YYYYMMDDNNNN)"))
            .put(ApplicationFieldName.PHONE_NUMBER, new LocalizableKey("Phone number"))
            .put(ApplicationFieldName.POSTAL_CODE, new LocalizableKey("Postal code"))
            .put(ApplicationFieldName.RECEIVING_ALIMONY, new LocalizableKey("Do you have any children that you receive alimony for?"))
            .put(ApplicationFieldName.RECEIVING_ALIMONY_COUNT, new LocalizableKey("Number of children"))
            .put(ApplicationFieldName.RELATIONSHIP_STATUS, new LocalizableKey("Relationship status"))
            .put(ApplicationFieldName.RESIDENCE_PROPERTY_TYPE, new LocalizableKey("Residence property type"))
            .put(ApplicationFieldName.SAVINGS_PRODUCT, new LocalizableKey("Product"))
            .put(ApplicationFieldName.CITIZENSHIP_COUNTRY, new LocalizableKey("Add citizenship in other county"))
            .put(ApplicationFieldName.CITIZENSHIP_IN_OTHER_COUNTRY, new LocalizableKey("Do you have a citizenship in another country?"))
            .put(ApplicationFieldName.CITIZENSHIP_IN_YET_ANOTHER_COUNTRY, new LocalizableKey("Do you have citizenship in yet another country?"))
            .put(ApplicationFieldName.SALARY_IN_FOREIGN_CURRENCY, new LocalizableKey("Do you have an income in another currency than Swedish crowns?"))
            .put(ApplicationFieldName.SBAB_INITIAL_DEPOSIT, new LocalizableKey("What approximate amount is deposited in association to opening the account?"))
            .put(ApplicationFieldName.SBAB_MONEY_WITHDRAWAL, new LocalizableKey("How often will you withdrawal money from the account?"))
            .put(ApplicationFieldName.SBAB_PERSONS_SAVING, new LocalizableKey("Who will be depositing money?"))
            .put(ApplicationFieldName.SBAB_PERSONS_SAVING_OTHER_VALUE, new LocalizableKey("Who is someone else?"))
            .put(ApplicationFieldName.SBAB_PROPERTY_TYPE, new LocalizableKey("Do you have other properties?"))
            .put(ApplicationFieldName.SBAB_SAVINGS_AMOUNT_PER_MONTH, new LocalizableKey("What's the total amount that will be deposited per month?"))
            .put(ApplicationFieldName.SBAB_SAVINGS_CONFIRMATION, new LocalizableKey("I confirm that I have read and accept SBAB's Terms and Conditions and Terms and Conditions for savings accounts and thus received the information about the deposit insurance and information concerning the processing of personal data."))
            .put(ApplicationFieldName.SBAB_SAVINGS_FREQUENCY, new LocalizableKey("How often will deposits be made?"))
            .put(ApplicationFieldName.SBAB_SAVINGS_MONTHLY_INCOME, new LocalizableKey("What's your monthly income, before taxes?"))
            .put(ApplicationFieldName.SBAB_SAVINGS_PURPOSE, new LocalizableKey("What is the purpose of the savings account?"))
            .put(ApplicationFieldName.SBAB_SAVINGS_PURPOSE_OTHER_VALUE, new LocalizableKey("Specify purpose"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES, new LocalizableKey("How will money mainly be deposited?"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_MY_ACCOUNT_IN_SWEDISH_BANK, new LocalizableKey("From my account in a Swedish bank"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_MY_ACCOUNT_IN_SWEDISH_BANK_OTHER_VALUE, new LocalizableKey("Name of other bank"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_OTHER_WAY_VALUE, new LocalizableKey("Specify other way"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON, new LocalizableKey("Where does the money come from?"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_INDUSTRY, new LocalizableKey("Own business (e.g salary or dividend)"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_RESTAURANT_COMPANY_NAME, new LocalizableKey("Company name"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_RESTAURANT_COMPANY_REGISTRATION_NUMBER, new LocalizableKey("Registration number"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_PAYMENT_COMPANY_NAME, new LocalizableKey("Company name"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_PAYMENT_COMPANY_REGISTRATION_NUMBER, new LocalizableKey("Registration number"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_GAMING_COMPANY_NAME, new LocalizableKey("Company name"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_GAMING_COMPANY_REGISTRATION_NUMBER, new LocalizableKey("Registration number"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_HAIRDRESSER_COMPANY_NAME, new LocalizableKey("Company name"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_HAIRDRESSER_COMPANY_REGISTRATION_NUMBER, new LocalizableKey("Registration number"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_CONSTRUCTION_COMPANY_NAME, new LocalizableKey("Company name"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_CONSTRUCTION_COMPANY_REGISTRATION_NUMBER, new LocalizableKey("Registration number"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_WEAPON_COMPANY_NAME, new LocalizableKey("Company name"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_WEAPON_COMPANY_REGISTRATION_NUMBER, new LocalizableKey("Registration number"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OWN_BUSINESS_OTHER_VALUE, new LocalizableKey("Specify industry"))
            .put(ApplicationFieldName.SBAB_SAVINGS_SOURCES_REASON_OTHER_VALUE, new LocalizableKey("Specify source"))
            .put(ApplicationFieldName.SEB_TRANSFER_SAVINGS, new LocalizableKey("Do you have savings that you want to transfer to SEB?"))
            .put(ApplicationFieldName.SEB_TRANSFER_ORIGIN, new LocalizableKey("Where is the money that you plan on transfering originating from?"))
            .put(ApplicationFieldName.SEB_OTHER_SERVICES_INTEREST, new LocalizableKey("Are you interested in other services from SEB in addition to mortgages?"))
            .put(ApplicationFieldName.SEB_OTHER_SERVICES_OPTIONS, new LocalizableKey("What kind of services are you interested in?"))
            .put(ApplicationFieldName.SELF_EMPLOYED_SINCE, new LocalizableKey("Self-employed since (YYYY-MM)"))
            .put(ApplicationFieldName.TAXPAYER_IDENTIFICATION_NUMBER, new LocalizableKey("Taxpayer identification number"))
            .put(ApplicationFieldName.STREET_ADDRESS, new LocalizableKey("Street address"))
            .put(ApplicationFieldName.SWEDISH_CITIZEN, new LocalizableKey("Are you a Swedish citizen?"))
            .put(ApplicationFieldName.TAXABLE_COUNTRY, new LocalizableKey("Add taxable country"))
            .put(ApplicationFieldName.TAXABLE_IN_OTHER_COUNTRY, new LocalizableKey("Are you taxable in any other country?"))
            .put(ApplicationFieldName.TAXABLE_IN_SWEDEN, new LocalizableKey("Is Sweden your residence for tax purposes?"))
            .put(ApplicationFieldName.TAXABLE_IN_USA, new LocalizableKey("Are you taxable in USA?"))
            .put(ApplicationFieldName.TAXABLE_IN_YET_ANOTHER_COUNTRY, new LocalizableKey("Are you taxable in yet another country?"))
            .put(ApplicationFieldName.TAXPAYER_IDENTIFICATION_NUMBER_USA, new LocalizableKey("Taxpayer identification number"))
            .put(ApplicationFieldName.TAXPAYER_IDENTIFICATION_NUMBER_OTHER_COUNTRY, new LocalizableKey("Taxpayer identification number"))
            .put(ApplicationFieldName.TOWN, new LocalizableKey("Town"))
            .put(ApplicationFieldName.CONSTRUCTION_YEAR, new LocalizableKey("Year of construction"))
            .put(ApplicationFieldName.ADDITIONAL_AREA, new LocalizableKey("Additional area (m²)"))
            .put(ApplicationFieldName.PLOT_AREA, new LocalizableKey("Plot area (m²)"))
            .put(ApplicationFieldName.VALUATION_MONTHLY_HOUSING_COMMUNITY_FEE, new LocalizableKey("Monthly fee"))
            .put(ApplicationFieldName.VALUATION_MONTHLY_OPERATING_COST, new LocalizableKey("Monthly operating cost"))
            .put(ApplicationFieldName.DIRECT_DEBIT_CONFIRM, new LocalizableKey("I confirm that I have read and accepted the terms of service for direct debit."))
            .put(ApplicationFieldName.SIGNATURE, new LocalizableKey("Signature"))
            .put(ApplicationFieldName.HAS_AMORTIZATION_REQUIREMENT, new LocalizableKey("Was your mortgage granted, extended, or otherwise changed after the 1st of June 2016?"))
            .build();

    public static final ImmutableMap<String, LocalizableKey> FIELD_DESCRIPTIONS = ImmutableMap.<String, LocalizableKey>builder()
            .put(ApplicationFieldName.BAILMENT, new LocalizableKey("If you for example helped a family member with taking a loan."))
            .put(ApplicationFieldName.HAS_CO_APPLICANT, new LocalizableKey("For example, if you and your partner took the loan together."))
            .put(ApplicationFieldName.HAS_DEFERED_CAPITAL_GAINS_TAX, new LocalizableKey("If you have sold e.g. an apartment or house and deferred to pay the tax."))
            .put(ApplicationFieldName.HOUSEHOLD_ADULTS, new LocalizableKey("As a cohabitant who is not included in the loan."))
            .put(ApplicationFieldName.ON_OWN_BEHALF, new LocalizableKey("The question is asked for the control of the true principal, to ensure that you do not act on somebody else's behalf. Any potential co-applicant is not concerned."))
            .put(ApplicationFieldName.SALARY_IN_FOREIGN_CURRENCY, new LocalizableKey("We ask because changes in the exchange rate can affect your finances."))
            .put(ApplicationFieldName.SEB_TRANSFER_SAVINGS, new LocalizableKey("This is not a requirement and you do not need to make a decision now."))
            .put(ApplicationFieldName.SEB_OTHER_SERVICES_INTEREST, new LocalizableKey("This is not a requirement and you do not need to make a decision now."))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_BAILMENT, new LocalizableKey("If your co-applicant e.g. has helped a family member to take a loan."))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_DEFERRAL_CAPITAL_GAIN_TAX, new LocalizableKey("If your co-applicant e.g. has sold an apartment or a house and deferred paying capital gains tax."))
            .put(ApplicationFieldName.SEB_CO_APPLICANT_OTHER_LOANS, new LocalizableKey("Like second mortgage, blanco loans or used credit not already stated. Don't include mortgages on other properties, for example the vacation house."))
            .put(ApplicationFieldName.IS_PEP, new LocalizableKey("For example, work as prime minister, commander in chief or judge of the Supreme Court."))
            .put(ApplicationFieldName.PAYING_ALIMONY, new LocalizableKey("Applies to children not living with you."))
            .put(ApplicationFieldName.TAXABLE_IN_SWEDEN, new LocalizableKey("Your residence for tax purposes is the country where you pay tax. Normally in the country where you live or work."))
            .put(ApplicationFieldName.TAXABLE_IN_USA, new LocalizableKey("You're considered to be this if you are an American citizen, have a Green card or is a US resident during a certain period."))
            .put(ApplicationFieldName.MORTGAGE_COMPARISONS, new LocalizableKey("3 months list rate / average rate"))
            .build();

    public static final ImmutableMap<String, LocalizableKey> FIELD_INTRODUCTIONS = ImmutableMap.<String, LocalizableKey>builder()
            .put(ApplicationFieldName.APPLICANT_NUMBER_OF_CHILDREN_PAYING_ALIMONY_FOR, new LocalizableKey("How many children do you pay alimony for?"))
            .put(ApplicationFieldName.CO_APPLICANT_NUMBER_OF_CHILDREN_PAYING_ALIMONY_FOR, new LocalizableKey("How many children does your co-applicant pay alimony for?"))
            .put(ApplicationFieldName.ALIMONY_AMOUNT_PER_MONTH, new LocalizableKey("How much alimony do you pay in total per month?"))
            .put(ApplicationFieldName.CO_APPLICANT_ALIMONY_AMOUNT, new LocalizableKey("How much alimony does your co-applicant pay in total per month?"))
            .put(ApplicationFieldName.CO_APPLICANT_RECEIVING_ALIMONY_COUNT, new LocalizableKey("How many children does your co-applicant receive alimony for?"))
            .put(ApplicationFieldName.CO_APPLICANT_STREET_ADDRESS, new LocalizableKey("Enter your co-applicant's postal address."))
            .put(ApplicationFieldName.DEFERRED_AMOUNT, new LocalizableKey("You can find your deferred amount by logging in with BankID at skatteverket.se."))
            .put(ApplicationFieldName.RECEIVING_ALIMONY_COUNT, new LocalizableKey("How many children do you receive alimony for?"))
            .put(ApplicationFieldName.MORTGAGE_SECURITY_STREET_ADDRESS, new LocalizableKey("Enter the address and property type of the residence that you want to move your mortgage for."))
            .put(ApplicationFieldName.TAXPAYER_IDENTIFICATION_NUMBER_USA, new LocalizableKey("Enter your American taxpayer identification number."))
            .put(ApplicationFieldName.TAXPAYER_IDENTIFICATION_NUMBER_OTHER_COUNTRY, new LocalizableKey("Your taxpayer identification number is usually on your ID documents or tax report. If the country doesn't issue TIN, enter instead 'Missing'."))
            .build();
    
    public static final ImmutableMap<String, LocalizableKey> OPTION_LABELS = ImmutableMap.<String, LocalizableKey>builder()
            .put(ApplicationFieldOptionValues.ACCOUNT_IN_FOREIGN_BANK, new LocalizableKey("From a foreign bank"))
            .put(ApplicationFieldOptionValues.APARTMENT, new LocalizableKey("Apartment"))
            .put(ApplicationFieldOptionValues.BETWEEN_10000_AND_20000, new LocalizableKey("Between 10000 and 20000"))
            .put(ApplicationFieldOptionValues.BETWEEN_10000_AND_25000, new LocalizableKey("Between 10000 and 25000"))
            .put(ApplicationFieldOptionValues.BETWEEN_20000_AND_30000, new LocalizableKey("Between 20000 and 30000"))
            .put(ApplicationFieldOptionValues.BETWEEN_20000_AND_35000, new LocalizableKey("Between 20000 and 35000"))
            .put(ApplicationFieldOptionValues.BETWEEN_25000_AND_50000, new LocalizableKey("Between 25000 and 50000"))
            .put(ApplicationFieldOptionValues.BETWEEN_30000_AND_40000, new LocalizableKey("Between 30000 and 40000"))
            .put(ApplicationFieldOptionValues.BETWEEN_35000_AND_50000, new LocalizableKey("Between 35000 and 50000"))
            .put(ApplicationFieldOptionValues.BETWEEN_50000_AND_70000, new LocalizableKey("Between 50000 and 70000"))
            .put(ApplicationFieldOptionValues.BETWEEN_50000_AND_150000, new LocalizableKey("Between 50000 and 150000"))
            .put(ApplicationFieldOptionValues.BETWEEN_150000_AND_250000, new LocalizableKey("Between 150000 and 250000"))
            .put(ApplicationFieldOptionValues.BETWEEN_250000_AND_350000, new LocalizableKey("Between 250000 and 350000"))
            .put(ApplicationFieldOptionValues.CHAIN_TERRACE_HOUSE, new LocalizableKey("Chain terrace house"))
            .put(ApplicationFieldOptionValues.COHABITANT, new LocalizableKey("Cohabitant"))
            .put(ApplicationFieldOptionValues.DANSKE_BANK, new LocalizableKey("Danske Bank"))
            .put(ApplicationFieldOptionValues.FALSE, new LocalizableKey("False"))
            .put(ApplicationFieldOptionValues.FIVE_TO_TEN_TIMES_A_MONTH, new LocalizableKey("Five to ten times a month"))
            .put(ApplicationFieldOptionValues.GIFT_OR_INHERITANCE, new LocalizableKey("Gift or inheritance"))
            .put(ApplicationFieldOptionValues.HANDELSBANKEN, new LocalizableKey("Handelsbanken"))
            .put(ApplicationFieldOptionValues.HOUSE, new LocalizableKey("House"))
            .put(ApplicationFieldOptionValues.INDUSTRY_IT, new LocalizableKey("Data/IT/Ekonomi/Juridik"))
            .put(ApplicationFieldOptionValues.INDUSTRY_SALES, new LocalizableKey("Försäljning/Marknadsföring"))
            .put(ApplicationFieldOptionValues.INDUSTRY_HOTEL, new LocalizableKey("Hotell/Uthyrning/Resetjänster"))
            .put(ApplicationFieldOptionValues.INDUSTRY_CULTURE, new LocalizableKey("Kultur/Media/Design/Hantverk"))
            .put(ApplicationFieldOptionValues.INDUSTRY_RESTAURANT, new LocalizableKey("Restaurang/Taxi/Bemanning/Åkeri/Transport"))
            .put(ApplicationFieldOptionValues.INDUSTRY_PAYMENTS, new LocalizableKey("Betalningsförmedling/Valutaväxling/Virtuella valutor"))
            .put(ApplicationFieldOptionValues.INDUSTRY_GAMING, new LocalizableKey("Spelbolag/Kasino"))
            .put(ApplicationFieldOptionValues.INDUSTRY_HAIRDRESSER, new LocalizableKey("Frisör/Hushållsnära tjänster"))
            .put(ApplicationFieldOptionValues.INDUSTRY_HEALTH, new LocalizableKey("Hälso- och sjukvård/Frisk- och kroppsvård"))
            .put(ApplicationFieldOptionValues.INDUSTRY_CONSTRUCTION, new LocalizableKey("Bygg och Anläggning/Skrot/Återvinning"))
            .put(ApplicationFieldOptionValues.INDUSTRY_WEAPON, new LocalizableKey("Vapenhandel"))
            .put(ApplicationFieldOptionValues.INDUSTRY_TECH, new LocalizableKey("Teknik/Säkerhet/Industri"))
            .put(ApplicationFieldOptionValues.LESS_THAN_10000, new LocalizableKey("Less than 10000"))
            .put(ApplicationFieldOptionValues.LESS_THAN_20000, new LocalizableKey("Less than 20000"))
            .put(ApplicationFieldOptionValues.LESS_THAN_50000, new LocalizableKey("Less than 50000"))
            .put(ApplicationFieldOptionValues.LESS_THAN_ONCE_A_MONTH, new LocalizableKey("Less than once a month"))
            .put(ApplicationFieldOptionValues.LOTTERY_OR_GAMBLING, new LocalizableKey("Lottery or gambling"))
            .put(ApplicationFieldOptionValues.MARRIED, new LocalizableKey("Married"))
            .put(ApplicationFieldOptionValues.MORE_THAN_350000, new LocalizableKey("More than 350000"))
            .put(ApplicationFieldOptionValues.MORE_THAN_40000, new LocalizableKey("More than 40000"))
            .put(ApplicationFieldOptionValues.MORE_THAN_50000, new LocalizableKey("More than 50000"))
            .put(ApplicationFieldOptionValues.MORE_THAN_70000, new LocalizableKey("More than 70000"))
            .put(ApplicationFieldOptionValues.MORE_THAN_FIVE_TIMES_A_MONTH, new LocalizableKey("More than five times a month"))
            .put(ApplicationFieldOptionValues.MORE_THAN_TEN_TIMES_A_MONTH, new LocalizableKey("More than ten times a month"))
            .put(ApplicationFieldOptionValues.MY_ACCOUNT_IN_SWEDISH_BANK, new LocalizableKey("From my account in a Swedish bank"))
            .put(ApplicationFieldOptionValues.NO, new LocalizableKey("No"))
            .put(ApplicationFieldOptionValues.NO_OTHER_PROPERTIES, new LocalizableKey("No other properties"))
            .put(ApplicationFieldOptionValues.NORDEA, new LocalizableKey("Nordea"))
            .put(ApplicationFieldOptionValues.ONE_TO_FIVE_TIMES_A_MONTH, new LocalizableKey("One to five times a month"))
            .put(ApplicationFieldOptionValues.OTHER, new LocalizableKey("Other"))
            .put(ApplicationFieldOptionValues.OTHER_OCCUPATION, new LocalizableKey("Other occupation"))
            .put(ApplicationFieldOptionValues.OTHER_SAVINGS, new LocalizableKey("Other savings (funds or stocks etc.)"))
            .put(ApplicationFieldOptionValues.OTHER_WAY, new LocalizableKey("Other way"))
            .put(ApplicationFieldOptionValues.OTHERS_ACCOUNT_IN_SWEDISH_BANK, new LocalizableKey("From someone else´s account in a Swedish bank"))
            .put(ApplicationFieldOptionValues.OWN_BUSINESS_OR_DIVIDEND, new LocalizableKey("Own business (e.g salary or dividend)"))
            .put(ApplicationFieldOptionValues.PERMANENT_EMPLOYMENT, new LocalizableKey("Permanent employment"))
            .put(ApplicationFieldOptionValues.PERSONS_SAVING_ME, new LocalizableKey("Me"))
            .put(ApplicationFieldOptionValues.PROPERTY_SALE, new LocalizableKey("Sale of property"))
            .put(ApplicationFieldOptionValues.PERSONS_SAVING_OTHER, new LocalizableKey("Someone else"))
            .put(ApplicationFieldOptionValues.PURPOSE_FINANCIAL_BUFFER, new LocalizableKey("Financial buffer"))
            .put(ApplicationFieldOptionValues.PURPOSE_FUTURE_TAX_PAYMENTS, new LocalizableKey("Future tax payments"))
            .put(ApplicationFieldOptionValues.PURPOSE_INVESTMENT_OF_SURPLUS_LIQUIDITY, new LocalizableKey("Investment of surplus liquidity"))
            .put(ApplicationFieldOptionValues.PURPOSE_LONG_TERM_INVESTMENT, new LocalizableKey("Long term investment"))
            .put(ApplicationFieldOptionValues.PURPOSE_ONGOING_EXPENSES, new LocalizableKey("Ongoing expenses"))
            .put(ApplicationFieldOptionValues.PURPOSE_OPERATING_COSTS_OF_MY_RESIDENCE, new LocalizableKey("Operating costs of my residence"))
            .put(ApplicationFieldOptionValues.PURPOSE_PAYMENTS_OF_LOAN_AT_SBAB, new LocalizableKey("Payments of loan at SBAB"))
            .put(ApplicationFieldOptionValues.PURPOSE_PENSION, new LocalizableKey("Pension"))
            .put(ApplicationFieldOptionValues.PURPOSE_PRIVATE_CONSUMPTION, new LocalizableKey("Private consumption"))
            .put(ApplicationFieldOptionValues.PURPOSE_SAVING_FOR_RELATED_PARTIES, new LocalizableKey("Saving for relative (e.g. children)"))
            .put(ApplicationFieldOptionValues.SALARY_OR_PENSION, new LocalizableKey("Salary or pension"))
            .put(ApplicationFieldOptionValues.SALE_OF_ASSETS, new LocalizableKey("Sales (e.g. house, car, boat, company)"))
            .put(ApplicationFieldOptionValues.SALE_OF_CAPITAL_GOODS, new LocalizableKey("Sale of capital goods"))
            .put(ApplicationFieldOptionValues.SALE_OF_COMPANY, new LocalizableKey("Sales of company"))
            .put(ApplicationFieldOptionValues.SALE_OF_PROPERTY, new LocalizableKey("Sales of property"))
            .put(ApplicationFieldOptionValues.SEB, new LocalizableKey("SEB"))
            .put(ApplicationFieldOptionValues.SELF_EMPLOYED, new LocalizableKey("Self employed"))
            .put(ApplicationFieldOptionValues.SENIOR, new LocalizableKey("Retired"))
            .put(ApplicationFieldOptionValues.SECURITIES_TRADING, new LocalizableKey("Securities trading"))
            .put(ApplicationFieldOptionValues.SEMI_DETACHED_HOUSE, new LocalizableKey("Semi-detached house"))
            .put(ApplicationFieldOptionValues.SINGLE, new LocalizableKey("Single"))
            .put(ApplicationFieldOptionValues.SIX_TO_TEN_TIMES_A_MONTH, new LocalizableKey("Six to ten times a month"))
            .put(ApplicationFieldOptionValues.STUDENT_RESEARCHER, new LocalizableKey("Student"))
            .put(ApplicationFieldOptionValues.SURPLUS_LIQUIDITY, new LocalizableKey("Surplus liquidity"))
            .put(ApplicationFieldOptionValues.SWEDBANK, new LocalizableKey("Swedbank"))
            .put(ApplicationFieldOptionValues.SWITCH_OF_BANK_OR_SAVINGS_FORM, new LocalizableKey("Switch of bank or savings form"))
            .put(ApplicationFieldOptionValues.TAX_REFUND, new LocalizableKey("Tax refund"))
            .put(ApplicationFieldOptionValues.TEMPORARY_EMPLOYMENT, new LocalizableKey("Temporary employment"))
            .put(ApplicationFieldOptionValues.TENANCY, new LocalizableKey("Tenancy"))
            .put(ApplicationFieldOptionValues.TERRACE_HOUSE, new LocalizableKey("Terrace house"))
            .put(ApplicationFieldOptionValues.TRUE, new LocalizableKey("True"))
            .put(ApplicationFieldOptionValues.UNEMPLOYED, new LocalizableKey("Unemployed"))
            .put(ApplicationFieldOptionValues.VACATION_HOUSE, new LocalizableKey("Vacation house"))
            .put(ApplicationFieldOptionValues.YES, new LocalizableKey("Yes"))
            .put(ApplicationFieldOptionValues.SALARY, new LocalizableKey("Salary"))
            .put(ApplicationFieldOptionValues.PENSION, new LocalizableKey("Pension"))
            .put(ApplicationFieldOptionValues.INSURANCE_PAYOUT, new LocalizableKey("Insurance payout"))
            .put(ApplicationFieldOptionValues.DIVIDENDS_FROM_SMALL_BUSINESS, new LocalizableKey("Dividends from small business"))
            .put(ApplicationFieldOptionValues.SAVINGS, new LocalizableKey("Savings"))
            .put(ApplicationFieldOptionValues.CAPITAL_MANAGEMENT, new LocalizableKey("Capital management"))
            .put(ApplicationFieldOptionValues.CARDS, new LocalizableKey("Cards"))
            .put(ApplicationFieldOptionValues.PENSION_INSURANCE, new LocalizableKey("Pension insurance"))
            .put(ApplicationFieldOptionValues.INVESTING, new LocalizableKey("Investing"))
            .build();

    public static final ImmutableMap<String, LocalizableKey> OPTION_DESCRIPTIONS = ImmutableMap.<String, LocalizableKey>builder()
            .build();
    
    private static final UnlocalizableInfoSection TAXABLE_IN_OTHER_COUNTRY_INFO_SECTION = new UnlocalizableInfoSection(
            "Skatterättslig hemvist i annat land",
            "Enligt svensk lagstiftning om internationellt informationsbyte på skatteområdet behöver banken veta i vilket land eller länder du har din skatterättsliga hemvist.\n\nI vissa fall kan man ha skatterättslig hemvist i mer än ett land. Har du skatterättslig hemvist i något mer land än Sverige eller USA ska du ange det eller de länderna.\n\nOm du enbart betalar en särskilt skatt i ett land, t.ex. fastighetsskatt för ett fritidshus, anses du inte ha skatterättslig hemvist där och ska inte ange det landet.");
    
    public static final ImmutableMap<String, InfoSection<?, ?>> INFO_SECTIONS = ImmutableMap
            .<String, InfoSection<?, ?>> builder()
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_ASSESSED_VALUE,
                    new UnlocalizableInfoSection(
                            "Taxeringsvärde",
                            "Taxeringsvärdet är det som Skatteverket utgår ifrån när de beskattar din fastighet. Ofta är taxeringsvärdet ungefär 75 % av fastighetens marknadsvärde. Du kan få hjälp att räkna ut exakt taxeringsvärde på Skatteverkets hemsida."))
            .put(ApplicationFieldName.OTHER_PROPERTY_HOUSE_GROUND_RENT,
                    new UnlocalizableInfoSection(
                            "Tomträttsavgäld",
                            "Om du själv inte är ägare till tomten som du har din fastighet på så betalar du en avgift till tomtägaren, en så kallad tomträttsavgäld."))
            .put(ApplicationFieldName.TAXABLE_IN_USA,
                    new UnlocalizableInfoSection(
                            "Skatterättslig hemvist i USA",
                            "Du anses ha skatterättslig hemvist i USA om du:\n1. är amerikansk medborgare,\n2. är innehavare av amerikanskt uppehålls-/arbetstillstånd, eller\n3. har vistats i USA under en viss tid (normalt mer än 183 dagar per år).\n\nOm du har skatterättslig hemvist i USA enligt den andra eller tredje punkten ovan och samtidigt har skatterättslig hemvist i ett annat land enligt ett dubbelbeskattnings-avtal mellan det landet och USA, anses du dock inte ha skatterättslig hemvist i USA."))
            .put(ApplicationFieldName.IS_PEP,
                    new UnlocalizableInfoSection(
                            "Personer i politiskt utsatt ställning/PEP (Politically Exposed Person)",
                            "Svenska banker och andra finansiella institut måste även enligt lag inhämta uppgifter om kunden är en person i en politiskt utsatt ställning (på engelska: politically exposed person, PEP). Att vara en person i politiskt utsatt ställning innebär att man har eller har haft viktiga funktioner i en stat, ett statsägt företag eller i en internationell organisation. En person i politiskt utsatt ställning anses genom sin position och sitt inflytande inneha en ställning som i sig utgör en risk att utnyttjas för bland annat mutor.\n\nSamma risk anses även omfatta personer som har en yrkesmässig, ägarmässig och/eller privat relation till en person i politiskt utsatt ställning.\n\nVi ber dig därför fylla i om du är en person i politiskt utsatt ställning eller om du är en familjemedlem eller känd medarbetare till en sådan person (t ex att du äger ett företag tillsammans med en person i politiskt utsatt ställning).\n\nOm du innehar någon av följande befattningar eller är närstående till en sådan person är du förmodligen PEP:\n\n- Stats- eller regeringschef\n- Minister\n- Vice och biträdande minister\n- Parlamentsledamot\n- Domare i Högsta domstolen\n- Domare i annan domstol\n- Tjänsteman vid revisionsmyndighet\n- Styrelseledamot i centralbank\n- Ambassadör\n- Diplomatiskt sändebud\n- Hög officer inom försvaret\n- Person med hög post inom statsägt företag\n- Direktör av en internationell organisation\n- Biträdande direktör av en internationell organisation\n- Styrelseledamot av en internationell organisation"))
            .put(ApplicationFieldName.TAXABLE_IN_OTHER_COUNTRY, TAXABLE_IN_OTHER_COUNTRY_INFO_SECTION)
            .put(ApplicationFieldName.TAXABLE_IN_YET_ANOTHER_COUNTRY, TAXABLE_IN_OTHER_COUNTRY_INFO_SECTION)
            .put(ApplicationFieldName.APARTMENT_NUMBER,
                    new UnlocalizableInfoSection(
                            "Lägenhetsnummer",
                            "Ange skatteverkets fyrsiffriga lägenhetsnummer. T.ex. 1105."))
            .put(ApplicationFieldName.ADDITIONAL_AREA,
                    new UnlocalizableInfoSection(
                            "Biarea",
                            "Inkluderar exempelvis källare, garage, pannrum och soprum."))
            .put(ApplicationFieldName.VALUATION_MONTHLY_OPERATING_COST,
                    new UnlocalizableInfoSection(
                            "Driftkostnad per månad",
                            "I driftkostnaden ingår t.ex. kostnader för uppvärmning, vatten och sophämtning."))
            .put(ApplicationFieldName.MORTGAGE_PRODUCT,
                    new UnlocalizableInfoSection(
                            "Flytta ditt lån direkt",
                            "Du kan skicka en ansökan om att flytta ditt bolån till en av våra partnerbanker direkt här i appen.\n\nVälj en bank och fyll i ansökan. Du signerar ansökan i appen, och den skickas till banken. Sedan ringer banken upp för att slutföra flytten av ditt bolån.\n\nI nuläget samarbetar vi med SEB och SBAB. Vi väljer ut banker som har bra räntor och schyssta villkor."))
            .put(ApplicationFieldName.MORTGAGE_COMPARISONS,
                    new UnlocalizableInfoSection(
                            "Ej anslutna banker",
                            "Vi visar räntor hos andra banker för att du ska kunna jämföra dem mot din nuvarande ränta, och räntorna från våra partners. Snitträntorna är sammanställda räntor från alla Tinks användare som har rörlig bolåneränta."))
            .build();
    
}
