load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "accountidentifier",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@tink_backend//src/libraries/account_identifier",
    ],
)
