server:
  shutdownGracePeriod: 30s
  applicationConnectors:
    - type: http
      port: 9095
    - type: https
      port: 9105
      keyStorePath: data/security/developer.keystore
      keyStorePassword: changeme
      certAlias: developer.internal.tink.se
      trustStorePath: data/security/TinkCA.truststore
      trustStorePassword: changeme
      # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8095

developmentMode: false
decoupledMode: true

developmentConfiguration:
  clusterConfiguration:
    clusterId: local-development
    host: http://localhost:9098
    apiToken: devtoken
    base64encodedclientcert: ""
    disablerequestcompression: false

  aggregatorConfiguration:
    aggregatorId: 00000000-0000-0000-0000-000000000000
    aggregatorInfo: Tink Testing

  clientConfiguration:
    clientName: local-development
    aggregatorId: 00000000-0000-0000-0000-000000000000
    apiClientKey: 00000000-0000-0000-0000-000000000000
    clusterId: local-development

  cryptoConfiguration:
    cryptoConfigurationId:
      clientName: local-development
      keyId: 1
    base64encodedkey: 'QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE='

  aggregationControllerClientConfiguration:
    socket: "${AGGREGATION_CONTROLLER_SOCKET:-localhost:8080}"

database:
  driverClass: com.mysql.jdbc.Driver
  username: tink
  password: tink
  url: jdbc:mysql://$STABLE_AGGREGATIONDB_HOSTPORT/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: false
  persistenceUnitName: tink-aggregation-api
  generateDdl: true

coordination:
  hosts: $STABLE_COORDINATION_HOSTPORT

cache:
  hosts: $STABLE_CACHE_HOSTPORT
  enabled: true

agentsServiceConfiguration:
  integrations:
    sbab:
      signBaseUrl: https://secure.sbab.se
    demoFinancialInstitution:
      mobilebanking:
        baseUrl: http://localhost:9271/mobilebanking
      openbanking:
        baseUrl: http://localhost:9271/openbanking
    collector:
      collectorSubscriptionKey: ASK_JOHANNES
    0ee1cda5943e4662bb9775c34de291d6:
      00000000-0000-0000-0000-000000000000:
        clientId: DUMMY_ID
        clientSecret: DUMMY_SECRET
        organizationId: MOCK_ORG_ID
        redirectUrl: https://api.tink.se/api/v1/credentials/third-party/callback
        rootCAData: /u3+7QAAAAIAAAABAAAAAQAMc2VydmVyLWFsaWFzAAABcV4ZikcAAAUDMIIE/zAOBgorBgEEASoCEQEBBQAEggTr1XsxDGRl5KMjbvN4Dz4ncstZaUwnqQlHW4JN7yt4oPamDfKWYB/31znr0SyS/uAjaX/4PsPlNWvR6qH7f5uWU4JxwOB+u7mo9Fqcy/OSfA1bCiL1NCUEN9FC9ELQsntJa58o/lvDlb0G+vH7gcpIFm5luabvfwmL3E38KhnU8Ze1KrsXwljf9vzCXJNEbup0a2tqAC1Gh2TN9k8iYBbDHvENNpXL2+1rfo0lQD1PBQIscymGHcHdoop0Fu3ofvcqhqYitEA/lLBUHBOAKxo4Y2l7ZzRkbDE/YWi4h8dHx5cDqbb/jjRsdsM2vun2kcdc9MhP0T91COKgna7I1xQQ6ZuWkl6cBSPGXqL5jJQejPNokr/mzKyRDSdndUzLRLD7PQLNzCal64GEpjhGS5EBrAjLBDnszZy8bk/p0htiTFLi7x+r9yUr/BzBIpWSM2lXNv/DxHZsDnsqiMPW/FrYTU9P8QqdhG0O6kPWAeSkOJckUvZgKeZ7VAedFUKjlL0QmIS4SQLnPsa0dhPQcV+ONLnmkBkCr3/5oESEl7BbGBHPUb/9JalA0087u+dfqilSp+MUQJZzl/e4Eif/ggiP2HMTlAu9twTK+bVysmRk+QInKCM7Bcb6OtUInttRuL9rvXlI/G6PhQR64XZ6OJMvuznShFsCJW9mz/rwCQZ1ennN05BblvcdiPRzTo22YTveWaMznLWOIkVi3Rh1Yp/1QMvXVLalOHy7t9dvPZS/AWfhF1yQa2MU4LszQsTjc4XRk24S5m35CF/PiQXD064zWB7T01sDMCOen5IKbZdjWPXPAODUHoVGRsQqE76vvjLaOXerRhzTn1MfSeJW4YDsbI+daBmsO7iqocoWahVK1+jeG0Hs4X5ubh7Slw2Apn//UlnXq66RI9jGNOC5fi8TdRYzV3iccUdTLpAVa5jLnwgDY9sZJwjrE8KN7br9F4YNo3sIBGa0SoCWSojkfx0mAVSeBKDgK1U9OOnGbyvyrQUkdAQBI5Xa4JMasPOwki3Y/ibZt4vPjam71rouKpUZMPZkj0xHLXf7C0wu1X5f1hnK3ImLei27im14GREBjVWpy5jPnSAwS0fGVqzQgTsabIhbtc4R+E0VtZa16hV9DQtX9dYoCYzSXSn2zsuSOn5NclR5XmsR7wAYWildsuTwQKa9gdC13uEfX8wksDurSodSRqucPXT/++WI08A7XfIzEOXsuAcTt1jmb0D8K/bZFaKgwNj2em7p8vnRIFD4Jb09PtOpPhKpzgHRZqaCq3Do+5gPLFq0sdnq4P9La5PrMxn5k47l9mzlBSaUo1tG0NtQqN9LzqG7dJhtNR2kBBF+H02zCoL5ZUnNkF6jU9HkoOT9150SZlajjfmwptJd2b3KBCCUr9gVf6y95NfDQvPxgA7Sa6YOkRsR+4Jnv6U5fzrnNyFbkQaUGjGrXXoOYeNnMwoNEKpP3rDknYR+aSS4PcZu3xWKt/SMPfHUVw28El+TKIjdWAjJaG55xg+steSe60NN7hPk/0oGm8GGp/LCwhEkmBaI/uAZ2Lyo0ipFklsp+wuTXq/EQAyWhA1wKLI1rIJCqMvKJUFDpkapFIKs3ZSghsrdSUis7Xlgltuho9DxJvqMGTW9J8WwQoms3Zi1B6eYRFn2zQZOIvXnTB0mB3EbR5YUFHC5uIoAAAABAAVYLjUwOQAAA1cwggNTMIICO6ADAgECAgQUZL0VMA0GCSqGSIb3DQEBCwUAMFoxCzAJBgNVBAYTAlNFMQ8wDQYDVQQIEwZTd2VkZW4xDTALBgNVBAcTBFRpbmsxDTALBgNVBAoTBFRpbmsxDTALBgNVBAsTBFRpbmsxDTALBgNVBAMTBFRpbmswHhcNMjAwNDA5MDg0MTA0WhcNMjAwNzA4MDg0MTA0WjBaMQswCQYDVQQGEwJTRTEPMA0GA1UECBMGU3dlZGVuMQ0wCwYDVQQHEwRUaW5rMQ0wCwYDVQQKEwRUaW5rMQ0wCwYDVQQLEwRUaW5rMQ0wCwYDVQQDEwRUaW5rMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArSlRbzaVBLpW933i1Fht8ttkwABDAZUR4yRYwC23inb+8i8Qunw5otBKcYOIAexYLaOp0w8M9rk/R6Q1UwyNh2Fj14WSpoqgGCyjPQptBXyl7SSbiC6q1Yixm8VPYugPqP1/rNd2sy/lXXW7oC6rkPHEyIXX0ZoXPeH0Rg44TWeMKaQ7A5irpk5+9hkFs1OPUEKXtC+kPLLA1MRYq3cD+WyMJep9WKSHY7n4oJmnDM2WA09ik/Ae4LFchNlQKnLLuhdhfdEnmVmiDKrbmn3Re4Xx8XZ/RQyozvdmoBmNSAZsO30LPRpB6Q9jvN/vrXPlrU/LRqxRmC91SOtO3KqxzwIDAQABoyEwHzAdBgNVHQ4EFgQU5KLdT+W0h1IHB7R/VeXFJNGMso4wDQYJKoZIhvcNAQELBQADggEBAC7k5julL++RAxhwQxNTbEa5QzD2uplQ9Dt1ibB1X9Vu//7Ni0AA1+7GmVkqaJy8wN+mvTfrpJUTEM/oSYdyuaLxeHQBphLkU3+1bK/SU37+c0NzClA7F492pI9je4nv4Eu251DqAuJLnGUz714ppcr9ZK4BnDUIu2sxGJnONiaF1xCQFKkmHJJdZx1yPnO4ld+RW8fHRFQQDq9iCMI9BT5yhD/EzCa7JTMHbAkzWVPQQYvHYuYKS4VgRkw3oV3dCMPMzR4OACk2qS8VyRqf3LaaiZpivGIUvcu0pduRYMFBIopGIpN2EubjBlLeTql37IP0LyhJ2OCp5EFu5wOKx99caetNjh0wFW59aCv/8C81Vz5W3Q==
        rootCAPassword: testpassword
        signingKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCeO0Lg7ku3wj5BXCsi2zGvV84A5e7acbrP2EeQxhdCjomDYYoQZpTiLcbRBSnXcb3RPhGqeDjfjTLpI7WcxrNAU1oK0+OSE+8i90MK4pX+50RTQOmNvgR5eQI3IBI1ZLsMDM1JjU8dmsKmcmoCf8wghsM/qXYtJOYP5mNwXQFRRoa/6ohZ/aMbKFBZ51HRb+CChiJkQmPC0+b/JA97noaqHrMH7shOsr12ivlSEOS2Wuqj+Axxg1TNA3EAiawFMI88NyU2ejDAtt9mzKQwlUdQnI0vWvT7hBAG4CCGm6dwYGOSlRS8uRTrRQYFcUDZzefpHoqVGMGjBVnrtSnnZwRLAgMBAAECggEAKe2eHShH3BuWj48yxvu6QLJNniNPlYbJb8XpwM0c4MAQZEX2Zb4o+X4TztNFcRdsqwN9fuR4fZRWxzx1JWPpn8P2eiQHi2/I0EUg+MNt56u0iTMMMEkHuoB8O8s9x/Q3NEw4IaNWMYwOxDhRKvReTMgo+LeY3wGGDPSJqP6cGMLix/cRafHAbs/+TbZuLs+fYu7Mxln0TFj1D9nEwj7awayuM5iAaWh899duxPr2NmOs1KA9xsOWSZJ1xi0eeqFlVUPnLWI7WFwKtz2x2H1oJZUqo3q3H7nigDrg7xzBEwmXhvOxlQkESfBv+vup0JwGINYnPBpe3c4JhKmenpYzkQKBgQDMy/xR1XH0pu27A21DBz6ZCXij7+NKOC8Plr23uO7fbb+6dkhCYOLYRtUB5gvj+a2SETigIw1T4NuM8EOsgAmaOLTodlThr3Qeq76f637xLTWETVr8ABdT48jRqZqM0Slk3FGamCFNPNxf1oOKXYPexzkQBxK+RKY7hK7GsotNFQKBgQDFytzx9IEmh5A296Yi4PxTMuj/mihmQGq9RihrdHG5cs4BYVjddwqtuWPY/VCyh0kG9ctjH1tOW2I/RjbGeXMGA/3hzmyWd156/BaFboWQ6aBJh382PbeHmMvBdqTwDTw0gp778gVZMdzBBXONrVni+AbLGSi6zwMr7L4bJbEj3wKBgGvZjMJHxqBRfGZ9EoA3A3cybq7euPKwDdCG0Ng88scFE/ANNFaIkU3WV3yNenuPVCHVId3rN6yRgO2C5hCkyOnHrTWyg1bqwBsa1OOA8DPwW/uVhTGqlp5eGbaYO8Smrcbo46ynKvpy75ck79bhEn4yqlFPeEZs/qHfaO9IvWVVAoGBAJHVhly7m3IOKA3vQMacvk6VzeeQAVOLEWhmzyyTWbqTZELuRLhdqjj25SC7fYF0cCq6lfCK0SaQCHuAyKhEKcP4s3uHWNcEQlxJfE17dO2o5C7ywZ/7l1NaHHmTgf8gsxBAcvpusvTV599FprKCazEHEPM0pKxAMCV106FuhBJfAoGABaG/3JCsqdMq7ak5nOK3ZJ3lMrWwulvwhC8baoUoutu2n34JnUi5XTdHIHeCrwn2bF9SaONulpW6H9tbGGjMYJPkA3N4iGfN02/6PukhO9/0Ei000DSp031Aof4xAPfr7RatuV75bcl12VBplPwFuiFCYnHunXmiEhuQfLQ0kVY=
        signingKeyId: DUMMY_KEY_ID
        signingKeyPassword: ''
        softwareId: DUMMY_SOFTWARE_ID
        softwareStatementAssertion: eyJhbGciOiJQUzI1NiIsImtpZCI6Ikh6YTl2NWJnREpjT25oY1VaN0JNd2JTTF80TlYwZ1NGdklqYVNYZEMtMWM9IiwidHlwIjoiSldUIn0.eyJpc3MiOiJPcGVuQmFua2luZyBMdGQiLCJpYXQiOjE1OTg4ODg2ODgsImp0aSI6ImY0NDNmYmExNDk5YzQ5NGQiLCJzb2Z0d2FyZV9lbnZpcm9ubWVudCI6InNhbmRib3giLCJzb2Z0d2FyZV9tb2RlIjoiVGVzdCIsInNvZnR3YXJlX2lkIjoibWprY2FsczFzcTI3cHYwWmxKNzhFeiIsInNvZnR3YXJlX2NsaWVudF9pZCI6Im1qa2NhbHMxc3EyN3B2MFpsSjc4RXoiLCJzb2Z0d2FyZV9jbGllbnRfbmFtZSI6IlRpbmsgU2FuZGJveCIsInNvZnR3YXJlX2NsaWVudF9kZXNjcmlwdGlvbiI6IlVzZWQgdG8gdGVzdCBzYW5kYm94Iiwic29mdHdhcmVfdmVyc2lvbiI6MS4wLCJzb2Z0d2FyZV9jbGllbnRfdXJpIjoiaHR0cHM6Ly9jb25zdW1lci50aW5rLnNlLyIsInNvZnR3YXJlX3JlZGlyZWN0X3VyaXMiOlsiaHR0cHM6Ly8xMjcuMC4wLjE6NzM1Ny9hcGkvdjEvdGhpcmRwYXJ0eS9jYWxsYmFjayJdLCJzb2Z0d2FyZV9yb2xlcyI6WyJBSVNQIiwiUElTUCJdLCJvcmdhbmlzYXRpb25fY29tcGV0ZW50X2F1dGhvcml0eV9jbGFpbXMiOnsiYXV0aG9yaXR5X2lkIjoiU0ZTQVNXRSIsInJlZ2lzdHJhdGlvbl9pZCI6IjQ0MDU5Iiwic3RhdHVzIjoiQWN0aXZlIiwiYXV0aG9yaXNhdGlvbnMiOlt7Im1lbWJlcl9zdGF0ZSI6IlNFIiwicm9sZXMiOlsiQUlTUCIsIlBJU1AiXX0seyJtZW1iZXJfc3RhdGUiOiJHQiIsInJvbGVzIjpbIkFJU1AiLCJQSVNQIl19LHsibWVtYmVyX3N0YXRlIjoiSUUiLCJyb2xlcyI6WyJBSVNQIiwiUElTUCJdfSx7Im1lbWJlcl9zdGF0ZSI6Ik5MIiwicm9sZXMiOlsiQUlTUCIsIlBJU1AiXX1dfSwic29mdHdhcmVfbG9nb191cmkiOiJodHRwczovL2Nkbi50aW5rLnNlL3RpbmstbG9nb3MvTE9XL1RpbmtfTGF4LnBuZyIsIm9yZ19zdGF0dXMiOiJBY3RpdmUiLCJvcmdfaWQiOiIwMDE1ODAwMDAxNmk0NElBQVEiLCJvcmdfbmFtZSI6IlRpbmsgQUIiLCJvcmdfY29udGFjdHMiOlt7Im5hbWUiOiJUZWNobmljYWwiLCJlbWFpbCI6Im9wZW5iYW5raW5nK3Vrb2J0ZWNoQHRpbmsuc2UiLCJwaG9uZSI6IjAwNDY3MDMyMzk2NDciLCJ0eXBlIjoiVGVjaG5pY2FsIn0seyJuYW1lIjoiQnVzaW5lc3MiLCJlbWFpbCI6Im9wZW5iYW5raW5nK3Vrb2JiaXpAdGluay5zZSIsInBob25lIjoiMDA0Njc2MDAyNDgzNyIsInR5cGUiOiJCdXNpbmVzcyJ9XSwib3JnX2p3a3NfZW5kcG9pbnQiOiJodHRwczovL2tleXN0b3JlLm9wZW5iYW5raW5ndGVzdC5vcmcudWsvMDAxNTgwMDAwMTZpNDRJQUFRLzAwMTU4MDAwMDE2aTQ0SUFBUS5qd2tzIiwib3JnX2p3a3NfcmV2b2tlZF9lbmRwb2ludCI6Imh0dHBzOi8va2V5c3RvcmUub3BlbmJhbmtpbmd0ZXN0Lm9yZy51ay8wMDE1ODAwMDAxNmk0NElBQVEvcmV2b2tlZC8wMDE1ODAwMDAxNmk0NElBQVEuandrcyIsInNvZnR3YXJlX2p3a3NfZW5kcG9pbnQiOiJodHRwczovL2tleXN0b3JlLm9wZW5iYW5raW5ndGVzdC5vcmcudWsvMDAxNTgwMDAwMTZpNDRJQUFRL21qa2NhbHMxc3EyN3B2MFpsSjc4RXouandrcyIsInNvZnR3YXJlX2p3a3NfcmV2b2tlZF9lbmRwb2ludCI6Imh0dHBzOi8va2V5c3RvcmUub3BlbmJhbmtpbmd0ZXN0Lm9yZy51ay8wMDE1ODAwMDAxNmk0NElBQVEvcmV2b2tlZC9tamtjYWxzMXNxMjdwdjBabEo3OEV6Lmp3a3MiLCJzb2Z0d2FyZV9wb2xpY3lfdXJpIjoiaHR0cHM6Ly9jb25zdW1lci50aW5rLnNlL2ludGVncml0eS1wb2xpY3kiLCJzb2Z0d2FyZV90b3NfdXJpIjoiaHR0cHM6Ly9jb25zdW1lci50aW5rLnNlL3Rlcm1zLWFuZC1jb25kaXRpb25zIiwic29mdHdhcmVfb25fYmVoYWxmX29mX29yZyI6bnVsbH0.sBFpkUCqMraUfRts2294fYxGc7d_0duTIU4s0I48B9jT8398vI8p9NsrrkexgLAnUbHIurGuGEqk3flM4pMxMVmZtCn4AFQoXDM2r2f0d7d1bbfOJ9MbgPvxi0sOEZlGZGVZogyjKtAHSdWMqDkNWLdPqLRil3PadqttDWv6mIuOFXjjYlkclSW9KgT8vI1RMgMdhLNFPJN18jNZdrZbfNtantcQcbFiOnYvpg8fB6PskOZLM8cMkRCAnBde3XLVAN8JcFz0YCO4gG23c5Kom_ftMlkKGcV3TWJX-o04g_n0k2xC1Cznr-YHQjOHX784tUv_xdoAWA9SVWnlNSl81Q
        transportKey: MIIJoQIBAzCCCWcGCSqGSIb3DQEHAaCCCVgEgglUMIIJUDCCBAcGCSqGSIb3DQEHBqCCA/gwggP0AgEAMIID7QYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQInWJuqbJvxZQCAggAgIIDwGtG/BKV4jTh1cmtRI2K7DlMmVjlVGWOi3+D/eY26F2vogb20ZVEy2u2+QuBbH6GSqYT2CxK3Ni0cgRbTa6cPWx8VjzZsX96Mz+AN8yyVWHML6t7VKbCY4o7Wq3v5QNeSefeAP5Yz8OJ8jEx2fqHFwtY7QTHXjxBWILZN0ri2OsaLTeHVb+BOFVQWe5hxH0JdLGfO+mvzySIQnrzRJqqQ+5fgqsZ39kbqtX4aB6fCC4/7x7nQlGVr23IqR/+eX+dJSXbQn8ft7jQw/sD3yH4XOHHNwFvwrr2J1vci2TIymUQdJ0Z7l8FrGovDk090xYDqmoSrQ7SXYEAa092cr63293lMAsuQ0lPl5uc9yoxQvqi6UlHVE/j38a4BXEEpHM+sjotOY0N9Xwb+1R0K9h1K+Zi4yFU2EGMRbhwlHvTAL3paquYsougxLZvY3sy/1m4/NUEbTf2u6en8647SOfXA7TuKtByOrHFMt00pLop3ZUTMBwIR3X9i8PFIFi5zwUDEBa47qJ43YXw/gXbpKOno+ZG0pPnH/8o304UwdhEZaViX0LrB1gMVdBHMI4hpOw9aUNBTE9jcOTp09mHY0y3s4fb4ixdswoAkTkuBhPMb83YeNCd+41QDzjoTK8kgyTqLhdnLQUsS5EUtzV8T+c9/fd2VcLi9Gm1pD8zXlhlZa3wT5d/SbpqlJ6wJvaILNcgEwqfA8wWUx/7GGJaTlPN5/tUC6cOG78GGHqnuVRyNOSDceHokPFjkcxGvCmMIM2Mg8X6k7Tgfu8h0PS7CejekPWkGaApgg8dn1d3Gp8slcMgp+e9WMzdto1ogAOCQraRmY/mJfgOf/hanvOJrZS66jxgbBSDlw6vUXWGZcpXLXKnTrctRHTDwBjqG+BLf4b6Bdj/atMzHrxm/o9AFgMlH4DksYC7JdOFIhcQXRkdM8ivrsHXH+S1fk/KvlxIdUzIJU4RTVL40WRlu9KaIIQ5C8bnUhbGGvRgVm2pNocNO8M05nENDlIcF7Tw3Y2Kf4Fdlr7r0vyiu6km80tOEeR1vWLKwJQf5nEGKk8rh3Epd7reD1R4yzX1R0P78VTGO5Tm/FRhl/dW9uc/qyf1SU96gebj3ZzvJCQJAgh2tKjwFY5JDjC4VPIClOikTjye4EohovOSIhLgyS6D5JY/m6jOFJzZhOXLGnvJYXiShvd3So0q+GDwlp0R1GjSekhKjwAyCgZHKE7+sEKK9w92818igOYGeLk55ql+JK36p4Ja4Urp4StaXEI1z89ICdBXyy6RwjCCBUEGCSqGSIb3DQEHAaCCBTIEggUuMIIFKjCCBSYGCyqGSIb3DQEMCgECoIIE7jCCBOowHAYKKoZIhvcNAQwBAzAOBAgZmPbJxPpoqwICCAAEggTIfmoJ2oz2iXvEa8qukhPPl6CggNIMuTYKf4U8tZllKYJTL/S2kHQ62Z2K0YM0xPOTWVls0Ss61v6oNm6jWjkDerZiglAZw/u9DPXCCSbZkfuQDqSyDxFYrF2LfuKzsw524fdXJN/ustvJC3roL3WtZo5gsNH3M3K0zxm5Dsl4BBSKY8iOEauiTO/+1q+/1c9vpzYMr8oUdKL3cT9RGD2e5f3p4HXZ9ONf8899toHewdhT5qG50iqYw3Sl38lDM7iSdoIPdo9iBep9ue7gD4qt/Fl7huqScIyX7N4e246C3qqnIh4Yi2+kjmlWPGwcP15nJo9DsjKakYgPoJ25f57DNPwE/4hx1juNyFvQc5WTKDdRpgYqJcm4YSjtJuV2ShOAq0K8/xygOV0xngRdW7xisnfuH+MY9dKiOcqH9X+Yk8c4+vLIZ8DRkbzclIy9+v7XUQu/6r+HrKa3fN3hKqJLohy7yIbbEisnUJM8CjescPMzNGKHLpK/0HNEdpAzf3+7AYQcx2cHOWGzVoMmuG/cQiLemIwB5JQEjQHVkMDzr8hYVqujBx77SEt/dcowWZLqVwyIAvBu1O58D51WwORu4oO28OrWGczfAocgi3euk/2EVdDhN4LgUo9F7mqmDB1Cwqq815W3Ca7XXrghXbVjzN9brKm3G9vKe1HbA8IIKHl56IDg68u0iVGSAxqVTefjj+nLVOeNGPi1lzJ+7nIlCkA6bpTBTnavTyvXpn/rB2cU+Q5LaoRkcpDvRHaIlMQ0Cze971fjXIkoDv2gdsstUVdpkznTrifiSuLjAvRqWDf4RqURDj0JCmQT8FC/Xbx/YPIBRIhw3R7nMCoCG7iVJlgi/rWyDbR8p9TrrJH6+OuZ5b8vG/Wu7W882d4vmeas7Wv7vLrFrjtOfF0dFLqJ3PPFz1n3AUEAy0kfuS152BWh1oiBy4rOoyF6oujoXiBP3FWwQkrWW6KBpC688AdCRI/X9/Gp/UcYqoixMOcM3pLubr/BTQgBpAqUwXEJe9Ql5EyAMuDk5ZO8eEfyhQycqedQjOukzZftiy8/Isld9owVsSDMEkKZJ/i1e+qvROljc9gSfjFeUUFORmSbsV/1xGfGCM2a4MfxxQXsQYAIlwtYFUKLGp9sP4Y5sia9HWLxJ632a08QQpWRj3TmXwfYI968dkFXc51gz2XM0/2ieeJfg431p2ylkyVBxQtSgx+L/uvyq1Yd5KRyPD+uibY6xzuJ1Bqv998gUhvcQI5HgNAHwCyn1orD3auTqMpXYszbWhJmA0KgiXiJG5pP1pLjY/35OBCeaHlLNBFAy65xHAExstwJMjtTohCesBwOxWGM1fP+IW7xcZK7KiG46D6R1p2Wab2zxC6mGUSZ1zO5AJKcT8g7iTs/h2AwnoF2YJ782MhvD4k/MVP2vl76TAGPQqFaKM2JZf8hk4snszX/BksWVix1vwjKjxuw8dk5cwlQnoMwZX04u3grxI4y4sxpMkMZ7TCWMnFsmoOR6diNBM4IzVoCYwkMt4MvNjAOplvksxFQDBIkfB/kG8Us8i0IG54uFoR4ItscWLh6twgRertUIKk6L9fTzWAGNWe7vLtv8t00Zn0aJV2FdDUsGer4B0wFvfmak8UIMSUwIwYJKoZIhvcNAQkVMRYEFKgZQt1gql2JpoOGLbVPMhn7Qi21MDEwITAJBgUrDgMCGgUABBRquBHtKXYkt/GKbM4b8LF1mmEKIQQIc9YELYmTnFECAggA
        transportKeyId: ''
        transportKeyPassword: testpassword
  creditsafe:
    username: TINKTESTIN
    password: cU7356rwx
  excludedDebugClusters:
    excludedClusters:
    - local-development
  signatureKeyPair:
    privateKeyPath: "data/test/cryptography/private_rsa_key.pem"
    publicKeyPath: "data/test/cryptography/public_rsa_key.pub"

sqsQueueConfiguration:
  enabled: false
  url: http://localhost:4576/
  region: local
  awsAccessKeyId: foobar
  awsSecretKey: foobar
  queueName: queue

s3StorageConfiguration:
  enabled: false
  url: http://localhost:4572
  region: local
  agentDebugBucketName: local-agent-debug-bucket

logging:
  level: INFO
  loggers:
    se.tink: TRACE
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} C:%X{clusterId} UID:%X{userId} CID:%X{credentialsId} P:%X{providerName} A:%X{agentName} %blue(%logger) %message%n%xException'
    - type: file
      threshold: INFO
      currentLogFilename: /usr/share/tink-backend-aggregation/log/tink-backend-aggregation.log
      archive: true
      archivedLogFilenamePattern: /usr/share/tink-backend-aggregation/log/tink-backend-aggregation-%d.log.gz
      archivedFileCount: 5
      timeZone: Europe/Stockholm
      logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %message%n%xException'

prometheus:
  port: 9130

isMultiClientDevelopment: false

provisionClientsConfig:
  clients:
    provision-job-testing:
      aggregatorIdentifier: "Provision Job Testing"
    provisioning-job2-testing:
      aggregatorIdentifier: "Local provisioning"

providerConfigurationServiceConfiguration:
  host: https://provider-configuration-api.provider-configuration.svc.cluster.local
  pinnedCertificates:
    - CERTSHA256:A0A8FBAC442F4A58AC56CB1D0C185F93EE119A1B026BA3F046B0CA99EC165390
  port: 9048
  enabled: true
