load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "charsetguesser",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:org_apache_commons_commons_lang3",
    ],
)
