java_library(
    name = "storage",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/serialization",
        "//third_party:com_fasterxml_jackson_core_jackson_core",
        "//third_party:org_slf4j_slf4j_api",
        "@aggregation//:com_google_guava_guava",
        "@io_reactivex_rxjava3_rxjava",
    ],
)
