java_library(
    name = "storage",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/serialization",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
    ],
)
