load("//tools/bzl:junit.bzl", "junit_test")

java_library(
    name = "local",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/interaction_counter",
    ],
)
