package se.tink.backend.aggregation.agents.nxgen.serviceproviders.creditcards.amex.v62.authenticator;

public class AmericanExpressV62PasswordAuthenticatorTestData {
    public static String logonResponse = "{\n\"status\": {\n"
            + "\t\t\"success\": true\n"
            + "\t},"
            + "  \"logonData\": {\n"
            + "    \"status\": 0,\n"
            + "    \"profileData\": {\n"
            + "      \"maskedUserId\": \"userdata\",\n"
            + "      \"data\": \"muid#ri*****|rmf#1|kid#1|ed#000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000|\"\n"
            + "    },\n"
            + "    \"gateKeeperCookie\": \"0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\",\n"
            + "    \"cupcake\": \"cupcake\",\n"
            + "    \"amexSession\": \"session\",\n"
            + "    \"publicGuid\": \"66666666666666666666666666666666\"\n"
            + "  },\n"
            + "  \"summaryData\": {\n"
            + "    \"status\": 0,\n"
            + "    \"cardList\": [\n"
            + "      {\n"
            + "        \"embossedName\": \"FIRST_NAME SURNAME\",\n"
            + "        \"homeCountryLocale\": \"sv_SE\",\n"
            + "        \"cardProductName\": \"SAS EuroBonus American Express® Classic Credit Card\",\n"
            + "        \"sortedIndex\": 1,\n"
            + "        \"cardKey\": \"6666666666666666666666666666666666666666\",\n"
            + "        \"cardNumberDisplay\": \"XXX-XXXX\",\n"
            + "        \"cardArtImage\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/se-cardasset-config/images/GSEGREN0SA01S3.gif\",\n"
            + "        \"rewards\": {\n"
            + "          \"message\": \"För fullständigt poängsaldo, besök sas.se/eurobonus\"\n"
            + "        },\n"
            + "        \"summary\": {\n"
            + "          \"availableCredit\": {\n"
            + "            \"label\": \"Tillgänglig kredit\",\n"
            + "            \"value\": \"666.666,66 kr\"\n"
            + "          },\n"
            + "          \"statementBalance\": {\n"
            + "            \"label\": \"Föregående faktura\",\n"
            + "            \"value\": \"6.666,66 kr\"\n"
            + "          },\n"
            + "          \"recentPayments\": {\n"
            + "            \"label\": \"Periodens inbetalningar och krediteringar\",\n"
            + "            \"value\": \"666,66 kr\"\n"
            + "          },\n"
            + "          \"recentCharges\": {\n"
            + "            \"label\": \"De senaste transaktionerna\",\n"
            + "            \"value\": \"6.066,06 kr\"\n"
            + "          },\n"
            + "          \"totalBalance\": {\n"
            + "            \"label\": \"Totalt saldo\",\n"
            + "            \"value\": \"6.666,66 kr\"\n"
            + "          },\n"
            + "          \"paymentDue\": {\n"
            + "            \"label\": \"Utestående skuld\",\n"
            + "            \"value\": \"6.666,66 kr\"\n"
            + "          },\n"
            + "          \"minimumPaymentDue\": {\n"
            + "            \"label\": \"Lägsta betalning\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          },\n"
            + "          \"commonPaymentDue\": {\n"
            + "            \"label\": \"Betalning\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          },\n"
            + "          \"paymentDueDate\": {\n"
            + "            \"label\": \"betalas senast den\",\n"
            + "            \"value\": \"11 maj 2018\"\n"
            + "          },\n"
            + "          \"paymentDueOnDate\": {\n"
            + "            \"label\": \"den %@\",\n"
            + "            \"value\": \"11 maj\"\n"
            + "          },\n"
            + "          \"lastStmtBalanceClosingDate\": {\n"
            + "            \"label\": \"Slutdatum\",\n"
            + "            \"value\": \"16 apr 2018\"\n"
            + "          },\n"
            + "          \"latestTransactionStartDate\": {\n"
            + "            \"label\": \"Sedan\",\n"
            + "            \"value\": \"17 apr 2018\"\n"
            + "          },\n"
            + "          \"timeLineBalance\": {\n"
            + "            \"label\": \"Totalt saldo\",\n"
            + "            \"value\": \"6.666,66 kr\"\n"
            + "          },\n"
            + "          \"timelinePaymentBalance\": {\n"
            + "            \"label\": \"Betalning\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"capabilities\": {\n"
            + "          \"cml\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false\n"
            + "          },\n"
            + "          \"transactions\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false,\n"
            + "            \"label\": \"Se transaktioner\"\n"
            + "          },\n"
            + "          \"home\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Hem\"\n"
            + "          },\n"
            + "          \"accountSummary\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Kontoöversikt\"\n"
            + "          },\n"
            + "          \"help\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Hjälp/Kontakta oss\"\n"
            + "          },\n"
            + "          \"logout\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Logga ut\"\n"
            + "          },\n"
            + "          \"terms\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Legalt/Sekretess\"\n"
            + "          },\n"
            + "          \"pendingTransaction\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false\n"
            + "          },\n"
            + "          \"transactionDtl\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false\n"
            + "          },\n"
            + "          \"nativeAppMGM\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Bjud in och bli belönad\"\n"
            + "          },\n"
            + "          \"pdfStatements\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"PDF Fakturor\"\n"
            + "          },\n"
            + "          \"activateRegister\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false,\n"
            + "            \"label\": \"Aktivera och lägg till Kort\"\n"
            + "          },\n"
            + "          \"removeCardV2\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false,\n"
            + "            \"label\": \"Ta bort ett Kort\"\n"
            + "          },\n"
            + "          \"manageCardsV2\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Hantera Kort\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"accountToken\": \"777777777777777\"\n"
            + "      },\n"
            + "      {\n"
            + "        \"embossedName\": \"FIRST_NAME SURNAME\",\n"
            + "        \"homeCountryLocale\": \"sv_SE\",\n"
            + "        \"cardProductName\": \"SAS EuroBonus American Express® Premium Card\",\n"
            + "        \"sortedIndex\": 0,\n"
            + "        \"cardKey\": \"6666666666666666666666666666666666666666\",\n"
            + "        \"cardNumberDisplay\": \"XXX-XXXXX\",\n"
            + "        \"cardArtImage\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/se-cardasset-config/images/CSEGOLD0SA01S3.gif\",\n"
            + "        \"message\": {\n"
            + "          \"type\": \"ERROR\",\n"
            + "          \"shortValue\": \"cancelled\",\n"
            + "          \"value\": \"Kortet har avslutats\",\n"
            + "          \"longValue\": \"This Card is cancelled\"\n"
            + "        },\n"
            + "        \"rewards\": {\n"
            + "          \"message\": \"För fullständigt poängsaldo, besök sas.se/eurobonus\"\n"
            + "        },\n"
            + "        \"summary\": {\n"
            + "          \"statementBalance\": {\n"
            + "            \"label\": \"Föregående faktura\",\n"
            + "            \"value\": \"-5,00 kr\"\n"
            + "          },\n"
            + "          \"recentPayments\": {\n"
            + "            \"label\": \"Periodens inbetalningar och krediteringar\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          },\n"
            + "          \"recentCharges\": {\n"
            + "            \"label\": \"De senaste transaktionerna\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          },\n"
            + "          \"totalBalance\": {\n"
            + "            \"label\": \"Totalt saldo\",\n"
            + "            \"value\": \"-5,00 kr\"\n"
            + "          },\n"
            + "          \"paymentDue\": {\n"
            + "            \"label\": \"Utestående skuld\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          },\n"
            + "          \"commonPaymentDue\": {\n"
            + "            \"label\": \"Att betala\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          },\n"
            + "          \"paymentDueDate\": {\n"
            + "            \"label\": \"betalas senast den\",\n"
            + "            \"value\": \"2 maj 2018\"\n"
            + "          },\n"
            + "          \"paymentDueOnDate\": {\n"
            + "            \"label\": \"den %@\",\n"
            + "            \"value\": \"2 maj\"\n"
            + "          },\n"
            + "          \"lastStmtBalanceClosingDate\": {\n"
            + "            \"label\": \"Slutdatum\",\n"
            + "            \"value\": \"16 apr 2018\"\n"
            + "          },\n"
            + "          \"latestTransactionStartDate\": {\n"
            + "            \"label\": \"Sedan\",\n"
            + "            \"value\": \"17 apr 2018\"\n"
            + "          },\n"
            + "          \"timeLineBalance\": {\n"
            + "            \"label\": \"Totalt saldo\",\n"
            + "            \"value\": \"-5,00 kr\"\n"
            + "          },\n"
            + "          \"timelinePaymentBalance\": {\n"
            + "            \"label\": \"Att betala\",\n"
            + "            \"value\": \"0,00 kr\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"capabilities\": {\n"
            + "          \"cml\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false\n"
            + "          },\n"
            + "          \"transactions\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false,\n"
            + "            \"label\": \"Se transaktioner\"\n"
            + "          },\n"
            + "          \"home\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Hem\"\n"
            + "          },\n"
            + "          \"accountSummary\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Kontoöversikt\"\n"
            + "          },\n"
            + "          \"help\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Hjälp/Kontakta oss\"\n"
            + "          },\n"
            + "          \"logout\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Logga ut\"\n"
            + "          },\n"
            + "          \"terms\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Legalt/Sekretess\"\n"
            + "          },\n"
            + "          \"pendingTransaction\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false\n"
            + "          },\n"
            + "          \"transactionDtl\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false\n"
            + "          },\n"
            + "          \"pdfStatements\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"PDF Fakturor\"\n"
            + "          },\n"
            + "          \"activateRegister\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false,\n"
            + "            \"label\": \"Aktivera och lägg till Kort\"\n"
            + "          },\n"
            + "          \"removeCardV2\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": false,\n"
            + "            \"label\": \"Ta bort ett Kort\"\n"
            + "          },\n"
            + "          \"manageCardsV2\": {\n"
            + "            \"enabled\": true,\n"
            + "            \"showInMenu\": true,\n"
            + "            \"label\": \"Hantera Kort\"\n"
            + "          }\n"
            + "        },\n"
            + "        \"accountToken\": \"666666666666666\"\n"
            + "      }\n"
            + "    ],\n"
            + "    \"userData\": {\n"
            + "      \"embossedName\": \"FIRST_NAME SURNAME\",\n"
            + "      \"firstName\": \"FIRST_NAME\",\n"
            + "      \"lastName\": \"SURNAME\"\n"
            + "    }\n"
            + "  }\n"
            + "}";
}
