filegroup(
    name = "development-configuration",
    srcs = [
        "development-configuration.yaml",
        "development-sensitive-configuration.yaml",
    ],
    visibility = ["//visibility:public"],
)
