apiVersion: v1
kind: ConfigMap
metadata:
  name: product-executor-configuration
  namespace: product-executor
data:
  product-executor-server.yml: |
    server:
      shutdownGracePeriod: 10s
      applicationConnectors:
        - type: http
          port: 80
        - type: https
          port: 443
          {{- if eq "local" .Values.Cluster }}
          keyStorePath: data/security/developer.keystore
          certAlias: developer.internal.tink.se
          {{- else }}
          keyStorePath: data/security/production.keystore
          certAlias: container.internal.tink.se
          {{- end }}
          keyStorePassword: KEYSTORE_PASSWORD # replaced from secrets
          trustStorePath: data/security/TinkCA.truststore
          trustStorePassword: changeme
          # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
          validateCerts: false
      adminConnectors:
        - type: http
          port: 8099
    endpoints:
      system:
        url: http://localhost:9091/
        accessToken: devtoken
        pinnedCertificates:
          - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"

    cluster: {{ .Values.applicationCluster | default "TINK" }}
    developmentMode: false

    integrations:
      seb:
        mortgage:
          https: false
          targetHost: 10.1.18.10:10090
          apiVersion: v1.0
          httpHeaders:
            Authorization: "Bearer ASK_JOHANNES"
            Host: tink-api.seb.se:10443
      sbab:
        signBaseUrl: https://secure.sbab.se
        mortgage:
          https: false
          targetHost: 10.10.1.120:10080
          username: sys_tink
          password: bytkod
          signBaseUrl: https://testsign.sbab.se

    coordination:
      hosts: {{ default "coordination.product-executor.svc.cluster.local:2181" .Values.coordinationHosts }}

    logging:
      level: INFO
      loggers:
        se.tink: INFO
        se.tink.org.eclipse: INFO
      appenders:
        - type: console
          threshold: ALL
          timeZone: Europe/Stockholm
          logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %replace(%m){"\n", "\\n"}\\n%replace(%ex){"[\r\n]+", "\\n"}%nopex%n'

    prometheus:
      port: 9130

{{ if .Values.createDevelopmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: product-executor-secrets
  namespace: product-executor
type: Opaque
data:
  # Is set to changeme for the development keystore
  keystore-password: Y2hhbmdlbWU=
{{ end }}
