package se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.responsecodes;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.rpc.GenericResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class GenericResponseTest {

    @Test
    public void shouldReportSessionExpiredIfUnsuccessfulResponse() {
        GenericResponse response =
                SerializationUtils.deserializeFromString(
                        getUnsuccessfulResponse(), GenericResponse.class);
        assertTrue(response.isSessionExpired());
    }

    @Test
    public void shouldReportSessionExpiredIfSessionExpiredResponse() {
        GenericResponse response =
                SerializationUtils.deserializeFromString(
                        getSessionExpiredResponse(), GenericResponse.class);
        assertTrue(response.isSessionExpired());
    }

    @Test
    public void shouldReportSessionAliveIfSessionAliveResponse() {
        GenericResponse response =
                SerializationUtils.deserializeFromString(
                        getSuccessfulResponse(), GenericResponse.class);
        assertFalse(response.isSessionExpired());
    }

    private String getUnsuccessfulResponse() {
        return "{\n"
                + "  \"Header\": {\n"
                + "    \"ResponseId\": \"b7e8627cf9b64542aaf0a64723838950\",\n"
                + "    \"OpToken\": null,\n"
                + "    \"Time\": \"2019-11-15T14:53:06.8443181Z\",\n"
                + "    \"SessionTimeout\": 0,\n"
                + "    \"Status\": {\n"
                + "      \"Mensagem\": \"De momento não é possível processar a sua instrução. Por favor tente mais tarde.\",\n"
                + "      \"Severidade\": 3,\n"
                + "      \"Codigo\": 50\n"
                + "    }\n"
                + "  }\n"
                + "}";
    }

    private String getSessionExpiredResponse() {
        return "{\n"
                + "  \"Header\": {\n"
                + "    \"ResponseId\": \"fed8f486110c4c7ba05ef092816263fa\",\n"
                + "    \"OpToken\": null,\n"
                + "    \"Time\": \"2019-11-27T09:37:35.5882499Z\",\n"
                + "    \"SessionTimeout\": 0,\n"
                + "    \"Status\": {\n"
                + "      \"Mensagem\": \"A sua sessão expirou. Por favor aceda novamente ao serviço.\",\n"
                + "      \"Severidade\": 4,\n"
                + "      \"Codigo\": 20\n"
                + "    }\n"
                + "  }\n"
                + "}";
    }

    private String getSuccessfulResponse() {
        return "{\n"
                + "  \"Header\": {\n"
                + "    \"ResponseId\": \"4e93f499bed94cdca38fcae4da894ab7\",\n"
                + "    \"OpToken\": \"5cba54d8e3d14102b2160c5855a4c079\",\n"
                + "    \"Time\": \"2019-11-18T11:10:18.4796648Z\",\n"
                + "    \"SessionTimeout\": 1800,\n"
                + "    \"Status\": {\n"
                + "      \"Severidade\": 0,\n"
                + "      \"Codigo\": 0\n"
                + "    },\n"
                + "    \"Contexto\": {\n"
                + "      \"Contas\": {\n"
                + "        \"Lista\": [{\n"
                + "          \"Id\": \"2222222222\",\n"
                + "          \"Iban\": \"PT22222222222222222\",\n"
                + "          \"Desc\": \"Conta DO\"\n"
                + "        }, {\n"
                + "          \"Id\": \"1111111111111111111\",\n"
                + "          \"Iban\": \"PT111111111111111111\",\n"
                + "          \"Desc\": \"Conta Serviço DO\"\n"
                + "        }, {\n"
                + "          \"Id\": \"33333333333\",\n"
                + "          \"Desc\": \"Dep. Someone\"\n"
                + "        }, {\n"
                + "          \"Id\": \"444444444444444\",\n"
                + "          \"Desc\": \"Dep. Someone Fancy\"\n"
                + "        }],\n"
                + "        \"Selected\": \"2222222222\"\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  \"Body\": {\n"
                + "    \"DataHoje\": \"2019-11-18\",\n"
                + "    \"Movimentos\": [{\n"
                + "      \"Saldo\": 650.37,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 3300 4358 0018\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-11-01\",\n"
                + "      \"DataOperacao\": \"2019-11-01\",\n"
                + "      \"Numero\": 21,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfValor\": 0.0,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 640.37,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 3300 4358 0018\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-10-01\",\n"
                + "      \"DataOperacao\": \"2019-10-01\",\n"
                + "      \"Numero\": 20,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 630.37,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 3300 4358 0018\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-09-01\",\n"
                + "      \"DataOperacao\": \"2019-09-01\",\n"
                + "      \"Numero\": 19,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 620.37,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"IMPOSTO RENDIMENTO S/ JUROS CONTA POUPANÇA\",\n"
                + "      \"Montante\": -0.08,\n"
                + "      \"DataValor\": \"2019-08-29\",\n"
                + "      \"DataOperacao\": \"2019-08-29\",\n"
                + "      \"Numero\": 18,\n"
                + "      \"Categoria\": \"Impostos, Fundos de Pensões, outras Taxas\",\n"
                + "      \"IdCategoria\": 346,\n"
                + "      \"OfIcon\": 8\n"
                + "    }, {\n"
                + "      \"Saldo\": 620.45,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"JUROS 1111111111111 - 01/03/2019 A 28/08/2019 - 0,1000% A)\",\n"
                + "      \"Montante\": 0.3,\n"
                + "      \"DataValor\": \"2019-08-29\",\n"
                + "      \"DataOperacao\": \"2019-08-29\",\n"
                + "      \"Numero\": 17,\n"
                + "      \"Categoria\": \"Juros e Dividendos\",\n"
                + "      \"IdCategoria\": 355,\n"
                + "      \"OfIdN1\": 12,\n"
                + "      \"OfIcon\": 10\n"
                + "    }, {\n"
                + "      \"Saldo\": 620.15,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-08-01\",\n"
                + "      \"DataOperacao\": \"2019-08-01\",\n"
                + "      \"Numero\": 16,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 610.15,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-07-01\",\n"
                + "      \"DataOperacao\": \"2019-07-01\",\n"
                + "      \"Numero\": 15,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 600.15,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-06-01\",\n"
                + "      \"DataOperacao\": \"2019-06-01\",\n"
                + "      \"Numero\": 14,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 590.15,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 3300 4358 0018\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-05-01\",\n"
                + "      \"DataOperacao\": \"2019-05-01\",\n"
                + "      \"Numero\": 13,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 580.15,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-04-01\",\n"
                + "      \"DataOperacao\": \"2019-04-01\",\n"
                + "      \"Numero\": 12,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 570.15,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-03-01\",\n"
                + "      \"DataOperacao\": \"2019-03-01\",\n"
                + "      \"Numero\": 11,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 560.15,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"IMPOSTO RENDIMENTO S/ JUROS CONTA POUPANÇA\",\n"
                + "      \"Montante\": -0.06,\n"
                + "      \"DataValor\": \"2019-03-01\",\n"
                + "      \"DataOperacao\": \"2019-03-01\",\n"
                + "      \"Numero\": 10,\n"
                + "      \"Categoria\": \"Impostos, Fundos de Pensões, outras Taxas\",\n"
                + "      \"IdCategoria\": 346,\n"
                + "      \"OfIcon\": 8\n"
                + "    }, {\n"
                + "      \"Saldo\": 560.21,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"JUROS 11111111111 - 29/08/2018 A 28/02/2019 - 0,1000% A)\",\n"
                + "      \"Montante\": 0.21,\n"
                + "      \"DataValor\": \"2019-03-01\",\n"
                + "      \"DataOperacao\": \"2019-03-01\",\n"
                + "      \"Numero\": 9,\n"
                + "      \"Categoria\": \"Juros e Dividendos\",\n"
                + "      \"IdCategoria\": 355,\n"
                + "      \"OfIdN1\": 12,\n"
                + "      \"OfIcon\": 10\n"
                + "    }, {\n"
                + "      \"Saldo\": 560.0,\n"
                + "      \"Tipo\": 24,\n"
                + "      \"Descricao\": \"DE SOMEONE FANCY\",\n"
                + "      \"Montante\": 150.0,\n"
                + "      \"DataValor\": \"2019-02-03\",\n"
                + "      \"DataOperacao\": \"2019-02-03\",\n"
                + "      \"Numero\": 8,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 410.0,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-02-01\",\n"
                + "      \"DataOperacao\": \"2019-02-01\",\n"
                + "      \"Numero\": 7,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 400.0,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2019-01-01\",\n"
                + "      \"DataOperacao\": \"2019-01-01\",\n"
                + "      \"Numero\": 6,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 390.0,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2018-12-01\",\n"
                + "      \"DataOperacao\": \"2018-12-01\",\n"
                + "      \"Numero\": 5,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 380.0,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2018-11-01\",\n"
                + "      \"DataOperacao\": \"2018-11-01\",\n"
                + "      \"Numero\": 4,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 370.0,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2018-10-01\",\n"
                + "      \"DataOperacao\": \"2018-10-01\",\n"
                + "      \"Numero\": 3,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 360.0,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"TRF ENTREGA PROGRAMADA MENSAL DE 12 34 56\",\n"
                + "      \"Montante\": 10.0,\n"
                + "      \"DataValor\": \"2018-09-01\",\n"
                + "      \"DataOperacao\": \"2018-09-01\",\n"
                + "      \"Numero\": 2,\n"
                + "      \"Categoria\": \"Intrapatrimónio\",\n"
                + "      \"IdCategoria\": 359,\n"
                + "      \"OfIdN1\": 13,\n"
                + "      \"OfIcon\": 13\n"
                + "    }, {\n"
                + "      \"Saldo\": 350.0,\n"
                + "      \"Tipo\": 0,\n"
                + "      \"Descricao\": \"CONST DEP SOMEONE NBnet 275464657 DE 111111111\",\n"
                + "      \"Montante\": 350.0,\n"
                + "      \"DataValor\": \"2018-08-29\",\n"
                + "      \"DataOperacao\": \"2018-08-28\",\n"
                + "      \"Numero\": 1,\n"
                + "      \"NumPedido\": \"123456\",\n"
                + "      \"Categoria\": \"Poupança e Investimento\",\n"
                + "      \"IdCategoria\": 357,\n"
                + "      \"OfIdN1\": 14,\n"
                + "      \"OfIcon\": 11\n"
                + "    }],\n"
                + "    \"Saldo\": {\n"
                + "      \"Disponivel\": 650.37,\n"
                + "      \"Cativo\": 0.0,\n"
                + "      \"Contabilistico\": 650.37,\n"
                + "      \"Autorizado\": 650.37,\n"
                + "      \"Descoberto\": 0.0,\n"
                + "      \"Moeda\": \"EUR\"\n"
                + "    },\n"
                + "    \"Moeda\": \"EUR\",\n"
                + "    \"ComSCA\": false\n"
                + "  }\n"
                + "}";
    }
}
