package se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.responsecodes;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.fetcher.rpc.loan.GetLoanDetailsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class GetLoanDetailsResponseTest {
    @Test
    public void shouldReportSuccessIfSuccessfulGetLoanDetailsResponse() {
        GetLoanDetailsResponse response =
                SerializationUtils.deserializeFromString(
                        getSuccessfulResponse(), GetLoanDetailsResponse.class);
        assertTrue(response.isSuccessful());
    }

    @Test
    public void shouldReportFailureIfUnsuccessfulGetLoanDetailsResponse() {
        GetLoanDetailsResponse response =
                SerializationUtils.deserializeFromString(
                        getUnsuccessfulResponse(), GetLoanDetailsResponse.class);
        assertFalse(response.isSuccessful());
    }

    private String getSuccessfulResponse() {
        return "{\n"
                + "  \"Header\": {\n"
                + "    \"ResponseId\": \"73526a81f758449d9764780e152b4779\",\n"
                + "    \"OpToken\": \"49936e4baec2467d9454caf7dd47b1c4\",\n"
                + "    \"Time\": \"2019-11-23T21:55:48.7681655Z\",\n"
                + "    \"SessionTimeout\": 1800,\n"
                + "    \"Status\": {\n"
                + "      \"Severidade\": 0,\n"
                + "      \"Codigo\": 0\n"
                + "    }\n"
                + "  },\n"
                + "  \"Body\": {\n"
                + "    \"Detalhe\": {\n"
                + "      \"Header\": {\n"
                + "        \"Titulo\": \"BHP - AQUISICAO DEFICIENTES\",\n"
                + "        \"SubTitulo\": {\n"
                + "          \"AM\": 1,\n"
                + "          \"T\": 3,\n"
                + "          \"L\": \"Próxima prestação - Nº 13\",\n"
                + "          \"V\": \"EUR\",\n"
                + "          \"DV\": 377.39\n"
                + "        },\n"
                + "        \"Linhas\": [{\n"
                + "          \"L\": \"Data da próxima prestação\",\n"
                + "          \"V\": \"02-12-2019\"\n"
                + "        }, {\n"
                + "          \"L\": \"Spread\",\n"
                + "          \"V\": \"0,00%\"\n"
                + "        }, {\n"
                + "          \"L\": \"TAN\",\n"
                + "          \"V\": \"0,00%\"\n"
                + "        }, {\n"
                + "          \"L\": \"Capital em divida\",\n"
                + "          \"V\": \"142.025,79 EUR\"\n"
                + "        }]\n"
                + "      },\n"
                + "      \"Linhas\": [{\n"
                + "        \"T\": 30,\n"
                + "        \"Linhas\": [{\n"
                + "          \"T\": 32,\n"
                + "          \"L\": \"Contrato\",\n"
                + "          \"V\": \"1234567\",\n"
                + "          \"Linhas\": [{\n"
                + "            \"L\": \"Designação\",\n"
                + "            \"V\": \"BHP - AQUISICAO DEFICIENTES\"\n"
                + "          }, {\n"
                + "            \"L\": \"Data Início do contrato\",\n"
                + "            \"V\": \"02-11-2018\"\n"
                + "          }, {\n"
                + "            \"L\": \"Capital contratado\",\n"
                + "            \"V\": \"146.510,79 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Capital utilizado\",\n"
                + "            \"V\": \"146.510,79 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Someone contratado\",\n"
                + "            \"V\": \"392\"\n"
                + "          }, {\n"
                + "            \"L\": \"Moeda\",\n"
                + "            \"V\": \"EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Regime\",\n"
                + "            \"V\": \"Bonificado\"\n"
                + "          }, {\n"
                + "            \"L\": \"Tipo de taxa\",\n"
                + "            \"V\": \"Variável\"\n"
                + "          }, {\n"
                + "            \"L\": \"Spread\",\n"
                + "            \"V\": \"0,00%\"\n"
                + "          }, {\n"
                + "            \"L\": \"Bonificação ao spread\",\n"
                + "            \"V\": \"0,00%\"\n"
                + "          }, {\n"
                + "            \"L\": \"Penalização ao spread\",\n"
                + "            \"V\": \"0,00%\"\n"
                + "          }, {\n"
                + "            \"L\": \"Escalão de bonificação\",\n"
                + "            \"V\": \"0\"\n"
                + "          }]\n"
                + "        }, {\n"
                + "          \"T\": 32,\n"
                + "          \"L\": \"Próxima prestação\",\n"
                + "          \"V\": \"Nº 13\",\n"
                + "          \"Linhas\": [{\n"
                + "            \"L\": \"Data valor\",\n"
                + "            \"V\": \"02-12-2019\"\n"
                + "          }, {\n"
                + "            \"L\": \"Montante da prestação\",\n"
                + "            \"V\": \"377,39 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Capital amortizado\",\n"
                + "            \"V\": \"373,75 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Capital em divida na data de emissão do aviso\",\n"
                + "            \"V\": \"141.652,04 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Indexante\",\n"
                + "            \"V\": \"0,00%\"\n"
                + "          }, {\n"
                + "            \"L\": \"TAN\",\n"
                + "            \"V\": \"0,00%\"\n"
                + "          }, {\n"
                + "            \"L\": \"Juros\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Bonificação de juros\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Imposto de selo s/juros\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Comissão de liquidação\",\n"
                + "            \"V\": \"3,50 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Imposto de selo s/comissão de liquidação\",\n"
                + "            \"V\": \"0,14 EUR\"\n"
                + "          }]\n"
                + "        }, {\n"
                + "          \"T\": 32,\n"
                + "          \"L\": \"Última prestação paga\",\n"
                + "          \"V\": \"Nº 12\",\n"
                + "          \"Linhas\": [{\n"
                + "            \"L\": \"Data valor\",\n"
                + "            \"V\": \"02-11-2019\"\n"
                + "          }, {\n"
                + "            \"L\": \"Montante da prestação\",\n"
                + "            \"V\": \"377,39 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Capital amortizado\",\n"
                + "            \"V\": \"373,75 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Capital em divida na data de emissão do aviso\",\n"
                + "            \"V\": \"142.025,79 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Indexante\",\n"
                + "            \"V\": \"0,00%\"\n"
                + "          }, {\n"
                + "            \"L\": \"TAN\",\n"
                + "            \"V\": \"0,00%\"\n"
                + "          }, {\n"
                + "            \"L\": \"Juros\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Bonificação de juros\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Imposto de selo s/juros\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Comissão de liquidação\",\n"
                + "            \"V\": \"3,50 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Imposto de selo s/comissão de liquidação\",\n"
                + "            \"V\": \"0,14 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Imposto s/comissão de atraso\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Juros de Mora\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }, {\n"
                + "            \"L\": \"Imposto s/juros de mora\",\n"
                + "            \"V\": \"0,00 EUR\"\n"
                + "          }]\n"
                + "        }]\n"
                + "      }]\n"
                + "    }\n"
                + "  }\n"
                + "}";
    }

    private String getUnsuccessfulResponse() {
        return "{\n"
                + "  \"Header\": {\n"
                + "    \"ResponseId\": \"28e913f5b57b42f793aff03bf7614b3f\",\n"
                + "    \"OpToken\": null,\n"
                + "    \"Time\": \"2019-11-25T11:04:39.3213808Z\",\n"
                + "    \"SessionTimeout\": 1800,\n"
                + "    \"Status\": {\n"
                + "      \"Mensagem\": \"De momento não é possível processar a sua instrução. Por favor tente mais tarde.\",\n"
                + "      \"Severidade\": 3,\n"
                + "      \"Codigo\": 50\n"
                + "    }\n"
                + "  }\n"
                + "}";
    }
}
