package se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.responsecodes;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.fetcher.rpc.creditcard.GetSummaryResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class GetSummaryResponseTest {
    @Test
    public void shouldReportSuccessIfSuccessfulGetSummaryResponse() {
        GetSummaryResponse response =
                SerializationUtils.deserializeFromString(
                        getSuccessfulResponse(), GetSummaryResponse.class);
        assertTrue(response.isSuccessful());
    }

    @Test
    public void shouldReportFailureIfUnsuccessfulGetSummaryResponse() {
        GetSummaryResponse response =
                SerializationUtils.deserializeFromString(
                        getUnsuccessfulResponse(), GetSummaryResponse.class);
        assertFalse(response.isSuccessful());
    }

    private String getSuccessfulResponse() {
        return "{\n"
                + "\t\"Header\": {\n"
                + "\t\t\"ResponseId\": \"8a513c5f0957439db75feeebb39df4c1\",\n"
                + "\t\t\"OpToken\": \"20d2672fbcc14c23b8fe8062584206ca\",\n"
                + "\t\t\"Time\": \"2019-11-23T21:59:57.0383892Z\",\n"
                + "\t\t\"SessionTimeout\": 1800,\n"
                + "\t\t\"Status\": {\n"
                + "\t\t\t\"Severidade\": 0,\n"
                + "\t\t\t\"Codigo\": 0\n"
                + "\t\t},\n"
                + "\t\t\"Contexto\": {\n"
                + "\t\t\t\"Contas\": {\n"
                + "\t\t\t\t\"Lista\": [{\n"
                + "\t\t\t\t\t\"Id\": \"123456789\",\n"
                + "\t\t\t\t\t\"Iban\": \"PT500123456789\",\n"
                + "\t\t\t\t\t\"Desc\": \"Conta DO\"\n"
                + "\t\t\t\t}],\n"
                + "\t\t\t\t\"Selected\": \"123456789\"\n"
                + "\t\t\t}\n"
                + "\t\t}\n"
                + "\t},\n"
                + "\t\"Body\": {\n"
                + "\t\t\"ResponsabilidadesHoje\": 222301.92,\n"
                + "\t\t\"RecursosHoje\": 6959.60,\n"
                + "\t\t\"NomeCliente\": \"Someone Fancy\",\n"
                + "\t\t\"DataConsulta\": \"2019-11-23T21:59:57.0383892Z\",\n"
                + "\t\t\"Responsabilidades\": [{\n"
                + "\t\t\t\"Designacao\": \"Cartões de Crédito\",\n"
                + "\t\t\t\"Valor\": 135.79,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 14,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"NB GOLD VISA\",\n"
                + "\t\t\t\t\"Contrato\": \"123456789\",\n"
                + "\t\t\t\t\"Saldo\": 135.79\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"NB VERDE VISA\",\n"
                + "\t\t\t\t\"Contrato\": \"123456789\",\n"
                + "\t\t\t\t\"Saldo\": 0.00\n"
                + "\t\t\t}]\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Crédito Habitação\",\n"
                + "\t\t\t\"Valor\": 222166.13,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 15,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"BHS SWAP - AQUISICAO C/ HIPO\",\n"
                + "\t\t\t\t\"Contrato\": \"12345\",\n"
                + "\t\t\t\t\"Saldo\": 80140.34\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"BHP - AQUISICAO DEFICIENTES\",\n"
                + "\t\t\t\t\"Contrato\": \"12346\",\n"
                + "\t\t\t\t\"Saldo\": 142025.79\n"
                + "\t\t\t}]\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Crédito Pessoal\",\n"
                + "\t\t\t\"Valor\": 0.0,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 16,\n"
                + "\t\t\t\"Detalhes\": []\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Conta Corrente Bancária\",\n"
                + "\t\t\t\"Valor\": 0.0,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 30,\n"
                + "\t\t\t\"Detalhes\": []\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Outros Créditos\",\n"
                + "\t\t\t\"Valor\": 0.0,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 26,\n"
                + "\t\t\t\"Detalhes\": []\n"
                + "\t\t}],\n"
                + "\t\t\"Recursos\": [{\n"
                + "\t\t\t\"Designacao\": \"Depósitos\",\n"
                + "\t\t\t\"Valor\": 2893.58,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 5,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"CONTA POUPANCA NB\",\n"
                + "\t\t\t\t\"Contrato\": \"1234\",\n"
                + "\t\t\t\t\"Saldo\": 0.00\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"CONTA POUPANCA NB\",\n"
                + "\t\t\t\t\"Contrato\": \"1235\",\n"
                + "\t\t\t\t\"Saldo\": 0.00\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"DP NB 3 ANOS TAXA CRESCENTE\",\n"
                + "\t\t\t\t\"Contrato\": \"121212\",\n"
                + "\t\t\t\t\"Saldo\": 2000.00\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"POUP PROGRAMADA 3 ANOS\",\n"
                + "\t\t\t\t\"Contrato\": \"121213\",\n"
                + "\t\t\t\t\"Saldo\": 650.37\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"CONTA NB 100% - DO\",\n"
                + "\t\t\t\t\"Contrato\": \"123456789\",\n"
                + "\t\t\t\t\"Saldo\": 243.21\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"CONTA NB 100% POUPANCA\",\n"
                + "\t\t\t\t\"Contrato\": \"123456799\",\n"
                + "\t\t\t\t\"Saldo\": 0.00\n"
                + "\t\t\t}]\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Fundos de Investimento\",\n"
                + "\t\t\t\"Valor\": 249.91,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 7,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"DOSSIER DE FUNDOS\",\n"
                + "\t\t\t\t\"Contrato\": \"123214\",\n"
                + "\t\t\t\t\"Saldo\": 249.91\n"
                + "\t\t\t}]\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Carteira de Títulos\",\n"
                + "\t\t\t\"Valor\": 0.00,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 3,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"DOSSIER DE TITULOS\",\n"
                + "\t\t\t\t\"Contrato\": \"1111111111111111\",\n"
                + "\t\t\t\t\"Saldo\": 0.00\n"
                + "\t\t\t}]\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"PPR/Prod. capit./Unit Link\",\n"
                + "\t\t\t\"Valor\": 3816.11,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 11,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"NB PPR SUPER POUPANCA 5ªS\",\n"
                + "\t\t\t\t\"Contrato\": \"12121212121212\",\n"
                + "\t\t\t\t\"Saldo\": 2694.65\n"
                + "\t\t\t}, {\n"
                + "\t\t\t\t\"Produto\": \"NB PPR TAXA GARANTIDA\",\n"
                + "\t\t\t\t\"Contrato\": \"121212121\",\n"
                + "\t\t\t\t\"Saldo\": 1121.46\n"
                + "\t\t\t}]\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Gestão de Carteiras\",\n"
                + "\t\t\t\"Valor\": 0.0,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 8,\n"
                + "\t\t\t\"Detalhes\": []\n"
                + "\t\t}],\n"
                + "\t\t\"OutrosProdutos\": [{\n"
                + "\t\t\t\"Designacao\": \"Seguros Vida Risco\",\n"
                + "\t\t\t\"Valor\": 0.0,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 27,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"SEG VIDA ACTIVA CRED HABITACAO\",\n"
                + "\t\t\t\t\"Contrato\": \"1111111111111\"\n"
                + "\t\t\t}]\n"
                + "\t\t}, {\n"
                + "\t\t\t\"Designacao\": \"Seguros Não Vida\",\n"
                + "\t\t\t\"Valor\": 0.0,\n"
                + "\t\t\t\"Estado\": 0,\n"
                + "\t\t\t\"Tipo\": 28,\n"
                + "\t\t\t\"Detalhes\": [{\n"
                + "\t\t\t\t\"Produto\": \"SEG. GNB CASA CH MAXI\",\n"
                + "\t\t\t\t\"Contrato\": \"111111122222222\"\n"
                + "\t\t\t}]\n"
                + "\t\t}]\n"
                + "\t}\n"
                + "}";
    }

    private String getUnsuccessfulResponse() {
        return "{\n"
                + "\t\"Header\": {\n"
                + "\t\t\"ResponseId\": \"ffd1770298624d64b4606176260fcdeb\",\n"
                + "\t\t\"OpToken\": null,\n"
                + "\t\t\"Time\": \"2019-11-25T13:15:28.4247229Z\",\n"
                + "\t\t\"SessionTimeout\": 1800,\n"
                + "\t\t\"Status\": {\n"
                + "\t\t\t\"Mensagem\": \"De momento não é possível processar a sua instrução. Por favor tente mais tarde.\",\n"
                + "\t\t\t\"Severidade\": 3,\n"
                + "\t\t\t\"Codigo\": 50\n"
                + "\t\t}\n"
                + "\t}\n"
                + "}";
    }
}
