package se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.responsecodes;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.fetcher.rpc.creditcard.GetSummaryResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class GetSummaryResponseTest {
    @Test
    public void shouldReportSuccessIfSuccessfulGetSummaryResponse() {
        GetSummaryResponse response =
                SerializationUtils.deserializeFromString(
                        getSuccessfulResponse(), GetSummaryResponse.class);
        assertTrue(response.isSuccessful());
    }

    @Test
    public void shouldReportFailureIfUnsuccessfulGetSummaryResponse() {
        GetSummaryResponse response =
                SerializationUtils.deserializeFromString(
                        getUnsuccessfulResponse(), GetSummaryResponse.class);
        assertFalse(response.isSuccessful());
    }

    private String getSuccessfulResponse() {
        return "{\n"
                + "  \"Header\": {\n"
                + "    \"ResponseId\": \"8a513c5f0957439db75feeebb39df4c1\",\n"
                + "    \"OpToken\": \"20d2672fbcc14c23b8fe8062584206ca\",\n"
                + "    \"Time\": \"2019-11-23T21:59:57.0383892Z\",\n"
                + "    \"SessionTimeout\": 1800,\n"
                + "    \"Status\": {\n"
                + "      \"Severidade\": 0,\n"
                + "      \"Codigo\": 0\n"
                + "    },\n"
                + "    \"Contexto\": {\n"
                + "      \"Contas\": {\n"
                + "        \"Lista\": [{\n"
                + "          \"Id\": \"123456789\",\n"
                + "          \"Iban\": \"PT500123456789\",\n"
                + "          \"Desc\": \"Conta DO\"\n"
                + "        }],\n"
                + "        \"Selected\": \"123456789\"\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  \"Body\": {\n"
                + "    \"ResponsabilidadesHoje\": 222301.92,\n"
                + "    \"RecursosHoje\": 6959.60,\n"
                + "    \"NomeCliente\": \"Someone Fancy\",\n"
                + "    \"DataConsulta\": \"2019-11-23T21:59:57.0383892Z\",\n"
                + "    \"Responsabilidades\": [{\n"
                + "      \"Designacao\": \"Cartões de Crédito\",\n"
                + "      \"Valor\": 135.79,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 14,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"NB GOLD VISA\",\n"
                + "        \"Contrato\": \"123456789\",\n"
                + "        \"Saldo\": 135.79\n"
                + "      }, {\n"
                + "        \"Produto\": \"NB VERDE VISA\",\n"
                + "        \"Contrato\": \"123456789\",\n"
                + "        \"Saldo\": 0.00\n"
                + "      }]\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Crédito Habitação\",\n"
                + "      \"Valor\": 222166.13,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 15,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"BHS SWAP - AQUISICAO C/ HIPO\",\n"
                + "        \"Contrato\": \"12345\",\n"
                + "        \"Saldo\": 80140.34\n"
                + "      }, {\n"
                + "        \"Produto\": \"BHP - AQUISICAO DEFICIENTES\",\n"
                + "        \"Contrato\": \"12346\",\n"
                + "        \"Saldo\": 142025.79\n"
                + "      }]\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Crédito Pessoal\",\n"
                + "      \"Valor\": 0.0,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 16,\n"
                + "      \"Detalhes\": []\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Conta Corrente Bancária\",\n"
                + "      \"Valor\": 0.0,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 30,\n"
                + "      \"Detalhes\": []\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Outros Créditos\",\n"
                + "      \"Valor\": 0.0,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 26,\n"
                + "      \"Detalhes\": []\n"
                + "    }],\n"
                + "    \"Recursos\": [{\n"
                + "      \"Designacao\": \"Depósitos\",\n"
                + "      \"Valor\": 2893.58,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 5,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"CONTA POUPANCA NB\",\n"
                + "        \"Contrato\": \"1234\",\n"
                + "        \"Saldo\": 0.00\n"
                + "      }, {\n"
                + "        \"Produto\": \"CONTA POUPANCA NB\",\n"
                + "        \"Contrato\": \"1235\",\n"
                + "        \"Saldo\": 0.00\n"
                + "      }, {\n"
                + "        \"Produto\": \"DP NB 3 ANOS TAXA CRESCENTE\",\n"
                + "        \"Contrato\": \"121212\",\n"
                + "        \"Saldo\": 2000.00\n"
                + "      }, {\n"
                + "        \"Produto\": \"POUP PROGRAMADA 3 ANOS\",\n"
                + "        \"Contrato\": \"121213\",\n"
                + "        \"Saldo\": 650.37\n"
                + "      }, {\n"
                + "        \"Produto\": \"CONTA NB 100% - DO\",\n"
                + "        \"Contrato\": \"123456789\",\n"
                + "        \"Saldo\": 243.21\n"
                + "      }, {\n"
                + "        \"Produto\": \"CONTA NB 100% POUPANCA\",\n"
                + "        \"Contrato\": \"123456799\",\n"
                + "        \"Saldo\": 0.00\n"
                + "      }]\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Fundos de Investimento\",\n"
                + "      \"Valor\": 249.91,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 7,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"DOSSIER DE FUNDOS\",\n"
                + "        \"Contrato\": \"123214\",\n"
                + "        \"Saldo\": 249.91\n"
                + "      }]\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Carteira de Títulos\",\n"
                + "      \"Valor\": 0.00,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 3,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"DOSSIER DE TITULOS\",\n"
                + "        \"Contrato\": \"1111111111111111\",\n"
                + "        \"Saldo\": 0.00\n"
                + "      }]\n"
                + "    }, {\n"
                + "      \"Designacao\": \"PPR/Prod. capit./Unit Link\",\n"
                + "      \"Valor\": 3816.11,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 11,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"NB PPR SUPER POUPANCA 5ªS\",\n"
                + "        \"Contrato\": \"12121212121212\",\n"
                + "        \"Saldo\": 2694.65\n"
                + "      }, {\n"
                + "        \"Produto\": \"NB PPR TAXA GARANTIDA\",\n"
                + "        \"Contrato\": \"121212121\",\n"
                + "        \"Saldo\": 1121.46\n"
                + "      }]\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Gestão de Carteiras\",\n"
                + "      \"Valor\": 0.0,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 8,\n"
                + "      \"Detalhes\": []\n"
                + "    }],\n"
                + "    \"OutrosProdutos\": [{\n"
                + "      \"Designacao\": \"Seguros Vida Risco\",\n"
                + "      \"Valor\": 0.0,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 27,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"SEG VIDA ACTIVA CRED HABITACAO\",\n"
                + "        \"Contrato\": \"1111111111111\"\n"
                + "      }]\n"
                + "    }, {\n"
                + "      \"Designacao\": \"Seguros Não Vida\",\n"
                + "      \"Valor\": 0.0,\n"
                + "      \"Estado\": 0,\n"
                + "      \"Tipo\": 28,\n"
                + "      \"Detalhes\": [{\n"
                + "        \"Produto\": \"SEG. GNB CASA CH MAXI\",\n"
                + "        \"Contrato\": \"111111122222222\"\n"
                + "      }]\n"
                + "    }]\n"
                + "  }\n"
                + "}";
    }

    private String getUnsuccessfulResponse() {
        return "{\n"
                + "  \"Header\": {\n"
                + "    \"ResponseId\": \"ffd1770298624d64b4606176260fcdeb\",\n"
                + "    \"OpToken\": null,\n"
                + "    \"Time\": \"2019-11-25T13:15:28.4247229Z\",\n"
                + "    \"SessionTimeout\": 1800,\n"
                + "    \"Status\": {\n"
                + "      \"Mensagem\": \"De momento não é possível processar a sua instrução. Por favor tente mais tarde.\",\n"
                + "      \"Severidade\": 3,\n"
                + "      \"Codigo\": 50\n"
                + "    }\n"
                + "  }\n"
                + "}";
    }
}
