server:
  applicationConnectors:
    - type: http
      port: 9091
  adminConnectors:
    - type: http
      port: 8091

endpoints:
  api:
    url: http://www.staging.tink.se/api/v1
  main:
    url: http://localhost:9090/
  system:
    url: http://localhost:9090/
    accessToken: devtoken
  aggregation:
    url: http://localhost:9090/
    accessToken: devtoken
  analytics:
    url: http://localhost:9090/
  encryption:
    url: http://localhost:9090/
    accessToken: devtoken
  connector:
    url: http://localhost:9090/

cluster: CORNWALL

developmentMode: true

distributedDatabase:
  seeds:
    - cassandra
  enabled: true
  datacenter: TestDatacenter

database:
  driverClass: com.mysql.jdbc.Driver
  username: tink
  password: tink
  url: jdbc:mysql://mysql/tink?useLocalSessionState=true&rewriteBatchedStatements=true
  showSql: false
  persistenceUnitName: tink-combined-api
  generateDdl: true
  maxPoolSize: 40

cache:
  hosts: memcached:11211
  enabled: true

scheduler:
  enabled: true

coordination:
  hosts: zookeeper:2181

search:
  clusterName: elasticsearch
  hosts: elasticsearch:9300
  enabled: true

analytics:
  intercom:
    enabled: false

logging:
  level: INFO
  loggers:
    se.tink: DEBUG
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
    org.apache.hadoop: INFO
    org.apache.http.client.protocol.ResponseProcessCookies: ERROR
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm

template:
  enabled: false
