java_library(
    name = "beobank",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/agents/src/main/java/se/tink/backend/aggregation/agents/nxgen/serviceproviders/openbanking/cmcic",
        "//src/integration/credentials:service",
        "//src/integration/lib",
    ],
)
