java_library(
    name = "rpc",
    srcs = glob(
        ["*.java"],
    ),
    data = [
    ],
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
        "//src/integration/lib",
        "//src/integration/lib:annotations",
        "//third_party:lombok_libs",
    ],
)
