package se.tink.backend.insights.core.valueobjects;

public enum InsightActionType {
    ACKNOWLEDGE,
    SUGGEST_CATEGORY,
    SWITCH_MORTGAGE,

    GOTO_PAYMENT,
    GOTO_PAYMENT_NO_ID,
    GOTO_TRANSFER,
    GOTO_TRANSFER_NO_ID,
    GOTO_EXPENSE,
    GOTO_INCOME,
    GOTO_CATEGORIZE,
    GOTO_BUDGET,
    GOTO_ID_KOLL,

    OPEN_SAVINGS_ACCOUNT,
    ADD_PROVIDER,
    CREATE_SAVINGS_GOAL,
    CREATE_BUDGET,

    EDIT_BUDGET,
    EDIT_CREDENTIALS,
    EDIT_LOAN,
    EDIT_SAVINGS_GOAL,

    EXTERNAL_LINK
}
