java_library(
    name = "supplementalfields",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api/src/main/java/se/tink/backend/agents/rpc",
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/utils",
        "//src/libraries/i18n",
        "//third_party:org_apache_commons_commons_lang3",
    ],
)
