package se.tink.backend.aggregation.agents.utils.supplementalfields;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import se.tink.backend.agents.rpc.Field;
import se.tink.libraries.i18n_aggregation.Catalog;
import se.tink.libraries.i18n_aggregation.LocalizableKey;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class NorwegianFields {

    @NoArgsConstructor(access = AccessLevel.PRIVATE)
    public static class BankIdReferenceInfo {
        private static final String FIELD_KEY = "name";
        private static final LocalizableKey DESCRIPTION = new LocalizableKey("Reference");
        private static final LocalizableKey HELP_TEXT =
                new LocalizableKey(
                        "Open BankID on your mobile device, check that the reference words match and enter the PIN. Then continue the connection.");

        public static Field build(Catalog catalog, String bankIdReference) {
            return CommonFields.Information.build(
                    FIELD_KEY,
                    catalog.getString(DESCRIPTION),
                    bankIdReference,
                    catalog.getString(HELP_TEXT));
        }
    }

    @NoArgsConstructor(access = AccessLevel.PRIVATE)
    public static class BankIdOneTimeCodeField {

        /*
        We were not able to find any max length limit for BankID OTP codes
        */
        public static final String VALID_OTP_PATTERN = "^\\d{3}\\d*$";

        private static final String FIELD_KEY = "bankIdOneTimeCode";
        private static final int MIN_CODE_LENGTH = 3;

        private static final LocalizableKey DESCRIPTION = new LocalizableKey("One-time code");
        private static final LocalizableKey HELP_TEXT =
                new LocalizableKey(
                        "Please enter the one-time code generated by your token device.");
        private static final LocalizableKey PATTERN_ERROR =
                new LocalizableKey("One-time code must contain only digits.");

        public static Field build(Catalog catalog) {
            return Field.builder()
                    .name(FIELD_KEY)
                    .helpText(catalog.getString(HELP_TEXT))
                    .description(catalog.getString(DESCRIPTION))
                    .numeric(true)
                    .minLength(MIN_CODE_LENGTH)
                    .pattern(VALID_OTP_PATTERN)
                    .patternError(catalog.getString(PATTERN_ERROR))
                    .build();
        }
    }

    @NoArgsConstructor(access = AccessLevel.PRIVATE)
    public static class BankIdAppField {

        private static final LocalizableKey DESCRIPTION =
                new LocalizableKey(
                        "Confirm BankID authentication in your mobile BankID authentication app.");

        public static Field build(Catalog catalog) {
            return CommonFields.Instruction.build(catalog.getString(DESCRIPTION));
        }
    }
}
