filegroup(
    name = "local",
    srcs = glob(
        include = ["local/**/*"],
        exclude = [
            "BUILD",
        ],
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "ci",
    srcs = glob(
        include = ["ci/**/*"],
        exclude = [
            "BUILD",
        ],
    ),
    visibility = ["//visibility:public"],
)
