alias(
    name = "transfer_rpc",
    actual = "//src/integration/transfer:rpc",
    visibility = ["//src/agent_sdk/sdk:__subpackages__"],
)

alias(
    name = "transfer_enums",
    actual = "//src/integration/transfer:enums",
    visibility = ["//src/agent_sdk/sdk:__subpackages__"],
)
