package se.tink.agent.sdk.models.payments;

public enum ErrorReason {
    INVALID_EXECUTION_DATE,
    INVALID_REMITTANCE_INFORMATION_VALUE,
    INVALID_REMITTANCE_INFORMATION_TYPE,
    INVALID_SOURCE_ACCOUNT_MESSAGE,
    INVALID_AMOUNT,
    INVALID_DEBTOR,
    INVALID_CREDITOR,
    INVALID_BENEFICIARY,
    PAYMENT_REJECTED,
    AUTHORIZATION_CANCELLED,
    AUTHORIZATION_TIMEOUT,
    AUTHORIZATION_FAILED,
    INVALID_PERMISSIONS
}
