# Currently traffic in Denmark is not big - a few refreshes per hour
# Because we do not support all NemID authentication methods - let's call alerts when success rate is below 60% (currently one priority)
#
# It appears that "increase" function is not returning what we expect that it will return
# When you are not creating vector in prometheus it appears that data from last 30 minutes will be taken into consideration
#
# For every error type (failed: TEMPORARY_ERROR, cancelled: AUTHENTICATION_ERROR, unavailable: BANK SIDE ERROR),
# all gathered (3 combined), agent errors (failed + cancelled)
# there is one AllLoginSuccessRates alerts which does not split rates by action type
# and there is one SplitLoginSuccessRates which checks success rates of specific login type.
#
# Refreshes alerts are split by our own errors and bank side errors
#
kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-dk-ng
  namespace: agents
spec:
  rules:
    - alert: AllLoginSuccessRatesBelow60WithUnhandledErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider) (tink_agent_login_total{provider_type!="test", outcome=~"completed|unavailable|cancelled", market="DK"}))
            / (sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for all authentication types with unknown errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: SplitLoginSuccessRatesBelow60WithUnhandledErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", outcome=~"completed|unavailable|cancelled", market="DK"}))
            / (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"})) < 0.6
         and sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for one of login type with unknown errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: AllLoginSuccessRatesBelow60WithKnownErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider) (tink_agent_login_total{provider_type!="test", outcome=~"completed|unavailable|failed", market="DK"}))
            / (sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for all authentication types with known errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: SplitLoginSuccessRatesBelow60WithKnownErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", outcome=~"completed|unavailable|failed", market="DK"}))
            / (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"})) < 0.6
         and sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for one of login type with known errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: AllLoginSuccessRatesBelow60WithBankErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider) (tink_agent_login_total{provider_type!="test", outcome=~"completed|cancelled|failed", market="DK"}))
            / (sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for all authentication types with bank errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: SplitLoginSuccessRatesBelow60WithBankErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", outcome=~"completed|cancelled|failed", market="DK"}))
            / (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"})) < 0.6
         and sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for one of login type with bank errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: AllLoginSuccessRatesBelow60WithAllErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider) (tink_agent_login_total{provider_type!="test", outcome="completed", market="DK"}))
            / (sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for all authentication types with all errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: SplitLoginSuccessRatesBelow60WithAllErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", outcome="completed", market="DK"}))
            / (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"})) < 0.6
         and sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for one of login type with all errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: AllLoginSuccessRatesBelow60WithAgentErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider) (tink_agent_login_total{provider_type!="test", outcome=~"completed|unavailable", market="DK"}))
            / (sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (provider) (tink_agent_login_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for all authentication types with agent errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: SplitLoginSuccessRatesBelow60WithAgentErrorsAndAttemptLimitDK_NG
      expr: |
        (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", outcome=~"completed|unavailable", market="DK"}))
            / (sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"})) < 0.6
         and sum by (provider, action) (tink_agent_login_total{action=~"login-auto|login-manual|login-cron|is-logged-in|persist-login-session", provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
        annotations:
          description: {{ .Values.kibanaLink }}
            {{ .Values.grafanaLink }}
        summary: Login success rate for one of login type with agent errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: AgentRefreshesBelow60DueToBankServerErrorWithRateLimitDK_NG
      expr: |
        (sum by (className) (tink_agent_refresh_total{provider_type!="test", outcome=~"completed|failed", market="DK"}))
            / (sum by (className) (tink_agent_refresh_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (className) (tink_agent_refresh_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is below 60% because of bank issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: AgentRefreshesBelow60DueToAgentErrorsWithRateLimitDK_NG
      expr: |
        (sum by (className) (tink_agent_refresh_total{provider_type!="test", outcome=~"completed|unavailable", market="DK"}))
            / (sum by (className) (tink_agent_refresh_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (className) (tink_agent_refresh_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is below 60% because of agent issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"

    - alert: AgentRefreshesBelow60DueToAllErrorsWithRateLimitDK_NG
      expr: |
        (sum by (className) (tink_agent_refresh_total{provider_type!="test", outcome=~"completed", market="DK"}))
            / (sum by (className) (tink_agent_refresh_total{provider_type!="test", market="DK"})) < 0.6
         and sum by (className) (tink_agent_refresh_total{provider_type!="test", market="DK"}) > 2
      for: 5m
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is below 60% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes.
        tags: "{{ .Values.teletubbiesTags }}"
