# EXPERIMENTAL APPROACH ALERTS V. 3.0.
# Description available on the Confluence page:
# https://tinkab.atlassian.net/wiki/spaces/INT/pages/6036291705/
kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-dk
  namespace: agents
spec:
  interval: 10m
  rules:
    # =========== SHORT-TERM (1h) and MID-TERM (4h) ALERTS ===========
    - alert: RefreshErrorRateAbove20%DK
      # Avoid alert duplication caused by the rule below this one
      expr: 0.2 <= sum:failed_refreshes_per_type_dk:delta1h / (sum:all_refreshes_per_type_dk:delta1h >= 5) <= 0.9
      priority: P3
      for: 30m
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Refresh failures for <{ $labels.type }> over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: RefreshErrorRateAbove90%DK
      expr: sum:failed_refreshes_per_type_dk:delta1h / (sum:all_refreshes_per_type_dk:delta1h >= 5) > 0.9
      priority: P1
      for: 30m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Refresh failures for <{ $labels.type }> over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: LoginErrorRateAbove20%DK
      expr: 0.2 <= sum:failed_logins_dk:delta1h / (sum:all_logins_dk:delta1h >= 5) <= 0.9
      priority: P3
      for: 30m
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Login error rate over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: LoginErrorRateAbove90%DK
      expr: sum:failed_logins_dk:delta1h / (sum:all_logins_dk:delta1h >= 5) > 0.9
      for: 30m
      priority: P1
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Login error rate over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: BackgroundLoginErrorRateAbove90%DK
      expr: sum:unsuccessful_background_logins_dk:delta4h / (sum:all_logins_dk:delta4h >= 5) > 0.9
      priority: P2
      for: 30m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs4h }}
          {{ .Values.grafanaClassLinkAbs4h }}
        summary: Background login error rate over the last 4 hours is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: OnDemandLoginErrorRateAbove90%DK
      expr: sum:unsuccessful_on_demand_logins_dk:delta4h / (sum:all_logins_dk:delta4h >= 5) > 0.9
      for: 30m
      priority: P2
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs4h }}
          {{ .Values.grafanaClassLinkAbs4h }}
        summary: On-demand login error rate over the last 4 hours is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>
