kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-dk-long-term
  namespace: agents
spec:
  interval: 2h
  rules:
    # ALL LOGIN ATTEMPTS (12h)
    - record: increase:all_logins_dk:delta12h
      expr: floor(increase(tink_agent_login_total{action="login", market="DK", provider_type!="test"}[12h]))
    - record: sum:all_logins_dk:delta12h
      expr: |
        sum by (className) (
          (increase:all_logins_dk:delta12h
           and
           (tink_agent_login_total{action="login", market="DK", provider_type!="test"} offset 12h
            unless tink_agent_login_total{action="login", market="DK", provider_type!="test"}))
          or
          (1 + increase:all_logins_dk:delta12h - floor(count_over_time(tink_agent_login_total{action="login", market="DK", provider_type!="test"}[12h]) / 4320))
        )
        
    # UNAVAILABLE OR CANCELLED LOGINS (12h)
    - record: increase:unavailable_or_cancelled_logins_dk:delta12h
      expr: floor(increase(tink_agent_login_total{action="login", outcome=~"unavailable|cancelled.*", market="DK", provider_type!="test"}[12h]))
    - record: sum:unavailable_or_cancelled_logins_dk:delta12h
      expr: |
        sum by (className) (
          (increase:unavailable_or_cancelled_logins_dk:delta12h
           and
           (tink_agent_login_total{action="login", outcome=~"unavailable|cancelled.*", market="DK", provider_type!="test"} offset 12h
            unless tink_agent_login_total{action="login", outcome=~"unavailable|cancelled.*", market="DK", provider_type!="test"}))
          or
          (1 + increase:unavailable_or_cancelled_logins_dk:delta12h - floor(count_over_time(tink_agent_login_total{action="login", outcome=~"unavailable|cancelled.*", market="DK", provider_type!="test"}[12h]) / 4320))
        )

    # ALL REFRESH ATTEMPTS PER TYPE (12h)
    - record: increase:all_refreshes_per_type_dk:delta12h
      expr: floor(increase(tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"}[12h]))
    - record: sum:all_refreshes_per_type_dk:delta12h
      expr: |
        sum by (className, type) (
          (increase:all_refreshes_per_type_dk:delta12h
           and
           (tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"} offset 12h
            unless tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"}))
          or
          (1 + increase:all_refreshes_per_type_dk:delta12h - floor(count_over_time(tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"}[12h]) / 4320))
        )
        
    # UNAVAILABLE REFRESHES PER TYPE (12h)
    - record: increase:unavailable_refreshes_per_type_dk:delta12h
      expr: floor(increase(tink_agent_refresh_total{action="refresh", outcome="unavailable", market="DK", provider_type!="test"}[12h]))
    - record: sum:unavailable_refreshes_per_type_dk:delta12h
      expr: |
        sum by (className, type) (
          (increase:unavailable_refreshes_per_type_dk:delta12h
           and
           (tink_agent_refresh_total{action="refresh", outcome="unavailable", market="DK", provider_type!="test"} offset 12h
            unless tink_agent_refresh_total{action="refresh", outcome="unavailable", market="DK", provider_type!="test"}))
          or
          (1 + increase:unavailable_refreshes_per_type_dk:delta12h - floor(count_over_time(tink_agent_refresh_total{action="refresh", outcome="unavailable", market="DK", provider_type!="test"}[12h]) / 4320))
        )

    # =========== LONG-TERM (12h) ALERTS ===========
    - alert: LongTermBankOrUserErrorRateAbove90%DK
      expr: sum:unavailable_or_cancelled_logins_dk:delta12h / (sum:all_logins_dk:delta12h > 2) > 0.9
      labels:
        severity: urgent
        priority: P2
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs12h }}
          {{ .Values.grafanaClassLinkAbs12h }}
        summary: Bank-side or user login error failure rate over the last 12 hours is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>
        
    - alert: LongTermRefreshUnavailableErrorRateAbove90%DK
      expr: sum:unavailable_refreshes_per_type_dk:delta12h / (sum:all_refreshes_per_type_dk:delta12h > 2) > 0.9
      labels:
        severity: urgent
        priority: P2
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs12h }}
          {{ .Values.grafanaClassLinkAbs12h }}
        summary: Refresh of <{ $labels.type }> over the last 12 hours is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

