kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-dk-experimental
  namespace: agents
spec:
  interval: 5m
  rules:
    ## COUNTER VALUES WITH OFFSET ON OUTCOME
    ## Offset is used to "travel back" 30minutes and get the value of counters after first 30 minutes in 1 hour
    - record: sum:tink_agent_login_denmark:all:delta30m_with_offset_30m
      expr: |
        (sum by (className, action) ((max_over_time(tink_agent_login_total{market="DK", provider_type!="test"}[30m] offset 30m)) or
            0 * (sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test"}[60m])
            unless max_over_time(tink_agent_login_total{market="DK", provider_type!="test"}[30m] offset 30m)))))
    - record: sum:tink_agent_login_denmark:unavailable:delta30m_with_offset_30m
      expr: |
        (sum by (className, action) ((max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome="unavailable"}[30m] offset 30m)) or
            0 * (sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome="unavailable"}[60m])
            unless max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome="unavailable"}[30m] offset 30m)))))
    - record: sum:tink_agent_login_denmark:temporary_errors:delta30m_with_offset_30m
      expr: |
        (sum by (className, action) ((max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"failed|failed_due_to_tink_infrastructure_failure"}[30m] offset 30m)) or
            0 * (sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"failed|failed_due_to_tink_infrastructure_failure"}[60m])
            unless max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"failed|failed_due_to_tink_infrastructure_failure"}[30m] offset 30m)))))
    - record: sum:tink_agent_login_denmark:all_errors:delta30m_with_offset_30m
      expr: |
        (sum by (className, action) ((max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"cancelled|cancelled_due_to_third_party_app_timeout|unavailable|failed|failed_due_to_tink_infrastructure_failure"}[30m] offset 30m)) or
            0 * (sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"cancelled|cancelled_due_to_third_party_app_timeout|unavailable|failed|failed_due_to_tink_infrastructure_failure"}[60m])
            unless max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"cancelled|cancelled_due_to_third_party_app_timeout|unavailable|failed|failed_due_to_tink_infrastructure_failure"}[30m] offset 30m)))))

    ## COUNTER VALUES DEPENDING ON THE OUTCOME
    ## Delta60m = Means last hour
    - record: sum:tink_agent_login_denmark:all:delta60m
      expr: |
        sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test"}[60m]))
    - record: sum:tink_agent_login_denmark:unavailable:delta60m
      expr: |
        sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome="unavailable"}[60m]))
    - record: sum:tink_agent_login_denmark:temporary_errors:delta60m
      expr: |
        sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"failed|failed_due_to_tink_infrastructure_failure"}[60m]))
    - record: sum:tink_agent_login_denmark:all_errors:delta60m
      expr: |
        sum by (className, action) (max_over_time(tink_agent_login_total{market="DK", provider_type!="test", outcome=~"cancelled|cancelled_due_to_third_party_app_timeout|unavailable|failed|failed_due_to_tink_infrastructure_failure"}[60m]))

    ## REAL NUMBER OF OCCURRENCES OF CERTAIN EVENTS
    ## This number is a difference between 60m - and 30m with 30m offset
    - record: sum:tink_agent_login_denmark:effectively_all:delta30m
      expr: |
        sum:tink_agent_login_denmark:all:delta60m - sum:tink_agent_login_denmark:all:delta30m_with_offset_30m
    - record: sum:tink_agent_login_denmark:effectively_all_unavailable:delta30m
      expr: |
        sum:tink_agent_login_denmark:unavailable:delta60m - sum:tink_agent_login_denmark:unavailable:delta30m_with_offset_30m
    - record: sum:tink_agent_login_denmark:effectively_all_temporary_errors:delta30m
      expr: |
        sum:tink_agent_login_denmark:temporary_errors:delta60m - sum:tink_agent_login_denmark:temporary_errors:delta30m_with_offset_30m
    - record: sum:tink_agent_login_denmark:effectively_all_errors:delta30m
      expr: |
        sum:tink_agent_login_denmark:all_errors:delta60m - sum:tink_agent_login_denmark:all_errors:delta30m_with_offset_30m

    ## Percentage of occurrence of specific type of event comparing to number of all events
    ## Service level is number of faulty refreshes comparing to all refreshes
    - record: service_level:tink_agent_login_denmark:unavailable:delta30m
      expr: |
        (sum:tink_agent_login_denmark:effectively_all_unavailable:delta30m) / (sum:tink_agent_login_denmark:effectively_all:delta30m)
    - record: service_level:tink_agent_login_denmark:temporary_error:delta30m
      expr: |
        (sum:tink_agent_login_denmark:effectively_all_temporary_errors:delta30m) / (sum:tink_agent_login_denmark:effectively_all:delta30m)
    - record: service_level:tink_agent_login_denmark:all_errors:delta30m
      expr: |
        (sum:tink_agent_login_denmark:effectively_all_errors:delta30m) / (sum:tink_agent_login_denmark:effectively_all:delta30m)

    #-------------------------------------------------------------------------------------------------------------------
    # Login Errors
    #-------------------------------------------------------------------------------------------------------------------
    - alert: LoginUnavailableErrorRateHigherThan20%DK
      expr: |
        service_level:tink_agent_login_denmark:unavailable:delta30m > 0.2
          and sum:tink_agent_login_denmark:effectively_all:delta30m > 5
      for: 15m
      priority: P4
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }} {{ .Values.grafanaClassLinkAbs1h }}
        summary: Login unavailable rate is <{ $value | humanizePercentage }> for <{ $labels.className }> for the last 30m
        tags: {{ .Values.tags }}
    - alert: LoginTemporaryErrorsRateHigherThan10%DK
      expr: |
        service_level:tink_agent_login_denmark:temporary_errors:delta30m > 0.1
          and sum:tink_agent_login_denmark:effectively_all:delta30m > 5
      for: 15m
      priority: P4
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }} {{ .Values.grafanaClassLinkAbs1h }}
        summary: Login temporary errors rate is <{ $value | humanizePercentage }> for <{ $labels.className }> for the last 30m
        tags: {{ .Values.tags }}
    - alert: LoginAllErrorsRateHigherThan90%DK
      expr: |
        service_level:tink_agent_login_denmark:all_errors:delta30m > 0.9
          and sum:tink_agent_login_denmark:effectively_all:delta30m > 5
      for: 15m
      priority: P4
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }} {{ .Values.grafanaClassLinkAbs1h }}
        summary: Login all errors rate is <{ $value | humanizePercentage }> for <{ $labels.className }> for the last 30m
        tags: {{ .Values.tags }}
