kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-dk
  namespace: agents
spec:
  interval: 5m
  rules:
    - record: sum:unsuccessful_refreshes_by_type_dk:delta1h
      expr: sum by (className, type) (internal:sum:all_refreshes_by_type_outcome_dk:delta1h{outcome!="completed"})
    - record: sum:refreshes_by_type_dk:delta1h
      expr: sum by (className, type) (internal:sum:all_refreshes_by_type_outcome_dk:delta1h)

    - alert: RefreshFailureRateAbove20%DK
      expr: 0.2 <= sum:unsuccessful_refreshes_by_type_dk:delta1h / (sum:refreshes_by_type_dk:delta1h >= 3) < 0.75
      for: 10m
      labels:
        priority: P3
        severity: ping
        who: integration-llamas
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
        summary: <{ $value | humanizePercentage }> refresh failure rate of <{ $labels.type }> by <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - alert: RefreshFailureRateAbove75%DK
      expr: sum:unsuccessful_refreshes_by_type_dk:delta1h / (sum:refreshes_by_type_dk:delta1h >= 3) >= 0.75
      for: 10m
      labels:
        priority: P1
        severity: urgent
        who: integration-llamas
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
        summary: <{ $value | humanizePercentage }> refresh failure rate of <{ $labels.type }> by <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - record: sum:failed_logins_by_type_dk:delta1h
      expr: sum by (className, login_type) (internal:sum:all_logins_by_type_outcome_dk:delta1h{outcome=~"failed.*"})
    - record: sum:non_auth_error_logins_by_type_dk:delta1h
      expr: sum by (className, login_type) (internal:sum:all_logins_by_type_outcome_dk:delta1h{outcome!~"cancelled.*"})

    - alert: LoginFailureRateAbove20%DK
      expr: 0.2 <= sum:failed_logins_by_type_dk:delta1h / (sum:non_auth_error_logins_by_type_dk:delta1h >= 3) < 0.75
      for: 10m
      labels:
        priority: P3
        severity: ping
        who: integration-llamas
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
        summary: <{ $value | humanizePercentage }> <{ $labels.login_type }> login failure rate (excluding authentication errors) for <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - alert: LoginFailureRateAbove75%DK
      expr: 0.2 <= sum:failed_logins_by_type_dk:delta1h / (sum:non_auth_error_logins_by_type_dk:delta1h >= 3) >= 0.75
      for: 10m
      labels:
        priority: P1
        severity: urgent
        who: integration-llamas
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
        summary: <{ $value | humanizePercentage }> <{ $labels.login_type }> login failure rate (excluding authentication errors) for <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - alert: BankSideErrorLoginRateAbove30%DK
      expr: |
        sum by (className) (internal:sum:all_logins_by_type_outcome_dk:delta1h{outcome="unavailable"}) 
        / 
        (sum by (className) (internal:sum:all_logins_by_type_outcome_dk:delta1h{outcome!~"cancelled.*"}) >= 3) >= 0.3
      for: 10m
      labels:
        priority: P1
        severity: urgent
        who: integration-llamas
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
        summary: <{ $value | humanizePercentage }> bank-side login failure rate (excluding authentication errors) for <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>
