kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-dk-long-term
  namespace: agents
spec:
  interval: 1h
  rules:
    - alert: UserLoginErrorRateAbove75%DK
      expr: |
        sum by (className) (sum_over_time(internal:sum:all_logins_by_outcome_action_dk:delta1h{outcome=~"cancelled.*"}[4h:1h]))
        /
        (sum by (className) (sum_over_time(internal:sum:all_logins_by_outcome_action_dk:delta1h[4h:1h])) >= 3) > 0.75
      labels:
        priority: P3
        severity: ping
        who: integration-teletubbies
      annotations:
        # magic string to enable keyword-based Slack notifications
        # without sending an alert to opsgenie
        description: <{{ .Values.kibanaClassLinkAbs4h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs4h }} |Grafana>
          TUBBIES_EXPERIMENTAL
        summary: <{ $value | humanizePercentage }> bank-side or user error login error rate for <{ $labels.className }> over the last 4 hours.
        tags: <{ $labels.className }>

    # for every hour within last 24 hours in which there was any traffic for a specific agent,
    # assign 1 if any request ended up with outcome="unavailable", 0 otherwise
    # average of these will give us an approximate downtime ratio
    - alert: BankUnavailabilityAbove50%DK
      expr: |
        avg_over_time(
          (group by (className) (internal:sum:all_logins_by_outcome_action_dk:delta1h{outcome="unavailable"})
           or
           0 * group by (className) (internal:sum:all_logins_by_outcome_action_dk:delta1h)
        )[24h:1h])
      labels:
        priority: P2
        severity: ping
        who: integration-teletubbies
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs24h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs24h }} |Grafana>
          TUBBIES_EXPERIMENTAL
        summary: <{ $value | humanizePercentage }> bank unavailability for <{ $labels.className }> over the last 24 hours.
        tags: <{ $labels.className }>
