# Description on how events are counted in this approach is available on the Confluence page:
# https://tinkab.atlassian.net/wiki/spaces/INT/pages/6036291705/
kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: dk-recording-rules
  namespace: agents
spec:
  interval: 2m30s
  rules:
    # Recording rules with 'internal' prefix are not meant to be used in alerting rules,
    # but rather to build other recording rules or for graphing purposes, e.g. in Grafana.
    # They come with labels which allows for easier aggregation across different markets within a team.
    # Grouping is done implicitly per agent.

    # Interval is set to 2m30s so that the rules are always available for querying in
    # Thanos querier or Grafana (metrics become stale after 5 minutes)

    # Query selector 'tink_agent_login_total{...}' can be cached in a recording rule to avoid repetition,
    # but this effectively caches most of the metric which is very ineffective disk storage-wise
    - record: internal:sum:all_logins_by_outcome_action_dk:delta1h
      expr: |
        sum by (className, action, outcome) (
          (floor(increase(tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="DK", provider_type!="test"}[1h]))
           and
           (tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="DK", provider_type!="test"} offset 1h
            unless tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="DK", provider_type!="test"}))
          or (1 + floor(increase(tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="DK", provider_type!="test"}[1h])) - floor(count_over_time(tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="DK", provider_type!="test"}[1h]) / 360))
        ) > 0

    - record: internal:sum:all_refreshes_by_type_outcome_dk:delta1h
      expr: |
        sum by (className, type, outcome) (
          (floor(increase(tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"}[1h]))
           and
           (tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"} offset 1h
            unless tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"}))
          or
          (1 + floor(increase(tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"}[1h])) - floor(count_over_time(tink_agent_refresh_total{action="refresh", market="DK", provider_type!="test"}[1h]) / 360))
        ) > 0
