load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "predicates",
    srcs = glob(
        ["*.java"],
    ),
    data = [
    ],
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
    ],
)
