load("@tink_backend//tools/bzl:junit_strict.bzl", "junit_test")

junit_test(
    name = "operation",
    srcs = glob(["*.java"]),
    data = [],
    resources = [],
    deps = [
        "//src/agent_sdk/runtime/src/main/java/operation",
    ],
)
