load("//tools/bzl:junit.bzl", "junit_test")

junit_test(
    name = "utilities",
    srcs = glob(["**/*.java"]),
    tags = [
        "external",
        "manual",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/agents/src/main/java/se/tink/backend/aggregation/agents/nxgen/se/banks/swedbank",
    ],
)
