load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "account",
    intdeps = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/nxgen/core/account",
    ],
    visibility = [
        "//src/agent_sdk/sdk:__subpackages__",
    ],
    exports = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/nxgen/core/account",
    ],
)
