# Note: Change this to `java_library_with_sources(intdeps = [".../nxgen/core/account"])` once that target uses `java_library_with_sources`.
alias(
    name = "account",
    actual = "//src/integration/lib/src/main/java/se/tink/backend/aggregation/nxgen/core/account",
    visibility = ["//src/agent_sdk/sdk:__subpackages__"],
)
