java_library(
    name = "screenscraping",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib",
        "//src/libraries/selenium",
        "@selenium//:org_seleniumhq_selenium_selenium_api",
    ],
)
