load("@rules_codeowners//tools:codeowners.bzl", "codeowners", "generate_codeowners")

package(default_visibility = ["//visibility:public"])

codeowners(
    name = "owners",
    team = "@tink-ab/engineering-productivity-maintainer",
)
