steps:

  - name: ':white_check_mark: Test'
    branches: '!master'
    command: .buildkite/run-unit-tests.sh
    timeout_in_minutes: 30
    plugins:
      docker-compose#v2.5.1:
        run: "app"
        config: "docker/docker-compose.bazel.yml"

  - name: ":kubernetes: Helm Lint"
    branches: '!master'
    command: /go/bin/kubernetes-generator --mode lint --repo .
    timeout_in_minutes: 5
    agents:
      queue: new
    plugins:
      docker#v2.0.0:
        image: gcr.io/tink-containers/kubernetes-generator:latest
        always-pull: true

  - wait

  - name: ':docker: Build and Upload'
    branches: 'staging'
    command: .buildkite/build-and-push-docker.sh
    plugins:
      docker-compose#v2.5.1:
        run: "app"
        config: "docker/docker-compose.bazel.yml"
    timeout_in_minutes: 30

  - name: ':debian: Build and Upload'
    branches: 'staging'
    command: .buildkite/build-and-upload-deb.sh
    plugins:
      docker-compose#v2.5.1:
        run: "app"
        config: "docker/docker-compose.bazel.yml"
    timeout_in_minutes: 30

  - wait

  - name: ':pipeline: Generate trigger steps'
    branches: 'master'
    command: .buildkite/generate-trigger-steps-master.py | buildkite-agent pipeline upload
