steps:

  - name: ':junit: Test'
    branches: '!master'
    command: .buildkite/run-unit-tests.sh
    timeout_in_minutes: 30
    agents:
      queue: default
    plugins:
      docker-compose#v3.0.3:
        run: "app"
        config: "docker/docker-compose.bazel.yml"
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - name: ':codecov: Test Coverage'
    branches: '!master'
    command: .buildkite/run-code-coverage.sh
    timeout_in_minutes: 30
    agents:
      queue: default
    plugins:
      docker-compose#v3.0.3:
        run: "app"
        config: "docker/docker-compose.bazel.yml"
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - name: ":sonarqube: Sonarqube"
    if: |
      build.branch != 'master' && build.branch != 'staging'
    command: .buildkite/run-sonar.sh
    timeout_in_minutes: 30
    agents:
      queue: default
    plugins:
      docker-compose#v3.0.3:
        run: "app"
        config: "docker/docker-compose.bazel.yml"
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - name: ":kubernetes: Helm Lint"
    branches: '!master'
    command: /go/bin/kubernetes-generator --mode lint --repo .
    timeout_in_minutes: 10
    agents:
      queue: default
    plugins:
      docker#v2.0.0:
        image: gcr.io/tink-containers/kubernetes-generator:latest
        always-pull: true
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - command: .buildkite/check-bazel-style.sh
    plugins:
      docker#v2.2.0:
        image: gcr.io/tink-containers/golang:1.11
        always-pull: true
    branches: '!master'
    name: ':bazel: Check BUILD style'
    timeout_in_minutes: 10
    agents:
      queue: default
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - command: .buildkite/check-java-style.sh
    plugins:
      docker-compose#v3.0.3:
        run: app
        config: docker/docker-compose.bazel.yml
    branches: '!master'
    name: ':java: Check Java style'
    timeout_in_minutes: 30
    agents:
      queue: default
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - name: ':male-detective: run detect-secrets on new commits'
    command: "/bin/sh /opt/detect-secrets"
    soft_fail:
      - exit_status: 1
    plugins:
      - docker#v3.3.0:
          image: gcr.io/tink-containers/detect-secrets:latest
          always-pull: true

  - wait

  - name: ':docker: tink-backend-aggregation'
    branches: 'staging'
    command: .buildkite/build-and-push-docker.sh //docker:aggregation_push
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.0.3:
        run: "app"
        config: "docker/docker-compose.bazel.yml"
    agents:
      queue: default
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - name: ':docker: tink-backend-aggregation-statuspage-providers-cronjob'
    branches: 'staging'
    command: .buildkite/build-and-push-python-docker.sh
    timeout_in_minutes: 10
    plugins:
      docker-compose#v3.0.3:
        run: "app"
        config: "docker/docker-compose.bazel.yml"
    agents:
      queue: default
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}

  - wait

  - name: ':pipeline: Generate trigger steps'
    branches: 'master'
    command: .buildkite/generate-trigger-steps-master.py | buildkite-agent pipeline upload
    agents:
      queue: default
    retry: {"automatic": [{"exit_status": -1, "limit": 2}, {"exit_status": 255, "limit": 2}]}
