kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-pt
  namespace: agents
spec:
  rules:

    #-------------------------------------------------------------------------------------------------------------------
    # All errors alerts
    #-------------------------------------------------------------------------------------------------------------------
    # Authentication alerts
    - alert: AuthenticationErrorRateOver50%PT
      expr: |
        # Failed logins over 50%
        (sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", outcome="completed", market="PT", provider_type!="test"}[30m])) by (action,className,provider)
            / sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[30m])) by (action,className,provider) < 0.5)
        # At least this many attempts.
            and sum(sum_over_time(tink_agent_login_total{action=~"login", market="PT", provider_type!="test"}[30m])) by (className,provider) > 3
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures 50% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
          the last hour.
        tags: {{ .Values.tags }}

    # Refresh alerts
    - alert: RefreshErrorRateOver20%PT
      expr: |
        # Failed refreshes over 20%
        (sum(sum_over_time(tink_agent_refresh_total{label="refresh", outcome="completed", market="PT", provider_type!="test"}[30m])) by (className,provider,type)
            / sum(sum_over_time(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider,type) < 0.2)
      for: 5m
      labels:
        severity: urgent
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh failures is over 20% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    #-------------------------------------------------------------------------------------------------------------------
    # Unknown errors (due to RuntimeException) alerts
    #-------------------------------------------------------------------------------------------------------------------
    # Authentication alerts
    - alert: AuthenticationUnknownErrorRateOver5%PT
      expr: |
        # Failed logins (due to unknown RuntimeException) over 10%
        (sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", outcome="failed", market="PT", provider_type!="test"}[30m])) by (action,className,provider)
            / sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[30m])) by (action,className,provider) > 0.1)
      for: 5m
      labels:
        severity: urgent
        priority: P2
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures due to unknown RuntimeExceptions is over 10% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
          the last hour.
        tags: {{ .Values.tags }}

    # Refresh alerts
    - alert: RefreshUnknownErrorRateOver10%PT
      expr: |
        # Failed refreshes (due to unknown RuntimeException) over 10%
        (sum(sum_over_time(tink_agent_refresh_total{label="refresh", outcome="failed", market="PT", provider_type!="test"}[30m])) by (className,provider,type)
            / sum(sum_over_time(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider,type) > 0.1)
      for: 5m
      labels:
        severity: urgent
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh failures due to unknown RuntimeExceptions is over 10% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    #-------------------------------------------------------------------------------------------------------------------
    # Bank site errors alerts
    #-------------------------------------------------------------------------------------------------------------------
    # Authentication alerts
    - alert: ManualAuthenticationBankSiteErrorRateOver90%PT
      expr: |
        # Failed logins (due to bank site errors) over 90%
        sum(sum_over_time(tink_agent_login_total{action="login",outcome="unavailable", market="PT"}[4h])) BY (className,provider)
        # All login attempts the last 4 hours
          / sum(sum_over_time(tink_agent_login_total{action=~"login", market="PT"}[4h])) BY (className,provider) > 0.90
        # At least this many attempts.
           and sum(sum_over_time(tink_agent_login_total{action=~"login", market="PT", provider_type!="test"}[4h])) by (className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Manual authentication failures due to bank site errors is over 90% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
        tags: {{ .Values.tags }}

    - alert: AutoAuthenticationBankSiteErrorRateOver90%PT
      expr: |
        # Failed logins (due to bank site errors) over 90%
        sum(sum_over_time(tink_agent_login_total{action="is-logged-in",outcome="unavailable", market="PT"}[4h])) BY (className,provider)
        # All login attempts the last 4 hours
          / sum(sum_over_time(tink_agent_login_total{action=~"is-logged-in", market="PT"}[4h])) BY (className,provider) > 0.90
        # At least this many attempts.
           and sum(sum_over_time(tink_agent_login_total{action=~"is-logged-in", market="PT", provider_type!="test"}[4h])) by (className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Auto authentication failures due to bank site errors is over 90% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
        tags: {{ .Values.tags }}


    - alert: LongTermAuthenticationBankSiteErrorRateOver90%PT
      expr: |
        # Failed logins (due to bank site errors) over 90%
        sum(sum_over_time(tink_agent_login_total{action="login|is-logged-in",outcome="unavailable", market="PT"}[12h])) BY (className,provider)
        # All login attempts the last 6 hours
          / sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", market="PT"}[6h])) BY (className,provider) > 0.90
      for: 1m
      labels:
        severity: urgent
        priority: P1
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures due to bank site errors is over 90% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
        tags: {{ .Values.tags }}

    # Refresh alerts
    - alert: RefreshBankSiteErrorRateOver90%PT
      expr: |
        # Failed refreshes (due to bank site errors) over 90%
        (sum(sum_over_time(tink_agent_refresh_total{label="refresh", outcome="unavailable", market="PT", provider_type!="test"}[4h])) by (className,provider)
            / sum(sum_over_time(tink_agent_refresh_total{market="PT", provider_type!="test"}[4h])) by (className,provider,type) > 0.90)
        # At least this many attempts.
           and sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[4h])) by (className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh failures due to bank site errors is over 90% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
        tags: {{ .Values.tags }}

    - alert: LongTermRefreshBankSiteErrorRateOver90%PT
      expr: |
        # Failed refresh (due to bank site errors) over 90%
        (sum(sum_over_time(tink_agent_refresh_total{label="refresh", outcome="unavailable", market="PT", provider_type!="test"}[12h])) by (className,provider)
            / sum(sum_over_time(tink_agent_refresh_total{market="PT", provider_type!="test"}[6h])) by (className,provider) > 0.90)
      for: 1m
      labels:
        severity: urgent
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh failures due to bank site errors is over 90% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
        tags: {{ .Values.tags }}


    #-------------------------------------------------------------------------------------------------------------------
    # Cancelled errors alerts
    #-------------------------------------------------------------------------------------------------------------------
    # Authentication alerts
    - alert: AuthenticationUserCancellationRateOver50%PT
      expr: |
        # Failed logins (due to user cancellation) over 50%
        sum(sum_over_time(tink_agent_login_total{action="login|is-logged-in",outcome=~"cancelled|cancelled_due_to_third_party_app_timeout", market="PT"}[2h])) BY (className,provider)
        # All login attempts the last 3 hours
          / sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", market="PT"}[2h])) BY (className,provider) > 0.50
        # At least this many attempts.
           and sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[2h])) by (className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures due to user cancelletion is over 50% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
        tags: {{ .Values.tags }}

    - alert: LongTermAuthenticationUserCancellationDueToThirdPartyAppTimeoutRateOver50%PT
      expr: |
        # Failed logins (due to third party app timeout) over 90%
        sum(sum_over_time(tink_agent_login_total{action="login|is-logged-in",outcome="cancelled_due_to_third_party_app_timeout", market="PT"}[6h])) BY (className,provider)
        # All login attempts the last 6 hours
          / sum(sum_over_time(tink_agent_login_total{action=~"login|is-logged-in", market="PT"}[6h])) BY (className,provider) > 0.90
      for: 1m
      labels:
        severity: urgent
        priority: P1
        who: integration-minions
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures due to user cancelletion is over 90% (<{ $value }>%) for <{ $labels.className }> ( <{ $labels.provider }>
        tags: {{ .Values.tags }}