alias(
    name = "client-lib",
    actual = "//src/integration/agent_data_availability_tracker/lib/src/main/java/se/tink/backend/integration/agent_data_availability_tracker/client:agent-data-availability-tracker-client-lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "client-lib-test",
    actual = "//src/integration/agent_data_availability_tracker/lib/src/test/java/se/tink/backend/integration/agent_data_availability_tracker/client:agent-data-availability-tracker-client-lib-test",
)
