java_library(
    name = "impl",
    srcs = glob(["*.java"]),
    visibility = ["//src/integration/lib/src/main/java/se/tink/backend/aggregation/compliance/account_classification:__subpackages__"],
    deps = [
        "//src/integration/api/src/main/java/se/tink/backend/agents/rpc",
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/compliance/account_capabilities",
    ],
)
