java_library(
    name = "credentials_requests",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/agents-api",
        "//src/libraries/user:rpc",
        "//src/libraries/strings",
        "//src/libraries/generic_application:generic-application",
        "//src/libraries/signableoperation:rpc",
        "//third_party:com_google_guava_guava",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//third_party:commons_codec_commons_codec",
    ],
)
