package se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.component.authenticator.detail;

import java.util.HashMap;
import java.util.Map;
import org.junit.Ignore;
import se.tink.backend.aggregation.agents.nxgen.pt.banks.novobanco.authenticator.rpc.Login0Response;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public class Login0TestData {
    public static final String SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN";
    public static final String INCORRECT_CREDENTIALS = "INCORRECT_CREDENTIALS";
    public static final String FAILED_REQUEST_REJECTED = "FAILED_REQUEST_REJECTED";
    private static final Map<String, String> requests = new HashMap<>();

    public static Login0Response getResponse(String payloadLabel) {
        return SerializationUtils.deserializeFromString(
                requests.get(payloadLabel), Login0Response.class);
    }

    static {
        requests.put(
                FAILED_REQUEST_REJECTED,
                "{\n"
                        + "  \"Header\": {\n"
                        + "    \"ResponseId\": \"821079cc56c740fdb445737147c0452a\",\n"
                        + "    \"OpToken\": null,\n"
                        + "    \"Time\": \"2019-11-07T11:46:25.7849391Z\",\n"
                        + "    \"SessionTimeout\": 0,\n"
                        + "    \"Status\": {\n"
                        + "      \"Mensagem\": \"Não foi possível efectuar o acesso ao serviço. Por favor tente mais tarde.\",\n"
                        + "      \"Severidade\": 3,\n"
                        + "      \"Codigo\": 50\n"
                        + "    }\n"
                        + "  }\n"
                        + "}");

        requests.put(
                INCORRECT_CREDENTIALS,
                "{  \n"
                        + "   \"Header\":{  \n"
                        + "      \"ResponseId\":\"06bdc6ddbfff4c088b7c645065a4d3e1\",\n"
                        + "      \"OpToken\":null,\n"
                        + "      \"Time\":\"2019-11-29T21:00:04.7561665Z\",\n"
                        + "      \"SessionTimeout\":0,\n"
                        + "      \"Status\":{  \n"
                        + "         \"Mensagem\":\"O NBnet está momentaneamente indisponível. Por favor tente mais tarde\",\n"
                        + "         \"Severidade\":3,\n"
                        + "         \"Codigo\":32\n"
                        + "      }\n"
                        + "   },\n"
                        + "   \"Body\":{  \n"
                        + "\n"
                        + "   },\n"
                        + "   \"Login\":{  \n"
                        + "\n"
                        + "   }\n"
                        + "}");

        requests.put(
                SUCCESSFUL_LOGIN,
                "{\n"
                        + "  \"Header\": {\n"
                        + "    \"ResponseId\": \"7e0238425d264366b84fe41457f01956\",\n"
                        + "    \"OpToken\": null,\n"
                        + "    \"Time\": \"2019-11-07T08:51:02.4442377Z\",\n"
                        + "    \"SessionTimeout\": 0,\n"
                        + "    \"Status\": {\n"
                        + "      \"Severidade\": 0,\n"
                        + "      \"Codigo\": 0\n"
                        + "    }\n"
                        + "  },\n"
                        + "  \"Conteudos\": {\n"
                        + "    \"ConteudoTeaser\": {\n"
                        + "      \"Teaser\": \"<a href=\\\"https://apps.apple.com/pt/app/nb-smart-app/id1011901080\\\">Classifique a NB smart app. Clique aqui.</a>\",\n"
                        + "      \"Chave\": \"86909666cee143779a996a47ff8b295e\",\n"
                        + "      \"DataInicio\": \"0001-01-01T00:00:00Z\",\n"
                        + "      \"DataFim\": \"9999-12-31T23:59:59.9999999Z\"\n"
                        + "    },\n"
                        + "    \"Campanhas\": [{\n"
                        + "      \"Campanha\": \"tudoverde\",\n"
                        + "      \"Img\": \"Img.axd?k=zyuG9j0qMEf3wiJ3ac7bhuc75ByhKd121IM9n006y2s%3d&r=1\",\n"
                        + "      \"Chave\": \"c281b7add8554490805ee8b87ba1cdf6\",\n"
                        + "      \"DataInicio\": \"0001-01-01T00:00:00Z\",\n"
                        + "      \"DataFim\": \"9999-12-31T23:59:59.9999999Z\"\n"
                        + "    }],\n"
                        + "    \"ConteudoLogout\": {\n"
                        + "      \"Conteudo\": \"<a href=\\\"http://onelink.to/ts3byu\\\"> <img src=\\\"https://www.novobanco.pt/site/images/crm_mobile/LogOut_AvaliacaoStores.png\\\" alt=\\\"fish\\\" width=\\\"255\\\"></a>\"\n"
                        + "    }\n"
                        + "  },\n"
                        + "  \"Body\": {\n"
                        + "    \"Session\": {\n"
                        + "      \"Application\": 1,\n"
                        + "      \"Media\": 18,\n"
                        + "      \"AuthCookie\": \"AA9DB35F05622871B3A25293CDB9B2DA5B8EEFFFC8BC79AEB50DE53594ADA8CFCA7E5B95E0D71F5ECFE4A3BAFDF14E462C6B31E6A7747ED799BCDEF98BFFEA3DD7D3D2CC55B2556D636795A5\",\n"
                        + "      \"SessionCookie\": \"jyamcgqb0j4tpy1ms3dvzm\"\n"
                        + "    },\n"
                        + "    \"Client\": {\n"
                        + "      \"IDPN\": \"04311342\",\n"
                        + "      \"Img\": \"Img.axd?k=IiL9hqlNCwYL8obC1P6BJ5puyAp5FEp2PM0c9Sgi4ag%3d&r=1\",\n"
                        + "      \"Nome\": \"SOMEONE FANCY\",\n"
                        + "      \"NomeAbrev\": \"SOMEONE FANCY\",\n"
                        + "      \"Sexo\": \"Masculino\",\n"
                        + "      \"Telemovel\": \"1212121212\",\n"
                        + "      \"Email\": \"someonefancy_tink@fancy_tink.com\",\n"
                        + "      \"Segmento\": \"3\",\n"
                        + "      \"Categoria\": \"36\",\n"
                        + "      \"Adesao\": \"1111111\",\n"
                        + "      \"UltimoLogin\": \"2019-11-07T08:48:39.453Z\",\n"
                        + "      \"NumeroMensagensNaoLidas\": 1\n"
                        + "    },\n"
                        + "    \"Device\": {\n"
                        + "      \"Id\": \"a1d0c6a741b14eb3a19850035f75e79f\"\n"
                        + "    },\n"
                        + "    \"Env\": {\n"
                        + "      \"MenuVersion\": \"{418d57ae-203d-47eb-be94-028638d4a387}\",\n"
                        + "      \"FavVersion\": \"637087134634738701\",\n"
                        + "      \"Language\": \"PT\",\n"
                        + "      \"Menu\": {\n"
                        + "        \"Itens\": [{\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"6000\",\n"
                        + "          \"Descricao\": \"Consultas\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"194\",\n"
                        + "            \"Descricao\": \"Posição Integrada\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"3396\",\n"
                        + "            \"Descricao\": \"Saldos e Movimentos\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6080\",\n"
                        + "            \"Descricao\": \"Extratos\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"6079\",\n"
                        + "              \"Descricao\": \"Extratos de Conta\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"1443\",\n"
                        + "              \"Descricao\": \"Extratos do Cartão de Crédito\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6085\",\n"
                        + "            \"Descricao\": \"Débitos Diretos\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"1648\",\n"
                        + "              \"Descricao\": \"Autorizações\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"1716\",\n"
                        + "              \"Descricao\": \"Movimentos \"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"40\",\n"
                        + "            \"Descricao\": \"NIB, IBAN e SWIFT\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"874\",\n"
                        + "            \"Descricao\": \"Pagamentos de Baixo Valor\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"2540\",\n"
                        + "            \"Descricao\": \"Assinatura de Documentos\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"25\",\n"
                        + "            \"Descricao\": \"Histórico de Operações\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"176\",\n"
                        + "            \"Descricao\": \"Operações Agendadas\"\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"6028\",\n"
                        + "          \"Descricao\": \"Poupanças\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"5955\",\n"
                        + "            \"Descricao\": \"Constituição de Poupanças\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"158\",\n"
                        + "            \"Descricao\": \"Dossier de Fundos\",\n"
                        + "            \"Novo\": true\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6062\",\n"
                        + "            \"Descricao\": \"Poupança por Objetivos\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"2559\",\n"
                        + "            \"Descricao\": \"Gestão de Poupanças\"\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"6090\",\n"
                        + "          \"Descricao\": \"Orçamento Familiar\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"6093\",\n"
                        + "            \"Descricao\": \"O meu Orçamento\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6091\",\n"
                        + "            \"Descricao\": \"Lista de Movimentos\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6092\",\n"
                        + "            \"Descricao\": \"Movimentos não Classificados\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6094\",\n"
                        + "            \"Descricao\": \"Ativar / Desativar\"\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"6001\",\n"
                        + "          \"Descricao\": \"Cartões\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"3393\",\n"
                        + "            \"Descricao\": \"Saldos de Cartões\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"2048\",\n"
                        + "            \"Descricao\": \"Movimentos Cartões\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"405\",\n"
                        + "            \"Descricao\": \"Cash-Advance\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"563\",\n"
                        + "            \"Descricao\": \"Pagamentos a Prestações\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6081\",\n"
                        + "            \"Descricao\": \"Pagar Cartão de Crédito\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6033\",\n"
                        + "            \"Descricao\": \"Cartão Virtual MB NET\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"6026\",\n"
                        + "              \"Descricao\": \"Cartão Virtual MB NET\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6027\",\n"
                        + "              \"Descricao\": \"Gestão de Cartões Virtuais\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"3471\",\n"
                        + "            \"Descricao\": \"3D Secure - Compras Online\"\n"
                        + "          }, {\n"
                        + "            \"Tipo\": 2,\n"
                        + "            \"Descricao\": \"Cancelar Cartão\",\n"
                        + "            \"Url\": \"https://www.novobanco.pt/site/cms.aspx?labelid=cancelamentocartoesmobile\"\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"3459\",\n"
                        + "          \"Descricao\": \"Transferências\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"6070\",\n"
                        + "            \"Descricao\": \"Executar Transferência\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"3029\",\n"
                        + "              \"Descricao\": \"Nacional ou Zona Euro\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"3526\",\n"
                        + "              \"Descricao\": \"Entre Contas Próprias\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6072\",\n"
                        + "              \"Descricao\": \"Para Beneficiário\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"3731\",\n"
                        + "              \"Descricao\": \"Para Telemóvel\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6071\",\n"
                        + "              \"Descricao\": \"Reutilizar Transferência\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6097\",\n"
                        + "            \"Descricao\": \"Ordens Permanentes\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"219\",\n"
                        + "              \"Descricao\": \"Criar Ordens Permanentes\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"218\",\n"
                        + "              \"Descricao\": \"Gestão de Ordens Permanentes\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Tipo\": 2,\n"
                        + "            \"Descricao\": \"NBChatPay\",\n"
                        + "            \"Url\": \"https://www.novobanco.pt/site/cms.aspx?labelid=nbchatpay_mobile\"\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"3458\",\n"
                        + "          \"Descricao\": \"Pagamentos\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"6073\",\n"
                        + "            \"Descricao\": \"Serviços ou Compras\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"11\",\n"
                        + "              \"Descricao\": \"Pagamento de Serviços\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"482\",\n"
                        + "              \"Descricao\": \"Pagamento de Compras\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6074\",\n"
                        + "              \"Descricao\": \"Reutilizar Pagamento\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6075\",\n"
                        + "              \"Descricao\": \"Pagamento PhotoScan\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6041\",\n"
                        + "            \"Descricao\": \"Carregamentos\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"6036\",\n"
                        + "              \"Descricao\": \"Novo Carregamento\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6076\",\n"
                        + "              \"Descricao\": \"Reutilizar Carregamento\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6077\",\n"
                        + "            \"Descricao\": \"Estado e Setor Público\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"668\",\n"
                        + "              \"Descricao\": \"Pagamento ao Estado\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"995\",\n"
                        + "              \"Descricao\": \"Pagamento da Seg. Social\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"460\",\n"
                        + "              \"Descricao\": \"Pagamento da TSU\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6087\",\n"
                        + "              \"Descricao\": \"Reutilizar Pagamento\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"6078\",\n"
                        + "              \"Descricao\": \"Pagamento PhotoScan\"\n"
                        + "            }]\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"6018\",\n"
                        + "          \"Descricao\": \"Ações e Mercados\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"3467\",\n"
                        + "            \"Descricao\": \"Bolsa\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"1759\",\n"
                        + "              \"Descricao\": \"Informação de Mercados\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"1517\",\n"
                        + "              \"Descricao\": \"Consulta de Carteira\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"1647\",\n"
                        + "              \"Descricao\": \"Ordens de bolsa\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"61\",\n"
                        + "              \"Descricao\": \"Ordens ativas\"\n"
                        + "            }]\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"6046\",\n"
                        + "          \"Descricao\": \"Crédito\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"3618\",\n"
                        + "            \"Descricao\": \"Solução NB Ordenado\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"3052\",\n"
                        + "            \"Descricao\": \"O meu Crédito Habitação\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"3053\",\n"
                        + "            \"Descricao\": \"O meu Crédito Pessoal\"\n"
                        + "          }, {\n"
                        + "            \"Descricao\": \"Simuladores\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Tipo\": 2,\n"
                        + "              \"Id\": \"6054\",\n"
                        + "              \"Descricao\": \"Crédito Pessoal\",\n"
                        + "              \"Url\": \"https://www.novobanco.pt/site/cms.aspx?labelid=pedir_credito_pessoal_nbapp&source=nbsmartapp\"\n"
                        + "            }, {\n"
                        + "              \"Tipo\": 2,\n"
                        + "              \"Id\": \"6054\",\n"
                        + "              \"Descricao\": \"Crédito Habitação\",\n"
                        + "              \"Url\": \"https://cliente.novobanco.pt/simulador-credito-habitacao/?utm_source=novobanco&utm_medium=mobile&utm_campaign=1906.ch.na.na&utm_content=opcao_menu.generico.na\"\n"
                        + "            }]\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"3466\",\n"
                        + "          \"Descricao\": \"Outras Opções\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Id\": \"6262\",\n"
                        + "            \"Descricao\": \"Definições\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"7021\",\n"
                        + "            \"Descricao\": \"Deixar o Cartão Matriz em Casa\",\n"
                        + "            \"Novo\": true\n"
                        + "          }, {\n"
                        + "            \"Id\": \"1774\",\n"
                        + "            \"Descricao\": \"Ativação de opções MBWAY\",\n"
                        + "            \"Novo\": true\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6029\",\n"
                        + "            \"Descricao\": \"Notificações\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Id\": \"2193\",\n"
                        + "              \"Descricao\": \"As minhas notificações\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"2209\",\n"
                        + "              \"Descricao\": \"Criar notificação\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"142\",\n"
                        + "            \"Descricao\": \"Gestão de Beneficiários\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"3756\",\n"
                        + "            \"Descricao\": \"Operações Certificadas\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6088\",\n"
                        + "            \"Descricao\": \"Gestão de Privacidade\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"7014\",\n"
                        + "            \"Descricao\": \"Ativar Cartão Matriz\"\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6054\",\n"
                        + "            \"Descricao\": \"Contactos NB\",\n"
                        + "            \"Filhos\": [{\n"
                        + "              \"Tipo\": 2,\n"
                        + "              \"Id\": \"3468\",\n"
                        + "              \"Descricao\": \"Localizar  Agências e ATMs\",\n"
                        + "              \"Url\": \"https://novobanco.pt/agenciasmobile\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"662\",\n"
                        + "              \"Descricao\": \"Gestor\"\n"
                        + "            }, {\n"
                        + "              \"Id\": \"3074\",\n"
                        + "              \"Descricao\": \"Pedir Contacto/Reunião\"\n"
                        + "            }, {\n"
                        + "              \"Tipo\": 2,\n"
                        + "              \"Id\": \"6054\",\n"
                        + "              \"Descricao\": \"Contactos Gerais NB\",\n"
                        + "              \"Url\": \"https://www.novobanco.pt/SITE/cms.aspx?labelid=contactosnbapp\"\n"
                        + "            }]\n"
                        + "          }, {\n"
                        + "            \"Id\": \"6086\",\n"
                        + "            \"Descricao\": \"Sessão Partilhada\"\n"
                        + "          }]\n"
                        + "        }, {\n"
                        + "          \"Tipo\": 1,\n"
                        + "          \"Id\": \"3462\",\n"
                        + "          \"Descricao\": \"Outras Aplicações\",\n"
                        + "          \"Filhos\": [{\n"
                        + "            \"Tipo\": 4,\n"
                        + "            \"Id\": \"3464\",\n"
                        + "            \"Descricao\": \"NB1Click\"\n"
                        + "          }]\n"
                        + "        }],\n"
                        + "        \"WelcomeId\": \"3398\"\n"
                        + "      },\n"
                        + "      \"Favoritos\": [{\n"
                        + "        \"IdServico\": \"3396\",\n"
                        + "        \"Nome\": \"Saldos e Movimentos\"\n"
                        + "      }]\n"
                        + "    },\n"
                        + "    \"Configuration\": {\n"
                        + "      \"toBackGround\": 30,\n"
                        + "      \"toWeb\": 60\n"
                        + "    },\n"
                        + "    \"RememberMeToken\": \"15316857577f4d3bbca5e730522222\",\n"
                        + "    \"EstadoNotificacao\": {\n"
                        + "      \"Ativo\": true,\n"
                        + "      \"DeviceName\": \"Redmi\",\n"
                        + "      \"DeviceModel\": \"Xiaomi Redmi 4X\",\n"
                        + "      \"DeviceId\": \"805139dc90244a5c9e61084a5cb6abcd\"\n"
                        + "    },\n"
                        + "    \"OfAtivo\": true\n"
                        + "  }\n"
                        + "}");
    }
}
