java_library(
    name = "amex",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/agents/src/main/java/se/tink/backend/aggregation/agents/nxgen/serviceproviders/creditcards/amex/v62",
        "//src/integration/lib",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "//src/libraries/date",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
    ],
)
