package se.tink.backend.common.workers.activity.renderers.themes;

public enum ColorTypes {
    BANK_FEE,
    CHART_AXIS,
    CHART_AXIS_X_LABEL,
    CHART_AXIS_Y_LABEL,
    CHART_AXIS_X_LABEL_HIGHLIGHTED,
    COMPARISON,
    CRITICAL,
    DEFAULT,
    EXPENSES,
    EXPENSES_COMPARISON,
    EXPENSES_PIE_CHART,
    INCOME,
    INFO,
    POSITIVE,
    SEARCH,
    SEARCH_PIE_CHART,
    TRANSFERS,
    WARNING,
    PATH_COLOR,
    LEFT_TO_SPEND,
    GREY,
    GREY_LIGHT,
    GREY_LIGHTEST,
}
