server:
  shutdownGracePeriod: 20s
  applicationConnectors:
    - type: http
      port: 9091
    - type: https
      port: 9101
      keyStorePath: data/security/developer.keystore
      keyStorePassword: changeme
      certAlias: developer.internal.tink.se
      trustStorePath: data/security/TinkCA.truststore
      trustStorePassword: changeme
      # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8091

endpoints:
  main:
    url: http://localhost:9090/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  system:
    url: http://localhost:9091/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  aggregation:
    url: http://localhost:9092/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  analytics:
    url: http://localhost:9093/
  encryption:
    url: http://localhost:9094/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  connector:
    url: http://localhost:9096/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"

cluster: ABNAMRO

serviceAuthentication:
  serverTokens:
    - devtoken

administrativeMode: ["ccccccelgiev", "ccccccflgngc"]

developmentMode: true

taskQueue:
  workers: 1
  mode: ENABLED
  hosts:
    - 172.16.42.2:9092
  firehoseEnabled: true

distributedDatabase:
  seeds:
    - 172.16.42.2
  enabled: true

database:
  driverClass: com.mysql.jdbc.Driver
  username: tink
  password: tink
  url: jdbc:mysql://172.16.42.2/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: false
  persistenceUnitName: tink-main-api
  generateDdl: true

scheduler:
  enabled: true

coordination:
  hosts: 172.16.42.2:2181

cache:
  hosts: 172.16.42.2:11211
  enabled: true

search:
  clusterName: elasticsearch
  hosts: 172.16.42.2:9300
  enabled: true

activities:
  shouldGenerateSensitiveMessage: false

notifications:
  startHourOfDay: 0
  endHourOfDay: 24
  maxAgeDays: 1
  applications:
    se.tink.frontend.mobile:
      google:
        apiKey: 'AIzaSyBbD-9t5m3EnL9U8vxD-3qrg9OKUrVZ92h'
      apple:
        topic: com.abnamro.nl.grip
        keystore:
          filename: abnamro-enterprise.p12
          password: 'gripET'

analytics:
  intercom:
    enabled: false

reprocessTransactions:
  categoryCodes: ["expenses:misc.uncategorized", "income:other.other"]
  description:
  includeModifiedByUser: false

logging:
  level: INFO
  loggers:
    se.tink: DEBUG
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} %blue(%logger) %message%n%xException'
    - type: file
      threshold: INFO
      currentLogFilename: /usr/share/tink-backend-system/log/tink-backend-system.log
      archive: true
      archivedLogFilenamePattern: /usr/share/tink-backend-system/log/tink-backend-system-%d.log.gz
      archivedFileCount: 5
      timeZone: Europe/Stockholm
      logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %message%n%xException'

abnAmro:
  trustStore:
    path: data/security/abnamro.truststore
    password: changeme
  internetBanking:
    host: www-et2.abnamro.nl
    authorizationToken: xxc6w3n3xzzcygzmir98pntfxswetqhq
  datawarehouseExportRemote:
    host: localhost
    port: 22
    remotePath: /tmp/

template:
  enabled: false

connector:
  defaultProviderName: "nl-abnamro-abstract"
