java_library(
    name = "queue-lib",
    srcs = glob(["src/main/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_google_guava_guava",
    ],
)
