java_library(
    name = "argenta",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api",
        "//src/integration/lib",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "@com_fasterxml_jackson_core_jackson_annotations//jar",
        "@com_google_guava_guava//jar",
        "@com_google_http_client_google_http_client//jar",
        "@com_sun_jersey_jersey_core//jar",
        "@commons_codec_commons_codec//jar",
        "@org_apache_httpcomponents_httpclient//jar",
        "@org_slf4j_slf4j_api//jar",
    ],
)
