java_library(
    name = "argenta",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api",
        "//src/integration/lib",
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/nxgen/storage",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:com_google_http_client_google_http_client",
        "@maven//:com_sun_jersey_jersey_core",
        "@maven//:commons_codec_commons_codec",
        "@maven//:org_apache_httpcomponents_httpclient",
        "@maven//:org_slf4j_slf4j_api",
    ],
)
