package(default_visibility = ["//visibility:public"])

alias(
    name = "bunq_register",
    actual = "//src/commands/psd2-register/src/main/java/se/tink/backend/aggregation/register/nl/bunq:bunq_register",
)
