
load("@rules_codeowners//tools:codeowners.bzl", "codeowners")

codeowners(
       name = "owners",
       teams = [
              "@tink-ab/aggregation-teletubbies-maintainer"
       ],
       visibility = ["//:__pkg__"],
)
                             