java_library(
    name = "crelan",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/agents/src/main/java/se/tink/backend/aggregation/agents/nxgen/serviceproviders/openbanking/xs2adevelopers",
        "//src/integration/credentials:service",
        "//src/integration/lib",
        "//third_party:com_google_inject_guice",
    ],
)
