java_library(
    name = "transmitter-lib",
    srcs = glob(
        ["**/*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_github_rholder_guava_retrying",
        "//third_party:com_google_guava_guava",
    ],
)
