java_library(
    name = "eidas",
    srcs = glob(["**/*.java"]),
    data = [
        "//data:aggregation_test",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib",
        "//third_party:com_google_code_findbugs_jsr305",
        "//third_party:com_google_guava_guava",
    ],
)
