package se.tink.backend.core.auth;

public enum AuthenticationStatus {
    AUTHENTICATED,
    AUTHENTICATED_UNAUTHORIZED_DEVICE,
    AUTHENTICATION_ERROR,
    AUTHENTICATION_ERROR_UNAUTHORIZED_DEVICE,
    NO_USER,
    USER_BLOCKED
}
