java_library(
    name = "webdriver",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:lombok_libs",
        "@selenium//:com_codeborne_phantomjsdriver",
        "@selenium//:org_seleniumhq_selenium_selenium_api",
        "@selenium//:org_seleniumhq_selenium_selenium_htmlunit_driver",
        "@selenium//:org_seleniumhq_selenium_selenium_java",
        "@selenium//:org_seleniumhq_selenium_selenium_remote_driver",
    ],
)
