filegroup(
    name = "development",
    srcs = [
        "development.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development-aggregation-server",
    srcs = [
        "development-aggregation-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development-credit-safe-server",
    srcs = [
        "development-credit-safe-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development-minikube-aggregation-server",
    srcs = [
        "development-minikube-aggregation-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development-minikube-provider-configuration-server",
    srcs = [
        "development-minikube-provider-configuration-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development-provider-configuration-server",
    srcs = [
        "development-provider-configuration-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "abn-development",
    srcs = [
        "abn/development.yml",
    ],
    visibility = ["//visibility:public"],
)
