filegroup(
    name = "development",
    srcs = [
        "development.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development_aggregation_server",
    srcs = [
        "development-aggregation-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development_credit_safe_server",
    srcs = [
        "development-credit-safe-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development_minikube_aggregation_server",
    srcs = [
        "development-minikube-aggregation-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development_minikube_provider_configuration_server",
    srcs = [
        "development-minikube-provider-configuration-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "development_provider_configuration_server",
    srcs = [
        "development-provider-configuration-server.yml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "abn_development",
    srcs = [
        "abn/development.yml",
    ],
    visibility = ["//visibility:public"],
)
