filegroup(
    name = "development",
    srcs = glob(["*.yml"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "logback_test",
    srcs = [
        "logback-test.xml",
    ],
    visibility = ["//visibility:public"],
)
