server:
  shutdownGracePeriod: 10s
  applicationConnectors:
    - type: http
      port: 9090
    - type: https
      port: 9100
      keyStorePath: data/security/developer.keystore
      keyStorePassword: changeme
      certAlias: developer.internal.tink.se
      trustStorePath: data/security/TinkCA.truststore
      trustStorePassword: changeme
      # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8090

grpc:
  enabled: true
  port: 9998

endpoints:
  api:
    url: http://www.staging.tink.se/api/v1
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  main:
    url: http://localhost:9090/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  system:
    url: http://localhost:9091/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  aggregation:
    url: http://localhost:9095/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  encryption:
    url: http://localhost:9094/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  connector:
    url: http://localhost:9095/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  aggregationController:
    url: http://localhost:9098/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"

taskQueue:
  workers: 1
  firehoseEnabled: false
  hosts:
    - 192.168.99.100:31007

cluster: TINK

administrativeMode: ["ccccccelgiev", "ccccccflgngc"]

developmentMode: true

supplementalOnAggregation: true

useAggregationController: true

isProvidersOnAggregation: false

flags:
  register:
    SE:
      FRAUD_PROTECTION: 1
      TINK_EMPLOYEE: 1
      APPLICATIONS: 1
    NO:
      FASTTEXT_CATEGORIZER: 1
    ALL:
      WRITE_CASSANDRA_STATISTICS: 1
      READ_CASSANDRA_STATISTICS: 1
      WRITE_NEW_TRANSACTIONS: 1
      READ_NEW_TRANSACTIONS: 1
      READ_PERIODS: 1
  device:
    ONBOARDING_V2: 1
  campaigns:
    MORTGAGE:
      - Mortgage
      - Bolån
  dynamicInheritance:
    APPLICATIONS:
        - TRANSFERS
        - BILLPAY
        - SHOW_BANK_LOGO
        - APPLICATIONS_INTERCOM_CHAT
        - RESIDENCE_TAB
        - IOS_MORTGAGE_TAKE_OVER
    IOS_BETA:
        - RESIDENCE_VALUATION
    TINK_EMPLOYEE:
        - RESIDENCE_VALUATION

distributedDatabase:
  seeds:
    - 192.168.99.100
  port: 31002
  enabled: true

database:
  driverClass: com.mysql.jdbc.Driver
  username: tink
  password: tink
  url: jdbc:mysql://192.168.99.100:31000/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: false
  persistenceUnitName: tink-main-api
  generateDdl: true

scheduler:
  enabled: false

coordination:
  hosts: 192.168.99.100:31003

cache:
  hosts: 192.168.99.100:31005
  enabled: true

search:
  clusterName: elasticsearch
  hosts: 192.168.99.100:31004
  enabled: true
  useHostSniffing: false

facebook:
  appId: 1482993025252778
  appSecret: f45f41de51bc7075b712e88ed270c93e

twilio:
  accountSid: ASK_FH
  authToken: ASK_FH
  enabled: false

analytics:
  intercom:
    enabled: false

integrations:
  booli:
    callerId: tink_app
    privateKey: PRIVATE_KEY_PLACEHOLDER

transfers:
  enabled: true
  duplicateTime: 1
  aggregationTime: 5
  bankTransferThreshold: 1000
  paymentThreshold: 20000

logging:
  level: INFO
  loggers:
    se.tink: TRACE
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} %blue(%logger) %message%n%xException'
    - type: file
      threshold: INFO
      currentLogFilename: /usr/share/tink-backend-main/log/tink-backend-main.log
      archive: true
      archivedLogFilenamePattern: /usr/share/tink-backend-main/log/tink-backend-main-%d.log.gz
      archivedFileCount: 5
      timeZone: Europe/Stockholm
      logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %message%n%xException'

authentication:
  methods:
    - BASIC
    - FACEBOOK
    - BEARER
    - SESSION
  marketRegisterMethods:
    SE:
      - BANKID
  marketLoginMethods:
    SE:
      - BANKID
      - EMAIL_AND_PASSWORD
