endpoints:
  api:
    url: http://www.staging.tink.se/api/v1
  main:
    url: http://localhost:9090/
  system:
    url: http://localhost:9090/
    accessToken: devtoken
  aggregation:
    url: http://localhost:9090/
    accessToken: devtoken
  analytics:
    url: http://localhost:9090/
  encryption:
    url: http://localhost:9094/
    accessToken: devtoken
  connector:
    url: http://localhost:9090/

distributedDatabase:
  seeds:
    - 172.16.42.2
  enabled: true

database:
  driverClass: com.mysql.jdbc.Driver
  username: root
  password:
  url: jdbc:mysql://172.16.42.2/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: true
  persistenceUnitName: tink-main-api
  generateDdl: true

cache:
  hosts: 172.16.42.2:11211
  enabled: true

analytics:
  intercom:
    enabled: false

logging:
  level: INFO
  loggers:
    se.tink: TRACE
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} %blue(%logger) %message%n%xException'

template:
  enabled: false
