server:
  shutdownGracePeriod: 30s
  applicationConnectors:
    - type: http
      port: 9095
    - type: https
      port: 9105
      keyStorePath: data/security/developer.keystore
      keyStorePassword: changeme
      certAlias: developer.internal.tink.se
      trustStorePath: data/security/TinkCA.truststore
      trustStorePassword: changeme
      # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8095

grpc:
  port: 9995

endpoints:
  main:
    url: http://localhost:9090/
    pinnedCertificates:
      - "CERTSHA256:A0A8FBAC442F4A58AC56CB1D0C185F93EE119A1B026BA3F046B0CA99EC165390"
  system:
    url: http://localhost:9091/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:A0A8FBAC442F4A58AC56CB1D0C185F93EE119A1B026BA3F046B0CA99EC165390"
  aggregation:
    url: http://localhost:9095/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:A0A8FBAC442F4A58AC56CB1D0C185F93EE119A1B026BA3F046B0CA99EC165390"
  analytics:
    url: http://localhost:9093/
  encryption:
    url: http://localhost:9094/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:A0A8FBAC442F4A58AC56CB1D0C185F93EE119A1B026BA3F046B0CA99EC165390"
  connector:
    url: http://localhost:9095/
    pinnedCertificates:
      - "CERTSHA256:A0A8FBAC442F4A58AC56CB1D0C185F93EE119A1B026BA3F046B0CA99EC165390"
  aggregationController:
     url: http://localhost:9098/
     accessToken: devtoken
     pinnedCertificates:
       - "CERTSHA256:A0A8FBAC442F4A58AC56CB1D0C185F93EE119A1B026BA3F046B0CA99EC165390"

useAggregationController: false
supplementalOnAggregation: true
isAggregationCluster: false

cluster: TINK

serviceAuthentication:
  serverTokens:
    - devtoken

developmentMode: true

distributedDatabase:
  seeds:
    - 172.16.42.2
  enabled: true

database:
  driverClass: com.mysql.jdbc.Driver
  username: tink
  password: tink
  url: jdbc:mysql://172.16.42.2/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: false
  persistenceUnitName: tink-aggregation-api
  generateDdl: true

creditsafe:
  username: TINKTESTIN
  password: cU7356rwx

coordination:
  hosts: 172.16.42.2:2181

cache:
  hosts: 172.16.42.2:11211
  enabled: true

aggregationWorker:
  collectorSubscriptionKey: ASK_JOHANNES

integrations:
  seb:
    mortgage:
      https: false
      targetHost: 10.1.18.10:10090
      apiVersion: v1.0
      httpHeaders:
        Authorization: "Bearer ASK_JOHANNES"
        Host: tink-api.seb.se:10443
  sbab:
    signBaseUrl: https://secure.sbab.se
    mortgage:
      https: false
      targetHost: 10.10.1.120:10080
      username: sys_tink
      password: bytkod
      signBaseUrl: https://testsign.sbab.se

logging:
  level: INFO
  loggers:
    se.tink: TRACE
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} C:%X{clusterId} UID:%X{userId} CID:%X{credentialsId} P:%X{providerName} A:%X{agentName} %blue(%logger) %message%n%xException'
    - type: file
      threshold: INFO
      currentLogFilename: /usr/share/tink-backend-aggregation/log/tink-backend-aggregation.log
      archive: true
      archivedLogFilenamePattern: /usr/share/tink-backend-aggregation/log/tink-backend-aggregation-%d.log.gz
      archivedFileCount: 5
      timeZone: Europe/Stockholm
      logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %message%n%xException'
