server:
  shutdownGracePeriod: 20s
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 8090

endpoints:
  api:
    url: http://www.staging.tink.se/api/v1
  main:
    url: http://localhost:9090/
  system:
    url: http://localhost:9090/
    accessToken: devtoken
  aggregation:
    url: http://localhost:9090/
    accessToken: devtoken
  analytics:
    url: http://localhost:9090/
  encryption:
    url: http://localhost:9094/
  connector:
    url: http://localhost:9090/
  fasttext:
    url: http://localhost:9090/

cluster: TINK

developmentMode: true

distributedDatabase:
  keyspace: tink_test
  seeds:
    - 172.16.42.2
  enabled: true

database:
  driverClass: com.mysql.jdbc.Driver
  username: root
  password:
  url: jdbc:mysql://172.16.42.2/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: false
  persistenceUnitName: tink-combined-api
  generateDdl: true

cache:
  hosts: 172.16.42.2:11211
  enabled: true

scheduler:
  enabled: true

coordination:
  hosts: 172.16.42.2:2181

search:
  clusterName: elasticsearch
  hosts: 172.16.42.2:9300
  enabled: true

analytics:
  intercom:
    enabled: false

logging:
  level: INFO
  loggers:
    se.tink: TRACE
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
    org.apache.hadoop: INFO
    org.apache.http.client.protocol.ResponseProcessCookies: ERROR
    com.datastax.spark: WARN
    org.apache.spark: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} %blue(%logger) %message%n%xException'
