load("@rules_codeowners//tools:codeowners.bzl", "codeowners", "generate_codeowners")

codeowners(
    name = "owners",
    teams = [
        "@tink-ab/payments-connectivity-maintainer",
    ],
    visibility = ["//:__pkg__"],
)
