version: '2'
services:
  integration-tests:
    image: "gcr.io/tink-containers/bazel:0.13"
    privileged: true
    working_dir: /tink-backend
    ulimits:
        nproc: 65535
        nofile:
          soft: 20000
          hard: 40000
    volumes:
      - "${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}"
      - ..:/tink-backend
      - $HOME/agent-cache/$BUILDKITE_AGENT_NAME/bazel-cache:/root/.cache/bazel
      - /usr/bin/buildkite-agent:/usr/bin/buildkite-agent:ro
    environment:
      - SSH_AUTH_SOCK
      - VERSION
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BRANCH
      - BUILDKITE_AGENT_ACCESS_TOKEN
    depends_on:
      - mysql
      - memcached
      - zookeeper
      - cassandra
      - elasticsearch
      - kafka

  mysql:
    image: mysql:5.7
    command: mysqld --max_connections=2000
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=tink
      - MYSQL_USER=tink
      - MYSQL_PASSWORD=tink

  memcached:
    image: memcached:1.4
    command: memcached -m 64

  cassandra:
    image: cassandra:2.1
    environment:
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=TestDatacenter

  zookeeper:
    image: "gcr.io/tink-containers/zookeeper:3.5.3-beta"

  elasticsearch:
    image: "gcr.io/tink-containers/elasticsearch:0.90.5"

  kafka:
    image: wurstmeister/kafka:1.0.1
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "UPDATE_TRANSACTIONS:1:1,UPDATE_HIGH_PRIO_TRANSACTIONS:1:1"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ADVERTISED_HOSTNAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 104857600
    depends_on:
     - zookeeper
