{{ $providerdb := .Values.providerdb | default dict }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: provider-configuration-configuration
  namespace: provider-configuration
data:
  provider-configuration-server.yml: |
    server:
      shutdownGracePeriod: 10s
      applicationConnectors:
        - type: http
          port: 8080
        - type: https
          port: 8443
          {{- if eq "local" .Values.Cluster }}
          keyStorePath: data/security/developer.keystore
          certAlias: developer.internal.tink.se
          {{- else }}
          keyStorePath: data/security/production.keystore
          certAlias: container.internal.tink.se
          {{- end }}
          keyStorePassword: KEYSTORE_PASSWORD # replaced from secrets
          trustStorePath: data/security/TinkCA.truststore
          trustStorePassword: changeme
          # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
          validateCerts: false
      adminConnectors:
        - type: http
          port: 8099

    logging:
      level: INFO
      loggers:
        se.tink: INFO
        se.tink.org.eclipse: INFO
      appenders:
        - type: console
          threshold: ALL
          timeZone: Europe/Stockholm
          logFormat: '{"date":"%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}","level":"%level","thread":"%thread","requestId":"%X{requestId}","logger":"%logger","message":"%replace(%m){"\n","\\n"}","exception":"%replace(%ex){"[\r\n]+","\\n"}"}%nopex%n'

    database:
      driverClass: com.mysql.jdbc.Driver
      username: {{ default "tink-provider-configuration" $providerdb.username }}
      {{- if eq "local" .Values.Cluster }}
      password: {{ default "password" $providerdb.password }}
      {{- else }}
      password: MYSQL_PASSWORD # Is added via Kubernetes Secrets
      {{- end }}
      url: jdbc:mysql://{{ default "providerdb.provider.svc.cluster.local" $providerdb.host }}/provider?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
      showSql: false
      persistenceUnitName: tink-provider-api
      generateDdl: true
    cluster: TINK

    prometheus:
      port: 9130

{{ if .Values.createDevelopmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: provider-configuration-secrets
  namespace: provider-configuration
type: Opaque
data:
  providerdb-password: ZGV2dG9rZW4=
  # Is set to changeme for the development keystore
  keystore-password: Y2hhbmdlbWU=
{{ end }}
