apiVersion: v1
kind: Service
metadata:
  name: provider-configuration-api
  namespace: provider-configuration
spec:
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  - port: 80
    targetPort: http-api
    name: http-api
  selector:
    app: provider-configuration-service

{{- /*
This condition is a bit ugly. But it is neccesary since booleans default to
"False" and there is currently no way to differentiate between a value that is
not set and a value that is explicitly set to false.
*/ -}}
{{ if not .Values.doNotCreateLoadBalancerService }}
---
apiVersion: v1
kind: Service
metadata:
  name: provider-configuration-loadbalancer
  namespace: provider-configuration
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    external-dns.alpha.kubernetes.io/hostname: "provider-configuration.internal.{{.Values.Environment}}.{{.Values.Cluster}}.tink.network"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  selector:
    app: provider-configuration-service
{{ end }}
