apiVersion: v1
kind: Service
metadata:
  name: provider-configuration-api
  namespace: provider-configuration
spec:
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  - port: 80
    targetPort: http-api
    name: http-api
  selector:
    app: provider-configuration-service


