apiVersion: v1
kind: Service
metadata:
  name: provider-configuration-api
  namespace: provider-configuration
spec:
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  {{- if .Values.insecureHttpServer }}
  - port: 80
    targetPort: http-api
    name: http-api
    nodePort: 31008
  {{- end }}
  type: NodePort
  selector:
    app: provider-configuration-service

{{- /*
This condition is a bit ugly. But it is neccesary since booleans default to
"False" and there is currently no way to differentiate between a value that is
not set and a value that is explicitly set to false.
*/ -}}
{{ if not .Values.doNotCreateLoadBalancerService }}
---
apiVersion: v1
kind: Service
metadata:
  name: provider-configuration-api-loadbalancer
  namespace: provider-configuration
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "provider-configuration.{{.Values.Environment}}.{{.Values.Cluster}}.tink.se"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  {{- if .Values.insecureHttpServer }}
  - port: 80
    targetPort: http-api
    name: http-api
  {{- end }}
  selector:
    app: provider-configuration-service
{{ end }}
