apiVersion: v1
kind: Service
metadata:
  name: provider-configuration-api
  namespace: provider-configuration
spec:
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  {{- if .Values.insecureHttpServer }}
  - port: 80
    targetPort: http-api
    name: http-api
    nodePort: 31008
  {{- end }}
  type: NodePort
  selector:
    app: provider-configuration-service


