java_library(
    name = "transfer-stub-test",
    visibility = ["//visibility:public"],
    srcs = glob(["src/test/**/*.java"]),
    deps = [

        "//third_party:com_fasterxml_jackson_core_jackson_core",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//src/libraries/account_identifier:account-identifier",
        "//src/main-api"
    ],
)
