java_library(
    name = "transfer-stub-test",
    srcs = glob(["src/test/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/account_identifier:account-identifier",
        "//src/libraries/amount",
        "//src/libraries/enums",
        "//src/libraries/transfer:enums",
        "//src/libraries/transfer:rpc",
        "//src/main-api",
        "//third_party:com_fasterxml_jackson_core_jackson_core",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
    ],
)
