java_library(
    name = "ps256",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/serialization",
        "//third_party:com_nimbusds_nimbus_jose_jwt",
        "//third_party:net_minidev_json_smart",
    ],
)
