kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-no
  namespace: agents
spec:
  interval: 5m
  rules:
    - record: sum:failed_refreshes_per_type_no:delta1h
      expr: sum by (className, type) (internal:sum:all_refreshes_by_type_outcome_no:delta1h{outcome=~"partially_completed|failed.*"})
    - record: sum:not_unavailable_refreshes_per_type_no:delta1h
      expr: sum by (className, type) (internal:sum:all_refreshes_by_type_outcome_no:delta1h{outcome!="unavailable"})

    - alert: RefreshFailureRateAbove20%NO
      expr: 0.2 <= sum:failed_refreshes_per_type_no:delta1h / (sum:not_unavailable_refreshes_per_type_no:delta1h >= 3) < 0.75
      for: 15m
      labels:
        priority: P3
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: <{ $value | humanizePercentage }> refresh failure rate of <{ $labels.type }> by <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - alert: RefreshFailureRateAbove75%NO
      expr: sum:failed_refreshes_per_type_no:delta1h / (sum:not_unavailable_refreshes_per_type_no:delta1h >= 3) >= 0.75
      for: 15m
      labels:
        priority: P1
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: <{ $value | humanizePercentage }> refresh failure rate of <{ $labels.type }> by <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - record: sum:failed_on_demand_logins_no:delta1h
      expr: sum by (className) (internal:sum:all_logins_by_outcome_action_no:delta1h{action=~"login-manual|login-auto", outcome=~"failed.*"})
    - record: sum:not_cancelled_or_unavailable_on_demand_logins_no:delta1h
      expr: sum by (className) (internal:sum:all_logins_by_outcome_action_no:delta1h{action=~"login-manual|login-auto", outcome!~"unavailable|cancelled.*"})

    - alert: OnDemandLoginFailureRateAbove20%NO
      expr: 0.2 <= sum:failed_on_demand_logins_no:delta1h / (sum:not_cancelled_or_unavailable_on_demand_logins_no:delta1h >= 3) < 0.75
      for: 15m
      labels:
        priority: P3
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: <{ $value | humanizePercentage }> on-demand login failure rate (excluding bank-side errors and cancellations) for <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - alert: OnDemandLoginFailureRateAbove75%NO
      expr: sum:failed_on_demand_logins_no:delta1h / (sum:not_cancelled_or_unavailable_on_demand_logins_no:delta1h >= 3) >= 0.75
      for: 15m
      labels:
        priority: P1
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: <{ $value | humanizePercentage }> on-demand login failure rate (excluding bank-side errors and cancellations) for <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>

    - record: sum:failed_background_logins:delta1h
      expr: sum by (className) (internal:sum:all_logins_by_outcome_action_no:delta1h{action="login-cron", outcome=~"failed.*"})
    - record: sum:not_cancelled_or_unavailable_background_logins_no:delta1h
      expr: sum by (className) (internal:sum:all_logins_by_outcome_action_no:delta1h{action="login-cron", outcome!~"unavailable|cancelled.*"})

    - alert: BackgroundLoginFailureRateAbove50%NO
      expr: sum:failed_background_logins:delta1h / (sum:not_cancelled_or_unavailable_background_logins_no:delta1h >= 3) >= 0.5
      for: 15m
      labels:
        priority: P1
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: <{ $value | humanizePercentage }> background login failure rate (excluding bank-side errors and cancellations) for <{ $labels.className }> over the last hour.
        tags: <{ $labels.className }>
