kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-pl-long-term
  namespace: agents
spec:
  interval: 1h
  rules:
    - alert: UserLoginErrorRateAbove75%PL
      expr: |
        sum by (className) (sum_over_time(internal:sum:all_logins_by_outcome_action_pl:delta1h{outcome=~"cancelled.*"}[4h:1h]))
        /
        (sum by (className) (sum_over_time(internal:sum:all_logins_by_outcome_action_pl:delta1h[4h:1h])) >= 3) > 0.75
      labels:
        priority: P3
        severity: ping
        who: integration-teletubbies
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs4h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs4h }} |Grafana>
          TUBBIES_EXPERIMENTAL
        summary: <{ $value | humanizePercentage }> user error login error rate for <{ $labels.className }> over the last 4 hours.
        tags: <{ $labels.className }>

    - alert: BankUnavailabilityAbove50%PL
      expr: |
        avg_over_time(
          (1 + 0 * sum by (className) (internal:sum:all_logins_by_outcome_action_pl:delta1h{outcome="unavailable"})
           or
           0 * sum by (className) (internal:sum:all_logins_by_outcome_action_pl:delta1h)
        )[24h:1h])
      labels:
        priority: P2
        severity: ping
        who: integration-teletubbies
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs24h }} |Kibana>
          <{{ .Values.grafanaClassLinkAbs24h }} |Grafana>
          TUBBIES_EXPERIMENTAL
        summary: <{ $value | humanizePercentage }> bank unavailability for <{ $labels.className }> over the last 24 hours.
        tags: <{ $labels.className }>
