kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-pl
  namespace: agents
spec:
  rules:
    - record: sum:all_logins_pl:delta1h
      expr: |
        sum by (className) (
          1 + floor(increase(tink_agent_login_total{action="login", market="PL", provider_type!="test"}[1h]))
          -
          floor(count_over_time(tink_agent_login_total{action="login", market="PL", provider_type!="test"}[1h]) / 360)
        )
    - record: sum:all_logins_pl:delta4h
      expr: |
        sum by (className) (
          1 + floor(increase(tink_agent_login_total{action="login", market="PL", provider_type!="test"}[4h]))
          -
          floor(count_over_time(tink_agent_login_total{action="login", market="PL", provider_type!="test"}[4h]) / 1440)
        )
    - record: sum:all_refreshes_per_type_pl:delta1h
      expr: |
        sum by (className, type) (
          1 + floor(increase(tink_agent_refresh_total{action="refresh", market="PL", provider_type!="test"}[1h]))
          -
          floor(count_over_time(tink_agent_refresh_total{action="refresh", market="PL", provider_type!="test"}[1h]) / 360)
        )
    - record: sum:failed_logins_pl:delta1h
      expr: |
        sum by (className) (
          1 + floor(increase(tink_agent_login_total{action="login", outcome=~"failed.*", market="PL", provider_type!="test"}[1h]))
          -
          floor(count_over_time(tink_agent_login_total{action="login", outcome=~"failed.*", market="PL", provider_type!="test"}[1h]) / 360)
        )
    - record: sum:unsuccessful_background_logins_pl:delta4h
      expr: |
        sum by (className) (
          1 + floor(increase(tink_agent_login_total{action="login-cron", outcome!="completed", market="PL", provider_type!="test"}[4h]))
          -
          floor(count_over_time(tink_agent_login_total{action="login-cron", outcome!="completed", market="PL", provider_type!="test"}[4h]) / 1440)
        )
    - record: sum:unsuccessful_on_demand_logins_pl:delta4h
      expr: |
        sum by (className) (
          1 + floor(increase(tink_agent_login_total{action=~"login-manual|login-auto", outcome!="completed", market="PL", provider_type!="test"}[4h]))
          -
          floor(count_over_time(tink_agent_login_total{action=~"login-manual|login-auto", outcome!="completed", market="PL", provider_type!="test"}[4h]) / 1440)
        )
    - record: sum:failed_refreshes_per_type_pl:delta1h
      expr: |
        sum by (className, type) (
          1 + floor(increase(tink_agent_refresh_total{action="refresh", outcome=~"failed.*|partially_completed", market="PL", provider_type!="test"}[1h]))
          -
          floor(count_over_time(tink_agent_refresh_total{action="refresh", outcome=~"failed.*|partially_completed", market="PL", provider_type!="test"}[1h]) / 360)
        )

    # =========== SHORT-TERM (1h) and MID-TERM (4h) ALERTS ===========
    - alert: RefreshErrorRateAbove10%PL
      expr: sum:failed_refreshes_per_type_pl:delta1h / sum:all_refreshes_per_type_pl:delta1h > 0.1
      for: 15m
      priority: P3
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Refresh failures for <{ $labels.type }> over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: RefreshErrorRateAbove90%PL
      expr: sum:failed_refreshes_per_type_pl:delta1h / (sum:all_refreshes_per_type_pl:delta1h > 2) > 0.9
      for: 15m
      priority: P1
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Refresh failures for <{ $labels.type }> over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: LoginErrorRateAbove10%PL
      expr: sum:failed_logins_pl:delta1h / sum:all_logins_pl:delta1h > 0.1
      for: 15m
      priority: P3
      labels:
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Login error rate over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: LoginErrorRateAbove90%PL
      expr: sum:failed_logins_pl:delta1h / (sum:all_logins_pl:delta1h > 2) > 0.9
      for: 15m
      priority: P1
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs1h }}
          {{ .Values.grafanaClassLinkAbs1h }}
        summary: Login error rate over the last hour is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: BackgroundLoginErrorRateAbove90%PL
      expr: sum:unsuccessful_background_logins_pl:delta4h / (sum:all_logins_pl:delta4h > 5) > 0.9
      for: 15m
      priority: P2
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs4h }}
          {{ .Values.grafanaClassLinkAbs4h }}
        summary: Background login error rate over the last 4 hours is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>

    - alert: OnDemandLoginErrorRateAbove90%PL
      expr: sum:unsuccessful_on_demand_logins_pl:delta4h / (sum:all_logins_pl:delta4h > 5) > 0.9
      for: 15m
      priority: P2
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs4h }}
          {{ .Values.grafanaClassLinkAbs4h }}
        summary: On-demand login error rate over the last 4 hours is <{ $value | humanizePercentage }> for <{ $labels.className }>
        tags: <{ $labels.className }>
