kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-pl-long-term
  namespace: agents
spec:
  interval: 15m
  rules:
    - record: internal:sum:all_logins_by_outcome_action_pl:delta4h
      expr: |
        sum by (className, action, outcome) (
          (floor(increase(tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="PL", provider_type!="test"}[4h]))
           and
           (tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="PL", provider_type!="test"} offset 4h
            unless tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="PL", provider_type!="test"}))
          or
          (1 + floor(increase(tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="PL", provider_type!="test"}[4h])) - floor(count_over_time(tink_agent_login_total{action=~"login-cron|login-auto|login-manual", market="PL", provider_type!="test"}[4h]) / 1440))
        ) > 0

    - record: internal:sum:all_refreshes_by_type_outcome_pl:delta4h
      expr: |
        sum by (className, type, outcome) (
          (floor(increase(tink_agent_refresh_total{action="refresh", market="PL", provider_type!="test"}[4h]))
           and
           (tink_agent_refresh_total{action="refresh", market="PL", provider_type!="test"} offset 4h
            unless tink_agent_refresh_total{action="refresh", market="PL", provider_type!="test"}))
          or
          (1 + floor(increase(tink_agent_refresh_total{action="refresh", market="PL", provider_type!="test"}[4h])) - floor(count_over_time(tink_agent_refresh_total{action="refresh", market="PL", provider_type!="test"}[4h]) / 1440))
        ) > 0

    - record: sum:cancelled_or_unavailable_logins_pl:delta4h
      expr: sum by (className) (internal:sum:all_logins_by_outcome_action_pl:delta4h{outcome=~"unavailable|cancelled.*"})
    - record: sum:all_logins_pl:delta4h
      expr: sum by (className) (internal:sum:all_logins_by_outcome_action_pl:delta4h)

    - alert: BankSideOrUserLoginErrorRateAbove75%PL
      expr: sum:cancelled_or_unavailable_logins_pl:delta4h / (sum:all_logins_pl:delta4h >= 3) >= 0.75
      for: 15m
      labels:
        priority: P3
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs4h }}
          {{ .Values.grafanaClassLinkAbs4h }}
        summary: <{ $value | humanizePercentage }> bank-side or user error login error rate for <{ $labels.className }> over the last 4 hours.
        tags: <{ $labels.className }>

    - record: sum:unavailable_refreshes_pl:delta4h
      expr: sum by (className) (internal:sum:all_refreshes_by_type_outcome_pl:delta4h{outcome="unavailable"})
    - record: sum:all_refreshes_pl:delta4h
      expr: sum by (className) (internal:sum:all_refreshes_by_type_outcome_pl:delta4h)

    - alert: RefreshUnavailabilityRateAbove75%PL
      expr: sum:unavailable_refreshes_pl:delta4h / (sum:all_refreshes_pl:delta4h >= 3) >= 0.75
      for: 15m
      labels:
        priority: P3
        severity: ping
        who: integration-teletubbies
      annotations:
        description: {{ .Values.kibanaClassLinkAbs4h }}
          {{ .Values.grafanaClassLinkAbs4h }}
        summary: <{ $value | humanizePercentage }> refresh unavailability rate for <{ $labels.className }> over the last 4 hours.
        tags: <{ $labels.className }>
