load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "account_capabilities",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@aggregation//:com_google_guava_guava",
    ],
)
