{{- if eq "aggregation" .Values.Cluster }}
kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts
  namespace: aggregation
spec:
  rules:

### Logs ###
  # Alert based on the 5m rate of log-lines from logback (used in tink-backend).
  # Threshold: old canonical threshold of 20 errors / 15 min.
  - alert: TooManyLoggedAggregationErrors
    expr: sum(rate(logback_appender_total{job="tink-aggregation",at!~"^(?:(se.tink.backend.aggregation.nxgen.*)|(se.tink.backend.aggregation.agents.*))$",level="error"}[5m]))
      BY (at, job) * 15 * 60 > 20
    for: 15m
    labels:
      severity: urgent
      who: aggregation
      priority: P2
    annotations:
      description: Job <{ $labels.job }> has logged <{ $value }> errors past 15m in class
        '<{ $labels.at }>'.
      summary: Too many errors logged by <{ $labels.job }>

### Response time alerts ###
  - alert: HighResponseTimeAggregationService
    expr: histogram_quantile(0.95, sum(increase(tink_api_response_duration_seconds_bucket{app="tink-aggregation-controller", team_owner="INTEGRATION", path=~'/aggregation.*', path!~'/aggregation/update'}[5m])) by (method, path, le, instance)) > 0.5
    for: 1m
    labels:
      severity: ping
      who: '#aggregation-alerts'
    annotations:
      description: The 95-%tile of the response duration for the Aggregation Service over the last 5 minutes is over 500 ms.

  - alert: HighResponseTimeProviderConfigurationService
    expr: histogram_quantile(0.95, sum(increase(tink_api_response_duration_seconds_bucket{app="provider-configuration-service", team_owner="INTEGRATION"}[5m])) by (method, path, le, kubernetes_pod_name)) > 0.5
    for: 1m
    labels:
      severity: ping
      who: '#aggregation-alerts'
    annotations:
      description: The 95-%tile of the response duration for the Provider Configuration Service over the last 5 minutes is over 500 ms.

### Only production ###
  {{- if eq .Values.Environment "production" }}
  - alert: NoConsumedMessagesFromAutomaticRefreshQueue
    expr: |
      sum(increase(tink_aggregation_queues_total{event="consumed"}[15m])) == 0
    for: 1m
    labels:
      severity: ping
      who: '#aggregation-oncall'
    annotations:
      description: No messages has been consumed from the Automatic Refresh Queue for the past 15 minutes.
  {{- end }}
{{ end }}
