apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: connectivity-cronjob
  namespace: aggregation
spec:
  schedule: "0/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 6
      template:
        metadata:
          labels:
            app: connectivity-cronjob
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: tink-containers
          securityContext:
            runAsNonRoot: true
            runAsUser: 65535
            runAsGroup: 65535
            fsGroup: 65535
          containers:
            - name: connectivity-cronjob

              {{- if eq "local" .Values.Cluster }}
              image: local_connectivity_test
              imagePullPolicy: Never
              {{else}}
              image: gcr.io/tink-containers/tink-backend-aggregation-connectivity-cronjob:{{ .Files.Get "tink-versions/tink-backend-aggregation-connectivity-cronjob.txt" | default "latest" }}
              imagePullPolicy: IfNotPresent
              {{end}}
              securityContext:
                readOnlyRootFilesystem: true
                privileged: false
              command:
                - "/opt/connectivity/cronjob.py"

{{- if eq "local" .Values.Cluster }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: aggregation
{{ end }}
