apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: aggregation
  namespace: aggregation
spec:
  podSelector:
    matchLabels:
      app: aggregation-service

  egress:
  - {}

  ingress:
  - ports:
    - protocol: TCP
      port: metrics
    from:
    - podSelector:
        matchLabels:
          app: prometheus
    - namespaceSelector:
        matchLabels:
          service: monitoring-prometheus

  - ports:
    - port: 8443
      protocol: TCP
    from:
    - namespaceSelector:
        matchLabels:
          service: ingress-nginx-public

  policyTypes:
  - Egress
  - Ingress
