apiKey-description: |2
    An application programming interface (API) key is the client secret.
    From https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/: The
    client secret is a secret known only to the application and the authorization server.
    It must be sufficiently random to not be guessable, which means you should avoid
    using common UUID libraries which often take into account the timestamp or MAC
    address of the server generating it. A great way to generate a secure secret is to
    use a cryptographically-secure library to generate a 256-bit value and converting it
    to a hexadecimal representation.

apiKey-example: |2
    "S1uyyfIPCaCE2nEirNanuRwjqk8Mybw2"
