java_library(
    name = "configuration",
    srcs = glob(
        ["**/*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/annotations",
        "//third_party:com_google_guava_guava",
        "//third_party:com_google_inject_guice",
    ],
)
