package se.tink.backend.common.loans;

import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.ListMultimap;
import org.junit.Ignore;
import org.junit.Test;
import se.tink.backend.core.Loan;

@Ignore
public class SwedishLoanNameInterpreterTest {


    static class Name {
        String name;
        int number;
        Integer numMonthsBound;

        Name(String name, int number) {
            this.name = name;
            this.number = number;
        }

        public void setNumMonthsBound(Integer numMonthsBound) {
            this.numMonthsBound = numMonthsBound;
        }
    }

    static final ImmutableSet<Name> names;

    static {
        names = ImmutableSet.of(
                new Name("Medlemslån", 3377),
                new Name("Medlemslån Lo", 3136),
                new Name("Medlemslån Tco", 1091),
                new Name("Jordbrukskredit", 581),
                new Name("Medlemslån Saco", 371),
                new Name("Bil- och Fritidslån", 346),
                new Name("Bil- och Fritidskredit", 324),
                new Name("Nya Medlemslån Lo", 53),
                new Name("Billån", 51),
                new Name("Medlemslånet", 43),
                new Name("Bilen", 19),
                new Name("Bil", 17),
                new Name("Nya Medlemslån Tco", 12),
                new Name("Båtlån", 8),
                new Name("Billån Spb.", 7),
                new Name("Medlemslånet Lo", 6),
                new Name("Jordbruk Bund 3mån P", 4),
                new Name("Båten", 3),
                new Name("Nya Medlemslån Saco", 3),
                new Name("Billån Sparbanken", 3),
                new Name("Bottenlån Jordbruk", 3),
                new Name("Lantbrukslån", 3),
                new Name("Jordbruk 3 Mån", 3),
                new Name("Studier", 3),
                new Name("Topplån Jordbruk", 3),
                new Name("Boendejordbruk 3 Mån", 2),
                new Name("Jordbruk Bund3må", 2),
                new Name("Jordbrukslån 3 Mån", 2),
                new Name("Studielån", 2),
                new Name("Bil XYR175", 2),
                new Name("Jordbruksfast Lån", 2),
                new Name("Huset Bilen", 2),
                new Name("3 Mån Jordbruk", 2),
                new Name("Bil-lånet", 2),
                new Name("BILLÅN", 2),
                new Name("Jordbruksfastighet P", 2),
                new Name("Båt", 2),
                new Name("båt", 1),
                new Name("Bil och säng", 1),
                new Name("Bolån o bil 161130", 1),
                new Name("Hemskogen 3", 1),
                new Name("Robert Billån", 1),
                new Name("Lån 4 Bil 1,57 100607", 1),
                new Name("CSN, kök - medlemslån", 1),
                new Name("Båthus", 1),
                new Name("Toyota billån", 1),
                new Name("Bilen V70", 1),
                new Name("Jordbruk Bundet 1 År", 1),
                new Name("Bilen amorteras", 1),
                new Name("bil", 1),
                new Name("Lantbruk Bund 3 Mån", 1),
                new Name("Bilfan", 1),
                new Name("Sofia bil", 1),
                new Name("Husbilen", 1),
                new Name("Jordbruk 3 År Bunden", 1),
                new Name("3 Mån Jordbruksfast", 1),
                new Name("Cecilias utbildning", 1),
                new Name("Billån WST023", 1),
                new Name("Marklån, blanco", 1),
                new Name("Lån Jordbruk 3mån365", 1),
                new Name("Skogslån 260k 12", 1),
                new Name("Billån Audi 2014", 1),
                new Name("Husvagn och bil", 1),
                new Name("Jordbruk Bundet 5årp", 1),
                new Name("Billån medlemslån", 1),
                new Name("Bottenlån Jordbruksf", 1),
                new Name("Vukas Bil", 1),
                new Name("Billån Eos", 1),
                new Name("5 År Jordbruk", 1),
                new Name("Hemskogen 2", 1),
                new Name("Botten 3 Marknadsränta", 1),
                new Name("Jordbruksfastighet", 1),
                new Name("Medlemslån_Bil", 1),
                new Name("Oldsmobile", 1),
                new Name("Skogslån med amortering", 1),
                new Name("060427 Bil 110", 1),
                new Name("Jordbruksfast 5 År", 1),
                new Name("Bil Tommy", 1),
                new Name("Billån - bolån", 1),
                new Name("Jordbruk Bunden 3mån", 1),
                new Name("Tand Bil", 1),
                new Name("Billån - medlemslån", 1),
                new Name("Chantras Studielån", 1),
                new Name("Topplån Marknadsränta", 1),
                new Name("BIL LÅN", 1),
                new Name("Marklån, rörligt", 1),
                new Name("Billån Rörligt", 1),
                new Name("Lilla skogsvägen 15", 1),
                new Name("Segelbåtslån", 1),
                new Name("Bil och båt", 1),
                new Name("Medlemslån 4,70-LAP744", 1),
                new Name("Bil lån", 1),
                new Name("MC och Bil", 1),
                new Name("Rest på bilen", 1),
                new Name("Kattis Studier", 1),
                new Name("billån", 1),
                new Name("Båtlån behållas", 1),
                new Name("Hemskogen 1", 1),
                new Name("Bil Citroen", 1),
                new Name("Eken Jordbruk P", 1),
                new Name("Jordbruk Bundet 4årp", 1),
                new Name("Båt  lösen av bil", 1),
                new Name("Bilen och torpet", 1),
                new Name("Bilen 2.13", 1),
                new Name("Bilen och annat", 1),
                new Name("Billån, rörligt", 1),
                new Name("Bilen S60 50 000 kr", 1),
                new Name("bilkredit", 1),
                new Name("Husbil", 1),
                new Name("Bil Reverslån", 1),
                new Name("3 mån brf markvilk U", 1),
                new Name("Handelsbanken", 4902),
                new Name("Privatlån Boende", 1050),
                new Name("Topplån Privat", 132),
                new Name("Topplån", 112),
                new Name("Topplån Villa", 100),
                new Name("Topplån Bostadsrätt", 31),
                new Name("Topplån Boende", 17),
                new Name("Topplån Prv", 15),
                new Name("Bundet Topplån 2 År", 14),
                new Name("Privatlån Boende 1", 11),
                new Name("Privatlånboende 2", 10),
                new Name("Topplån 3 Mån", 7),
                new Name("Bostad Topplån", 7),
                new Name("Bostadsr.lån Privat", 6),
                new Name("Bo-Lån, Topplån", 4),
                new Name("Privatlån Boende 874", 3),
                new Name("Privat Boende/blanco", 3),
                new Name("Topplån Fastighet", 3),
                new Name("Topplån 2", 2),
                new Name("(villalån Topplån)", 2),
                new Name("Fritidshus Topplån", 2),
                new Name("Topplån 1", 2),
                new Name("Topplån 3 mån", 2),
                new Name("Topplån aug 2017", 2),
                new Name("Topplånet", 2),
                new Name("Topplån Rörlig", 1),
                new Name("Topplån Renovering 6", 1),
                new Name("Topplån Jordbr Fast", 1),
                new Name("topplån", 1),
                new Name("TOPPLÅN BOSTAD", 1),
                new Name("Topplån Victor, huset", 1),
                new Name("Topplån Fritidsfast", 1),
                new Name("TOPPLÅN ALBATROSSEN", 1),
                new Name("Topplånsdel", 1),
                new Name("Topplån - rörlig", 1),
                new Name("Bostadsrätt Topplån", 1),
                new Name("Topplån Bost.rätt", 1),
                new Name("Topplån Flerfam.hus", 1),
                new Name("Fritidshuslån Privat", 1),
                new Name("Hus Blanco", 1),
                new Name("Topplån lgh", 1),
                new Name("Rörligt inkl. Topplån", 1),
                new Name("Topplån Lägenhet", 1),
                new Name("Topplån 15", 1),
                new Name("Stuga topplån pers", 1),
                new Name("Bostad Bund3må", 258),
                new Name("Tilläggslån Bostad", 85),
                new Name("Borätt Bund3må", 59),
                new Name("Villalån", 57),
                new Name("Huslån", 44),
                new Name("Bo-Lån 3 Mån", 34),
                new Name("Hus", 33),
                new Name("Villafastighet", 30),
                new Name("Boende Över 85 Proc", 29),
                new Name("Villa 3 Mån Bundet", 27),
                new Name("Boende Bundet 3 Mån", 23),
                new Name("Huset", 23),
                new Name("Personallån Boende", 22),
                new Name("Villalån 3 Månader", 18),
                new Name("Fastighet/brf 1 Mån", 18),
                new Name("Bostadslån 3 Mån (p)", 17),
                new Name("Bostadsrätt 3 Mån", 14),
                new Name("hus", 14),
                new Name("Bostad Rörligt", 14),
                new Name("Villalån B Rta 2 År", 14),
                new Name("Bostadsr Bu Lån 1mån", 13),
                new Name("Bostadsrätt", 11),
                new Name("Villalån 3 Mån 365", 10),
                new Name("Lån Bostadsrätt", 10),
                new Name("Tilläggslån Boende", 9),
                new Name("Huslån 1", 8),
                new Name("Huslån 2", 8),
                new Name("Villalån Bu Rta 5 År", 8),
                new Name("Fof Spec Bostadsrätt", 7),
                new Name("Fastighetslån Lantbr", 7),
                new Name("Villa 3 Mån", 6),
                new Name("Fastighet/jordb 1mån", 6),
                new Name("Villalån 2 År", 6),
                new Name("Bundet Lån Villa 2", 5),
                new Name("Villa 5 År", 5),
                new Name("Huslån 3", 5),
                new Name("Villalån 2 År Bunden", 5),
                new Name("Bostadsrätt B", 5),
                new Name("Landet", 5),
                new Name("Byggnadslån Villa", 4),
                new Name("Bk Villa", 4),
                new Name("Hus 2", 4),
                new Name("Bostadsrättslån", 4),
                new Name("Villa 3 År", 4),
                new Name("Hus 1", 4),
                new Name("Villa 3-Månader", 4),
                new Name("Lån Mot Bostadsrätt", 4),
                new Name("Huslån internt", 4),
                new Name("Bostad", 4),
                new Name("Villalån 3 Mån", 4),
                new Name("Takräntelån Boende", 4),
                new Name("Bostadsrätt 3 År", 3),
                new Name("Bostadsrätt 5 År", 3),
                new Name("Villa Bunden 3mån", 3),
                new Name("Rörligt, 3 mån - Hus", 3),
                new Name("Husvagn", 3),
                new Name("Villa Bundet 2 År", 3),
                new Name("huslån", 3),
                new Name("Villalån Mot Pant", 3),
                new Name("Bostadslån (p)", 3),
                new Name("Bostadsrätt Bunden 2", 3),
                new Name("Villalån 3 År Bunden", 3),
                new Name("Personal Boende", 3),
                new Name("Borätt 3 År Bundet", 3),
                new Name("Hus 3", 3),
                new Name("Villa", 3),
                new Name("Villalån Bu Rta 3 År", 3),
                new Name("bostadsrätt", 3),
                new Name("Inköp av huset", 3),
                new Name("Villakredit, Rörlig", 3),
                new Name("Villalån T", 3),
                new Name("Villalån 3 År", 3),
                new Name("Byggnadskred. Villa", 2),
                new Name("Villa 3-Månader Ny", 2),
                new Name("Fastighet/brf 5 År", 2),
                new Name("Huslån nr.2", 2),
                new Name("Annan Fastighet", 2),
                new Name("Huslån1", 2),
                new Name("Huset 2", 2),
                new Name("Byggnadskred Villa", 2),
                new Name("Fritidsfastighet", 2),
                new Name("Huslånet", 2),
                new Name("Bostad Bund2må", 2),
                new Name("Huslån rörligt lån", 2),
                new Name("Huslån nr.1", 2),
                new Name("Huset Rosenhill", 2),
                new Name("Bostadsrätt 2 År", 2),
                new Name("huset Angela", 2),
                new Name("Villalån Bu 4", 2),
                new Name("Huslån rörligt", 2),
                new Name("Bostadsrätt 3mån", 2),
                new Name("Huset 1", 2),
                new Name("Hus utan amotering", 2),
                new Name("Villalån Bundet 1år", 2),
                new Name("Huslån externt", 2),
                new Name("Huslån2", 2),
                new Name("Husvagnen", 2),
                new Name("Villalån 5 År", 2),
                new Name("Villalån Bu 3", 2),
                new Name("Landet Överföra", 2),
                new Name("husett", 1),
                new Name("landet 2", 1),
                new Name("villa 3", 1),
                new Name("Villalån Topp", 1),
                new Name("Bostadsr Bu Lån 2år", 1),
                new Name("Annas Huslån", 1),
                new Name("Fastighet/brf 1 År", 1),
                new Name("Villalån Bu 2", 1),
                new Name("Huslån Anita o Carsten", 1),
                new Name("hus fst", 1),
                new Name("Hus 2012 05 A", 1),
                new Name("Villalån 3-Mån(stib)", 1),
                new Name("Villalån 2013", 1),
                new Name("hus fst med amort", 1),
                new Name("Bostadsrätt Mot Pant", 1),
                new Name("Villa Bunden 3år", 1),
                new Name("Villa 5 År Bundet", 1),
                new Name("Huslån Borgen", 1),
                new Name("Hus 5", 1),
                new Name("Boende. ROT lån nr 2.", 1),
                new Name("Hus1", 1),
                new Name("Villafast Bu 2 År", 1),
                new Name("hus 3", 1),
                new Name("landet 1", 1),
                new Name("Personallån Villa", 1),
                new Name("Villalån Bu Rta 2 År", 1),
                new Name("500 TKR 4,83 Hus", 1),
                new Name("Fastighetslån Jordbr", 1),
                new Name("Fastighetslån 2 Mån", 1),
                new Name("Villalån 2", 1),
                new Name("Gamla huslånet", 1),
                new Name("Bostadslån 2 År (p)", 1),
                new Name("Borätt 2 År Bundet", 1),
                new Name("Hus 4", 1),
                new Name("Bostadslån 2 Mån (p)", 1),
                new Name("HUSET_1", 1),
                new Name("Vårt hus 1", 1),
                new Name("Villalån 4 År", 1),
                new Name("Hus 2016 04", 1),
                new Name("Fritidshus", 1),
                new Name("villa 2", 1),
                new Name("Hus Rörlig", 1),
                new Name("Hus med amotering 535t", 1),
                new Name("Bostadsrätts lån", 1),
                new Name("hustvå", 1),
                new Name("Boende. Huslån 2.", 1),
                new Name("Lån Fritidshus", 1),
                new Name("Bostadsrätt T", 1),
                new Name("Villa Bunden 2år", 1),
                new Name("Bostadslån 5 År (p)", 1),
                new Name("Huslån gemensamt", 1),
                new Name("Boende. ROT lån nr 1.", 1),
                new Name("Huset Hällgumsgatan", 1),
                new Name("Stora huslånet", 1),
                new Name("husvagn", 1),
                new Name("hus 2", 1),
                new Name("Bostadsrättslån Topp", 1),
                new Name("Vårt hus 3", 1),
                new Name("Rovehus 2925", 1),
                new Name("500 TKR 2,36 Hus", 1),
                new Name("hustre", 1),
                new Name("villa 4", 1),
                new Name("Fritidshus 3 Mån", 1),
                new Name("Villalån 1", 1),
                new Name("Villalån 5 År Bunden", 1),
                new Name("Hus 2012 05 B", 1),
                new Name("Huslån nr.3", 1),
                new Name("Villalån 4", 1),
                new Name("Villa Lån", 1),
                new Name("Lilla huslånet", 1),
                new Name("Villa 3 År Bundet", 1),
                new Name("Bostadsrättslån 3 Må", 1),
                new Name("Huslån  låst 2015 04 27", 1),
                new Name("Boende. Huslån 1.", 1),
                new Name("hus 1", 1),
                new Name("villa 1", 1),
                new Name("Huslån Anitao Carsten", 1),
                new Name("Villa Bunden 4år", 1),
                new Name("husfyra", 1),
                new Name("hus 4", 1),
                new Name("Bostadsrätt P", 1),
                new Name("Dyrt huslån", 1),
                new Name("Landet Janne", 1),
                new Name("Hus lån fast", 1),
                new Name("Huslån 5 år 3,05%", 1),
                new Name("Fastighet/flerf 1mån", 1),
                new Name("Huslån kontant", 1),
                new Name("Fastighet Ftg 3 Mån", 1),
                new Name("Rest på huset", 1),
                new Name("Bostadsslån", 1),
                new Name("Huset 3", 1),
                new Name("377 TKR 2,43 Hus", 1),
                new Name("Villalån 3", 1),
                new Name("Huslån I", 1),
                new Name("Fritidshus 3-Mån", 1),
                new Name("huslån 2", 1),
                new Name("HUSET_2", 1),
                new Name("Vårt hus 2", 1),
                new Name("Privatlån Direkt", 2729),
                new Name("Övrigt lån", 1703),
                new Name("Privatlån", 1650),
                new Name("Bundet 3mån Prv", 266),
                new Name("Handpenningslån", 262),
                new Name("Blancolån", 259),
                new Name("Personallån Övrigt", 182),
                new Name("Bundet Lån 3 Mån", 171),
                new Name("Direktlån", 160),
                new Name("Överbryggningskredit", 137),
                new Name("Personallån", 134),
                new Name("Bundet Lån 3 År", 107),
                new Name("Takräntelån", 85),
                new Name("Byggnadskredit", 80),
                new Name("Byggkredit Privat", 80),
                new Name("Bergslagslån 1 Mån/p", 70),
                new Name("Bundet Lån 5 År", 68),
                new Name("Borgenslån", 59),
                new Name("Bunden Kredit, 3 Mån", 57),
                new Name("Privatlåndirekt", 48),
                new Name("Företagslån", 46),
                new Name("Bunden 3-Mån", 45),
                new Name("Bundet Lån 2 År", 41),
                new Name("3 Mån Bunden", 40),
                new Name("Energilån", 38),
                new Name("Privatlån,bundet1mån", 34),
                new Name("Räntetaklån Privat", 31),
                new Name("Byggnadslån Privat", 31),
                new Name("Investeringslån 365", 27),
                new Name("Privatlån M Säkerhet", 23),
                new Name("Privat 3 Mån", 23),
                new Name("Blancolån Privat", 23),
                new Name("Rörligt", 23),
                new Name("Bundet P3mx", 22),
                new Name("Laholmslån 2", 19),
                new Name("Bunden Kredit, 3 År", 18),
                new Name("Bundet Lån 4 År", 16),
                new Name("Laholmslån 1 Mån", 16),
                new Name("Varbergslånet", 16),
                new Name("Bundet P3må", 14),
                new Name("3 Mån Ränterörlig", 14),
                new Name("Personallån Säkerhet", 13),
                new Name("3 mån", 13),
                new Name("Sparbankslånet", 12),
                new Name("Trygghetslånprv", 12),
                new Name("Lån 2", 12),
                new Name("Lån 1", 11),
                new Name("736 Räntebundet Lån", 10),
                new Name("Räntegarantilån P", 10),
                new Name("Rtebundet Bostlån 3", 10),
                new Name("Lekebergslån 1 Mån", 10),
                new Name("Blåklocksvägen", 9),
                new Name("Blanco", 9),
                new Name("Rörlig", 9),
                new Name("Personallån Blanco", 9),
                new Name("Privatlån Direkt Tib", 9),
                new Name("Lägenheten", 9),
                new Name("Bunden 2-Åring", 9),
                new Name("Bunden Kredit, 2 År", 8),
                new Name("Lägenhet", 8),
                new Name("Sparb Betal-& Kredit", 8),
                new Name("Handpenningslånm", 7),
                new Name("Privatlån,bundet 3år", 7),
                new Name("Spb Takräntelån", 7),
                new Name("20120530 4,2", 6),
                new Name("Personallån Övr Säk", 6),
                new Name("Bunden Kredit, 1 År", 6),
                new Name("Privatlån,bundet 5år", 6),
                new Name("Valuta", 6),
                new Name("Bergslagslån Priv4år", 6),
                new Name("Bundet 3år Prv", 5),
                new Name("Takränta Privat", 5),
                new Name("Eskilstuna löses", 5),
                new Name("Amortering", 5),
                new Name("Amorteringslån", 5),
                new Name("Byggnadskreditiv", 5),
                new Name("Stuga", 5),
                new Name("Topp", 5),
                new Name("Privatlån Stibor3m", 5),
                new Name("Boprojektlån", 5),
                new Name("Personal Övrigt", 5),
                new Name("Lån 3", 5),
                new Name("Takräntelån Privat", 5),
                new Name("Torpvägen", 5),
                new Name("Sparbanken Privatlån", 5),
                new Name("Stora lånet", 4),
                new Name("Konsumtionslån Sparb", 4),
                new Name("Bergslagslån Trygg", 4),
                new Name("Avbetalningskredit", 4),
                new Name("PÅ KUNDENS BEGÄRAN", 4),
                new Name("Byggnadslån", 4),
                new Name("Rtebundet Bostlån 2", 4),
                new Name("Investeringslån", 4),
                new Name("Hudiklån", 4),
                new Name("Sbg Lånet Privat 2", 4),
                new Name("Lån Utan Säkerhet", 4),
                new Name("Hasselbacksgatan 11", 4),
                new Name("Privatlån,bundet 2år", 4),
                new Name("Personal Med Säkerhe", 4),
                new Name("1,67 3-månaders", 3),
                new Name("Tomtlån", 3),
                new Name("Personallån < 40 Pbb", 3),
                new Name("Rörlig ränta", 3),
                new Name("Personallån, Övrigt", 3),
                new Name("Lösas", 3),
                new Name("Skiftesvägen", 3),
                new Name("2år", 3),
                new Name("Lilla lånet", 3),
                new Name("Sparbanken Blancolån", 3),
                new Name("Renoveringslån", 3),
                new Name("MC", 3),
                new Name("Fast ränta", 3),
                new Name("Personal Bundet Lån", 3),
                new Name("Bunden ränta", 3),
                new Name("Räntetak", 3),
                new Name("1,27", 3),
                new Name("Tolered", 3),
                new Name("5 årigt", 3),
                new Name("Endre 53 O", 3),
                new Name("Handpenningslån Wws", 3),
                new Name("160826  3", 3),
                new Name("PERSONAL", 3),
                new Name("Maryse Jarl", 3),
                new Name("Toplån", 3),
                new Name("Skoter", 3),
                new Name("Rörligt lån", 3),
                new Name("3år", 3),
                new Name("Lahäll", 3),
                new Name("Lån 3 år", 3),
                new Name("Pers Övr Säkerhet", 3),
                new Name("Handpenning", 3),
                new Name("Rörligt Prta", 3),
                new Name("Sotenäs", 3),
                new Name("Storlån", 3),
                new Name("*räntegar Personal", 3),
                new Name("Stuglån", 3),
                new Name("Rörligt 3-månaders", 3),
                new Name("BOKVÄGEN 3B", 3),
                new Name("1.50 170927", 3),
                new Name("Byggnadskred Privat", 3),
                new Name("Personal Blanco", 3),
                new Name("Bundet Lån, Ca 2 År", 3),
                new Name("Anna", 3),
                new Name("Takräntelån Prv", 3),
                new Name("5år", 3),
                new Name("Reverslån, Nordea finans", 3),
                new Name("Lån Mot Värdepapper", 2),
                new Name("Järva Skjutbaneväg 45", 2),
                new Name("Medelhavet", 2),
                new Name("3 månaders", 2),
                new Name("Rtebundet Bostlån 1", 2),
                new Name("Lån1", 2),
                new Name("Backabo", 2),
                new Name("Säkerhetsbytas", 2),
                new Name("A 0, R 2,03", 2),
                new Name("2", 2),
                new Name("Rörligt 3 mån", 2),
                new Name("Rtebundet Jordblån 1", 2),
                new Name("Stugan", 2),
                new Name("3,99", 2),
                new Name("5 årig 2,83 procent", 2),
                new Name("1,22", 2),
                new Name("Torpet", 2),
                new Name("Vinstavägen 28B, lån 3", 2),
                new Name("Aktielån", 2),
                new Name("3 år", 2),
                new Name("Rörelselån", 2),
                new Name("5 år", 2),
                new Name("Bundet Lån Brf 2", 2),
                new Name("Gemensamt lån", 2),
                new Name("Rörlig tak 2 år -0.70", 2),
                new Name("Privat Stibor 3mån", 2),
                new Name("Privatlån,bundet 4år", 2),
                new Name("Bunden Kredit, 4 År", 2),
                new Name("Sommarstuga", 2),
                new Name("treåring", 2),
                new Name("Dalarö", 2),
                new Name("Linda", 2),
                new Name("Bunden 5 År Privat", 2),
                new Name("fast", 2),
                new Name("Rörliga lånet", 2),
                new Name("Jbkr Bundet 5 År", 2),
                new Name("2,88 20160226", 2),
                new Name("1.69 - 2018-02-27", 2),
                new Name("Handpenningslån Ny", 2),
                new Name("Bundet lån", 2),
                new Name("949kr Bundet 170927", 2),
                new Name("Vinstavägen 28B, lån 2", 2),
                new Name("Volvo", 2),
                new Name("Indiska Oceanen", 2),
                new Name("Maria lght Bryggargatan", 2),
                new Name("20181026 Sidö", 2),
                new Name("Bundet", 2),
                new Name("Idre", 2),
                new Name("4,40", 2),
                new Name("Fast 27 juli 2016", 2),
                new Name("3 års", 2),
                new Name("Micke", 2),
                new Name("Bergsgatan 10", 2),
                new Name("Kvartalsbet H.Konto", 2),
                new Name("Trollbäcken", 2),
                new Name("3-mån stort lån", 2),
                new Name("Månadsbet H.Konto", 2),
                new Name("Espana", 2),
                new Name("UA Bundet 170927", 2),
                new Name("Nya Handpenningslån", 2),
                new Name("Hudik", 2),
                new Name("Lgh 1253", 2),
                new Name("3mån", 2),
                new Name("Bu Kredit Ftg.,3 Mån", 2),
                new Name("Atlanten", 2),
                new Name("Saab", 2),
                new Name("Bergslagslån Priv2år", 2),
                new Name("säkerhetsbytas", 2),
                new Name("40 år", 2),
                new Name("Stilla Havet", 2),
                new Name("4,93, 10-12-22", 2),
                new Name("913kr Bundet 170927", 2),
                new Name("Stibor 3 Mån Företag", 2),
                new Name("Lån", 2),
                new Name("Kia", 2),
                new Name("Lån Mot Övr Säkerhet", 2),
                new Name("Sandgärdsgatan 28", 2),
                new Name("Bo", 2),
                new Name("1,32", 2),
                new Name("låst", 2),
                new Name("Gislaved", 2),
                new Name("2års", 2),
                new Name("Lån2", 2),
                new Name("Företagslån Övr Säk.", 2),
                new Name("Lån 5 år", 2),
                new Name("2 år", 2),
                new Name("Golflån", 2),
                new Name("Extralån", 2),
                new Name("Hyp", 2),
                new Name("Vinstavägen 28B, lån 1", 2),
                new Name("0amortering", 2),
                new Name("Bunden 3-Åring", 2),
                new Name("Bundet 4år Prv", 2),
                new Name("Per", 2),
                new Name("Rtebundet Bostlån 5", 2),
                new Name("Blanco Personal", 2),
                new Name("1.50 170825", 2),
                new Name("Byggnadskred. Privat", 2),
                new Name("Brorsan 25 kvar", 2),
                new Name("Roslagslånet", 2),
                new Name("5-årigt med räntetak", 2),
                new Name("Pannan", 2),
                new Name("Rörlig 3 mån -0.70 fel", 2),
                new Name("Talludden", 2),
                new Name("Franzengatan Rörl 1", 2),
                new Name("3", 2),
                new Name("Björlanda Personalränta", 2),
                new Name("Tullgatan 29A", 2),
                new Name("Hypotek 50", 2),
                new Name("Ränta 1,42 rörlig", 2),
                new Name("Rörligt tak 2015-01-27", 2),
                new Name("Rtebundet Bostlån 4", 2),
                new Name("Volvolån", 2),
                new Name("Lån 5", 2),
                new Name("Boobs", 2),
                new Name("Trygghetslån", 2),
                new Name("Blancolån M Försäkr", 2),
                new Name("Angelas", 1),
                new Name("5,08 20160329", 1),
                new Name("Hem", 1),
                new Name("lgh 3", 1),
                new Name("Klostergatan lån 2", 1),
                new Name("Rörlig Lägenhet", 1),
                new Name("Lån MC", 1),
                new Name("2017      2,05", 1),
                new Name("Kvarnsjö lån 1", 1),
                new Name("åkervägen del 1", 1),
                new Name("1 Amort fritt", 1),
                new Name("Lån med Avbet", 1),
                new Name("Maison Matecumbe 2", 1),
                new Name("Kök, badrum & grovkök", 1),
                new Name("Nordea lånet", 1),
                new Name("Bundlån Solbacken", 1),
                new Name("3124 82 78747", 1),
                new Name("JAN-APR-JULI-OKT", 1),
                new Name("Rörligt med Amortering", 1),
                new Name("1185 50 67080", 1),
                new Name("3 mån ränta 2.33", 1),
                new Name("Blancolån 12 år", 1),
                new Name("Drottningholm", 1),
                new Name("Byggkreditiv", 1),
                new Name("Trosa LÅN", 1),
                new Name("3månaders", 1),
                new Name("Byggn.kred. Privat", 1),
                new Name("Storebro 36", 1),
                new Name("Blancolån 5,2", 1),
                new Name("SHILA", 1),
                new Name("Energilån 2", 1),
                new Name("Lyan1", 1),
                new Name("toppen", 1),
                new Name("Lundholmen", 1),
                new Name("VI", 1),
                new Name("Personallån #2", 1),
                new Name("Killingegången lån 2", 1),
                new Name("Eslöv 1", 1),
                new Name("4an", 1),
                new Name("1,50 180626 Kv 252", 1),
                new Name("Linus", 1),
                new Name("Lån Industrifast", 1),
                new Name("gemensamt", 1),
                new Name("Slarvet", 1),
                new Name("1,17 tom 2015-09-30", 1),
                new Name("Forden faaaan", 1),
                new Name("Västra Mälardalslån", 1),
                new Name("2 års", 1),
                new Name("Rörlig tak 5år -0.70fel", 1),
                new Name("Mahmoud", 1),
                new Name("3978 86 47332", 1),
                new Name("5år 170825 2 88", 1),
                new Name("Bundet 2017 del 2", 1),
                new Name("Victor", 1),
                new Name("Am 5000Kr V2010-09-27", 1),
                new Name("Rörlig, villkor 16 juli", 1),
                new Name("Lån2 1,57 121002 475", 1),
                new Name("2016     1,95", 1),
                new Name("Privat00496", 1),
                new Name("Majid Almasoodi", 1),
                new Name("Räntetaklån 2020  2,30", 1),
                new Name("Reparation", 1),
                new Name("Mikaels fryksåslån", 1),
                new Name("Handpenning Hondan", 1),
                new Name("Bussemåla", 1),
                new Name("Lisa 150", 1),
                new Name("Branka", 1),
                new Name("Jeeplån", 1),
                new Name("Företagslån 3 Mån", 1),
                new Name("Miljölån", 1),
                new Name("3993 15 06555", 1),
                new Name("3 årigt", 1),
                new Name("2.02 2015-08-26", 1),
                new Name("Toplån rörlig", 1),
                new Name("Reporänta Privat", 1),
                new Name("Rörligt 3 månader", 1),
                new Name("Bergslagslån 1mån/jk", 1),
                new Name("LÄGENHET 1a LÅN", 1),
                new Name("Rörligt 2014-11-26", 1),
                new Name("Reparationer", 1),
                new Name("V", 1),
                new Name("Hagstigen 40 - 2", 1),
                new Name("Dodge", 1),
                new Name("Globen 2", 1),
                new Name("Handpenningslånet", 1),
                new Name("Rörligt brytdatum Juli", 1),
                new Name("5 år 1,55 p 200327", 1),
                new Name("4,3", 1),
                new Name("Köksrenovering", 1),
                new Name("Lisa3", 1),
                new Name("0,6   4 år till sep 16", 1),
                new Name("15 000 kr", 1),
                new Name("Övrig Säkerhet Priv", 1),
                new Name("Fredriks fryksås konto", 1),
                new Name("Dec 2014 15t", 1),
                new Name("Företag 3 Mån", 1),
                new Name("Daniels Lån", 1),
                new Name("Percys", 1),
                new Name("Privatlån Boend", 1),
                new Name("Vårt", 1),
                new Name("Ellas och Karins handp", 1),
                new Name("Ekollongatan lån 1", 1),
                new Name("Problem 1", 1),
                new Name("Nordea Blancolån", 1),
                new Name("4 år fast 16", 1),
                new Name("Lån Amo 1,47  2 dec 15", 1),
                new Name("Rörligt 3 mån 1", 1),
                new Name("2.78 - 2016-02-26", 1),
                new Name("Mamma & Gunnar", 1),
                new Name("Lån 3 amortering", 1),
                new Name("Restskatten", 1),
                new Name("0,50 R Kv 1.272", 1),
                new Name("5årig", 1),
                new Name("största 4", 1),
                new Name("Drömkåken", 1),
                new Name("Norrböle personalränta", 1),
                new Name("Ränta 2,00 till 160621", 1),
                new Name("Lån1 1,57 121002 550", 1),
                new Name("Företagslån Övr Säk", 1),
                new Name("BD 1", 1),
                new Name("Adoptionslån", 1),
                new Name("20200527Storhogna", 1),
                new Name("5 år fast 18", 1),
                new Name("5 med Amort", 1),
                new Name("2013.04.27 2.69 1611", 1),
                new Name("Mellan Lån", 1),
                new Name("160323 2,83", 1),
                new Name("MARS-JUNI-SEP-DEC", 1),
                new Name("NNV 52", 1),
                new Name("1,47 Sep 30", 1),
                new Name("Lilla hypotek", 1),
                new Name("1180 50 17144", 1),
                new Name("3978 86 49475", 1),
                new Name("Bundet till 2016", 1),
                new Name("Privatlån 1", 1),
                new Name("2020-11-27 , 3,98", 1),
                new Name("Tomträtt", 1),
                new Name("Jörg o Margit Birkl", 1),
                new Name("Lägenhets lån", 1),
                new Name("20130929", 1),
                new Name("3978 85 18370", 1),
                new Name("Mitt privata lån", 1),
                new Name("3.55 1219", 1),
                new Name("Honda", 1),
                new Name("Bygglån", 1),
                new Name("3månAmortering", 1),
                new Name("3978 86 52409", 1),
                new Name("Stamg lån 1", 1),
                new Name("Investeringslån 2 År", 1),
                new Name("Karlbergsvägen 1", 1),
                new Name("F800GS", 1),
                new Name("LGHT Lund", 1),
                new Name("Jordbr Bundet 3mån", 1),
                new Name("A834kr 11-2019 M", 1),
                new Name("Bundet Lån 1 År", 1),
                new Name("Hyp - Muskö", 1),
                new Name("1åring", 1),
                new Name("Roddaren2", 1),
                new Name("Bundet till 2019", 1),
                new Name("Handpenninglån", 1),
                new Name("Handpenningskredit", 1),
                new Name("Rörligt    258", 1),
                new Name("30 år", 1),
                new Name("3996 21 89063", 1),
                new Name("Lån 6 1.54 130710 360", 1),
                new Name("202206 3,00", 1),
                new Name("Investeringslån 4 År", 1),
                new Name("F16", 1),
                new Name("Hemligheten", 1),
                new Name("Extra lånet", 1),
                new Name("Östersem lån 2", 1),
                new Name("V28B III", 1),
                new Name("Toyota Prius", 1),
                new Name("Kamin Kök", 1),
                new Name("Franzengatan Rörl 1,2", 1),
                new Name("179 t rörligt ränta", 1),
                new Name("lilla1", 1),
                new Name("3997 26 65402", 1),
                new Name("Industrifastigh 5 År", 1),
                new Name("XI", 1),
                new Name("Extra lån", 1),
                new Name("Frippes lägis lån", 1),
                new Name("Släpet", 1),
                new Name("Hypotek 1", 1),
                new Name("Största lånet", 1),
                new Name("Lån att amortera", 1),
                new Name("Dyrt förmånslån", 1),
                new Name("540000 lånet", 1),
                new Name("Byggkredit Personal", 1),
                new Name("Fontin 150827", 1),
                new Name("BRF 3", 1),
                new Name("Sauron", 1),
                new Name("Gården56179", 1),
                new Name("3-åring", 1),
                new Name("Monica", 1),
                new Name("Sunnanäng rörligt", 1),
                new Name("Ramsjö", 1),
                new Name("LÄGENHET 2a LÅN", 1),
                new Name("Ugglum 3m 17se de ma ja", 1),
                new Name("Umeå", 1),
                new Name("Killingegången lån 4", 1),
                new Name("2.02 16-03-29", 1),
                new Name("2,38", 1),
                new Name("Restlån", 1),
                new Name("Personal/styrelse", 1),
                new Name("Fontin 3m 25ju ok ja ap", 1),
                new Name("Laxforsen", 1),
                new Name("Rörligt 1,63 53068", 1),
                new Name("Lån säkerhet Hlja", 1),
                new Name("Utan Avbet", 1),
                new Name("Renovering, Eneby", 1),
                new Name("Ågatan 16  del 1", 1),
                new Name("Grundlån 2", 1),
                new Name("Myran 2", 1),
                new Name("20110225", 1),
                new Name("201602 2,48", 1),
                new Name("kredyt 2", 1),
                new Name("Rörlig 0910", 1),
                new Name("Firmalån", 1),
                new Name("Bergvärme", 1),
                new Name("amortera här", 1),
                new Name("Golflån-Nyköping", 1),
                new Name("Med amortering", 1),
                new Name("Lån 3 amorteras på", 1),
                new Name("Fast.lån Övr", 1),
                new Name("20140725", 1),
                new Name("Hjortronet 10", 1),
                new Name("Kombi", 1),
                new Name("Maxränta 2", 1),
                new Name("Golflån-Kfv", 1),
                new Name("Fast lån 25 juni 2015", 1),
                new Name("Stuglån 2013", 1),
                new Name("3 år 1,24 p 180327", 1),
                new Name("Davids Lån", 1),
                new Name("3Mån", 1),
                new Name("Investeringslån Stiv", 1),
                new Name("Rörligt 1,63 53041", 1),
                new Name("Tjörn", 1),
                new Name("Bundet 5 År Privat", 1),
                new Name("3 årig 2,58 procent", 1),
                new Name("753 Räntebundet Lån", 1),
                new Name("Tomtlån Lght Mrta", 1),
                new Name("Mortgage-Fix Rate", 1),
                new Name("4år", 1),
                new Name("Värdepapper Lån", 1),
                new Name("GEMENSAMT BLANCO", 1),
                new Name("Rörlig med räntetak", 1),
                new Name("taket", 1),
                new Name("Hagalund", 1),
                new Name("Rörliga", 1),
                new Name("UFB", 1),
                new Name("Toyota IQ", 1),
                new Name("Kårböle", 1),
                new Name("Gården88763", 1),
                new Name("BL. 7978", 1),
                new Name("Hondan", 1),
                new Name("Stuga Hemavan", 1),
                new Name("Kristineberg", 1),
                new Name("Lån 4", 1),
                new Name("Gotland", 1),
                new Name("3991 29 63903", 1),
                new Name("3050 83 95321", 1),
                new Name("Veranda", 1),
                new Name("Maj 2018", 1),
                new Name("20190126 Sidö", 1),
                new Name("Fast ränta 2 år", 1),
                new Name("3995 13 61226", 1),
                new Name("Åkervägen del 2", 1),
                new Name("2013.04.27 2.59", 1),
                new Name("Störst", 1),
                new Name("Investeringslån Ftg", 1),
                new Name("Rotskär 1", 1),
                new Name("Lösas vilk.ändring aug", 1),
                new Name("3.49", 1),
                new Name("Privat lån", 1),
                new Name("Gården56152", 1),
                new Name("Stuglån 2007", 1),
                new Name("BRF Kandelabern", 1),
                new Name("BRF Bödabaden", 1),
                new Name("Kapitaltillskott", 1),
                new Name("0,50 Kv 750", 1),
                new Name("Reverslån Personal", 1),
                new Name("BoH a2106kr 2037 K JAN", 1),
                new Name("VH, 0", 1),
                new Name("Ford Kuga", 1),
                new Name("Banklånet", 1),
                new Name("Bundet Lån, Ca 3 År", 1),
                new Name("Övrigt", 1),
                new Name("3an", 1),
                new Name("Eu-Kredit", 1),
                new Name("stuglån topp", 1),
                new Name("3 månaders rörlig  2.33", 1),
                new Name("Killingegången lån 1", 1),
                new Name("Sissels Lån", 1),
                new Name("20200427 Sidö", 1),
                new Name("201804 1,49", 1),
                new Name("Klostergatan lån 1", 1),
                new Name("Maison Matecumbe 1", 1),
                new Name("BRF Säfsbyn 1", 1),
                new Name("Lilla Lån", 1),
                new Name("Jägersrovägen", 1),
                new Name("rörlig", 1),
                new Name("minsta 1", 1),
                new Name("Miss Grey", 1),
                new Name("Gamla lilla", 1),
                new Name("2åring", 1),
                new Name("30 juli 2014", 1),
                new Name("WKAB", 1),
                new Name("Takräntelån 3mån Prv", 1),
                new Name("20150327", 1),
                new Name("Mortgage-Float Rate", 1),
                new Name("Bundet tom 20180126", 1),
                new Name("0,50 Kv 705", 1),
                new Name("Rörligt 3 mån 3", 1),
                new Name("Eskilsgatan", 1),
                new Name("3-månaders", 1),
                new Name("751 Räntebundet Lån", 1),
                new Name("Mellösa", 1),
                new Name("cheva lånet", 1),
                new Name("Roddaren1", 1),
                new Name("Flygcert. lån", 1),
                new Name("Personallån #1", 1),
                new Name("3,39", 1),
                new Name("Stora Lån", 1),
                new Name("Myran 2, Lgh 1253", 1),
                new Name("Sammanslag o amort brf", 1),
                new Name("MAMMAS", 1),
                new Name("Fast 3.7", 1),
                new Name("övrigt", 1),
                new Name("20120516 4,3", 1),
                new Name("Snöstorp", 1),
                new Name("Pant", 1),
                new Name("I", 1),
                new Name("lgh 2", 1),
                new Name("20161125 Storhogna", 1),
                new Name("SP Lån 2", 1),
                new Name("3993 26 17636", 1),
                new Name("Tidigare Takräntelån", 1),
                new Name("Oktober 2017", 1),
                new Name("TOPP", 1),
                new Name("Lisa2", 1),
                new Name("Pappas lån", 1),
                new Name("Ränta 2,20 till 160427", 1),
                new Name("ÖVRIG", 1),
                new Name("3323 80 07211", 1),
                new Name("Bundet 2017 del 1", 1),
                new Name("Am 334kr", 1),
                new Name("1,4   3 år till sep 15", 1),
                new Name("Renovering Eneby", 1),
                new Name("Bunden", 1),
                new Name("4,2", 1),
                new Name("BRF 2", 1),
                new Name("Skoterlån", 1),
                new Name("AndresLån", 1),
                new Name("Privat45314", 1),
                new Name("BoH a0kr 20XX M XXXX", 1),
                new Name("ENL TEL 20140522/HE", 1),
                new Name("2015-05-27 , 3,89", 1),
                new Name("10an", 1),
                new Name("Värdepapper", 1),
                new Name("Mitt Stavsnäslån", 1),
                new Name("Mitt PrivatLån", 1),
                new Name("1,50 till 26.8.16 pers", 1),
                new Name("Rörligt 4 brytdatum Juni", 1),
                new Name("2017  5 år 3.21", 1),
                new Name("3 årslånet", 1),
                new Name("3 mån Mrta", 1),
                new Name("Aktierlån", 1),
                new Name("ENL KUND", 1),
                new Name("Mondeo", 1),
                new Name("Slissjön 2", 1),
                new Name("Globen 1", 1),
                new Name("Snäckbacken lgh 1101", 1),
                new Name("1,50 180627 Kv 439", 1),
                new Name("3,79 150527", 1),
                new Name("Bo1", 1),
                new Name("Bundet 2-år", 1),
                new Name("Daniels långlån", 1),
                new Name("5år 2017", 1),
                new Name("Hasslarp", 1),
                new Name("Byggnadslån Personal", 1),
                new Name("1,62 tom 2015-08-26", 1),
                new Name("Hagstigen 40 - 1", 1),
                new Name("Dator", 1),
                new Name("Tomtköp", 1),
                new Name("Lägenhet Fast", 1),
                new Name("Ford Focus", 1),
                new Name("Grundlån 1", 1),
                new Name("1542 10 03965", 1),
                new Name("Tellusvägen 19 topp", 1),
                new Name("Kökslån", 1),
                new Name("Byggn.kredit Privat", 1),
                new Name("Uttern", 1),
                new Name("Ampes Lån", 1),
                new Name("Connylån", 1),
                new Name("ÖK", 1),
                new Name("X", 1),
                new Name("KIA Carneval", 1),
                new Name("Altandörr och lösen lån", 1),
                new Name("nyfors", 1),
                new Name("Mustangen", 1),
                new Name("Tomtlån Mrta", 1),
                new Name("3 år 3,10 1305", 1),
                new Name("Nedandel", 1),
                new Name("Byggnadskredit Priv", 1),
                new Name("Rörligt   2,18", 1),
                new Name("stuga", 1),
                new Name("Tobbe Grindtorps", 1),
                new Name("Ågatan 16  del 3", 1),
                new Name("Valbogatan", 1),
                new Name("Bundet P04", 1),
                new Name("0,50 Kv", 1),
                new Name("Smorgasalliansen", 1),
                new Name("Fladje", 1),
                new Name("Handpenning reverslån", 1),
                new Name("Mindre", 1),
                new Name("Hypotek Trappa Bef", 1),
                new Name("Lgh2", 1),
                new Name("GT-R", 1),
                new Name("JUSEKLÅN", 1),
                new Name("1,67 rörligt topp", 1),
                new Name("Stora hypotek", 1),
                new Name("Stora Uppsalalånet", 1),
                new Name("Personal bundet 160825", 1),
                new Name("0.5", 1),
                new Name("Örsjö", 1),
                new Name("20191025 Storhogna", 1),
                new Name("2013 12 20 3.75", 1),
                new Name("Blankolån", 1),
                new Name("jelenas lån", 1),
                new Name("Garanti", 1),
                new Name("3978 84 39268", 1),
                new Name("Företagslån 1", 1),
                new Name("201606 2,85", 1),
                new Name("Amorterar", 1),
                new Name("Skoda Superb", 1),
                new Name("Östersem lån 1", 1),
                new Name("Gäddstigen 15", 1),
                new Name("BD 3", 1),
                new Name("3 månaders rörligt 2.13", 1),
                new Name("4-årig", 1),
                new Name("233 t 3 mån ränta", 1),
                new Name("1,75 20160226", 1),
                new Name("Botttenlån rörligt", 1),
                new Name("Kök och fönster", 1),
                new Name("5/27/2015", 1),
                new Name("Rörligt 3 brytdatum Juli", 1),
                new Name("Lillån", 1),
                new Name("167 med Amort", 1),
                new Name("Stugelånet", 1),
                new Name("V70", 1),
                new Name("tvååring", 1),
                new Name("Nickes o Ullis", 1),
                new Name("3.06 - 2017-10-27", 1),
                new Name("3år 2015", 1),
                new Name("5 år räntetak 2019", 1),
                new Name("3åring", 1),
                new Name("Privatlån Med Säkerh", 1),
                new Name("Tobbe Mörby", 1),
                new Name("Inköp", 1),
                new Name("top", 1),
                new Name("Företagslån Stib3mån", 1),
                new Name("4064 50 53062", 1),
                new Name("Bunden 2,38 t 20160621", 1),
                new Name("Övrigt flytt", 1),
                new Name("Rörligt Lån", 1),
                new Name("Nora Strand", 1),
                new Name("Privat Stibor 3 Mån", 1),
                new Name("Audi", 1),
                new Name("0,50 R M 1.108", 1),
                new Name("Opel FOG 416", 1),
                new Name("VII", 1),
                new Name("Brändströmsgatan", 1),
                new Name("Ödby Ö", 1),
                new Name("Lån Swetech", 1),
                new Name("Jm Konvertibler 2014", 1),
                new Name("20101030", 1),
                new Name("3051 86 07607", 1),
                new Name("Bindning 170927", 1),
                new Name("Förmånslån", 1),
                new Name("Saaben", 1),
                new Name("SP Lån 1", 1),
                new Name("Månadsbet S.konto", 1),
                new Name("Vikingavägen", 1),
                new Name("HYPOTEK2", 1),
                new Name("Ågatan 16 del 4 kök", 1),
                new Name("3 år 3,68 1506", 1),
                new Name("Lån från Citibank", 1),
                new Name("Hartzö", 1),
                new Name("Gården56160", 1),
                new Name("Jörgens lån", 1),
                new Name("Rörlig 3 mån", 1),
                new Name("Företag Bund 3mån", 1),
                new Name("5an", 1),
                new Name("ENL ÖK MED KUND", 1),
                new Name("Blanco Lägenhet", 1),
                new Name("Östermalm Privatlån", 1),
                new Name("NNV 52 Amort", 1),
                new Name("Eslöv 2", 1),
                new Name("Dolda Dimman", 1),
                new Name("Slasklån", 1),
                new Name("3.77 1205", 1),
                new Name("2.02 2015-06-24", 1),
                new Name("Am 348kr", 1),
                new Name("Killingegången lån 3", 1),
                new Name("Reverslån Övrigt", 1),
                new Name("Kvarnsjö lån 2", 1),
                new Name("Amortera mindre", 1),
                new Name("Leif lån", 1),
                new Name("Lägenhetslån", 1),
                new Name("5+45år Stege", 1),
                new Name("Tomtplaneringslån", 1),
                new Name("Fast Lån", 1),
                new Name("Maria gammalt", 1),
                new Name("PERSONAL I", 1),
                new Name("Ekollongatan lån3 amort", 1),
                new Name("3998 18 49472", 1),
                new Name("Bindning 200625", 1),
                new Name("Mustang GT", 1),
                new Name("201706 3,50", 1),
                new Name("Tenhult", 1),
                new Name("Personal rörlig", 1),
                new Name("Underhållet", 1),
                new Name("Mazda", 1),
                new Name("Stugan Gallsäter", 1),
                new Name("Löses", 1),
                new Name("kredyt 1", 1),
                new Name("Lyan2", 1),
                new Name("A 2084, R 2,03", 1),
                new Name("20170427", 1),
                new Name("2 årslånet", 1),
                new Name("Eget lån", 1),
                new Name("Annas Lägenhet", 1),
                new Name("Mormor, Lina & jag", 1),
                new Name("3 år 2.38", 1),
                new Name("Företaget", 1),
                new Name("Aspö lånet", 1),
                new Name("5 utan Amort", 1),
                new Name("25 juni 2015", 1),
                new Name("20150827", 1),
                new Name("fast till 151127", 1),
                new Name("5-åring", 1),
                new Name("3254 80 10856", 1),
                new Name("Räntetaklån 2019  3,70", 1),
                new Name("197 utan amort", 1),
                new Name("4/27/2016", 1),
                new Name("Maxränta 1", 1),
                new Name("201904 2,7 procent", 1),
                new Name("Nya stora", 1),
                new Name("Personallån > 40 Pbb", 1),
                new Name("Blanko", 1),
                new Name("Rörligt 2014-11-12", 1),
                new Name("ENLIGT KUNDS ÖNSKEMÅL", 1),
                new Name("Studsare", 1),
                new Name("4års", 1),
                new Name("Företagslån Övr. Säk", 1),
                new Name("Fontin 3m 17se de ma ja", 1),
                new Name("Rörligt 2 brytdatum Juli", 1),
                new Name("BMW 3,0 CSI", 1),
                new Name("Amortera mycket", 1),
                new Name("Amorteringsfritt", 1),
                new Name("Priv.låndirektstib1m", 1),
                new Name("Lån 3 1,57 121002 475", 1),
                new Name("lån", 1),
                new Name("Kreditlån", 1),
                new Name("Fast 27 aug 2015", 1),
                new Name("Dell Vostro Laptop", 1),
                new Name("3978 84 97705", 1),
                new Name("Rest på annat", 1),
                new Name("Lån tom170530", 1),
                new Name("Rörligt 3 mån nr 2", 1),
                new Name("2013 01 23 3.30", 1),
                new Name("Rörligt 1,41 96086", 1),
                new Name("4069 51 52048", 1),
                new Name("Lägenhet Lund", 1),
                new Name("Tiia", 1),
                new Name("Fredriks lån", 1),
                new Name("Rörligt lån ej hypotek", 1),
                new Name("Lisa4", 1),
                new Name("4/1/2019", 1),
                new Name("3 mån 1,47", 1),
                new Name("VOLVON", 1),
                new Name("personallån fast 171127", 1),
                new Name("IX", 1),
                new Name("3 år - 2016-05-27", 1),
                new Name("Ylvas lån", 1),
                new Name("Köket", 1),
                new Name("Gammalt lån", 1),
                new Name("Kök, el", 1),
                new Name("V28B II", 1),
                new Name("Personal Säkerhet", 1),
                new Name("CSN", 1),
                new Name("1,52 Aug 26", 1),
                new Name("Studio Lån", 1),
                new Name("FORD", 1),
                new Name("Företagslån Stibor3", 1),
                new Name("Slussgatan 14", 1),
                new Name("Bundet till 2017", 1),
                new Name("Toyota", 1),
                new Name("Krukmakargatan", 1),
                new Name("Bundet 4 år", 1),
                new Name("Lägenhet Rörl", 1),
                new Name("Bundet 2 År Privat", 1),
                new Name("Flyglinjen", 1),
                new Name("3978 86 23832", 1),
                new Name("Fast lån", 1),
                new Name("F-kil", 1),
                new Name("OSG203", 1),
                new Name("Kontantinsatslån", 1),
                new Name("Utköp", 1),
                new Name("ENL TEL 110303 08-53492218", 1),
                new Name("Företagslån Blanco", 1),
                new Name("64990 Rörl", 1),
                new Name("Rörligt 3 mån 2", 1),
                new Name("Badrumslån", 1),
                new Name("Lelles", 1),
                new Name("Ekollongatan lån 2", 1),
                new Name("201802 2,63", 1),
                new Name("Amortera lite", 1),
                new Name("Nytt lån", 1),
                new Name("Lån 5 1,54 100607 225", 1),
                new Name("2,33", 1),
                new Name("Utan amortering", 1),
                new Name("maxräntelån", 1),
                new Name("Växellåda Corsa", 1),
                new Name("Stamg lån 3 amortering", 1),
                new Name("Personlån Borgen", 1),
                new Name("lgh 1", 1),
                new Name("3-mån litet  lån", 1),
                new Name("Problem 2", 1),
                new Name("KUNDENS ÖNSKEMÅL", 1),
                new Name("Gammalt", 1),
                new Name("Samlade lån", 1),
                new Name("kök", 1),
                new Name("Lägenhetslånet", 1),
                new Name("B A 834, R 2,43", 1),
                new Name("Jimmy", 1),
                new Name("BoH a807kr 2039 K FEB", 1),
                new Name("Åkervägen del 4", 1),
                new Name("8/13/2014", 1),
                new Name("Minst", 1),
                new Name("3978 86 80119", 1),
                new Name("3 mån 2,38 procent", 1),
                new Name("Bundet 5år", 1),
                new Name("Lån 3 - A", 1),
                new Name("volvo", 1),
                new Name("Fast ränta 5 år", 1),
                new Name("Eget kapital", 1),
                new Name("NNV 52 Amort.", 1),
                new Name("2 år 2016", 1),
                new Name("Ford Focus RS", 1),
                new Name("Fasta lånet", 1),
                new Name("BRF 1", 1),
                new Name("3.65", 1),
                new Name("BoH a888kr 2042 K JAN", 1),
                new Name("A348kr 02-2026 M", 1),
                new Name("2/27/2012", 1),
                new Name("Hypotek", 1),
                new Name("Klimpfjäll", 1),
                new Name("Lilla Uppsalalånet", 1),
                new Name("stora1", 1),
                new Name("Eu-Kredit Rev", 1),
                new Name("Nordea Lilla", 1),
                new Name("2013.04.27 3.00 1341", 1),
                new Name("XII", 1),
                new Name("20150925 Sidö", 1),
                new Name("Monikas", 1),
                new Name("5 år 3,74 1504", 1),
                new Name("Stamg lån 2", 1),
                new Name("buick", 1),
                new Name("Personal bundet 170825", 1),
                new Name("A 476, R 2,03 o 2,43", 1),
                new Name("Karlbergsvägen 2", 1),
                new Name("Mitt lån", 1),
                new Name("Fordon", 1),
                new Name("Kooperlånet", 1),
                new Name("Lisa1", 1),
                new Name("Företagslån Borgen", 1),
                new Name("Mordor", 1),
                new Name("4 år Amorteringslånet", 1),
                new Name("nytt rörligt", 1),
                new Name("audi lånet", 1),
                new Name("SMULTRONET 4", 1),
                new Name("Rörligt samt amortering", 1),
                new Name("5 års", 1),
                new Name("Skodan", 1),
                new Name("Kim musik 7,2", 1),
                new Name("Säfsen", 1),
                new Name("lgh 4", 1),
                new Name("lilla2", 1),
                new Name("5 år 2018_07_27", 1),
                new Name("898 Privatlån Direkt", 1),
                new Name("Fjätervålen", 1),
                new Name("3995 29 62495", 1),
                new Name("Rörlig - 3,89", 1),
                new Name("Borgen", 1),
                new Name("Torpet investering", 1),
                new Name("Ovandel", 1),
                new Name("2,02 R EFM M", 1),
                new Name("Rörligt med Tak", 1),
                new Name("1,47 Sep 16", 1),
                new Name("Personal Ej Säkerhet", 1),
                new Name("Bara ränta", 1),
                new Name("Sunnanäng bundet", 1),
                new Name("(företagslån Stib-3)", 1),
                new Name("JESS LÅN 2013", 1),
                new Name("Lån Med Säkerhet", 1),
                new Name("Hypotek 2", 1),
                new Name("Norrböle", 1),
                new Name("3978 84 80918", 1),
                new Name("PERSONAL II", 1),
                new Name("5 år - 2018-05-25", 1),
                new Name("rörligt - 70bp", 1),
                new Name("2013.04.27 3.00 1437", 1),
                new Name("273 med amort", 1),
                new Name("Mikans", 1),
                new Name("20 000 kr", 1),
                new Name("Skoda", 1),
                new Name("Lgh1", 1),
                new Name("Grundlån 3", 1),
                new Name("kredyt 3", 1),
                new Name("badrum", 1),
                new Name("Tomt 1,54   28 Okt 15", 1),
                new Name("425 TKR 2,21 Takkupa", 1),
                new Name("0,50 R Kv 00", 1),
                new Name("Awnic", 1),
                new Name("Ågatan 16  del 2", 1),
                new Name("Privat47072", 1),
                new Name("3 mån brf personal U", 1),
                new Name("Renovering", 1),
                new Name("Spalånet", 1),
                new Name("Mörbyhöjden", 1),
                new Name("Fittlån", 1),
                new Name("Bindning 180927", 1),
                new Name("Besam Jaaz", 1),
                new Name("3MånAmort", 1),
                new Name("Vulcanus-lånet", 1),
                new Name("B&H 15", 1),
                new Name("20120509 4,3", 1),
                new Name("Kökslånet", 1),
                new Name("Bundet 2 år", 1),
                new Name("1,50 181026 Kv 375", 1),
                new Name("2 Amort fritt", 1),
                new Name("Granvattnet topp", 1),
                new Name("A3021kr 02-2022 M", 1),
                new Name("Håkans Stavsnäslån", 1),
                new Name("V28B I", 1),
                new Name("Bindning 160427", 1),
                new Name("Tolered blanco", 1),
                new Name("DEP. LÄGENHET", 1),
                new Name("3978 86 22836", 1),
                new Name("ENLIGT ÖK.", 1),
                new Name("BD 2", 1),
                new Name("0,50 rörligt pers", 1),
                new Name("Täck", 1),
                new Name("Åkervägen del 3", 1),
                new Name("3978 84 39276", 1),
                new Name("Hyresfast Bu Lån 1må", 1),
                new Name("Lån 3 mån", 1),
                new Name("00184 Rörl", 1),
                new Name("Nordea Stora", 1),
                new Name("BMWlån", 1),
                new Name("Blancolån Försäkr.", 1),
                new Name("Fatmir", 1),
                new Name("Gemensam", 1),
                new Name("5åring", 1),
                new Name("1,37", 1),
                new Name("Nina", 1),
                new Name("197 med amort", 1),
                new Name("långa lånet", 1),
                new Name("KIA", 1),
                new Name("Jbkr Bundet 3 Mån", 1),
                new Name("HYPOTEK1", 1),
                new Name("Gamla lån", 1),
                new Name("Investering Företag", 1),
                new Name("Olsbo", 1),
                new Name("50 000 kr", 1),
                new Name("PRIVAT FÖRETAGSLÅN", 1),
                new Name("3-mån", 1),
                new Name("Mixat", 1),
                new Name("BMW lån", 1),
                new Name("Ellas och Karins lån", 1),
                new Name("Kök och Fönster", 1),
                new Name("Bolån", 61788),
                new Name("Stadshypotek", 21110),
                new Name("BOLÅN - BOTTENLÅN MED BUNDEN RÄNTA", 13661),
                new Name("Bolån Privat", 127),
                new Name("Bolån Special", 118),
                new Name("Bolån 3 Mån", 116),
                new Name("Rörligt Bolån", 115),
                new Name("Bolån Mot Pant", 106),
                new Name("Sparb. Hypotekslån", 102),
                new Name("Bottenlån", 91),
                new Name("Bolån Bundet 1 Mån", 86),
                new Name("Eken Bolån 3 Mån P", 71),
                new Name("Bolån Villa Bu 1mån", 64),
                new Name("Bolån Plus", 63),
                new Name("BOLÅN - TOPPLÅN MED BUNDEN RÄNTA", 60),
                new Name("Privat Bolån 3 Mån", 55),
                new Name("Bottenlån Boende", 55),
                new Name("Fastighet/bolån 1mån", 54),
                new Name("Spb Bolån 3 Mån", 47),
                new Name("BOLÅN - BOTTENLÅN MED RÖRLIG RÄNTA", 45),
                new Name("Bolån Villa", 40),
                new Name("3 Mån Bolån Villa", 32),
                new Name("Bolån Privat 1 Mån", 32),
                new Name("Bottenlån Villa", 30),
                new Name("Bundet Bolån 3mån", 30),
                new Name("Bolån  Blanco", 30),
                new Name("Bolån 2", 27),
                new Name("Spb Bolån 3 År", 26),
                new Name("Bolån 1", 25),
                new Name("Bostad Bottenlån3mån", 24),
                new Name("Hudik Bolån, 3 Mån", 24),
                new Name("Eken Bolån P", 23),
                new Name("Bolån Privat 3 År", 23),
                new Name("Bolån 3 Mån Act", 21),
                new Name("Bolån Bundet 3 Månad", 20),
                new Name("Tjust Bolån 3 Mån", 19),
                new Name("Bolån 3", 19),
                new Name("Bundet Bolån 3år", 19),
                new Name("Bolån Bundet 5 År", 17),
                new Name("Bolån Bundet 3 År", 17),
                new Name("Privatbolån Stibor-V", 17),
                new Name("Bottenlån 2", 17),
                new Name("Fastighet/bolån 5 År", 16),
                new Name("Bottenlån 3 Mån", 16),
                new Name("Bottenlån 1", 15),
                new Name("Spb Bolån 5 År", 14),
                new Name("Bolån Bundet 5 År P", 13),
                new Name("Bolån 3-Mån", 13),
                new Name("Spec Bolån", 12),
                new Name("Spb Bolån 2 År", 12),
                new Name("Bolån 1 Månad", 12),
                new Name("Privat Bolån 2 År", 12),
                new Name("Privat Bolån 3 År", 10),
                new Name("Bundet Bolån 2 År", 10),
                new Name("Bottenlån 3", 10),
                new Name("3 Mån Bolån", 9),
                new Name("Bolån Bundet 3 År P", 9),
                new Name("Bolån Privat 5 År", 9),
                new Name("Bottenlån 3 Mån P", 8),
                new Name("Bundet Bolån 5år", 8),
                new Name("Spb Bolån 4 År", 8),
                new Name("Bolån Privat 2 År", 8),
                new Name("Bottenlån Stibor3mån", 8),
                new Name("Bundet Bolån 3 År", 8),
                new Name("Eken Bolån Bas", 7),
                new Name("Fastighet/bolån 10år", 7),
                new Name("Bolån 4", 7),
                new Name("3 Mån Bolån Brf", 7),
                new Name("Eken Bolån Blanco P", 7),
                new Name("Bolån rörligt", 7),
                new Name("Bolån Topp", 7),
                new Name("Bottenlån Fritidshus", 7),
                new Name("Fastighet/bolån 3 År", 6),
                new Name("Bolån Villa Bu 4år", 6),
                new Name("Bottenlån tredjedel", 6),
                new Name("Bottenlån Brf", 6),
                new Name("Bolån Privat 4 År", 6),
                new Name("Bolånepaket 3mån", 6),
                new Name("Bolån med amortering", 5),
                new Name("Bundet Bolån 2år", 5),
                new Name("Bolån bundet", 5),
                new Name("Fastighet/bolån 4 År", 5),
                new Name("Bolån Botten", 5),
                new Name("Bolån Privat 1 År", 5),
                new Name("Bolån Vätteslingan", 4),
                new Name("Bolånepaket 5 År", 4),
                new Name("Bolån-Personal", 4),
                new Name("Bundet Bolån 1år", 4),
                new Name("Bundet Bolån 4år", 4),
                new Name("Bolån 5 år", 4),
                new Name("Bolån Bundet 2 År", 4),
                new Name("Bundet Bolån 5 År", 4),
                new Name("Tjust Bolån 5 År", 4),
                new Name("Bolån Torslanda 36 111", 3),
                new Name("Bolåndirekt Topplån", 3),
                new Name("Bolån/topplån", 3),
                new Name("Bottenlån 4", 3),
                new Name("Bolån Rörligt", 3),
                new Name("Lägenhet Botten", 3),
                new Name("Bolån Bostadsrätt", 3),
                new Name("Botten", 3),
                new Name("Bottenlån Prv", 3),
                new Name("Bolån Bundet 2 År P", 3),
                new Name("Bolån, rörligt", 3),
                new Name("Bolån 3 år", 3),
                new Name("Bolån rörlig", 3),
                new Name("Fastighet/bolån 2 År", 3),
                new Name("Bolån Spec Prv", 3),
                new Name("Tjust Bolån 3 År", 3),
                new Name("Bolån fast", 2),
                new Name("Bolån Faktorigatan", 2),
                new Name("Botten 2", 2),
                new Name("Bolån A", 2),
                new Name("Bolån 1,47 R 150923", 2),
                new Name("Bolån Gethagen 160", 2),
                new Name("Botten Rörligt", 2),
                new Name("Bolån 5", 2),
                new Name("Bolån 3 mån", 2),
                new Name("bolån", 2),
                new Name("Bottenl. Bostadsrätt", 2),
                new Name("Bottenl Flerfam.hus", 2),
                new Name("Bolånrörligt", 2),
                new Name("Bolån Amorteras", 2),
                new Name("Bolån 3 mån rörlig", 2),
                new Name("Bolån 4 år", 2),
                new Name("Bundet Bolån 4 År", 2),
                new Name("Bolån1", 2),
                new Name("Bottenlån 131025", 2),
                new Name("Bolån 20140428", 2),
                new Name("Botten 1", 2),
                new Name("Bottenlån 45", 2),
                new Name("Bolånepaket 2 År", 2),
                new Name("Bolån3", 2),
                new Name("Bolån bottenlån", 2),
                new Name("Personal Bolån", 2),
                new Name("Botten lån", 2),
                new Name("Rörligt bolån", 2),
                new Name("Bottenlån2", 2),
                new Name("bottenlån", 2),
                new Name("Bolån Hus", 2),
                new Name("Fof Bolån", 2),
                new Name("Bolån Bundet 4 År P", 2),
                new Name("Bolån Villa Bu 5år", 2),
                new Name("Bottenlån 3 mån", 2),
                new Name("Bolån B", 2),
                new Name("Bolån2", 2),
                new Name("Bottenlån Bost.rätt", 2),
                new Name("Topplån och Bottenlån 1", 2),
                new Name("Bolån Bundet 1 Månad", 2),
                new Name("Hus Bottenlån 2", 1),
                new Name("Liten bolån", 1),
                new Name("Botten 1 Personalränta", 1),
                new Name("Bolånbunden", 1),
                new Name("Bolån1.52 Rörlig 151223", 1),
                new Name("Bolån ett", 1),
                new Name("Bolån 2år amort_1173kr", 1),
                new Name("Bottenlån,fritidshus", 1),
                new Name("Bolån, 4,44 131127", 1),
                new Name("Bolån Blanco", 1),
                new Name("Bolån ränta2", 1),
                new Name("Bolån 1,47    2 dec15", 1),
                new Name("Bolån personallån", 1),
                new Name("NORDEA Bolån 2", 1),
                new Name("Bolån - Rörligt", 1),
                new Name("Bolån1.52 Rörlig 151028", 1),
                new Name("Bottenlån1", 1),
                new Name("Botten lån 2", 1),
                new Name("BOTTENLÅN BOSTAD", 1),
                new Name("Bolån1 5år sep 2017", 1),
                new Name("Bolån Ekg ej am FG", 1),
                new Name("Bolån 3år April 2018", 1),
                new Name("ÖstermalmBolån", 1),
                new Name("Bolån Järla 2", 1),
                new Name("Bolån m amortering", 1),
                new Name("bolån1", 1),
                new Name("Bolån D", 1),
                new Name("Bolån 3 mån - 1", 1),
                new Name("Bolån br 3 mån", 1),
                new Name("Bolån, 4,04 121220", 1),
                new Name("Bolån Amortera", 1),
                new Name("Bolån - Botten", 1),
                new Name("Stor bolån", 1),
                new Name("Bolån - Bunden ränta", 1),
                new Name("Bolån 8 År 3.73", 1),
                new Name("Bottenlån 1 (R 3 m)", 1),
                new Name("Bolån landet", 1),
                new Name("Bolån 22054", 1),
                new Name("Fastighet/bolån 7 År", 1),
                new Name("Bolån 3 ingen amotering", 1),
                new Name("Bolån4  3mån", 1),
                new Name("Lilla bolånet", 1),
                new Name("Hypotekslån", 1),
                new Name("Bolån 3 År 2.53", 1),
                new Name("Bottenlån del 2 3 år", 1),
                new Name("Bolån 2 år", 1),
                new Name("Bolån 8 år", 1),
                new Name("Bottenlån Affärsfast", 1),
                new Name("NORDEA Bolån 1", 1),
                new Name("BOTTEN 2 ALBATROSSEN", 1),
                new Name("Bolån med ammortering", 1),
                new Name("Bolån ränta&amortering", 1),
                new Name("Botten lån 1", 1),
                new Name("Bolån4 med amort", 1),
                new Name("Privat Bolån 1 År", 1),
                new Name("Byggnadskred Bolån", 1),
                new Name("Stort bolån 1", 1),
                new Name("Bottenlån Bostadsrät", 1),
                new Name("BOTTEN 1 ALBATROSSEN", 1),
                new Name("Bolån Brf", 1),
                new Name("hus-botten", 1),
                new Name("botten", 1),
                new Name("Bolån Järla 1", 1),
                new Name("Bolån Samui", 1),
                new Name("Bottenlån rörligt", 1),
                new Name("Spb Bolån 6 År", 1),
                new Name("Bolån2.23 Bundet 160621", 1),
                new Name("Bundet Bolån", 1),
                new Name("Bolån 3,23", 1),
                new Name("Bolån Bundet 1 År", 1),
                new Name("Bolån som amorteras", 1),
                new Name("Bolån ränta1", 1),
                new Name("Bolån - 5 år", 1),
                new Name("Bolån 164k", 1),
                new Name("Bolån Pappas Rörl", 1),
                new Name("Bolån Räntetak", 1),
                new Name("Bolån br 2 år", 1),
                new Name("Bolån 20160127", 1),
                new Name("Bolån 3 ränta amort", 1),
                new Name("Bolån Direkt", 1),
                new Name("Bottenlån 2 år", 1),
                new Name("Bottenlån Fritid", 1),
                new Name("Bolån - 3 år", 1),
                new Name("Bolån 3 mån - 3", 1),
                new Name("bolån3", 1),
                new Name("Bolån Storön", 1),
                new Name("Bolån grund", 1),
                new Name("Bolån 5 År", 1),
                new Name("Bolån - 2,79", 1),
                new Name("Hus Bottenlån", 1),
                new Name("Bolån två", 1),
                new Name("Bolån 2-ingen amotering", 1),
                new Name("Stadshypotek Seniorlån", 1),
                new Name("Bottenlån Renovering 45", 1),
                new Name("Östermalm Bolån", 1),
                new Name("Tjust Bolån 2 År", 1),
                new Name("Bolån2  5år sep 2017", 1),
                new Name("Bolån 22062", 1),
                new Name("BoLån Topp", 1),
                new Name("Tellusvägen 19 botten", 1),
                new Name("Bolån 3,70", 1),
                new Name("Bolån C", 1),
                new Name("Bolån - M o P Säkerhet", 1),
                new Name("Bottenlån Industri", 1),
                new Name("Bottenlån amorterar", 1),
                new Name("Fof Bolån Bostadsr.", 1),
                new Name("Bolån 2 årig fast ränta", 1),
                new Name("Sportstugan Bottenlån", 1),
                new Name("Bolån 22038", 1),
                new Name("Bolån Villa Bu 3år", 1),
                new Name("Bolån 1,67", 1),
                new Name("Fast Bolån Amortering", 1),
                new Name("Bolån 1,54   14 Okt 15", 1),
                new Name("Bolån 20180525  2,80", 1),
                new Name("Stora bolånet", 1),
                new Name("Bolån 2,98", 1),
                new Name("Spb Bolån 2 Mån", 1),
                new Name("Stuglån botten", 1),
                new Name("Bolån amort_500kr", 1),
                new Name("Bolån 5 År 3.13", 1),
                new Name("botten med amortering", 1),
                new Name("Bolån 1,47 R 151104", 1),
                new Name("Bolån 2 ränta amort", 1),
                new Name("Bolån - Räntetak", 1),
                new Name("Bolån 2.90", 1),
                new Name("Bolån tre", 1),
                new Name("Bolån 3 no amo", 1),
                new Name("Spb Bolån 10 År", 1),
                new Name("Bolån Rörlig räntetak", 1),
                new Name("Botten 2 Personalränta", 1),
                new Name("Bolån 5 År Special", 1),
                new Name("Bottenlånet", 1),
                new Name("Bottenlån del 1", 1),
                new Name("Botten 3", 1),
                new Name("Bolån - rörligt, mamma", 1),
                new Name("Granvattnet botten", 1),
                new Name("Bolån över 75 proc.", 1),
                new Name("Bolån 1 ränta", 1),
                new Name("Botten lån 3", 1),
                new Name("Bolån, Sävlingsbol rörl", 1),
                new Name("Bolån Amortering 297.5k", 1),
                new Name("Bolån - rörligt", 1),
                new Name("Bolån3  4år sep 2016", 1),
                new Name("Bolån - Amorteras", 1),
                new Name("Bolån-Stibor 3mån", 1),
                new Name("Bolån - Botten-Topp", 1),
                new Name("Bolån 20140226", 1),
                new Name("Bolån 297.5k", 1),
                new Name("Bolån - 2,28", 1),
                new Name("Bolån 3 mån - 2", 1),
                new Name("bolån2", 1),
                new Name("Bolån amorteras", 1),
                new Name("Spb Bolån 7 År", 1),
                new Name("Bottenlån 2 (R)", 1),
                new Name("Bolån 1.67", 1),
                new Name("Vanligt bolån", 1),
                new Name("Bolån1.52R Amort 151028", 1),
                new Name("Bolån Bundet 4 År", 1),
                new Name("Bolån 2 no amo", 1),
                new Name("Spb Bolån 1 År", 1),
                new Name("Bottenlån 3,5 150127", 1),
                new Name("Bundet bolån", 1),
                new Name("Bolån Bu 3 Mån", 1),
                new Name("BoLån Botten", 1),
                new Name("NORDEA Bolån 3 Amort.", 1),
                new Name("Bolån 1-amotering", 1),
                new Name("Bolån 1,97 R 151028", 1),
                new Name("Bolån 3.28", 1),
                new Name("Bolånet", 1),
                new Name("Hypotekslån 5 år", 1),
                new Name("Bolån 20170526  2,75", 1),
                new Name("Bolån Unga", 1),
                new Name("Bottenlån 3 år", 1),
                new Name("Hypotekslån 3 år", 1),
                new Name("Bolån - Rörlig ränta", 1),
                new Name("Bolån - 4 år", 1),
                new Name("Bottenlån stora", 1),
                new Name("Bottenlån 2,58 151127", 1),
                new Name("Bottenlån fast", 1),
                new Name("Bolån aktivt", 1),
                new Name("Stort bolån 2", 1),
                new Name("Bolån Villa T", 1),
                new Name("Bolån vilande", 1),
                new Name("Bolån 3,45", 1),
                new Name("Bolån-Amortering", 1),
                new Name("Fof Bolån Villa", 1),
                new Name("Bolån 1år Maj 2016", 1),
                new Name("Bolån 22046", 1)
        );
    }

    @Test
    public void testInterpretNames() {
        ListMultimap<Loan.Type, Name> nameByType = ArrayListMultimap.create();
        for (Name name : names) {
            SwedishLoanNameInterpreter interpreter = new SwedishLoanNameInterpreter(name.name);
            name.setNumMonthsBound(interpreter.getGuessedNumMonthsBound());
            nameByType.put(interpreter.getGuessedLoanType(), name);
        }

        for (Loan.Type type : nameByType.keySet()) {
            for (Name name : nameByType.get(type)) {
                System.out.println(name.name + "\t" + name.number + "\t" + type + "\t" + name.numMonthsBound);
            }
        }
    }
}