java_library(
    name = "entities",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/aggregation/api/src/main/java/se/tink/backend/aggregation/rpc/enums",
        "//src/libraries/date",
        "//src/libraries/serialization",
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:com_google_guava_guava",
        "//third_party:io_vavr",
        "//third_party:joda_time_joda_time",
    ],
)
