java_library(
    name = "bnppf",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api",
        "//src/integration/lib",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "@com_google_guava_guava//jar",
        "@com_sun_jersey_jersey_core//jar",
        "@commons_io_commons_io//jar",
        "@org_apache_commons_commons_lang3//jar",
        "@org_apache_httpcomponents_httpcore//jar",
    ],
)
