load("@tink_backend//tools/bzl:junit_strict.bzl", "junit_test")

java_library(
    name = "account",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/account_identifier",
    ],
)
