alias(
    name = "transmitter-client",
    actual = "//src/integration/agent_capability_tracker/client/src/main/java/se/tink/backend/integration/agentcapabilitytracker/transmitter:transmitter-client",
    visibility = ["//visibility:public"],
)

alias(
    name = "transmitter-client-test",
    actual = "//src/integration/agent_capability_tracker/client/src/test/java/se/tink/backend/integration/agentcapabilitytracker/transmitter:transmitter-client-test",
)
