load("//tools/bzl:junit.bzl", "junit_test")

junit_test(
    name = "random_utils",
    srcs = glob(["**/*.java"]),
    data = [
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib",
        "//third_party:org_assertj_assertj_core",
    ],
)
