package se.tink.backend.aggregation.agents.nxgen.it.bancoposta.fetcher;

import org.junit.Ignore;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.AccountDetailsResponse;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.AccountsResponse;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.SavingAccountDetailsResponse;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.SavingAccountResponse;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.SavingTransactionResponse;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.TransactionsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public class FetcherTestData {
    public static final String IDENTITY_FETCHER_RESPONSE =
            "eyJraWQiOiI2Mzc4Nzc2MkUxQ0UxQzM1NjA4RkFFMzgxMzBCNjExODE3NTVBRTgyQTZBOTE2Q0EyMjRCRUE1MEMzRUZBQ0U2IiwiY3R5IjoiSldUIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkdW1teU5hbWUuZHVtbXlMYXN0TmFtZS0xMjM0IiwiYXVkIjoiaHR0cHM6Ly9vaWRjLXByb3h5LnBvc3RlLml0IiwibmJmIjoxNjAyMDc3MTc4LCJhY3QiOnsic3ViIjoiZDhiN2ExNTYtMjE4Ny00OTE3LWI2M2UtMzI0NDNiN2ZjY2FiIiwiYWNyX3ZhbHVlcyI6Imh0dHBzOi8vaWRwLnBvc3RlLml0L0wwIiwiaXNzIjoiaHR0cHM6Ly9vaWRjLXByb3h5LnBvc3RlLml0In0sImFjcl92YWx1ZXMiOiJodHRwczovL2lkcC5wb3N0ZS5pdC9MMiIsImlzcyI6Imh0dHBzOi8vaWRwLXBvc3RlLnBvc3RlLml0IiwiY2xhaW1zIjp7ImJpcnRodG93bl9kZXNjcmlwdGlvbiI6IlBBTEVSTU8iLCJiaXJ0aGRhdGUiOiIyMDAwLTAxLTAxIiwibW9iaWxlTnVtYmVyIjoiZHVtbXlQaG9uZSIsInNleCI6Ik0iLCJwclJvbGVNZW1iZXIiOlsiaWQtcHJpdmF0YS1zdHJvbmcscG9ydGFsIiwibm90aWNlYm9hcmQscG9ydGFsIiwiaWQtcHJpdmF0YS1iYXNlLHBvcnRhbCIsInVzZXJzLHBvcnRhbCJdLCJ1c2VyaWQiOiJkdW1teU5hbWUuZHVtbXlMYXN0TmFtZS0xMjM0IiwiYmlydGhuYXRpb25fY29kZSI6IklUIiwiYmlydGhwcm92aW5jZV9jb2RlIjoiUEEiLCJzdXJuYW1lIjoiZHVtbXlMYXN0TmFtZSIsIm5hbWUiOiJkdW1teU5hbWUiLCJ0YXhjb2RlIjoiZHVtbXlTU04iLCJyZWFsbSI6InBvc3RlLml0IiwiYmlydGh0b3duX2NvZGUiOiIiLCJlbWFpbCI6ImZkdW1teUxhc3ROYW1lOTNAZ21haWwuY29tIiwiY2xpZW50X2NvZGUiOiJkdW1teUNsaWVudENvZGUifSwiZXhwIjoxNjAyMDc4MDc4LCJpYXQiOjE2MDIwNzcxNzgsIm5vbmNlIjoiM0Q3MDNBOUItM0Q4Mi00NjMzLUFFMzktQjczOTBERTI1QzE4IiwianRpIjoiNUEyN0UyMzctRDQ5OC00N0U3LTk4RTgtMTk3MUIzMjA5RUUzIiwic3RhdHVzIjoic3VjY2VzcyJ9.h3Eh9ifodcTxkIxOCfqs0tPrIRfmBNr8IxbojNoqiPnQ7VBp784YYNuzK2gmXvzlqjEThvRt2R3yebJWcf5gVAyzCyvzCwpezpvdDC54wQXICb5kPJsX658hubvzjJM5uyeZS92yE8fYAR7UxGDDJw2v3LZXcoaaLmSupOLWAlvRPlnwPr_1Wu9MNDI_TDR2qDr_ErPTOiTda5EQ3Q4ccWjkD4dPxf0LS2Iasiiz_O22nrzHtTcPTKEDaSaQCRjNuK_6eje98UPxRT8vRhe91FldemMbbQMPi_yPiMQ4YSUqm7X0rR_sIIvUDTbwL-9gFSpF2GN8db2mJyD2dsQFsw\n";

    public static AccountsResponse getAccountResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "    \"data\": [\n"
                        + "        {\n"
                        + "            \"id\": 841243,\n"
                        + "            \"accountIdentifier\": \"001043581196\",\n"
                        + "            \"realmIdentifier\": \"posteitaliane\",\n"
                        + "            \"accountTypeId\": 45,\n"
                        + "            \"name\": \"CONTO\",\n"
                        + "            \"balance\": 0.0000,\n"
                        + "            \"limit\": 0.0000,\n"
                        + "            \"accountClass\": null,\n"
                        + "            \"organizationName\": null,\n"
                        + "            \"organizationIdentifier\": \"posteitaliane\",\n"
                        + "            \"realmCredentialsId\": 348385,\n"
                        + "            \"accountAuthorizationType\": \"External\",\n"
                        + "            \"orderId\": 0,\n"
                        + "            \"isImportAccount\": false,\n"
                        + "            \"lastUpdate\": \"2019-01-11T21:23:31.7332123\",\n"
                        + "            \"personId\": 20348385,\n"
                        + "            \"userEmail\": \"\",\n"
                        + "            \"createDate\": \"2018-12-06T13:19:18.4503954\",\n"
                        + "            \"accountCategory\": \"Current\",\n"
                        + "            \"emergencyFundBalanceLimit\": null,\n"
                        + "            \"inactive\": false,\n"
                        + "            \"attachedToUserDate\": null,\n"
                        + "            \"isHidden\": false,\n"
                        + "            \"isDisabled\": false,\n"
                        + "            \"metadata\": [\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPFM\",\n"
                        + "                    \"value\": \"13-11-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPRIMAMOV\",\n"
                        + "                    \"value\": \"18-09-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"FLGSTO\",\n"
                        + "                    \"value\": \"S\"\n"
                        + "                }\n"
                        + "            ],\n"
                        + "            \"currencyCode\": \"EUR\",\n"
                        + "            \"accountRoleExternal\": \"MONOINTESTATO\",\n"
                        + "            \"accountStatusExternal\": \"APERTO\",\n"
                        + "            \"balanceInUserCurrency\": 0.0,\n"
                        + "            \"limitInUserCurrency\": 0.0\n"
                        + "        },\n"
                        + "        {\n"
                        + "            \"id\": 841243,\n"
                        + "            \"accountIdentifier\": \"001043581196\",\n"
                        + "            \"realmIdentifier\": \"posteitaliane\",\n"
                        + "            \"accountTypeId\": 45,\n"
                        + "            \"name\": \"CONTO\",\n"
                        + "            \"balance\": 0.0000,\n"
                        + "            \"limit\": 0.0000,\n"
                        + "            \"accountClass\": null,\n"
                        + "            \"organizationName\": null,\n"
                        + "            \"organizationIdentifier\": \"posteitaliane\",\n"
                        + "            \"realmCredentialsId\": 348385,\n"
                        + "            \"accountAuthorizationType\": \"External\",\n"
                        + "            \"orderId\": 0,\n"
                        + "            \"isImportAccount\": false,\n"
                        + "            \"lastUpdate\": \"2019-01-11T21:23:31.7332123\",\n"
                        + "            \"personId\": 20348385,\n"
                        + "            \"userEmail\": \"\",\n"
                        + "            \"createDate\": \"2018-12-06T13:19:18.4503954\",\n"
                        + "            \"accountCategory\": \"Current\",\n"
                        + "            \"emergencyFundBalanceLimit\": null,\n"
                        + "            \"inactive\": false,\n"
                        + "            \"attachedToUserDate\": null,\n"
                        + "            \"isHidden\": false,\n"
                        + "            \"isDisabled\": false,\n"
                        + "            \"metadata\": [\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPFM\",\n"
                        + "                    \"value\": \"13-11-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPRIMAMOV\",\n"
                        + "                    \"value\": \"18-09-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"FLGSTO\",\n"
                        + "                    \"value\": \"S\"\n"
                        + "                }\n"
                        + "            ],\n"
                        + "            \"currencyCode\": \"EUR\",\n"
                        + "            \"accountRoleExternal\": \"MONOINTESTATO\",\n"
                        + "            \"accountStatusExternal\": \"APERTO\",\n"
                        + "            \"balanceInUserCurrency\": 0.0,\n"
                        + "            \"limitInUserCurrency\": 0.0\n"
                        + "        }\n"
                        + "    ]\n"
                        + "}",
                AccountsResponse.class);
    }

    public static AccountDetailsResponse getAccountDetailsResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "  \"header\": {\n"
                        + "    \"command-result\": \"0\",\n"
                        + "    \"clientId\": \"75d20ad6-94f4-47ba-88a3-79bea47fa2a8\",\n"
                        + "    \"command-result-description\": \"\",\n"
                        + "    \"requestId\": \"\",\n"
                        + "    \"requestid\": \"cc624779-d6cd-4580-931d-028c9eaee0b6:node-3\",\n"
                        + "    \"command-result-details\": \"\",\n"
                        + "    \"command-request-version\": \"v1\",\n"
                        + "    \"command-request-service\": \"bancoposta\",\n"
                        + "    \"command-request-command\": \"ricercaListaMovimentiConto\",\n"
                        + "    \"command-result-reason\": \"\",\n"
                        + "    \"status\": \"COMPLETED\"\n"
                        + "  },\n"
                        + "  \"body\": {\n"
                        + "    \"saldoH24\": true,\n"
                        + "    \"iban\": \"dummyIban\",\n"
                        + "    \"presenzaPrenotate\": false,\n"
                        + "    \"movimenti\": [\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI AGOSTO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/08/2020\",\n"
                        + "        \"dataContabile\": \"10/09/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020091000130053208500000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI LUGLIO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/07/2020\",\n"
                        + "        \"dataContabile\": \"19/08/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020081900130058781600000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"+\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI SETTEMBRE 2019\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"30/09/2019\",\n"
                        + "        \"dataContabile\": \"10/10/2019\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962019101000130045166000000\"\n"
                        + "      }\n"
                        + "    ],\n"
                        + "    \"saldo\": {\n"
                        + "      \"saldoDisponibile\": 370,\n"
                        + "      \"saldoContabile\": 370,\n"
                        + "      \"segnoSaldoContabile\": \"-\",\n"
                        + "      \"segnoSaldoDisponibile\": \"-\",\n"
                        + "      \"dataSaldo\": \"29/09/2020\"\n"
                        + "    },\n"
                        + "    \"bic\": \"BPPIITRRXXX\"\n"
                        + "  }\n"
                        + "}",
                AccountDetailsResponse.class);
    }

    public static TransactionsResponse getCheckingTransactionResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "  \"header\": {\n"
                        + "    \"command-result\": \"0\",\n"
                        + "    \"clientId\": \"75d20ad6-94f4-47ba-88a3-79bea47fa2a8\",\n"
                        + "    \"command-result-description\": \"\",\n"
                        + "    \"requestId\": \"\",\n"
                        + "    \"requestid\": \"cc624779-d6cd-4580-931d-028c9eaee0b6:node-3\",\n"
                        + "    \"command-result-details\": \"\",\n"
                        + "    \"command-request-version\": \"v1\",\n"
                        + "    \"command-request-service\": \"bancoposta\",\n"
                        + "    \"command-request-command\": \"ricercaListaMovimentiConto\",\n"
                        + "    \"command-result-reason\": \"\",\n"
                        + "    \"status\": \"COMPLETED\"\n"
                        + "  },\n"
                        + "  \"body\": {\n"
                        + "    \"saldoH24\": true,\n"
                        + "    \"iban\": \"dummyIban\",\n"
                        + "    \"presenzaPrenotate\": false,\n"
                        + "    \"movimenti\": [\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI AGOSTO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/08/2020\",\n"
                        + "        \"dataContabile\": \"10/09/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020091000130053208500000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI LUGLIO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/07/2020\",\n"
                        + "        \"dataContabile\": \"19/08/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020081900130058781600000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"+\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI SETTEMBRE 2019\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"30/09/2019\",\n"
                        + "        \"dataContabile\": \"10/10/2019\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962019101000130045166000000\"\n"
                        + "      }\n"
                        + "    ],\n"
                        + "    \"saldo\": {\n"
                        + "      \"saldoDisponibile\": 370,\n"
                        + "      \"saldoContabile\": 370,\n"
                        + "      \"segnoSaldoContabile\": \"-\",\n"
                        + "      \"segnoSaldoDisponibile\": \"-\",\n"
                        + "      \"dataSaldo\": \"29/09/2020\"\n"
                        + "    },\n"
                        + "    \"bic\": \"BPPIITRRXXX\"\n"
                        + "  }\n"
                        + "}",
                TransactionsResponse.class);
    }

    public static TransactionsResponse getEmptyCheckingTransactionResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "  \"header\": {\n"
                        + "    \"command-result\": \"0\",\n"
                        + "    \"clientId\": \"75d20ad6-94f4-47ba-88a3-79bea47fa2a8\",\n"
                        + "    \"command-result-description\": \"\",\n"
                        + "    \"requestId\": \"\",\n"
                        + "    \"requestid\": \"cc624779-d6cd-4580-931d-028c9eaee0b6:node-3\",\n"
                        + "    \"command-result-details\": \"\",\n"
                        + "    \"command-request-version\": \"v1\",\n"
                        + "    \"command-request-service\": \"bancoposta\",\n"
                        + "    \"command-request-command\": \"ricercaListaMovimentiConto\",\n"
                        + "    \"command-result-reason\": \"\",\n"
                        + "    \"status\": \"COMPLETED\"\n"
                        + "  },\n"
                        + "  \"body\": {\n"
                        + "    \"saldoH24\": true,\n"
                        + "    \"iban\": \"dummyIban\",\n"
                        + "    \"presenzaPrenotate\": false,\n"
                        + "    \"movimenti\": ["
                        + "    ],\n"
                        + "    \"saldo\": {\n"
                        + "      \"saldoDisponibile\": 370,\n"
                        + "      \"saldoContabile\": 370,\n"
                        + "      \"segnoSaldoContabile\": \"-\",\n"
                        + "      \"segnoSaldoDisponibile\": \"-\",\n"
                        + "      \"dataSaldo\": \"29/09/2020\"\n"
                        + "    },\n"
                        + "    \"bic\": \"BPPIITRRXXX\"\n"
                        + "  }\n"
                        + "}",
                TransactionsResponse.class);
    }

    public static SavingAccountResponse getSavingAccountsResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "    \"header\": {\n"
                        + "        \"command-result\": \"0\",\n"
                        + "        \"clientId\": \"f358a2ee-eb26-4726-8282-16aa65df8043\",\n"
                        + "        \"command-result-description\": \"\",\n"
                        + "        \"requestId\": \"\",\n"
                        + "        \"requestid\": \"7681efa9-bbcd-40b7-8be6-730055eca35f:node-2\",\n"
                        + "        \"command-result-details\": \"\",\n"
                        + "        \"command-request-version\": \"v2\",\n"
                        + "        \"command-request-service\": \"bancoposta\",\n"
                        + "        \"command-request-command\": \"listaLibrettiH24\",\n"
                        + "        \"command-result-reason\": \"\",\n"
                        + "        \"status\": \"COMPLETED\"\n"
                        + "    },\n"
                        + "    \"body\": {\n"
                        + "        \"statoSemaforoBfp\": \"standard\",\n"
                        + "        \"listaLibretti\": [\n"
                        + "            {\n"
                        + "                \"onBoardable\": true,\n"
                        + "                \"presenzaBfp\": false,\n"
                        + "                \"presenzaPvr\": false,\n"
                        + "                \"monointestato\": true,\n"
                        + "                \"iban\": \"dummyIban1\",\n"
                        + "                \"numeroRapporto\": \"000050444884\",\n"
                        + "                \"librettoSmart\": true\n"
                        + "            },\n"
                        + "            {\n"
                        + "                \"onBoardable\": true,\n"
                        + "                \"presenzaBfp\": false,\n"
                        + "                \"presenzaPvr\": false,\n"
                        + "                \"monointestato\": true,\n"
                        + "                \"iban\": \"dummyIban2\",\n"
                        + "                \"numeroRapporto\": \"000050444884\",\n"
                        + "                \"librettoSmart\": true\n"
                        + "            }\n"
                        + "        ],\n"
                        + "        \"statoSemaforoDr\": \"standard\"\n"
                        + "    }\n"
                        + "}",
                SavingAccountResponse.class);
    }

    public static SavingAccountResponse getEmptySavingAccountsResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "    \"header\": {\n"
                        + "        \"command-result\": \"0\",\n"
                        + "        \"clientId\": \"f358a2ee-eb26-4726-8282-16aa65df8043\",\n"
                        + "        \"command-result-description\": \"\",\n"
                        + "        \"requestId\": \"\",\n"
                        + "        \"requestid\": \"7681efa9-bbcd-40b7-8be6-730055eca35f:node-2\",\n"
                        + "        \"command-result-details\": \"\",\n"
                        + "        \"command-request-version\": \"v2\",\n"
                        + "        \"command-request-service\": \"bancoposta\",\n"
                        + "        \"command-request-command\": \"listaLibrettiH24\",\n"
                        + "        \"command-result-reason\": \"\",\n"
                        + "        \"status\": \"COMPLETED\"\n"
                        + "    },\n"
                        + "    \"body\": {\n"
                        + "        \"statoSemaforoBfp\": \"standard\",\n"
                        + "        \"listaLibretti\": [\n"
                        + "        ],\n"
                        + "        \"statoSemaforoDr\": \"standard\"\n"
                        + "    }\n"
                        + "}",
                SavingAccountResponse.class);
    }

    public static SavingAccountDetailsResponse getSavingAccountsDetailsResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "    \"header\": {\n"
                        + "        \"command-result\": \"0\",\n"
                        + "        \"clientId\": \"3786256d-d177-40c1-b0ad-5395ffde614f\",\n"
                        + "        \"command-result-description\": \"\",\n"
                        + "        \"requestId\": \"\",\n"
                        + "        \"requestid\": \"f0be1897-2cb7-46b4-97f1-ba6f11537d3c:node-2\",\n"
                        + "        \"command-result-details\": \"\",\n"
                        + "        \"command-request-version\": \"v2\",\n"
                        + "        \"command-request-service\": \"bancoposta\",\n"
                        + "        \"command-request-command\": \"listaMovimentiLibrettoH24\",\n"
                        + "        \"command-result-reason\": \"\",\n"
                        + "        \"status\": \"COMPLETED\"\n"
                        + "    },\n"
                        + "    \"body\": {\n"
                        + "        \"listaMovimentoRisparmioPostale\": [\n"
                        + "            {\n"
                        + "                \"segno\": \"A\",\n"
                        + "                \"descrizione\": \"ACCREDITO GIRO CONTO ALTRO INTERMEDIARIO\",\n"
                        + "                \"divisa\": \"USD\",\n"
                        + "                \"dataValuta\": \"04/02/2020\",\n"
                        + "                \"dataContabile\": \"04/02/2020\",\n"
                        + "                \"descrizioneEstesa\": \"ACCREDITO GIRO CONTO ALTRO INT\",\n"
                        + "                \"importo\": 500,\n"
                        + "                \"causale\": \"BO79\"\n"
                        + "            }\n"
                        + "        ],\n"
                        + "        \"statoSemaforoBfp\": \"standard\",\n"
                        + "        \"saldo\": {\n"
                        + "            \"saldoDisponibile\": 500,\n"
                        + "            \"saldoContabile\": 1000\n"
                        + "        },\n"
                        + "        \"statoSemaforoDr\": \"standard\"\n"
                        + "    }\n"
                        + "}",
                SavingAccountDetailsResponse.class);
    }

    public static SavingTransactionResponse getSavingTransactionsResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "    \"header\": {\n"
                        + "        \"command-result\": \"0\",\n"
                        + "        \"clientId\": \"3786256d-d177-40c1-b0ad-5395ffde614f\",\n"
                        + "        \"command-result-description\": \"\",\n"
                        + "        \"requestId\": \"\",\n"
                        + "        \"requestid\": \"f0be1897-2cb7-46b4-97f1-ba6f11537d3c:node-2\",\n"
                        + "        \"command-result-details\": \"\",\n"
                        + "        \"command-request-version\": \"v2\",\n"
                        + "        \"command-request-service\": \"bancoposta\",\n"
                        + "        \"command-request-command\": \"listaMovimentiLibrettoH24\",\n"
                        + "        \"command-result-reason\": \"\",\n"
                        + "        \"status\": \"COMPLETED\"\n"
                        + "    },\n"
                        + "    \"body\": {\n"
                        + "        \"listaMovimentoRisparmioPostale\": [\n"
                        + "            {\n"
                        + "                \"segno\": \"A\",\n"
                        + "                \"descrizione\": \"ACCREDITO GIRO CONTO ALTRO INTERMEDIARIO\",\n"
                        + "                \"divisa\": \"EUR\",\n"
                        + "                \"dataValuta\": \"04/02/2020\",\n"
                        + "                \"dataContabile\": \"04/02/2020\",\n"
                        + "                \"descrizioneEstesa\": \"ACCREDITO GIRO CONTO ALTRO INT\",\n"
                        + "                \"importo\": 500,\n"
                        + "                \"causale\": \"BO79\"\n"
                        + "            },\n"
                        + "            {\n"
                        + "                \"segno\": \"A\",\n"
                        + "                \"descrizione\": \"ACCREDITO GIRO CONTO ALTRO INTERMEDIARIO\",\n"
                        + "                \"divisa\": \"EUR\",\n"
                        + "                \"dataValuta\": \"05/02/2020\",\n"
                        + "                \"descrizioneEstesa\": \"ACCREDITO GIRO CONTO ALTRO INT\",\n"
                        + "                \"importo\": 300,\n"
                        + "                \"causale\": \"BO79\"\n"
                        + "            }\n"
                        + "        ],\n"
                        + "        \"statoSemaforoBfp\": \"standard\",\n"
                        + "        \"saldo\": {\n"
                        + "            \"saldoDisponibile\": 500,\n"
                        + "            \"saldoContabile\": 500\n"
                        + "        },\n"
                        + "        \"statoSemaforoDr\": \"standard\"\n"
                        + "    }\n"
                        + "}",
                SavingTransactionResponse.class);
    }
}
