package se.tink.backend.aggregation.agents.nxgen.it.bancoposta.fetcher;

import org.junit.Ignore;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.AccountDetailsResponse;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.AccountsResponse;
import se.tink.backend.aggregation.agents.nxgen.it.banks.bancoposta.fetcher.rpc.TransactionsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public class FetcherTestData {
    public static AccountsResponse getAccountResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "    \"data\": [\n"
                        + "        {\n"
                        + "            \"id\": 841243,\n"
                        + "            \"accountIdentifier\": \"001043581196\",\n"
                        + "            \"realmIdentifier\": \"posteitaliane\",\n"
                        + "            \"accountTypeId\": 45,\n"
                        + "            \"name\": \"CONTO\",\n"
                        + "            \"balance\": 0.0000,\n"
                        + "            \"limit\": 0.0000,\n"
                        + "            \"accountClass\": null,\n"
                        + "            \"organizationName\": null,\n"
                        + "            \"organizationIdentifier\": \"posteitaliane\",\n"
                        + "            \"realmCredentialsId\": 348385,\n"
                        + "            \"accountAuthorizationType\": \"External\",\n"
                        + "            \"orderId\": 0,\n"
                        + "            \"isImportAccount\": false,\n"
                        + "            \"lastUpdate\": \"2019-01-11T21:23:31.7332123\",\n"
                        + "            \"personId\": 20348385,\n"
                        + "            \"userEmail\": \"\",\n"
                        + "            \"createDate\": \"2018-12-06T13:19:18.4503954\",\n"
                        + "            \"accountCategory\": \"Current\",\n"
                        + "            \"emergencyFundBalanceLimit\": null,\n"
                        + "            \"inactive\": false,\n"
                        + "            \"attachedToUserDate\": null,\n"
                        + "            \"isHidden\": false,\n"
                        + "            \"isDisabled\": false,\n"
                        + "            \"metadata\": [\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPFM\",\n"
                        + "                    \"value\": \"13-11-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPRIMAMOV\",\n"
                        + "                    \"value\": \"18-09-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"FLGSTO\",\n"
                        + "                    \"value\": \"S\"\n"
                        + "                }\n"
                        + "            ],\n"
                        + "            \"currencyCode\": \"EUR\",\n"
                        + "            \"accountRoleExternal\": \"MONOINTESTATO\",\n"
                        + "            \"accountStatusExternal\": \"APERTO\",\n"
                        + "            \"balanceInUserCurrency\": 0.0,\n"
                        + "            \"limitInUserCurrency\": 0.0\n"
                        + "        },\n"
                        + "        {\n"
                        + "            \"id\": 841243,\n"
                        + "            \"accountIdentifier\": \"001043581196\",\n"
                        + "            \"realmIdentifier\": \"posteitaliane\",\n"
                        + "            \"accountTypeId\": 45,\n"
                        + "            \"name\": \"CONTO\",\n"
                        + "            \"balance\": 0.0000,\n"
                        + "            \"limit\": 0.0000,\n"
                        + "            \"accountClass\": null,\n"
                        + "            \"organizationName\": null,\n"
                        + "            \"organizationIdentifier\": \"posteitaliane\",\n"
                        + "            \"realmCredentialsId\": 348385,\n"
                        + "            \"accountAuthorizationType\": \"External\",\n"
                        + "            \"orderId\": 0,\n"
                        + "            \"isImportAccount\": false,\n"
                        + "            \"lastUpdate\": \"2019-01-11T21:23:31.7332123\",\n"
                        + "            \"personId\": 20348385,\n"
                        + "            \"userEmail\": \"\",\n"
                        + "            \"createDate\": \"2018-12-06T13:19:18.4503954\",\n"
                        + "            \"accountCategory\": \"Current\",\n"
                        + "            \"emergencyFundBalanceLimit\": null,\n"
                        + "            \"inactive\": false,\n"
                        + "            \"attachedToUserDate\": null,\n"
                        + "            \"isHidden\": false,\n"
                        + "            \"isDisabled\": false,\n"
                        + "            \"metadata\": [\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPFM\",\n"
                        + "                    \"value\": \"13-11-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"DTPRIMAMOV\",\n"
                        + "                    \"value\": \"18-09-2018\"\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"name\": \"FLGSTO\",\n"
                        + "                    \"value\": \"S\"\n"
                        + "                }\n"
                        + "            ],\n"
                        + "            \"currencyCode\": \"EUR\",\n"
                        + "            \"accountRoleExternal\": \"MONOINTESTATO\",\n"
                        + "            \"accountStatusExternal\": \"APERTO\",\n"
                        + "            \"balanceInUserCurrency\": 0.0,\n"
                        + "            \"limitInUserCurrency\": 0.0\n"
                        + "        }\n"
                        + "    ]\n"
                        + "}",
                AccountsResponse.class);
    }

    public static AccountDetailsResponse getAccountDetailsResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "  \"header\": {\n"
                        + "    \"command-result\": \"0\",\n"
                        + "    \"clientId\": \"75d20ad6-94f4-47ba-88a3-79bea47fa2a8\",\n"
                        + "    \"command-result-description\": \"\",\n"
                        + "    \"requestId\": \"\",\n"
                        + "    \"requestid\": \"cc624779-d6cd-4580-931d-028c9eaee0b6:node-3\",\n"
                        + "    \"command-result-details\": \"\",\n"
                        + "    \"command-request-version\": \"v1\",\n"
                        + "    \"command-request-service\": \"bancoposta\",\n"
                        + "    \"command-request-command\": \"ricercaListaMovimentiConto\",\n"
                        + "    \"command-result-reason\": \"\",\n"
                        + "    \"status\": \"COMPLETED\"\n"
                        + "  },\n"
                        + "  \"body\": {\n"
                        + "    \"saldoH24\": true,\n"
                        + "    \"iban\": \"dummyIban\",\n"
                        + "    \"presenzaPrenotate\": false,\n"
                        + "    \"movimenti\": [\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI AGOSTO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/08/2020\",\n"
                        + "        \"dataContabile\": \"10/09/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020091000130053208500000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI LUGLIO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/07/2020\",\n"
                        + "        \"dataContabile\": \"19/08/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020081900130058781600000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"+\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI SETTEMBRE 2019\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"30/09/2019\",\n"
                        + "        \"dataContabile\": \"10/10/2019\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962019101000130045166000000\"\n"
                        + "      }\n"
                        + "    ],\n"
                        + "    \"saldo\": {\n"
                        + "      \"saldoDisponibile\": 370,\n"
                        + "      \"saldoContabile\": 370,\n"
                        + "      \"segnoSaldoContabile\": \"-\",\n"
                        + "      \"segnoSaldoDisponibile\": \"-\",\n"
                        + "      \"dataSaldo\": \"29/09/2020\"\n"
                        + "    },\n"
                        + "    \"bic\": \"BPPIITRRXXX\"\n"
                        + "  }\n"
                        + "}",
                AccountDetailsResponse.class);
    }

    public static TransactionsResponse getCheckingTransactionResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "  \"header\": {\n"
                        + "    \"command-result\": \"0\",\n"
                        + "    \"clientId\": \"75d20ad6-94f4-47ba-88a3-79bea47fa2a8\",\n"
                        + "    \"command-result-description\": \"\",\n"
                        + "    \"requestId\": \"\",\n"
                        + "    \"requestid\": \"cc624779-d6cd-4580-931d-028c9eaee0b6:node-3\",\n"
                        + "    \"command-result-details\": \"\",\n"
                        + "    \"command-request-version\": \"v1\",\n"
                        + "    \"command-request-service\": \"bancoposta\",\n"
                        + "    \"command-request-command\": \"ricercaListaMovimentiConto\",\n"
                        + "    \"command-result-reason\": \"\",\n"
                        + "    \"status\": \"COMPLETED\"\n"
                        + "  },\n"
                        + "  \"body\": {\n"
                        + "    \"saldoH24\": true,\n"
                        + "    \"iban\": \"dummyIban\",\n"
                        + "    \"presenzaPrenotate\": false,\n"
                        + "    \"movimenti\": [\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI AGOSTO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/08/2020\",\n"
                        + "        \"dataContabile\": \"10/09/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020091000130053208500000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"-\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI LUGLIO 2020\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"31/07/2020\",\n"
                        + "        \"dataContabile\": \"19/08/2020\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962020081900130058781600000\"\n"
                        + "      },\n"
                        + "      {\n"
                        + "        \"descrizioneCausale\": \"CANONE MENSILE CONTO BANCOPOSTA\",\n"
                        + "        \"segno\": \"+\",\n"
                        + "        \"header2\": \"ADDEBITO RELATIVO AL PERIODO DI SETTEMBRE 2019\",\n"
                        + "        \"header1\": \"CANONE CONTO \",\n"
                        + "        \"dataValuta\": \"30/09/2019\",\n"
                        + "        \"dataContabile\": \"10/10/2019\",\n"
                        + "        \"importo\": 400,\n"
                        + "        \"transactionID\": \"0010435811962019101000130045166000000\"\n"
                        + "      }\n"
                        + "    ],\n"
                        + "    \"saldo\": {\n"
                        + "      \"saldoDisponibile\": 370,\n"
                        + "      \"saldoContabile\": 370,\n"
                        + "      \"segnoSaldoContabile\": \"-\",\n"
                        + "      \"segnoSaldoDisponibile\": \"-\",\n"
                        + "      \"dataSaldo\": \"29/09/2020\"\n"
                        + "    },\n"
                        + "    \"bic\": \"BPPIITRRXXX\"\n"
                        + "  }\n"
                        + "}",
                TransactionsResponse.class);
    }

    public static TransactionsResponse getEmptyCheckingTransactionResponse() {
        return SerializationUtils.deserializeFromString(
                "{\n"
                        + "  \"header\": {\n"
                        + "    \"command-result\": \"0\",\n"
                        + "    \"clientId\": \"75d20ad6-94f4-47ba-88a3-79bea47fa2a8\",\n"
                        + "    \"command-result-description\": \"\",\n"
                        + "    \"requestId\": \"\",\n"
                        + "    \"requestid\": \"cc624779-d6cd-4580-931d-028c9eaee0b6:node-3\",\n"
                        + "    \"command-result-details\": \"\",\n"
                        + "    \"command-request-version\": \"v1\",\n"
                        + "    \"command-request-service\": \"bancoposta\",\n"
                        + "    \"command-request-command\": \"ricercaListaMovimentiConto\",\n"
                        + "    \"command-result-reason\": \"\",\n"
                        + "    \"status\": \"COMPLETED\"\n"
                        + "  },\n"
                        + "  \"body\": {\n"
                        + "    \"saldoH24\": true,\n"
                        + "    \"iban\": \"dummyIban\",\n"
                        + "    \"presenzaPrenotate\": false,\n"
                        + "    \"movimenti\": ["
                        + "    ],\n"
                        + "    \"saldo\": {\n"
                        + "      \"saldoDisponibile\": 370,\n"
                        + "      \"saldoContabile\": 370,\n"
                        + "      \"segnoSaldoContabile\": \"-\",\n"
                        + "      \"segnoSaldoDisponibile\": \"-\",\n"
                        + "      \"dataSaldo\": \"29/09/2020\"\n"
                        + "    },\n"
                        + "    \"bic\": \"BPPIITRRXXX\"\n"
                        + "  }\n"
                        + "}",
                TransactionsResponse.class);
    }
}
