package se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.authenticator;

public class BelfiusLoginErrorData {
    static final String NOT_ENABLED_MOBILE_BANKING =
            "{\"pendingResponseSets\":false,\"responseSets\":[{\"requestCounter\":2,\"applicationId\":\"BDM\",\"responses\":[{\"ScreenUpdate\":[{\"widgetId\":\"Container@minp_Pan\",\"properties\":[{\"text\":\"Card number\"}]},{\"widgetId\":\"Container@inp_Pan\",\"properties\":[{\"text\":\"Card number\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_title2\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@lbl_challenge\",\"properties\":[{\"text\":\"440A9450C79B84AF722FAE1EE6927EF28E706075\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_flag_not_registered\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@inp_pan\",\"properties\":[{\"text\":\"Card number\"}]},{\"widgetId\":\"Container@reuse_LoginPw@lb_challengeResponse\",\"properties\":[{\"text\":\"8839 0372\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_ina_title\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@inp_deviceToken\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_ina_descr\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_title1\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_descr2\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@minp_VersionKindApp\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@minp_TypeLogonDevice\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@inp_PushID\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@inp_signature\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_descr1\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@lb_contract_nr\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_dev_registration_flag_inactive\",\"properties\":[{\"text\":\"\"}]}]},{\"MessageResponse\":[{\"messageContent\":\"Aan deze kaart werd nog geen Belfius Mobile contract verbonden. Maak een contract aan via de app of via Belfius Direct Net.\\n(MOBILEBANKINGSESSIONHASHCODECONS/1501/1501  )\"},{\"messageDetail\":\"ERROR IN OperationMobileBankingSessionHashCodeConsultation (GE9KT082/1501/1501  )\"},{\"messageType\":\"error\"},{\"messageTarget\":\"internal\"}]}]}]}";
    static final String WRONG_CREDENTIALS =
            "{\"pendingResponseSets\":false,\"responseSets\":[{\"requestCounter\":3,\"applicationId\":\"BDM\",\"responses\":[{\"ScreenUpdate\":[{\"widgetId\":\"Container@reuse_LoginPw@lb_ActorNumberCloudID\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_ShowEidPopup\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_EidBlockingDate\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_EidAppBlocked\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_ActorFirstName\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_SegmentType\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_EidDaysB4Blocked\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_ActorLastName\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@mlb_EidMessage\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_LoginPw@inp_deviceToken\",\"properties\":[{\"text\":\"C7AFE2CDB1680D9C7F1948CC626AD380A3C71F8D\"}]}]},{\"MessageResponse\":[{\"messageContent\":\"Combinatie kaartnummer/paswoord is incorrect.\\n(MOBILEBANKINGNATAPPFINGERUSAU2UM/90AC/1307  )\"},{\"messageDetail\":\"ERROR IN OperationMobileBankingNativeAppFingerprintUserAuthentication2UtilizationManagement (GE9KT60O/90AC/1307  )\"},{\"messageType\":\"error\"},{\"messageTarget\":\"internal\"}]}]}]}";
    static final String SESSION_DOES_NOT_EXISTS =
            "{\"pendingResponseSets\":false,\"responseSets\":[{\"requestCounter\":-1,\"applicationId\":\"Unknown\",\"responses\":[{\"MessageResponse\":[{\"messageContent\":\"Technische error / Erreur technique / Technical error : ticket = PRS/s5/1544346285786 [SESSION DOESN'T EXIST]\"},{\"messageDetail\":\"\"},{\"messageType\":\"fatal\"},{\"messageTarget\":\"internal_and_container\"},{\"messageCode\":\"SESSION DOESN'T EXIST\"}]}]}]}";
    static final String UNKNOWN_SESSION =
            "{\"pendingResponseSets\":false,\"responseSets\":[{\"requestCounter\":-1,\"applicationId\":\"Unknown\",\"responses\":[{\"MessageResponse\":[{\"messageContent\":\"Technische error / Erreur technique / Technical error : ticket = PRS/s4/1544269219395 [UNKNOWN SESSION]\"},{\"messageDetail\":\"\"},{\"messageType\":\"fatal\"},{\"messageTarget\":\"internal_and_container\"},{\"messageCode\":\"UNKNOWN SESSION\"}]}]}]}";
}
