java_library(
    name = "endpoint_configuration",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:io_dropwizard_dropwizard_core",
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
    ],
)
