load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "field",
    intdeps = [
        "//src/integration/api/src/main/java/se/tink/backend/agents/rpc:field",
    ],
    visibility = ["//src/agent_sdk/sdk:__subpackages__"],
    exports = [
        "//src/integration/api/src/main/java/se/tink/backend/agents/rpc:field",
    ],
)
