package se.tink.backend.aggregation.agents.nxgen.uk.banks.metro.fetcher.account;

import org.junit.Ignore;
import se.tink.backend.aggregation.agents.nxgen.uk.banks.metro.fetcher.account.rpc.AccountsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public enum AccountFixtures {
    CHECKING_ACCOUNT(
            "{\n"
                    + "    \"entities\": [\n"
                    + "        {\n"
                    + "            \"accounts\": [\n"
                    + "                {\n"
                    + "                    \"accountId\": \"1111111111\",\n"
                    + "                    \"accountLevelAccess\": {\n"
                    + "                        \"createBeneficiary\": true,\n"
                    + "                        \"deleteBeneficiary\": false,\n"
                    + "                        \"deleteDirectDebit\": true,\n"
                    + "                        \"eligibleForOverdraft\": false,\n"
                    + "                        \"makeInternationalPayment\": true,\n"
                    + "                        \"makePayment\": true,\n"
                    + "                        \"makeRecurringPayment\": true,\n"
                    + "                        \"mobileBeneficiaryLimit\": \"2500.00\",\n"
                    + "                        \"transferFrom\": true,\n"
                    + "                        \"transferTo\": true,\n"
                    + "                        \"updateBeneficiary\": false,\n"
                    + "                        \"viewBeneficiary\": true,\n"
                    + "                        \"viewDirectDebits\": true,\n"
                    + "                        \"viewFutureDatedPayments\": true,\n"
                    + "                        \"viewStandingOrders\": true\n"
                    + "                    },\n"
                    + "                    \"accountNumber\": \"1111111111\",\n"
                    + "                    \"aerPercent\": \"29.63\",\n"
                    + "                    \"aprPercent\": \"29.63\",\n"
                    + "                    \"availableBalance\": {\n"
                    + "                        \"amount\": \"0.03\",\n"
                    + "                        \"currency\": \"GBP\"\n"
                    + "                    },\n"
                    + "                    \"card\": {\n"
                    + "                        \"accountId\": \"1111111111\",\n"
                    + "                        \"cardDesign\": \"RETAIL_DEBIT\",\n"
                    + "                        \"cardNumber\": \"557361******0517\",\n"
                    + "                        \"cardStatus\": \"ACTIVE\",\n"
                    + "                        \"cardType\": \"MCDC\",\n"
                    + "                        \"entityId\": \"10701049\",\n"
                    + "                        \"expiryDate\": \"2020-08-31\",\n"
                    + "                        \"isEligibleForNotifications\": true,\n"
                    + "                        \"metroCardNumber\": \"MCDC.0000000002470006\"\n"
                    + "                    },\n"
                    + "                    \"category\": {\n"
                    + "                        \"accountCategory\": \"CURRENT_ACCOUNT\"\n"
                    + "                    },\n"
                    + "                    \"creationDate\": \"2015-08-28\",\n"
                    + "                    \"currency\": \"GBP\",\n"
                    + "                    \"iban\": \"GB95BARC20040446135312\",\n"
                    + "                    \"isMultiCustomerAccount\": false,\n"
                    + "                    \"nickname\": \"CURRENT ACCOUNT\",\n"
                    + "                    \"ordinal\": 1,\n"
                    + "                    \"primaryBalance\": {\n"
                    + "                        \"amount\": \"0.03\",\n"
                    + "                        \"currency\": \"GBP\"\n"
                    + "                    },\n"
                    + "                    \"productType\": \"Current Account\",\n"
                    + "                    \"secondaryBalance\": {\n"
                    + "                        \"amount\": \"0.00\",\n"
                    + "                        \"currency\": \"GBP\"\n"
                    + "                    },\n"
                    + "                    \"sortCode\": \"111111\",\n"
                    + "                    \"swiftBic\": \"MYMBGB2L\",\n"
                    + "                    \"takenOverdraft\": {\n"
                    + "                        \"amount\": \"0.00\",\n"
                    + "                        \"currency\": \"GBP\"\n"
                    + "                    }\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"beneficiaries\": [\n"
                    + "            ],\n"
                    + "            \"entityId\": \"10701049\",\n"
                    + "            \"entityLevelAccess\": {\n"
                    + "                \"productAccessList\": [\n"
                    + "                    {\n"
                    + "                        \"createAccount\": true,\n"
                    + "                        \"productCode\": \"6001\"\n"
                    + "                    }\n"
                    + "                ]\n"
                    + "            },\n"
                    + "            \"entityName\": \"MYMON SZYSIAK\",\n"
                    + "            \"entityType\": \"RETAIL\"\n"
                    + "        }\n"
                    + "    ]\n"
                    + "}"),
    SAVING_ACCOUNT(
            "{\n"
                    + "    \"entities\": [\n"
                    + "        {\n"
                    + "            \"accounts\": [\n"
                    + "                {\n"
                    + "                    \"accountId\": \"1111111111\",\n"
                    + "                    \"accountLevelAccess\": {\n"
                    + "                        \"createBeneficiary\": true,\n"
                    + "                        \"deleteBeneficiary\": false,\n"
                    + "                        \"deleteDirectDebit\": false,\n"
                    + "                        \"eligibleForOverdraft\": false,\n"
                    + "                        \"makeInternationalPayment\": false,\n"
                    + "                        \"makePayment\": true,\n"
                    + "                        \"makeRecurringPayment\": true,\n"
                    + "                        \"mobileBeneficiaryLimit\": \"2500.00\",\n"
                    + "                        \"transferFrom\": true,\n"
                    + "                        \"transferTo\": true,\n"
                    + "                        \"updateBeneficiary\": false,\n"
                    + "                        \"viewBeneficiary\": true,\n"
                    + "                        \"viewDirectDebits\": true,\n"
                    + "                        \"viewFutureDatedPayments\": true,\n"
                    + "                        \"viewStandingOrders\": true\n"
                    + "                    },\n"
                    + "                    \"accountNumber\": \"1111111111\",\n"
                    + "                    \"aerPercent\": \"0.10\",\n"
                    + "                    \"aprPercent\": \"0.10\",\n"
                    + "                    \"availableBalance\": {\n"
                    + "                        \"amount\": \"0.00\",\n"
                    + "                        \"currency\": \"GBP\"\n"
                    + "                    },\n"
                    + "                    \"category\": {\n"
                    + "                        \"accountCategory\": \"SAVINGS_ACCOUNT\"\n"
                    + "                    },\n"
                    + "                    \"creationDate\": \"2016-07-15\",\n"
                    + "                    \"currency\": \"GBP\",\n"
                    + "                    \"iban\": \"GB95BARC20040446135312\",\n"
                    + "                    \"isMultiCustomerAccount\": false,\n"
                    + "                    \"nickname\": \"Savings\",\n"
                    + "                    \"ordinal\": 30,\n"
                    + "                    \"primaryBalance\": {\n"
                    + "                        \"amount\": \"0.00\",\n"
                    + "                        \"currency\": \"GBP\"\n"
                    + "                    },\n"
                    + "                    \"productType\": \"Instant Access Account\",\n"
                    + "                    \"secondaryBalance\": {\n"
                    + "                        \"amount\": \"0.00\",\n"
                    + "                        \"currency\": \"GBP\"\n"
                    + "                    },\n"
                    + "                    \"sortCode\": \"111111\",\n"
                    + "                    \"swiftBic\": \"MYMBGB2L\"\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"beneficiaries\": [\n"
                    + "            ],\n"
                    + "            \"entityId\": \"10701049\",\n"
                    + "            \"entityLevelAccess\": {\n"
                    + "                \"productAccessList\": [\n"
                    + "                    {\n"
                    + "                        \"createAccount\": true,\n"
                    + "                        \"productCode\": \"6001\"\n"
                    + "                    }\n"
                    + "                ]\n"
                    + "            },\n"
                    + "            \"entityName\": \"MYMON SZYSIAK\",\n"
                    + "            \"entityType\": \"RETAIL\"\n"
                    + "        }\n"
                    + "    ]\n"
                    + "}");

    private final String json;

    AccountFixtures(String json) {
        this.json = json;
    }

    AccountsResponse toObject() {
        return SerializationUtils.deserializeFromString(json, AccountsResponse.class);
    }
}
