package se.tink.backend.aggregation.agents.nxgen.serviceproviders.banks.sdc.fetcher.rpc;

import org.junit.Ignore;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public class ListCreditCardsResponseTestData {

    static ListCreditCardsResponse getTestDataOneCreditCard() {
        return SerializationUtils.deserializeFromString(
                TEST_DATA_ONE_CREDIT_CARD, ListCreditCardsResponse.class);
    }

    static ListCreditCardsResponse getTestDataTwoCreditCardsForOneAccountPickFirst() {
        return SerializationUtils.deserializeFromString(
                TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_PICK_FIRST,
                ListCreditCardsResponse.class);
    }

    static ListCreditCardsResponse getTestDataTwoCreditCardsForOneAccountPickSecond() {
        return SerializationUtils.deserializeFromString(
                TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_PICK_SECOND,
                ListCreditCardsResponse.class);
    }

    static ListCreditCardsResponse getTestDataTwoCreditCardsForOneAccountFirstEndDateNull() {
        return SerializationUtils.deserializeFromString(
                TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_ADDED_CARD_NULL_ENDDATE,
                ListCreditCardsResponse.class);
    }

    static ListCreditCardsResponse getTestDataTwoCreditCardsForOneAccountSecondEndDateNull() {
        return SerializationUtils.deserializeFromString(
                TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_NEW_CARD_NULL_ENDDATE,
                ListCreditCardsResponse.class);
    }

    static ListCreditCardsResponse getTestDataTwoCreditCardsAndTwoAccounts() {
        return SerializationUtils.deserializeFromString(
                TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_EACH, ListCreditCardsResponse.class);
    }

    private static final String TEST_DATA_ONE_CREDIT_CARD =
            "[ {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344411\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2017-11-07\","
                    + "  \"creditcardNumber\" : \"332211xxxxxx7788\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.6198765\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.6198765\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.61.98765\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2021-11-28\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"644221133557799\""
                    + "  },"
                    + "  \"creditcardType\" : \"VISA_DEBET_NO\","
                    + "  \"creditcardTypeName\" : \"visa debet\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2017-11-07\","
                    + "  \"creditcardNumber\" : \"111333xxxxxx7799\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"8776.3243377\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"8776.3243377\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"8776.32.43377\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Visakort\""
                    + "  },"
                    + "  \"endDate\" : \"2021-11-28\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "} ]";

    private static final String TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_PICK_FIRST =
            "[ {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344411\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2018-05-16\","
                    + "  \"creditcardNumber\" : \"776615xxxxxx3855\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2021-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344412\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"665549xxxxxx9444\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344413\""
                    + "  },"
                    + "  \"creditcardType\" : \"VISA_DEBET_NO\","
                    + "  \"creditcardTypeName\" : \"visa debet\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"554479xxxxxx3433\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"9934.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"9934.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"9934.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Matkonto\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "} ]";

    private static final String TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_PICK_SECOND =
            "[ {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344411\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2015-05-16\","
                    + "  \"creditcardNumber\" : \"776615xxxxxx3855\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2018-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344412\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"665549xxxxxx9444\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344413\""
                    + "  },"
                    + "  \"creditcardType\" : \"VISA_DEBET_NO\","
                    + "  \"creditcardTypeName\" : \"visa debet\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"554479xxxxxx3433\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"9934.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"9934.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"9934.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Matkonto\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "} ]";

    private static final String TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_ADDED_CARD_NULL_ENDDATE =
            "[ {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344411\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2018-05-16\","
                    + "  \"creditcardNumber\" : \"776615xxxxxx3855\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344412\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"665549xxxxxx9444\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344413\""
                    + "  },"
                    + "  \"creditcardType\" : \"VISA_DEBET_NO\","
                    + "  \"creditcardTypeName\" : \"visa debet\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"554479xxxxxx3433\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"9934.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"9934.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"9934.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Matkonto\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "} ]";

    private static final String TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_NEW_CARD_NULL_ENDDATE =
            "[ {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344411\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2018-05-16\","
                    + "  \"creditcardNumber\" : \"776615xxxxxx3855\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2021-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344412\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"665549xxxxxx9444\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344413\""
                    + "  },"
                    + "  \"creditcardType\" : \"VISA_DEBET_NO\","
                    + "  \"creditcardTypeName\" : \"visa debet\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"554479xxxxxx3433\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"9934.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"9934.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"9934.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Matkonto\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "} ]";

    private static final String TEST_DATA_TWO_CREDIT_CARDS_FOR_ONE_ACCOUNT_EACH =
            "[ {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344411\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2018-05-16\","
                    + "  \"creditcardNumber\" : \"776615xxxxxx3855\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"1234.56709\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.56709\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"1234.05.6709\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2021-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344412\""
                    + "  },"
                    + "  \"creditcardType\" : \"MASTERCARD\","
                    + "  \"creditcardTypeName\" : \"kredittkort\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"665549xxxxxx9444\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"9934.56709\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"9934.56709\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"9934.05.6709\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Kredittkort\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "}, {"
                    + "  \"entityKey\" : {"
                    + "    \"rifsIdfr\" : \"111122233344413\""
                    + "  },"
                    + "  \"creditcardType\" : \"VISA_DEBET_NO\","
                    + "  \"creditcardTypeName\" : \"visa debet\","
                    + "  \"creditcardStatus\" : \"utlevert\","
                    + "  \"statusEffectiveDate\" : \"2016-11-03\","
                    + "  \"creditcardNumber\" : \"554479xxxxxx3433\","
                    + "  \"cardHolderName\" : \"KALLE KULA\","
                    + "  \"attachedAccount\" : {"
                    + "    \"id\" : \"9934.56789\","
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"9934.56789\","
                    + "      \"agreementId\" : null"
                    + "    },"
                    + "    \"localizedAccountId\" : \"9934.05.6789\","
                    + "    \"type\" : \"KS-KONTO\","
                    + "    \"currency\" : \"NOK\","
                    + "    \"name\" : \"Matkonto\""
                    + "  },"
                    + "  \"endDate\" : \"2019-12-31\","
                    + "  \"creditcardStatusType\" : \"UDLEVERET\""
                    + "} ]";
}
