package se.tink.backend.aggregation.agents.nxgen.serviceproviders.banks.sdc.fetcher.rpc;

import org.junit.Ignore;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public class SearchCreditCardTransactionsResponseTestData {

    static SearchTransactionsResponse getTestData() {
        return SerializationUtils.deserializeFromString(
                TEST_DATA, SearchTransactionsResponse.class);
    }

    private static final String TEST_DATA =
            "{"
                    + "  \"transactions\" : [ {"
                    + "    \"paymentDate\" : \"2017-12-15\","
                    + "    \"amount\" : {"
                    + "      \"localizedValue\" : \"0.01\","
                    + "      \"localizedValueWithCurrency\" : \"0.01 NOK\","
                    + "      \"value\" : 1,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"0.01 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"NOK0\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"0 NOK\""
                    + "    },"
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.6198765\","
                    + "      \"agreementId\" : \"112233445566789\","
                    + "      \"refNumber\" : \"000035544\","
                    + "      \"amount\" : \"1\","
                    + "      \"paymentDate\" : \"2017-12-15\","
                    + "      \"hostTms\" : \"2017-12-15-15.59.53.554428\","
                    + "      \"pstgWsId\" : \"000N0425\","
                    + "      \"pciHostTimeStamp\" : \"0000-00-00-00.00.00.000000\","
                    + "      \"dtCreate\" : \"2017-12-15\","
                    + "      \"ownText\" : \"\","
                    + "      \"balance\" : \"-8899\","
                    + "      \"ldbId\" : \"000090\","
                    + "      \"afrIdfr\" : \"112233445566789\","
                    + "      \"pccgHostTs\" : \"\""
                    + "    },"
                    + "    \"balance\" : {"
                    + "      \"localizedValue\" : \"-88.99\","
                    + "      \"localizedValueWithCurrency\" : \"-88.99 NOK\","
                    + "      \"value\" : -8899,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"-88.99 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"-NOK89\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"-89 NOK\""
                    + "    },"
                    + "    \"label\" : \"Innbetaling OCR Giro \","
                    + "    \"originalText\" : \"\","
                    + "    \"clearingChoice\" : \"Unknown\","
                    + "    \"icon\" : {"
                    + "      \"color\" : \"54B017\","
                    + "      \"name\" : \"icon_spo_pension_2f\""
                    + "    },"
                    + "    \"categoryLabel\" : \"Income\","
                    + "    \"subCategoryLabel\" : \"Other income\","
                    + "    \"dueDate\" : \"2017-12-15\","
                    + "    \"crrfValue\" : null,"
                    + "    \"eerfValue\" : null"
                    + "  }, {"
                    + "    \"paymentDate\" : \"2017-12-08\","
                    + "    \"amount\" : {"
                    + "      \"localizedValue\" : \"-89.00\","
                    + "      \"localizedValueWithCurrency\" : \"-89.00 NOK\","
                    + "      \"value\" : -8900,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"-89.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"-NOK89\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"-89 NOK\""
                    + "    },"
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.6198765\","
                    + "      \"agreementId\" : \"112233445566789\","
                    + "      \"refNumber\" : \"0000000812\","
                    + "      \"amount\" : \"-8900\","
                    + "      \"paymentDate\" : \"2017-12-08\","
                    + "      \"hostTms\" : \"2017-12-08-21.52.14.097822\","
                    + "      \"pstgWsId\" : \"00000057\","
                    + "      \"pciHostTimeStamp\" : \"0000-00-00-00.00.00.000000\","
                    + "      \"dtCreate\" : \"2017-12-08\","
                    + "      \"ownText\" : \"\","
                    + "      \"balance\" : \"-8900\","
                    + "      \"ldbId\" : \"09060\","
                    + "      \"afrIdfr\" : \"112233445566789\","
                    + "      \"pccgHostTs\" : \"\""
                    + "    },"
                    + "    \"balance\" : {"
                    + "      \"localizedValue\" : \"-89.00\","
                    + "      \"localizedValueWithCurrency\" : \"-89.00 NOK\","
                    + "      \"value\" : -8900,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"-89.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"-NOK89\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"-89 NOK\""
                    + "    },"
                    + "    \"label\" : \"ITUNES.COM/BILL, IT  0,00 Kurs 0,0000 Notanr 0\","
                    + "    \"originalText\" : \"\","
                    + "    \"clearingChoice\" : \"Unknown\","
                    + "    \"icon\" : {"
                    + "      \"color\" : \"EC7608\","
                    + "      \"name\" : \"icon_spo_shopping_38\""
                    + "    },"
                    + "    \"categoryLabel\" : \"Private consumption\","
                    + "    \"subCategoryLabel\" : \"Books, music and films\","
                    + "    \"dueDate\" : \"2017-12-08\","
                    + "    \"crrfValue\" : null,"
                    + "    \"eerfValue\" : null"
                    + "  }, {"
                    + "    \"paymentDate\" : \"2017-10-28\","
                    + "    \"amount\" : {"
                    + "      \"localizedValue\" : \"10.00\","
                    + "      \"localizedValueWithCurrency\" : \"10.00 NOK\","
                    + "      \"value\" : 1000,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"10.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"NOK10\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"10 NOK\""
                    + "    },"
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.6198765\","
                    + "      \"agreementId\" : \"112233445566789\","
                    + "      \"refNumber\" : \"00000960\","
                    + "      \"amount\" : \"1000\","
                    + "      \"paymentDate\" : \"2017-10-28\","
                    + "      \"hostTms\" : \"2017-10-28-09.46.58.027150\","
                    + "      \"pstgWsId\" : \"Ho00bank\","
                    + "      \"pciHostTimeStamp\" : \"0000-00-00-00.00.00.000000\","
                    + "      \"dtCreate\" : \"2017-10-28\","
                    + "      \"ownText\" : \"\","
                    + "      \"balance\" : \"0\","
                    + "      \"ldbId\" : \"00000\","
                    + "      \"afrIdfr\" : \"112233445566789\","
                    + "      \"pccgHostTs\" : \"\""
                    + "    },"
                    + "    \"balance\" : {"
                    + "      \"localizedValue\" : \"0.00\","
                    + "      \"localizedValueWithCurrency\" : \"0.00 NOK\","
                    + "      \"value\" : 0,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"0.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"NOK0\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"0 NOK\""
                    + "    },"
                    + "    \"label\" : \"Overføring  Iflg. melding nr.  Betalingsdato\","
                    + "    \"originalText\" : \"\","
                    + "    \"clearingChoice\" : \"Unknown\","
                    + "    \"icon\" : {"
                    + "      \"color\" : \"54B017\","
                    + "      \"name\" : \"icon_spo_pension_2f\""
                    + "    },"
                    + "    \"categoryLabel\" : \"Income\","
                    + "    \"subCategoryLabel\" : \"Other income\","
                    + "    \"dueDate\" : \"2017-10-28\","
                    + "    \"crrfValue\" : null,"
                    + "    \"eerfValue\" : null"
                    + "  }, {"
                    + "    \"paymentDate\" : \"2017-10-20\","
                    + "    \"amount\" : {"
                    + "      \"localizedValue\" : \"-10.00\","
                    + "      \"localizedValueWithCurrency\" : \"-10.00 NOK\","
                    + "      \"value\" : -1000,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"-10.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"-NOK10\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"-10 NOK\""
                    + "    },"
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.6198765\","
                    + "      \"agreementId\" : \"112233445566789\","
                    + "      \"refNumber\" : \"0000000660\","
                    + "      \"amount\" : \"-1000\","
                    + "      \"paymentDate\" : \"2017-10-20\","
                    + "      \"hostTms\" : \"2017-10-20-21.09.26.058346\","
                    + "      \"pstgWsId\" : \"000000\","
                    + "      \"pciHostTimeStamp\" : \"0000-00-00-00.00.00.000000\","
                    + "      \"dtCreate\" : \"2017-10-20\","
                    + "      \"ownText\" : \"\","
                    + "      \"balance\" : \"-1000\","
                    + "      \"ldbId\" : \"09060\","
                    + "      \"afrIdfr\" : \"112233445566789\","
                    + "      \"pccgHostTs\" : \"\""
                    + "    },"
                    + "    \"balance\" : {"
                    + "      \"localizedValue\" : \"-10.00\","
                    + "      \"localizedValueWithCurrency\" : \"-10.00 NOK\","
                    + "      \"value\" : -1000,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"-10.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"-NOK10\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"-10 NOK\""
                    + "    },"
                    + "    \"label\" : \"ITUNES.COM/BILL, IT  0,00 Kurs 0,0000 Notanr 00\","
                    + "    \"originalText\" : \"\","
                    + "    \"clearingChoice\" : \"Unknown\","
                    + "    \"icon\" : {"
                    + "      \"color\" : \"000608\","
                    + "      \"name\" : \"icon_spo_shopping_38\""
                    + "    },"
                    + "    \"categoryLabel\" : \"Private consumption\","
                    + "    \"subCategoryLabel\" : \"Books, music and films\","
                    + "    \"dueDate\" : \"2017-10-20\","
                    + "    \"crrfValue\" : null,"
                    + "    \"eerfValue\" : null"
                    + "  }, {"
                    + "    \"paymentDate\" : \"2017-10-15\","
                    + "    \"amount\" : {"
                    + "      \"localizedValue\" : \"32.00\","
                    + "      \"localizedValueWithCurrency\" : \"32.00 NOK\","
                    + "      \"value\" : 3200,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"32.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"NOK32\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"32 NOK\""
                    + "    },"
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.6198765\","
                    + "      \"agreementId\" : \"112233445566789\","
                    + "      \"refNumber\" : \"1554284949\","
                    + "      \"amount\" : \"3200\","
                    + "      \"paymentDate\" : \"2017-10-15\","
                    + "      \"hostTms\" : \"2017-10-15-15.54.28.494902\","
                    + "      \"pstgWsId\" : \"00000400\","
                    + "      \"pciHostTimeStamp\" : \"0000-00-00-00.00.00.000000\","
                    + "      \"dtCreate\" : \"2017-10-15\","
                    + "      \"ownText\" : \"\","
                    + "      \"balance\" : \"0\","
                    + "      \"ldbId\" : \"00000\","
                    + "      \"afrIdfr\" : \"112233445566789\","
                    + "      \"pccgHostTs\" : \"\""
                    + "    },"
                    + "    \"balance\" : {"
                    + "      \"localizedValue\" : \"0.00\","
                    + "      \"localizedValueWithCurrency\" : \"0.00 NOK\","
                    + "      \"value\" : 0,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"0.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"NOK0\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"0 NOK\""
                    + "    },"
                    + "    \"label\" : \"Innbetaling OCR Giro 00\","
                    + "    \"originalText\" : \"\","
                    + "    \"clearingChoice\" : \"Unknown\","
                    + "    \"icon\" : {"
                    + "      \"color\" : \"54B017\","
                    + "      \"name\" : \"icon_spo_pension_2f\""
                    + "    },"
                    + "    \"categoryLabel\" : \"Income\","
                    + "    \"subCategoryLabel\" : \"Other income\","
                    + "    \"dueDate\" : \"2017-10-15\","
                    + "    \"crrfValue\" : null,"
                    + "    \"eerfValue\" : null"
                    + "  }, {"
                    + "    \"paymentDate\" : \"2017-09-20\","
                    + "    \"amount\" : {"
                    + "      \"localizedValue\" : \"-10.00\","
                    + "      \"localizedValueWithCurrency\" : \"-10.00 NOK\","
                    + "      \"value\" : -1000,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"-10.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"-NOK10\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"-10 NOK\""
                    + "    },"
                    + "    \"entityKey\" : {"
                    + "      \"accountId\" : \"1234.6198765\","
                    + "      \"agreementId\" : \"112233445566789\","
                    + "      \"refNumber\" : \"0045725734\","
                    + "      \"amount\" : \"-1000\","
                    + "      \"paymentDate\" : \"2017-09-20\","
                    + "      \"hostTms\" : \"2017-09-20-22.16.53.648737\","
                    + "      \"pstgWsId\" : \"000N0000\","
                    + "      \"pciHostTimeStamp\" : \"0000-00-00-00.00.00.000000\","
                    + "      \"dtCreate\" : \"2017-09-20\","
                    + "      \"ownText\" : \"\","
                    + "      \"balance\" : \"-3200\","
                    + "      \"ldbId\" : \"000000\","
                    + "      \"afrIdfr\" : \"112233445566789\","
                    + "      \"pccgHostTs\" : \"\""
                    + "    },"
                    + "    \"balance\" : {"
                    + "      \"localizedValue\" : \"-32.00\","
                    + "      \"localizedValueWithCurrency\" : \"-32.00 NOK\","
                    + "      \"value\" : -3200,"
                    + "      \"scale\" : 2,"
                    + "      \"currency\" : \"NOK\","
                    + "      \"localizedValueWithCurrencyAtEnd\" : \"-32.00 NOK\","
                    + "      \"roundedAmountWithIsoCurrency\" : \"-NOK32\","
                    + "      \"roundedAmountWithCurrencySymbol\" : \"-32 NOK\""
                    + "    },"
                    + "    \"label\" : \"ITUNES.COM/BILL, IT  0,00 Kurs 0,0000 Notanr 000\","
                    + "    \"originalText\" : \"\","
                    + "    \"clearingChoice\" : \"Unknown\","
                    + "    \"icon\" : {"
                    + "      \"color\" : \"EC7608\","
                    + "      \"name\" : \"icon_spo_shopping_38\""
                    + "    },"
                    + "    \"categoryLabel\" : \"Private consumption\","
                    + "    \"subCategoryLabel\" : \"Books, music and films\","
                    + "    \"dueDate\" : \"2017-09-20\","
                    + "    \"crrfValue\" : null,"
                    + "    \"eerfValue\" : null"
                    + "  } ],"
                    + "\"reservations\" : [ {"
                    + "      \"id\": \"1122411431159137333346\","
                    + "      \"type\": \"VPES\","
                    + "      \"amount\": {"
                    + "        \"localizedValue\": \"-33.00\","
                    + "        \"localizedValueWithCurrency\": \"-33.00 NOK\","
                    + "        \"value\": -3300,"
                    + "        \"scale\": 2,"
                    + "        \"currency\": \"NOK\","
                    + "        \"localizedValueWithCurrencyAtEnd\": \"-33.00 NOK\","
                    + "        \"roundedAmountWithIsoCurrency\": \"-NOK33\","
                    + "        \"roundedAmountWithCurrencySymbol\": \"-33 NOK\""
                    + "      },"
                    + "      \"calculatedAmount\": {"
                    + "        \"localizedValue\": \"9,405.82\","
                    + "        \"localizedValueWithCurrency\": \"9,405.82\","
                    + "        \"value\": 940582,"
                    + "        \"scale\": 2,"
                    + "        \"currency\": null,"
                    + "        \"localizedValueWithCurrencyAtEnd\": null,"
                    + "        \"roundedAmountWithIsoCurrency\": null,"
                    + "        \"roundedAmountWithCurrencySymbol\": null"
                    + "      },"
                    + "      \"expirationDate\": \"2017-12-05\","
                    + "      \"description\": \"Vipps by DnB/OSLO/NO\","
                    + "      \"hostId\": \"112358767144769\","
                    + "      \"createDate\": \"2017-11-30\","
                    + "      \"createTimestamp\": \"2017-11-30T09:03:46\","
                    + "      \"status\": \"ACTIVE\","
                    + "      \"validation\": \"UNKN\","
                    + "      \"labelValuePair\": ["
                    + "        {"
                    + "          \"label\": \"Amount\","
                    + "          \"value\": \"-33.00\""
                    + "        },"
                    + "        {"
                    + "          \"label\": \"Reservation number\","
                    + "          \"value\": \"1122411431159137333346\""
                    + "        },"
                    + "        {"
                    + "          \"label\": \"Created on\","
                    + "          \"value\": \"2017-11-30\""
                    + "        },"
                    + "        {"
                    + "          \"label\": \"Expiration date\","
                    + "          \"value\": \"2017-12-05\""
                    + "        },"
                    + "        {"
                    + "          \"label\": \"Status\","
                    + "          \"value\": \"aktiv\""
                    + "        }"
                    + "      ]"
                    + "} ],"
                    + "  \"totalReservationsAmount\" : null"
                    + "}";
}
