alias(
    name = "transmitter-lib",
    actual = "//src/integration/agent_capability_tracker/lib/src/main/java/se/tink/backend/integration/agentcapabilitytracker/transmitter:transmitter-lib",
    visibility = ["//visibility:public"],
)

alias(
    name = "transmitter-lib-test",
    actual = "//src/integration/agent_capability_tracker/lib/src/test/java/se/tink/backend/integration/agentcapabilitytracker/transmitter:transmitter-lib-test",
)
