java_library(
    name = "identification",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/metrics:core",
        "//third_party:com_google_guava_guava",
    ],
)
