package se.tink.libraries.credentials.service;

public enum DataFetchingRestrictions {
    // Restrictions based on PSD2 Payment Account Determination
    RESTRICT_FETCHING_PSD2_PAYMENT_ACCOUNTS,
    RESTRICT_FETCHING_PSD2_UNDETERMINED_PAYMENT_ACCOUNTS,
    // Restrictions based on Tink Account Type
    RESTRICT_FETCHING_CHECKING_ACCOUNTS,
    RESTRICT_FETCHING_CHECKING_TRANSACTIONS,
    RESTRICT_FETCHING_SAVINGS_ACCOUNTS,
    RESTRICT_FETCHING_SAVINGS_TRANSACTIONS,
    RESTRICT_FETCHING_CREDIT_CARD_ACCOUNTS,
    RESTRICT_FETCHING_CREDIT_CARD_TRANSACTIONS,
    RESTRICT_FETCHING_LOAN_ACCOUNTS,
    RESTRICT_FETCHING_LOAN_TRANSACTIONS,
    RESTRICT_FETCHING_INVESTMENT_ACCOUNTS,
    RESTRICT_FETCHING_INVESTMENT_TRANSACTIONS,
}
