package se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.creditagricole.transactionalaccount.apiclient;

import se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.creditagricole.transactionalaccount.rpc.GetTransactionsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

class TransactionsFixtures {

    static final GetTransactionsResponse transactionsResponse =
            SerializationUtils.deserializeFromString(
                    "{\n"
                            + "    \"_links\": {\n"
                            + "        \"self\": {\n"
                            + "            \"href\": \"/accounts/123/transactions\",\n"
                            + "            \"templated\": true\n"
                            + "        },\n"
                            + "        \"balances\": {\n"
                            + "            \"href\": \"/accounts/123/balances\",\n"
                            + "            \"templated\": false\n"
                            + "        },\n"
                            + "        \"parent-list\": {\n"
                            + "            \"href\": \"/accounts\",\n"
                            + "            \"templated\": false\n"
                            + "        },\n"
                            + "        \"prev\": null,\n"
                            + "        \"last\": null,\n"
                            + "        \"next\": {\n"
                            + "            \"href\": null,\n"
                            + "            \"templated\": true\n"
                            + "        },\n"
                            + "        \"first\": null\n"
                            + "    },\n"
                            + "    \"transactions\": [\n"
                            + "        {\n"
                            + "            \"resourceId\": null,\n"
                            + "            \"entryReference\": \"1234\",\n"
                            + "            \"bookingDate\": \"2020-01-17\",\n"
                            + "            \"valueDate\": \"2020-01-17\",\n"
                            + "            \"transactionDate\": null,\n"
                            + "            \"status\": \"BOOK\",\n"
                            + "            \"creditDebitIndicator\": \"DBIT\",\n"
                            + "            \"remittanceInformation\": [\n"
                            + "                \"PAIEMENT PAR CARTE PXP*elptoo.fr + 11/01\"\n"
                            + "            ],\n"
                            + "            \"transactionAmount\": {\n"
                            + "                \"currency\": \"EUR\",\n"
                            + "                \"amount\": \"39.00\"\n"
                            + "            }\n"
                            + "        },\n"
                            + "        {\n"
                            + "            \"resourceId\": null,\n"
                            + "            \"entryReference\": \"546645\",\n"
                            + "            \"bookingDate\": \"2020-01-17\",\n"
                            + "            \"valueDate\": \"2020-01-17\",\n"
                            + "            \"transactionDate\": null,\n"
                            + "            \"status\": \"BOOK\",\n"
                            + "            \"creditDebitIndicator\": \"DBIT\",\n"
                            + "            \"remittanceInformation\": [\n"
                            + "                \"PAIEMENT PAR CARTE SARL LMCG LE MANS 11 \"\n"
                            + "            ],\n"
                            + "            \"transactionAmount\": {\n"
                            + "                \"currency\": \"EUR\",\n"
                            + "                \"amount\": \"13.00\"\n"
                            + "            }\n"
                            + "        }\n"
                            + "    ]\n"
                            + "}",
                    GetTransactionsResponse.class);
}
