load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "encoding",
    srcs = glob(["*.java"]),
    extdeps = [
        "//third_party:commons_codec_commons_codec",
    ],
    visibility = ["//visibility:public"],
)
