java_library(
    name = "encoding",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:commons_codec_commons_codec",
        "@aggregation//:com_google_guava_guava",
    ],
)
