package se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.transactionalaccount;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.when;
import static se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.AmexTestFixtures.createHmacToken;
import static se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.AmexTestFixtures.createMultiToken;

import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.AmexApiClient;
import se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.dto.AccountsResponseDto;
import se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.dto.BalanceDto;
import se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.dto.StatementPeriodsDto;
import se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.amex.transactionalaccount.storage.HmacAccountIdStorage;
import se.tink.backend.aggregation.nxgen.controllers.authentication.multifactor.thirdpartyapp.hmac.HmacMultiTokenStorage;
import se.tink.backend.aggregation.nxgen.core.account.creditcard.CreditCardAccount;
import se.tink.backend.aggregation.nxgen.core.authentication.HmacMultiToken;
import se.tink.backend.aggregation.nxgen.core.authentication.HmacToken;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class AmexCreditCardFetcherTest {

    private AmexCreditCardFetcher amexCreditCardFetcher;
    private AmexApiClient spyApiClient;
    private HmacMultiTokenStorage hmacMultiTokenStorage;
    private HmacAccountIdStorage hmacAccountIdStorage;
    private HmacToken hmacToken;

    @Before
    public void setUp() {
        AmexApiClient amexApiClient = mock(AmexApiClient.class);
        spyApiClient = spy(amexApiClient);
        hmacAccountIdStorage = mock(HmacAccountIdStorage.class);
        hmacMultiTokenStorage = mock(HmacMultiTokenStorage.class);
        hmacToken = createHmacToken();
        final HmacMultiToken multiToken = createMultiToken(Collections.singletonList(hmacToken));
        when(hmacMultiTokenStorage.getToken()).thenReturn(Optional.of(multiToken));
        amexCreditCardFetcher =
                new AmexCreditCardFetcher(
                        spyApiClient, hmacMultiTokenStorage, hmacAccountIdStorage);
    }

    @Test
    public void shouldMapCurrencyCorrectWhenLocalCurrencyMatchBalanceCurrency() {
        AccountsResponseDto accounts = getAccountsWhereCurrencyMatchLocalCurrency();
        doReturn(accounts).when(spyApiClient).fetchAccounts(any());
        doReturn(getStatements()).when(spyApiClient).fetchStatementPeriods(any());
        doReturn(Collections.singletonList(getBalanceWhereCurrencyMatchLocalCurrency()))
                .when(spyApiClient)
                .fetchBalances(any());

        String holderCurrencyCode = accounts.getHolder().getCurrencyCode();

        Collection<CreditCardAccount> result = amexCreditCardFetcher.fetchAccounts();

        Assert.assertEquals(5, result.size());

        List<String> listOfCurrencyCodes =
                result.stream()
                        .map(r -> r.getExactBalance().getCurrencyCode())
                        .collect(Collectors.toList());

        Assert.assertTrue(listOfCurrencyCodes.stream().allMatch(holderCurrencyCode::equals));
    }

    @Test
    public void shouldMapCurrencyToBalanceCurrencyIfLocaleCurrencyDoesNotMatchBalanceCurrency() {
        AccountsResponseDto accounts = getAccountsWhereCurrencyDoesNotMatchLocaleCurrency();
        doReturn(accounts).when(spyApiClient).fetchAccounts(any());
        doReturn(getStatements()).when(spyApiClient).fetchStatementPeriods(any());
        doReturn(Collections.singletonList(getBalanceCurrencyDoesNotMatchLocal()))
                .when(spyApiClient)
                .fetchBalances(any());

        // EUR
        String holderCurrencyCode = accounts.getHolder().getCurrencyCode();

        Collection<CreditCardAccount> result = amexCreditCardFetcher.fetchAccounts();

        Assert.assertEquals(5, result.size());

        List<String> listOfCurrencyCodes =
                result.stream()
                        .map(r -> r.getExactBalance().getCurrencyCode())
                        .collect(Collectors.toList());

        // Balance currency USD & Holder locale_currency is EUR
        Assert.assertFalse(listOfCurrencyCodes.stream().allMatch(holderCurrencyCode::equals));
        Assert.assertTrue(listOfCurrencyCodes.stream().allMatch("USD"::equals));
    }

    private BalanceDto getBalanceCurrencyDoesNotMatchLocal() {
        return SerializationUtils.deserializeFromString(
                "{\"last_statement_balance_amount\":\"6177.40\","
                        + "\"debits_balance_amount\":\"61.67\","
                        + "\"payments_credits_amount\":\"0.00\","
                        + "\"statement_balance_amount\":\"6239.07\","
                        + "\"payment_due_amount\":\"6177.40\","
                        + "\"iso_alpha_currency_code\":\"USD\","
                        + "\"payment_due_date\":\"2022-01-28\","
                        + "\"remaining_statement_balance_amount\":\"6177.40\","
                        + "\"statement_start_date\":\"2022-01-15\","
                        + "\"statement_end_date\":\"2022-02-14\"}",
                BalanceDto.class);
    }

    private BalanceDto getBalanceWhereCurrencyMatchLocalCurrency() {
        return SerializationUtils.deserializeFromString(
                "{\"last_statement_balance_amount\":\"1290.58\","
                        + "\"debits_balance_amount\":\"3774.40\","
                        + "\"payments_credits_amount\":\"1200.00\","
                        + "\"statement_balance_amount\":\"3864.98\","
                        + "\"payment_due_amount\":\"0.00\","
                        + "\"iso_alpha_currency_code\":\"SEK\","
                        + "\"payment_due_date\":\"2020-06-27\","
                        + "\"remaining_statement_balance_amount\":\"90.58\","
                        + "\"pay_flex_indicator\":false,"
                        + "\"pay_flex_disclosure_indicator\":false,"
                        + "\"previous_statement_start_date\":\"2020-05-03\","
                        + "\"previous_statement_end_date\":\"2020-06-02\","
                        + "\"statement_start_date\":\"2020-06-03\","
                        + "\"statement_end_date\":\"2020-07-02\","
                        + "\"interest_saver_amount\":\"0.00\"}",
                BalanceDto.class);
    }

    private StatementPeriodsDto getStatements() {
        return SerializationUtils.deserializeFromString(
                "{\"statement_periods\":["
                        + "{\"start_date\":\"1992-04-03\","
                        + "\"end_date\":\"1992-05-02\","
                        + "\"index\":0},"
                        + "{\"start_date\":\"1992-03-03\","
                        + "\"end_date\":\"1992-04-02\","
                        + "\"index\":1}]}",
                StatementPeriodsDto.class);
    }

    private AccountsResponseDto getAccountsWhereCurrencyMatchLocalCurrency() {
        return SerializationUtils.deserializeFromString(
                "{"
                        + "\"identifiers\": {"
                        + "\"display_account_number\": \"XXXX-XXXXXX-61001\","
                        + "\"is_basic\": true,"
                        + "\"account_key\": \"8C7713E95B9BE005D70FA7834952205D\""
                        + "},"
                        + "\"holder\": {"
                        + "\"profile\": {"
                        + "\"first_name\": \"Holder Name\","
                        + "\"last_name\": \"Last Name\","
                        + "\"embossed_name\": \"Holder Name Last Name\""
                        + "},"
                        + "\"localization_preferences\": {"
                        + "\"localization_id\": \"sv-SE-revolve\","
                        + "\"home_country_locale\": \"sv-SE\","
                        + "\"currency_locale\": \"sv-SE\","
                        + "\"date_locale\": \"sv-SE\","
                        + "\"language_preference\": \"sv-SE\","
                        + "\"language_preference_code\": \"SV\","
                        + "\"geo_country_locale\": \"sv-SE\""
                        + "}"
                        + "},"
                        + "\"product\": {"
                        + "\"digital_info\": {"
                        + "\"product_desc\": \"SAS Amex Premium\","
                        + "\"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/se-cardasset-config/images/GSEGOLD0SA02.jpg\""
                        + "},"
                        + "\"account_types\": {"
                        + "\"plastic_types\": ["
                        + "\"AffinityCard\","
                        + "\"Gold\","
                        + "\"CoBrandCard\""
                        + "],"
                        + "\"line_of_business_type\": \"ConsumerCard\","
                        + "\"payment_type\": \"Revolve\""
                        + "},"
                        + "\"account_eligibilities\": ["
                        + "\"IntlAllEstmServiceEligible\","
                        + "\"MembershipRewardsEligible\","
                        + "\"ProdIDInfoAvailableEligible\""
                        + "],"
                        + "\"program_enrollments\": ["
                        + "\"PaperlessEnrolled\""
                        + "],"
                        + "\"account_features\": {"
                        + "},"
                        + "\"line_of_business\": {"
                        + "}"
                        + "},"
                        + "\"status\": {"
                        + "\"account_status\": ["
                        + "\"Active\""
                        + "]"
                        + "},"
                        + "\"supplementary_accounts\": ["
                        + "{"
                        + "\"identifiers\": {"
                        + "  \"display_account_number\": \"XXXX-XXXXXX-12345\","
                        + "  \"is_basic\": true,"
                        + "  \"account_key\": \"987653E95B9BE005D70FA7834952205D\""
                        + "  },"
                        + "  \"holder\": {"
                        + "  \"profile\": {"
                        + "  \"first_name\": \"Supplementary Holder Name\","
                        + "  \"last_name\": \"Supplementary Last Name\","
                        + "  \"embossed_name\": \"Supplementary Holder Name Last Name\""
                        + "  },"
                        + "  \"localization_preferences\": {"
                        + "  \"localization_id\": \"sv-SE-revolve\","
                        + "  \"home_country_locale\": \"sv-SE\","
                        + "  \"currency_locale\": \"sv-SE\","
                        + "  \"date_locale\": \"sv-SE\","
                        + "  \"language_preference\": \"sv-SE\","
                        + "  \"language_preference_code\": \"SV\","
                        + "  \"geo_country_locale\": \"sv-SE\""
                        + "  }"
                        + "  },"
                        + "  \"product\": {"
                        + "  \"digital_info\": {"
                        + "  \"product_desc\": \"American Express Platinum Card\","
                        + "  \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/se-cardasset-config/images/GSEGOLD0SA02.jpg\""
                        + "  },"
                        + "  \"account_types\": {"
                        + "  \"plastic_types\": ["
                        + "  \"Platinum\""
                        + "  ],"
                        + "  \"line_of_business_type\": \"CompanyCard\","
                        + "  \"payment_type\": \"ChargeCard\""
                        + "  },"
                        + "  \"account_eligibilities\": ["
                        + "  \"IntlAllEstmServiceEligible\","
                        + "  \"MembershipRewardsEligible\","
                        + "  \"ProdIDInfoAvailableEligible\","
                        + "  \"EStatementEligible\""
                        + "  ],"
                        + "  \"program_enrollments\": ["
                        + "  \"PaperlessEnrolled\""
                        + "  ],"
                        + "  \"account_features\": {"
                        + "  },"
                        + "  \"line_of_business\": {"
                        + "  }"
                        + "  },"
                        + "  \"status\": {"
                        + "  \"account_status\": ["
                        + "  \"Active\""
                        + "  ]"
                        + "  }"
                        + "},"
                        + "    {"
                        + "\"identifiers\": {"
                        + "  \"display_account_number\": \"XXXX-XXXXXX-22345\","
                        + "  \"is_basic\": true,"
                        + "  \"account_key\": \"187653E95B9BE005D70FA7834952205D\""
                        + "  },"
                        + "  \"holder\": {"
                        + "  \"profile\": {"
                        + "  \"first_name\": \"Supplementary Holder Name\","
                        + "  \"last_name\": \"Supplementary Last Name\","
                        + "  \"embossed_name\": \"Supplementary Holder Name Last Name\""
                        + "  },"
                        + "  \"localization_preferences\": {"
                        + "  \"localization_id\": \"sv-SE-revolve\","
                        + "  \"home_country_locale\": \"sv-SE\","
                        + "  \"currency_locale\": \"sv-SE\","
                        + "  \"date_locale\": \"sv-SE\","
                        + "  \"language_preference\": \"sv-SE\","
                        + "  \"language_preference_code\": \"SV\","
                        + "  \"geo_country_locale\": \"sv-SE\""
                        + "  }"
                        + "  },"
                        + "  \"product\": {"
                        + "  \"digital_info\": {"
                        + "  \"product_desc\": \"American Express Platinum Card\","
                        + "  \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/se-cardasset-config/images/GSEGOLD0SA02.jpg\""
                        + "  },"
                        + "  \"account_types\": {"
                        + "  \"plastic_types\": ["
                        + "  \"Platinum\""
                        + "  ],"
                        + "  \"line_of_business_type\": \"CorporateCard\","
                        + "  \"payment_type\": \"ChargeCard\""
                        + "  },"
                        + "  \"account_eligibilities\": ["
                        + "  \"IntlAllEstmServiceEligible\","
                        + "  \"MembershipRewardsEligible\","
                        + "  \"ProdIDInfoAvailableEligible\","
                        + "  \"EStatementEligible\""
                        + "  ],"
                        + "  \"program_enrollments\": ["
                        + "  \"PaperlessEnrolled\""
                        + "  ],"
                        + "  \"account_features\": {"
                        + "  },"
                        + "  \"line_of_business\": {"
                        + "  }"
                        + "  },"
                        + "  \"status\": {"
                        + "  \"account_status\": ["
                        + "  \"Active\""
                        + "  ]"
                        + "  }"
                        + "},"
                        + "    {"
                        + "\"identifiers\": {"
                        + "  \"display_account_number\": \"XXXX-XXXXXX-32345\","
                        + "  \"is_basic\": true,"
                        + "  \"account_key\": \"287653E95B9BE005D70FA7834952205D\""
                        + "  },"
                        + "  \"holder\": {"
                        + "  \"profile\": {"
                        + "  \"first_name\": \"Supplementary Holder Name\","
                        + "  \"last_name\": \"Supplementary Last Name\","
                        + "  \"embossed_name\": \"Supplementary Holder Name Last Name\""
                        + "  },"
                        + "  \"localization_preferences\": {"
                        + "  \"localization_id\": \"sv-SE-revolve\","
                        + "  \"home_country_locale\": \"sv-SE\","
                        + "  \"currency_locale\": \"sv-SE\","
                        + "  \"date_locale\": \"sv-SE\","
                        + "  \"language_preference\": \"sv-SE\","
                        + "  \"language_preference_code\": \"SV\","
                        + "  \"geo_country_locale\": \"sv-SE\""
                        + "  }"
                        + "  },"
                        + "  \"product\": {"
                        + "  \"digital_info\": {"
                        + "  \"product_desc\": \"American Express Platinum Card\","
                        + "  \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/se-cardasset-config/images/GSEGOLD0SA02.jpg\""
                        + "  },"
                        + "  \"account_types\": {"
                        + "  \"plastic_types\": ["
                        + "  \"Platinum\""
                        + "  ],"
                        + "  \"line_of_business_type\": \"VeryRandomValue\","
                        + "  \"payment_type\": \"ChargeCard\""
                        + "  },"
                        + "  \"account_eligibilities\": ["
                        + "  \"IntlAllEstmServiceEligible\","
                        + "  \"MembershipRewardsEligible\","
                        + "  \"ProdIDInfoAvailableEligible\","
                        + "  \"EStatementEligible\""
                        + "  ],"
                        + "  \"program_enrollments\": ["
                        + "  \"PaperlessEnrolled\""
                        + "  ],"
                        + "  \"account_features\": {"
                        + "  },"
                        + "  \"line_of_business\": {"
                        + "  }"
                        + "  },"
                        + "  \"status\": {"
                        + "  \"account_status\": ["
                        + "  \"Active\""
                        + "  ]"
                        + "  }"
                        + "},"
                        + "    {"
                        + "\"identifiers\": {"
                        + "  \"display_account_number\": \"XXXX-XXXXXX-42345\","
                        + "  \"is_basic\": true,"
                        + "  \"account_key\": \"387653E95B9BE005D70FA7834952205D\""
                        + "  },"
                        + "  \"holder\": {"
                        + "  \"profile\": {"
                        + "  \"first_name\": \"Supplementary Holder Name\","
                        + "  \"last_name\": \"Supplementary Last Name\","
                        + "  \"embossed_name\": \"Supplementary Holder Name Last Name\""
                        + "  },"
                        + "  \"localization_preferences\": {"
                        + "  \"localization_id\": \"sv-SE-revolve\","
                        + "  \"home_country_locale\": \"sv-SE\","
                        + "  \"currency_locale\": \"sv-SE\","
                        + "  \"date_locale\": \"sv-SE\","
                        + "  \"language_preference\": \"sv-SE\","
                        + "  \"language_preference_code\": \"SV\","
                        + "  \"geo_country_locale\": \"sv-SE\""
                        + "  }"
                        + "  },"
                        + "  \"product\": {"
                        + "  \"digital_info\": {"
                        + "  \"product_desc\": \"American Express Platinum Card\","
                        + "  \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/se-cardasset-config/images/GSEGOLD0SA02.jpg\""
                        + "  },"
                        + "  \"account_types\": {"
                        + "  \"plastic_types\": ["
                        + "  \"Platinum\""
                        + "  ],"
                        + "  \"payment_type\": \"ChargeCard\""
                        + "  },"
                        + "  \"account_eligibilities\": ["
                        + "  \"IntlAllEstmServiceEligible\","
                        + "  \"MembershipRewardsEligible\","
                        + "  \"ProdIDInfoAvailableEligible\","
                        + "  \"EStatementEligible\""
                        + "  ],"
                        + "  \"program_enrollments\": ["
                        + "  \"PaperlessEnrolled\""
                        + "  ],"
                        + "  \"account_features\": {"
                        + "  },"
                        + "  \"line_of_business\": {"
                        + "  }"
                        + "  },"
                        + "  \"status\": {"
                        + "  \"account_status\": ["
                        + "  \"Active\""
                        + "  ]"
                        + "  }"
                        + "}"
                        + "]"
                        + "}",
                AccountsResponseDto.class);
    }

    private AccountsResponseDto getAccountsWhereCurrencyDoesNotMatchLocaleCurrency() {
        return SerializationUtils.deserializeFromString(
                "{"
                        + "  \"identifiers\": {"
                        + "    \"display_account_number\": \"XXXX-XXXXXX-45006\","
                        + "    \"is_basic\": true,"
                        + "    \"account_key\": \"1A1FC88138184732E8927E3AD3624173\""
                        + "  },"
                        + "  \"holder\": {"
                        + "    \"profile\": {"
                        + "      \"title_name\": \"MR\","
                        + "      \"first_name\": \"ESBJORN\","
                        + "      \"last_name\": \"FAKENAME\","
                        + "      \"embossed_name\": \"ESBJORN FAKENAME\""
                        + "    },"
                        + "    \"localization_preferences\": {"
                        + "      \"localization_id\": \"en-EU-estmt\","
                        + "      \"home_country_locale\": \"en-XB\","
                        + "      \"currency_locale\": \"en-EU\","
                        + "      \"date_locale\": \"en-EU\","
                        + "      \"language_preference\": \"en-GB\","
                        + "      \"language_preference_code\": \"EN\","
                        + "      \"geo_country_locale\": \"en-EU\""
                        + "    }"
                        + "  },"
                        + "  \"product\": {"
                        + "    \"digital_info\": {"
                        + "      \"product_desc\": \"The Platinum Card®\","
                        + "      \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/eu-cardasset-config/images/CEUPLAT00001.gif\""
                        + "    },"
                        + "    \"account_types\": {"
                        + "      \"plastic_types\": ["
                        + "        \"Platinum\""
                        + "      ],"
                        + "      \"line_of_business_type\": \"ConsumerCard\","
                        + "      \"payment_type\": \"ChargeCard\""
                        + "    },"
                        + "    \"account_eligibilities\": ["
                        + "      \"IntlAllEstmServiceEligible\","
                        + "      \"MembershipRewardsEligible\","
                        + "      \"ProdIDInfoAvailableEligible\","
                        + "      \"EStatementEligible\""
                        + "    ],"
                        + "    \"program_enrollments\": ["
                        + "      \"PaperlessEnrolled\""
                        + "    ],"
                        + "    \"account_features\": {},"
                        + "    \"line_of_business\": {}"
                        + "  },"
                        + "  \"status\": {"
                        + "    \"account_status\": ["
                        + "      \"Active\""
                        + "    ]"
                        + "  },"
                        + "  \"supplementary_accounts\": ["
                        + "    {"
                        + "      \"identifiers\": {"
                        + "        \"display_account_number\": \"XXXX-XXXXXX-42011\","
                        + "        \"is_basic\": false,"
                        + "        \"account_key\": \"99FE0BD7CBA2B415004CD3B4ABF97562\""
                        + "      },"
                        + "      \"holder\": {"
                        + "        \"profile\": {"
                        + "          \"title_name\": \"MR\","
                        + "          \"first_name\": \"ESBJORN\","
                        + "          \"last_name\": \"FAKENAME\","
                        + "          \"embossed_name\": \"ESBJORN FAKENAME A.C\""
                        + "        },"
                        + "        \"localization_preferences\": {"
                        + "          \"localization_id\": \"en-EU-estmt\","
                        + "          \"home_country_locale\": \"en-XB\","
                        + "          \"currency_locale\": \"en-EU\","
                        + "          \"date_locale\": \"en-EU\","
                        + "          \"language_preference\": \"en-GB\","
                        + "          \"language_preference_code\": \"EN\","
                        + "          \"geo_country_locale\": \"en-EU\""
                        + "        }"
                        + "      },"
                        + "      \"product\": {"
                        + "        \"digital_info\": {"
                        + "          \"product_desc\": \"The Platinum Additional Card®\","
                        + "          \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/eu-cardasset-config/images/CEUPLAT00001.gif\""
                        + "        },"
                        + "        \"account_types\": {"
                        + "          \"plastic_types\": ["
                        + "            \"Platinum\""
                        + "          ],"
                        + "          \"line_of_business_type\": \"ConsumerCard\","
                        + "          \"payment_type\": \"ChargeCard\""
                        + "        },"
                        + "        \"account_eligibilities\": ["
                        + "          \"IntlAllEstmServiceEligible\","
                        + "          \"MembershipRewardsEligible\","
                        + "          \"ProdIDInfoAvailableEligible\","
                        + "          \"EStatementEligible\""
                        + "        ],"
                        + "        \"account_features\": {},"
                        + "        \"line_of_business\": {}"
                        + "      },"
                        + "      \"status\": {"
                        + "        \"account_status\": ["
                        + "          \"Active\""
                        + "        ]"
                        + "      }"
                        + "    },"
                        + "    {"
                        + "      \"identifiers\": {"
                        + "        \"display_account_number\": \"XXXX-XXXXXX-42029\","
                        + "        \"is_basic\": false,"
                        + "        \"account_key\": \"AED4E44473C4E0629770DA0BE196F09C\""
                        + "      },"
                        + "      \"holder\": {"
                        + "        \"profile\": {"
                        + "          \"title_name\": \"MR\","
                        + "          \"first_name\": \"THORBJORN\","
                        + "          \"last_name\": \"FAKENAME\","
                        + "          \"embossed_name\": \"THORBJORN FAKENAME\""
                        + "        },"
                        + "        \"localization_preferences\": {"
                        + "          \"localization_id\": \"en-EU-estmt\","
                        + "          \"home_country_locale\": \"en-XB\","
                        + "          \"currency_locale\": \"en-EU\","
                        + "          \"date_locale\": \"en-EU\","
                        + "          \"language_preference\": \"en-GB\","
                        + "          \"language_preference_code\": \"EN\","
                        + "          \"geo_country_locale\": \"en-EU\""
                        + "        }"
                        + "      },"
                        + "      \"product\": {"
                        + "        \"digital_info\": {"
                        + "          \"product_desc\": \"The Platinum Supplementary Card®\","
                        + "          \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/eu-cardasset-config/images/CEUPLAT00001.gif\""
                        + "        },"
                        + "        \"account_types\": {"
                        + "          \"plastic_types\": ["
                        + "            \"Platinum\""
                        + "          ],"
                        + "          \"line_of_business_type\": \"ConsumerCard\","
                        + "          \"payment_type\": \"ChargeCard\""
                        + "        },"
                        + "        \"account_eligibilities\": ["
                        + "          \"IntlAllEstmServiceEligible\","
                        + "          \"MembershipRewardsEligible\","
                        + "          \"ProdIDInfoAvailableEligible\","
                        + "          \"EStatementEligible\""
                        + "        ],"
                        + "        \"account_features\": {},"
                        + "        \"line_of_business\": {}"
                        + "      },"
                        + "      \"status\": {"
                        + "        \"account_status\": ["
                        + "          \"Active\""
                        + "        ]"
                        + "      }"
                        + "    },"
                        + "    {"
                        + "      \"identifiers\": {"
                        + "        \"display_account_number\": \"XXXX-XXXXXX-42045\","
                        + "        \"is_basic\": false,"
                        + "        \"account_key\": \"0A130FC958B64314EE2CFEF2F5FD8537\""
                        + "      },"
                        + "      \"holder\": {"
                        + "        \"profile\": {"
                        + "          \"title_name\": \"MR\","
                        + "          \"first_name\": \"STYRBJORN\","
                        + "          \"last_name\": \"FAKENAME\","
                        + "          \"embossed_name\": \"MR S FAKENAME\""
                        + "        },"
                        + "        \"localization_preferences\": {"
                        + "          \"localization_id\": \"en-EU-estmt\","
                        + "          \"home_country_locale\": \"en-XB\","
                        + "          \"currency_locale\": \"en-EU\","
                        + "          \"date_locale\": \"en-EU\","
                        + "          \"language_preference\": \"en-GB\","
                        + "          \"language_preference_code\": \"EN\","
                        + "          \"geo_country_locale\": \"en-EU\""
                        + "        }"
                        + "      },"
                        + "      \"product\": {"
                        + "        \"digital_info\": {"
                        + "          \"product_desc\": \"The Platinum Supplementary Card®\","
                        + "          \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/eu-cardasset-config/images/CEUPLAT00001.gif\""
                        + "        },"
                        + "        \"account_types\": {"
                        + "          \"plastic_types\": ["
                        + "            \"Platinum\""
                        + "          ],"
                        + "          \"line_of_business_type\": \"ConsumerCard\","
                        + "          \"payment_type\": \"ChargeCard\""
                        + "        },"
                        + "        \"account_eligibilities\": ["
                        + "          \"IntlAllEstmServiceEligible\","
                        + "          \"MembershipRewardsEligible\","
                        + "          \"ProdIDInfoAvailableEligible\","
                        + "          \"EStatementEligible\""
                        + "        ],"
                        + "        \"account_features\": {},"
                        + "        \"line_of_business\": {}"
                        + "      },"
                        + "      \"status\": {"
                        + "        \"account_status\": ["
                        + "          \"Active\""
                        + "        ]"
                        + "      }"
                        + "    },"
                        + "    {"
                        + "      \"identifiers\": {"
                        + "        \"display_account_number\": \"XXXX-XXXXXX-42037\","
                        + "        \"is_basic\": false,"
                        + "        \"account_key\": \"63DF97DF376BF8A504192655C8FFA180\""
                        + "      },"
                        + "      \"holder\": {"
                        + "        \"profile\": {"
                        + "          \"title_name\": \"MS\","
                        + "          \"first_name\": \"ISBJORN\","
                        + "          \"last_name\": \"FAKENAME\","
                        + "          \"embossed_name\": \"MS ISBJORN FAKENAME\""
                        + "        },"
                        + "        \"localization_preferences\": {"
                        + "          \"localization_id\": \"en-EU-estmt\","
                        + "          \"home_country_locale\": \"en-XB\","
                        + "          \"currency_locale\": \"en-EU\","
                        + "          \"date_locale\": \"en-EU\","
                        + "          \"language_preference\": \"en-GB\","
                        + "          \"language_preference_code\": \"EN\","
                        + "          \"geo_country_locale\": \"en-EU\""
                        + "        }"
                        + "      },"
                        + "      \"product\": {"
                        + "        \"digital_info\": {"
                        + "          \"product_desc\": \"The Platinum Gold Supplementary Card®\","
                        + "          \"digital_asset_url\": \"https://secure.cmax.americanexpress.com/Internet/CardArt/EMEA/eu-cardasset-config/images/CEUGOLD00001.gif\""
                        + "        },"
                        + "        \"account_types\": {"
                        + "          \"plastic_types\": ["
                        + "            \"Gold\""
                        + "          ],"
                        + "          \"line_of_business_type\": \"ConsumerCard\","
                        + "          \"payment_type\": \"ChargeCard\""
                        + "        },"
                        + "        \"account_eligibilities\": ["
                        + "          \"IntlAllEstmServiceEligible\","
                        + "          \"MembershipRewardsEligible\","
                        + "          \"ProdIDInfoAvailableEligible\","
                        + "          \"EStatementEligible\""
                        + "        ],"
                        + "        \"account_features\": {},"
                        + "        \"line_of_business\": {}"
                        + "      },"
                        + "      \"status\": {"
                        + "        \"account_status\": ["
                        + "          \"Canceled\""
                        + "        ]"
                        + "      }"
                        + "    }"
                        + "  ]"
                        + "}",
                AccountsResponseDto.class);
    }
}
