java_library(
    name = "dropwizard",
    srcs = ["@tink_backend//src/libraries/endpoint_configuration/src/main/java/se/tink/libraries/endpoints/dropwizard:dropwizard_srcjar"],
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:io_dropwizard_dropwizard_core",
    ],
)
