kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-payments-fr
  namespace: agents
spec:
  rules:
    #-------------------------------------------------------------------------------------------------------------------
    # All errors alerts
    #-------------------------------------------------------------------------------------------------------------------
    - alert: TransferUnknownErrorRate100%FR
      expr: |
        # Failed transfers outcome 100%
        (count(sum_over_time(tink_agent_transfer_total{ market="FR", provider_type!="test", outcome=~"failed|rejected"}[1h])) by (className,provider)
            / count(sum_over_time(tink_agent_transfer_total{ market="FR", provider_type!="test"}[1h])) by (className,provider) > 0.99)
        # At least this many attempts
              and count(sum_over_time(tink_agent_transfer_total{ market="FR", provider_type!="test"}[1h])) by (className,provider) > 5
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: connectivity-penguins
      annotations:
        description: {{ .Values.kibanaClassPaymentLink }}
          {{ .Values.grafanaLink }}
        summary: Transfer failure rate is 100% for <{ $labels.className }> on <{ $labels.market }> market the last 1h. More than 5 attempts.
        tags: <{ $labels.className }> , *#payments*

    - alert: TransferBankSideErrorRate100%FR
      expr: |
        # Failed transfers outcome 100%
        (count(sum_over_time(tink_agent_transfer_total{ market="FR", provider_type!="test", outcome=~"unavailable"}[4h])) by (className,provider)
            / count(sum_over_time(tink_agent_transfer_total{ market="FR", provider_type!="test"}[4h])) by (className,provider) > 0.99)
        # At least this many attempts
              and count(sum_over_time(tink_agent_transfer_total{ market="FR", provider_type!="test"}[4h])) by (className,provider) > 5
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: connectivity-penguins
      annotations:
        description: {{ .Values.kibanaClassPaymentLink }}
          {{ .Values.grafanaLink }}
        summary: Transfer failure rate due to bank side error is 100% for <{ $labels.className }> on <{ $labels.market }> market the last 4h. More than 5 attempts.
        tags: <{ $labels.className }> , *#payments*

    # Payment ping alerts
    - alert: TransferFailedRateOver50%FR
      expr: |
        # Failed transfer outcomes above 50%
        (count(sum_over_time(tink_agent_transfer_total{market="FR", provider_type!="test", outcome=~"failed|rejected"}[1h])) by (className,provider)
              / count(sum_over_time(tink_agent_transfer_total{market="FR", provider_type!="test"}[1h])) by (className,provider) > 0.5)
        # At least this many attempts
                and count(sum_over_time(tink_agent_transfer_total{market="FR", provider_type!="test"}[1h])) by (className,provider) > 5
      for: 5m
      labels:
        severity: ping
        priority: P3
        who: connectivity-penguins
      annotations:
        description: {{ .Values.kibanaClassPaymentLink }}
          {{ .Values.grafanaLink }}
        summary: Transfer fail rate is above 50% actual % is <{ $value }> for <{ $labels.className }> on <{ $labels.market }> market the last 1h. More than 5 attempts.
        tags: <{ $labels.className }> , *#payments*
        