{{ $bigdb := .Values.bigdb | default dict }}
{{ $maindb := .Values.maindb | default dict }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-configuration
  namespace: insights
data:
  insights-server.yml: |
    server:
      shutdownGracePeriod: 10s
      applicationConnectors:
        - type: http
          port: 80
        - type: https
          port: 443
          {{- if eq "local" .Values.Cluster }}
          keyStorePath: data/security/developer.keystore
          certAlias: developer.internal.tink.se
          {{- else }}
          keyStorePath: data/security/production.keystore
          certAlias: container.internal.tink.se
          {{- end }}
          keyStorePassword: KEYSTORE_PASSWORD # replaced from secrets
          trustStorePath: data/security/TinkCA.truststore
          trustStorePassword: changeme
          # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
          validateCerts: false
      adminConnectors:
        - type: http
          port: 8099
    endpoints:
      api:
        url: http://www.staging.tink.se/api/v1
        pinnedCertificates:
          - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
      main:
        url: http://localhost:9090/
        pinnedCertificates:
          - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
      system:
        url: http://localhost:9091/
        accessToken: devtoken
        pinnedCertificates:
          - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
      aggregation:
        url: http://localhost:9095/
        accessToken: devtoken
        pinnedCertificates:
          - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
      encryption:
        url: http://localhost:9094/
        accessToken: devtoken
        pinnedCertificates:
          - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
      connector:
        url: http://localhost:9095/
        pinnedCertificates:
          - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"

    cluster: TINK
    developmentMode: false

    flags:
      register:
        SE:
          FRAUD_PROTECTION: 1
          TINK_EMPLOYEE: 1
          APPLICATIONS: 1
      device:
        ONBOARDING_V2: 1
      campaigns:
        MORTGAGE:
          - Mortgage
          - Bolån
      dynamicInheritance:
        APPLICATIONS:
            - TRANSFERS
            - BILLPAY
            - SHOW_BANK_LOGO
            - APPLICATIONS_INTERCOM_CHAT
            - RESIDENCE_TAB
            - IOS_MORTGAGE_TAKE_OVER
        IOS_BETA:
            - RESIDENCE_VALUATION
        TINK_EMPLOYEE:
            - RESIDENCE_VALUATION

    distributedDatabase:
      # No username needed by default (local development)
      {{- if $bigdb.username }}
      username: {{ $bigdb.username }}
      password: CASSANDRA_PASSWORD # Is added via Kubernetes Secrets
      {{- end }}
      seeds:
        {{- if gt (len ($bigdb.hosts | default list)) 0 }}
        {{- range $bigdb.hosts }}
        - "{{ . }}"
        {{- end }}
        {{- else }}
        - "bigdb.insights.svc.cluster.local"
        {{- end }}
      enabled: true
      createKeyspaceOnStart: false

    database:
      driverClass: com.mysql.jdbc.Driver
      username: {{ default "tink-insights" $maindb.username }}
      password: MYSQL_PASSWORD # Is added via Kubernetes Secrets
      url: jdbc:mysql://{{ default "maindb.insights.svc.cluster.local" $maindb.host }}/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
      showSql: false
      persistenceUnitName: tink-main-api
      generateDdl: true

    scheduler:
      enabled: false

    coordination:
      hosts: {{ default "coordination.insights.svc.cluster.local:2181" .Values.coordinationHosts }}

    cache:
      hosts: {{ default "cache.insights.svc.cluster.local:11211" .Values.cacheHosts }}
      enabled: true

    search:
      clusterName: elasticsearch
      hosts: {{ default "elasticsearch.insights.svc.cluster.local:9300" .Values.searchHosts }}
      enabled: true

    analytics:
      intercom:
        enabled: false

    integrations:
      booli:
        callerId: tink_app
        privateKey: PRIVATE_KEY_PLACEHOLDER

    transfers:
      enabled: true
      duplicateTime: 1
      aggregationTime: 5
      bankTransferThreshold: 1000
      paymentThreshold: 20000

    logging:
      level: INFO
      loggers:
        se.tink: INFO
        se.tink.org.eclipse: INFO
      appenders:
        - type: console
          threshold: ALL
          timeZone: Europe/Stockholm
          logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %replace(%m){"\n", "\\n"}\\n%replace(%ex){"[\r\n]+", "\\n"}%nopex%n'

    authentication:
      methods:
        - BASIC
        - SESSION
      marketRegisterMethods:
        SE:
          - BANKID
      marketLoginMethods:
        SE:
          - BANKID
          - EMAIL_AND_PASSWORD

    prometheus:
      port: 9130

{{ if .Values.createDevelopmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: insights-secrets
  namespace: insights
type: Opaque
data:
  # Both are set to "tink" in the development setup
  # This Secret object has to be created manually for Kubernetes in production
  maindb-password: dGluaw==
  cassandra-password: dGluaw==
  # Is set to changeme for the development keystore
  keystore-password: Y2hhbmdlbWU=
{{ end }}
