load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "processes",
    intdeps = [
        "//src/agent_sdk/runtime/src/payments/single/processes/generic",
    ],
    visibility = [
        "//src/agent_sdk/runtime:__subpackages__",
    ],
    exports = [
        "//src/agent_sdk/runtime/src/payments/single/processes/generic",
    ],
)
