load("@rules_codeowners//tools:codeowners.bzl", "codeowners")

codeowners(
    name = "owners",
    teams = [
        "@tink-ab/aggregation-thundercats-maintainer",
    ],
    visibility = ["//:__pkg__"],
)
