package se.tink.backend.aggregation.agents.nxgen.be.banks.fortis;

import se.tink.backend.aggregation.agents.nxgen.be.banks.fortis.fetchers.rpc.TransactionsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class FortisTestData {

    static final String BULK_ERROR_MESSAGE =
            "{\n"
                    + "    \"value\": null,\n"
                    + "    \"businessMessageBulk\": {\n"
                    + "        \"messages\": [{\n"
                    + "            \"ind\": \"E\",\n"
                    + "            \"code\": \"PEW0026\",\n"
                    + "            \"text\": \"\"\n"
                    + "        }],\n"
                    + "        \"pewCode\": \"PEW0501\",\n"
                    + "        \"globalIndicator\": \"E\",\n"
                    + "        \"text\": \"\"\n"
                    + "    }\n"
                    + "}";

    static final String TRANSACTIONS_EMPTY_RESPONSE =
            "{\"value\":{\"numberPending\":0,\"completeListFlag\":true,\"movements\":[]},\"businessMessageBulk\":{\"messages\":[],\"pewCode\":null,\"globalIndicator\":null,\"text\":null}}";

    static final TransactionsResponse TRANSACTIONS_RESPONSE =
            SerializationUtils.deserializeFromString(
                    "{\n"
                            + "\t\"value\": {\n"
                            + "\t\t\"numberPending\": 0,\n"
                            + "\t\t\"completeListFlag\": false,\n"
                            + "\t\t\"movements\": [{\n"
                            + "\t\t\t\"movementText\": \"movementText                \",\n"
                            + "\t\t\t\"sequenceNb\": \"0029\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"otherParty             \",\n"
                            + "\t\t\t\"operationId\": \"BEXXXXXXXXX#EUR#74#0029##1\",\n"
                            + "\t\t\t\"executionDate\": \"20181108\",\n"
                            + "\t\t\t\"amount\": \"-3,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"COMFORT PACK\\\\r\\\\n\",\n"
                            + "\t\t\t\"description2\": \"REFERENCE BANQUE : XXXXXXXXXXX\\\\r\\\\nDATE VALEUR : 01/11/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20181101\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"movementText \",\n"
                            + "\t\t\t\"sequenceNb\": \"0028\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"BEXXXXXXXXXXX\",\n"
                            + "\t\t\t\"operationId\": \"BEXXXXXXXXXXX#EUR#74#0028##2\",\n"
                            + "\t\t\t\"executionDate\": \"20181031\",\n"
                            + "\t\t\t\"amount\": \"-1,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"description 1\",\n"
                            + "\t\t\t\"description2\": \"description2\",\n"
                            + "\t\t\t\"valueDate\": \"20181101\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"movementText                      \",\n"
                            + "\t\t\t\"sequenceNb\": \"0027\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"BEXXXXXXXXXXXX\",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0027##3\",\n"
                            + "\t\t\t\"executionDate\": \"20181030\",\n"
                            + "\t\t\t\"amount\": \"-1,20\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"FIRSTNAME LASTNAME\\\\r\\\\nBEXXXXXXXXXXXX\",\n"
                            + "\t\t\t\"description2\": \"BIC GEBABEBB    VIA WEB BANKING\\\\r\\\\nPAS DE COMMUNICATION\\\\r\\\\nREFERENCE BANQUE : 1810301637542164\\\\r\\\\nDATE VALEUR : 31/10/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20181031\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"movementText                      \",\n"
                            + "\t\t\t\"sequenceNb\": \"0026\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"BEXXXXXXXXXXXX\",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0026##4\",\n"
                            + "\t\t\t\"executionDate\": \"20181030\",\n"
                            + "\t\t\t\"amount\": \"-2,30\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"FIRSTNAME LASTNAME\\\\r\\\\nBEXXXXXXXXXXXX\",\n"
                            + "\t\t\t\"description2\": \"BIC GEBABEBB    VIA WEB BANKING\\\\r\\\\nPAS DE COMMUNICATION\\\\r\\\\nREFERENCE BANQUE : 1810301638206951\\\\r\\\\nDATE VALEUR : 31/10/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20181031\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"VIREMENT EUROPEEN DE                     \",\n"
                            + "\t\t\t\"sequenceNb\": \"0025\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"BEXXXXXXXXXXXX\",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0025##5\",\n"
                            + "\t\t\t\"executionDate\": \"20181030\",\n"
                            + "\t\t\t\"amount\": \"0,50\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"FIRSTNAME LASTNAME\\\\r\\\\nRUE DU TABELLION 108 2-3-E\",\n"
                            + "\t\t\t\"description2\": \"1050     IXELLES\\\\r\\\\nBEZZZZZZZZZZZZZZ BIC GEBABEBB\\\\r\\\\nPAS DE COMMUNICATION\\\\r\\\\nREFERENCE BANQUE : 1810301639490884\\\\r\\\\nDATE VALEUR : 30/10/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20181030\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"VIREMENT EUROPEEN DE                     \",\n"
                            + "\t\t\t\"sequenceNb\": \"0024\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"BEXXXXXXXXXXXX\",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0024##6\",\n"
                            + "\t\t\t\"executionDate\": \"20181030\",\n"
                            + "\t\t\t\"amount\": \"1,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"FIRSTNAME LASTNAME\\\\r\\\\nRUE DU TABELLION 108 2-3-E\",\n"
                            + "\t\t\t\"description2\": \"1050     IXELLES\\\\r\\\\nBEZZZZZZZZZZZZZZ BIC GEBABEBB\\\\r\\\\nPAS DE COMMUNICATION\\\\r\\\\nREFERENCE BANQUE : 1810301639130207\\\\r\\\\nDATE VALEUR : 30/10/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20181030\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"VIREMENT EUROPEEN DE                     \",\n"
                            + "\t\t\t\"sequenceNb\": \"0023\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"BEXXXXXXXXXXXX\",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0023##7\",\n"
                            + "\t\t\t\"executionDate\": \"20181030\",\n"
                            + "\t\t\t\"amount\": \"2,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"FIRSTNAME LASTNAME\\\\r\\\\nRUE DU TABELLION 108 2-3-E\",\n"
                            + "\t\t\t\"description2\": \"1050     IXELLES\\\\r\\\\nBEZZZZZZZZZZZZZZ BIC GEBABEBB\\\\r\\\\nPAS DE COMMUNICATION\\\\r\\\\nREFERENCE BANQUE : 1810301639286956\\\\r\\\\nDATE VALEUR : 30/10/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20181030\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"REDEVANCE MENSUELLE                      \",\n"
                            + "\t\t\t\"sequenceNb\": \"0022\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"REDEVANCE MENSUELLE             \",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0022##8\",\n"
                            + "\t\t\t\"executionDate\": \"20181006\",\n"
                            + "\t\t\t\"amount\": \"-3,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"COMFORT PACK\\\\r\\\\nEXECUTE LE 05-10\",\n"
                            + "\t\t\t\"description2\": \"REFERENCE BANQUE : 1810052315088125\\\\r\\\\nDATE VALEUR : 01/10/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20181001\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"REDEVANCE MENSUELLE                      \",\n"
                            + "\t\t\t\"sequenceNb\": \"0021\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"REDEVANCE MENSUELLE             \",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0021##9\",\n"
                            + "\t\t\t\"executionDate\": \"20180907\",\n"
                            + "\t\t\t\"amount\": \"-3,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"COMFORT PACK\\\\r\\\\nEXECUTE LE 06-09\",\n"
                            + "\t\t\t\"description2\": \"DATE VALEUR : 01/09/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20180901\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"REDEVANCE MENSUELLE                      \",\n"
                            + "\t\t\t\"sequenceNb\": \"0020\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"REDEVANCE MENSUELLE             \",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0020##10\",\n"
                            + "\t\t\t\"executionDate\": \"20180807\",\n"
                            + "\t\t\t\"amount\": \"-3,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"COMFORT PACK\\\\r\\\\nEXECUTE LE 06-08\",\n"
                            + "\t\t\t\"description2\": \"DATE VALEUR : 01/08/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20180801\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"VIREMENT ETRANGER                        \",\n"
                            + "\t\t\t\"sequenceNb\": \"0019\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"VIREMENT ETRANGER               \",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0019#00000019F20180724#11\",\n"
                            + "\t\t\t\"executionDate\": \"20180724\",\n"
                            + "\t\t\t\"amount\": \"35,04\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"DATE VALEUR : 30/07/2018\\\\r\\\\n\",\n"
                            + "\t\t\t\"description2\": \"\",\n"
                            + "\t\t\t\"valueDate\": \"20180730\",\n"
                            + "\t\t\t\"detailPresent\": true\n"
                            + "\t\t}, {\n"
                            + "\t\t\t\"movementText\": \"REDEVANCE MENSUELLE                      \",\n"
                            + "\t\t\t\"sequenceNb\": \"0018\",\n"
                            + "\t\t\t\"pending\": false,\n"
                            + "\t\t\t\"period\": \"PREVIOUS\",\n"
                            + "\t\t\t\"annexes\": [],\n"
                            + "\t\t\t\"otherParty\": \"REDEVANCE MENSUELLE             \",\n"
                            + "\t\t\t\"operationId\": \"BEYYYYYYYYYYYYY#EUR#74#0018##12\",\n"
                            + "\t\t\t\"executionDate\": \"20180706\",\n"
                            + "\t\t\t\"amount\": \"-3,00\",\n"
                            + "\t\t\t\"currency\": \"EUR\",\n"
                            + "\t\t\t\"description1\": \"COMFORT PACK\\\\r\\\\nEXECUTE LE 05-07\",\n"
                            + "\t\t\t\"description2\": \"DATE VALEUR : 01/07/2018\",\n"
                            + "\t\t\t\"valueDate\": \"20180701\",\n"
                            + "\t\t\t\"detailPresent\": false\n"
                            + "\t\t}]\n"
                            + "\t},\n"
                            + "\t\"businessMessageBulk\": {\n"
                            + "\t\t\"messages\": [],\n"
                            + "\t\t\"pewCode\": null,\n"
                            + "\t\t\"globalIndicator\": null,\n"
                            + "\t\t\"text\": null\n"
                            + "\t}\n"
                            + "}",
                    TransactionsResponse.class);

    static final String UPCOMING_TRANSACTIONS =
            "{\"value\":{\"numberUpcoming\":1,\"completeListFlag\":true,\"transfer\":[{\"transferId\":\"172875266\",\"transferType\":\"Standing Order\",\"beneficiary\":{\"name\":\"Firstname Lastname\",\"accountNumber\":\"BEXXXXXXXXXX\"},\"amount\":{\"amount\":\"50,00\",\"currency\":\"EUR\"},\"period\":\"LATER\",\"executionDate\":\"20190101\",\"originatingAccount\":\"BEYYYYYYYYYYY\",\"communication\":{\"type\":\"FREE_TEXT\",\"message\":\"KeyPlan\"},\"transferLastUpdate\":null,\"amountType\":\"F\"}]},\"businessMessageBulk\":{\"messages\":[],\"pewCode\":null,\"globalIndicator\":null,\"text\":null}}";

    static final String UPCOMING_TRANSACTIONS_EMPTY =
            "{\"value\":{\"numberUpcoming\":0,\"completeListFlag\":false,\"transfer\":[]},\"businessMessageBulk\":{\"messages\":[],\"pewCode\":null,\"globalIndicator\":null,\"text\":null}}";
}
