java_library(
    name = "erstebank",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api",
        "//src/integration/lib",
        "//src/libraries/account_identifier",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "@com_fasterxml_jackson_core_jackson_annotations//jar",
        "@com_google_guava_guava//jar",
        "@com_sun_jersey_jersey_core//jar",
        "@org_slf4j_slf4j_api//jar",
    ],
)
