java_library(
    name = "queue_lib",
    srcs = glob(["src/main/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    deps = [
        "@aggregation//:com_google_guava_guava",
    ],
)
