java_library(
    name = "agents",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib:annotations",
        "@aggregation//:com_fasterxml_jackson_core_jackson_annotations",
        "@aggregation//:com_kjetland_mbknor_jackson_jsonschema_2_13",
    ],
)
