java_library(
    name = "tpp-secrets-service-client",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib:annotations",
        "//src/integration/tpp_secrets_service/proto:lib",
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//third_party:com_google_guava_guava",
        "//third_party:com_google_inject_guice",
        "//third_party:io_dropwizard_dropwizard_lifecycle",
        "//third_party:io_netty_netty_all",
        "//third_party:netty",
        "//third_party:org_bouncycastle_bcprov_jdk15on",
        "//third_party:org_slf4j_slf4j_api",
    ],
)
