java_library(
    name = "dropwizard_lifecycle",
    srcs = ["@tink_backend//src/libraries/dropwizard_lifecycle:dropwizard_lifecycle_srcjar"],
    visibility = ["//visibility:public"],
    deps = [
        "@aggregation//:io_dropwizard_dropwizard_core",
        "@aggregation//:io_dropwizard_dropwizard_lifecycle",
        "@aggregation//:org_slf4j_slf4j_api",
    ],
)
