apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: aggregation-java11
  namespace: aggregation
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: aggregation-service-java11
