java_library(
    name = "agents-models",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/serialization:serialization",
        "//src/libraries/strings:strings",
        "//src/libraries/uuid",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//third_party:com_google_guava_guava",
    ],
)
