package se.tink.backend.aggregation.rpc;

import org.junit.Assert;
import org.junit.Test;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class RecurringPaymentRequestDeserializationTest {

    @Test
    public void deserializableFromJsonTest() {
        // Given
        String jsonPayload = getExampleJson();

        // When
        RecurringPaymentRequest recurringPaymentRequest =
                SerializationUtils.deserializeFromString(
                        jsonPayload, RecurringPaymentRequest.class);

        // Then
        Assert.assertNotNull(recurringPaymentRequest);
    }

    private String getExampleJson() {
        return "{\n"
                + "  \"credentials\": {\n"
                + "    \"providerLatency\": 0,\n"
                + "    \"sensitiveDataSerialized\": \"{\\\"version\\\":2,\\\"timestamp\\\":1618561078086,\\\"keyId\\\":0,\\\"fields\\\":\\\"{\\\\\\\"version\\\\\\\":2,\\\\\\\"timestamp\\\\\\\":\\\\\\\"2021-04-16T08:17:58.086Z\\\\\\\",\\\\\\\"keyId\\\\\\\":3,\\\\\\\"payload\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"iv\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"+tODTsFykY+fPdlF\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"data\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"X/crCt4bNVeitdLi47eV7LGc\\\\\\\\\\\\\\\"}\\\\\\\"}\\\",\\\"payload\\\":\\\"{\\\\\\\"version\\\\\\\":2,\\\\\\\"timestamp\\\\\\\":\\\\\\\"2021-04-16T08:17:58.086Z\\\\\\\",\\\\\\\"keyId\\\\\\\":3,\\\\\\\"payload\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"iv\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"om+Zl5jMWZKnu7i5\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\"data\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"47qJiPTU57+CAbc9vuorQUpNdq8bZeiFS6imn/3pSXGrvUlyxf1nKuD5AMNovonrarrvD0HA70DLrLMabHAedzSCwAWiUWtOgX6Sa46S8k3ERpxSvzhyAei1tELqH6Nto2Vh5AxUO6G8Z7KIT27BVjlIZsFxrCs8E2GkaW+NNhLtfyLdrWuAWpXOge/GYYRpDpnUnjcI8c3zqY2buBSzLcrQjHTASNgT9ZMJXCiVQ3qmzDDdlCT4nrdHl8WuLYy+350RMHYonJt2wRrat6FzZ+Zzs0nvMnTbvduo56nrhdnBk4Kht+jE4gj4CvqLNJ63X3XWblqTsDn0rFeccyZQzaSby7CW+UF9kZO6kX/poCJsTVIBmMKYduVQqzORru3KYCj0ADDXADsDCXk315BPDgSp0u3O2dzonz4aIND3CcKNh4fAybhFgpF+aaQtWnISFUOMI5nYWduzll+r511rhgb0hAHv11+Gjb7xWQFkhIk2LQMvPb++rp3ozc4X6ejxUrdx3q5GjPCS31aywhhZGZA\\\\\\\\u003d\\\\\\\\\\\\\\\"}\\\\\\\"}\\\"}\",\n"
                + "    \"id\": \"749d9eb38428445a951b306562c42745\",\n"
                + "    \"providerName\": \"it-test-open-banking-redirect\",\n"
                + "    \"status\": \"UPDATED\",\n"
                + "    \"statusPayload\": \"Updated.\",\n"
                + "    \"statusUpdated\": 1618561078108,\n"
                + "    \"type\": \"PASSWORD\",\n"
                + "    \"updated\": 1618561078104,\n"
                + "    \"userId\": \"f8e8d9b3f90f47a2a366a9ae932542b5\",\n"
                + "    \"sessionExpiryDate\": 1621153076000,\n"
                + "    \"psd2CredentialGenerated\": false,\n"
                + "    \"dataVersion\": 1,\n"
                + "    \"fields\": {},\n"
                + "    \"sensitivePayload\": {}\n"
                + "  },\n"
                + "  \"provider\": {\n"
                + "    \"accessType\": \"OPEN_BANKING\",\n"
                + "    \"authenticationUserType\": \"PERSONAL\",\n"
                + "    \"authenticationFlow\": \"REDIRECT\",\n"
                + "    \"financialServices\": [\n"
                + "      {\n"
                + "        \"segment\": \"PERSONAL\",\n"
                + "        \"shortName\": \"Personal Banking\",\n"
                + "        \"financialServiceSegment\": \"PERSONAL\"\n"
                + "      }\n"
                + "    ],\n"
                + "    \"capabilitiesSerialized\": \"[\\\"TRANSFERS\\\",\\\"MORTGAGE_AGGREGATION\\\",\\\"CHECKING_ACCOUNTS\\\",\\\"SAVINGS_ACCOUNTS\\\",\\\"CREDIT_CARDS\\\",\\\"LOANS\\\",\\\"INVESTMENTS\\\",\\\"IDENTITY_DATA\\\"]\",\n"
                + "    \"pisCapabilitiesSerialized\": \"[\\\"PIS_SEPA\\\",\\\"PIS_SEPA_ICT\\\"]\",\n"
                + "    \"className\": \"nxgen.demo.banks.psd2.redirect.RedirectAuthenticationDemoAgent\",\n"
                + "    \"credentialsType\": \"THIRD_PARTY_APP\",\n"
                + "    \"currency\": \"EUR\",\n"
                + "    \"displayName\": \"Demo Open Banking Redirect\",\n"
                + "    \"financialInstitutionId\": \"f58e31ebaf625c15a9601aa4deac83d0\",\n"
                + "    \"financialInstitutionName\": \"Demo Open Banking Redirect\",\n"
                + "    \"defaultDataVersion\": 0,\n"
                + "    \"groupDisplayName\": \"Demo providers\",\n"
                + "    \"market\": \"IT\",\n"
                + "    \"multiFactor\": true,\n"
                + "    \"name\": \"it-test-open-banking-redirect\",\n"
                + "    \"passwordHelpText\": \"To connect your bank, you need to identify yourself using a third party app.\",\n"
                + "    \"popular\": false,\n"
                + "    \"backgroundRefreshMaxFrequency\": 4,\n"
                + "    \"backgroundRefreshEnabled\": true,\n"
                + "    \"status\": \"ENABLED\",\n"
                + "    \"transactional\": true,\n"
                + "    \"type\": \"TEST\",\n"
                + "    \"displayDescription\": \"Redirect\",\n"
                + "    \"releaseStatus\": \"GENERALLY_AVAILABLE\",\n"
                + "    \"complianceStatus\": \"NON_COMPLIANT\",\n"
                + "    \"fields\": [],\n"
                + "    \"realProvider\": false,\n"
                + "    \"supplementalFields\": [],\n"
                + "    \"testProvider\": true,\n"
                + "    \"openBanking\": true,\n"
                + "    \"passwordIsPIN\": false,\n"
                + "    \"passwordLength\": 0,\n"
                + "    \"demoProvider\": true,\n"
                + "    \"usernameIsPersonnummer\": false,\n"
                + "    \"legacyDemoProvider\": false,\n"
                + "    \"capabilities\": [\n"
                + "      \"INVESTMENTS\",\n"
                + "      \"CHECKING_ACCOUNTS\",\n"
                + "      \"LOANS\",\n"
                + "      \"CREDIT_CARDS\",\n"
                + "      \"IDENTITY_DATA\",\n"
                + "      \"TRANSFERS\",\n"
                + "      \"MORTGAGE_AGGREGATION\",\n"
                + "      \"SAVINGS_ACCOUNTS\"\n"
                + "    ],\n"
                + "    \"pisCapabilities\": [\n"
                + "      \"PIS_SEPA\",\n"
                + "      \"PIS_SEPA_ICT\"\n"
                + "    ]\n"
                + "  },\n"
                + "  \"user\": {\n"
                + "    \"created\": 1618561071000,\n"
                + "    \"flags\": [\n"
                + "      \"ACTIONABLE_INSIGHTS\",\n"
                + "      \"ANONYMOUS\",\n"
                + "      \"NO_TINK_USER\",\n"
                + "      \"READY_FOR_PSD2_MIGRATION\",\n"
                + "      \"TEMPORARY\",\n"
                + "      \"RECURRING_TRANSACTIONS\",\n"
                + "      \"BUDGETS_V2\",\n"
                + "      \"TRANSFERS\",\n"
                + "      \"BUDGETS_MIGRATE\"\n"
                + "    ],\n"
                + "    \"id\": \"f8e8d9b3f90f47a2a366a9ae932542b5\",\n"
                + "    \"profile\": {\n"
                + "      \"currency\": \"EUR\",\n"
                + "      \"locale\": \"en_US\",\n"
                + "      \"market\": \"IT\",\n"
                + "      \"periodAdjustedDay\": 15,\n"
                + "      \"periodMode\": \"MONTHLY\",\n"
                + "      \"timeZone\": \"Europe/Rome\",\n"
                + "      \"cashbackEnabled\": false,\n"
                + "      \"periodSettings\": {\n"
                + "        \"mode\": \"MONTHLY\",\n"
                + "        \"adjustedPeriodDay\": 15\n"
                + "      },\n"
                + "      \"notificationSettings\": {\n"
                + "        \"balance\": true,\n"
                + "        \"budget\": true,\n"
                + "        \"doubleCharge\": true,\n"
                + "        \"income\": true,\n"
                + "        \"largeExpense\": true,\n"
                + "        \"summaryMonthly\": true,\n"
                + "        \"summaryWeekly\": true,\n"
                + "        \"transaction\": true,\n"
                + "        \"unusualAccount\": true,\n"
                + "        \"unusualCategory\": true,\n"
                + "        \"einvoices\": true,\n"
                + "        \"fraud\": true,\n"
                + "        \"leftToSpend\": false,\n"
                + "        \"loanUpdate\": true\n"
                + "      }\n"
                + "    }\n"
                + "  },\n"
                + "  \"create\": false,\n"
                + "  \"update\": false,\n"
                + "  \"appUriId\": \"047c667f-0f33-4405-a9aa-51e22727feed\",\n"
                + "  \"dataFetchingRestrictions\": [],\n"
                + "  \"timePutOnQueue\": 0,\n"
                + "  \"timeLeavingQueue\": 0,\n"
                + "  \"signableOperation\": {\n"
                + "    \"created\": 1618561080857,\n"
                + "    \"id\": \"4238c980-9e8c-11eb-8824-83f3e2021a2a\",\n"
                + "    \"status\": \"CREATED\",\n"
                + "    \"type\": \"RECURRING_PAYMENT\",\n"
                + "    \"underlyingId\": \"5be22e27-3b35-4109-a9a4-b8b403de9665\",\n"
                + "    \"updated\": 1618561080857,\n"
                + "    \"userId\": \"f8e8d9b3-f90f-47a2-a366-a9ae932542b5\",\n"
                + "    \"credentialsId\": \"749d9eb3-8428-445a-951b-306562c42745\"\n"
                + "  },\n"
                + "  \"id\": \"5be22e27-3b35-4109-a9a4-b8b403de9665\",\n"
                + "  \"credentialsId\": \"749d9eb38428445a951b306562c42745\",\n"
                + "  \"userId\": \"f8e8d9b3-f90f-47a2-a366-a9ae932542b5\",\n"
                + "  \"creditorType\": \"IBAN\",\n"
                + "  \"creditorId\": \"FR7630006000011234567890189\",\n"
                + "  \"creditorName\": \"Merchant LLC\",\n"
                + "  \"amount\": 100,\n"
                + "  \"currency\": \"EUR\",\n"
                + "  \"remittanceInformation\": {\n"
                + "    \"type\": \"UNSTRUCTURED\",\n"
                + "    \"value\": \"wow so recurring\"\n"
                + "  },\n"
                + "  \"frequency\": \"MONTHLY\",\n"
                + "  \"executionRule\": \"PRECEEDING\",\n"
                + "  \"dayOfExecution\": 10,\n"
                + "  \"startDate\": \"2021-03-10\",\n"
                + "  \"forceAuthenticate\": false\n"
                + "}";
    }
}
