java_library(
    name = "hellobank",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/agents/src/main/java/se/tink/backend/aggregation/agents/nxgen/fr/banks/bnpparibas",
        "//src/integration/lib",
        "//src/integration/lib:annotations",
        "//third_party:com_google_inject_guice",
        "//third_party:lombok_libs",
    ],
)
