package se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.Payment;

public class BelfiusPaymentTestData {

    public static final String RESPONSE =
            "{\n"
                    + "    \"pendingResponseSets\": false,\n"
                    + "    \"responseSets\": [{\n"
                    + "        \"requestCounter\": 13,\n"
                    + "        \"applicationId\": \"BDM\",\n"
                    + "        \"responses\": [{\n"
                    + "            \"LoadScreen\": [{\n"
                    + "                \"screenName\": \"gef0.gef1.gemd.Native_BeneficiaryManagement\"\n"
                    + "            }, {\n"
                    + "                \"screenVersion\": \"%24Revision%3A+1.14+%24+%5BP060%5D\"\n"
                    + "            }, {\n"
                    + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement\"\n"
                    + "            }, {\n"
                    + "                \"modal\": false\n"
                    + "            }]\n"
                    + "        }, {\n"
                    + "            \"LoadScreen\": [{\n"
                    + "                \"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse\"\n"
                    + "            }, {\n"
                    + "                \"screenVersion\": \"%24Revision%3A+1.2+%24+%5BP060%5D\"\n"
                    + "            }, {\n"
                    + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature\"\n"
                    + "            }, {\n"
                    + "                \"modal\": false\n"
                    + "            }]\n"
                    + "        }, {\n"
                    + "            \"LoadScreen\": [{\n"
                    + "                \"screenName\": \"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"\n"
                    + "            }, {\n"
                    + "                \"screenVersion\": \"%24Revision%3A+1.11+%24+%5BP060%5D\"\n"
                    + "            }, {\n"
                    + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_protocolDetermination\"\n"
                    + "            }, {\n"
                    + "                \"modal\": false\n"
                    + "            }]\n"
                    + "        }, {\n"
                    + "            \"LoadScreen\": [{\n"
                    + "                \"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"\n"
                    + "            }, {\n"
                    + "                \"screenVersion\": \"%24Revision%3A+1.7+%24+%5BP060%5D\"\n"
                    + "            }, {\n"
                    + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature\"\n"
                    + "            }, {\n"
                    + "                \"modal\": false\n"
                    + "            }]\n"
                    + "        }, {\n"
                    + "            \"ScreenUpdate\": [{\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegistrationResultDescription\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_EntityAccounts\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"contentList\": {\n"
                    + "                        \"staticcontent\": {},\n"
                    + "                        \"dynamiccontent\": [],\n"
                    + "                        \"type\": \"full\"\n"
                    + "                    }\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Ext_Int_Account\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Communication\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Name\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CodeCountry\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_AccountTypes\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"contentList\": {\n"
                    + "                        \"staticcontent\": {},\n"
                    + "                        \"dynamiccontent\": [],\n"
                    + "                        \"type\": \"full\"\n"
                    + "                    }\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_BenefiariesContacts\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"contentList\": {\n"
                    + "                        \"staticcontent\": {\n"
                    + "                            \"repeatedPane_BeneficiariesContacts\": {\n"
                    + "                                \"btn_Selected\": {\n"
                    + "                                    \"color\": \"Green\",\n"
                    + "                                    \"label\": \"Select\",\n"
                    + "                                    \"small\": \"true\"\n"
                    + "                                }\n"
                    + "                            }\n"
                    + "                        },\n"
                    + "                        \"dynamiccontent\": [],\n"
                    + "                        \"type\": \"full\"\n"
                    + "                    }\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_StructuredCommunication\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_TransferOrigin\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"contentList\": {\n"
                    + "                        \"staticcontent\": {},\n"
                    + "                        \"dynamiccontent\": [],\n"
                    + "                        \"type\": \"full\"\n"
                    + "                    }\n"
                    + "                }]\n"
                    + "            }, {\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature@mlb_ActionIdentifier\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"text\": \"\"\n"
                    + "                }]\n"
                    + "            }]\n"
                    + "        }]\n"
                    + "    }, {\n"
                    + "        \"requestCounter\": 13,\n"
                    + "        \"applicationId\": \"BDM\",\n"
                    + "        \"responses\": [{\n"
                    + "            \"ScreenUpdate\": [{\n"
                    + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_BenefiariesContacts\",\n"
                    + "                \"properties\": [{\n"
                    + "                    \"contentList\": {\n"
                    + "                        \"staticcontent\": {\n"
                    + "                            \"repeatedPane_BeneficiariesContacts\": {\n"
                    + "                                \"btn_Selected\": {\n"
                    + "                                    \"color\": \"Green\",\n"
                    + "                                    \"label\": \"Select\",\n"
                    + "                                    \"small\": \"true\"\n"
                    + "                                }\n"
                    + "                            }\n"
                    + "                        },\n"
                    + "                        \"dynamiccontent\": [{\n"
                    + "                            \"key\": \"1\",\n"
                    + "                            \"repeatedPane_BeneficiariesContacts\": {\n"
                    + "                                \"mlb_ZipCode\": {\n"
                    + "                                    \"text\": \"\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Alias\": {\n"
                    + "                                    \"text\": \"\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Key2_SequenceNumber\": {\n"
                    + "                                    \"text\": \"1\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Street\": {\n"
                    + "                                    \"text\": \"\"\n"
                    + "                                },\n"
                    + "                                \"mlb_HouseNumber\": {\n"
                    + "                                    \"text\": \"\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Ext_Int_Account\": {\n"
                    + "                                    \"text\": \"IBE11111111111111\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Communication\": {\n"
                    + "                                    \"text\": \"\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Name\": {\n"
                    + "                                    \"text\": \"fake name\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Amount\": {\n"
                    + "                                    \"text\": \"\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Key1_ListNumber\": {\n"
                    + "                                    \"text\": \"11111111\"\n"
                    + "                                },\n"
                    + "                                \"mlb_StructuredCommunication\": {\n"
                    + "                                    \"text\": \"N\"\n"
                    + "                                },\n"
                    + "                                \"mlb_City\": {\n"
                    + "                                    \"text\": \"\"\n"
                    + "                                },\n"
                    + "                                \"mlb_CodeCountry\": {\n"
                    + "                                    \"text\": \"BE\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Contact\": {\n"
                    + "                                    \"text\": \"Y\"\n"
                    + "                                },\n"
                    + "                                \"mlb_Account\": {\n"
                    + "                                    \"text\": \"BE11 1111 1111 1111\"\n"
                    + "                                }\n"
                    + "                            }\n"
                    + "                        }],\n"
                    + "                        \"type\": \"full\"\n"
                    + "                    }\n"
                    + "                }]\n"
                    + "            }]\n"
                    + "        }]\n"
                    + "    }]\n"
                    + "}";
    public static final String SIGN2_REQUIRE_FRENCH =
            "{\"pendingResponseSets\":false,\"responseSets\":[{\"requestCounter\":14,\"applicationId\":\"BDM\",\"responses\":[{\"LoadScreen\":[{\"screenName\":\"gef0.gef1.gemd.Native_Transfers\"},{\"screenVersion\":\"%24Revision%3A+1.19+%24+%5BP062%5D\"},{\"parentWidgetId\":\"Container@reuse_transfer\"},{\"modal\":false}]},{\"LoadScreen\":[{\"screenName\":\"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"},{\"screenVersion\":\"%24Revision%3A+1.11+%24+%5BP060%5D\"},{\"parentWidgetId\":\"Container@reuse_transfer@reuse_protocolDetermination\"},{\"modal\":false}]},{\"LoadScreen\":[{\"screenName\":\"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"},{\"screenVersion\":\"%24Revision%3A+1.7+%24+%5BP060%5D\"},{\"parentWidgetId\":\"Container@reuse_transfer@reuse_ItsMeSignature\"},{\"modal\":false}]},{\"ScreenUpdate\":[{\"widgetId\":\"Container@reuse_transfer@inp_benefhouse\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_ownbenefaccount\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_benefstreet\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_benefzip\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_benefcity\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_benefname\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_country\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_structuredCommFlag\",\"properties\":[{\"text\":\"N\"}]},{\"widgetId\":\"Container@reuse_transfer@lb_exec_ok\",\"properties\":[{\"text\":\"N\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_amount\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_memodate\",\"properties\":[{\"text\":\"09/01/2019\"}]},{\"widgetId\":\"Container@reuse_transfer@reuse_ItsMeSignature@mlb_ActionIdentifier\",\"properties\":[{\"text\":\"\"}]}]}]},{\"requestCounter\":14,\"applicationId\":\"BDM\",\"responses\":[{\"ScreenUpdate\":[{\"widgetId\":\"Container@reuse_transfer@inp_benefhouse\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_benefstreet\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_benefzip\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_benefcity\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@lb_exc\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@lb_exc_desc\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_signature\",\"properties\":[{\"text\":\"dummy\"}]},{\"widgetId\":\"Container@reuse_transfer@lb_exec_ok\",\"properties\":[{\"text\":\"N\"}]},{\"widgetId\":\"Container@reuse_transfer@inp_commchange\",\"properties\":[{\"text\":\"Tink trans 10.00 EUR\"}]}]},{\"MessageResponse\":[{\"messageContent\":\"Attention!  Vous avez déjà introduit un virement similaire. Si vous souhaitez poursuivre l'exécution de ce virement, veuillez cliquer sur le bouton 'Continuer'. Sinon, veuillez cliquer sur le bouton 'Modifier'.\\n(MOBILEBANKINGTRANSFERCREATION   /12DB/000000)\"},{\"messageDetail\":\"ERROR IN OperationMobileBankingTransferCreation (RK9HI510/12DB/000000)\\nN             2019                          PERSONAL INFORMATION KBC                                                   Y                                                                                                                                                                                                                                                                                                                                                                YFBEPERSONAL INFORMATION                  900000002 KREDBEBB             FBEPERSONAL INFORMATION                  16012019Y1121100 NON000000000000000000\"},{\"messageType\":\"warning\"},{\"messageTarget\":\"internal\"}]}]}]}";

    static final String BENEFICIARY_RESPONSE =
            "{\n"
                    + "\t\"pendingResponseSets\": false,\n"
                    + "\t\"responseSets\": [{\n"
                    + "\t\t\"requestCounter\": 14,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_BeneficiaryManagement\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.14+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.2+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.11+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_protocolDetermination\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.7+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_EntityAccounts\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Ext_Int_Account\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_AccountTypes\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Name\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Communication\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_TransferOrigin\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegistrationResultDescription\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_StructuredCommunication\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CodeCountry\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature@mlb_ActionIdentifier\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}, {\n"
                    + "\t\t\"requestCounter\": 14,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_BenefiariesContacts\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {\n"
                    + "\t\t\t\t\t\t\t\"repeatedPane_BeneficiariesContacts\": {\n"
                    + "\t\t\t\t\t\t\t\t\"btn_Selected\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"color\": \"Green\",\n"
                    + "\t\t\t\t\t\t\t\t\t\"label\": \"Select\",\n"
                    + "\t\t\t\t\t\t\t\t\t\"small\": \"true\"\n"
                    + "\t\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [{\n"
                    + "\t\t\t\t\t\t\t\"key\": \"1\",\n"
                    + "\t\t\t\t\t\t\t\"repeatedPane_BeneficiariesContacts\": {\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_ZipCode\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Alias\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Key2_SequenceNumber\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"1\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Street\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_HouseNumber\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Ext_Int_Account\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"IBE11111111111111\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Communication\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Name\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"Fake Name\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Amount\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Key1_ListNumber\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"3274151\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_StructuredCommunication\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_City\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_CodeCountry\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"BE\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Contact\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Account\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"BE11 1111 1111 1111\"\n"
                    + "\t\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\t\"key\": \"2\",\n"
                    + "\t\t\t\t\t\t\t\"repeatedPane_BeneficiariesContacts\": {\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_ZipCode\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Alias\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Key2_SequenceNumber\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"2\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Street\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_HouseNumber\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Ext_Int_Account\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"IBE11111111111111\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Communication\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Name\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"Optional.empty\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Amount\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Key1_ListNumber\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"3274151\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_StructuredCommunication\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_City\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_CodeCountry\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"BE\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Contact\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"mlb_Account\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"BE11 1111 1111 1111\"\n"
                    + "\t\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}]\n"
                    + "}";
    static final String signBeneficiaryRequire =
            "{\"pendingResponseSets\":false,\"responseSets\":[{\"requestCounter\":15,\"applicationId\":\"BDM\",\"responses\":[{\"LoadScreen\":[{\"screenName\":\"gef0.gef1.gemd.Native_BeneficiaryManagement\"},{\"screenVersion\":\"%24Revision%3A+1.14+%24+%5BP060%5D\"},{\"parentWidgetId\":\"Container@reuse_BeneficiaryManagement\"},{\"modal\":false}]},{\"LoadScreen\":[{\"screenName\":\"gef0.gef1.gemd.Native_Signature_Reuse\"},{\"screenVersion\":\"%24Revision%3A+1.2+%24+%5BP060%5D\"},{\"parentWidgetId\":\"Container@reuse_BeneficiaryManagement@reuse_signature\"},{\"modal\":false}]},{\"LoadScreen\":[{\"screenName\":\"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"},{\"screenVersion\":\"%24Revision%3A+1.11+%24+%5BP060%5D\"},{\"parentWidgetId\":\"Container@reuse_BeneficiaryManagement@reuse_protocolDetermination\"},{\"modal\":false}]},{\"LoadScreen\":[{\"screenName\":\"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"},{\"screenVersion\":\"%24Revision%3A+1.7+%24+%5BP060%5D\"},{\"parentWidgetId\":\"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature\"},{\"modal\":false}]},{\"ScreenUpdate\":[{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_CommChange\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Amount\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Alias\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_City\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Name\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Bic\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@rep_AccountTypes\",\"properties\":[{\"contentList\":{\"staticcontent\":{},\"dynamiccontent\":[],\"type\":\"full\"}}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Communication\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_StructuredCommunication\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@mlb_RegistrationResultDescription\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Street\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Ext_Int_Account\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_CodeCountry\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@rep_EntityAccounts\",\"properties\":[{\"contentList\":{\"staticcontent\":{},\"dynamiccontent\":[],\"type\":\"full\"}}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_TransferOrigin\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\"properties\":[{\"contentList\":{\"staticcontent\":{},\"dynamiccontent\":[],\"type\":\"full\"}}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature@mlb_ActionIdentifier\",\"properties\":[{\"text\":\"\"}]}]}]},{\"requestCounter\":15,\"applicationId\":\"BDM\",\"responses\":[{\"ScreenUpdate\":[{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_CommChange\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Amount\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Alias\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\"properties\":[{\"text\":\"N\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_City\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Bic\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Street\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\"properties\":[{\"text\":\"\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\"properties\":[{\"contentList\":{\"staticcontent\":{},\"dynamiccontent\":[{\"RP_Scenario\":{\"lb_scen_data_formatted\":{\"text\":\"\"},\"lb_scen_type\":{\"text\":\"03\"},\"lb_scen_label\":{\"text\":\"Een begunstigde aanmaken?\"},\"lb_scen_data\":{\"text\":\"\"}},\"key\":\"1\"},{\"RP_Scenario\":{\"lb_scen_data_formatted\":{\"text\":\"917360\"},\"lb_scen_type\":{\"text\":\"00\"},\"lb_scen_label\":{\"text\":\"Controlegetal:\"},\"lb_scen_data\":{\"text\":\"917360\"}},\"key\":\"2\"}],\"type\":\"full\"}}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@reuse_signature@lb_Challenge\",\"properties\":[{\"text\":\"3812 9670 9279\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@reuse_signature@mlb_BuyIcon\",\"properties\":[{\"text\":\"N\"}]},{\"widgetId\":\"Container@reuse_BeneficiaryManagement@reuse_signature@lb_Protocol\",\"properties\":[{\"text\":\"PROTIMSC\"}]}]}]}]}";
    static final String signPrep =
            "{\n"
                    + "\t\"pendingResponseSets\": false,\n"
                    + "\t\"responseSets\": [{\n"
                    + "\t\t\"requestCounter\": 15,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_ownbenefaccount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefname\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"Fake Name\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_amount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"2.000,00 EUR\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_country\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"BE\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_memodate\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"27/04/2018\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_PWAllowed\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_ConfirmAllowed\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_ItsMeAllowed\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_CardReaderAllowed\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"Y\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}]\n"
                    + "}";

    static final String SIGN_REQUIRE =
            "{\n"
                    + "\t\"pendingResponseSets\": false,\n"
                    + "\t\"responseSets\": [{\n"
                    + "\t\t\"requestCounter\": 13,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Transfers\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.25+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.11+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer@reuse_protocolDetermination\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.7+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer@reuse_ItsMeSignature\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_structuredCommFlag\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_amount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_country\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_memodate\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"26/04/2018\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_ownbenefaccount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefname\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_ItsMeSignature@mlb_ActionIdentifier\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}, {\n"
                    + "\t\t\"requestCounter\": 13,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_signature\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"dummy\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"1208000000\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_commchange\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"TEST FROM TEST1524735839283\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"De weeklimiet voor \\\"Mijn begunstigden\\\" werd bereikt. Daarom moet u even ondertekenen.\\n(MOBILEBANKINGTRANSFERCREATION   /1000/AMW033)\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"MessageResponse\": [{\n"
                    + "\t\t\t\t\"messageContent\": \"De weeklimiet voor \\\"Mijn begunstigden\\\" werd bereikt. Daarom moet u even ondertekenen.\\n(MOBILEBANKINGTRANSFERCREATION   /1000/AMW033)\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"messageDetail\": \"ERROR IN  OperationMobileTransferCreation (1208/000000)\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"messageType\": \"error\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"messageTarget\": \"internal\"\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}]\n"
                    + "}";
    static final String PAYMENT_REQUEST =
            "{\n"
                    + "\t\"pendingResponseSets\": false,\n"
                    + "\t\"responseSets\": [{\n"
                    + "\t\t\"requestCounter\": 16,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"LoadScreen\": [{\n"
                    + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.2+%24+%5BP060%5D\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer@reuse_signature\"\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"modal\": false\n"
                    + "\t\t\t}]\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc_sign\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_sign\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_ownbenefaccount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefname\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"Cedric Verbeken\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_amount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"2.000,00 EUR\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok_Transfer_Signed\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_country\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"BE\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_memodate\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"27/04/2018\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@lb_Challenge\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"4420 5434 5740\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@lb_Protocol\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"PROTIMSC\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@rep_scenarios\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [{\n"
                    + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"03\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"Een overschrij-<br />ving tekenen?\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\"key\": \"1\"\n"
                    + "\t\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"2000\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"00\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"Bedrag:\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"2000\"\n"
                    + "\t\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\"key\": \"2\"\n"
                    + "\t\t\t\t\t\t}],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@mlb_BuyIcon\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}]\n"
                    + "}";

    static final String BENEFICIARY_ADD_STRING =
            "{\n"
                    + "\t\"pendingResponseSets\": false,\n"
                    + "\t\"responseSets\": [{\n"
                    + "\t\t\"requestCounter\": 15,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CodeCountry\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Name\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Communication\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_TransferOrigin\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_AccountTypes\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_StructuredCommunication\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_EntityAccounts\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Ext_Int_Account\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegistrationResultDescription\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}, {\n"
                    + "\t\t\"requestCounter\": 15,\n"
                    + "\t\t\"applicationId\": \"BDM\",\n"
                    + "\t\t\"responses\": [{\n"
                    + "\t\t\t\"ScreenUpdate\": [{\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"contentList\": {\n"
                    + "\t\t\t\t\t\t\"staticcontent\": {},\n"
                    + "\t\t\t\t\t\t\"dynamiccontent\": [{\n"
                    + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"03\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"Een begunstigde aanmaken?\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
                    + "\t\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\"key\": \"1\"\n"
                    + "\t\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"602710\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"00\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"Controlegetal:\"\n"
                    + "\t\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
                    + "\t\t\t\t\t\t\t\t\t\"text\": \"602710\"\n"
                    + "\t\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\t\t\"key\": \"2\"\n"
                    + "\t\t\t\t\t\t}],\n"
                    + "\t\t\t\t\t\t\"type\": \"full\"\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@mlb_BuyIcon\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"N\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@lb_Protocol\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"PROTIMSC\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}, {\n"
                    + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@lb_Challenge\",\n"
                    + "\t\t\t\t\"properties\": [{\n"
                    + "\t\t\t\t\t\"text\": \"3154 7130 2300\"\n"
                    + "\t\t\t\t}]\n"
                    + "\t\t\t}]\n"
                    + "\t\t}]\n"
                    + "\t}]\n"
                    + "}";
}
