java_library(
    name = "factory",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/credentials:service",
        "//src/integration/lib",
        "//third_party:com_google_guava_guava",
        "//third_party:com_google_inject_guice",
    ],
)
