load("//tools/bzl:junit.bzl", "junit_test")

junit_test(
    name = "agentfactory",
    srcs = glob(["*.java"]),
    deps = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/agents/agentfactory",
    ],
)
