java_library(
    name = "rpc",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/date",
        "//src/libraries/serialization",
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:io_vavr",
        "//third_party:joda_time_joda_time",
        "@aggregation//:com_google_guava_guava",
    ],
)
