kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-se
  namespace: agents
spec:
  rules:

  - alert: LoginSuccessRateBelow90WithAttemptLimitSE
    expr: |
      # Successful/Cancelled attempts above 90%
      (sum(increase(tink_agent_login_total{action=~"login|is-logged-in", outcome=~"completed|cancelled|unavailable", market="SE", provider_type!="test"}[60m])) by (action,className,provider)
          / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) < 0.90)
      # At least this many attempts.
      and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) > 10
    for: 5m
    labels:
      severity: urgent
      priority: P4
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Login success rate is below 90% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last hour.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: LoginSuccessRateBelow80WithAttemptLimitSE
    expr: |
      # Successful/Cancelled attempts above 80%
      (sum(increase(tink_agent_login_total{action=~"login|is-logged-in", outcome=~"completed|cancelled|unavailable", market="SE", provider_type!="test"}[60m])) by (action,className,provider)
          / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) < 0.80)
      # At least this many attempts.
      and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) > 10
    for: 5m
    labels:
      severity: urgent
      priority: P3
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Login success rate is below 80% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last hour.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: LoginSuccessRateBelow70WithAttemptLimitSE
    expr: |
      # Successful/Cancelled attempts above 70%
      (sum(increase(tink_agent_login_total{action=~"login|is-logged-in", outcome=~"completed|cancelled|unavailable", market="SE", provider_type!="test"}[60m])) by (action,className,provider)
          / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) < 0.70)
      # At least this many attempts.
      and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) > 10
    for: 5m
    labels:
      severity: urgent
      priority: P2
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Login success rate is below 70% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last hour.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: LoginSuccessRateBelow60WithAttemptLimitSE
    expr: |
      # Successful/Cancelled attempts above 60%
      (sum(increase(tink_agent_login_total{action=~"login|is-logged-in",  outcome=~"completed|cancelled|unavailable", market="SE", provider_type!="test"}[60m])) by (action,className,provider)
          / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) < 0.60)
      # At least this many attempts.
      and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="SE", provider_type!="test"}[60m])) by (action,className,provider) > 10
    for: 5m
    labels:
      severity: urgent
      priority: P1
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Login success rate is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last hour.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: RefreshSuccessRateBelow90WithAttemptLimitSE
    expr: |
      # Successful attempts above 90%
      (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="SE", provider_type!="test"}[30m])) by (className,provider)
          / sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) < 0.90)
      # At least this many attempts.
        and sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) > 40
    for: 5m
    labels:
      severity: urgent
      priority: P4
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Refresh success rate is below 90% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last 30 minutes.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: RefreshSuccessRateBelow80WithAttemptLimitSE
    expr: |
      # Successful attempts above 80%
      (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="SE", provider_type!="test"}[30m])) by (className,provider)
          / sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) < 0.80)
      # At least this many attempts.
        and sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) > 40
    for: 5m
    labels:
      severity: urgent
      priority: P3
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Refresh success rate is below 80% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last 30 minutes.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: RefreshSuccessRateBelow70WithAttemptLimitSE
    expr: |
      # Successful attempts above 70%
      (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="SE", provider_type!="test"}[30m])) by (className,provider)
          / sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) < 0.70)
      # At least this many attempts.
        and sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) > 40
    for: 5m
    labels:
      severity: urgent
      priority: P2
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Refresh success rate is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last 30 minutes.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: RefreshSuccessRateBelow60WithAttemptLimitSE
    expr: |
      # Successful attempts above 60%
      (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="SE", provider_type!="test"}[30m])) by (className,provider)
          / sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) < 0.60)
      # At least this many attempts.
        and sum(increase(tink_agent_refresh_total{market="SE", provider_type!="test"}[30m])) by (className,provider) > 40
    for: 5m
    labels:
      severity: urgent
      priority: P1
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Refresh success rate is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
        the last 30 minutes.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  ### Bank side failures
  - alert: BankServerUnavailableForLoginSE
    expr: |
      # Unavailable outcome above 50%
      (sum(increase(tink_agent_login_total{action=~"login|is-logged-in",  outcome=~"unavailable", market="SE", provider_type!="test"}[30m])) by (action,className)
          / sum(increase(tink_agent_login_total{action=~"login|is-logged-in"}[30m])) by (action,className) > 0.50)
      # At least this many attempts.
      and sum(increase(tink_agent_login_total{action=~"login|is-logged-in"}[30m])) by (action,className) > 10
    for: 5m
    labels:
      severity: urgent
      priority: P1
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Login unavailable rate is above 50% ( <{ $value }> ) for <{ $labels.className }>
        the last 30 minutes.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*

  - alert: BankServerUnavailableForRefreshSE
    expr: |
      # Unavailable outcome above 50%
      (sum(increase(tink_agent_refresh_total{outcome=~"unavailable", market="SE", provider_type!="test"}[30m])) by (className)
          / sum(increase(tink_agent_refresh_total[30m])) by (className) > 0.50)
      # At least this many attempts.
      and sum(increase(tink_agent_refresh_total[30m])) by (className) > 10
    for: 5m
    labels:
      severity: urgent
      priority: P1
      who: integration-thundercats
    annotations:
      description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
        https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
      summary: Refresh unavailable rate is above 50% ( <{ $value }> ) for <{ $labels.className }>
        the last 30 minutes.
      tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-thundercats*
