load("//tools/bzl:maven_artifact.bzl", "java_library_maven")

java_library_maven(
    name = "pair",
    srcs = glob(["src/main/**/*.java"]),
    groupId = "se.tink.libraries.pair",
    visibility = ["//visibility:public"],
    deps = [
    ],
)
