load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "pair",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
)
