package se.tink.backend.aggregation.utils;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.util.NoSuchElementException;
import org.junit.Test;

public class QrCodeParserTest {
    private static String ENCODED_IMAGE =
            "iVBORw0KGgoAAAANSUhEUgAAAjAAAAIwCAYAAACY8VFvAAAY60lEQVR42u3dwbHj"
                    + "MAxEQeWDaJx/MHIWFDHTr0pn/aVIsPfk55UkSVrWYwkkSRLASJIkAYwkSRLASJIk"
                    + "gJEkSQIYSZIkgJEkSQAjSZIEMJIkSQAjSZIARpIkCWAkSZIARpIkAYwkSRLASJIk"
                    + "AYwkSQIYSZIkgJEkSQIYSZIkgJEkSQAjSZIEMJIkSQAjSZIARpIkCWAkSZIARpIk"
                    + "AYwkSRLASJIkAYwkSQIYSZIkgJEkSQIYSZIEMJIkSQAjSZIEMJIkSQAjSZIARpIk"
                    + "CWAkSZIARpIkAYwkSRLASJIkAYwkSQIYSZIkgJEkSQIYSZIEMJIkSQAjSZIEMJIk"
                    + "CWAkSZIARpIkCWAkSRLASJIkAYwkSRLASJIkAYwkSQIYSZIkgJEkSQIYSZIEMJIk"
                    + "SQAjSZIEMJIkCWAkSZIARpIkCWAkSRLANPWb8Rx6bv6mylvrU39b2nvMUXMUYADG"
                    + "AzDOD8AAjAdgAMbBc/AABmAABmDMUQGMgwcwhgLAAIw5ao4CDMB4AMb5ARiA8QAM"
                    + "wDh4Dh7AAAzAAIzHrAIYBw9gDAWAARhz1BwFGIDxAIzzAzAAY74BDMAAjIMHMAAD"
                    + "MADjMasAxsEDGEMBYADGHDVHAcYA9gCMAAZgzFGAARiAcfAABmAABmA8ZhXAOHgO"
                    + "HsAADMAAjDkKMAawDbRwaKf9bf494/zAlTlq3QDGBgIYFz7AOD8A4/4BGBvIugEM"
                    + "wAAMwJij1g1gbCDrBjD+PQADMOaodQMYGwhgXPgA4/wAjPsHYGwgGwhgAAZgAMYc"
                    + "df8AjA1k3QDGvwdgAMYctW4AYwMBjAvfv8f5ARj7AGBsIBsIYAAGYADGHHX/AIwN"
                    + "ZN0Axr8HYABG1g1gbCAD2IXv3+P8AIx9ADA2kA0EMAADMABjjrp/AMYGsm4AAzAA"
                    + "AzDmqHUDGBfxzsvu5m/qF7nBwgzJhJJ1AxjDx8EDGIAxTAHGHAUYgDF8HDyAARgz"
                    + "BGDMUWcOYAwfBw9gAMYMARhzFGAMHwcPYADGMAUYcxRgAMbwcfAABmDMEIAxRwEG"
                    + "YAwfBw9gAMYMARhzFGAMHwcPYADGMAUYa2COAozh4+ABDMCYIQBjjgIMwBg+Dh7A"
                    + "AIwZAjDmqADGwQMYgAEYMwRgzFGAMXwcPIABGDMEYMxRgAEYw8fBs9YAY4YAjDnq"
                    + "zAGMg2dgWQO/eg1x5ijAAIyD5+ABjL0DMLJ3AAZgHDwHD2DsHYAxR50F+w1gHDyX"
                    + "tzUAGIAxRwEGYBw8Bw9g7B2AcaE4CwADMA6egwcw9g7AmKPOgv0GMA6ey9saAAzA"
                    + "mKPmKMA4eA4ewNg7AONCcRYABmAcPAcPYOwdgDFHnQWAARgHz+VtDQAGYMxRcxRg"
                    + "HDwHD2DsHYBxoTgLAAMwDp6DBzD2DsCYo84CwACMg+fytgYAAzDmqDkKMA6eg+fg"
                    + "vdbt4Lo5C9bAHAUYgAEYBw9gAAZgAMa6AQzAOHguYuvm8rYG5qh5ADAA4+ABjHVz"
                    + "eVsDcxRgAAZgHDyAARiAARjrBjBy8Bw8gAEYgAEYcxRgAMbBAxjr5vK2BuYowAAM"
                    + "wDh4AAMwAGMemKMAAzAOnoMHMAADMABjjgIMwDh4AGPdXN7WwBw1DwDGxeXg2QcA"
                    + "AzDmgTkKMADj4Dl4AAMwAAMw5ijAAIyD5yK2bi5va2COmgcAU3JxWbfxHsgGMutm"
                    + "jlo3gLGBAAZgAAZgzFFzFGBsIBsIYADGRQww5qh1AxgbyLoBDMAAjHUzR60bwNhA"
                    + "AAMwAAMw5qg5KoCxgQAGYAAGYMxR6wYwNpB1AxiAARjrZo5aN4CxgawbwAAMwACM"
                    + "OWrdAMYGAhiAARiAMUetG8DYQNYNYADGRWzdzFHrBjA2kHUDGIABGIAxR60bwNhA"
                    + "AAMwAAMw5qh1AxgbyAYCGIBxEQOMOWrdAMbA6noAxnu8x3s8uZAFGIBx8Ax67/Ee"
                    + "gPEADMA4eADjPd7jPQADMAADMB6A8R7v8R5zFGAABmAcPIPee7wHYDwAAzAOHsB4"
                    + "j/d4D8CYowADMB6A8R7v8R5zFGAABmAcPIPee7wHYDwAAzAAAzDe4z3eAzDmKMAA"
                    + "jAdgvMd7vMccBRiAARiPQe893uM9HoABGIABGO/xHu8BGHMUYADGAzDe4z3eAzAA"
                    + "AzCSXFwLf8XbxSUBjCSAARiAkQBGAhiAARhJACMBDMAAjAQwkgAGYABGAhgJYAAG"
                    + "YABGAhgJYAAGYCSAkQQwAAMwEsBIAAMwAAMwEsBIAAMwACMBjCSAARiAkQBGAhiA"
                    + "ARiAkQBGAhiAARgJYFwoft3Uulm3qss7bR/AL8wDDMC4HKybdQMYgPEegAEYgHER"
                    + "WzcPwACM9whgAMZFbN2sNcC48AEGYADG5WDdrBvAAIz3AAzAAIyL2LpZN4ABGO8B"
                    + "GIABGBexdbPWAOPCBxiAARiXg3WzbgADMN4DMAADMC5i62bdAAZgvAdgAAZgXMTW"
                    + "zVoDjAsfYAQwLhQXsXUDGIABC4ABGIBxEVs36wYwAOM9AAMwAOMitm4egAEY7xHA"
                    + "gFLJhWKQOD8ufDMkdV8LYAAGYAwF5wdgAAZgAEaGD8AIYADGmQMYgLFRDR+AEcCY"
                    + "Ifa1dQMYgAEYQ8H5ARiAARiAkeEDMLIPAMaZAxiAsVENH4ARwJgh9rV1AxiAARhD"
                    + "wfkBGIABGIARwACMAAZgnDmAARgb1fABGAGMGWJfWzeAMYABxjB1fgDGDAEYgBHA"
                    + "AIwABmCcOYABGBvV8AEYAQzAOHMAAzA2t8cvS3sM+qIL0h4VwACMB2B8UzMEYOxR"
                    + "gJHDCjAelwPAmIn2KMDIBQkwHpcDwACMAAZgPADjm5ohAGOPAowcVoPEurkcAMZM"
                    + "tEcBRi5IgPG4HAAGYAQwAOMBGN/UDAEYexRg5LC67HwflwPAmIn2KMDIBQkwHpcD"
                    + "wACMAMbw8QCMx+UAMPYowMhhddn5Pi4HgDET7VGAkcMKMB6XA8CYifYowBgKQGZg"
                    + "1ZwFKM2Due9jhgAMwACM4QMwLkiAMUMARgADMIYPwAAMwJghAOMitukMH4ABGIDx"
                    + "fcwQgAEYgDF8AMYFCTBmCMAIYADG8AEYgAEYMwRgXMQ2neEDMAADML6PGQIwAAMw"
                    + "hg/AuCABxgxxlwAMwACM4QMwAAMwZgjAuIhtOsMHYAAGYHwfMwRgDG3rZvg4CwAD"
                    + "MGaIuwRgAAZgDB+AARiAMUMAxkVs0xk+hg/AAAzAmCEAU3CpQsK47PzSb+T5cU7H"
                    + "7PWfYYABGIABGIABGOcUYAAGYADGYAQYgAEYgAEYgAEYgAEYgAEYgAEYgAEYgAEY"
                    + "gAEYgHFOAQZgAMYhMhgBBmAABmAABmAABmAABmAABmAABmAABmAABmAABmCcU4AB"
                    + "GIABGIMRYAAGYAAGYAAGYAAGYAAGYAAGYAAGYAAGYAAGYADGOQUYgAEYgDEYAQZg"
                    + "AAZgAAZgAMYANhgBBmAABmAABmCgx6+bulQN7ab/aHiP/9T5TxDAGKYAAzAA4xIC"
                    + "GHsHYAAGYAAGYJw5gAEYgAEYAYy1djkADMAADMAAjGEKMAADMC4hgLF3AAZgXKoA"
                    + "AzAAAzD2qL0DMAIYa+1yABiAARiAARjDFGAABmBcQgADMAADMC5VgAEYgAEYe9Te"
                    + "ARgBjLV2OQAMwAAMwAAMwAAMwACMSwhgAAZgAMalCjAAAzAAY4/aOwAjgAEYgHHm"
                    + "AAZgAAZgAMbAqvlFYYgDJb/InXl5Oz8AAzAAAzAuVYBxfgAGYAAGYAAGYADGWptv"
                    + "ACOAccABBmAMYGsNMAADMAADMADjUgUY5wdgAAZgAAZgAMalaq0BBmAEMA44wACM"
                    + "AWytAQZgAAZgAAZgXKoA4/wAjPMDMAADMADjUrXWAAMwAhgHHGAAxgC21gADMAAj"
                    + "gDGAXaoAAzAA4/wADMAADMC4VK01wACMAMYBd1gBBmCstfkGMAADI36xtuJC8e9x"
                    + "Tn0fmdcAY6M6EC58FyTAuITsN4ABGBsVYAAGYABG9pu9AzAAAzAA45z6PjKvAcZG"
                    + "dSBc+C5IgHEJ2W8AAzA2qgMBMC5IgJH9Zu8ADMAADMA4p76PzGuAsVEdCBe+f49z"
                    + "6vu4F8xrgLFRHQiAcUECjOw3ewdgAAZgAMY59X1kXgOMjQowAOPf45z6Pu4F8xpg"
                    + "bFQHAmBckAAj+83eARgbFWAABmAARu4FgNHSTWfQ2zsnv8/N+8A59R+A2/ebmQgw"
                    + "AGMw2jsA45wCDMAAjAxGh9X3ARj7AGDMRIBxCRmMDivAAIxzCjBmIsAAjMFo7wCM"
                    + "cwowAAMwMhgdVt8HYJxTgLHWAAMwBqPDCjAA45wCjJkIMABjMNo7AOOcAgzAuIAB"
                    + "BmAcVoABGOcUYKw1wACMweiwAgzAOKcAYyYCjEvIYAQYgAEY5xRgAAZgAMZhBRiA"
                    + "cU4BxloDDMAYjA6r7wMw9gHAmIkA4xJyqbrsZO8AmX1t3QDGpgMYgwRgAMZMNHsB"
                    + "RgADMAYJwACM82PdAMamAxiAkb0DMPa1dQMYmw5gAMaZAxiAcZcAjAAGYAwSgAEY"
                    + "58e6AYxNBzAuIQEMwDg/1g1gbDqAARhnDmAAxl0CMAIYgDFIAAZgnB/rBjA2HcC4"
                    + "hAQwAOP8WDeAsekABmCcOYABGHeJAMamAxiDBGAAxkx0lwCMTQcwLiEBDMA4P9YN"
                    + "YJIGo18h9mvHfukX5l1c7hLfFGAABmAABmAARgADMDadSxVgAAZgAEYAAzAAAzAA"
                    + "AzAA47Jzl/imAAMwAAMwAAMwAhgBDMB4AAZgAEYAAzAAAzAAAzAA47Jzl/imAAMw"
                    + "AGOtAQZgXHYAI4ABGA/AAAzACGAABmAABmAABmBcdvJNAQZgAMZaAwzAuOwARgAD"
                    + "MB6AARiAEcAAjE3nUgUYgAEYgJFvCjDQ4xdr6xBnrcc8sK/NeIABGJsbYAx6gAEY"
                    + "gAEYgBHAGPQAAzD2tW9q3QAGYADGoLfWLjv72owHGICxuQHGoAcYgAEYgAEYSwAw"
                    + "LlWAARj72kUMMAADMABj0Ftrl519bcYDDMDY3ABj0AMMwNjXZrwABmBcqgADMPa1"
                    + "ixhgAAZgAMagt9YuO/vaN7VuAGNzA4xBDzAAY1+b8QIYgHGpAgzA2NcuYoABGAGM"
                    + "QQ8wAGNf+6bWDWBaNqpfIR5/W+AvMfuF8fF9AmEugAEYgAEYgAEYswpgBDCGAsC4"
                    + "7AAGYMwqgBHAGAoAAzAAAzAAI4ABGIABGIABGLMKYAQwhgLAuOycBd/UrAIYAYyh"
                    + "ADAAAzAAAzACGIABGIABGIAxqwBGAGNoAwzAOAu+qVkFMAIYQwFgAAZgAAZgBDAA"
                    + "YygADMAADMAAjADG0AYYgHEWfFOzCmAEMIYCJLjsAAZgzCqAARiA8Quvho/9Zr8V"
                    + "fVPo8bcBjAvFheKw2m8AAzCQYCYCjAvFhWK/2W8AAzAAI4BxoQCM/WatAQZg/G0A"
                    + "40JxoTis9hvAAAwkmIkA40Kx1tbAfgMYgAEYgAEYFwrA2G/WGmAAxt8GMC4UF4rD"
                    + "ar8BDMBAgpkIMC4UF4o1sN8ABmAABmAAxoUCMPabtQYYgPG3AQzAuFAcVvvNfgMY"
                    + "gDETAcaF4kKxBvYbwAAMwAAMwBg+LhT7zX4DGIABGIABGL8SvXBo+5VovxINI9qw"
                    + "dwQwAAMwAAMwACOAARibG2BcqgADMPaoGQ8wAGNzAwzAAAzAAAzA+KYAAzAAAzAA"
                    + "AzACGICxuQHGpQowAAMwZjzAAIzNDTAAAzAAAzAA45sCDMAADMAADMAIYAQwAAMw"
                    + "AAMwAGPGAwzA2NwAAzAAAzAAAzC+KcAADMC4HKw1wLjsAEYAAzAAAzAAAzBmPMAA"
                    + "jM0NMC5VgAEYe9SMBxiAsbkLLgfZB+CX+X38grUzBzAAYzDab/YBwAAMwJi9AAMw"
                    + "DhHAAAzAAAzAAIwLBWAcIoABGN8HYJw5gAEYg9F+sw8ABmAAxuwFGIBxiFyq9gHA"
                    + "AAzAAIwLBWAcIoABGN8HYJw5gAEYg9F+sw8ABmAAxuwFGIBxiADGPgAYgAEYgHGh"
                    + "AIxDBDAA4/sAjDMHMADj4pJ9ADAAAzBmL8AAjEMEMPYBwAAMwACMCwVgHCKAARiA"
                    + "ARiAARiA8Z6S4QPMfvU6EQn2gQAGYLwHYAAGYAAGYAQwAAMw/jaXnX3tARgBDFgY"
                    + "9ADj4gIY+0AAAzDeAzAAAzAAAzACGIDxHn8bwACMbwowAhiwMOgBxsUFMPaBAAZg"
                    + "vAdgAAZgAAZgBDAA4z0AAzAA45sCjAAGLAx6gHFxAYx9IIABGLCABIABGIABGAEM"
                    + "wHgPwAAMwPimACOAceEb9P42l5197QEYgJFKgKm7v2kaeoDsjVtr3wdgJAfcNwUY"
                    + "gAEY8w1gBDACGIABGIABGAlgBDAAAzDmG8BIDrhvCjAAAzDmG8AIYOQSAhiAARiA"
                    + "kQBGAAMwAGO+AYzkgPumAAMwAGO+AYxcdg44wAAMwAAMwEgAI4ABGIAx3wBGcsAF"
                    + "MAADMOYbwMhl54ADDMAADMAAjAQwAhiAARiAARjD1FPx69qG6ZgHzmnkOXV+AMbA"
                    + "8hiMAGMeOKcAAzAAY2AZjAADMOaBcwowAhgDy2AEGAPYPHBOAQZgDCyPwQgw5oFz"
                    + "CjAAAzAGlsEIMABjHjinACOAMbAMRoAxgM0D5xRgAMbA8hiMAGMeOKcA4/wAjIFl"
                    + "MAIMwJgHzinACGAMLIMRYAxg88A5BRiAARiPwQgwAOOcAozzAzAGlsEIMABjHjin"
                    + "ACOAMbAMRoABGPPAOQUYgAEYm866LVyDNFxZN9/0diiZowDjErJu1gBgAMY3BRj3"
                    + "D8DYQNYNYAAGYAAGYADGwLKBrBvA+KYAAzAAAzAuIetmDQAGYHxTgHH/AIwNZN2s"
                    + "gcsOYAAGYADGRWwDWTeA8U0BBmAABmBcQtbNGgAMwPimYOHMAYyL2LpZA5cdwAAM"
                    + "wACMi9gGsm4A45sCDMAADMC4hKybyw5gAAZgAMYcBRgXsXWzBi47gAEYgAEYF7EN"
                    + "ZN0ABmAABmAABmBcQh8OHwfc5ZB44VvrvO/j19zta4ABGIABGBekQQ8wAAMwDjjA"
                    + "AIzhAzC+D8CYIQADMAADMAADML4PwNjXAAMwAAMwLkiDHmAABmAccIABGMMHYMw3"
                    + "gAEYgAEYgAEYgAEY3wdg7GuAARiAARgXpEEPMABjXwMMwACM4QMw5hvAAAzAAAzA"
                    + "AAzAAIzvAzD2NcAADMAAjAvSWgMMwNjXAAMwAGP4AIz5BjAAAzAAY9B7j+EDML4P"
                    + "wJghAAMwAPPxe1wocOXXmzN/Xdt/ggAGYBxWgAEYgLHfzET7DWAABmAABmAABmAA"
                    + "BmAABmAAxoViMLpQAAZgAAZgHFaAARiAsd/MRPsNYAAGYAAGYFze1sBMdE4BBmAA"
                    + "xoViMLpQAAZgAAZgHFaAARiAsd/MRPsNYADGYQUYgHF5WwMz0TkFGIABGBeKwehC"
                    + "ARiAEcAADMAADMAADMAADMAAjMMKMADj8rYGZqJzCjAAAzAuFIABGIABGIABGIDx"
                    + "K9EuIb9C7Pv4PpAAMAADMADjgnRBWmuAEcAADMAAjAsSYHwfgBHAAAzAAIwL0vfx"
                    + "fQAGYAAGYAAGYFyQvg/ACGAABmAAxgUJML4PwAhgAAZgAMYDML4PwAAMwAAMwACM"
                    + "C9L3ARgBDMAADMC4IAHGAzACGIABGIDxAIzvAzAAAzAAAzAA44L0fQBGAAMwAAMw"
                    + "LkgXpAdgBDAAAzAA4wEY3wdgAAZgbG6AybvsnAXATNwH1kAAY6MCDMA4CwADMM4C"
                    + "wLiIrRvAAIyzADAAI4ABGOsGMC4ugLEPAEYAY6MCDMA4CwADMM4CwLiIrRvAAIyz"
                    + "ADAA4ywADMBYN4BxcQGMfQAwAhgbFWAAxlkAGIBxFgDG8LFRAQZgnAWAARhnAWAA"
                    + "xroBjIsLYOwDgBHAAAzAAIyhDTAA4ywAjOFjowIMwDgLAAMwzgLAAIx1AxiAcRYA"
                    + "BmAEMAXDx6/PuhwS182+zsOvNYAegAEYgx5gAAZgAAZgBDAGPcAAjAdgAAZgAAZg"
                    + "PAADMB6AARiAARiAMegBBmAABmAARgBj0LvwDTn7GmAABmAABmA8AAMwHoABGIAB"
                    + "GIAx6AEGYAAGYAAGYAAGYAAGYOxrgAEYgAEYgPEADMB4AAZgAAZgAMYDMABjXwMM"
                    + "wAAMwAAMwACMfQ0wAAMwAAMwBjDAAIwHYAAGYABGkiQJYCRJkgBGkiQBjCRJEsBI"
                    + "kiQBjCRJAhhJkiSAkSRJAhhJkgQwkiRJACNJkgQwkiQJYCRJkgBGkiQJYCRJEsBI"
                    + "kiQBjCRJEsBIkiQBjCRJAhhJkiSAkSRJAhhJkgQwkiRJACNJkgQwkiQJYCRJkgBG"
                    + "kiQJYCRJEsBIkiQBjCRJEsBIkiSAkSRJAhhJkiSAkSRJACNJkgQwkiRJACNJkgQw"
                    + "kiQJYCRJkgBGkiQJYCRJEsBIkiQBjCRJEsBIkiSAkSRJAhhJkiSAkSRJACNJkgQw"
                    + "kiRJACNJkgBGkiQJYCRJkgBGkiQJYCRJEsBIkiQBjCRJEsBIkiSAkSRJAhhJkiSA"
                    + "kSRJACNJkgQwkiRJACNJkgBGkiQJYCRJkgBGkiQ19gc5Yy3QTgKcGwAAAABJRU5E"
                    + "rkJggg==";

    private static String AUTOSTART_TOKEN = "2f5cdf44-8e71-4787-bde1-31817277accf";
    private static String DECODED_IMAGE = "bankid:///?autostarttoken=" + AUTOSTART_TOKEN;

    @Test
    public void testQrCodeParser() throws IOException {
        final String decoded = QrCodeParser.decodeQRCode(ENCODED_IMAGE);
        assertThat(decoded).isEqualTo(DECODED_IMAGE);
    }

    @Test
    public void testBankIdQrCodeParser() throws NoSuchElementException {
        final String token = QrCodeParser.decodeBankIdQrCode(ENCODED_IMAGE);
        assertThat(token).isEqualTo(AUTOSTART_TOKEN);
    }
}
