load("//tools/bzl:maven_artifact.bzl", "java_library_maven")

java_library_maven(
    name = "api_headers",
    srcs = glob(["src/main/**/*.java"]),
    artifactId = "apiheaders",
    groupId = "se.tink.libraries.api",
    visibility = ["//visibility:public"],
)
