# Note: Change this to `java_library_with_sources` once that target uses `java_library_with_sources`.
alias(
    name = "features",
    actual = "//src/integration/lib/src/main/java/se/tink/backend/aggregation/agents/payments",
    visibility = ["//src/agent_sdk/sdk:__subpackages__"],
)
