java_library(
    name = "nemid",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib",
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/nxgen/http/url",
        "//third_party:com_github_detro_ghostdriver_phantomjsdriver",
        "//third_party:com_google_guava_guava",
        "//third_party:org_seleniumhq_selenium_selenium_java",
        "@selenium//:org_seleniumhq_selenium_selenium_api",
        "@selenium//:org_seleniumhq_selenium_selenium_htmlunit_driver",
        "@selenium//:org_seleniumhq_selenium_selenium_remote_driver",
    ],
)
