java_library(
    name = "loader",
    srcs = glob(
        ["*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_google_inject_guice",
        "//third_party:org_reflections_reflections",
    ],
)
