package se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.manual;

public class LansforsakringarTestData {

    private LansforsakringarTestData() {}

    static final String TRANSACTIONS =
            "{\n"
                    + "\t\"id\": null,\n"
                    + "\t\"response\": {\n"
                    + "\t\t\"moreExists\": true,\n"
                    + "\t\t\"transactions\": [{\n"
                    + "\t\t\t\"id\": \"200309042-1516\",\n"
                    + "\t\t\t\"text\": \"Kortköp\",\n"
                    + "\t\t\t\"amount\": {\n"
                    + "\t\t\t\t\"currency\": \"SEK\",\n"
                    + "\t\t\t\t\"value\": -32.15\n"
                    + "\t\t\t},\n"
                    + "\t\t\t\"accountingDate\": \"2020-02-11\",\n"
                    + "\t\t\t\"transactionDate\": \"2020-02-10\",\n"
                    + "\t\t\t\"currencyDate\": \"2020-02-11\",\n"
                    + "\t\t\t\"unconstrainedText\": \"Amazon \",\n"
                    + "\t\t\t\"balance\": 690.97,\n"
                    + "\t\t\t\"marketingCode\": null,\n"
                    + "\t\t\t\"transactionType\": \"CAR\",\n"
                    + "\t\t\t\"upcomingDeposit\": false\n"
                    + "\t\t}]\n"
                    + "}, \n"
                    + "\"errors\": null\n"
                    + "}\n";

    static final String ACCOUNTS =
            "{\n"
                    + "\t\"mainAndCoAccounts\": [{\n"
                    + "\t\t\"accountNumber\": \"123456\",\n"
                    + "\t\t\"balance\": 1336.0,\n"
                    + "\t\t\"accountName\": \"Lägenhetskonto\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"CO_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90239056703\",\n"
                    + "\t\t\"balance\": 690.97,\n"
                    + "\t\t\"accountName\": \"Privat\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"654321\",\n"
                    + "\t\t\"balance\": 948.07,\n"
                    + "\t\t\"accountName\": \"Gemensamt\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"CO_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"444555\",\n"
                    + "\t\t\"balance\": 1000.0,\n"
                    + "\t\t\"accountName\": \"GemensamtSpar\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"111111112\",\n"
                    + "\t\t\"balance\": 10000.0,\n"
                    + "\t\t\"accountName\": \"Spar\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": {\n"
                    + "\t\t\t\"name\": \"Sparande\",\n"
                    + "\t\t\t\"accountNumber\": \"99999999\",\n"
                    + "\t\t\t\"savingsGoalId\": \"3c86b69d1e\",\n"
                    + "\t\t\t\"goalAmount\": 25000.0,\n"
                    + "\t\t\t\"completedInPercent\": 0.4,\n"
                    + "\t\t\t\"sequenceNumber\": null,\n"
                    + "\t\t\t\"estimatedCompletionDate\": null,\n"
                    + "\t\t\t\"goalDate\": \"2020-10-25\"\n"
                    + "\t\t},\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"SAVINGS\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": true,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}],\n"
                    + "\t\"dispositionAccounts\": [],\n"
                    + "\t\"cards\": [],\n"
                    + "\t\"errorMessages\": []\n"
                    + "}";

    static final String UPCOMING_TRANSACTIONS =
            "{\n"
                    + "\t\"upcomingTransactions\": [{\n"
                    + "\t\t\"id\": \"232455503-25\",\n"
                    + "\t\t\"description\": \"SKARPNÄCKS\",\n"
                    + "\t\t\"amount\": -1478.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"8888888888\",\n"
                    + "\t\t\t\"giroNumber\": \"964802-3\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-05-05.32.02.394767\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"232455857-25\",\n"
                    + "\t\t\"description\": \"ENERGIKUNDSERVICE SVERIGE\",\n"
                    + "\t\t\"amount\": -2235.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"99999999\",\n"
                    + "\t\t\t\"giroNumber\": \"4875503-7\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-05-06.30.12.796691\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"233161778-25\",\n"
                    + "\t\t\"description\": \"desc\",\n"
                    + "\t\t\"amount\": -429.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"5555555555\",\n"
                    + "\t\t\t\"giroNumber\": \"5361-1737\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-07-12.16.48.168365\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"221720580-25\",\n"
                    + "\t\t\"description\": \"TRÄNGSELSKATT\",\n"
                    + "\t\t\"amount\": -22.0,\n"
                    + "\t\t\"date\": \"2020-03-02\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"8888888889\",\n"
                    + "\t\t\t\"giroNumber\": \"282-4647\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-01-20-09.33.48.584961\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-03-02\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}],\n"
                    + "\t\"errorMessages\": [],\n"
                    + "\t\"sumOfUpcomingTransactions\": -4164.0,\n"
                    + "\t\"currentMonth\": {\n"
                    + "\t\t\"year\": \"2020\",\n"
                    + "\t\t\"month\": \"Februari\",\n"
                    + "\t\t\"sumUpcomingTransactions\": -4142.0,\n"
                    + "\t\t\"currentDate\": \"2020-02-13\"\n"
                    + "\t}\n"
                    + "}";

    static final String CARDS_LIST =
            "{\n"
                    + "\t\"cards\": [{\n"
                    + "\t\t\"cardName\": \"Bankkort Privat\",\n"
                    + "\t\t\"balance\": 0.0,\n"
                    + "\t\t\"cardNumber\": \"5758\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardTypeAsString\": \"DEBIT\",\n"
                    + "\t\t\"connectedAccountNumber\": \"90239056703\",\n"
                    + "\t\t\"cardLimit\": 0.0,\n"
                    + "\t\t\"cardAvailable\": 0.0,\n"
                    + "\t\t\"expires\": \"08/21\",\n"
                    + "\t\t\"reservedAmount\": 0.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"2\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": {\n"
                    + "\t\t\t\"accountNumber\": \"12321321\",\n"
                    + "\t\t\t\"balance\": 690.97,\n"
                    + "\t\t\t\"accountName\": \"Privat\",\n"
                    + "\t\t\t\"productCode\": \"11\",\n"
                    + "\t\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\t\"youthAccount\": false,\n"
                    + "\t\t\t\"transferFrom\": true,\n"
                    + "\t\t\t\"transferTo\": true,\n"
                    + "\t\t\t\"type\": \"CHECKING\"\n"
                    + "\t\t},\n"
                    + "\t\t\"accountDetailsAvailable\": true\n"
                    + "\t}, {\n"
                    + "\t\t\"cardName\": \"Bankkort Privat\",\n"
                    + "\t\t\"balance\": 0.0,\n"
                    + "\t\t\"cardNumber\": \"8778\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardTypeAsString\": \"CREDIT\",\n"
                    + "\t\t\"connectedAccountNumber\": \"777777\",\n"
                    + "\t\t\"cardLimit\": 0.0,\n"
                    + "\t\t\"cardAvailable\": 0.0,\n"
                    + "\t\t\"expires\": \"08/21\",\n"
                    + "\t\t\"reservedAmount\": 0.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"2\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": {\n"
                    + "\t\t\t\"accountNumber\": \"99000099\",\n"
                    + "\t\t\t\"balance\": 948.07,\n"
                    + "\t\t\t\"accountName\": \"Gemensamt\",\n"
                    + "\t\t\t\"productCode\": \"11\",\n"
                    + "\t\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\t\"youthAccount\": false,\n"
                    + "\t\t\t\"transferFrom\": true,\n"
                    + "\t\t\t\"transferTo\": true,\n"
                    + "\t\t\t\"type\": \"CHECKING\"\n"
                    + "\t\t},\n"
                    + "\t\t\"accountDetailsAvailable\": true\n"
                    + "\t}]\n"
                    + "}";

    static final String PENSION_OVERVIEW =
            "{\n"
                    + "\t\"ipsPensionsResponseModel\": {\n"
                    + "\t\t\"ipsPensions\": [],\n"
                    + "\t\t\"error\": null\n"
                    + "\t},\n"
                    + "\t\"livPensionsResponseModel\": {\n"
                    + "\t\t\"privatePensions\": [],\n"
                    + "\t\t\"occupationalPensions\": [{\n"
                    + "\t\t\t\"name\": \"Ålderspension Fond\",\n"
                    + "\t\t\t\"agreementId\": \"1234_1\",\n"
                    + "\t\t\t\"value\": 33333.62,\n"
                    + "\t\t\t\"hasDetails\": true,\n"
                    + "\t\t\t\"footNotes\": []\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"name\": \"Ålderspension Fond\",\n"
                    + "\t\t\t\"agreementId\": \"3424332_1\",\n"
                    + "\t\t\t\"value\": 1234.35,\n"
                    + "\t\t\t\"hasDetails\": true,\n"
                    + "\t\t\t\"footNotes\": []\n"
                    + "\t\t}],\n"
                    + "\t\t\"capitalInsurances\": [],\n"
                    + "\t\t\"error\": null\n"
                    + "\t},\n"
                    + "\t\"footNotes\": {},\n"
                    + "\t\"totalValue\": 298642.97\n"
                    + "}";

    static final String PENSION_ENGAGEMENTS =
            "{\n"
                    + "\t\"id\": null,\n"
                    + "\t\"response\": {\n"
                    + "\t\t\"hasSavingEngagement\": null,\n"
                    + "\t\t\"hasProtectionEngagement\": null,\n"
                    + "\t\t\"engagements\": [{\n"
                    + "\t\t\t\"name\": \"First Lastname\",\n"
                    + "\t\t\t\"productName\": \"Tjänstepensionsplan\",\n"
                    + "\t\t\t\"id\": \"866777\",\n"
                    + "\t\t\t\"type\": \"AGREEMENT\",\n"
                    + "\t\t\t\"riskCovers\": [\"DEATH\"],\n"
                    + "\t\t\t\"status\": \"PAID_UP\",\n"
                    + "\t\t\t\"investmentValue\": 217527.62,\n"
                    + "\t\t\t\"agreedPremium\": null,\n"
                    + "\t\t\t\"premiumModelTerm\": null,\n"
                    + "\t\t\t\"owner\": \"Someorg AB\",\n"
                    + "\t\t\t\"ownerId\": \"165565883278\",\n"
                    + "\t\t\t\"productType\": \"PENSION_PLAN\",\n"
                    + "\t\t\t\"productCategory\": \"OCCUPATIONAL_PENSION\",\n"
                    + "\t\t\t\"hasDetail\": true\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"name\": \"First Lastname\",\n"
                    + "\t\t\t\"productName\": \"Löneväxling\",\n"
                    + "\t\t\t\"id\": \"34985d\",\n"
                    + "\t\t\t\"type\": \"AGREEMENT\",\n"
                    + "\t\t\t\"riskCovers\": [\"DEATH\"],\n"
                    + "\t\t\t\"status\": \"PAID_UP\",\n"
                    + "\t\t\t\"investmentValue\": 81115.35,\n"
                    + "\t\t\t\"agreedPremium\": null,\n"
                    + "\t\t\t\"premiumModelTerm\": null,\n"
                    + "\t\t\t\"owner\": \"Starcounter AB\",\n"
                    + "\t\t\t\"ownerId\": \"165565883278\",\n"
                    + "\t\t\t\"productType\": \"PENSION_PLAN\",\n"
                    + "\t\t\t\"productCategory\": \"OCCUPATIONAL_PENSION\",\n"
                    + "\t\t\t\"hasDetail\": true\n"
                    + "\t\t}],\n"
                    + "\t\t\"livSystemOpen\": true\n"
                    + "\t},\n"
                    + "\t\"errors\": null\n"
                    + "}";

    static final String MORTGAGE_LOAN_WITH_CO_APPLICANT =
            "{\n"
                    + "\t\"loanName\": \"Bolån Hypotek\",\n"
                    + "\t\"loanNumber\": \"1.2.3.4.5\",\n"
                    + "\t\"originalDebt\": \"250 000,00\",\n"
                    + "\t\"currentDebt\": \"250 000,00\",\n"
                    + "\t\"currentInterestRate\": \"1,60 %\",\n"
                    + "\t\"rateBoundUntil\": \"2020-06-30\",\n"
                    + "\t\"rateBindingPeriodLength\": \"3 år\",\n"
                    + "\t\"borrowers\": [{\n"
                    + "\t\t\"name\": \"someone\",\n"
                    + "\t\t\"debtOwnershipShare\": \"50,00 %\",\n"
                    + "\t\t\"interestRateOwnershipShare\": \"50,00 %\"\n"
                    + "\t}, {\n"
                    + "\t\t\"name\": \"someones parnter\",\n"
                    + "\t\t\"debtOwnershipShare\": \"50,00 %\",\n"
                    + "\t\t\"interestRateOwnershipShare\": \"50,00 %\"\n"
                    + "\t}],\n"
                    + "\t\"securities\": [{\n"
                    + "\t\t\"securityText\": \"STOCKHOLM\",\n"
                    + "\t\t\"securityType\": \"Nyttjanderätt\"\n"
                    + "\t}],\n"
                    + "\t\"fixedRate\": true,\n"
                    + "\t\"modificationStatus\": \"NONE\",\n"
                    + "\t\"infoText\": null,\n"
                    + "\t\"nearExpiryDate\": false,\n"
                    + "\t\"bindingPeriodInfoModel\": null\n"
                    + "}";

    static final String INVOICE_REQUEST =
            "{\n"
                    + "\t\"responseControl\": {\n"
                    + "\t\t\"profile\": {\n"
                    + "\t\t\t\"profileType\": \"CUSTOMER\",\n"
                    + "\t\t\t\"customerId\": \"123456789\"\n"
                    + "\t\t},\n"
                    + "\t\t\"filter\": {\n"
                    + "\t\t\t\"includes\": [{\n"
                    + "\t\t\t\t\"invoiceType\": \"DEBIT\",\n"
                    + "\t\t\t\t\"eInvoiceStatuses\": [\"NEW\"],\n"
                    + "\t\t\t\t\"paymentType\": \"MANUAL_EINVOICE\"\n"
                    + "\t\t\t}]\n"
                    + "\t\t},\n"
                    + "\t\t\"pager\": {\n"
                    + "\t\t\t\"startIndex\": 0,\n"
                    + "\t\t\t\"size\": 20\n"
                    + "\t\t}\n"
                    + "\t},\n"
                    + "\t\"customerId\": \"123456789\"\n"
                    + "}";

    static final String CREDIT_CARD_LIST =
            "{\n"
                    + "\t\"cards\": [{\n"
                    + "\t\t\"cardName\": \"Bankkort Privat\",\n"
                    + "\t\t\"balance\": 0.0,\n"
                    + "\t\t\"cardNumber\": \"0702\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardType\": \"BANK_CARD_PRIVATE\",\n"
                    + "\t\t\"connectedAccountNumber\": \"91111118\",\n"
                    + "\t\t\"cardLimit\": 0.0,\n"
                    + "\t\t\"cardAvailable\": 0.0,\n"
                    + "\t\t\"expires\": \"02/21\",\n"
                    + "\t\t\"reservedAmount\": 0.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"1\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": {\n"
                    + "\t\t\t\"accountNumber\": \"91111118\",\n"
                    + "\t\t\t\"balance\": 9252.97,\n"
                    + "\t\t\t\"accountName\": \"Privatkonto\",\n"
                    + "\t\t\t\"productCode\": \"11\",\n"
                    + "\t\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\t\"youthAccount\": false,\n"
                    + "\t\t\t\"transferFrom\": true,\n"
                    + "\t\t\t\"transferTo\": true,\n"
                    + "\t\t\t\"type\": \"CHECKING\"\n"
                    + "\t\t},\n"
                    + "\t\t\"embossedName\": \"Someone\",\n"
                    + "\t\t\"issuingNetwork\": \"VISA\",\n"
                    + "\t\t\"productName\": \"Bankkort Privat\",\n"
                    + "\t\t\"enriched\": true,\n"
                    + "\t\t\"accountDetailsAvailable\": true\n"
                    + "\t}, {\n"
                    + "\t\t\"cardName\": \"Kreditkort Privat\",\n"
                    + "\t\t\"balance\": 3824.7,\n"
                    + "\t\t\"cardNumber\": \"6226\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardType\": \"CREDIT_CARD_PRIVATE\",\n"
                    + "\t\t\"connectedAccountNumber\": null,\n"
                    + "\t\t\"cardLimit\": 50000.0,\n"
                    + "\t\t\"cardAvailable\": 46175.3,\n"
                    + "\t\t\"expires\": \"03/23\",\n"
                    + "\t\t\"reservedAmount\": 1023.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"1\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": null,\n"
                    + "\t\t\"embossedName\": \"someone\",\n"
                    + "\t\t\"issuingNetwork\": \"VISA\",\n"
                    + "\t\t\"productName\": \"Kreditkort Privat\",\n"
                    + "\t\t\"enriched\": true,\n"
                    + "\t\t\"accountDetailsAvailable\": false\n"
                    + "\t}]\n"
                    + "}";

    static final String CARD_TRANSACTIONS =
            "{\n"
                    + "\t\"transactions\": [{\n"
                    + "\t\t\"date\": 1585705999999,\n"
                    + "\t\t\"text\": \"NETONNET\",\n"
                    + "\t\t\"amountHolderCurrency\": 1023.0,\n"
                    + "\t\t\"merchant\": \"NETONNET\",\n"
                    + "\t\t\"debitDate\": 1588197600000,\n"
                    + "\t\t\"definitive\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"date\": 1585350000000,\n"
                    + "\t\t\"text\": \"NETONNET\",\n"
                    + "\t\t\"amountHolderCurrency\": 1599.0,\n"
                    + "\t\t\"merchant\": \"NETONNET\",\n"
                    + "\t\t\"debitDate\": 1588197600000,\n"
                    + "\t\t\"definitive\": true\n"
                    + "\t}, {\n"
                    + "\t\t\"date\": 1585350000000,\n"
                    + "\t\t\"text\": \"JYSK\",\n"
                    + "\t\t\"amountHolderCurrency\": 999.0,\n"
                    + "\t\t\"merchant\": \"JYSK\",\n"
                    + "\t\t\"debitDate\": 1588197600000,\n"
                    + "\t\t\"definitive\": true\n"
                    + "\t}, {\n"
                    + "\t\t\"date\": 1585090800000,\n"
                    + "\t\t\"text\": \"ICA\",\n"
                    + "\t\t\"amountHolderCurrency\": 203.7,\n"
                    + "\t\t\"merchant\": \"ICA\",\n"
                    + "\t\t\"debitDate\": 1588197600000,\n"
                    + "\t\t\"definitive\": true\n"
                    + "\t}],\n"
                    + "\t\"morePages\": false,\n"
                    + "\t\"announcedAmount\": 0.0\n"
                    + "}";
}
