alias(
    name = "client",
    actual = "//src/integration/agent_data_availability_tracker/client/src/main/java/se/tink/backend/integration/agent_data_availability_tracker/client",
    visibility = ["//visibility:public"],
)

alias(
    name = "serialization",
    actual = "//src/integration/agent_data_availability_tracker/client/src/main/java/se/tink/backend/integration/agent_data_availability_tracker/client/serialization",
    visibility = ["//visibility:public"],
)

alias(
    name = "client-test",
    actual = "//src/integration/agent_data_availability_tracker/client/src/test/java/se/tink/backend/integration/agent_data_availability_tracker/client:client-test",
)
