alias(
    name = "serialization",
    actual = "//src/integration/agent_data_availability_tracker/client/src/main/java/se/tink/backend/integration/agent_data_availability_tracker/serialization",
    visibility = ["//visibility:public"],
)
