package se.tink.libraries.creditsafe.consumermonitoring.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/** This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2 */
@WebServiceClient(
        name = "Monitoring",
        targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
        wsdlLocation = "https://webservice.creditsafe.se/ConsumerMonitoring/Monitoring.asmx?WSDL")
public class Monitoring extends Service {

    private static final URL MONITORING_WSDL_LOCATION;
    private static final WebServiceException MONITORING_EXCEPTION;
    private static final QName MONITORING_QNAME =
            new QName("https://webservice.creditsafe.se/ConsumerMonitoring/", "Monitoring");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                    new URL(
                            "https://webservice.creditsafe.se/ConsumerMonitoring/Monitoring.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MONITORING_WSDL_LOCATION = url;
        MONITORING_EXCEPTION = e;
    }

    public Monitoring() {
        super(__getWsdlLocation(), MONITORING_QNAME);
    }

    public Monitoring(WebServiceFeature... features) {
        super(__getWsdlLocation(), MONITORING_QNAME, features);
    }

    public Monitoring(URL wsdlLocation) {
        super(wsdlLocation, MONITORING_QNAME);
    }

    public Monitoring(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MONITORING_QNAME, features);
    }

    public Monitoring(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Monitoring(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /** @return returns MonitoringSoap */
    @WebEndpoint(name = "MonitoringSoap")
    public MonitoringSoap getMonitoringSoap() {
        return super.getPort(
                new QName("https://webservice.creditsafe.se/ConsumerMonitoring/", "MonitoringSoap"),
                MonitoringSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
     *     Supported features not in the <code>features</code> parameter will have their default
     *     values.
     * @return returns MonitoringSoap
     */
    @WebEndpoint(name = "MonitoringSoap")
    public MonitoringSoap getMonitoringSoap(WebServiceFeature... features) {
        return super.getPort(
                new QName("https://webservice.creditsafe.se/ConsumerMonitoring/", "MonitoringSoap"),
                MonitoringSoap.class,
                features);
    }

    private static URL __getWsdlLocation() {
        if (MONITORING_EXCEPTION != null) {
            throw MONITORING_EXCEPTION;
        }
        return MONITORING_WSDL_LOCATION;
    }
}
