package se.tink.libraries.creditsafe.consumermonitoring.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/** This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2 */
@WebService(
        name = "MonitoringSoap",
        targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
@XmlSeeAlso({ObjectFactory.class})
public interface MonitoringSoap {

    /**
     * @param objPortfolioInfo
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "CreatePortfolio",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/CreatePortfolio")
    @WebResult(
            name = "CreatePortfolioResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "CreatePortfolio",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.CreatePortfolio")
    @ResponseWrapper(
            localName = "CreatePortfolioResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.CreatePortfolioResponse")
    public MonitoringResponse createPortfolio(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq,
            @WebParam(
                            name = "objPortfolioInfo",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    PortfolioInfoObject objPortfolioInfo);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "ChangeStdPortfolio",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/ChangeStdPortfolio")
    @WebResult(
            name = "ChangeStdPortfolioResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "ChangeStdPortfolio",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.ChangeStdPortfolio")
    @ResponseWrapper(
            localName = "ChangeStdPortfolioResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.ChangeStdPortfolioResponse")
    public MonitoringResponse changeStdPortfolio(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param objPortfolioInfo
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "UpdatePortfolio",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/UpdatePortfolio")
    @WebResult(
            name = "UpdatePortfolioResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "UpdatePortfolio",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.UpdatePortfolio")
    @ResponseWrapper(
            localName = "UpdatePortfolioResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.UpdatePortfolioResponse")
    public MonitoringResponse updatePortfolio(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq,
            @WebParam(
                            name = "objPortfolioInfo",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    PortfolioInfoObject objPortfolioInfo);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "GetPortfolioEmailFilters",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/GetPortfolioEmailFilters")
    @WebResult(
            name = "GetPortfolioEmailFiltersResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "GetPortfolioEmailFilters",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.GetPortfolioEmailFilters")
    @ResponseWrapper(
            localName = "GetPortfolioEmailFiltersResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.GetPortfolioEmailFiltersResponse")
    public MonitoringResponse getPortfolioEmailFilters(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @param filters
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "SavePortfolioEmailFilters",
            action =
                    "https://webservice.creditsafe.se/ConsumerMonitoring/SavePortfolioEmailFilters")
    @WebResult(
            name = "SavePortfolioEmailFiltersResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "SavePortfolioEmailFilters",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.SavePortfolioEmailFilters")
    @ResponseWrapper(
            localName = "SavePortfolioEmailFiltersResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.SavePortfolioEmailFiltersResponse")
    public MonitoringResponse savePortfolioEmailFilters(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq,
            @WebParam(
                            name = "filters",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    ArrayOfEmailFilterObject filters);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "AddPortfolioEmail",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/AddPortfolioEmail")
    @WebResult(
            name = "AddPortfolioEmailResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "AddPortfolioEmail",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.AddPortfolioEmail")
    @ResponseWrapper(
            localName = "AddPortfolioEmailResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.AddPortfolioEmailResponse")
    public MonitoringResponse addPortfolioEmail(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "RemovePortfolioEmail",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/RemovePortfolioEmail")
    @WebResult(
            name = "RemovePortfolioEmailResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "RemovePortfolioEmail",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.RemovePortfolioEmail")
    @ResponseWrapper(
            localName = "RemovePortfolioEmailResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.RemovePortfolioEmailResponse")
    public MonitoringResponse removePortfolioEmail(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "RemovePortfolio",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/RemovePortfolio")
    @WebResult(
            name = "RemovePortfolioResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "RemovePortfolio",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.RemovePortfolio")
    @ResponseWrapper(
            localName = "RemovePortfolioResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.RemovePortfolioResponse")
    public MonitoringResponse removePortfolio(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "GetPortfolioInformation",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/GetPortfolioInformation")
    @WebResult(
            name = "GetPortfolioInformationResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "GetPortfolioInformation",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.GetPortfolioInformation")
    @ResponseWrapper(
            localName = "GetPortfolioInformationResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.GetPortfolioInformationResponse")
    public MonitoringResponse getPortfolioInformation(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "GetPortfolioList",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/GetPortfolioList")
    @WebResult(
            name = "GetPortfolioListResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "GetPortfolioList",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.GetPortfolioList")
    @ResponseWrapper(
            localName = "GetPortfolioListResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.GetPortfolioListResponse")
    public MonitoringResponse getPortfolioList(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "MonitorConsumer",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/MonitorConsumer")
    @WebResult(
            name = "MonitorConsumerResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "MonitorConsumer",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.MonitorConsumer")
    @ResponseWrapper(
            localName = "MonitorConsumerResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.MonitorConsumerResponse")
    public MonitoringResponse monitorConsumer(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "GetChangedConsumers",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/GetChangedConsumers")
    @WebResult(
            name = "GetChangedConsumersResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "GetChangedConsumers",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.GetChangedConsumers")
    @ResponseWrapper(
            localName = "GetChangedConsumersResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.GetChangedConsumersResponse")
    public MonitoringResponse getChangedConsumers(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "GetMonitoredConsumers",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/GetMonitoredConsumers")
    @WebResult(
            name = "GetMonitoredConsumersResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "GetMonitoredConsumers",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.GetMonitoredConsumers")
    @ResponseWrapper(
            localName = "GetMonitoredConsumersResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.GetMonitoredConsumersResponse")
    public MonitoringResponse getMonitoredConsumers(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "RemoveConsumer",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/RemoveConsumer")
    @WebResult(
            name = "RemoveConsumerResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "RemoveConsumer",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.RemoveConsumer")
    @ResponseWrapper(
            localName = "RemoveConsumerResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.RemoveConsumerResponse")
    public MonitoringResponse removeConsumer(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "GetRemovedConsumers",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/GetRemovedConsumers")
    @WebResult(
            name = "GetRemovedConsumersResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "GetRemovedConsumers",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.GetRemovedConsumers")
    @ResponseWrapper(
            localName = "GetRemovedConsumersResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.GetRemovedConsumersResponse")
    public MonitoringResponse getRemovedConsumers(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "ReactivateConsumer",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/ReactivateConsumer")
    @WebResult(
            name = "ReactivateConsumerResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "ReactivateConsumer",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.ReactivateConsumer")
    @ResponseWrapper(
            localName = "ReactivateConsumerResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className =
                    "https.webservice_creditsafe_se.consumermonitoring.ReactivateConsumerResponse")
    public MonitoringResponse reactivateConsumer(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "MoveConsumer",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/MoveConsumer")
    @WebResult(
            name = "MoveConsumerResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "MoveConsumer",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.MoveConsumer")
    @ResponseWrapper(
            localName = "MoveConsumerResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.MoveConsumerResponse")
    public MonitoringResponse moveConsumer(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);

    /**
     * @param monReq
     * @return returns https.webservice_creditsafe_se.consumermonitoring.MonitoringResponse
     */
    @WebMethod(
            operationName = "CopyConsumer",
            action = "https://webservice.creditsafe.se/ConsumerMonitoring/CopyConsumer")
    @WebResult(
            name = "CopyConsumerResult",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/")
    @RequestWrapper(
            localName = "CopyConsumer",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.CopyConsumer")
    @ResponseWrapper(
            localName = "CopyConsumerResponse",
            targetNamespace = "https://webservice.creditsafe.se/ConsumerMonitoring/",
            className = "https.webservice_creditsafe_se.consumermonitoring.CopyConsumerResponse")
    public MonitoringResponse copyConsumer(
            @WebParam(
                            name = "mon_req",
                            targetNamespace =
                                    "https://webservice.creditsafe.se/ConsumerMonitoring/")
                    MonitoringRequest monReq);
}
