apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-safe
  namespace: credit-safe
  labels:
    app: credit-safe-service
spec:
  replicas: {{ default "2" .Values.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: credit-safe-service
  template:
    metadata:
      labels:
        app: credit-safe-service
      annotations:
        # Force rollout of new pods if the config has changed
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        prometheus.io/port: '9130'
        prometheus.io/scrape: 'true'
    spec:
      initContainers:
      # Script to replace placeholder passwords with the real passwords
      - name: add-secrets-to-config
        command:
          - "bash"
          - "-c"
          - "cp /mnt/config-volume/* /mnt/altered-config-volume && \
             sed -i \"s/KEYSTORE_PASSWORD/$KEYSTORE_PWD/g\" /mnt/altered-config-volume/credit-safe-server.yml && \
             sed -i \"s/SYSTEM_ACCESS_TOKEN/$SYSTEM_TOKEN/g\" /mnt/altered-config-volume/credit-safe-server.yml"
        image: gcr.io/tink-containers/debian:stretch
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/config-volume
        - name: altered-config-volume
          mountPath: /mnt/altered-config-volume
        env:
        - name: KEYSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: credit-safe-secrets
              key: keystore-password
        - name: SYSTEM_TOKEN
          valueFrom:
            secretKeyRef:
              name: credit-safe-secrets
              key: system-access-token
      containers:
      - name: tink-backend-credit-safe
        resources:
          requests:
            memory: {{ default "700Mi" .Values.podMemoryRequest }}
            cpu: {{ default "500m" .Values.podCpuRequest }}
          limits:
            memory: {{ default "1Gi" .Values.podMemoryLimit }}
            cpu: {{ default "1000m" .Values.podCpuLimit }}

        image: gcr.io/tink-containers/tink-backend-credit-safe:{{ .Files.Get "tink-versions/tink-backend-credit-safe.txt" | default "latest" }}
        imagePullPolicy: IfNotPresent

        command:
        - "java"
        - "-jar"
        - "-Xmx{{ default "256m" .Values.heapSize }}"
        - "-XX:-OmitStackTraceInFastThrow"
        - "-Dnetworkaddress.cache.ttl=60"
        - "-XX:+ExitOnOutOfMemoryError"
        - "/usr/share/tink-backend-credit-safe/credit-safe-service.jar"
        - "server"
        - "/etc/tink/credit-safe-server.yml"

        ports:
        - name: https-api
          containerPort: 443
        {{- if .Values.insecureHttpServer }}
        - name: http-api
          containerPort: 80
        {{- end }}
        - name: metrics
          containerPort: 9130

      # add readiness/liveness probes
      volumes:
      - name: config-volume
        configMap:
          name: credit-safe-configuration
      # ConfigMaps are mounted as a read-only filesystem.
      # Before we can edit the config in rumtime we need to copy the files
      # to a fs with read-write permissions.
      - name: altered-config-volume
        emptyDir: {}
      imagePullSecrets:
        - name: tink-containers

{{- if eq "local" .Values.Cluster }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: credit-safe
{{ end }}
