apiVersion: v1
kind: Service
metadata:
  name: credit-safe-api
  namespace: credit-safe
spec:
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  {{- if .Values.insecureHttpServer }}
  - port: 80
    targetPort: http-api
    name: http-api
  {{- end }}
  selector:
    app: credit-safe-service

{{- /*
This condition is a bit ugly. But it is neccesary since booleans default to
"False" and there is currently no way to differentiate between a value that is
not set and a value that is explicitly set to false.
*/ -}}
{{ if not .Values.doNotCreateLoadBalancerService }}
---
apiVersion: v1
kind: Service
metadata:
  name: credit-safe-api-loadbalancer
  namespace: credit-safe
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: https-api
    name: https-api
  {{- if .Values.insecureHttpServer }}
  - port: 80
    targetPort: http-api
    name: http-api
  {{- end }}
  selector:
    app: credit-safe-service
{{ end }}
