java_library(
    name = "volksbank",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api",
        "//src/integration/lib",
        "//src/libraries/account_identifier",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "//src/libraries/date",
        "//src/libraries/strings",
        "@com_fasterxml_jackson_core_jackson_annotations//jar",
        "@com_fasterxml_jackson_core_jackson_core//jar",
        "@commons_codec_commons_codec//jar",
        "@org_jsoup_jsoup//jar",
    ],
)
