package se.tink.backend.aggregation.agents.nxgen.fr.openbanking.societegenerale.fetcher.card;

import org.junit.Ignore;
import se.tink.backend.aggregation.agents.nxgen.fr.openbanking.societegenerale.fetcher.transactionalaccount.rpc.AccountsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

@Ignore
public class SocieteGeneraleCreditCardFetcherTestData {

    static final AccountsResponse CARD_RESPONSE =
            SerializationUtils.deserializeFromString(
                    "{\n"
                            + "  \"accounts\": [\n"
                            + "    {\n"
                            + "      \"resourceId\": \"resourceId1\",\n"
                            + "      \"name\": \"CB Visa\",\n"
                            + "      \"details\": \"Carte à débit immédiat\",\n"
                            + "      \"linkedAccount\": \"linkedAccount\",\n"
                            + "      \"usage\": \"PRIV\",\n"
                            + "      \"cashAccountType\": \"CARD\",\n"
                            + "      \"balances\": [],\n"
                            + "      \"psuStatus\": \"Account Holder\",\n"
                            + "      \"_links\": {\n"
                            + "        \"balances\": {\n"
                            + "          \"href\": \"/accounts/resourceId1/balances\"\n"
                            + "        }\n"
                            + "      }\n"
                            + "    },\n"
                            + "    {\n"
                            + "      \"resourceId\": \"2314311342234234243\",\n"
                            + "      \"accountId\": {\n"
                            + "        \"other\": {\n"
                            + "          \"identification\": \"213123213123\",\n"
                            + "          \"schemeName\": \"CPAN\"\n"
                            + "        }\n"
                            + "      },\n"
                            + "      \"name\": \"CB Mastercard numéro **** **** **** prochaine imputation ****-**-**\",\n"
                            + "      \"details\": \"Carte à débit différé\",\n"
                            + "      \"linkedAccount\": \"9832749872938943875938\",\n"
                            + "      \"usage\": \"PRIV\",\n"
                            + "      \"cashAccountType\": \"CARD\",\n"
                            + "      \"balances\": [\n"
                            + "        {\n"
                            + "          \"name\": \"Paiements CB à venir débités le **/**/****\",\n"
                            + "          \"balanceAmount\": {\n"
                            + "            \"currency\": \"EUR\",\n"
                            + "            \"amount\": \"9.00\"\n"
                            + "          },\n"
                            + "          \"balanceType\": \"OTHR\",\n"
                            + "          \"referenceDate\": \"****-**-**\"\n"
                            + "        }\n"
                            + "      ],\n"
                            + "      \"psuStatus\": \"Account Holder\",\n"
                            + "      \"_links\": {\n"
                            + "        \"balances\": {\n"
                            + "          \"href\": \"/accounts/2314311342234234243/balances\"\n"
                            + "        },\n"
                            + "        \"transactions\": {\n"
                            + "          \"href\": \"/accounts/2314311342234234243/transactions\"\n"
                            + "        }\n"
                            + "      }\n"
                            + "    }\n"
                            + "  ],\n"
                            + "  \"_links\": {\n"
                            + "    \"self\": {\n"
                            + "      \"href\": \"/accounts\"\n"
                            + "    },\n"
                            + "    \"endUserIdentity\": {\n"
                            + "      \"href\": \"/end-user-identity\"\n"
                            + "    },\n"
                            + "    \"beneficiaries\": {\n"
                            + "      \"href\": \"/trusted-beneficiaries\"\n"
                            + "    }\n"
                            + "  }\n"
                            + "}",
                    AccountsResponse.class);
}
