package se.tink.backend.aggregation.agents.banks.sbab.client;

import com.sun.jersey.core.util.MultivaluedMapImpl;
import java.util.HashMap;
import java.util.List;
import org.junit.Test;
import se.tink.libraries.serialization.utils.SerializationUtils;
import se.tink.libraries.application.GenericApplication;
import se.tink.backend.serialization.TypeReferences;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Examples on how we built the mapping to consider when maintaining code.
 */
public class OpenSavingsAccountClientTest {
    private static final String APPLICATION_1 = "{"
            + "  \"applicationId\": \"9f9e6bfd-fc79-412f-bcaf-0156db8752fd\","
            + "  \"credentialsId\": \"38a5eb44-525e-45ac-a6b4-3c4c11f6cece\","
            + "  \"fieldGroups\": ["
            + "    {"
            + "      \"fields\": null,"
            + "      \"name\": \"applicants\","
            + "      \"subGroups\": ["
            + "        {"
            + "          \"fields\": {"
            + "            \"phone-number\": \"0701231234\","
            + "            \"postal-code\": \"11212\","
            + "            \"town\": \"Stockholm\","
            + "            \"street-address\": \"Gatan 1B\","
            + "            \"name\": \"Test Name\","
            + "            \"personal-number\": \"20121212-1212\","
            + "            \"email\": \"aa@aa.se\""
            + "          },"
            + "          \"name\": null,"
            + "          \"subGroups\": null"
            + "        }"
            + "      ]"
            + "    },"
            + "    {"
            + "      \"fields\": {"
            + "        \"sbab-savings-sources-reason-own-business-hairdresser-company-name\": null,"
            + "        \"sbab-persons-saving\": \"[\\\"persons-saving-me\\\",\\\"persons-saving-other\\\"]\","
            + "        \"sbab-savings-sources-reason-own-business-construction-company-registration-number\": \"Construction org number\","
            + "        \"sbab-savings-sources-reason-own-business-restaurant-company-registration-number\": null,"
            + "        \"sbab-savings-sources-reason-own-business-payment-company-name\": null,"
            + "        \"sbab-savings-sources-my-account-in-swedish-bank\": \"[\\\"handelsbanken\\\",\\\"nordea\\\",\\\"seb\\\",\\\"danske-bank\\\",\\\"other\\\"]\","
            + "        \"sbab-persons-saving-other-value\": \"Other person saving\","
            + "        \"sbab-savings-frequency\": \"one-to-five-times-a-month\","
            + "        \"sbab-savings-sources-reason-own-business-other-value\": null,"
            + "        \"sbab-savings-sources-reason-own-business\": \"industry-construction\","
            + "        \"sbab-savings-sources-other-way-value\": \"Other source than swedish\","
            + "        \"sbab-savings-sources-reason-own-business-gaming-company-registration-number\": null,"
            + "        \"sbab-savings-purpose\": \"[\\\"purpose-operating-costs-of-my-residence\\\",\\\"purpose-financial-buffer\\\",\\\"purpose-ongoing-expenses\\\",\\\"purpose-saving-for-related-parties\\\",\\\"other\\\"]\","
            + "        \"sbab-initial-deposit\": \"between-50000-and-150000\","
            + "        \"sbab-savings-sources-reason-own-business-weapon-company-name\": null,"
            + "        \"sbab-savings-sources-my-account-in-swedish-bank-other-value\": \"Other swedish bank\","
            + "        \"sbab-savings-sources\": \"[\\\"my-account-in-swedish-bank\\\",\\\"other-way\\\"]\","
            + "        \"sbab-savings-sources-reason-own-business-gaming-company-name\": null,"
            + "        \"sbab-savings-sources-reason-other-value\": \"Other source reason\","
            + "        \"sbab-savings-sources-reason-own-business-construction-company-name\": \"Construction name\","
            + "        \"sbab-savings-sources-reason\": \"[\\\"own-business-or-dividend\\\",\\\"other-savings\\\",\\\"sale-of-assets\\\",\\\"gift-or-inheritance\\\",\\\"other\\\"]\","
            + "        \"sbab-money-withdrawal\": \"one-to-five-times-a-month\","
            + "        \"sbab-savings-monthly-income\": \"between-20000-and-35000\","
            + "        \"is-pep\": \"no\","
            + "        \"sbab-savings-sources-reason-own-business-weapon-company-registration-number\": null,"
            + "        \"sbab-savings-sources-reason-own-business-restaurant-company-name\": null,"
            + "        \"sbab-savings-amount-per-month\": \"between-10000-and-20000\","
            + "        \"sbab-savings-sources-reason-own-business-payment-company-registration-number\": null,"
            + "        \"sbab-savings-purpose-other-value\": \"Other purpose\","
            + "        \"sbab-savings-sources-reason-own-business-hairdresser-company-registration-number\": null"
            + "      },"
            + "      \"name\": \"know-your-customer\","
            + "      \"subGroups\": ["
            + "        {"
            + "          \"fields\": null,"
            + "          \"name\": \"citizenships\","
            + "          \"subGroups\": ["
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"se\""
            + "              },"
            + "              \"name\": \"citizenship\","
            + "              \"subGroups\": null"
            + "            },"
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"af\""
            + "              },"
            + "              \"name\": \"citizenship\","
            + "              \"subGroups\": null"
            + "            },"
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"al\""
            + "              },"
            + "              \"name\": \"citizenship\","
            + "              \"subGroups\": null"
            + "            }"
            + "          ]"
            + "        },"
            + "        {"
            + "          \"fields\": null,"
            + "          \"name\": \"residence-for-tax-purposes\","
            + "          \"subGroups\": ["
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"se\""
            + "              },"
            + "              \"name\": null,"
            + "              \"subGroups\": null"
            + "            },"
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"af\","
            + "                \"taxpayer-identification-number\": \"111222\""
            + "              },"
            + "              \"name\": null,"
            + "              \"subGroups\": null"
            + "            },"
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"al\","
            + "                \"taxpayer-identification-number\": \"222333\""
            + "              },"
            + "              \"name\": null,"
            + "              \"subGroups\": null"
            + "            }"
            + "          ]"
            + "        }"
            + "      ]"
            + "    },"
            + "    {"
            + "      \"fields\": null,"
            + "      \"name\": \"withdrawal-account\","
            + "      \"subGroups\": null"
            + "    }"
            + "  ],"
            + "  \"personalNumber\": \"201212121212\","
            + "  \"productId\": \"a0c0fec9-1079-438c-92c5-37e7cc65fe6c\","
            + "  \"type\": \"open-savings-account\","
            + "  \"userId\": \"d3b347b1-9711-475e-a11a-b691777c072b\","
            + "  \"remoteIp\": null"
            + "}";

    @Test
    public void createInformationRequestBody_application1() {
        GenericApplication application = SerializationUtils
                .deserializeFromString(APPLICATION_1, GenericApplication.class);

        MultivaluedMapImpl informationRequest = OpenSavingsAccountClient.createInformationRequestBody(application);

        HashMap<String, List<String>> expected = SerializationUtils.deserializeFromString("{"
                + "\"svar['111_111']\":[\"162\"],"
                + "\"svar['111_112']\":[\"1\"],"
                + "\"svar['111_113']\":[\"2\"],"
                + "\"svar['111_114']\":[\"2\"],"
                + "\"svar['111_116']\":[\"2\"],"
                + "\"svar['151_151']\":[\"174\"],"
                + "\"svar['151_152']\":[\"1\"],"
                + "\"svar['151_158_1_fritext']\":[\"111222\"],"
                + "\"svar['151_158']\":[\"1\"],"
                + "\"svar['151_153']\":[\"2\"],"
                + "\"svar['151_159_1_fritext']\":[\"222333\"],"
                + "\"svar['151_159']\":[\"1\"],"
                + "\"svar['200_200_2']\":[\"on\"],"
                + "\"svar['200_200_3']\":[\"on\"],"
                + "\"svar['200_200_4']\":[\"on\"],"
                + "\"svar['200_200_5']\":[\"on\"],"
                + "\"svar['200_200_6']\":[\"on\"],"
                + "\"svar['200_200_6_fritext']\":[\"Other purpose\"],"
                + "\"svar['200_201_5']\":[\"on\"],"
                + "\"svar['200_202']\":[\"10\"],"
                + "\"svar['200_203_1_fritext']\":[\"Construction name\"],"
                + "\"svar['200_203']\":[\"1\"],"
                + "\"svar['200_204_1_fritext']\":[\"Construction org number\"],"
                + "\"svar['200_204']\":[\"1\"],"
                + "\"svar['200_201_2']\":[\"on\"],"
                + "\"svar['200_201_3']\":[\"on\"],"
                + "\"svar['200_201_4']\":[\"on\"],"
                + "\"svar['200_201_6']\":[\"on\"],"
                + "\"svar['200_201_6_fritext']\":[\"Other source reason\"],"
                + "\"svar['200_205']\":[\"2\"],"
                + "\"svar['200_206']\":[\"2\"],"
                + "\"svar['200_207']\":[\"2\"],"
                + "\"svar['200_208_1']\":[\"on\"],"
                + "\"svar['200_208_2']\":[\"on\"],"
                + "\"svar['200_208_2_fritext']\":[\"Other person saving\"],"
                + "\"svar['200_209_1']\":[\"on\"],"
                + "\"svar['200_210_2']\":[\"on\"],"
                + "\"svar['200_210_3']\":[\"on\"],"
                + "\"svar['200_210_4']\":[\"on\"],"
                + "\"svar['200_210_5']\":[\"on\"],"
                + "\"svar['200_210_6']\":[\"on\"],"
                + "\"svar['200_210_6_fritext']\":[\"Other swedish bank\"],"
                + "\"svar['200_209_2']\":[\"on\"],"
                + "\"svar['200_209_2_fritext']\":[\"Other source than swedish\"],"
                + "\"svar['200_211']\":[\"2\"]"
                + "}", TypeReferences.MAP_OF_STRING_LIST_STRING);

        for (String key : informationRequest.keySet()) {
            assertThat(informationRequest.get(key)).isEqualTo(expected.get(key));
        }

        for (String key : expected.keySet()) {
            assertThat(informationRequest.get(key)).isEqualTo(expected.get(key));
        }

        assertThat(informationRequest).isEqualTo(expected);
    }

    private static final String APPLICATION_2 = "{"
            + "  \"applicationId\": \"9f9e6bfd-fc79-412f-bcaf-0156db8752fd\","
            + "  \"credentialsId\": \"38a5eb44-525e-45ac-a6b4-3c4c11f6cece\","
            + "  \"fieldGroups\": ["
            + "    {"
            + "      \"fields\": null,"
            + "      \"name\": \"applicants\","
            + "      \"subGroups\": ["
            + "        {"
            + "          \"fields\": {"
            + "            \"phone-number\": \"0701231234\","
            + "            \"postal-code\": \"11212\","
            + "            \"town\": \"Stockholm\","
            + "            \"street-address\": \"Gatan 1B\","
            + "            \"name\": \"Test Name\","
            + "            \"personal-number\": \"20121212-1212\","
            + "            \"email\": \"aa@aa.se\""
            + "          },"
            + "          \"name\": null,"
            + "          \"subGroups\": null"
            + "        }"
            + "      ]"
            + "    },"
            + "    {"
            + "      \"fields\": {"
            + "        \"sbab-savings-sources-reason-own-business-hairdresser-company-name\": null,"
            + "        \"sbab-persons-saving\": \"[\\\"persons-saving-me\\\"]\","
            + "        \"sbab-savings-sources-reason-own-business-construction-company-registration-number\": null,"
            + "        \"sbab-savings-sources-reason-own-business-restaurant-company-registration-number\": null,"
            + "        \"sbab-savings-sources-reason-own-business-payment-company-name\": null,"
            + "        \"sbab-savings-sources-my-account-in-swedish-bank\": null,"
            + "        \"sbab-persons-saving-other-value\": null,"
            + "        \"sbab-savings-frequency\": \"one-to-five-times-a-month\","
            + "        \"sbab-savings-sources-reason-own-business-other-value\": \"Other own business\","
            + "        \"sbab-savings-sources-reason-own-business\": \"other\","
            + "        \"sbab-savings-sources-other-way-value\": \"Other source than swedish\","
            + "        \"sbab-savings-sources-reason-own-business-gaming-company-registration-number\": null,"
            + "        \"sbab-savings-purpose\": \"[\\\"purpose-operating-costs-of-my-residence\\\"]\","
            + "        \"sbab-initial-deposit\": \"between-50000-and-150000\","
            + "        \"sbab-savings-sources-reason-own-business-weapon-company-name\": null,"
            + "        \"sbab-savings-sources-my-account-in-swedish-bank-other-value\": null,"
            + "        \"sbab-savings-sources\": \"[\\\"other-way\\\"]\","
            + "        \"sbab-savings-sources-reason-own-business-gaming-company-name\": null,"
            + "        \"sbab-savings-sources-reason-other-value\": null,"
            + "        \"sbab-savings-sources-reason-own-business-construction-company-name\": null,"
            + "        \"sbab-savings-sources-reason\": \"[\\\"own-business-or-dividend\\\"]\","
            + "        \"sbab-money-withdrawal\": \"one-to-five-times-a-month\","
            + "        \"sbab-savings-monthly-income\": \"between-20000-and-35000\","
            + "        \"is-pep\": \"no\","
            + "        \"sbab-savings-sources-reason-own-business-weapon-company-registration-number\": null,"
            + "        \"sbab-savings-sources-reason-own-business-restaurant-company-name\": null,"
            + "        \"sbab-savings-amount-per-month\": \"between-10000-and-20000\","
            + "        \"sbab-savings-sources-reason-own-business-payment-company-registration-number\": null,"
            + "        \"sbab-savings-purpose-other-value\": null,"
            + "        \"sbab-savings-sources-reason-own-business-hairdresser-company-registration-number\": null"
            + "      },"
            + "      \"name\": \"know-your-customer\","
            + "      \"subGroups\": ["
            + "        {"
            + "          \"fields\": null,"
            + "          \"name\": \"citizenships\","
            + "          \"subGroups\": ["
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"se\""
            + "              },"
            + "              \"name\": \"citizenship\","
            + "              \"subGroups\": null"
            + "            }"
            + "          ]"
            + "        },"
            + "        {"
            + "          \"fields\": null,"
            + "          \"name\": \"residence-for-tax-purposes\","
            + "          \"subGroups\": ["
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"se\""
            + "              },"
            + "              \"name\": null,"
            + "              \"subGroups\": null"
            + "            },"
            + "            {"
            + "              \"fields\": {"
            + "                \"country-code\": \"us\","
            + "                \"taxpayer-identification-number\": \"111222121\""
            + "              },"
            + "              \"name\": \"citizenship\","
            + "              \"subGroups\": null"
            + "            }"
            + "          ]"
            + "        }"
            + "      ]"
            + "    },"
            + "    {"
            + "      \"fields\": null,"
            + "      \"name\": \"withdrawal-account\","
            + "      \"subGroups\": null"
            + "    }"
            + "  ],"
            + "  \"personalNumber\": \"201212121212\","
            + "  \"productId\": \"a0c0fec9-1079-438c-92c5-37e7cc65fe6c\","
            + "  \"type\": \"open-savings-account\","
            + "  \"userId\": \"d3b347b1-9711-475e-a11a-b691777c072b\","
            + "  \"remoteIp\": null"
            + "}";

    @Test
    public void createInformationRequestBody_application2() {
        GenericApplication application = SerializationUtils
                .deserializeFromString(APPLICATION_2, GenericApplication.class);

        MultivaluedMapImpl informationRequest = OpenSavingsAccountClient.createInformationRequestBody(application);

        assertThat(informationRequest).isEqualTo(SerializationUtils.deserializeFromString("{"
                + "\"svar['111_111']\":[\"162\"],"
                + "\"svar['111_112']\":[\"0\"],"
                + "\"svar['111_113']\":[\"0\"],"
                + "\"svar['111_114']\":[\"2\"],"
                + "\"svar['111_116']\":[\"2\"],"
                + "\"svar['151_151']\":[\"174\"],"
                + "\"svar['151_152']\":[\"198\"],"
                + "\"svar['151_153']\":[\"0\"],"
                + "\"svar['151_158']\":[\"1\"],"
                + "\"svar['151_158_1_fritext']\":[\"111222121\"],"
                + "\"svar['200_200_2']\":[\"on\"],"
                + "\"svar['200_201_5']\":[\"on\"],"
                + "\"svar['200_202']\":[\"13\"],"
                + "\"svar['200_202_13_fritext']\":[\"Other own business\"],"
                + "\"svar['200_205']\":[\"2\"],"
                + "\"svar['200_206']\":[\"2\"],"
                + "\"svar['200_207']\":[\"2\"],"
                + "\"svar['200_208_1']\":[\"on\"],"
                + "\"svar['200_209_2']\":[\"on\"],"
                + "\"svar['200_209_2_fritext']\":[\"Other source than swedish\"],"
                + "\"svar['200_211']\":[\"2\"]"
                + "}", TypeReferences.MAP_OF_STRING_LIST_STRING));
    }
}
