#!/bin/bash
set -xe

if [ "$BUILDKITE_PIPELINE_SLUG" = "build-tink-backend" ]; then
    # Needed to merge target branch and for commit tagging
    export GIT_AUTHOR_NAME=Buildkite
    export GIT_AUTHOR_EMAIL=buildkite@tink.se
    export GIT_COMMITTER_NAME=Buildkite
    export GIT_COMMITTER_EMAIL=buildkite@tink.se

    if [ "$BUILDKITE_PULL_REQUEST" != false ]; then
        git fetch origin master
        git merge --no-commit origin/master
        git submodule update
        git status
    fi
fi
