alias(
    name = "core",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/core:core",
    visibility = ["//visibility:public"],
)

alias(
    name = "collection",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/collection:collection",
    visibility = ["//visibility:public"],
)

alias(
    name = "configuration",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/configuration:configuration",
    visibility = ["//visibility:public"],
)

alias(
    name = "logbackappender",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/logbackappender:logbackappender",
    visibility = ["//visibility:public"],
)

alias(
    name = "monitor",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/monitor:monitor",
    visibility = ["//visibility:public"],
)

alias(
    name = "prometheus",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/prometheus:prometheus",
    visibility = ["//visibility:public"],
)

alias(
    name = "registry",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/registry:registry",
    visibility = ["//visibility:public"],
)

alias(
    name = "counters",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/types/counters:counters",
    visibility = ["//visibility:public"],
)

alias(
    name = "gauges",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/types/gauges:gauges",
    visibility = ["//visibility:public"],
)

alias(
    name = "histograms",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/types/histograms:histograms",
    visibility = ["//visibility:public"],
)

alias(
    name = "other",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/types/other:other",
    visibility = ["//visibility:public"],
)

alias(
    name = "timers",
    actual = "@tink_backend//src/libraries/metrics/core/src/main/java/se/tink/libraries/metrics/types/timers:timers",
    visibility = ["//visibility:public"],
)
