load("@tink_backend//tools/bzl:junit_strict.bzl", "junit_test")

java_library(
    name = "annotation",
    srcs = glob(["*.java"]),
    data = [
    ],
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
        "//third_party:javax_inject_javax_inject",
    ],
)
