kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-de
  namespace: agents
spec:
  rules:

  - alert: login_success_rate_between_70_and_80_de
    expr: 0.7 <= sum:DE:action_className:all_manual_attempts:not_failed:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.8
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is between 70 - 80% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes..
      tags: {{ .Values.tags }}

  - alert: login_success_rate_between_60_and_70_de
    expr: 0.6 <= sum:DE:action_className:all_manual_attempts:not_failed:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.7
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is between 60 - 70% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: login_success_rate_between_50_and_60_de
    expr: 0.5 <= sum:DE:action_className:all_manual_attempts:not_failed:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.6
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is between 50 - 60 % ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: login_success_rate_below_50_de
    expr: sum:DE:action_className:all_manual_attempts:not_failed:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.5
    for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is below 50% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  ### Bank side failures
  - alert: bank_success_rate_between_70_and_80_de
    expr: 0.7 <= sum:DE:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.8
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is between 20 - 30% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: bank_success_rate_between_60_and_70_de
    expr: 0.6 <= sum:DE:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.7
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is between 30 - 40% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: bank_success_rate_between_50_and_60_de
    expr: 0.5 <= sum:DE:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.6
    for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is between 40 - 50% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the {{ .Values.p3WaitTimeBeforeFiringAlert }} 30 minutes.
      tags: {{ .Values.tags }}

  - alert: bank_success_rate_below_50_de
    expr: sum:DE:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:DE:action_className:all_manual_attempts:delta1h > 5) < 0.5
    for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is above 50% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  # These two alerts below work in opposite way of others, here we look at "error rate being high == bad", instead of "success rate being low == bad"

  - alert: manual_login_error_rate_over_50%_due_to_bank_side_error_de
    expr: |
      0.5 < 
      sum by(className) (increase (tink_agent_login_total{ provider_type!="test", market="DE", action="login-manual", outcome="unavailable"}[1h])) 
      / 
      (sum by (className) (increase (tink_agent_login_total{ provider_type!="test", market="DE", action="login-manual"}[1h])) > 5)
    for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Manual login error rate due to bank unavailable is <{ $value | humanizePercentage }> for agent <{ $labels.className }>
        in the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: auto_login_error_rate_over_50%_due_to_bank_side_error_de
    expr: |
      0.5 < 
      sum by(action, className) (increase (tink_agent_login_total{ provider_type!="test", market="DE", action=~"login-auto|login-cron", outcome="unavailable"}[1h])) 
      / 
      (sum by (action, className) (increase (tink_agent_login_total{ provider_type!="test", market="DE", action=~"login-auto|login-cron"}[1h])) > 5)
    for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Auto login error rate due to bank unavailable is <{ $value | humanizePercentage }> for action <{ $labels.action }> and agent <{ $labels.className }>
        in the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  #################################
  ### AllErrors - Agent Refresh ###
  #################################
  - alert: agent_refreshes_below45_greater35_due_to_all_error_for_specific_product_in_de
    expr: 0.35 <= sum:DE:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.45
    for: 30m
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 35 - 45% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below35_greater25_due_to_all_error_for_specific_product_in_de
    expr: 0.25 <= sum:DE:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.35
    for: 30m
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 25 - 35% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below25_greater15_due_to_all_error_for_specific_product_in_de
    expr: 0.15 <= sum:DE:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.25
    for: 30m
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 15 - 25% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below15_due_to_all_error_for_specific_product_in_de
    expr: sum:DE:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.15
    for: 30m
    labels:
      severity: urgent
      priority: P1
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is below 15% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  ###############################################
  ### AllErrors - Partially Completed Refresh ###
  ###############################################

  - alert: agent_refreshes_below60_greater50_due_to_partially_completed_error_for_specific_product_in_de
    expr: 0.5 <= sum:DE:className_type:not_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.6
    for: 30m
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 50 - 60% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below50_greater40_due_to_partially_completed_error_for_specific_product_in_de
    expr: 0.4 <= sum:DE:className_type:not_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.5
    for: 30m
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 40 - 50% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below40_greater30_due_to_partially_completed_error_for_specific_product_in_de
    expr: 0.3 <= sum:DE:className_type:not_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.4
    for: 30m
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 30 - 40% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below30_due_to_partially_completed_error_for_specific_product_in_de
    expr: sum:DE:className_type:not_partially_completed:delta1h / (sum:DE:className_type:all_refreshes:delta1h > 20) < 0.3
    for: 30m
    labels:
      severity: urgent
      priority: P1
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is below 30% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}
