kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-de
  namespace: agents
spec:
  rules:

    ## Login success rates - for DE because of a lot of TIMEOUTs and INCORRECT_CREDENTIALS
    ## and being aware of the issue - we will assume all auth errors as successful refreshes.
    ## To discover agents with really low SR there are long term alerts prepared.
    ## is action grouping needed ??
    - alert: login_success_rate_between_70_and_80_de
      expr: |
        # Successful/Cancelled attempts above 80%
        (sum:all_manual_attempts:not_failed_DE:delta60m:action_className
            / sum:all_manual_attempts:delta60m:action_className < 0.80)
        and (sum:all_manual_attempts:not_failed_DE:delta60m:action_className
                    / sum:all_manual_attempts:delta60m:action_className >= 0.70)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:action_className > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Login success rate is between 70 - 80% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes..
        tags: {{ .Values.tags }}

    - alert: login_success_rate_between_60_and_70_de
      expr: |
        (sum:all_manual_attempts:not_failed_DE:delta60m:action_className
            / sum:all_manual_attempts:delta60m:action_className < 0.70)
        and (sum:all_manual_attempts:not_failed_DE:delta60m:action_className
                    / sum:all_manual_attempts:delta60m:action_className >= 0.60)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:action_className > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Login success rate is between 60 - 70% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: login_success_rate_between_50_and_60_de
      expr: |
        (sum:all_manual_attempts:not_failed_DE:delta60m:action_className
            / sum:all_manual_attempts:delta60m:action_className < 0.60)
        and (sum:all_manual_attempts:not_failed_DE:delta60m:action_className
                    / sum:all_manual_attempts:delta60m:action_className >= 0.50)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:action_className > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Login success rate is between 50 - 60 % ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    # why only className not action,className grouping ?? or maybe just use className grouping in above alerts
    - alert: manual_login_success_rate_below_50_de
      expr: |
        (sum:all_manual_attempts:not_failed_DE:delta60m:className
            / sum:all_manual_attempts:delta60m:className < 0.50)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:className > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: kibana Link {{ .Values.kibanaClassLink }}
          Grafana Link {{ .Values.grafanaLink }}
        summary: Login success rate is below 50% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    ### Bank side failures
    - alert: bank_success_rate_between_70_and_80_de
      expr: |
        # Unavailable outcome above 50%
        (sum:all_manual_attempts:not_unavailable:delta60m:action_className
            / sum:all_manual_attempts:delta60m:action_className < 0.80)
        and (sum:all_manual_attempts:not_unavailable:delta60m:action_className
                        / sum:all_manual_attempts:delta60m:action_className >= 0.70)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:action_className > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Bank errors rate is between 20 - 30% ( <{ $value }> ) for <{ $labels.className }>
          the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: bank_success_rate_between_60_and_70_de
      expr: |
        # Unavailable outcome above 50%
        (sum:all_manual_attempts:not_unavailable:delta60m:action_className
            / sum:all_manual_attempts:delta60m:action_className < 0.70)
        and (sum:all_manual_attempts:not_unavailable:delta60m:action_className
                    / sum:all_manual_attempts:delta60m:action_className >= 0.60)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:action_className > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Bank errors rate is between 30 - 40% ( <{ $value }> ) for <{ $labels.className }>
          the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: bank_success_rate_between_50_and_60_de
      expr: |
        # Unavailable outcome above 50%
        (sum:all_manual_attempts:not_unavailable:delta60m:action_className
            / sum:all_manual_attempts:delta60m:action_className < 0.60)
        and (sum:all_manual_attempts:not_unavailable:delta60m:action_className
                        / sum:all_manual_attempts:delta60m:action_className >= 0.50)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:action_className > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Bank errors rate is between 40 - 50% ( <{ $value }> ) for <{ $labels.className }>
          the {{ .Values.p3WaitTimeBeforeFiringAlert }} 30 minutes.
        tags: {{ .Values.tags }}

    - alert: bank_success_rate_below_50_de
      expr: |
        # Unavailable outcome above 50%
        (sum:all_manual_attempts:not_unavailable:delta60m:action_className
            / sum:all_manual_attempts:delta60m:action_className < 0.50)
        # At least this many attempts.
        and sum:all_manual_attempts:delta60m:action_className > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Bank errors rate is below 50% ( <{ $value }> ) for <{ $labels.className }>
          the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: manual_login_error_rate_over_50%_due_to_bank_side_error_de
      expr: |
        (sum by(className) (increase (tink_agent_login_total{ environment="production",market="DE", outcome="unavailable", action="login-manual"}[1h]))
        / sum:className:production:login-manual:delta1h > 0.5 )
        and sum:className:production:login-manual:delta1h > 5
      for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Manual login error rate more than 50% ( <{ $value * 100}> ) % for agent <{ $labels.className }>
          the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: auto_login_error_rate_over_50%_due_to_bank_side_error_de
      expr: |
        (sum by(className) (increase (tink_agent_login_total{ environment="production",market="DE", outcome="unavailable", action=~"login-auto|login-cron"}[1h]))
        / sum:className:production:login-auto-and-cron:delta1h > 0.5 )
        and sum:className:production:login-auto-and-cron:delta1h > 5
      for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Auto login error rate more than 50% ( <{ $value * 100 }>  ) % for agent <{ $labels.className }>
          the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    ## Long term alerts
    ## - to detect only authentication error / timeouts through longer period of time with really low SR
    - alert: long_term_all_error_between_80_and_90_de
      expr: |
        sum:all_manual_attempts:not_cancelled_unavaible_failed:delta6h
          / sum:all_manual_attempts:delta6h < 0.2
        and sum(sum_over_time(tink_agent_login_total{ {{ .Values.manualLoginActions }}, {{ .Values.allErrorsAuth }}", market="DE"}[6h])) BY (className)
          / sum:all_manual_attempts:delta6h >= 0.1
      for: 1h
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Login success rate is between 10 - 20% ( <{ $value }> ) the last 6 hours because of all errors.
        tags: {{ .Values.tags }}

    - alert: long_term_all_error_below_90_de
      expr: |
        # Login failure the last 6 hours
        sum:all_manual_attempts:not_cancelled_unavaible_failed:delta6h
        # All login attempts the last 6 hours
          / sum:all_manual_attempts:delta6h < 0.10
      for: 1h
      labels:
        severity: urgent
        priority: P1
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Login success rate is below 10% ( <{ $value }> ) the last 6 hours because of all errors.
        tags: {{ .Values.tags }}

    - alert: long_term_authentication_errors_between_80_and_90_de
      expr: |
        (sum:all_manual_attempts:not_cancelled:delta6h
          / sum:all_manual_attempts:delta6h < 0.2)
        and (sum:all_manual_attempts:not_cancelled:delta6h
          / sum:all_manual_attempts:delta6h > 0.1)
      for: 1h
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Login success rate is between 10 - 20% ( <{ $value }> ) the last 6 hours because of all errors.
        tags: {{ .Values.tags }}

    - alert: long_term_authentication_errors_over_90_de
      expr: |
        # Login cancelled the last 6 hours
        sum:all_manual_attempts:not_cancelled:delta6h
        # All login attempts the last 6 hours
          / sum:all_manual_attempts:delta6h < 0.10
      for: 1h
      labels:
        severity: urgent
        priority: P1
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Login success rate is below 10% ( <{ $value }> ) the last 6 hours.
        tags: {{ .Values.tags }}

    #################################
    ### AllErrors - Agent Refresh ###
    #################################
    - alert: agent_refreshes_below45_greater35_due_to_all_error_for_specific_product_in_de
      expr: |
        (sum:className_type:not_failed_unavailable_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.45)
        and sum:className_type:not_failed_unavailable_partially_completed:delta60m)
            / sum:refreshes_DE:delta60m >= 0.35)
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 35 - 45% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below35_greater25_due_to_all_error_for_specific_product_in_de
      expr: |
        (sum:className_type:not_failed_unavailable_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.35)
        and (sum:className_type:not_failed_unavailable_partially_completed:delta60m
            / sum:refreshes_DE:delta60m >= 0.25)
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 25 - 35% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below25_greater15_due_to_all_error_for_specific_product_in_de
      expr: |
        (sum:className_type:not_failed_unavailable_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.25)
        and (sum:className_type:not_failed_unavailable_partially_completed:delta60m
            / sum:refreshes_DE:delta60m >= 0.15)
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 15 - 25% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below15_due_to_all_error_for_specific_product_in_de
      expr: |
        (sum:className_type:not_failed_unavailable_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.15)
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: urgent
        priority: P1
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is below 15% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    ###############################################
    ### AllErrors - Partially Completed Refresh ###
    ###############################################

    - alert: agent_refreshes_below60_greater50_due_to_partially_completed_error_for_specific_product_in_de
      expr: |
        (sum:className_type:not_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.6)
        and (sum:className_type:not_partially_completed:delta60m
            / sum:refreshes_DE:delta60m >= 0.5)
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 50 - 60% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below50_greater40_due_to_partially_completed_error_for_specific_product_in_de
      expr: |
        (sum:className_type:not_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.5)
        and (sum:className_type:not_partially_completed:delta60m
            / sum:refreshes_DE:delta60m >= 0.4)
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 40 - 50% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below40_greater30_due_to_partially_completed_error_for_specific_product_in_de
      expr: |
        (sum:className_type:not_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.4)
        and (sum:className_type:not_partially_completed:delta60m
            / sum:refreshes_DE:delta60m >= 0.3)
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 30 - 40% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below30_due_to_partially_completed_error_for_specific_product_in_de
      expr: |
        sum:className_type:not_partially_completed:delta60m
            / sum:refreshes_DE:delta60m < 0.3
         and sum:refreshes_DE:delta60m > 20
      for: 30m
      labels:
        severity: urgent
        priority: P1
        who: integration-nazguls
      annotations:
        description: {{ .Values.kibanaClassLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is below 30% because of all issues ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}
