kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: recordingrules-refresh-de-test
  namespace: agents
spec:
  interval: 2m30s
  rules:

#===================================================
# Work in progress below!
#
# These expressions below should do what increase should be doing on its own, if the metrics were 0-initialized.
# For now, those recording rules are not used by any alerts!
# They are here to observe:
#  * if using variables in this syntax is ok
#  * how long do they take to evaluate on DE market
#  * do they even evaluate
#===================================================

  - record: DE:agent_refresh:className_type:all_refreshes:delta1h:TESTING
    expr: sum by(className, type) (
        (floor(increase({{ .Values.deQueryRefreshAll }}[1h])) and ({{ .Values.deQueryRefreshAll }} offset 1h unless {{ .Values.deQueryRefreshAll }}))
        or 
        (1 + floor(increase({{ .Values.deQueryRefreshAll }}[1h])) - floor(count_over_time({{ .Values.deQueryRefreshAll }}[1h]) / 360))
      )

  - record: DE:agent_refresh:className_type:failed_or_partially_completed:delta1h:TESTING
    expr: sum by(className, type) (
        (floor(increase({{ .Values.deQueryRefreshFailed }}[1h])) and ({{ .Values.deQueryRefreshFailed }} offset 1h unless {{ .Values.deQueryRefreshFailed }}))
        or 
        (1 + floor(increase({{ .Values.deQueryRefreshFailed }}[1h])) - floor(count_over_time({{ .Values.deQueryRefreshFailed }}[1h]) / 360))
      )

  - record: DE:agent_refresh:className_type:unavailable:delta1h:TESTING
    expr: sum by(className, type) (
        (floor(increase({{ .Values.deQueryRefreshUnavailable }}[1h])) and ({{ .Values.deQueryRefreshUnavailable }} offset 1h unless {{ .Values.deQueryRefreshUnavailable }}))
        or 
        (1 + floor(increase({{ .Values.deQueryRefreshUnavailable }}[1h])) - floor(count_over_time({{ .Values.deQueryRefreshUnavailable }}[1h]) / 360))
      )
