kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: recordingrules-payment-de-test
  namespace: agents
spec:
  interval: 2m30s
  rules:

#===================================================
# Work in progress below!
#
# These expressions below should do what increase should be doing on its own, if the metrics were 0-initialized.
# For now, those recording rules are not used by any alerts!
# They are here to observe:
#  * if using variables in this syntax is ok
#  * how long do they take to evaluate on DE market
#  * do they even evaluate
#===================================================

  - record: DE:agent_transfer:className:all_payments:delta1h:TESTING
    expr: sum by(className) (
        (floor(increase({{ .Values.deQueryPaymentAll }}[1h])) and ({{ .Values.deQueryPaymentAll }} offset 1h unless {{ .Values.deQueryPaymentAll }}))
        or 
        (1 + floor(increase({{ .Values.deQueryPaymentAll }}[1h])) - floor(count_over_time({{ .Values.deQueryPaymentAll }}[1h]) / 360))
      )

  - record: DE:agent_transfer:className:failed:delta1h:TESTING
    expr: sum by(className) (
        (floor(increase({{ .Values.deQueryPaymentFailed }}[1h])) and ({{ .Values.deQueryPaymentFailed }} offset 1h unless {{ .Values.deQueryPaymentFailed }}))
        or 
        (1 + floor(increase({{ .Values.deQueryPaymentFailed }}[1h])) - floor(count_over_time({{ .Values.deQueryPaymentFailed }}[1h]) / 360))
      )

  - record: DE:agent_transfer:className:unavailable:delta1h:TESTING
    expr: sum by(className) (
        (floor(increase({{ .Values.deQueryPaymentUnavailable }}[1h])) and ({{ .Values.deQueryPaymentUnavailable }} offset 1h unless {{ .Values.deQueryPaymentUnavailable }}))
        or 
        (1 + floor(increase({{ .Values.deQueryPaymentUnavailable }}[1h])) - floor(count_over_time({{ .Values.deQueryPaymentUnavailable }}[1h]) / 360))
      )

  - record: DE:agent_transfer:className:cancelled:delta1h:TESTING
    expr: sum by(className) (
        (floor(increase({{ .Values.deQueryPaymentCancelled }}[1h])) and ({{ .Values.deQueryPaymentCancelled }} offset 1h unless {{ .Values.deQueryPaymentCancelled }}))
        or 
        (1 + floor(increase({{ .Values.deQueryPaymentCancelled }}[1h])) - floor(count_over_time({{ .Values.deQueryPaymentCancelled }}[1h]) / 360))
      )
