kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: recordingrules-login-de
  namespace: agents
spec:
  rules:

  - record: sum:DE:action_className:all_manual_attempts:delta1h
    expr: sum by (action,className) (increase(tink_agent_login_total{ provider_type!="test", market="DE", action="login-manual"}[1h]))

  - record: sum:DE:action_className:all_manual_attempts:not_failed:delta1h
    expr: sum by (action,className) (increase(tink_agent_login_total{ provider_type!="test", market="DE", action="login-manual", {{ .Values.temporaryErrorsAuth }}}[1h]))

  - record: sum:DE:action_className:all_manual_attempts:not_unavailable:delta1h
    expr: sum by (action,className) (increase(tink_agent_login_total{ provider_type!="test", market="DE", action="login-manual", {{ .Values.bankErrorsAuth }}}[1h]))
