kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: recordingrules-refresh-de
  namespace: agents
spec:
  rules:

  - record: sum:DE:className_type:all_refreshes:delta1h
    expr: sum by (className,type) (increase(tink_agent_refresh_total{ provider_type!="test", market="DE"}[1h]))

  - record: sum:DE:className_type:not_failed_unavailable_partially_completed:delta1h
    expr: sum by (className,type) (increase(tink_agent_refresh_total{ provider_type!="test", market="DE", {{ .Values.allErrorsRefresh }}}[1h]))

  - record: sum:DE:className_type:not_partially_completed:delta1h
    expr: sum by (className,type) (increase(tink_agent_refresh_total{ provider_type!="test", market="DE", {{ .Values.partiallyCompletedErrorRefresh }}}[1h]))
