package se.tink.backend.aggregation.agents.nxgen.serviceproviders.openbanking.creditagricole.transactionalaccount;

import org.junit.Ignore;

@Ignore
public class CreditAgricoleCreditCardsAccountTransactionalFetcherTestData {

    static final String CREDIT_CARDS_ACCOUNT_RESPOMSE =
            "{\n"
                    + "    \"accounts\": [\n"
                    + "        {\n"
                    + "            \"resourceId\": \"12312312312312312\",\n"
                    + "            \"bicFi\": null,\n"
                    + "            \"accountId\": {\n"
                    + "                \"area\": null,\n"
                    + "                \"iban\": null,\n"
                    + "                \"other\": {\n"
                    + "                    \"identification\": \"312312312312312312\",\n"
                    + "                    \"cardNumber\": \"3123213123123123123\",\n"
                    + "                    \"schemeName\": \"CPAN\",\n"
                    + "                    \"issuer\": \"ASASA313231231\"\n"
                    + "                },\n"
                    + "                \"currency\": \"EUR\"\n"
                    + "            },\n"
                    + "            \"name\": \"SAMPLE NAME\",\n"
                    + "            \"details\": \"active\",\n"
                    + "            \"linkedAccount\": \"FR3123123123123123\",\n"
                    + "            \"usage\": null,\n"
                    + "            \"cashAccountType\": \"CARD\",\n"
                    + "            \"product\": \"SAMPLE PRODUCT\",\n"
                    + "            \"balances\": [\n"
                    + "                {\n"
                    + "                    \"name\": \"Instant Balance 01/2021\",\n"
                    + "                    \"balanceAmount\": {\n"
                    + "                        \"currency\": \"EUR\",\n"
                    + "                        \"amount\": \"0.0\"\n"
                    + "                    },\n"
                    + "                    \"balanceType\": \"XPCD\",\n"
                    + "                    \"lastChangeDateTime\": null,\n"
                    + "                    \"referenceDate\": \"2021-01-13\",\n"
                    + "                    \"lastCommittedTransaction\": null\n"
                    + "                },\n"
                    + "                {\n"
                    + "                    \"name\": \"Instant Balance 02/2021\",\n"
                    + "                    \"balanceAmount\": {\n"
                    + "                        \"currency\": \"EUR\",\n"
                    + "                        \"amount\": \"0.0\"\n"
                    + "                    },\n"
                    + "                    \"balanceType\": \"XPCD\",\n"
                    + "                    \"lastChangeDateTime\": null,\n"
                    + "                    \"referenceDate\": \"2021-01-13\",\n"
                    + "                    \"lastCommittedTransaction\": null\n"
                    + "                }\n"
                    + "            ],\n"
                    + "            \"psuStatus\": null,\n"
                    + "            \"_links\": {\n"
                    + "                \"balances\": {\n"
                    + "                    \"href\": \"/accounts/sampleres/balances\",\n"
                    + "                    \"templated\": false\n"
                    + "                },\n"
                    + "                \"transactions\": {\n"
                    + "                    \"href\": \"/accounts/sampleres/transactions\",\n"
                    + "                    \"templated\": true\n"
                    + "                }\n"
                    + "            }\n"
                    + "        }\n"
                    + "    ],\n"
                    + "    \"_links\": {\n"
                    + "        \"self\": {\n"
                    + "            \"href\": \"/accounts\",\n"
                    + "            \"templated\": false\n"
                    + "        },\n"
                    + "        \"endUserIdentity\": {\n"
                    + "            \"href\": \"/end-user-identity\",\n"
                    + "            \"templated\": false\n"
                    + "        },\n"
                    + "        \"beneficiaries\": {\n"
                    + "            \"href\": \"/trusted-beneficiaries\",\n"
                    + "            \"templated\": false\n"
                    + "        },\n"
                    + "        \"first\": null,\n"
                    + "        \"last\": null,\n"
                    + "        \"next\": null,\n"
                    + "        \"prev\": null\n"
                    + "    }\n"
                    + "}";
}
