package se.tink.backend.aggregation.agents.nxgen.be.banks.ing.fetcher.transactionalaccount.entities;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;

import java.util.Collection;
import org.junit.Assert;
import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.be.banks.ing.fetcher.transactionalaccount.rpc.TransactionsResponse;
import se.tink.backend.aggregation.nxgen.core.transaction.Transaction;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class TransactionsResponseTest {
    @Test
    public void testParseTransactionDescription() {
        TransactionsResponse response =
                SerializationUtils.deserializeFromString(TEST_DATA, TransactionsResponse.class);
        Collection<Transaction> transactions = response.getTinkTransactions();
        assertEquals(7, transactions.size());
        for (Transaction tx : transactions) {
            System.out.println(
                    String.format(
                            "TX description: %s\nrawDetails: %s",
                            tx.getDescription(), tx.getRawDetails()));
            assertFalse(tx.getDescription().startsWith("From:"));
            assertFalse(tx.getDescription().startsWith("To:"));
            assertFalse(tx.getDescription().startsWith("06/02 - 12.48 pm"));
            assertFalse(tx.getDescription().startsWith("12/02 - 1.06 pm"));
            assertFalse(tx.getDescription().startsWith("19/02 - 8.09 am"));
            assertFalse(tx.getDescription().startsWith("19/02 - 8.09 am"));
            assertFalse(tx.getDescription().startsWith("06/02 - 12.48 pm"));
        }
    }

    @Test(expected = IllegalStateException.class)
    public void testOutOfSessionResponses() {
        TransactionsResponse transactionsResponse =
                SerializationUtils.deserializeFromString(
                        OUT_OF_SESSION_RESPONSE, TransactionsResponse.class);
        TransactionsResponseEntity mobileResponse = transactionsResponse.getMobileResponse();
        Assert.assertEquals("NOK", mobileResponse.getReturnCode());
    }

    private static final String OUT_OF_SESSION_RESPONSE =
            "{\n"
                    + " \"mobileResponse\": {\n"
                    + " \"header\": {\n"
                    + " \"version\": \"0.1\"\n"
                    + " },\n"
                    + " \"returnCode\": \"NOK\",\n"
                    + " \"errors\": [\n"
                    + " {\n"
                    + " \"code\": \"001\",\n"
                    + " \"text\": \"Out Of Session\"\n"
                    + " }\n"
                    + " ]\n"
                    + " }\n"
                    + "}";

    private static final String TEST_DATA =
            "{"
                    + " \"mobileResponse\": {"
                    + "  \"header\": {"
                    + "   \"version\": \"0.1\","
                    + "   \"url\": \"/eb/MobileRequest\""
                    + "  },"
                    + "  \"returnCode\": \"OK\","
                    + "  \"movements\": [{"
                    + "   \"seqNr\": 1,"
                    + "   \"startIndex\": 1,"
                    + "   \"endIndex\": 4,"
                    + "   \"amount\": \"-000000000000001002\","
                    + "   \"postingDate\": \"20180409\","
                    + "   \"valueDate\": \"20180409\","
                    + "   \"balance\": \"+000000000000000002\","
                    + "   \"bbanNumber\": \"BBAN1110000\","
                    + "   \"categoryCode\": \"\","
                    + "   \"category\": \"\","
                    + "   \"subCategoryCode\": \"\","
                    + "   \"subCategory\": \"\","
                    + "   \"details\": ["
                    + "    \"ING Smart Banking payment (see advice)\","
                    + "    \"To: MR CHEN THE MAN - BEIBAN111\","
                    + "    \"Communication: Testing\""
                    + "   ],"
                    + "   \"extraDetails\": ["
                    + "    \"ING Smart Banking payment\","
                    + "    \"In favour of: MR CHEN THE MAN\","
                    + "    \"GROSSENLAAN 112\","
                    + "    \"9001        BRUXELLES\","
                    + "    \"Belgium\","
                    + "    \"IBAN: BE3IAB1111\","
                    + "    \"Message:\","
                    + "    \"Testing\""
                    + "   ],"
                    + "   \"number\": \"000004\","
                    + "   \"posId\": \"\","
                    + "   \"counterpartyAccountNr\": \"IBAN12121212\","
                    + "   \"dayCode\": \"00\","
                    + "   \"sequence\": \"2\""
                    + "  }, {"
                    + "   \"seqNr\": 2,"
                    + "   \"startIndex\": 1,"
                    + "   \"endIndex\": 4,"
                    + "   \"amount\": \"+000000000000001002\","
                    + "   \"postingDate\": \"20180409\","
                    + "   \"valueDate\": \"20180409\","
                    + "   \"balance\": \"+000000000000001002\","
                    + "   \"bbanNumber\": \"BBAN222222\","
                    + "   \"categoryCode\": \"\","
                    + "   \"category\": \"\","
                    + "   \"subCategoryCode\": \"\","
                    + "   \"subCategory\": \"\","
                    + "   \"details\": ["
                    + "    \"European transfer (see advice)\","
                    + "    \"From: MR CHEN THE MAN - BE3IBAN2222\","
                    + "    \"Communication: Testing\""
                    + "   ],"
                    + "   \"extraDetails\": ["
                    + "    \"European transfer\","
                    + "    \"From: MR CHEN THE MAN\","
                    + "    \"GROSSENLAAN 112\","
                    + "    \"9001        BRUXELLES\","
                    + "    \"Belgium\","
                    + "    \"IBAN: BE3IBAN2222\","
                    + "    \"Message:\","
                    + "    \"Testing\""
                    + "   ],"
                    + "   \"number\": \"000003\","
                    + "   \"posId\": \"\","
                    + "   \"counterpartyAccountNr\": \"IBAN131313313\","
                    + "   \"dayCode\": \"00\","
                    + "   \"sequence\": \"1\""
                    + "  }, {"
                    + "   \"seqNr\": 3,"
                    + "   \"startIndex\": 1,"
                    + "   \"endIndex\": 4,"
                    + "   \"amount\": \"+000000000000000002\","
                    + "   \"postingDate\": \"20180102\","
                    + "   \"valueDate\": \"20171231\","
                    + "   \"balance\": \"+000000000000000002\","
                    + "   \"bbanNumber\": \"BBAN33333333\","
                    + "   \"categoryCode\": \"\","
                    + "   \"category\": \"\","
                    + "   \"subCategoryCode\": \"\","
                    + "   \"subCategory\": \"\","
                    + "   \"details\": ["
                    + "    \"Interests-Charges 31/12/17\","
                    + "    \"Statement enclosed\""
                    + "   ],"
                    + "   \"extraDetails\": ["
                    + "    \"Statement of Interest and Expenses at 31/12/17\","
                    + "    \"from account BE62 IBAN 4444 4444 EUR   000\","
                    + "    \"===ING LION ACCOUNT===\","
                    + "    \"Net to BE62 4141 1414 4141 EUR...      +    0,00\","
                    + "    \"Tax on bank documents (EUR 0,15)\""
                    + "   ],"
                    + "   \"number\": \"000002\","
                    + "   \"posId\": \"\","
                    + "   \"counterpartyAccountNr\": \"000000000000\","
                    + "   \"dayCode\": \"00\","
                    + "   \"sequence\": \"2\""
                    + "  }, {"
                    + "   \"seqNr\": 4,"
                    + "   \"startIndex\": 1,"
                    + "   \"endIndex\": 4,"
                    + "   \"amount\": \"+000000000000000002\","
                    + "   \"postingDate\": \"20180102\","
                    + "   \"valueDate\": \"20171231\","
                    + "   \"balance\": \"+000000000000000002\","
                    + "   \"bbanNumber\": \"BBAN5555555\","
                    + "   \"categoryCode\": \"\","
                    + "   \"category\": \"\","
                    + "   \"subCategoryCode\": \"\","
                    + "   \"subCategory\": \"\","
                    + "   \"details\": ["
                    + "    \"Breakdown of charges No. 01010101\","
                    + "    \"Proof attached\""
                    + "   ],"
                    + "   \"extraDetails\": ["
                    + "    \"Breakdown of charges No. 01010101 on 31/12/2017\","
                    + "    \"ING Lion Account BE62 IBAN 4444 4444 EUR\","
                    + "    \"Current account BE62 IBAN 4444 4444 EUR\","
                    + "    \"Period from 01/01/2018 to 31/12/2018\","
                    + "    \"Account servicing charges                            + 0,0000 EUR (0)\","
                    + "    \"Annual flat fee covering an unlimited number of\","
                    + "    \"electronic banking operations in euros, access\","
                    + "    \"to Home'Bank, Smart Banking, Self'Bank and\","
                    + "    \"Phone'Bank, account statements via Home'Bank,\","
                    + "    \"and 1 ING payment card with payment and\","
                    + "    \"withdrawal functions per holder (max. 2)            + 0,0000 EUR (1)\","
                    + "    \"ING payment card BE62 IBAN 4444 4444\","
                    + "    \"Period from 01/01/2018 to 31/12/2018\","
                    + "    \"Annual fee for payment and withdrawal\","
                    + "    \"facilities in Belgium and in Europe                 + 0,0000 EUR (1)\","
                    + "    \"ING payment card BE62 IBAN 4444 4444\","
                    + "    \"Period from 01/01/2018 to 31/12/2018\","
                    + "    \"Annual fee for payment and withdrawal\","
                    + "    \"facilities in Belgium and in Europe                 + 0,0000 EUR (1)\","
                    + "    \"--------------------------------------------------\","
                    + "    \"Total\","
                    + "    \"debited against account BE62 IBAN 4444 4444:          + 0,00 EUR\","
                    + "    \"To be sent, if necessary, with your tax return.\""
                    + "   ],"
                    + "   \"number\": \"000001\","
                    + "   \"posId\": \"\","
                    + "   \"counterpartyAccountNr\": \"000000000000\","
                    + "   \"dayCode\": \"00\","
                    + "   \"sequence\": \"1\""
                    + "  }, {"
                    + "   \"seqNr\": 36,"
                    + "   \"startIndex\": 21,"
                    + "   \"endIndex\": 40,"
                    + "   \"amount\": \"-000000000000002002\","
                    + "   \"postingDate\": \"20180212\","
                    + "   \"valueDate\": \"20180212\","
                    + "   \"balance\": \"+000000000001554492\","
                    + "   \"bbanNumber\": \"BBAN66666666\","
                    + "   \"categoryCode\": \"\","
                    + "   \"category\": \"\","
                    + "   \"subCategoryCode\": \"\","
                    + "   \"subCategory\": \"\","
                    + "   \"details\": ["
                    + "    \"Purchase Bancontact/Mister Cash\","
                    + "    \"12/02 - 1.06 pm - BNP PARIBAS FORT - ST GOOD GOLLY MISS MOLLY T - BEL\","
                    + "    \"Card Number 6666 66XX XXXX 6666 6\""
                    + "   ],"
                    + "   \"number\": \"000034\","
                    + "   \"posId\": \"679269\","
                    + "   \"counterpartyAccountNr\": \"16161616161\","
                    + "   \"dayCode\": \"00\","
                    + "   \"sequence\": \"1\""
                    + "  },{"
                    + "   \"seqNr\": 33,"
                    + "   \"startIndex\": 21,"
                    + "   \"endIndex\": 40,"
                    + "   \"amount\": \"-000000000000002202\","
                    + "   \"postingDate\": \"20180219\","
                    + "   \"valueDate\": \"20180219\","
                    + "   \"balance\": \"+000000000001540692\","
                    + "   \"bbanNumber\": \"BBAN77777777\","
                    + "   \"categoryCode\": \"\","
                    + "   \"category\": \"\","
                    + "   \"subCategoryCode\": \"\","
                    + "   \"subCategory\": \"\","
                    + "   \"details\": ["
                    + "    \"Purchase Bancontact/Mister Cash\","
                    + "    \"19/02 - 8.09 am - BALOOBA - BRUGES - BEL\","
                    + "    \"Card Number 7777 77XX XXXX 7777 7\""
                    + "   ],"
                    + "   \"number\": \"000037\","
                    + "   \"posId\": \"818076\","
                    + "   \"counterpartyAccountNr\": \"17171717171\","
                    + "   \"dayCode\": \"00\","
                    + "   \"sequence\": \"1\""
                    + "  },{"
                    + "   \"seqNr\": 39,"
                    + "   \"startIndex\": 21,"
                    + "   \"endIndex\": 40,"
                    + "   \"amount\": \"-000000000000006402\","
                    + "   \"postingDate\": \"20180206\","
                    + "   \"valueDate\": \"20180206\","
                    + "   \"balance\": \"+000000000001470802\","
                    + "   \"bbanNumber\": \"BBAN8888888\","
                    + "   \"categoryCode\": \"\","
                    + "   \"category\": \"\","
                    + "   \"subCategoryCode\": \"\","
                    + "   \"subCategory\": \"\","
                    + "   \"details\": ["
                    + "    \"Purchase Bancontact/Mister Cash\","
                    + "    \"06/02 - 12.48 pm - BNP PARIBAS FORT - ST JOOST T - BEL\","
                    + "    \"Card Number 8888 88XX XXXX 8888 8\""
                    + "   ],"
                    + "   \"number\": \"000031\","
                    + "   \"posId\": \"679269\","
                    + "   \"counterpartyAccountNr\": \"18181818181\","
                    + "   \"dayCode\": \"00\","
                    + "   \"sequence\": \"1\""
                    + "  }]"
                    + " }"
                    + "}";
}
