kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts
  namespace: agents
spec:
  rules:

    # Test alert to try "file alerts separation" in sub directory
    - alert: BeProudBeFluffy
      expr: |
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in",  outcome=~"completed|cancelled|unavailable", market="FI"}[60m])) by (action,className,provider)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="FI"}[60m])) by (action,className,provider) < 0.95)
      for: 5m
      labels:
        severity: ping
        who: integration
