package se.tink.backend.rpc;

public enum RefreshableItem {
    ACCOUNTS, TRANSACTIONAL_ACCOUNTS_AND_TRANSACTIONS, EINVOICES, TRANSFER_DESTINATIONS,

    CHECKING_ACCOUNTS,
    CHECKING_TRANSACTIONS,
    SAVING_ACCOUNTS,
    SAVING_TRANSACTIONS,
    CREDITCARD_ACCOUNTS,
    CREDITCARD_TRANSACTIONS,
    LOAN_ACCOUNTS,
    LOAN_TRANSACTIONS,
    INVESTMENT_ACCOUNTS,
    INVESTMENT_TRANSACTIONS
}
