package se.tink.backend.aggregation.agents.summary.refresh;

public enum RefreshStatus {
    NOT_STARTED,
    FETCHING_STARTED,
    FETCHING_COMPLETED,
    FETCHING_COMPLETED_PARTIALLY,
    INTERRUPTED_BY_BANK_SERVICE_EXCEPTION,
    INTERRUPTED_BY_SESSION_EXCEPTION,
    INTERRUPTED_BY_RUNTIME_EXCEPTION,
    INTERRUPTED_BY_EXCEPTION
}
