java_library(
    name = "rabobank",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib",
        "//src/libraries/account_identifier",
        "//src/libraries/amount",
        "//src/libraries/credentials:service",
        "@com_fasterxml_jackson_core_jackson_annotations//jar",
        "@com_google_code_findbugs_jsr305//jar",
        "@com_google_guava_guava//jar",
        "@com_sun_jersey_jersey_core//jar",
        "@org_assertj_assertj_core//jar",
    ],
)
