load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "hash",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:commons_codec_commons_codec",
    ],
)
