java_library(
    name = "document_container",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:org_apache_hadoop_hadoop_core",
    ],
)
