load("//tools/bzl:lib_with_sources.bzl", "java_library_with_sources")

java_library_with_sources(
    name = "aggregator_configuration",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
)
