package se.tink.backend.aggregation.agents.nxgen.de.banks.fints.configuration;

import java.util.Arrays;

public enum Bank {
    POSTBANK("Postbank"),
    SPARKASSE("Sparkasse"),
    B_1822_DIREKT("1822direkt"),
    AACHENER("Aachener"),
    APO_BANK("apoBank"),
    AUGSBURGER_AKTIEN_BANK("AugsburgerAktienbank"),
    BAD_WALDSEER_BANK("BadWaldseerBank"),
    BAGBANKAKTIENGESELLSCHAFT("BAGBankaktiengesellschaft"),
    BANK11("Bank11"),
    BANK1SAAR("Bank1Saar"),
    KD_BANK("KDBank"),
    BANKHAUS("Bankhaus"),
    BANK_IM_BISTUM_ESSEN("BankImBistumEssen"),
    KC_BANK("KCBank"),
    BANK_SCHILLING_CO("BankSchillingCo"),
    VERBUND_VOLKSBANK_OWL("VerbundVolksbankOWL"),
    BB_BANK("BBBank"),
    BENSBERGER_BANK("BensbergerBank"),
    BERKHEIMER_BANK("BerkheimerBank"),
    BERNHAUSER("Bernhauser"),
    BHF_BANK("BHFBank"),
    BOPFINGER_BANK_SR("BopfingerBankSechtaRies"),
    BREMER_LANDES_BANK("BremerLandesBank"),
    BRUEHLER_BANK("BruehlerBank"),
    BW_BANK("BWBank"),
    CALENBERGER_KREDITVEREIN("CalenbergerKreditverein"),
    REISE_BANK("ReiseBank"),
    COMDIRECT("Comdirect"),
    CONSORS_BANK("Consorsbank"),
    CRON_BANK("Cronbank"),
    CVW_PRIVATE_BANK("CVWPrivatbank"),
    DEGUSSA_BANK("DegussaBank"),
    DETTINGER_BANK("DettingerBank"),
    DEUTSCHE_BANK("DeutscheBank"),
    DEUTSCHE_GH("DeutscheGH"),
    DKB("DKB"),
    DKM_DARLEHNSKASSE_MUENSTER("DKMDarlehnskasseMuenster"),
    DONNER_REUSCHEL("DonnerReuschel"),
    DZ_BANK("DZBank"),
    ECHTERDINGER_BANK("EchterdingerBank"),
    EDEKA_BANK("EdekaBank"),
    EENZTAL_BANK("EnztalBank"),
    ERFURTER_BANK("ErfurterBank"),
    ERLIGHEIMER_BANK("ErligheimerBank"),
    EUROCITY_BANK("EurocityBank"),
    EVANGELISCHE_BANK("EvangelischeBank"),
    EVENORD_BANK("EvenordBank"),
    FEDERSEE_BANK("Federseebank"),
    FFS_BANK("FFSBank"),
    FINTECH_GROUP_BANK("FinTechGroupBank"),
    FRANKFURTER_BANK_GESELLSCHAFT("FrankfurterBankgesellschaft"),
    FUERST_FUGGER_PRIVATBANK("FuerstFuggerPrivatbank"),
    FUERSTLICH_CASTELL_BANK("FuerstlichCastellBank"),
    FOEHR_AMRUMER_BANK("FoehrAmrumerBank"),
    GS_BANK("GSBank"),
    GALLER_KANTONAL_BANK("GallerKantonalbank"),
    GENOSSENSCHAFTS_BANK("GenossenschaftsBank"),
    GERAER_BANK("GeraerBank"),
    GLADBACHER_BANK("GladbacherBank"),
    GLS_BANK("GLSBank"),
    GG_BANK("GGBank"),
    GREENSILL_BANK("GreensillBank"),
    GRENKE_BANK("GrenkeBank"),
    HAUS_BANK("HausBank"),
    HKB_BANK("HKBBank"),
    HOERNER_BANK("HoernerBank"),
    HSBC("HSBC"),
    HSH_NORD_BANK("HSHNordBank"),
    HUETTEN_BERGER_BANK("HuettenbergerBank"),
    ING_DIBA("INGDiBa"),
    IBB("IBB"),
    ISBANK("Isbank"),
    JULIUS_BAER("JuliusBaer"),
    KBC_BANK("KBCBank"),
    KORBER_BANK("KorberBank"),
    KURHESSISCHE_LANDBANK("KurhessischeLandbank"),
    HARLOFFTAL_LANDBANK("HorlofftalLandBank"),
    LEVO_BANK("LevoBank"),
    LIGA_BANK("LIGABank"),
    MARCARD_STEIN_CO("MarcardSteinCo"),
    MENDENER_BANK("MendenerBank"),
    MERCK_FINCK_CO("MerckFinckCo"),
    MERKUR_BANK("MerkurBank"),
    MKB_BANK("MKBBank"),
    MLP_BANK("MLPBank"),
    MM_WARBURG_CO("MMWarburgCo"),
    MUENSTER_LAENDLISCHE_BANK("MuensterlaendischeBank"),
    MURGTAL_BANK("MurgtalBank"),
    MAERKISCHE_BANK("MaerkischeBank"),
    MUENCHER_BANK("MuenchnerBank"),
    NATIONAL_BANK_ESSEN("NationalBankEssen"),
    NETBANK("Netbank"),
    NET_M_PRIVATBANK("NetMPrivatbank"),
    NIBC_BANK("NIBCBank"),
    NORDDEUTSCHE_LANDESBANK("NorddeutscheLandesbank"),
    NORTH_CHANNEL_BANK("NorthChannelBank"),
    OBER_BANK("Oberbank"),
    OLDENBURGISCHE_LANDSBANK("OldenburgischeLandesbank"),
    ONSTMETTINGER_BANK("OnstmettingerBank"),
    OTTO_SCHROEDER_BANK("OttoSchroederBank"),
    PAX_BANK("PaxBank"),
    PAYCENETR("PayCenter"),
    PSD_BANK("PSDBank"),
    AKTIVBANK("AktivBank"),
    RSB_RETAIL_SERVICE_BANK("SBRetailServiceBank"),
    LANDESBANK_SAAR("LandesbankSaar"),
    SAFRA_SARASIN_BANK("SafraSarasinBank"),
    SBERBANK("Sberbank"),
    SHCARNHAUSER_BANK("ScharnhauserBank"),
    SWAEBISCHE_BANK("SchwaebischeBank"),
    SKB("SKB"),
    SPARDA("Sparda"),
    SPAR_KREDIT_BANK("SparKreditbank"),
    SPAR_DARLEHNSKASSE("SparDarlehnskasse"),
    STEYLER_BANK("SteylerBank"),
    SYDBANK("Sydbank"),
    SUEDWEST_BANK("Suedwestbank"),
    TRIDOS_BANK("TriodosBank"),
    UHLBACHER_BANK("UhlbacherBank"),
    UMWELT_BANK("UmweltBank"),
    VAKIF_BANK("VakifBank"),
    VOLKS_RAIFFEISEN("Raiffeisenbank"),
    WEBERBANK("Weberbank"),
    WALDECKER_BANK("WaldeckerBank"),
    VTB_BANK("VTBBank"),
    WL_BANK("WLBank"),
    WUESTENROT_BANK("WuestenrotBank"),
    WINTERLINGER_BANK("WinterlingerBank"),
    AKF_BANK("AKFBank"),
    WINTERBACHER_BANK("WinterbacherBank");

    private final String bankName;

    Bank(String bankName) {
        this.bankName = bankName;
    }

    public String getBankName() {
        return bankName;
    }

    public static Bank of(String bankName) {
        return Arrays.stream(values())
                .filter(name -> name.bankName.equals(bankName))
                .findFirst()
                .orElseThrow(IllegalArgumentException::new);
    }
}
