java_library(
    name = "agent-data-availability-tracker-module",
    srcs = glob(
        ["**/*.java"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/agent_data_availability_tracker/client",
        "//third_party:com_google_inject_guice",
    ],
)
