kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-es
  namespace: agents
spec:
  rules:
    #-------------------------------------------------------------------------------------------------------------------
    # All errors alerts
    #-------------------------------------------------------------------------------------------------------------------
    # Refresh urgent alerts
    - alert: RefreshErrorRate100%ES
      expr: |
        # Failed refreshes is 100%
        (count(sum_over_time(tink_agent_refresh_total{action="refresh", outcome=~"unavailable|failed", market="ES", provider_type!="test"}[1h])) by (className,provider,type)
            / count(sum_over_time(tink_agent_refresh_total{market="ES", provider_type!="test"}[1h])) by (className,provider,type) > 0.99)
      for: 15m
      priority: P1
      labels:
        severity: urgent
        who: integration-toros
      annotations:
        description: {{ .Values.kibanaLink }}
          {{ .Values.grafanaLink }}
        summary: Refresh failures is 100% for <{ $labels.className }> ( <{ $labels.provider }> for the last 1h
        tags: {{ .Values.tags }}

    #-------------------------------------------------------------------------------------------------------------------
    # Unknown errors (due to RuntimeException) alerts
    #-------------------------------------------------------------------------------------------------------------------
    # Authentication urgent alerts
    - alert: AuthenticationUnknownErrorRate100%ES
      expr: |
        # Failed logins (due to unknown RuntimeException) is 100%
        (count(sum_over_time(tink_agent_login_total{action="login", outcome="failed", market="ES", provider_type!="test"}[1h])) by (className,provider)
            / count(sum_over_time(tink_agent_login_total{action="login", market="ES", provider_type!="test"}[1h])) by (className,provider) > 0.99)
        # At least this many attempts.
             and count(sum_over_time(tink_agent_login_total{action="login", outcome="failed", market="ES", provider_type!="test"}[1h])) by (className,provider) > 1
      for: 15m
      labels:
        severity: urgent
        priority: P1
        who: integration-toros
      annotations:
        description: {{ .Values.kibanaUnknowErrorsLink12h }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures due to unknown RuntimeExceptions is 100% <{ $labels.className }> <{ $labels.provider }> for the last 1h
        tags: {{ .Values.tags }}

    - alert: AuthenticationTinkInfrastructureErrorRate100%ES
      expr: |
        # Failed logins over 100%
        (count(sum_over_time(tink_agent_login_total{action="login", outcome="failed_due_to_tink_infrastructure_failure", market="ES", provider_type!="test"}[1h])) by (className,provider)
           / count(sum_over_time(tink_agent_login_total{action="login", market="ES", provider_type!="test"}[1h])) by (className,provider) > 0.99)
        # At least this many attempts.
           and count(sum_over_time(tink_agent_login_total{action="login", outcome="failed_due_to_tink_infrastructure_failure", market="ES", provider_type!="test"}[1h])) by (className,provider) > 5
      for: 15m
      labels:
        severity: urgent
        priority: P1
        who: integration-toros
      annotations:
        description: {{ .Values.kibanaLink12h }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures due to Tink infrastructure errors is 100% for <{ $labels.className }> <{ $labels.provider }> for the last 1 hour
        tags: {{ .Values.tags }}

    # Refresh urgent alerts
    - alert: RefreshUnknownErrorRateIs100%ES
      expr: |
        # Failed refreshes (due to unknown RuntimeException) is 100%
        count(sum_over_time(tink_agent_refresh_total{action="refresh", outcome="failed", market="ES", provider_type!="test"}[1h])) by (className,provider,type)
            / count(sum_over_time(tink_agent_refresh_total{market="ES", provider_type!="test"}[1h])) by (className,provider,type) > 0.99
      for: 15m
      labels:
        severity: urgent
        priority: P1
        who: integration-toros
      annotations:
        description: {{ .Values.kibanaUnknowErrorsLink12h }}
          {{ .Values.grafanaLink }}
        summary: Refresh failures due to unknown RuntimeExceptions is 100% for <{ $labels.className }> <{ $labels.provider }> for the last 1h
        tags: {{ .Values.tags }}

    # Authentication ping alerts
    - alert: AuthenticationUnknownErrorRateOver10%ES
      expr: |
        # Failed logins (due to unknown RuntimeException) over 10%
        (count(sum_over_time(tink_agent_login_total{action="login", outcome="failed", market="ES", provider_type!="test"}[1h])) by (className,provider)
            / count(sum_over_time(tink_agent_login_total{action="login", market="ES", provider_type!="test"}[1h])) by (className,provider) > 0.1)
        # At least this many attempts.
             and count(sum_over_time(tink_agent_login_total{action="login", outcome="failed", market="ES", provider_type!="test"}[1h])) by (className,provider) > 1
      for: 15m
      labels:
        severity: ping
        priority: P3
        who: integration-toros
      annotations:
        description: {{ .Values.kibanaUnknowErrorsLink12h }}
          {{ .Values.grafanaLink }}
        summary: Authentication failures due to unknown RuntimeExceptions is over 10% (<{ $value }>) for <{ $labels.className }> <{ $labels.provider }> for the last 1h
        tags: {{ .Values.tags }}

    # Refresh ping alerts
    - alert: RefreshUnknownErrorRateOver10%ES
      expr: |
        # Failed refreshes (due to unknown RuntimeException) over 10%
        (count(sum_over_time(tink_agent_refresh_total{action="refresh", outcome="failed", market="ES", provider_type!="test"}[1h])) by (className,provider,type)
            / count(sum_over_time(tink_agent_refresh_total{market="ES", provider_type!="test"}[1h])) by (className,provider,type) > 0.1)
      for: 15m
      labels:
        severity: ping
        priority: P3
        who: integration-toros
      annotations:
        description: {{ .Values.kibanaUnknowErrorsLink12h }}
          {{ .Values.grafanaLink }}
        summary: Refresh failures due to unknown RuntimeExceptions is over 10% (<{ $value }>) for <{ $labels.className }> <{ $labels.provider }> for the last 1h
        tags: {{ .Values.tags }}
