kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-es
  namespace: agents
spec:
  interval: 10m
  rules:
                      ##### RE #####

    #######################################################
    ### All login success rates - Temporary Errors - RE ###
    #######################################################

    - alert: AllLoginSuccessRatesBelow90AndGreater80WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }}  , market="ES"}[60m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) < 0.9
          and count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) >= 0.8
      for: 15m
      labels:
        severity: ping
        priority: P4
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and all authentication types with temporary errors is between 90 - 80% with the value ( <{ $value }> ) for the last the last 60 minutes
            for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for last 75 minutes.
        tags: {{ .Values.tags }}

    - alert: AllLoginSuccessRatesBelow80AndGreater70WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) < 0.8
          and count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) >= 0.7
      for: 15m
      labels:
        severity: urgent
        priority: P3
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for all authentication types with temporary errors is between 80 - 70% with the value ( <{ $value }> ) for the last the last 60 minutes
          for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for last 75 minutes.
        tags: {{ .Values.tags }}

    - alert: AllLoginSuccessRatesBelow70AndGreater60WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) < 0.7
          and count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) >= 0.6
      for: 5m
      labels:
        severity: urgent
        priority: P2
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for all authentication types with temporary errors is between 70 - 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60 minutes.
        tags: {{ .Values.tags }}

    - alert: AllLoginSuccessRatesBelow60WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) < 0.60
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for all authentication types with temporary errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60 minutes.
        tags: {{ .Values.tags }}

    ##################################################
    ### All login success rates - Bank Errors - RE ###
    ##################################################

    - alert: AllLoginSuccessRatesBelow50WithBankErrorsAndAttemptLimitES_RE
      expr: |
        count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.bankErrorsAuth }} , market="ES"}[60m])) by (provider)
          / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider) < 0.5
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for all Bank types with Bank errors is below 50% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60 minutes.
        tags: {{ .Values.tags }}

    #################################################
    ### All login success rates - All Errors - RE ###
    #################################################

    - alert: AllLoginSuccessRatesBelow50WithAllErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", {{ .Values.allErrorsAuth }} , market="ES"}[50m])) by (provider)
                 / count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, provider_type!="test", market="ES"}[50m])) by (provider) < 0.5
          # At least this many attempts
          and count(count_over_time(tink_agent_login_total{ {{ .Values.reAgents }}, market="ES", provider_type!="test"}[50m])) by (provider) > 3
      for: 10m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for all login types with All Errors is below 50% with the value ( <{ $value }> )
              for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for the last 60 minutes.
        tags: {{ .Values.tags }}

    ##### OpenBanking #####

    ############################################################
    ### All login success rates - Temporary Errors - OB ###
    ############################################################

    - alert: AllLoginSuccessRatesBelow60WithTemporaryErrorsAndAttemptLimitES_OB
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, {{ .Values.temporaryErrorsAuth }}, market="ES"}[50m])) by (provider)
              / count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, provider_type!="test", market="ES"}[50m])) by (provider) < 0.6
          # At least this many attempts
          and count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, market="ES", provider_type!="test"}[50m])) by (provider) > 3
      for: 10m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for OB agents and for all authentication types with temporary errors is below 60% with value ( <{ $value }> )
          for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for the last 60 minutes.
        tags: {{ .Values.tags }}

    ##################################################
    ### All login success rates - Bank Errors - OB ###
    ##################################################

    - alert: AllLoginSuccessRatesBelow60WithBankErrorsAndAttemptLimitES_OB
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, provider_type!="test", {{ .Values.bankErrorsAuth }} , market="ES"}[50m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, provider_type!="test", market="ES"}[50m])) by (provider) < 0.6
          # At least this many attempts
          and count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, market="ES", provider_type!="test"}[50m])) by (provider) > 3
      for: 10m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for OB agents and for all Bank types with Bank errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60m.
        tags: {{ .Values.tags }}

    #################################################
    ### All login success rates - All Errors - OB ###
    #################################################

    - alert: AllLoginSuccessRatesBelow50WithAllErrorsAndAttemptLimitES_OB
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, provider_type!="test", {{ .Values.allErrorsAuth }} , market="ES"}[50m])) by (provider)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, provider_type!="test", market="ES"}[50m])) by (provider) < 0.5
          # At least this many attempts
            and count(count_over_time(tink_agent_login_total{ {{ .Values.obAgents }}, market="ES", provider_type!="test"}[50m])) by (provider) > 3
      for: 10m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for OB agents and for all login types with All Errors is below 50% with the value ( <{ $value }> )
              for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for the last 60 minutes.
        tags: {{ .Values.tags }}

    #### Agent refresh ####

    #################################
    ### AllErrors - Agent Refresh ###
    #################################

    - alert: AgentRefreshesBelow70Greater60DueToAllErrorWithRateLimitES
      expr: |
        count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.allErrorsRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) < 0.7
        and count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.allErrorsRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) >= 0.6
      for: 5m
      labels:
        severity: ping
        priority: P4
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaClassLink90m }}
             {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 70 - 60% because of all issues ( <{ $value }> ) for <{ $labels.className }>
            the last 90 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: AgentRefreshesBelow60Greater50DueToAllErrorWithRateLimitES
      expr: |
        count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.allErrorsRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) < 0.6
        and count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.allErrorsRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) >= 0.5
      for: 5m
      labels:
        severity: urgent
        priority: P2
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaClassLink90m }}
             {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 60 - 50% because of all issues ( <{ $value }> ) for <{ $labels.className }>
              the last 90 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: AgentRefreshesBelow50DueToAllErrorWithRateLimitES
      expr: |
        count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.allErrorsRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) < 0.5
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaClassLink90m }}
             {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is below 50% because of all issues ( <{ $value }> ) for <{ $labels.className }>
              the last 90 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    ###############################################
    ### AllErrors - Partially Completed Refresh ###
    ###############################################

    - alert: AgentRefreshesBelow70Greater60DueToPartiallyCompletedErrorWithRateLimitES
      expr: |
        count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.partiallyCompletedErrorRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) < 0.7
        and count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.partiallyCompletedErrorRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) >= 0.6
      for: 5m
      labels:
        severity: ping
        priority: P4
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaClassLink90m }}
             {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 70 - 60% because of all issues ( <{ $value }> ) for <{ $labels.className }>
               the last 90 minutes.
        tags: {{ .Values.tags }}

    - alert: AgentRefreshesBelow60Greater50DueToPartiallyCompletedErrorWithRateLimitES
      expr: |
        count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.partiallyCompletedErrorRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) < 0.6
        and count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.partiallyCompletedErrorRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) >= 0.5
      for: 5m
      labels:
        severity: urgent
        priority: P2
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaClassLink90m }}
             {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is between 60 - 50% because of all issues ( <{ $value }> ) for <{ $labels.className }>
               the last 90 minutes.
        tags: {{ .Values.tags }}

    - alert: AgentRefreshesBelow50DueToPartiallyCompletedErrorWithRateLimitES
      expr: |
        count(count_over_time(tink_agent_refresh_total{ provider_type!="test", {{ .Values.partiallyCompletedErrorRefresh }}, market="ES"}[90m])) by (className,type)
          / count(count_over_time(tink_agent_refresh_total{ provider_type!="test", market="ES"}[90m])) by (className,type) < 0.5
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaClassLink90m }}
             {{ .Values.grafanaLink }}
        summary: Refresh unavailable rate is below 50% because of all issues ( <{ $value }> ) for <{ $labels.className }>
               the last 90 minutes.
        tags: {{ .Values.tags }}
