kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-es-ng
  namespace: agents
spec:
  interval: 10m
  rules:

    #########################################################
    ### Split login success rates - Temporary Errors - RE ###
    #########################################################

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow90AndGreater80WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.9
          and count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) >= 0.8
      for: 5m
      labels:
        severity: ping
        priority: P4
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for one of login type with temporary errors is between 90 - 80% with the value ( <{ $value }> ) for the last the last 60 minutes
          for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for last 60 minutes.
        tags: {{ .Values.tags }}

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow80AndGreater70WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.8
          and count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) >= 0.7
      for: 5m
      labels:
        severity: urgent
        priority: P3
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for one of login type with temporary errors is between 80 - 70% with the value ( <{ $value }> ) for the last the last 60 minutes
              for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for last 60 minutes.
        tags: {{ .Values.tags }}

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow70AndGreater60WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.7
          and count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) >= 0.6
      for: 5m
      labels:
        severity: urgent
        priority: P2
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for one of login type with temporary errors is between 70 - 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60 minutes.
        tags: {{ .Values.tags }}

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow60WithTemporaryErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.6
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for one of login type with temporary errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
              the last 60 minutes.
        tags: {{ .Values.tags }}

    ####################################################
    ### Split login success rates - Bank Errors - RE ###
    ####################################################

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow50WithBankErrorsAndAttemptLimitES_RE
      expr: |
        count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.bankErrorsAuth }} , market="ES"}[60m])) by (provider, action)
          / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.5
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for one of login type with Bank errors is below 50% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60 minutes.
        tags: {{ .Values.tags }}

    ###################################################
    ### Split login success rates - All Errors - RE ###
    ###################################################
    # As there is a lot of errors for incorrect credentials and blocked account for Spanish market login-manual action is excluded from this alert
    # to decrease the number of non-actionable alerts. If something will be really wrong it will be covered by `All login success rates` alert

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow50WithAllErrorsAndAttemptLimitES_RE
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.loginActionsWithoutManual }}, {{ .Values.reAgents }}, provider_type!="test", {{ .Values.allErrorsAuth }} , market="ES"}[60m])) by (provider, action)
                / count(count_over_time(tink_agent_login_total{ {{ .Values.loginActionsWithoutManual }}, {{ .Values.reAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.5
          # At least this many attempts
          and count(count_over_time(tink_agent_login_total{ {{ .Values.loginActionsWithoutManual }}, {{ .Values.reAgents }}, market="ES", provider_type!="test"}[60m])) by (provider, action) > 3
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for RE agents and for one of login type with All Errors is below 50% with the value ( <{ $value }> )
              for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for the last 60 minutes.
        tags: {{ .Values.tags }}

    ##### OpenBanking #####

    #########################################################
    ### Split login success rates - Temporary Errors - OB ###
    #########################################################

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow60WithTemporaryErrorsAndAttemptLimitES_OB
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.obAgents }}, provider_type!="test", {{ .Values.temporaryErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.obAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.6
          # At least this many attempts
          and count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.obAgents }}, market="ES", provider_type!="test"}[60m])) by (provider, action) > 3
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for OB agents and for one of login type with temporary errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60m.
        tags: {{ .Values.tags }}

    ####################################################
    ### Split login success rates - Bank Errors - OB ###
    ####################################################

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow60WithBankErrorsAndAttemptLimitES_OB
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.obAgents }}, provider_type!="test", {{ .Values.bankErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.obAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.6
          # At least this many attempts
          and count(count_over_time(tink_agent_login_total{ {{ .Values.allLoginActions }}, {{ .Values.obAgents }}, market="ES", provider_type!="test"}[60m])) by (provider, action) > 3
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for OB agents and for one of login type with Bank errors is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
             the last 60m.
        tags: {{ .Values.tags }}

    ###################################################
    ### Split login success rates - All Errors - OB ###
    ###################################################
    # As there is a lot of errors for incorrect credentials and blocked account for Spanish market login-manual action is excluded from this alert
    # to decrease the number of non-actionable alerts. If something will be really wrong it will be covered by `All login success rates` alert

    - alert: EXPERIMENTAL_SplitLoginSuccessRatesBelow50WithAllErrorsAndAttemptLimitES_OB
      expr: |
          count(count_over_time(tink_agent_login_total{ {{ .Values.loginActionsWithoutManual }}, {{ .Values.obAgents }}, provider_type!="test", {{ .Values.allErrorsAuth }} , market="ES"}[60m])) by (provider, action)
            / count(count_over_time(tink_agent_login_total{ {{ .Values.loginActionsWithoutManual }}, {{ .Values.obAgents }}, provider_type!="test", market="ES"}[60m])) by (provider, action) < 0.5
          # At least this many attempts
          and count(count_over_time(tink_agent_login_total{ {{ .Values.loginActionsWithoutManual }}, {{ .Values.obAgents }}, market="ES", provider_type!="test"}[60m])) by (provider, action) > 3
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaLink }}
             {{ .Values.grafanaLink }}
        summary: Login success rate for OB agents and for one of login type with All Errors is below 50% with the value ( <{ $value }> )
             for <{ $labels.className }> ( <{ $labels.provider }> ) and it was below for the last 60 minutes.
        tags: {{ .Values.tags }}
