kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts
  namespace: agents
spec:
  rules:

### Not able to refresh certain refreshable items
  - alert: ProviderNotAbleToFetchCheckingAccounts
    expr: |
      sum(increase(tink_accounts_refresh_total[1h])) BY (provider) > 10 and
      ratio:tink_no_checking_accounts_fetched:delta1h > 0.99 and
      ratio:tink_no_checking_accounts_fetched:delta1w < 0.2
    for: 2h
    labels:
      severity: urgent
      who: integration
    annotations:
      description: No checking accounts fetched for <{ $labels.provider }>
        for 2 hours. Over 80% of users used to have checking accounts.
      summary: No checking accounts fetched for <{ $labels.provider }>
        for 2 hours.

  - alert: ProviderNotAbleToFetchSavingAccounts
    expr: |
      sum(increase(tink_accounts_refresh_total[1h])) BY (provider) > 10 and
      ratio:tink_no_savings_accounts_fetched:delta1h > 0.99 and
      ratio:tink_no_savings_accounts_fetched:delta1w < 0.8
    for: 2h
    labels:
      severity: urgent
      who: integration
    annotations:
      description: No savings accounts fetched for <{ $labels.provider }>
        for 2 hours. Over 20% of users used to have saving accounts.
      summary: No savings accounts fetched for <{ $labels.provider }>
        for 2 hours.

  - alert: ProviderNotAbleToFetchCreditCardAccounts
    expr: |
      sum(increase(tink_accounts_refresh_total[1h])) BY (provider) > 10 and
      ratio:tink_no_creditcards_accounts_fetched:delta1h > 0.99 and
      ratio:tink_no_creditcards_accounts_fetched:delta1w < 0.85
    for: 2h
    labels:
      severity: urgent
      who: integration
    annotations:
      description: No credit card accounts fetched for <{ $labels.provider }>
        for 2 hours. Over 15% of users used to have credit card accounts.
      summary: No credit card accounts fetched for <{ $labels.provider }>
        for 2 hours.

  - alert: ProviderNotAbleToFetchInvestmentAccounts
    expr: |
      sum(increase(tink_accounts_refresh_total[1h])) BY (provider) > 10 and
      ratio:tink_no_investment_accounts_fetched:delta1h > 0.99 and
      ratio:tink_no_investment_accounts_fetched:delta1w < 0.9
    for: 2h
    labels:
      severity: urgent
      who: integration
    annotations:
      description: No investment accounts fetched for <{ $labels.provider }>
        for 2 hours. Over 15% of users used to have investment accounts.
      summary: No investment card accounts fetched for <{ $labels.provider }>
        for 2 hours.

  - alert: ProviderNotAbleToFetchLoanAccounts
    expr: |
      sum(increase(tink_accounts_refresh_total[1h])) BY (provider) > 10 and
      ratio:tink_no_loan_accounts_fetched:delta1h > 0.99 and
      ratio:tink_no_loan_accounts_fetched:delta1w < 0.9
    for: 2h
    labels:
      severity: urgent
      who: integration
    annotations:
      description: No loan accounts fetched for <{ $labels.provider }>
        for 2 hours. Over 15% of users used to have loan accounts.
      summary: No loan card accounts fetched for <{ $labels.provider }>
        for 2 hours.

### Precomputations.
    # Calculate the ratio of not fetching any accounts (with certain type)
    # over certain interval of time.
  - record: ratio:tink_no_checking_accounts_fetched:delta1h
    expr: sum(increase(tink_no_accounts_fetched_total {type="CHECKING"} [1h])) BY (provider)
        / sum(increase(tink_accounts_refresh_total[1h])) BY (provider)
  - record: ratio:tink_no_savings_accounts_fetched:delta1h
    expr: sum(increase(tink_no_accounts_fetched_total {type="SAVINGS"} [1h])) BY (provider)
        / sum(increase(tink_accounts_refresh_total[1h])) BY (provider)

  - record: ratio:tink_no_creditcards_accounts_fetched:delta1h
    expr: sum(increase(tink_no_accounts_fetched_total {type="CREDIT_CARD"} [1h])) BY (provider)
        / sum(increase(tink_accounts_refresh_total[1h])) BY (provider)

  - record: ratio:tink_no_investment_accounts_fetched:delta1h
    expr: sum(increase(tink_no_accounts_fetched_total {type="INVESTMENT"} [1h])) BY (provider)
        / sum(increase(tink_accounts_refresh_total[1h])) BY (provider)

  - record: ratio:tink_no_loan_accounts_fetched:delta1h
    expr: sum(increase(tink_no_accounts_fetched_total {type="LOAN"} [1h])) BY (provider)
        / sum(increase(tink_accounts_refresh_total[1h])) BY (provider)

    # Calculate the the ration of provider errors (without authentication errors).
  - record: ratio:tink_provider_errors:delta60m
    expr: 100 * ((sum(increase(tink_temporary_errors_total[1h])) BY (provider)) /
      (sum(increase(tink_executions_total[1h])) BY (provider)))

# Payments SE market dashboard
  - record: sum:tink_transfers_in_sweden:delta15m
    expr: sum(increase(tink_agent_transfer_total{market="SE"}[15m])) or on() vector(0)

  - record: sum:tink_transfers_in_sweden:delta12h
    expr: sum(increase(tink_agent_transfer_total{market="SE"}[12h])) or on() vector(0)

  - record: sum:tink_successful_transfers_in_sweden:delta15m
    expr: sum(increase(tink_agent_transfer_total{market="SE", outcome="completed"}[15m])) or on() vector(0)

  - record: sum:tink_successful_transfers_in_sweden:delta12h
    expr: sum(increase(tink_agent_transfer_total{market="SE", outcome="completed"}[12h])) or on() vector(0)

  - record: sum:tink_failed_transfers_in_sweden:delta15m
    expr: sum(increase(tink_agent_transfer_total{market="SE", outcome="failed"}[15m])) or on() vector(0)

  - record: sum:tink_failed_transfers_in_sweden:delta12h
    expr: sum(increase(tink_agent_transfer_total{market="SE", outcome="failed"}[12h])) or on() vector(0)

  - record: sum:tink_cancelled_transfers_in_sweden:delta15m
    expr: sum(increase(tink_agent_transfer_total{market="SE", outcome="cancelled"}[15m])) or on() vector(0)

  - record: sum:tink_cancelled_transfers_in_sweden:delta12h
    expr: sum(increase(tink_agent_transfer_total{market="SE", outcome="cancelled"}[12h])) or on() vector(0)

  # Precompute realtime banking metrics
  - record: ratio:tink_aggregation_market_success:delta5m
    expr: sum(increase(tink_aggregation_successful_market_total[5m])) by (market)
        / sum(increase(tink_aggregation_total_market_total[5m])) by (market) > 0

  - record: ratio:tink_aggregation_operation_success:delta5m
    expr: sum(increase(tink_aggregation_successful_operations_total[5m])) by (operation)
       / sum(increase(tink_aggregation_total_operations_total[5m])) by (operation) > 0

  - record: ratio:tink_aggregation_market_operation_success:delta5m
    expr: sum(increase(tink_aggregation_successful_market_operations_total[5m])) by (operation, market)
      / sum(increase(tink_aggregation_total_market_operations_total[5m])) by (operation, market) > 0

  # Precompute statistics
  - record: statistics:tink_aggregation_market_success:delta5m:avg1w
    expr: avg_over_time((ratio:tink_aggregation_market_success:delta5m > 0)[1w:])

  - record: statistics:tink_aggregation_market_success:delta5m:stddev1w
    expr: stddev_over_time((ratio:tink_aggregation_market_success:delta5m > 0)[1w:])

  - record: statistics:tink_aggregation_operation_success:delta5m:avg1w
    expr: avg_over_time((ratio:tink_aggregation_operation_success:delta5m > 0)[1w:])

  - record: statistics:tink_aggregation_operation_success:delta5m:stddev1w
    expr: stddev_over_time((ratio:tink_aggregation_operation_success:delta5m > 0)[1w:])

  - record: statistics:tink_aggregation_market_operation_success:delta5m:avg1w
    expr: avg_over_time((ratio:tink_aggregation_market_operation_success:delta5m > 0)[1w:])

  - record: statistics:tink_aggregation_market_operation_success:delta5m:stddev1w
    expr: stddev_over_time((ratio:tink_aggregation_market_operation_success:delta5m > 0)[1w:])
