package se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar;

import org.junit.Assert;
import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.creditcard.rpc.FetchCreditCardResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.transactional.rpc.FetchTransactionResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.transactional.rpc.FetchUpcomingResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.rpc.ListAccountsResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class LansforsakringarTransactionFetcherTest {

    private static final String TRANSACTIONS =
            "{\n"
                    + "\t\"id\": null,\n"
                    + "\t\"response\": {\n"
                    + "\t\t\"moreExists\": true,\n"
                    + "\t\t\"transactions\": [{\n"
                    + "\t\t\t\"id\": \"200309042-1516\",\n"
                    + "\t\t\t\"text\": \"Kortköp\",\n"
                    + "\t\t\t\"amount\": {\n"
                    + "\t\t\t\t\"currency\": \"SEK\",\n"
                    + "\t\t\t\t\"value\": -32.15\n"
                    + "\t\t\t},\n"
                    + "\t\t\t\"accountingDate\": \"2020-02-11\",\n"
                    + "\t\t\t\"transactionDate\": \"2020-02-10\",\n"
                    + "\t\t\t\"currencyDate\": \"2020-02-11\",\n"
                    + "\t\t\t\"unconstrainedText\": \"Amazon Video*U458N19A5,amazon.com,LU\",\n"
                    + "\t\t\t\"balance\": 690.97,\n"
                    + "\t\t\t\"marketingCode\": null,\n"
                    + "\t\t\t\"transactionType\": \"CAR\",\n"
                    + "\t\t\t\"upcomingDeposit\": false\n"
                    + "\t\t}]\n"
                    + "}, \n"
                    + "\"errors\": null\n"
                    + "}\n";

    private static final String ACCOUNTS =
            "{\n"
                    + "\t\"mainAndCoAccounts\": [{\n"
                    + "\t\t\"accountNumber\": \"90239056657\",\n"
                    + "\t\t\"balance\": 1336.0,\n"
                    + "\t\t\"accountName\": \"Lägenhetskonto\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"CO_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90239056703\",\n"
                    + "\t\t\"balance\": 690.97,\n"
                    + "\t\t\"accountName\": \"PrivatPierre\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90239111313\",\n"
                    + "\t\t\"balance\": 948.07,\n"
                    + "\t\t\"accountName\": \"Gemensamt\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"CO_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90245316789\",\n"
                    + "\t\t\"balance\": 1000.0,\n"
                    + "\t\t\"accountName\": \"GemensamtSpar\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90239056711\",\n"
                    + "\t\t\"balance\": 10000.0,\n"
                    + "\t\t\"accountName\": \"SparPierre\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": {\n"
                    + "\t\t\t\"name\": \"Sparande\",\n"
                    + "\t\t\t\"accountNumber\": \"90239056711\",\n"
                    + "\t\t\t\"savingsGoalId\": \"3c86b69d1e\",\n"
                    + "\t\t\t\"goalAmount\": 25000.0,\n"
                    + "\t\t\t\"completedInPercent\": 0.4,\n"
                    + "\t\t\t\"sequenceNumber\": null,\n"
                    + "\t\t\t\"estimatedCompletionDate\": null,\n"
                    + "\t\t\t\"goalDate\": \"2020-10-25\"\n"
                    + "\t\t},\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"SAVINGS\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": true,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}],\n"
                    + "\t\"dispositionAccounts\": [],\n"
                    + "\t\"cards\": [],\n"
                    + "\t\"errorMessages\": []\n"
                    + "}";

    final String UPCOMING_TRANSACTIONS =
            "{\n"
                    + "\t\"upcomingTransactions\": [{\n"
                    + "\t\t\"id\": \"232455503-25\",\n"
                    + "\t\t\"description\": \"SKARPNÄCKS SDF C/O SERVIC\",\n"
                    + "\t\t\"amount\": -1478.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"7151710008941763\",\n"
                    + "\t\t\t\"giroNumber\": \"964802-3\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-05-05.32.02.394767\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"232455857-25\",\n"
                    + "\t\t\"description\": \"ENERGIKUNDSERVICE SVERIGE\",\n"
                    + "\t\t\"amount\": -2235.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"4010338760031\",\n"
                    + "\t\t\t\"giroNumber\": \"4875503-7\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-05-06.30.12.796691\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"233161778-25\",\n"
                    + "\t\t\"description\": \"COM HEM AB\",\n"
                    + "\t\t\"amount\": -429.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"208988924428\",\n"
                    + "\t\t\t\"giroNumber\": \"5361-1737\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-07-12.16.48.168365\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"221720580-25\",\n"
                    + "\t\t\"description\": \"TRÄNGSELSKATT TRANSPORTSTYRELSEN\",\n"
                    + "\t\t\"amount\": -22.0,\n"
                    + "\t\t\"date\": \"2020-03-02\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"18139701605872471\",\n"
                    + "\t\t\t\"giroNumber\": \"282-4647\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-01-20-09.33.48.584961\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-03-02\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}],\n"
                    + "\t\"errorMessages\": [],\n"
                    + "\t\"sumOfUpcomingTransactions\": -4164.0,\n"
                    + "\t\"currentMonth\": {\n"
                    + "\t\t\"year\": \"2020\",\n"
                    + "\t\t\"month\": \"Februari\",\n"
                    + "\t\t\"sumUpcomingTransactions\": -4142.0,\n"
                    + "\t\t\"currentDate\": \"2020-02-13\"\n"
                    + "\t}\n"
                    + "}";

    private final String CARDS_LIST =
            "{\n"
                    + "\t\"cards\": [{\n"
                    + "\t\t\"cardName\": \"Bankkort Privat\",\n"
                    + "\t\t\"balance\": 0.0,\n"
                    + "\t\t\"cardNumber\": \"5758\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardTypeAsString\": \"DEBIT\",\n"
                    + "\t\t\"connectedAccountNumber\": \"90239056703\",\n"
                    + "\t\t\"cardLimit\": 0.0,\n"
                    + "\t\t\"cardAvailable\": 0.0,\n"
                    + "\t\t\"expires\": \"08/21\",\n"
                    + "\t\t\"reservedAmount\": 0.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"2\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": {\n"
                    + "\t\t\t\"accountNumber\": \"90239056703\",\n"
                    + "\t\t\t\"balance\": 690.97,\n"
                    + "\t\t\t\"accountName\": \"PrivatPierre\",\n"
                    + "\t\t\t\"productCode\": \"11\",\n"
                    + "\t\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\t\"youthAccount\": false,\n"
                    + "\t\t\t\"transferFrom\": true,\n"
                    + "\t\t\t\"transferTo\": true,\n"
                    + "\t\t\t\"type\": \"CHECKING\"\n"
                    + "\t\t},\n"
                    + "\t\t\"accountDetailsAvailable\": true\n"
                    + "\t}, {\n"
                    + "\t\t\"cardName\": \"Bankkort Privat\",\n"
                    + "\t\t\"balance\": 0.0,\n"
                    + "\t\t\"cardNumber\": \"8778\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardTypeAsString\": \"CREDIT\",\n"
                    + "\t\t\"connectedAccountNumber\": \"90239111313\",\n"
                    + "\t\t\"cardLimit\": 0.0,\n"
                    + "\t\t\"cardAvailable\": 0.0,\n"
                    + "\t\t\"expires\": \"08/21\",\n"
                    + "\t\t\"reservedAmount\": 0.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"2\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": {\n"
                    + "\t\t\t\"accountNumber\": \"90239111313\",\n"
                    + "\t\t\t\"balance\": 948.07,\n"
                    + "\t\t\t\"accountName\": \"Gemensamt\",\n"
                    + "\t\t\t\"productCode\": \"11\",\n"
                    + "\t\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\t\"youthAccount\": false,\n"
                    + "\t\t\t\"transferFrom\": true,\n"
                    + "\t\t\t\"transferTo\": true,\n"
                    + "\t\t\t\"type\": \"CHECKING\"\n"
                    + "\t\t},\n"
                    + "\t\t\"accountDetailsAvailable\": true\n"
                    + "\t}]\n"
                    + "}";

    @Test
    public void testTransactionParsing() {
        FetchTransactionResponse ftr =
                SerializationUtils.deserializeFromString(
                        TRANSACTIONS, FetchTransactionResponse.class);
        Assert.assertTrue(ftr.getResponse().hasMore());
        Assert.assertNotNull(ftr.getResponse().getTransactions());
        Assert.assertEquals(
                ftr.getResponse().getTransactions().get(0).getTransactionDate(), "2020-02-10");
    }

    @Test
    public void testAccountParsing() {
        ListAccountsResponse lar =
                SerializationUtils.deserializeFromString(ACCOUNTS, ListAccountsResponse.class);
        Assert.assertNotNull(lar.getMainAndCoAccounts());
        Assert.assertEquals(lar.getMainAndCoAccounts().get(0).getAccountNumber(), "90239056657");
    }

    @Test
    public void testUpcomingTransactionParsing() {
        FetchUpcomingResponse fur =
                SerializationUtils.deserializeFromString(
                        UPCOMING_TRANSACTIONS, FetchUpcomingResponse.class);
        Assert.assertNotNull(fur.getUpcomingTransactions());
        Assert.assertEquals(fur.getUpcomingTransactions().get(0).getDate(), "2020-02-28");
    }

    @Test
    public void testListCardsParsing() {
        FetchCreditCardResponse fccr =
                SerializationUtils.deserializeFromString(CARDS_LIST, FetchCreditCardResponse.class);
        Assert.assertNotNull(fccr.getCards());
    }

}
