package se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar;

import org.junit.Assert;
import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.creditcard.rpc.FetchCreditCardResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.investment.rpc.FetchPensionResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.investment.rpc.FetchPensionWithLifeInsuranceAgreementResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.investment.rpc.FetchPensionWithLifeInsuranceResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.transactional.rpc.FetchAccountsResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.transactional.rpc.FetchTransactionResponse;
import se.tink.backend.aggregation.agents.nxgen.se.banks.lansforsakringar.fetcher.transactional.rpc.FetchUpcomingResponse;
import se.tink.libraries.serialization.utils.SerializationUtils;

public class LansforsakringarEntitiesDeserializationTest {

    private static final String TRANSACTIONS =
            "{\n"
                    + "\t\"id\": null,\n"
                    + "\t\"response\": {\n"
                    + "\t\t\"moreExists\": true,\n"
                    + "\t\t\"transactions\": [{\n"
                    + "\t\t\t\"id\": \"200309042-1516\",\n"
                    + "\t\t\t\"text\": \"Kortköp\",\n"
                    + "\t\t\t\"amount\": {\n"
                    + "\t\t\t\t\"currency\": \"SEK\",\n"
                    + "\t\t\t\t\"value\": -32.15\n"
                    + "\t\t\t},\n"
                    + "\t\t\t\"accountingDate\": \"2020-02-11\",\n"
                    + "\t\t\t\"transactionDate\": \"2020-02-10\",\n"
                    + "\t\t\t\"currencyDate\": \"2020-02-11\",\n"
                    + "\t\t\t\"unconstrainedText\": \"Amazon Video*U458N19A5,amazon.com,LU\",\n"
                    + "\t\t\t\"balance\": 690.97,\n"
                    + "\t\t\t\"marketingCode\": null,\n"
                    + "\t\t\t\"transactionType\": \"CAR\",\n"
                    + "\t\t\t\"upcomingDeposit\": false\n"
                    + "\t\t}]\n"
                    + "}, \n"
                    + "\"errors\": null\n"
                    + "}\n";

    private static final String ACCOUNTS =
            "{\n"
                    + "\t\"mainAndCoAccounts\": [{\n"
                    + "\t\t\"accountNumber\": \"90239056657\",\n"
                    + "\t\t\"balance\": 1336.0,\n"
                    + "\t\t\"accountName\": \"Lägenhetskonto\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"CO_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90239056703\",\n"
                    + "\t\t\"balance\": 690.97,\n"
                    + "\t\t\"accountName\": \"PrivatPierre\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90239111313\",\n"
                    + "\t\t\"balance\": 948.07,\n"
                    + "\t\t\"accountName\": \"Gemensamt\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"CO_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90245316789\",\n"
                    + "\t\t\"balance\": 1000.0,\n"
                    + "\t\t\"accountName\": \"GemensamtSpar\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": null,\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"CHECKING\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": false,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}, {\n"
                    + "\t\t\"accountNumber\": \"90239056711\",\n"
                    + "\t\t\"balance\": 10000.0,\n"
                    + "\t\t\"accountName\": \"SparPierre\",\n"
                    + "\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\"savingsGoal\": {\n"
                    + "\t\t\t\"name\": \"Sparande\",\n"
                    + "\t\t\t\"accountNumber\": \"90239056711\",\n"
                    + "\t\t\t\"savingsGoalId\": \"3c86b69d1e\",\n"
                    + "\t\t\t\"goalAmount\": 25000.0,\n"
                    + "\t\t\t\"completedInPercent\": 0.4,\n"
                    + "\t\t\t\"sequenceNumber\": null,\n"
                    + "\t\t\t\"estimatedCompletionDate\": null,\n"
                    + "\t\t\t\"goalDate\": \"2020-10-25\"\n"
                    + "\t\t},\n"
                    + "\t\t\"isSelectedStartPageEngagement\": true,\n"
                    + "\t\t\"localAccount\": false,\n"
                    + "\t\t\"bankName\": null,\n"
                    + "\t\t\"type\": \"SAVINGS\",\n"
                    + "\t\t\"savedRecipient\": false,\n"
                    + "\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\"savingsGoalAllowed\": true,\n"
                    + "\t\t\"fixedRateAccount\": false,\n"
                    + "\t\t\"accountInfoText\": null,\n"
                    + "\t\t\"relationToAccount\": \"MAIN_ACCOUNT_HOLDER\",\n"
                    + "\t\t\"transferFrom\": true,\n"
                    + "\t\t\"transferTo\": true,\n"
                    + "\t\t\"youthAccount\": false\n"
                    + "\t}],\n"
                    + "\t\"dispositionAccounts\": [],\n"
                    + "\t\"cards\": [],\n"
                    + "\t\"errorMessages\": []\n"
                    + "}";

    private final String UPCOMING_TRANSACTIONS =
            "{\n"
                    + "\t\"upcomingTransactions\": [{\n"
                    + "\t\t\"id\": \"232455503-25\",\n"
                    + "\t\t\"description\": \"SKARPNÄCKS SDF C/O SERVIC\",\n"
                    + "\t\t\"amount\": -1478.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"7151710008941763\",\n"
                    + "\t\t\t\"giroNumber\": \"964802-3\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-05-05.32.02.394767\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"232455857-25\",\n"
                    + "\t\t\"description\": \"ENERGIKUNDSERVICE SVERIGE\",\n"
                    + "\t\t\"amount\": -2235.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"4010338760031\",\n"
                    + "\t\t\t\"giroNumber\": \"4875503-7\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-05-06.30.12.796691\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"233161778-25\",\n"
                    + "\t\t\"description\": \"COM HEM AB\",\n"
                    + "\t\t\"amount\": -429.0,\n"
                    + "\t\t\"date\": \"2020-02-28\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"208988924428\",\n"
                    + "\t\t\t\"giroNumber\": \"5361-1737\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-02-07-12.16.48.168365\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-02-28\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}, {\n"
                    + "\t\t\"id\": \"221720580-25\",\n"
                    + "\t\t\"description\": \"TRÄNGSELSKATT TRANSPORTSTYRELSEN\",\n"
                    + "\t\t\"amount\": -22.0,\n"
                    + "\t\t\"date\": \"2020-03-02\",\n"
                    + "\t\t\"type\": \"PAYMENT\",\n"
                    + "\t\t\"typeAsString\": \"BETALNING\",\n"
                    + "\t\t\"transferInfo\": null,\n"
                    + "\t\t\"paymentInfo\": {\n"
                    + "\t\t\t\"reference\": \"18139701605872471\",\n"
                    + "\t\t\t\"giroNumber\": \"282-4647\",\n"
                    + "\t\t\t\"invoiceId\": \"2020-01-20-09.33.48.584961\",\n"
                    + "\t\t\t\"paymentType\": \"ElectronicInvoice\",\n"
                    + "\t\t\t\"modificationAllowed\": true,\n"
                    + "\t\t\t\"debitDate\": \"2020-03-02\",\n"
                    + "\t\t\t\"thirdPartyProviderName\": null,\n"
                    + "\t\t\t\"thirdPartyProviderPaymentReference\": null\n"
                    + "\t\t},\n"
                    + "\t\t\"loanInfo\": null,\n"
                    + "\t\t\"directDebitInfo\": null,\n"
                    + "\t\t\"statusInfo\": null\n"
                    + "\t}],\n"
                    + "\t\"errorMessages\": [],\n"
                    + "\t\"sumOfUpcomingTransactions\": -4164.0,\n"
                    + "\t\"currentMonth\": {\n"
                    + "\t\t\"year\": \"2020\",\n"
                    + "\t\t\"month\": \"Februari\",\n"
                    + "\t\t\"sumUpcomingTransactions\": -4142.0,\n"
                    + "\t\t\"currentDate\": \"2020-02-13\"\n"
                    + "\t}\n"
                    + "}";

    private final String CARDS_LIST =
            "{\n"
                    + "\t\"cards\": [{\n"
                    + "\t\t\"cardName\": \"Bankkort Privat\",\n"
                    + "\t\t\"balance\": 0.0,\n"
                    + "\t\t\"cardNumber\": \"5758\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardTypeAsString\": \"DEBIT\",\n"
                    + "\t\t\"connectedAccountNumber\": \"90239056703\",\n"
                    + "\t\t\"cardLimit\": 0.0,\n"
                    + "\t\t\"cardAvailable\": 0.0,\n"
                    + "\t\t\"expires\": \"08/21\",\n"
                    + "\t\t\"reservedAmount\": 0.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"2\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": {\n"
                    + "\t\t\t\"accountNumber\": \"90239056703\",\n"
                    + "\t\t\t\"balance\": 690.97,\n"
                    + "\t\t\t\"accountName\": \"PrivatPierre\",\n"
                    + "\t\t\t\"productCode\": \"11\",\n"
                    + "\t\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\t\"youthAccount\": false,\n"
                    + "\t\t\t\"transferFrom\": true,\n"
                    + "\t\t\t\"transferTo\": true,\n"
                    + "\t\t\t\"type\": \"CHECKING\"\n"
                    + "\t\t},\n"
                    + "\t\t\"accountDetailsAvailable\": true\n"
                    + "\t}, {\n"
                    + "\t\t\"cardName\": \"Bankkort Privat\",\n"
                    + "\t\t\"balance\": 0.0,\n"
                    + "\t\t\"cardNumber\": \"8778\",\n"
                    + "\t\t\"status\": \"ACTIVE\",\n"
                    + "\t\t\"cardTypeAsString\": \"CREDIT\",\n"
                    + "\t\t\"connectedAccountNumber\": \"90239111313\",\n"
                    + "\t\t\"cardLimit\": 0.0,\n"
                    + "\t\t\"cardAvailable\": 0.0,\n"
                    + "\t\t\"expires\": \"08/21\",\n"
                    + "\t\t\"reservedAmount\": 0.0,\n"
                    + "\t\t\"aviAmount\": 0.0,\n"
                    + "\t\t\"versionNumber\": \"2\",\n"
                    + "\t\t\"statusText\": \"Giltigt\",\n"
                    + "\t\t\"replaced\": false,\n"
                    + "\t\t\"cardAccountDetails\": {\n"
                    + "\t\t\t\"accountNumber\": \"90239111313\",\n"
                    + "\t\t\t\"balance\": 948.07,\n"
                    + "\t\t\t\"accountName\": \"Gemensamt\",\n"
                    + "\t\t\t\"productCode\": \"11\",\n"
                    + "\t\t\t\"clearingNumber\": \"0\",\n"
                    + "\t\t\t\"ledger\": \"DEPOSIT\",\n"
                    + "\t\t\t\"youthAccount\": false,\n"
                    + "\t\t\t\"transferFrom\": true,\n"
                    + "\t\t\t\"transferTo\": true,\n"
                    + "\t\t\t\"type\": \"CHECKING\"\n"
                    + "\t\t},\n"
                    + "\t\t\"accountDetailsAvailable\": true\n"
                    + "\t}]\n"
                    + "}";

    private final String PENSION_OVERVIEW =
            "{\n"
                    + "\t\"ipsPensionsResponseModel\": {\n"
                    + "\t\t\"ipsPensions\": [],\n"
                    + "\t\t\"error\": null\n"
                    + "\t},\n"
                    + "\t\"livPensionsResponseModel\": {\n"
                    + "\t\t\"privatePensions\": [],\n"
                    + "\t\t\"occupationalPensions\": [{\n"
                    + "\t\t\t\"name\": \"Ålderspension Fond via Friplan 86687217\",\n"
                    + "\t\t\t\"agreementId\": \"86687217_1\",\n"
                    + "\t\t\t\"value\": 217527.62,\n"
                    + "\t\t\t\"hasDetails\": true,\n"
                    + "\t\t\t\"footNotes\": []\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"name\": \"Ålderspension Fond via Friplan 86719994\",\n"
                    + "\t\t\t\"agreementId\": \"86719994_1\",\n"
                    + "\t\t\t\"value\": 81115.35,\n"
                    + "\t\t\t\"hasDetails\": true,\n"
                    + "\t\t\t\"footNotes\": []\n"
                    + "\t\t}],\n"
                    + "\t\t\"capitalInsurances\": [],\n"
                    + "\t\t\"error\": null\n"
                    + "\t},\n"
                    + "\t\"footNotes\": {},\n"
                    + "\t\"totalValue\": 298642.97\n"
                    + "}";

    private final String PENSION_ENGAGEMENTS =
            "{\n"
                    + "\t\"id\": null,\n"
                    + "\t\"response\": {\n"
                    + "\t\t\"hasSavingEngagement\": null,\n"
                    + "\t\t\"hasProtectionEngagement\": null,\n"
                    + "\t\t\"engagements\": [{\n"
                    + "\t\t\t\"name\": \"Stefan Edqvist\",\n"
                    + "\t\t\t\"productName\": \"Tjänstepensionsplan\",\n"
                    + "\t\t\t\"id\": \"86687217\",\n"
                    + "\t\t\t\"type\": \"AGREEMENT\",\n"
                    + "\t\t\t\"riskCovers\": [\"DEATH\"],\n"
                    + "\t\t\t\"status\": \"PAID_UP\",\n"
                    + "\t\t\t\"investmentValue\": 217527.62,\n"
                    + "\t\t\t\"agreedPremium\": null,\n"
                    + "\t\t\t\"premiumModelTerm\": null,\n"
                    + "\t\t\t\"owner\": \"Starcounter AB\",\n"
                    + "\t\t\t\"ownerId\": \"165565883278\",\n"
                    + "\t\t\t\"productType\": \"PENSION_PLAN\",\n"
                    + "\t\t\t\"productCategory\": \"OCCUPATIONAL_PENSION\",\n"
                    + "\t\t\t\"hasDetail\": true\n"
                    + "\t\t}, {\n"
                    + "\t\t\t\"name\": \"Stefan Edqvist\",\n"
                    + "\t\t\t\"productName\": \"Löneväxling\",\n"
                    + "\t\t\t\"id\": \"86719994\",\n"
                    + "\t\t\t\"type\": \"AGREEMENT\",\n"
                    + "\t\t\t\"riskCovers\": [\"DEATH\"],\n"
                    + "\t\t\t\"status\": \"PAID_UP\",\n"
                    + "\t\t\t\"investmentValue\": 81115.35,\n"
                    + "\t\t\t\"agreedPremium\": null,\n"
                    + "\t\t\t\"premiumModelTerm\": null,\n"
                    + "\t\t\t\"owner\": \"Starcounter AB\",\n"
                    + "\t\t\t\"ownerId\": \"165565883278\",\n"
                    + "\t\t\t\"productType\": \"PENSION_PLAN\",\n"
                    + "\t\t\t\"productCategory\": \"OCCUPATIONAL_PENSION\",\n"
                    + "\t\t\t\"hasDetail\": true\n"
                    + "\t\t}],\n"
                    + "\t\t\"livSystemOpen\": true\n"
                    + "\t},\n"
                    + "\t\"errors\": null\n"
                    + "}";

    private final String PENSION_WITH_LIFEINSURANCE_AGREEMENT =
            "{\n"
                    + "\t\"id\": null,\n"
                    + "\t\"response\": {\n"
                    + "\t\t\"lifeInsuranceAgreement\": {\n"
                    + "\t\t\t\"agreedPremium\": 0.00,\n"
                    + "\t\t\t\"agreementInvestmentValue\": 81115.35,\n"
                    + "\t\t\t\"agreedPremiumExemption\": 0.00,\n"
                    + "\t\t\t\"agreedPremiumAllCovers\": 0,\n"
                    + "\t\t\t\"agreedPremiumAllSavings\": 0.00,\n"
                    + "\t\t\t\"agreementNumber\": \"86719994\",\n"
                    + "\t\t\t\"premiumModelTerm\": \"QUARTER\",\n"
                    + "\t\t\t\"startDate\": \"2018-05-01\",\n"
                    + "\t\t\t\"concept\": \"LONEVAXLING\",\n"
                    + "\t\t\t\"pensionAge\": {\n"
                    + "\t\t\t\t\"year\": 65,\n"
                    + "\t\t\t\t\"month\": 0\n"
                    + "\t\t\t},\n"
                    + "\t\t\t\"product\": {\n"
                    + "\t\t\t\t\"name\": \"Löneväxling\",\n"
                    + "\t\t\t\t\"code\": \"FT\"\n"
                    + "\t\t\t},\n"
                    + "\t\t\t\"status\": \"INFORCE\",\n"
                    + "\t\t\t\"paymentDate\": \"2037-03-07\",\n"
                    + "\t\t\t\"insured\": {\n"
                    + "\t\t\t\t\"id\": \"197203072710\",\n"
                    + "\t\t\t\t\"name\": \"Stefan Edqvist\"\n"
                    + "\t\t\t},\n"
                    + "\t\t\t\"owner\": {\n"
                    + "\t\t\t\t\"id\": \"165565883278\",\n"
                    + "\t\t\t\t\"name\": \"Starcounter AB\"\n"
                    + "\t\t\t},\n"
                    + "\t\t\t\"reportedMonthlySalary\": 76250.00,\n"
                    + "\t\t\t\"lifeInsurances\": [{\n"
                    + "\t\t\t\t\"startDate\": \"2018-05-01\",\n"
                    + "\t\t\t\t\"lifeInsuranceType\": \"SAVING\",\n"
                    + "\t\t\t\t\"concept\": \"LONEVAXLING\",\n"
                    + "\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\"referenceNumber\": \"01633674\",\n"
                    + "\t\t\t\t\"product\": {\n"
                    + "\t\t\t\t\t\"name\": \"Ålderspension Fond\",\n"
                    + "\t\t\t\t\t\"code\": \"TP3\"\n"
                    + "\t\t\t\t},\n"
                    + "\t\t\t\t\"status\": \"INFORCE\",\n"
                    + "\t\t\t\t\"beneficiaryCode\": \"61\",\n"
                    + "\t\t\t\t\"totalPremiumPaid\": 74033.00,\n"
                    + "\t\t\t\t\"investmentValue\": 81115.35,\n"
                    + "\t\t\t\t\"termsDate\": \"2018-05-01\",\n"
                    + "\t\t\t\t\"taxClass\": \"T\",\n"
                    + "\t\t\t\t\"termsAndConditions\": [{\n"
                    + "\t\t\t\t\t\"id\": \"19\",\n"
                    + "\t\t\t\t\t\"termsDate\": \"2018-05-01\",\n"
                    + "\t\t\t\t\t\"productCode\": \"TP3\",\n"
                    + "\t\t\t\t\t\"statisticalCode\": \"\",\n"
                    + "\t\t\t\t\t\"validFrom\": \"2018-05-01\",\n"
                    + "\t\t\t\t\t\"validTo\": \"2019-01-31\",\n"
                    + "\t\t\t\t\t\"type\": \"REGULAR\",\n"
                    + "\t\t\t\t\t\"url\": \"http://www.lansforsakringar.se/globalassets/aa-global/dokument/villkor/friplanvillkor20180501.pdf\"\n"
                    + "\t\t\t\t}],\n"
                    + "\t\t\t\t\"agreementNumber\": \"86719994\",\n"
                    + "\t\t\t\t\"saving\": {\n"
                    + "\t\t\t\t\t\"paymentAge\": {\n"
                    + "\t\t\t\t\t\t\"year\": 65,\n"
                    + "\t\t\t\t\t\t\"month\": 0\n"
                    + "\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\"paymentDate\": \"2037-03-07\",\n"
                    + "\t\t\t\t\t\"paymentType\": \"WHILE_INSURED_ALIVE\",\n"
                    + "\t\t\t\t\t\"insuranceAmount\": 81115.35,\n"
                    + "\t\t\t\t\t\"insuranceAmountType\": \"REPAYMENT_PROTECTION\",\n"
                    + "\t\t\t\t\t\"investmentValue\": 81115.35\n"
                    + "\t\t\t\t},\n"
                    + "\t\t\t\t\"deathRiskCover\": {\n"
                    + "\t\t\t\t\t\"paymentPeriod\": {\n"
                    + "\t\t\t\t\t\t\"year\": 20,\n"
                    + "\t\t\t\t\t\t\"month\": 0\n"
                    + "\t\t\t\t\t},\n"
                    + "\t\t\t\t\t\"paymentType\": \"WHILE_INSURED_ALIVE\",\n"
                    + "\t\t\t\t\t\"insuranceAmount\": 81115.35,\n"
                    + "\t\t\t\t\t\"insuranceAmountType\": \"REPAYMENT_PROTECTION\",\n"
                    + "\t\t\t\t\t\"isStaticText\": true,\n"
                    + "\t\t\t\t\t\"hasRepaymentCover\": true\n"
                    + "\t\t\t\t},\n"
                    + "\t\t\t\t\"premium\": {\n"
                    + "\t\t\t\t\t\"agreedPremium\": 0.00,\n"
                    + "\t\t\t\t\t\"premiumPaymentMethod\": \"BANKGIRO\",\n"
                    + "\t\t\t\t\t\"totalPremium\": 74032.00,\n"
                    + "\t\t\t\t\t\"paidUntilDate\": \"2019-06-30\",\n"
                    + "\t\t\t\t\t\"paidYearToDate\": 0.00\n"
                    + "\t\t\t\t},\n"
                    + "\t\t\t\t\"insured\": {\n"
                    + "\t\t\t\t\t\"id\": \"197203072710\",\n"
                    + "\t\t\t\t\t\"name\": \"Stefan Edqvist\"\n"
                    + "\t\t\t\t},\n"
                    + "\t\t\t\t\"owner\": {\n"
                    + "\t\t\t\t\t\"id\": \"165565883278\",\n"
                    + "\t\t\t\t\t\"name\": \"Starcounter AB\"\n"
                    + "\t\t\t\t},\n"
                    + "\t\t\t\t\"fundSelections\": [{\n"
                    + "\t\t\t\t\t\"share\": 50.00,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\"name\": \"Catella Hedgefond\",\n"
                    + "\t\t\t\t\t\t\"fundId\": \"C53\",\n"
                    + "\t\t\t\t\t\t\"isinCode\": \"SE0001131335\",\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=FHUSA04BUJ\",\n"
                    + "\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\"category\": \"Specialfonder\"\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\"share\": 10.00,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\"name\": \"LF Europa Indexnära\",\n"
                    + "\t\t\t\t\t\t\"fundId\": \"W26\",\n"
                    + "\t\t\t\t\t\t\"isinCode\": \"SE0002793935\",\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F000003SS5\",\n"
                    + "\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\"subCategory\": \"Europa\"\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\"share\": 10.00,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\"name\": \"LF Sverige Indexnära\",\n"
                    + "\t\t\t\t\t\t\"fundId\": \"W27\",\n"
                    + "\t\t\t\t\t\t\"isinCode\": \"SE0002656611\",\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F000002ISI\",\n"
                    + "\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\"subCategory\": \"Sverige\"\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\"share\": 10.00,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\"name\": \"LF USA Indexnära\",\n"
                    + "\t\t\t\t\t\t\"fundId\": \"W28\",\n"
                    + "\t\t\t\t\t\t\"isinCode\": \"SE0002793943\",\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F000002YC3\",\n"
                    + "\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\"subCategory\": \"Nordamerika\"\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\"share\": 10.00,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\"name\": \"LF Global Indexnära\",\n"
                    + "\t\t\t\t\t\t\"fundId\": \"W30\",\n"
                    + "\t\t\t\t\t\t\"isinCode\": \"SE0005188836\",\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F00000PYZ6\",\n"
                    + "\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\"subCategory\": \"Global\"\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\"share\": 5.00,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\"name\": \"LF Tillväxtmarknad Indexnära\",\n"
                    + "\t\t\t\t\t\t\"fundId\": \"W34\",\n"
                    + "\t\t\t\t\t\t\"isinCode\": \"SE0005796331\",\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F00000TIJU\",\n"
                    + "\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\"subCategory\": \"Tillväxtmarknad\"\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\"share\": 5.00,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\"name\": \"LF Japan Indexnära\",\n"
                    + "\t\t\t\t\t\t\"fundId\": \"W41\",\n"
                    + "\t\t\t\t\t\t\"isinCode\": \"SE0000837296\",\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F0GBR04LEN\",\n"
                    + "\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\"subCategory\": \"Japan\"\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}\n"
                    + "\t\t\t\t}],\n"
                    + "\t\t\t\t\"lifeInsuranceStatus\": {\n"
                    + "\t\t\t\t\t\"isFundSwitchAllowed\": true,\n"
                    + "\t\t\t\t\t\"isFuturePremiumPlanAllowed\": true,\n"
                    + "\t\t\t\t\t\"isOngoingPremium\": false,\n"
                    + "\t\t\t\t\t\"isOngoingFundTrade\": false,\n"
                    + "\t\t\t\t\t\"hasPaymentInformation\": false,\n"
                    + "\t\t\t\t\t\"assetReallocationAllowed\": \"AVAILABLE\",\n"
                    + "\t\t\t\t\t\"isTermsAndConditionsApplicable\": false,\n"
                    + "\t\t\t\t\t\"isFundSwitchMayPostponePayout\": false,\n"
                    + "\t\t\t\t\t\"hasTransactions\": true\n"
                    + "\t\t\t\t},\n"
                    + "\t\t\t\t\"assetSummarys\": {\n"
                    + "\t\t\t\t\t\"marketValue\": 81115.35,\n"
                    + "\t\t\t\t\t\"performanceMarketValue\": 7083.35,\n"
                    + "\t\t\t\t\t\"calculatedAtDate\": \"2020-02-25\",\n"
                    + "\t\t\t\t\t\"numberOfFunds\": 7,\n"
                    + "\t\t\t\t\t\"insuranceNumber\": \"86719994-1\",\n"
                    + "\t\t\t\t\t\"financialAssets\": [{\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"numberOfShares\": 211.49045,\n"
                    + "\t\t\t\t\t\t\"isTradingAllowed\": true,\n"
                    + "\t\t\t\t\t\t\"value\": 37000.25,\n"
                    + "\t\t\t\t\t\t\"valuePercent\": 46,\n"
                    + "\t\t\t\t\t\t\"rate\": 174.95000,\n"
                    + "\t\t\t\t\t\t\"rateDate\": \"2020-02-21\",\n"
                    + "\t\t\t\t\t\t\"performancePercent\": 0.31,\n"
                    + "\t\t\t\t\t\t\"performanceSince\": \"2018-05-04\",\n"
                    + "\t\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\t\"name\": \"Catella Hedgefond\",\n"
                    + "\t\t\t\t\t\t\t\"fundId\": \"C53\",\n"
                    + "\t\t\t\t\t\t\t\"isinCode\": \"SE0001131335\",\n"
                    + "\t\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=FHUSA04BUJ\",\n"
                    + "\t\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\t\"category\": \"Specialfonder\"\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"numberOfShares\": 20.08782,\n"
                    + "\t\t\t\t\t\t\"isTradingAllowed\": true,\n"
                    + "\t\t\t\t\t\t\"value\": 9491.94,\n"
                    + "\t\t\t\t\t\t\"valuePercent\": 12,\n"
                    + "\t\t\t\t\t\t\"rate\": 472.52220,\n"
                    + "\t\t\t\t\t\t\"rateDate\": \"2020-02-24\",\n"
                    + "\t\t\t\t\t\t\"performancePercent\": 28.84,\n"
                    + "\t\t\t\t\t\t\"performanceSince\": \"2018-05-04\",\n"
                    + "\t\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\t\"name\": \"LF USA Indexnära\",\n"
                    + "\t\t\t\t\t\t\t\"fundId\": \"W28\",\n"
                    + "\t\t\t\t\t\t\t\"isinCode\": \"SE0002793943\",\n"
                    + "\t\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F000002YC3\",\n"
                    + "\t\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\t\"subCategory\": \"Nordamerika\"\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"numberOfShares\": 23.65972,\n"
                    + "\t\t\t\t\t\t\"isTradingAllowed\": true,\n"
                    + "\t\t\t\t\t\t\"value\": 8816.92,\n"
                    + "\t\t\t\t\t\t\"valuePercent\": 11,\n"
                    + "\t\t\t\t\t\t\"rate\": 372.65540,\n"
                    + "\t\t\t\t\t\t\"rateDate\": \"2020-02-24\",\n"
                    + "\t\t\t\t\t\t\"performancePercent\": 19.60,\n"
                    + "\t\t\t\t\t\t\"performanceSince\": \"2018-05-04\",\n"
                    + "\t\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\t\"name\": \"LF Sverige Indexnära\",\n"
                    + "\t\t\t\t\t\t\t\"fundId\": \"W27\",\n"
                    + "\t\t\t\t\t\t\t\"isinCode\": \"SE0002656611\",\n"
                    + "\t\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F000002ISI\",\n"
                    + "\t\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\t\"subCategory\": \"Sverige\"\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"numberOfShares\": 34.51265,\n"
                    + "\t\t\t\t\t\t\"isTradingAllowed\": true,\n"
                    + "\t\t\t\t\t\t\"value\": 9101.59,\n"
                    + "\t\t\t\t\t\t\"valuePercent\": 11,\n"
                    + "\t\t\t\t\t\t\"rate\": 263.71740,\n"
                    + "\t\t\t\t\t\t\"rateDate\": \"2020-02-24\",\n"
                    + "\t\t\t\t\t\t\"performancePercent\": 23.51,\n"
                    + "\t\t\t\t\t\t\"performanceSince\": \"2018-05-04\",\n"
                    + "\t\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\t\"name\": \"LF Global Indexnära\",\n"
                    + "\t\t\t\t\t\t\t\"fundId\": \"W30\",\n"
                    + "\t\t\t\t\t\t\t\"isinCode\": \"SE0005188836\",\n"
                    + "\t\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F00000PYZ6\",\n"
                    + "\t\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\t\"subCategory\": \"Global\"\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"numberOfShares\": 36.53944,\n"
                    + "\t\t\t\t\t\t\"isTradingAllowed\": true,\n"
                    + "\t\t\t\t\t\t\"value\": 8435.61,\n"
                    + "\t\t\t\t\t\t\"valuePercent\": 10,\n"
                    + "\t\t\t\t\t\t\"rate\": 230.86320,\n"
                    + "\t\t\t\t\t\t\"rateDate\": \"2020-02-24\",\n"
                    + "\t\t\t\t\t\t\"performancePercent\": 14.44,\n"
                    + "\t\t\t\t\t\t\"performanceSince\": \"2018-05-04\",\n"
                    + "\t\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\t\"name\": \"LF Europa Indexnära\",\n"
                    + "\t\t\t\t\t\t\t\"fundId\": \"W26\",\n"
                    + "\t\t\t\t\t\t\t\"isinCode\": \"SE0002793935\",\n"
                    + "\t\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F000003SS5\",\n"
                    + "\t\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\t\"subCategory\": \"Europa\"\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"numberOfShares\": 25.49117,\n"
                    + "\t\t\t\t\t\t\"isTradingAllowed\": true,\n"
                    + "\t\t\t\t\t\t\"value\": 4108.71,\n"
                    + "\t\t\t\t\t\t\"valuePercent\": 5,\n"
                    + "\t\t\t\t\t\t\"rate\": 161.18160,\n"
                    + "\t\t\t\t\t\t\"rateDate\": \"2020-02-24\",\n"
                    + "\t\t\t\t\t\t\"performancePercent\": 11.46,\n"
                    + "\t\t\t\t\t\t\"performanceSince\": \"2018-05-04\",\n"
                    + "\t\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\t\"name\": \"LF Tillväxtmarknad Indexnära\",\n"
                    + "\t\t\t\t\t\t\t\"fundId\": \"W34\",\n"
                    + "\t\t\t\t\t\t\t\"isinCode\": \"SE0005796331\",\n"
                    + "\t\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F00000TIJU\",\n"
                    + "\t\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\t\"subCategory\": \"Tillväxtmarknad\"\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}, {\n"
                    + "\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\"numberOfShares\": 31.29511,\n"
                    + "\t\t\t\t\t\t\"isTradingAllowed\": true,\n"
                    + "\t\t\t\t\t\t\"value\": 4160.33,\n"
                    + "\t\t\t\t\t\t\"valuePercent\": 5,\n"
                    + "\t\t\t\t\t\t\"rate\": 132.93880,\n"
                    + "\t\t\t\t\t\t\"rateDate\": \"2020-02-21\",\n"
                    + "\t\t\t\t\t\t\"performancePercent\": 12.82,\n"
                    + "\t\t\t\t\t\t\"performanceSince\": \"2018-05-07\",\n"
                    + "\t\t\t\t\t\t\"fund\": {\n"
                    + "\t\t\t\t\t\t\t\"name\": \"LF Japan Indexnära\",\n"
                    + "\t\t\t\t\t\t\t\"fundId\": \"W41\",\n"
                    + "\t\t\t\t\t\t\t\"isinCode\": \"SE0000837296\",\n"
                    + "\t\t\t\t\t\t\t\"managementForm\": \"FUND\",\n"
                    + "\t\t\t\t\t\t\t\"fundInfoURL\": \"https://www.lansforsakringar.se/privat/bank/spara/fondkurser/fond/?id=F0GBR04LEN\",\n"
                    + "\t\t\t\t\t\t\t\"category\": {\n"
                    + "\t\t\t\t\t\t\t\t\"category\": \"Aktiefonder\",\n"
                    + "\t\t\t\t\t\t\t\t\"subCategory\": \"Japan\"\n"
                    + "\t\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t\t}\n"
                    + "\t\t\t\t\t}],\n"
                    + "\t\t\t\t\t\"portfolios\": []\n"
                    + "\t\t\t\t}\n"
                    + "\t\t\t}]\n"
                    + "\t\t}\n"
                    + "\t},\n"
                    + "\t\"errors\": null\n"
                    + "}";

    @Test
    public void testTransactionParsing() {
        FetchTransactionResponse ftr =
                SerializationUtils.deserializeFromString(
                        TRANSACTIONS, FetchTransactionResponse.class);
        Assert.assertTrue(ftr.getResponse().hasMore());
        Assert.assertNotNull(ftr.getResponse().getTransactions());
        Assert.assertEquals(
                ftr.getResponse().getTransactions().get(0).getTransactionDate(), "2020-02-10");
    }

    @Test
    public void testAccountParsing() {
        FetchAccountsResponse lar =
                SerializationUtils.deserializeFromString(ACCOUNTS, FetchAccountsResponse.class);
        Assert.assertNotNull(lar.getMainAndCoAccounts());
        Assert.assertEquals(lar.getMainAndCoAccounts().get(0).getAccountNumber(), "90239056657");
    }

    @Test
    public void testUpcomingTransactionParsing() {
        FetchUpcomingResponse fur =
                SerializationUtils.deserializeFromString(
                        UPCOMING_TRANSACTIONS, FetchUpcomingResponse.class);
        Assert.assertNotNull(fur.getUpcomingTransactions());
        Assert.assertEquals(fur.getUpcomingTransactions().get(0).getDate(), "2020-02-28");
    }

    @Test
    public void testListCardsParsing() {
        FetchCreditCardResponse fccr =
                SerializationUtils.deserializeFromString(CARDS_LIST, FetchCreditCardResponse.class);
        Assert.assertNotNull(fccr.getCards());
    }

    @Test
    public void testPensionOverviewParsing() {
        FetchPensionResponse fpr =
                SerializationUtils.deserializeFromString(
                        PENSION_OVERVIEW, FetchPensionResponse.class);
        Assert.assertNotNull(fpr.getLivPensionsResponseModel());
        Assert.assertFalse(fpr.getLivPensionsResponseModel().getOccupationalPensions().isEmpty());
    }

    @Test
    public void testPensionEngagementsParsing() {
        FetchPensionWithLifeInsuranceResponse fpwli =
                SerializationUtils.deserializeFromString(
                        PENSION_ENGAGEMENTS, FetchPensionWithLifeInsuranceResponse.class);
        Assert.assertNotNull(fpwli.getResponse());
        Assert.assertNotNull(fpwli.getResponse().getEngagements());
        Assert.assertFalse(fpwli.getResponse().getEngagements().isEmpty());
    }

    @Test
    public void testPensionWithLifInsuranceAgreementParsing() {
        FetchPensionWithLifeInsuranceAgreementResponse fpwlia =
                SerializationUtils.deserializeFromString(
                        PENSION_WITH_LIFEINSURANCE_AGREEMENT,
                        FetchPensionWithLifeInsuranceAgreementResponse.class);
        Assert.assertNotNull(fpwlia.getResponse());
        Assert.assertNotNull(fpwlia.getResponse().getLifeInsuranceAgreement());
        Assert.assertFalse(
                fpwlia.getResponse().getLifeInsuranceAgreement().getLifeInsurances().isEmpty());
    }
}
