package se.tink.backend.aggregation.agents.nxgen.be.banks.argenta.integration;

public class ArgentaTestData {

    static final String ERROR = "{\"code\":\"error.request.invalid\",\"message\":\"The request has validation errors.\",\"reregister\":false,\"fieldErrors\":[{\"field\":\"cardNumber\",\"code\":\"error.authentication.cardnumber.invalid\",\"message\":\"Card number is required when no ib subscription is passed and should be in the following format: 6703 xxxx xxxx xxxx x with the final x being the control digit.\"}]}";
    static final String AUTHENTICATION_ERROR = "{\"code\":\"error.sbp\",\"message\":\"De logingegevens zijn niet juist.\",\"reregister\":false}";
    static final String TOO_MANY_DEVICE_ERROR = "{\"code\":\"error.sbp\",\"message\":\"U hebt het maximumaantal actieve registraties voor dit abonnement bereikt. Meld u aan op Argenta Internetbankieren en ga naar 'Instellingen' om een registratie te verwijderen.\",\"reregister\":false}";
    static final String ACCOUNTS = "{\n"
            + "  \"page\": 1,\n"
            + "  \"nextPage\": null,\n"
            + "  \"accounts\": [\n"
            + "    {\n"
            + "      \"id\": \"1#01\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"alias\": \"Jean Pomme\",\n"
            + "      \"type\": \"CHECKING\",\n"
            + "      \"balance\": 1891.98,\n"
            + "      \"currency\": \"EUR\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#02\",\n"
            + "      \"iban\": \"BE42979248412254\",\n"
            + "      \"alias\": \"Jean Pomme\",\n"
            + "      \"type\": \"CHECKING\",\n"
            + "      \"balance\": 2003.00,\n"
            + "      \"currency\": \"EUR\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#03\",\n"
            + "      \"iban\": \"BE37973007982528\",\n"
            + "      \"alias\": \"Jean Pomme\",\n"
            + "      \"type\": \"SAVINGS\",\n"
            + "      \"balance\": 4117.02,\n"
            + "      \"currency\": \"EUR\"\n"
            + "    }\n"
            + "  ]\n"
            + "}";
    static final String TRANSACTIONS = "{\n"
            + "  \"page\": 1,\n"
            + "  \"nextPage\": 2,\n"
            + "  \"transactions\": [\n"
            + "    {\n"
            + "      \"id\": \"1#01\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"30/09/2017\",\n"
            + "      \"amount\": -150.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"30/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\"Zakgeld\"],\n"
            + "      \"reference\": \"B7H30BI1K00A000U\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#02\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"30/09/2017\",\n"
            + "      \"amount\": -150.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"30/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\"Zakgeld\"],\n"
            + "      \"reference\": \"B7H30BI4K00A000T\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#03\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"30/09/2017\",\n"
            + "      \"amount\": -15.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"30/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI7K00A000V\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#04\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"29/09/2017\",\n"
            + "      \"amount\": -15.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"29/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"test\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI0K00A000V\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#05\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"29/09/2017\",\n"
            + "      \"amount\": -15.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"29/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Olivier Appel\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI3K00A000T\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#06\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"24/09/2017\",\n"
            + "      \"amount\": -150.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"24/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI6K00A000S\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#07\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"22/09/2017\",\n"
            + "      \"amount\": -1.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"22/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"test\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI9K00A000S\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#08\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"22/09/2017\",\n"
            + "      \"amount\": -150.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"22/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI2K00A000Q\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#09\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"22/09/2017\",\n"
            + "      \"amount\": -150.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"22/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI4K00A000Q\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#10\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"21/09/2017\",\n"
            + "      \"amount\": -150.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"21/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI7K00A000R\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#11\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"21/09/2017\",\n"
            + "      \"amount\": -1.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"21/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI0K00A000R\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#12\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"21/09/2017\",\n"
            + "      \"amount\": -10.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"21/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI3K00A000P\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#13\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"20/09/2017\",\n"
            + "      \"amount\": -150.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"20/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI6K00A000N\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#14\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"20/09/2017\",\n"
            + "      \"amount\": -10.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"20/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI9K00A000N\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#15\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"20/09/2017\",\n"
            + "      \"amount\": -10.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"20/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI2K00A000L\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#16\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"20/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"20/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI5K00A000J\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#17\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"19/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"19/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI8K00A000M\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#18\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"19/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"19/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI0K00A000L\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#19\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"19/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"19/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI3K00A000I\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#20\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"18/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"18/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"paginatie test\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI6K00A000H\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#21\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"17/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"17/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI9K00A000I\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#22\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"15/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"15/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI2K00A000F\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#23\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"15/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"15/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI4K00A000H\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#24\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"15/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"15/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Argenta Verzekeringen\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Polis 123456\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H30BI7K00A000H\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#25\",\n"
            + "      \"description\": \"Uw overschrijving\",\n"
            + "      \"transactionDate\": \"10/09/2017\",\n"
            + "      \"amount\": -5.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"10/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\"Zakgeld\"],\n"
            + "      \"reference\": \"B7H30BI0K00A000H\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#26\",\n"
            + "      \"description\": \"Overschrijving te uwen gunste\",\n"
            + "      \"transactionDate\": \"10/09/2017\",\n"
            + "      \"amount\": 17.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"10/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H29PG7KH0A000D\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"id\": \"1#27\",\n"
            + "      \"description\": \"Overschrijving te uwen gunste\",\n"
            + "      \"transactionDate\": \"10/09/2017\",\n"
            + "      \"amount\": 13.00,\n"
            + "      \"currency\": \"EUR\",\n"
            + "      \"iban\": \"BE78973136067186\",\n"
            + "      \"currencyDate\": \"10/09/2017\",\n"
            + "      \"beneficiaryIban\": \"BE33973151001146\",\n"
            + "      \"beneficiaryName\": \"Olivier Appel\",\n"
            + "      \"messageLines\": [\n"
            + "        \"Zakgeld\"\n"
            + "      ],\n"
            + "      \"reference\": \"B7H29PG5KH0A000Q\",\n"
            + "      \"transferType\": \"OTHER\"\n"
            + "    }\n"
            + "  ]\n"
            + "}";
    public static final String CARD_NUMBER_REQUIRED = "Card number is required when no ib subscription is passed and should be in the following format: 6703 xxxx xxxx xxxx x with the final x being the control digit.";
}
