java_library(
    name = "protobuf-serialization-utils",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        # Log
        "//src/libraries/log:log",

        # Protostuff
        "//third_party:io_protostuff_protostuff_api",
        "//third_party:io_protostuff_protostuff_core",
        "//third_party:io_protostuff_protostuff_runtime",
        "//third_party:io_protostuff_protostuff_collectionschema",
    ],
)
