java_library(
    name = "document_container",
    srcs = glob(["src/main/**/*.java"]),
    visibility = [
        "//src/aggregation:__subpackages__",
        "//src/aggregation/aggregationcontroller_api:__subpackages__",
        "//src/integration:__subpackages__",
    ],
    deps = [
        "//third_party:com_fasterxml_jackson_core_jackson_annotations",
        "//third_party:com_sun_jersey_jersey_core",
        "//third_party:commons_io_commons_io",
    ],
)
