apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    # This secret has to be created manually and should contain the CA certificate that has signed
    # the client certs
    nginx.ingress.kubernetes.io/auth-tls-secret: "integration-service/ingress-tls-client-ca"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: public-ingress
  namespace: integration
spec:
  rules:
  - host: integration.{{ .Values.Environment }}.{{ .Values.Cluster }}.tink.se
    http:
      paths:
      - backend:
          serviceName: integration-service
          servicePort: grpc
        path: /
  tls:
  - hosts:
    - integration.{{ .Values.Environment }}.{{ .Values.Cluster }}.tink.se
    secretName: ingress-tls
