java_library(
    name = "typemappers",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api",
        "//src/integration/lib",
        "//src/libraries/pair",
        "//third_party:org_slf4j_slf4j_api",
    ],
)
