package se.tink.backend.aggregation.agents.nxgen.nl.banks.bunq;

public class BunqAgentTestData {

    static final String TRANSACTION_01 =
            "{\n"
                    + "   \"Payment\":{\n"
                    + "      \"id\":202549532,\n"
                    + "      \"created\":\"2019-10-14 17:34:51.103560\",\n"
                    + "      \"updated\":\"2019-10-14 17:34:51.103560\",\n"
                    + "      \"monetary_account_id\":72041,\n"
                    + "      \"amount\":{\n"
                    + "         \"currency\":\"EUR\",\n"
                    + "         \"value\":\"0.01\"\n"
                    + "      },\n"
                    + "      \"description\":\"Topup account NL44BUNQ2025348894Minderhoud\",\n"
                    + "      \"type\":\"IDEAL\",\n"
                    + "      \"merchant_reference\":null,\n"
                    + "      \"alias\":{\n"
                    + "         \"iban\":\"NL44BUNQ2025348894\",\n"
                    + "         \"is_light\":null,\n"
                    + "         \"display_name\":\"Martijn Joseph Dani\\u00ebl Minderhoud\",\n"
                    + "         \"avatar\":{\n"
                    + "            \"uuid\":\"85726a47-22a9-40a3-9af9-4b131fb65c46\",\n"
                    + "            \"image\":[\n"
                    + "               {\n"
                    + "                  \"attachment_public_uuid\":\"6a7e6795-fd8e-490b-a692-594d2c3ebbfa\",\n"
                    + "                  \"height\":1024,\n"
                    + "                  \"width\":1024,\n"
                    + "                  \"content_type\":\"image\\/jpeg\"\n"
                    + "               }\n"
                    + "            ],\n"
                    + "            \"anchor_uuid\":null\n"
                    + "         },\n"
                    + "         \"label_user\":{\n"
                    + "            \"uuid\":\"88039ab3-bdc9-418d-a319-a4236d7130a3\",\n"
                    + "            \"display_name\":\"M.J.D. Minderhoud\",\n"
                    + "            \"country\":\"NL\",\n"
                    + "            \"avatar\":{\n"
                    + "               \"uuid\":\"9e7546f4-067f-45b0-867b-3f018d1da421\",\n"
                    + "               \"image\":[\n"
                    + "                  {\n"
                    + "                     \"attachment_public_uuid\":\"0b7417b9-427e-4c25-b859-e771aa46ae74\",\n"
                    + "                     \"height\":1024,\n"
                    + "                     \"width\":1024,\n"
                    + "                     \"content_type\":\"image\\/jpeg\"\n"
                    + "                  }\n"
                    + "               ],\n"
                    + "               \"anchor_uuid\":null\n"
                    + "            },\n"
                    + "            \"public_nick_name\":null\n"
                    + "         },\n"
                    + "         \"country\":null\n"
                    + "      },\n"
                    + "      \"counterparty_alias\":{\n"
                    + "         \"iban\":\"NL59ABNA0846721422\",\n"
                    + "         \"is_light\":null,\n"
                    + "         \"display_name\":\"MJD MINDERHOUD\",\n"
                    + "         \"avatar\":{\n"
                    + "            \"uuid\":\"abf4c4a5-b9be-4738-b768-e115b4c23069\",\n"
                    + "            \"image\":[\n"
                    + "               {\n"
                    + "                  \"attachment_public_uuid\":\"74ac1a57-e4dc-4108-b6c2-2c993a4f58e5\",\n"
                    + "                  \"height\":640,\n"
                    + "                  \"width\":640,\n"
                    + "                  \"content_type\":\"image\\/jpeg\"\n"
                    + "               }\n"
                    + "            ],\n"
                    + "            \"anchor_uuid\":null\n"
                    + "         },\n"
                    + "         \"label_user\":{\n"
                    + "            \"uuid\":\"88039ab3-bdc9-418d-a319-a4236d7130a3\",\n"
                    + "            \"display_name\":\"M.J.D. Minderhoud\",\n"
                    + "            \"country\":\"NL\",\n"
                    + "            \"avatar\":{\n"
                    + "               \"uuid\":\"9e7546f4-067f-45b0-867b-3f018d1da421\",\n"
                    + "               \"image\":[\n"
                    + "                  {\n"
                    + "                     \"attachment_public_uuid\":\"0b7417b9-427e-4c25-b859-e771aa46ae74\",\n"
                    + "                     \"height\":1024,\n"
                    + "                     \"width\":1024,\n"
                    + "                     \"content_type\":\"image\\/jpeg\"\n"
                    + "                  }\n"
                    + "               ],\n"
                    + "               \"anchor_uuid\":null\n"
                    + "            },\n"
                    + "            \"public_nick_name\":null\n"
                    + "         },\n"
                    + "         \"country\":null\n"
                    + "      },\n"
                    + "      \"attachment\":[\n"
                    + "\n"
                    + "      ],\n"
                    + "      \"geolocation\":null,\n"
                    + "      \"batch_id\":null,\n"
                    + "      \"scheduled_id\":null,\n"
                    + "      \"address_billing\":null,\n"
                    + "      \"address_shipping\":null,\n"
                    + "      \"sub_type\":\"PAYMENT\",\n"
                    + "      \"request_reference_split_the_bill\":[\n"
                    + "\n"
                    + "      ],\n"
                    + "      \"balance_after_mutation\":{\n"
                    + "         \"currency\":null,\n"
                    + "         \"value\":null\n"
                    + "      },\n"
                    + "      \"payment_auto_allocate_instance\":null\n"
                    + "   }\n"
                    + "}";
}
