#!/bin/bash
# Workaround for https://github.com/bazelbuild/bazel/issues/2337
# As IntelliJ uses "bazel run" which is only allowed to run once per workspace,
# this helper is needed to override the behavior.
# The normal Bazel starter script will look for a tools/bazel in the workspace
# and use that (i.e. this script) instead if found.

has_script_path=false

i=0
for arg in "$@"
do
    i=$((i+1))
    case "$arg" in
        --) : ${split_pos:=$i} ;;
        run) is_run=true ;;
        --script_path) has_script_path=true ;;
    esac
done

if [ -n "${split_pos:-}" ]
then
    extra_args=( "${@:$split_pos:$#}" )
    set -- "${@:1:$split_pos-1}"
fi

if [ "$is_run" = true -a "$has_script_path" = false ]
then
    runcmd="$(mktemp /tmp/bazel-run.XXXXXX)"
    set -- "$@" --script_path="$runcmd"
fi

test -n "${split_pos:-}" && set -- "$@" "${extra_args[@]}"

"$BAZEL_REAL" "$@"

if [ "$is_run" = true -a "$has_script_path" = false ]
then
    exec "$runcmd"
fi
