filegroup(
    name = "phantomjs_linux",
    srcs = ["phantomjs-tink-linux-x86_64-1.9.8"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "phantomjs_mac",
    srcs = ["phantomjs-tink-mac64-2.1.1"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "libkbc_wbaes_linux",
    srcs = ["libkbc_wbaes_linux.so"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "libkbc_wbaes_mac",
    srcs = ["libkbc_wbaes_mac.dylib"],
    visibility = ["//visibility:public"],
)
