package se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.Payment;

import java.util.ArrayList;
import org.junit.Test;
import se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.BelfiusTest;
import se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.payments.entities.BelfiusPaymentResponse;
import se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.payments.entities.getsigningprotocol.SignProtocolResponse;
import se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.payments.entities.preparetransfer.PrepareRoot;
import se.tink.backend.aggregation.agents.nxgen.be.banks.belfius.payments.entities.preparetransfer.BeneficiariesContacts;
import se.tink.libraries.serialization.utils.SerializationUtils;
import static junit.framework.TestCase.assertTrue;
import static org.junit.Assert.assertFalse;

public class ParseTest  extends BelfiusTest {


    private final String response = "{\n"
            + "    \"pendingResponseSets\": false,\n"
            + "    \"responseSets\": [{\n"
            + "        \"requestCounter\": 13,\n"
            + "        \"applicationId\": \"BDM\",\n"
            + "        \"responses\": [{\n"
            + "            \"LoadScreen\": [{\n"
            + "                \"screenName\": \"gef0.gef1.gemd.Native_BeneficiaryManagement\"\n"
            + "            }, {\n"
            + "                \"screenVersion\": \"%24Revision%3A+1.14+%24+%5BP060%5D\"\n"
            + "            }, {\n"
            + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement\"\n"
            + "            }, {\n"
            + "                \"modal\": false\n"
            + "            }]\n"
            + "        }, {\n"
            + "            \"LoadScreen\": [{\n"
            + "                \"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse\"\n"
            + "            }, {\n"
            + "                \"screenVersion\": \"%24Revision%3A+1.2+%24+%5BP060%5D\"\n"
            + "            }, {\n"
            + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature\"\n"
            + "            }, {\n"
            + "                \"modal\": false\n"
            + "            }]\n"
            + "        }, {\n"
            + "            \"LoadScreen\": [{\n"
            + "                \"screenName\": \"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"\n"
            + "            }, {\n"
            + "                \"screenVersion\": \"%24Revision%3A+1.11+%24+%5BP060%5D\"\n"
            + "            }, {\n"
            + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_protocolDetermination\"\n"
            + "            }, {\n"
            + "                \"modal\": false\n"
            + "            }]\n"
            + "        }, {\n"
            + "            \"LoadScreen\": [{\n"
            + "                \"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"\n"
            + "            }, {\n"
            + "                \"screenVersion\": \"%24Revision%3A+1.7+%24+%5BP060%5D\"\n"
            + "            }, {\n"
            + "                \"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature\"\n"
            + "            }, {\n"
            + "                \"modal\": false\n"
            + "            }]\n"
            + "        }, {\n"
            + "            \"ScreenUpdate\": [{\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegistrationResultDescription\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_EntityAccounts\",\n"
            + "                \"properties\": [{\n"
            + "                    \"contentList\": {\n"
            + "                        \"staticcontent\": {},\n"
            + "                        \"dynamiccontent\": [],\n"
            + "                        \"type\": \"full\"\n"
            + "                    }\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Ext_Int_Account\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Communication\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Name\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CodeCountry\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_AccountTypes\",\n"
            + "                \"properties\": [{\n"
            + "                    \"contentList\": {\n"
            + "                        \"staticcontent\": {},\n"
            + "                        \"dynamiccontent\": [],\n"
            + "                        \"type\": \"full\"\n"
            + "                    }\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_BenefiariesContacts\",\n"
            + "                \"properties\": [{\n"
            + "                    \"contentList\": {\n"
            + "                        \"staticcontent\": {\n"
            + "                            \"repeatedPane_BeneficiariesContacts\": {\n"
            + "                                \"btn_Selected\": {\n"
            + "                                    \"color\": \"Green\",\n"
            + "                                    \"label\": \"Select\",\n"
            + "                                    \"small\": \"true\"\n"
            + "                                }\n"
            + "                            }\n"
            + "                        },\n"
            + "                        \"dynamiccontent\": [],\n"
            + "                        \"type\": \"full\"\n"
            + "                    }\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_StructuredCommunication\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_TransferOrigin\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\n"
            + "                \"properties\": [{\n"
            + "                    \"contentList\": {\n"
            + "                        \"staticcontent\": {},\n"
            + "                        \"dynamiccontent\": [],\n"
            + "                        \"type\": \"full\"\n"
            + "                    }\n"
            + "                }]\n"
            + "            }, {\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature@mlb_ActionIdentifier\",\n"
            + "                \"properties\": [{\n"
            + "                    \"text\": \"\"\n"
            + "                }]\n"
            + "            }]\n"
            + "        }]\n"
            + "    }, {\n"
            + "        \"requestCounter\": 13,\n"
            + "        \"applicationId\": \"BDM\",\n"
            + "        \"responses\": [{\n"
            + "            \"ScreenUpdate\": [{\n"
            + "                \"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_BenefiariesContacts\",\n"
            + "                \"properties\": [{\n"
            + "                    \"contentList\": {\n"
            + "                        \"staticcontent\": {\n"
            + "                            \"repeatedPane_BeneficiariesContacts\": {\n"
            + "                                \"btn_Selected\": {\n"
            + "                                    \"color\": \"Green\",\n"
            + "                                    \"label\": \"Select\",\n"
            + "                                    \"small\": \"true\"\n"
            + "                                }\n"
            + "                            }\n"
            + "                        },\n"
            + "                        \"dynamiccontent\": [{\n"
            + "                            \"key\": \"1\",\n"
            + "                            \"repeatedPane_BeneficiariesContacts\": {\n"
            + "                                \"mlb_ZipCode\": {\n"
            + "                                    \"text\": \"\"\n"
            + "                                },\n"
            + "                                \"mlb_Alias\": {\n"
            + "                                    \"text\": \"\"\n"
            + "                                },\n"
            + "                                \"mlb_Key2_SequenceNumber\": {\n"
            + "                                    \"text\": \"1\"\n"
            + "                                },\n"
            + "                                \"mlb_Street\": {\n"
            + "                                    \"text\": \"\"\n"
            + "                                },\n"
            + "                                \"mlb_HouseNumber\": {\n"
            + "                                    \"text\": \"\"\n"
            + "                                },\n"
            + "                                \"mlb_Ext_Int_Account\": {\n"
            + "                                    \"text\": \"IBE11111111111111\"\n"
            + "                                },\n"
            + "                                \"mlb_Communication\": {\n"
            + "                                    \"text\": \"\"\n"
            + "                                },\n"
            + "                                \"mlb_Name\": {\n"
            + "                                    \"text\": \"fake name\"\n"
            + "                                },\n"
            + "                                \"mlb_Amount\": {\n"
            + "                                    \"text\": \"\"\n"
            + "                                },\n"
            + "                                \"mlb_Key1_ListNumber\": {\n"
            + "                                    \"text\": \"11111111\"\n"
            + "                                },\n"
            + "                                \"mlb_StructuredCommunication\": {\n"
            + "                                    \"text\": \"N\"\n"
            + "                                },\n"
            + "                                \"mlb_City\": {\n"
            + "                                    \"text\": \"\"\n"
            + "                                },\n"
            + "                                \"mlb_CodeCountry\": {\n"
            + "                                    \"text\": \"BE\"\n"
            + "                                },\n"
            + "                                \"mlb_Contact\": {\n"
            + "                                    \"text\": \"Y\"\n"
            + "                                },\n"
            + "                                \"mlb_Account\": {\n"
            + "                                    \"text\": \"BE11 1111 1111 1111\"\n"
            + "                                }\n"
            + "                            }\n"
            + "                        }],\n"
            + "                        \"type\": \"full\"\n"
            + "                    }\n"
            + "                }]\n"
            + "            }]\n"
            + "        }]\n"
            + "    }]\n"
            + "}";

    private String signPrep = "{\n"
            + "\t\"pendingResponseSets\": false,\n"
            + "\t\"responseSets\": [{\n"
            + "\t\t\"requestCounter\": 15,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_ownbenefaccount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefname\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"Fake Name\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_amount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"2.000,00 EUR\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_country\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"BE\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_memodate\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"27/04/2018\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_PWAllowed\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_ConfirmAllowed\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_ItsMeAllowed\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_protocolDetermination@mlb_CardReaderAllowed\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"Y\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}]\n"
            + "}";


    private String paymentRequest = "{\n"
            + "\t\"pendingResponseSets\": false,\n"
            + "\t\"responseSets\": [{\n"
            + "\t\t\"requestCounter\": 16,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.2+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer@reuse_signature\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc_sign\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_sign\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_ownbenefaccount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefname\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"Cedric Verbeken\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_amount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"2.000,00 EUR\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok_Transfer_Signed\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_country\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"BE\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_memodate\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"27/04/2018\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@lb_Challenge\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"4420 5434 5740\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@lb_Protocol\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"PROTIMSC\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@rep_scenarios\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [{\n"
            + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"03\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"Een overschrij-<br />ving tekenen?\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\"key\": \"1\"\n"
            + "\t\t\t\t\t\t}, {\n"
            + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"2000\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"00\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"Bedrag:\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"2000\"\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\"key\": \"2\"\n"
            + "\t\t\t\t\t\t}],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_signature@mlb_BuyIcon\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}]\n"
            + "}";

    private String beneficiaryAddString = "{\n"
            + "\t\"pendingResponseSets\": false,\n"
            + "\t\"responseSets\": [{\n"
            + "\t\t\"requestCounter\": 15,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CodeCountry\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Name\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Communication\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_TransferOrigin\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_AccountTypes\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_StructuredCommunication\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_EntityAccounts\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Ext_Int_Account\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegistrationResultDescription\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}, {\n"
            + "\t\t\"requestCounter\": 15,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [{\n"
            + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"03\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"Een begunstigde aanmaken?\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\"key\": \"1\"\n"
            + "\t\t\t\t\t\t}, {\n"
            + "\t\t\t\t\t\t\t\"RP_Scenario\": {\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data_formatted\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"602710\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_type\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"00\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_label\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"Controlegetal:\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"lb_scen_data\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"602710\"\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\"key\": \"2\"\n"
            + "\t\t\t\t\t\t}],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@mlb_BuyIcon\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@lb_Protocol\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"PROTIMSC\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@lb_Challenge\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"3154 7130 2300\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}]\n"
            + "}";


    private final String beneficiaryResponse = "{\n"
            + "\t\"pendingResponseSets\": false,\n"
            + "\t\"responseSets\": [{\n"
            + "\t\t\"requestCounter\": 14,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_BeneficiaryManagement\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.14+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.2+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.11+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_protocolDetermination\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.7+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_EntityAccounts\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key2_SequenceNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Ext_Int_Account\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Key1_ListNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_ZipCode\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_City\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_AccountTypes\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Bic\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegResult\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Name\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Communication\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Street\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Amount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CommChange\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_TransferOrigin\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@mlb_RegistrationResultDescription\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_Alias\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_StructuredCommunication\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_CodeCountry\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@minp_HouseNumber\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_signature@rep_scenarios\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@reuse_ItsMeSignature@mlb_ActionIdentifier\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}, {\n"
            + "\t\t\"requestCounter\": 14,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_BeneficiaryManagement@rep_BenefiariesContacts\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"contentList\": {\n"
            + "\t\t\t\t\t\t\"staticcontent\": {\n"
            + "\t\t\t\t\t\t\t\"repeatedPane_BeneficiariesContacts\": {\n"
            + "\t\t\t\t\t\t\t\t\"btn_Selected\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"color\": \"Green\",\n"
            + "\t\t\t\t\t\t\t\t\t\"label\": \"Select\",\n"
            + "\t\t\t\t\t\t\t\t\t\"small\": \"true\"\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\"dynamiccontent\": [{\n"
            + "\t\t\t\t\t\t\t\"key\": \"1\",\n"
            + "\t\t\t\t\t\t\t\"repeatedPane_BeneficiariesContacts\": {\n"
            + "\t\t\t\t\t\t\t\t\"mlb_ZipCode\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Alias\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Key2_SequenceNumber\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"1\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Street\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_HouseNumber\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Ext_Int_Account\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"IBE11111111111111\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Communication\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Name\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"Fake Name\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Amount\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Key1_ListNumber\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"3274151\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_StructuredCommunication\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_City\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_CodeCountry\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"BE\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Contact\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Account\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"BE11 1111 1111 1111\"\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t}, {\n"
            + "\t\t\t\t\t\t\t\"key\": \"2\",\n"
            + "\t\t\t\t\t\t\t\"repeatedPane_BeneficiariesContacts\": {\n"
            + "\t\t\t\t\t\t\t\t\"mlb_ZipCode\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Alias\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Key2_SequenceNumber\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"2\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Street\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_HouseNumber\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Ext_Int_Account\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"IBE11111111111111\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Communication\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Name\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"Optional.empty\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Amount\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Key1_ListNumber\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"3274151\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_StructuredCommunication\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_City\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_CodeCountry\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"BE\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Contact\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t\t\t\t\t},\n"
            + "\t\t\t\t\t\t\t\t\"mlb_Account\": {\n"
            + "\t\t\t\t\t\t\t\t\t\"text\": \"BE11 1111 1111 1111\"\n"
            + "\t\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t\t}\n"
            + "\t\t\t\t\t\t}],\n"
            + "\t\t\t\t\t\t\"type\": \"full\"\n"
            + "\t\t\t\t\t}\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}]\n"
            + "}";

    private final String signRequire = "{\n"
            + "\t\"pendingResponseSets\": false,\n"
            + "\t\"responseSets\": [{\n"
            + "\t\t\"requestCounter\": 13,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Transfers\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.25+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_ProtocolDetermination_Reuse\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.11+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer@reuse_protocolDetermination\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"LoadScreen\": [{\n"
            + "\t\t\t\t\"screenName\": \"gef0.gef1.gemd.Native_Signature_Reuse_ItsMe\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"screenVersion\": \"%24Revision%3A+1.7+%24+%5BP060%5D\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"parentWidgetId\": \"Container@reuse_transfer@reuse_ItsMeSignature\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"modal\": false\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_structuredCommFlag\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_amount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_country\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_memodate\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"26/04/2018\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_ownbenefaccount\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefname\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@reuse_ItsMeSignature@mlb_ActionIdentifier\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}, {\n"
            + "\t\t\"requestCounter\": 13,\n"
            + "\t\t\"applicationId\": \"BDM\",\n"
            + "\t\t\"responses\": [{\n"
            + "\t\t\t\"ScreenUpdate\": [{\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefzip\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefstreet\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_signature\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"dummy\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"1208000000\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exec_ok\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"N\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefhouse\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_commchange\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"TEST FROM TEST1524735839283\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@lb_exc_desc\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"De weeklimiet voor \\\"Mijn begunstigden\\\" werd bereikt. Daarom moet u even ondertekenen.\\n(MOBILEBANKINGTRANSFERCREATION   /1000/AMW033)\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"widgetId\": \"Container@reuse_transfer@inp_benefcity\",\n"
            + "\t\t\t\t\"properties\": [{\n"
            + "\t\t\t\t\t\"text\": \"\"\n"
            + "\t\t\t\t}]\n"
            + "\t\t\t}]\n"
            + "\t\t}, {\n"
            + "\t\t\t\"MessageResponse\": [{\n"
            + "\t\t\t\t\"messageContent\": \"De weeklimiet voor \\\"Mijn begunstigden\\\" werd bereikt. Daarom moet u even ondertekenen.\\n(MOBILEBANKINGTRANSFERCREATION   /1000/AMW033)\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"messageDetail\": \"ERROR IN  OperationMobileTransferCreation (1208/000000)\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"messageType\": \"error\"\n"
            + "\t\t\t}, {\n"
            + "\t\t\t\t\"messageTarget\": \"internal\"\n"
            + "\t\t\t}]\n"
            + "\t\t}]\n"
            + "\t}]\n"
            + "}";


    public boolean isBeneficiary(String accountNum, ArrayList<BeneficiariesContacts> beneficiaries){
        boolean ret = false;
        for(BeneficiariesContacts beneficiary : beneficiaries){
            ret = ret || beneficiary.isAccount(accountNum);
        }
        return ret;
    }

    @Test
    public void parseResponseTest() throws Exception{
        PrepareRoot pr = SerializationUtils.deserializeFromString(beneficiaryResponse, PrepareRoot.class);
        ArrayList<BeneficiariesContacts> beneficiaries = pr.getBeneficiaries();

        assertTrue(isBeneficiary("BE11111111111111", beneficiaries));
        BelfiusPaymentResponse bpr = SerializationUtils.deserializeFromString(signRequire, BelfiusPaymentResponse.class);
        assertTrue(bpr.requireSign());
        SignProtocolResponse spr = SerializationUtils.deserializeFromString(signPrep, SignProtocolResponse.class);
        assertTrue(spr.cardReaderAllowed());
        spr = SerializationUtils.deserializeFromString(paymentRequest, SignProtocolResponse.class);
        assertTrue(spr.getChallenge().equals("4420 5434 5740")); //beneficiaryAddString
        assertTrue(spr.getSignType().equals("2000"));
        spr = SerializationUtils.deserializeFromString(beneficiaryAddString, SignProtocolResponse.class);
        assertTrue(spr.getChallenge().equals("3154 7130 2300"));


    }

}
