load("//tools/bzl:junit.bzl", "junit_test")

java_library(
    name = "api-annotations",
    srcs = glob(["src/main/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
)
