load("//tools/bzl:junit.bzl", "junit_test")

java_library(
    name = "metrics",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
    ],
)
