kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-pt-ng
  namespace: agents
spec:
  rules:

    - alert: LoginSuccessRateBelow90WithAttemptLimitPT_NG
      expr: |
        # Successful/Cancelled attempts above 90%
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in", outcome=~"completed|cancelled|unavailable", market="PT", provider_type!="test"}[60m])) by (action,className,provider)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) < 0.90)
        # At least this many attempts.
        and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P4
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Login success rate is below 90% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last hour.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert , @minions-goalie

    - alert: LoginSuccessRateBelow80WithAttemptLimitPT_NG
      expr: |
        # Successful/Cancelled attempts above 80%
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in", outcome=~"completed|cancelled|unavailable", market="PT", provider_type!="test"}[60m])) by (action,className,provider)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) < 0.80)
        # At least this many attempts.
        and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P3
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Login success rate is below 80% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last hour.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert , @minions-goalie

    - alert: LoginSuccessRateBelow70WithAttemptLimitPT_NG
      expr: |
        # Successful/Cancelled attempts above 70%
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in", outcome=~"completed|cancelled|unavailable", market="PT", provider_type!="test"}[60m])) by (action,className,provider)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) < 0.70)
        # At least this many attempts.
        and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P2
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Login success rate is below 70% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last hour.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert

    - alert: LoginSuccessRateBelow60WithAttemptLimitPT_NG
      expr: |
        # Successful/Cancelled attempts above 60%
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in",  outcome=~"completed|cancelled|unavailable", market="PT", provider_type!="test"}[60m])) by (action,className,provider)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) < 0.60)
        # At least this many attempts.
        and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="PT", provider_type!="test"}[60m])) by (action,className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Login success rate is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last hour.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert

    - alert: RefreshSuccessRateBelow90WithAttemptLimitPT_NG
      expr: |
        # Successful attempts above 90%
        (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="PT", provider_type!="test"}[30m])) by (className,provider)
            / sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) < 0.90)
        # At least this many attempts.
          and sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) > 40
      for: 5m
      labels:
        severity: urgent
        priority: P4
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Refresh success rate is below 90% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert , @minions-goalie

    - alert: RefreshSuccessRateBelow80WithAttemptLimitPT_NG
      expr: |
        # Successful attempts above 80%
        (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="PT", provider_type!="test"}[30m])) by (className,provider)
            / sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) < 0.80)
        # At least this many attempts.
          and sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) > 40
      for: 5m
      labels:
        severity: urgent
        priority: P3
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Refresh success rate is below 80% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert , @minions-goalie

    - alert: RefreshSuccessRateBelow70WithAttemptLimitPT_NG
      expr: |
        # Successful attempts above 70%
        (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="PT", provider_type!="test"}[30m])) by (className,provider)
            / sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) < 0.70)
        # At least this many attempts.
          and sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) > 40
      for: 5m
      labels:
        severity: urgent
        priority: P2
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Refresh success rate is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert

    - alert: RefreshSuccessRateBelow60WithAttemptLimitPT_NG
      expr: |
        # Successful attempts above 60%
        (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="PT", provider_type!="test"}[30m])) by (className,provider)
            / sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) < 0.60)
        # At least this many attempts.
          and sum(increase(tink_agent_refresh_total{market="PT", provider_type!="test"}[30m])) by (className,provider) > 40
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Refresh success rate is below 60% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last 30 minutes.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-minions* , pt-market-alert

    ### Bank side failures
    - alert: BankServerUnavailableForLoginPT_NG
      expr: |
        # Unavailable outcome above 50%
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in",  outcome=~"unavailable", market="PT", provider_type!="test"}[30m])) by (action,className)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in"}[30m])) by (action,className) > 0.50)
        # At least this many attempts.
        and sum(increase(tink_agent_login_total{action=~"login|is-logged-in"}[30m])) by (action,className) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration
      annotations:
        description: Login unavailable rate is above 50% ( <{ $value }> ) for the last 30 minutes.
          Investigate immediately.
        summary: Login unavailable rate is above 50% ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes.
        tags: <{ $labels.className }> , pt-market-alert

    - alert: BankServerUnavailableForRefreshPT_NG
      expr: |
        # Unavailable outcome above 50%
        (sum(increase(tink_agent_refresh_total{outcome=~"unavailable", market="PT", provider_type!="test"}[30m])) by (className)
            / sum(increase(tink_agent_refresh_total[30m])) by (className) > 0.50)
        # At least this many attempts.
        and sum(increase(tink_agent_refresh_total[30m])) by (className) > 10
      for: 5m
      labels:
        severity: urgent
        priority: P1
        who: integration
      annotations:
        description: Refresh unavailable rate is above 50% ( <{ $value }> ) for the last 30 minutes.
          Investigate immediately.
        summary: Refresh unavailable rate is above 50% ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes.
        tags: <{ $labels.className }> , pt-market-alert
