java_library(
    name = "enums",
    srcs = glob(["src/main/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/libraries/account_identifier",
        "//third_party:com_google_guava_guava",
        "//third_party:commons_lang_commons_lang",
    ],
)
