java_library(
    name = "configuration",
    srcs = glob(["*.java"]),
    data = [
        "//data:cryptography_test",
        "//data:provision_clients",
        "//data:tesseract_training_set",
        "//tools:libkbc_wbaes_linux",
        "//tools:libkbc_wbaes_mac",
        "//tools:phantomjs_linux",
        "//tools:phantomjs_mac",
    ],
    visibility = ["//visibility:public"],
    runtime_deps = [],
    deps = [],
)
