kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-refresh-it
  namespace: agents
spec:
  rules:

  #-------------------------------------------------------------------------------------------------------------------
  # All errors alerts
  #-------------------------------------------------------------------------------------------------------------------
  - alert: agent_refreshes_below45_greater35_due_to_all_error_for_specific_product_in_it
    expr: 0.35 <= sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.45
    for: 30m
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 35 - 45% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below35_greater25_due_to_all_error_for_specific_product_in_it
    expr: 0.25 <= sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.35
    for: 30m
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 25 - 35% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below25_greater15_due_to_all_error_for_specific_product_in_it
    expr: 0.15 <= sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.25
    for: 30m
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 15 - 25% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below15_due_to_all_error_for_specific_product_in_it
    expr: sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.15
    for: 30m
    labels:
      severity: urgent
      priority: P1
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is below 15% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  #-------------------------------------------------------------------------------------------------------------------
  # Partially completed alerts
  #-------------------------------------------------------------------------------------------------------------------
  - alert: agent_refreshes_below60_greater50_due_to_partially_completed_error_for_specific_product_in_it
    expr: 0.5 <= sum:IT:className_type:not_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.6
    for: 30m
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 50 - 60% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below50_greater40_due_to_partially_completed_error_for_specific_product_in_it
    expr: 0.4 <= sum:IT:className_type:not_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.5
    for: 30m
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 40 - 50% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below40_greater30_due_to_partially_completed_error_for_specific_product_in_it
    expr: 0.3 <= sum:IT:className_type:not_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.4
    for: 30m
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is between 30 - 40% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}

  - alert: agent_refreshes_below30_due_to_partially_completed_error_for_specific_product_in_it
    expr: sum:IT:className_type:not_partially_completed:delta1h / (sum:IT:className_type:all_refreshes:delta1h > 20) < 0.3
    for: 30m
    labels:
      severity: urgent
      priority: P1
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Refresh unavailable rate is below 30% because of all issues ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last 30 minutes for <{ $labels.type }>
      tags: {{ .Values.tags }}
