kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-it
  namespace: agents
spec:
  rules:

    ## Login success rates - for IT because of a lot of TIMEOUTs and INCORRECT_CREDENTIALS
    ## and being aware of the issue - we will assume all auth errors as successful refreshes.
    ## To discover agents with really low SR there are long term alerts prepared.
    - alert: login_success_rate_between_70_and_80_it
      expr: |
        # Successful/Cancelled attempts above 80%
        (sum:IT:action_className:all_manual_attempts:not_failed:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.80)
        and (sum:IT:action_className:all_manual_attempts:not_failed:delta1h
                    / sum:IT:action_className:all_manual_attempts:delta1h >= 0.70)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Login success rate is between 70 - 80% ( <{ value | humanizePercentage }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes..
        tags: {{ .Values.tags }}

    - alert: login_success_rate_between_60_and_70_it
      expr: |
        (sum:IT:action_className:all_manual_attempts:not_failed:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.70)
        and (sum:IT:action_className:all_manual_attempts:not_failed:delta1h
                    / sum:IT:action_className:all_manual_attempts:delta1h >= 0.60)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Login success rate is between 60 - 70% ( <{ value | humanizePercentage }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: login_success_rate_between_50_and_60_it
      expr: |
        (sum:IT:action_className:all_manual_attempts:not_failed:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.60)
        and (sum:IT:action_className:all_manual_attempts:not_failed:delta1h
                    / sum:IT:action_className:all_manual_attempts:delta1h >= 0.50)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Login success rate is between 50 - 60 % ( <{ value | humanizePercentage }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: login_success_rate_below_50_it
      expr: |
        (sum:IT:action_className:all_manual_attempts:not_failed:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.50)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Login success rate is below 50% ( <{ value | humanizePercentage }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    ### Bank side failures
    - alert: bank_success_rate_between_70_and_80_it
      expr: |
        # Unavailable outcome above 50%
        (sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.80)
        and (sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h
                        / sum:IT:action_className:all_manual_attempts:delta1h >= 0.70)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Bank errors rate is between 20 - 30% ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: bank_success_rate_between_60_and_70_it
      expr: |
        # Unavailable outcome above 50%
        (sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.70)
        and (sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h
                    / sum:IT:action_className:all_manual_attempts:delta1h >= 0.60)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Bank errors rate is between 30 - 40% ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: bank_success_rate_between_50_and_60_it
      expr: |
        # Unavailable outcome above 50%
        (sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.60)
        and (sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h
                        / sum:IT:action_className:all_manual_attempts:delta1h >= 0.50)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Bank errors rate is between 40 - 50% ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the {{ .Values.p3WaitTimeBeforeFiringAlert }} 30 minutes.
        tags: {{ .Values.tags }}

    - alert: bank_success_rate_below_50_it
      expr: |
        # Unavailable outcome above 50%
        (sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h
            / sum:IT:action_className:all_manual_attempts:delta1h < 0.50)
        # At least this many attempts.
        and sum:IT:action_className:all_manual_attempts:delta1h > 5
      for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Bank errors rate is above 50% ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: manual_login_error_rate_over_50%_due_to_bank_side_error_it
      expr: |
        (sum by(provider, className) (increase (tink_agent_login_total{market="IT", outcome="unavailable", action="login-manual"}[1h]))
        / sum:IT:provider_className:login-manual:delta1h > 0.5 )
        and (sum:IT:provider_className:login-manual:delta1h) > 5)
      for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Manual login error rate more than 50% ( <{ value | humanizePercentage }> * 100 ) % for provider <{ $labels.provider }> of agent <{ $labels.className }>
          the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    - alert: auto_login_error_rate_over_50%_due_to_bank_side_error_it
      expr: |
        (sum by(provider, className, action) (increase (tink_agent_login_total{market="IT", outcome="unavailable", action=~"login-auto|login-cron"}[1h]))
        / sum:IT:provider_className:login-manual:delta1h > 0.5 )
        and (sum:IT:provider_className:login-manual:delta1h > 5)
      for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Auto login error rate more than 50% ( <{ value | humanizePercentage }> * 100 ) % for action <{ $labels.action }> provider <{ $labels.provider }> of agent <{ $labels.className }>
          the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
        tags: {{ .Values.tags }}

    ## Long term alerts
    ## removed due to problems with prometheus performance



    #################################
    ### AllErrors - Agent Refresh ###
    #################################
    - alert: agent_refreshes_below45_greater35_due_to_all_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.45
        and (sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) >= 0.35
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is between 35 - 45% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below35_greater25_due_to_all_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.35
        and (sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) >= 0.25
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is between 25 - 35% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below25_greater15_due_to_all_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.25
        and (sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) >= 0.15
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is between 15 - 25% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below15_due_to_all_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_failed_unavailable_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.15
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: urgent
        priority: P1
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is below 15% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    ###############################################
    ### AllErrors - Partially Completed Refresh ###
    ###############################################

    - alert: agent_refreshes_below60_greater50_due_to_partially_completed_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.6
        and (sum:IT:className_type:not_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) >= 0.5
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: ping
        priority: P4
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is between 50 - 60% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below50_greater40_due_to_partially_completed_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.5
        and (sum:IT:className_type:not_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) >= 0.4
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: urgent
        priority: P3
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is between 40 - 50% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below40_greater30_due_to_partially_completed_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.4
        and (sum:IT:className_type:not_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) >= 0.3
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: urgent
        priority: P2
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is between 30 - 40% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}

    - alert: agent_refreshes_below30_due_to_partially_completed_error_for_specific_product_in_it
      expr: |
        (sum:IT:className_type:not_partially_completed:delta1h
            / sum:IT:className_type:all_refreshes:delta1h) < 0.3
         and sum:IT:className_type:all_refreshes:delta1h > 20
      for: 30m
      labels:
        severity: urgent
        priority: P1
        who: integration-nazguls
      annotations:
        description: <{{ .Values.kibanaClassLinkAbs1h }}|Kibana> \n <{{ .Values.grafanaClassLinkAbs1h }}|Grafana>
        summary: Refresh unavailable rate is below 30% because of all issues ( <{ value | humanizePercentage }> ) for <{ $labels.className }>
          the last 30 minutes for <{ $labels.type }>
        tags: {{ .Values.tags }}
