kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-it
  namespace: agents
spec:
  rules:

    - alert: LoginSuccessRateLowWithAttemptLimitIT
      expr: |
        # Successful/Cancelled attempts above 90%
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in",  outcome=~"completed|cancelled|unavailable", market="IT", provider_type!="test"}[60m])) by (action,className,provider)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="IT", provider_type!="test"}[60m])) by (action,className,provider) < 0.90)
        # At least this many attempts.
        and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="IT", provider_type!="test"}[60m])) by (action,className,provider) > 5
      for: 5m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Login success rate is below 90% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last hour.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-teletubbies*

    - alert: RefreshSuccessRateLowWithAttemptLimitIT
      expr: |
        # Successful attempts above 90%
        (sum(increase(tink_agent_refresh_total{outcome=~"completed|unavailable", market="IT", provider_type!="test"}[60m])) by (className,provider)
            / sum(increase(tink_agent_refresh_total{market="IT", provider_type!="test"}[60m])) by (className,provider) < 0.90)
        # At least this many attempts.
        and sum(increase(tink_agent_refresh_total{market="IT", provider_type!="test"}[60m])) by (className,provider) > 10
      for: 5m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Refresh success rate is below 90% ( <{ $value }> ) for <{ $labels.className }> ( <{ $labels.provider }> )
          the last hour.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-teletubbies*

    ### Bank side failures
    - alert: BankServerUnavailableForLoginIT
      expr: |
        # Unavailable outcome above 50%
        (sum(increase(tink_agent_login_total{action=~"login|is-logged-in", outcome=~"unavailable", market="IT"}[30m])) by (action,className)
            / sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="IT"}[30m])) by (action,className) > 0.50)
        # At least this many attempts.
        and sum(increase(tink_agent_login_total{action=~"login|is-logged-in", market="IT"}[30m])) by (action,className) > 10
      for: 5m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Login unavailable rate is above 50% ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-teletubbies*

    - alert: BankServerUnavailableForRefreshIT
      expr: |
        # Unavailable outcome above 50%
        (sum(increase(tink_agent_refresh_total{outcome=~"unavailable", market="IT"}[30m])) by (className)
            / sum(increase(tink_agent_refresh_total{market="IT"}[30m])) by (className) > 0.50)
        # At least this many attempts.
        and sum(increase(tink_agent_refresh_total{market="IT"}[30m])) by (className) > 10
      for: 5m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Refresh unavailable rate is above 50% ( <{ $value }> ) for <{ $labels.className }>
          the last 30 minutes.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-teletubbies*
 
    ### Provider level fails
    - alert: HighProviderErrorRatioIT
      expr: |
        # Never triggers on providers that did less than 10 operations past 60
        # minutes. This filters out small providers which are less critical to fix
        # quickly.
        sum(increase(tink_executions_total{market="IT"}[1h])) BY (provider) > 10 and
        # Providers where over 50% of the requests have failed.
        ratio:tink_provider_errors:delta60m > 50
      for: 15m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Provider <{ $labels.provider }> has failed over 50%
          of its operations the past 60 minutes
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-teletubbies*

    ### Agent level login failures
    - alert: HighProviderFailedLoginRatioIT
      expr: |
        # Never trigger on agents with less than 40 login attempts past 60 minutes.
        # This filters out small agents which are less critical to fix quickly
        sum(increase(tink_agent_login_total{action="login", market="IT"}[1h])) BY (className,provider) > 40 and
        # Agents where more than 20% of the login attempts fail.
        sum(increase(tink_agent_login_total{action="login",outcome="failed", market="IT"}[30m])) BY (className,provider) / sum(increase(tink_agent_login_total{action="login", market="IT"}[30m])) BY (className,provider) > 0.20
      for: 30m
      labels:
        severity: urgent
        who: integration-teletubbies
      annotations:
        description: To learn more check out the metric `tink_agent_login_total`. This
          alert never triggers on agents that did less than 10 operations in the
          past 60 minutes.
          https://kibana.aggregation-production.tink.network/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1h,to:now))&_a=(columns:!(doc.exception,doc.message),filters:!(('$state':(store:appState),exists:(field:doc.exception),meta:(alias:!n,disabled:!f,index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',key:doc.exception,negate:!f,type:exists,value:exists))),index:'26fa2220-73b2-11e8-9a34-dbc1936ede52',interval:auto,query:(language:lucene,query:'doc.mdc.providerName:%22<{$labels.provider}>%22'),sort:!(!('@timestamp',desc)))
          https://grafana.global-production.tink.network/d/000000078/integration-dashboard?orgId=1&from=now-1h&to=now&var-cluster=aggregation&var-environment=production&var-market=All&var-agent=All&var-provider=<{$labels.provider}>&var-interval=15m&var-app=tink-backend-aggregation
        summary: Agent <{ $labels.className }> has failed over 20%
          of its login attempts the past 60 minutes.
        tags: <{ $labels.className }> , <{ $labels.provider }> , *#aggregation-teletubbies*
