kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-login-it
  namespace: agents
spec:
  rules:

  #-------------------------------------------------------------------------------------------------------------------
  # Manual logins failed alerts
  #-------------------------------------------------------------------------------------------------------------------
  - alert: login_success_rate_between_70_and_80_it
    expr: 0.7 <= sum:IT:action_className:all_manual_attempts:not_failed:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.8
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is between 70 - 80% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes..
      tags: {{ .Values.tags }}

  - alert: login_success_rate_between_60_and_70_it
    expr: 0.6 <= sum:IT:action_className:all_manual_attempts:not_failed:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.7
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is between 60 - 70% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: login_success_rate_between_50_and_60_it
    expr: 0.5 <= sum:IT:action_className:all_manual_attempts:not_failed:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.6
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is between 50 - 60 % ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: login_success_rate_below_50_it
    expr: sum:IT:action_className:all_manual_attempts:not_failed:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.5
    for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Login success rate is below 50% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }> 
        the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  #-------------------------------------------------------------------------------------------------------------------
  # Manual logins bank side issues alerts
  #-------------------------------------------------------------------------------------------------------------------
  - alert: bank_success_rate_between_70_and_80_it
    expr: 0.7 <= sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.8
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is between 20 - 30% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: bank_success_rate_between_60_and_70_it
    expr: 0.6 <= sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.7
    for: {{ .Values.p4WaitTimeBeforeFiringAlert }}
    labels:
      severity: ping
      priority: P4
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is between 30 - 40% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last {{ .Values.p4WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: bank_success_rate_between_50_and_60_it
    expr: 0.5 <= sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.6
    for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is between 40 - 50% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the {{ .Values.p3WaitTimeBeforeFiringAlert }} 30 minutes.
      tags: {{ .Values.tags }}

  - alert: bank_success_rate_below_50_it
    expr: sum:IT:action_className:all_manual_attempts:not_unavailable:delta1h / (sum:IT:action_className:all_manual_attempts:delta1h > 5) < 0.5
    for: {{ .Values.p3WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P3
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Bank errors rate is above 50% ( <{ $value | humanizePercentage }> ) for <{ $labels.className }>
        the last {{ .Values.p3WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  - alert: manual_login_error_rate_over_50%_due_to_bank_side_error_it
    expr: |
      0.5 < 
      sum by(className) (increase (tink_agent_login_total{ provider_type!="test", market="IT", action="login-manual", outcome="unavailable"}[1h])) 
      / 
      (sum by (className) (increase (tink_agent_login_total{ provider_type!="test", market="IT", action="login-manual"}[1h])) > 5)
    for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Manual login error rate due to bank unavailable is <{ $value | humanizePercentage }> for agent <{ $labels.className }>
        in the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}

  #-------------------------------------------------------------------------------------------------------------------
  # Auto logins bank side issues alerts
  #-------------------------------------------------------------------------------------------------------------------
  - alert: auto_login_error_rate_over_50%_due_to_bank_side_error_it
    expr: |
      0.5 < 
      sum by(action, className) (increase (tink_agent_login_total{ provider_type!="test", market="IT", action=~"login-auto|login-cron", outcome="unavailable"}[1h]))
      / 
      (sum by (action, className) (increase (tink_agent_login_total{ provider_type!="test", market="IT", action=~"login-auto|login-cron"}[1h])) > 5)
    for: {{ .Values.p2WaitTimeBeforeFiringAlert }}
    labels:
      severity: urgent
      priority: P2
      who: integration-nazguls
    annotations:
      description: <{{ .Values.kibanaClassLinkAbs1h }} |Kibana>      <{{ .Values.grafanaClassLinkAbs1h }} |Grafana>
      summary: Auto login error rate due to bank unavailable is <{ $value | humanizePercentage }> for action <{ $labels.action }> and agent <{ $labels.className }>
        in the last {{ .Values.p2WaitTimeBeforeFiringAlert }} minutes.
      tags: {{ .Values.tags }}
