package se.tink.backend.aggregation.agents.nxgen.dk.banks.nordea;

public class NordeaTestData {

    static final String ACCOUNT_1_API_ID = "NAID-DK-DKK-7418529630";
    static final String TRANSACTIONS_CONTINUATION_KEY =
            "LEG_EjcqIJ8Abe9-bsc61MMA-UMCB7stdmeb2qPfCQVuitc=:rO0ABXNyAD9jb20ubm9yZGVhLmRiZi5kay5hY2NvdW50LmludGVncmF0aW9uLmNvcHlib29rcy5Db250aW51YXRpb25LZXlgVTENuzwM0gIAAUwAD2NvbnRpbnVhdGlvbmtleXQAEkxqYXZhL2xhbmcvU3RyaW5nO3hwdAA3UDAwMDAwMDAzNkc2ODk3NjQ3MDdHwIDAgMCAwIDAgMCAwIDAgDAwMDAwMDAwMDAwNTYyOTU0RA==";
    static final String CREDIT_CARD_ID = "9638527410963852";
    static final String INVESTMENT_1_ID = "DKWRAP1234123456";

    static final String FETCH_ACCOUNTS_RESULT =
            "{\n"
                    + "  \"result\": [\n"
                    + "    {\n"
                    + "      \"account_id\": \"NAID-DK-DKK-1234567890\",\n"
                    + "      \"account_status\": \"open\",\n"
                    + "      \"available_balance\": 0.00,\n"
                    + "      \"bic\": \"NDEADKKK\",\n"
                    + "      \"booked_balance\": 0.00,\n"
                    + "      \"category\": \"transaction\",\n"
                    + "      \"country_code\": \"DK\",\n"
                    + "      \"credit_limit\": 0.00,\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"display_account_number\": \"1234567890\",\n"
                    + "      \"iban\": \"DK2020001234567890\",\n"
                    + "      \"interest_info\": {\n"
                    + "        \"interests\": [\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.00,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [\n"
                    + "              {\n"
                    + "                \"from_amount\": 0.00,\n"
                    + "                \"rate\": 0.1000,\n"
                    + "                \"to_amount\": 4999.99\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"from_amount\": 5000.00,\n"
                    + "                \"rate\": 0.1000,\n"
                    + "                \"to_amount\": 9999999999999999.99\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"rate_type\": \"credit\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.00,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [],\n"
                    + "            \"rate_type\": \"debit\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.00,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [\n"
                    + "              {\n"
                    + "                \"from_amount\": 0.00,\n"
                    + "                \"rate\": 17.2500,\n"
                    + "                \"to_amount\": -0.01\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"from_amount\": -0.02,\n"
                    + "                \"rate\": 21.2500,\n"
                    + "                \"to_amount\": -9999999999999999.99\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"rate_type\": \"overdraft\"\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      },\n"
                    + "      \"latest_transaction_date\": \"2020-01-14\",\n"
                    + "      \"nickname\": \"Forbrug\",\n"
                    + "      \"permissions\": {\n"
                    + "        \"can_deposit_to_account\": true,\n"
                    + "        \"can_pay_from_account\": true,\n"
                    + "        \"can_transfer_from_account\": true,\n"
                    + "        \"can_transfer_to_account\": true,\n"
                    + "        \"can_view\": true,\n"
                    + "        \"can_view_transactions\": true,\n"
                    + "        \"require_4eye_signing\": false\n"
                    + "      },\n"
                    + "      \"product_code\": \"UNG28\",\n"
                    + "      \"product_name\": \"Lønkonto+\",\n"
                    + "      \"product_type\": \"308\",\n"
                    + "      \"registration_number\": \"2316\",\n"
                    + "      \"roles\": [\n"
                    + "        {\n"
                    + "          \"name\": \"TEST USER\",\n"
                    + "          \"role\": \"owner\"\n"
                    + "        }\n"
                    + "      ],\n"
                    + "      \"transaction_list_search_criteria\": {\n"
                    + "        \"can_use_end_date\": true,\n"
                    + "        \"can_use_free_text\": false,\n"
                    + "        \"can_use_highest_amount\": false,\n"
                    + "        \"can_use_lowest_amount\": false,\n"
                    + "        \"can_use_start_date\": true,\n"
                    + "        \"sort_by_list\": [\n"
                    + "          \"transaction_date_desc\"\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"account_id\": \"NAID-DK-DKK-9876543210\",\n"
                    + "      \"account_status\": \"open\",\n"
                    + "      \"available_balance\": 337.00,\n"
                    + "      \"bic\": \"NDEADKKK\",\n"
                    + "      \"booked_balance\": 337.00,\n"
                    + "      \"category\": \"transaction\",\n"
                    + "      \"country_code\": \"DK\",\n"
                    + "      \"credit_limit\": 0.00,\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"display_account_number\": \"9876543210\",\n"
                    + "      \"iban\": \"DK3120009876543210\",\n"
                    + "      \"interest_info\": {\n"
                    + "        \"interests\": [\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.13,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [\n"
                    + "              {\n"
                    + "                \"from_amount\": 0.00,\n"
                    + "                \"rate\": 0.1000,\n"
                    + "                \"to_amount\": 4999.99\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"from_amount\": 5000.00,\n"
                    + "                \"rate\": 0.1000,\n"
                    + "                \"to_amount\": 9999999999999999.99\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"rate_type\": \"credit\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.00,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [],\n"
                    + "            \"rate_type\": \"debit\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.00,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [\n"
                    + "              {\n"
                    + "                \"from_amount\": 0.00,\n"
                    + "                \"rate\": 17.2500,\n"
                    + "                \"to_amount\": -0.01\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"from_amount\": -0.02,\n"
                    + "                \"rate\": 21.2500,\n"
                    + "                \"to_amount\": -9999999999999999.99\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"rate_type\": \"overdraft\"\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      },\n"
                    + "      \"latest_transaction_date\": \"2020-03-08\",\n"
                    + "      \"nickname\": \"Nordea Pay\",\n"
                    + "      \"permissions\": {\n"
                    + "        \"can_deposit_to_account\": true,\n"
                    + "        \"can_pay_from_account\": true,\n"
                    + "        \"can_transfer_from_account\": true,\n"
                    + "        \"can_transfer_to_account\": true,\n"
                    + "        \"can_view\": true,\n"
                    + "        \"can_view_transactions\": true,\n"
                    + "        \"require_4eye_signing\": false\n"
                    + "      },\n"
                    + "      \"product_code\": \"UNG28\",\n"
                    + "      \"product_name\": \"Lønkonto+\",\n"
                    + "      \"product_type\": \"308\",\n"
                    + "      \"registration_number\": \"2316\",\n"
                    + "      \"roles\": [\n"
                    + "        {\n"
                    + "          \"name\": \"TEST USER\",\n"
                    + "          \"role\": \"owner\"\n"
                    + "        }\n"
                    + "      ],\n"
                    + "      \"transaction_list_search_criteria\": {\n"
                    + "        \"can_use_end_date\": true,\n"
                    + "        \"can_use_free_text\": false,\n"
                    + "        \"can_use_highest_amount\": false,\n"
                    + "        \"can_use_lowest_amount\": false,\n"
                    + "        \"can_use_start_date\": true,\n"
                    + "        \"sort_by_list\": [\n"
                    + "          \"transaction_date_desc\"\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"account_id\": \"NAID-DK-DKK-7418529630\",\n"
                    + "      \"account_status\": \"open\",\n"
                    + "      \"available_balance\": 91844.66,\n"
                    + "      \"bic\": \"NDEADKKK\",\n"
                    + "      \"booked_balance\": 91844.66,\n"
                    + "      \"category\": \"savings\",\n"
                    + "      \"country_code\": \"DK\",\n"
                    + "      \"credit_limit\": 0.00,\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"display_account_number\": \"7418529630\",\n"
                    + "      \"iban\": \"DK4520007418529630\",\n"
                    + "      \"interest_info\": {\n"
                    + "        \"interests\": [\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 27.86,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [\n"
                    + "              {\n"
                    + "                \"from_amount\": 0.00,\n"
                    + "                \"rate\": 0.1000,\n"
                    + "                \"to_amount\": 9999999999999999.99\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"rate_type\": \"credit\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.00,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [],\n"
                    + "            \"rate_type\": \"debit\"\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"accumulated_amount\": 0.00,\n"
                    + "            \"accumulated_year_amount\": 0.00,\n"
                    + "            \"interest_intervals\": [\n"
                    + "              {\n"
                    + "                \"from_amount\": 0.00,\n"
                    + "                \"rate\": 21.2500,\n"
                    + "                \"to_amount\": -9999999999999999.99\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"rate_type\": \"overdraft\"\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      },\n"
                    + "      \"latest_transaction_date\": \"2020-03-05\",\n"
                    + "      \"nickname\": \"Opsparing\",\n"
                    + "      \"permissions\": {\n"
                    + "        \"can_deposit_to_account\": true,\n"
                    + "        \"can_pay_from_account\": true,\n"
                    + "        \"can_transfer_from_account\": true,\n"
                    + "        \"can_transfer_to_account\": true,\n"
                    + "        \"can_view\": true,\n"
                    + "        \"can_view_transactions\": true,\n"
                    + "        \"require_4eye_signing\": false\n"
                    + "      },\n"
                    + "      \"product_code\": \"UNGOPS\",\n"
                    + "      \"product_name\": \"Nordea Opsparing\",\n"
                    + "      \"product_type\": \"493\",\n"
                    + "      \"registration_number\": \"2316\",\n"
                    + "      \"roles\": [\n"
                    + "        {\n"
                    + "          \"name\": \"TEST USER\",\n"
                    + "          \"role\": \"owner\"\n"
                    + "        }\n"
                    + "      ],\n"
                    + "      \"transaction_list_search_criteria\": {\n"
                    + "        \"can_use_end_date\": true,\n"
                    + "        \"can_use_free_text\": false,\n"
                    + "        \"can_use_highest_amount\": false,\n"
                    + "        \"can_use_lowest_amount\": false,\n"
                    + "        \"can_use_start_date\": true,\n"
                    + "        \"sort_by_list\": [\n"
                    + "          \"transaction_date_desc\"\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"sub_system_errors\": []\n"
                    + "}";

    static final String FETCH_ACCOUNT_1_TRANSACTIONS_RESULT =
            "{\n"
                    + "  \"continuation_key\": \"LEG_EjcqIJ8Abe9-bsc61MMA-UMCB7stdmeb2qPfCQVuitc=:rO0ABXNyAD9jb20ubm9yZGVhLmRiZi5kay5hY2NvdW50LmludGVncmF0aW9uLmNvcHlib29rcy5Db250aW51YXRpb25LZXlgVTENuzwM0gIAAUwAD2NvbnRpbnVhdGlvbmtleXQAEkxqYXZhL2xhbmcvU3RyaW5nO3hwdAA3UDAwMDAwMDAzNkc2ODk3NjQ3MDdHwIDAgMCAwIDAgMCAwIDAgDAwMDAwMDAwMDAwNTYyOTU0RA==\",\n"
                    + "  \"result\": [\n"
                    + "    {\n"
                    + "      \"amount\": -1164.05,\n"
                    + "      \"balance_after\": 91844.66,\n"
                    + "      \"booked\": true,\n"
                    + "      \"booking_date\": \"2020-03-05\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"description\": \"Bgs Lunar Way\",\n"
                    + "      \"has_details\": true,\n"
                    + "      \"interest_date\": \"2020-03-05\",\n"
                    + "      \"reconciliation_id\": \"UDY4OTc2NDcwNzcyMDIwMDMwNTAwMDAwMDA1NjY\",\n"
                    + "      \"reconciliation_status\": \"not_done\",\n"
                    + "      \"title\": \"Lunar Way\",\n"
                    + "      \"transaction_date\": \"2020-03-05\",\n"
                    + "      \"transaction_id\": \"FUVn231qH9MK06D_Kg7mxID_YTJFQUHkmCWxcxo8-OE.a2V5PTgxNjY4MDIzMTYgMjAyMDAzMDUmZHM9QkdTJmluY29taW5nPWZhbHNl\"\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"amount\": 6100.00,\n"
                    + "      \"balance_after\": 93008.71,\n"
                    + "      \"booked\": true,\n"
                    + "      \"booking_date\": \"2020-03-05\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"description\": \"Bgs From Nordea Pay\",\n"
                    + "      \"has_details\": true,\n"
                    + "      \"interest_date\": \"2020-03-05\",\n"
                    + "      \"reconciliation_id\": \"UDY4OTc2NDcwNzcyMDIwMDMwNTAwMDAwMDA1NjU\",\n"
                    + "      \"reconciliation_status\": \"not_done\",\n"
                    + "      \"title\": \"From Nordea Pay\",\n"
                    + "      \"transaction_date\": \"2020-03-05\",\n"
                    + "      \"transaction_id\": \"_sA7vL0hbV2lql6ZNsSTc3hBOqL_IyQQ-iDV76ypO28.a2V5PTAzOTI0NTA2NDIwMDY1Njg5NzY0NzA3NzA1MDMyMDIwJmRzPUFEVklTJmluY29taW5nPXRydWU\"\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"sub_system_errors\": []\n"
                    + "}";

    static final String FETCH_ACCOUNT_1_TRANSACTIONS_CONTINUATION =
            "{\n"
                    + "  \"result\": [\n"
                    + "    {\n"
                    + "      \"amount\": -1000.00,\n"
                    + "      \"balance_after\": 56295.44,\n"
                    + "      \"booked\": true,\n"
                    + "      \"booking_date\": \"2019-07-22\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"description\": \"Bgs Forbrug\",\n"
                    + "      \"has_details\": true,\n"
                    + "      \"interest_date\": \"2019-07-20\",\n"
                    + "      \"reconciliation_id\": \"UDY4OTc2NDcwNzcyMDE5MDcyMjAwMDAwMDAzNjY\",\n"
                    + "      \"reconciliation_status\": \"not_done\",\n"
                    + "      \"title\": \"Forbrug\",\n"
                    + "      \"transaction_date\": \"2019-07-22\",\n"
                    + "      \"transaction_id\": \"flRyYmE-CZ60YOY9AKzeHUHb37ZYIsU8unRhLUQvpI4.a2V5PTU5MTY3MjU5NzMgMjAxOTA3MjImZHM9QkdTJmluY29taW5nPWZhbHNl\"\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"amount\": 60.00,\n"
                    + "      \"balance_after\": 57295.44,\n"
                    + "      \"booked\": true,\n"
                    + "      \"booking_date\": \"2019-07-22\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"description\": \"MobilePay: Pernille\",\n"
                    + "      \"has_details\": true,\n"
                    + "      \"interest_date\": \"2019-07-21\",\n"
                    + "      \"reconciliation_id\": \"UDY4OTc2NDcwNzcyMDE5MDcyMjAwMDAwMDAzNjU\",\n"
                    + "      \"reconciliation_status\": \"not_done\",\n"
                    + "      \"title\": \"MobilePay: Pernille\",\n"
                    + "      \"transaction_date\": \"2019-07-22\",\n"
                    + "      \"transaction_id\": \"Q-EMsXJ6B0n99CVh108_6ZqkT2hLNn3IxkN7KtRQM4M.a2V5PTE5MTYyMjMyNTE5MjAzNjg5NzY0NzA3NzIyMDcyMDE5JmRzPUFEVklTJmluY29taW5nPXRydWU\"\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"sub_system_errors\": []\n"
                    + "}";

    static final String FETCH_CREDIT_CARDS =
            "{\n"
                    + "  \"cards\": [\n"
                    + "    {\n"
                    + "      \"atm_account_number\": null,\n"
                    + "      \"card_category\": \"credit\",\n"
                    + "      \"card_expiration\": {\n"
                    + "        \"date\": \"2022-10-31\",\n"
                    + "        \"formatted\": \"10/22\"\n"
                    + "      },\n"
                    + "      \"card_id\": \"9638527410963852\",\n"
                    + "      \"card_loyalty_group\": null,\n"
                    + "      \"card_status\": \"active\",\n"
                    + "      \"cardholder_name\": \"TEST USER\",\n"
                    + "      \"cardholder_type\": \"principal\",\n"
                    + "      \"country_code\": \"DK\",\n"
                    + "      \"credit\": {\n"
                    + "        \"credit_available_balance\": null,\n"
                    + "        \"credit_booked_balance\": null,\n"
                    + "        \"credit_limit\": null,\n"
                    + "        \"instalment_free_months\": [],\n"
                    + "        \"instalment_min_percent\": null,\n"
                    + "        \"interest\": null,\n"
                    + "        \"invoice\": null,\n"
                    + "        \"masked_credit_card_number\": \"1234 **** **** 5678\",\n"
                    + "        \"prev_min_instalment_amount\": null\n"
                    + "      },\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"debit\": null,\n"
                    + "      \"metadata\": null,\n"
                    + "      \"nickname\": null,\n"
                    + "      \"notifications\": null,\n"
                    + "      \"pan_id\": null,\n"
                    + "      \"parallel_cards\": null,\n"
                    + "      \"permissions\": {\n"
                    + "        \"allowed_to_enroll_mobile_payments\": null,\n"
                    + "        \"transactions\": true,\n"
                    + "        \"transfer_from_credit\": false,\n"
                    + "        \"view_pin\": true\n"
                    + "      },\n"
                    + "      \"principal_cardholder_name\": \"TEST USER\",\n"
                    + "      \"product_code\": \"DK0072\",\n"
                    + "      \"usage_limits\": null\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"atm_account_number\": null,\n"
                    + "      \"card_category\": \"debit\",\n"
                    + "      \"card_expiration\": {\n"
                    + "        \"date\": \"2021-07-31\",\n"
                    + "        \"formatted\": \"07/21\"\n"
                    + "      },\n"
                    + "      \"card_id\": \"81c43ca32d7beb0554c4fe6ca8a43ab9975755da\",\n"
                    + "      \"card_loyalty_group\": null,\n"
                    + "      \"card_status\": \"active\",\n"
                    + "      \"cardholder_name\": \"TEST USER\",\n"
                    + "      \"cardholder_type\": null,\n"
                    + "      \"country_code\": \"DK\",\n"
                    + "      \"credit\": null,\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"debit\": {\n"
                    + "        \"debit_account_balance\": null,\n"
                    + "        \"debit_account_key\": null,\n"
                    + "        \"debit_account_name\": null,\n"
                    + "        \"debit_account_number\": null,\n"
                    + "        \"masked_debit_card_number\": \"1111 **** **** 2222\"\n"
                    + "      },\n"
                    + "      \"metadata\": null,\n"
                    + "      \"nickname\": null,\n"
                    + "      \"notifications\": null,\n"
                    + "      \"pan_id\": null,\n"
                    + "      \"parallel_cards\": null,\n"
                    + "      \"permissions\": {\n"
                    + "        \"allowed_to_enroll_mobile_payments\": null,\n"
                    + "        \"transactions\": true,\n"
                    + "        \"transfer_from_credit\": false,\n"
                    + "        \"view_pin\": true\n"
                    + "      },\n"
                    + "      \"principal_cardholder_name\": null,\n"
                    + "      \"product_code\": \"DK0036\",\n"
                    + "      \"usage_limits\": null\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"atm_account_number\": null,\n"
                    + "      \"card_category\": \"debit\",\n"
                    + "      \"card_expiration\": {\n"
                    + "        \"date\": \"2022-11-30\",\n"
                    + "        \"formatted\": \"11/22\"\n"
                    + "      },\n"
                    + "      \"card_id\": \"5f820c4271cea591ef05cc0c2dcbba05b828a086\",\n"
                    + "      \"card_loyalty_group\": null,\n"
                    + "      \"card_status\": \"active\",\n"
                    + "      \"cardholder_name\": \"TEST USER\",\n"
                    + "      \"cardholder_type\": null,\n"
                    + "      \"country_code\": \"DK\",\n"
                    + "      \"credit\": null,\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"debit\": {\n"
                    + "        \"debit_account_balance\": null,\n"
                    + "        \"debit_account_key\": null,\n"
                    + "        \"debit_account_name\": null,\n"
                    + "        \"debit_account_number\": null,\n"
                    + "        \"masked_debit_card_number\": \"3333 **** **** 4444\"\n"
                    + "      },\n"
                    + "      \"metadata\": null,\n"
                    + "      \"nickname\": null,\n"
                    + "      \"notifications\": null,\n"
                    + "      \"pan_id\": null,\n"
                    + "      \"parallel_cards\": null,\n"
                    + "      \"permissions\": {\n"
                    + "        \"allowed_to_enroll_mobile_payments\": null,\n"
                    + "        \"transactions\": true,\n"
                    + "        \"transfer_from_credit\": false,\n"
                    + "        \"view_pin\": true\n"
                    + "      },\n"
                    + "      \"principal_cardholder_name\": null,\n"
                    + "      \"product_code\": \"DK0040\",\n"
                    + "      \"usage_limits\": null\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"atm_account_number\": null,\n"
                    + "      \"card_category\": \"debit\",\n"
                    + "      \"card_expiration\": {\n"
                    + "        \"date\": \"2020-12-31\",\n"
                    + "        \"formatted\": \"12/20\"\n"
                    + "      },\n"
                    + "      \"card_id\": \"76ec8f53ebdb5012bac46616faaeb151233bd383\",\n"
                    + "      \"card_loyalty_group\": null,\n"
                    + "      \"card_status\": \"active\",\n"
                    + "      \"cardholder_name\": \"TEST USER\",\n"
                    + "      \"cardholder_type\": null,\n"
                    + "      \"country_code\": \"DK\",\n"
                    + "      \"credit\": null,\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"debit\": {\n"
                    + "        \"debit_account_balance\": null,\n"
                    + "        \"debit_account_key\": null,\n"
                    + "        \"debit_account_name\": null,\n"
                    + "        \"debit_account_number\": null,\n"
                    + "        \"masked_debit_card_number\": \"5555 **** **** 6666\"\n"
                    + "      },\n"
                    + "      \"metadata\": null,\n"
                    + "      \"nickname\": null,\n"
                    + "      \"notifications\": null,\n"
                    + "      \"pan_id\": null,\n"
                    + "      \"parallel_cards\": null,\n"
                    + "      \"permissions\": {\n"
                    + "        \"allowed_to_enroll_mobile_payments\": null,\n"
                    + "        \"transactions\": true,\n"
                    + "        \"transfer_from_credit\": false,\n"
                    + "        \"view_pin\": true\n"
                    + "      },\n"
                    + "      \"principal_cardholder_name\": null,\n"
                    + "      \"product_code\": \"DK0036\",\n"
                    + "      \"usage_limits\": null\n"
                    + "    }\n"
                    + "  ]\n"
                    + "}";

    static final String FETCH_CREDIT_CARD_DETAILS =
            "{\n"
                    + "  \"card_id\": \"9638527410963852\",\n"
                    + "  \"card_category\": \"credit\",\n"
                    + "  \"card_status\": \"active\",\n"
                    + "  \"card_expiration\": {\n"
                    + "    \"date\": \"2022-10-31\",\n"
                    + "    \"formatted\": \"10/22\"\n"
                    + "  },\n"
                    + "  \"cardholder_name\": \"TEST USER\",\n"
                    + "  \"cardholder_type\": \"principal\",\n"
                    + "  \"principal_cardholder_name\": \"TEST USER\",\n"
                    + "  \"product_code\": \"DK0072\",\n"
                    + "  \"card_loyalty_group\": null,\n"
                    + "  \"country_code\": \"DK\",\n"
                    + "  \"currency\": \"DKK\",\n"
                    + "  \"nickname\": null,\n"
                    + "  \"pan_id\": \"43066705\",\n"
                    + "  \"atm_account_number\": null,\n"
                    + "  \"credit\": {\n"
                    + "    \"masked_credit_card_number\": \"1234 **** **** 5678\",\n"
                    + "    \"credit_limit\": 50000.00,\n"
                    + "    \"credit_booked_balance\": 10000.00,\n"
                    + "    \"credit_available_balance\": 40000.00,\n"
                    + "    \"prev_min_instalment_amount\": null,\n"
                    + "    \"instalment_min_percent\": null,\n"
                    + "    \"instalment_free_months\": [],\n"
                    + "    \"interest\": {\n"
                    + "      \"reference_rate_type\": null,\n"
                    + "      \"margin\": null,\n"
                    + "      \"reference_rate\": null,\n"
                    + "      \"billing_period_rate\": 0.00\n"
                    + "    },\n"
                    + "    \"invoice\": {\n"
                    + "      \"next_sum\": null,\n"
                    + "      \"next_date\": \"2020-04-01\",\n"
                    + "      \"prev_total\": null,\n"
                    + "      \"prev_date\": null,\n"
                    + "      \"due_day_of_month\": 1,\n"
                    + "      \"reference_number\": null\n"
                    + "    }\n"
                    + "  },\n"
                    + "  \"debit\": {\n"
                    + "    \"masked_debit_card_number\": \"1234 **** **** 5678\",\n"
                    + "    \"debit_account_balance\": null,\n"
                    + "    \"debit_account_number\": \"7418529630\",\n"
                    + "    \"debit_account_name\": \"Opsparing\",\n"
                    + "    \"debit_account_key\": null\n"
                    + "  },\n"
                    + "  \"parallel_cards\": null,\n"
                    + "  \"usage_limits\": {\n"
                    + "    \"internet\": true,\n"
                    + "    \"internet_non3d\": null,\n"
                    + "    \"contactless\": null,\n"
                    + "    \"daily_limits\": {\n"
                    + "      \"atm_pay\": null,\n"
                    + "      \"atm_withdrawal\": 0.00\n"
                    + "    },\n"
                    + "    \"weekly_limits\": null,\n"
                    + "    \"monthly_credit_spending_limit\": null,\n"
                    + "    \"permanent_region\": [\n"
                    + "      \"denmark\"\n"
                    + "    ],\n"
                    + "    \"temporary_region\": null\n"
                    + "  },\n"
                    + "  \"permissions\": {\n"
                    + "    \"transactions\": true,\n"
                    + "    \"transfer_from_credit\": false,\n"
                    + "    \"view_pin\": true,\n"
                    + "    \"allowed_to_enroll_mobile_payments\": null\n"
                    + "  },\n"
                    + "  \"notifications\": null,\n"
                    + "  \"metadata\": {\n"
                    + "    \"geographical_zones\": [\n"
                    + "      \"denmark\",\n"
                    + "      \"europe\",\n"
                    + "      \"nordic\",\n"
                    + "      \"baltic\",\n"
                    + "      \"americas\",\n"
                    + "      \"asia\",\n"
                    + "      \"oceania\",\n"
                    + "      \"africa\"\n"
                    + "    ],\n"
                    + "    \"limits\": {\n"
                    + "      \"atm_payment\": 0,\n"
                    + "      \"atm_payment_step\": 0,\n"
                    + "      \"atm_withdrawal\": 10000,\n"
                    + "      \"atm_withdrawal_step\": 500\n"
                    + "    }\n"
                    + "  }\n"
                    + "}\n";

    static final String FETCH_CREDIT_CARD_TRANSACTIONS_PAGE1 =
            "{\n"
                    + "  \"billing_period\": {\n"
                    + "    \"billing_period_end_date\": \"2020-02-17\",\n"
                    + "    \"billing_period_start_date\": \"2020-01-18\",\n"
                    + "    \"last_invoiced_sum\": 3600.5,\n"
                    + "    \"non_invoiced_sum\": null\n"
                    + "  },\n"
                    + "  \"page\": 1,\n"
                    + "  \"page_size\": 100,\n"
                    + "  \"size\": 3,\n"
                    + "  \"transactions\": [\n"
                    + "    {\n"
                    + "      \"amount\": -410.00,\n"
                    + "      \"booked\": true,\n"
                    + "      \"booking_date\": \"2020-02-17\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"exchange_rate\": null,\n"
                    + "      \"invoice_status\": \"paid\",\n"
                    + "      \"invoiced_date\": null,\n"
                    + "      \"merchant_city\": \"Aarhus C\",\n"
                    + "      \"merchant_country\": \"DNK\",\n"
                    + "      \"original_amount\": null,\n"
                    + "      \"original_currency\": null,\n"
                    + "      \"title\": \"Very good pizza\",\n"
                    + "      \"transaction_date\": \"2020-02-14\",\n"
                    + "      \"transaction_id\": \"230407857\",\n"
                    + "      \"transaction_type\": null\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"amount\": -578.00,\n"
                    + "      \"booked\": true,\n"
                    + "      \"booking_date\": \"2020-02-15\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"exchange_rate\": null,\n"
                    + "      \"invoice_status\": \"paid\",\n"
                    + "      \"invoiced_date\": null,\n"
                    + "      \"merchant_city\": \"CARRICKMACROS\",\n"
                    + "      \"merchant_country\": \"IRL\",\n"
                    + "      \"original_amount\": null,\n"
                    + "      \"original_currency\": null,\n"
                    + "      \"title\": \"Awesome burger\",\n"
                    + "      \"transaction_date\": \"2020-02-14\",\n"
                    + "      \"transaction_id\": \"230163349\",\n"
                    + "      \"transaction_type\": null\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"amount\": -1347.50,\n"
                    + "      \"booked\": true,\n"
                    + "      \"booking_date\": \"2020-02-13\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"exchange_rate\": null,\n"
                    + "      \"invoice_status\": \"paid\",\n"
                    + "      \"invoiced_date\": null,\n"
                    + "      \"merchant_city\": \"ARHUS C\",\n"
                    + "      \"merchant_country\": \"DNK\",\n"
                    + "      \"original_amount\": null,\n"
                    + "      \"original_currency\": null,\n"
                    + "      \"title\": \"Some other thingy\",\n"
                    + "      \"transaction_date\": \"2020-02-11\",\n"
                    + "      \"transaction_id\": \"229937819\",\n"
                    + "      \"transaction_type\": null\n"
                    + "    }\n"
                    + "  ]\n"
                    + "}";

    static final String FETCH_CREDIT_CARD_TRANSACTIONS_PAGE2 =
            "{\n"
                    + "  \"billing_period\": {\n"
                    + "    \"billing_period_end_date\": \"2020-02-17\",\n"
                    + "    \"billing_period_start_date\": \"2020-01-18\",\n"
                    + "    \"last_invoiced_sum\": 3600.5,\n"
                    + "    \"non_invoiced_sum\": null\n"
                    + "  },\n"
                    + "  \"page\": 2,\n"
                    + "  \"page_size\": 100,\n"
                    + "  \"size\": 0,\n"
                    + "  \"transactions\": []\n"
                    + "}";

    static final String FETCH_INVESTMENT_ACCOUNTS =
            "{\n"
                    + "  \"accounts\": [\n"
                    + "    {\n"
                    + "      \"account_number\": \"4321 321 321\",\n"
                    + "      \"cash_amount\": 0.0,\n"
                    + "      \"classification\": \"FREE\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"custody_tags\": [\n"
                    + "        \"EXCHANGE_TRADING\"\n"
                    + "      ],\n"
                    + "      \"details_available\": true,\n"
                    + "      \"has_additional_info\": false,\n"
                    + "      \"has_fund_allocation_plan\": false,\n"
                    + "      \"has_reports\": false,\n"
                    + "      \"holdings\": [],\n"
                    + "      \"id\": \"BMS:4321321321\",\n"
                    + "      \"market_value\": 0.0,\n"
                    + "      \"market_value_in_local_currrency\": 0.0,\n"
                    + "      \"name\": \"Depot\",\n"
                    + "      \"owner_id\": \"7894561230\",\n"
                    + "      \"owner_name\": \"TEST USER\",\n"
                    + "      \"profit_loss\": 0.0,\n"
                    + "      \"profit_loss_applicable\": true,\n"
                    + "      \"profit_loss_percentage\": 0,\n"
                    + "      \"profit_loss_valid\": true,\n"
                    + "      \"tags\": [],\n"
                    + "      \"todays_change\": 0.0,\n"
                    + "      \"todays_change_percentage\": 0.0,\n"
                    + "      \"todays_change_valid\": true,\n"
                    + "      \"todays_changes_applicable\": true,\n"
                    + "      \"type\": \"CUSTODY\",\n"
                    + "      \"wrapper\": false\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"account_number\": \"1234 123 456\",\n"
                    + "      \"cash_amount\": 0.32,\n"
                    + "      \"classification\": \"FREE\",\n"
                    + "      \"currency\": \"DKK\",\n"
                    + "      \"custody_tags\": [],\n"
                    + "      \"details_available\": true,\n"
                    + "      \"has_additional_info\": false,\n"
                    + "      \"has_fund_allocation_plan\": false,\n"
                    + "      \"has_reports\": true,\n"
                    + "      \"holdings\": [\n"
                    + "        {\n"
                    + "          \"avg_purchase_price\": 0.9898,\n"
                    + "          \"currency\": \"DKK\",\n"
                    + "          \"custody_key\": \"DKWRAP:1234123456\",\n"
                    + "          \"fx_rate\": 1.0,\n"
                    + "          \"id\": \"DKWRAP:1234123456+BMS-DK9876543210-UNOT-null\",\n"
                    + "          \"instrument\": {\n"
                    + "            \"buy_allowed\": false,\n"
                    + "            \"currency\": \"DKK\",\n"
                    + "            \"details_available\": true,\n"
                    + "            \"dividend_paying\": false,\n"
                    + "            \"document_types\": [],\n"
                    + "            \"flag_code\": \"DK\",\n"
                    + "            \"fund_category\": \"Global\",\n"
                    + "            \"fund_type\": \"Multi-Asset\",\n"
                    + "            \"id\": \"IMC-DK9876543210-DKOTC-DKK\",\n"
                    + "            \"instrument_name\": \"Nora Fund Five (DKK)\",\n"
                    + "            \"instrument_type\": \"FUND\",\n"
                    + "            \"isin\": \"DK9876543210\",\n"
                    + "            \"issuer\": \"Nordea Funds Ltd\",\n"
                    + "            \"lot_size\": 1.0,\n"
                    + "            \"main_sector_code\": \"GICS45\",\n"
                    + "            \"management_fee\": 0.0,\n"
                    + "            \"price\": 0.98,\n"
                    + "            \"price_precision\": 2,\n"
                    + "            \"price_time\": 1583708400000,\n"
                    + "            \"price_time_iso\": \"2020-03-08T23:00:00Z\",\n"
                    + "            \"region_allocation\": [\n"
                    + "              {\n"
                    + "                \"code\": \"USA\",\n"
                    + "                \"value\": 51.11\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"EUROPE\",\n"
                    + "                \"value\": 25.21\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"FAR_EAST_EM\",\n"
                    + "                \"value\": 15.48\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"JAPAN\",\n"
                    + "                \"value\": 6.52\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"HOME_BIAS\",\n"
                    + "                \"value\": 0.86\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"OTHER\",\n"
                    + "                \"value\": 0.82\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"returns\": {\n"
                    + "              \"five_years\": 0.0,\n"
                    + "              \"one_day\": -5.77,\n"
                    + "              \"one_year\": -1.26,\n"
                    + "              \"three_years\": 0.0,\n"
                    + "              \"year_to_date\": -13.86\n"
                    + "            },\n"
                    + "            \"risk\": 5,\n"
                    + "            \"sector_allocation\": [\n"
                    + "              {\n"
                    + "                \"code\": \"GICS45\",\n"
                    + "                \"value\": 17.54\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS40\",\n"
                    + "                \"value\": 16.12\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS35\",\n"
                    + "                \"value\": 11.46\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS25\",\n"
                    + "                \"value\": 11.08\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS20\",\n"
                    + "                \"value\": 10.57\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS50\",\n"
                    + "                \"value\": 8.7\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS30\",\n"
                    + "                \"value\": 8.2\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS10\",\n"
                    + "                \"value\": 4.94\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS15\",\n"
                    + "                \"value\": 4.65\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS55\",\n"
                    + "                \"value\": 3.5\n"
                    + "              },\n"
                    + "              {\n"
                    + "                \"code\": \"GICS0\",\n"
                    + "                \"value\": 3.24\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"sell_allowed\": false,\n"
                    + "            \"switch_allowed\": false,\n"
                    + "            \"use_native_trading_flow\": false\n"
                    + "          },\n"
                    + "          \"market_value\": 9785.3,\n"
                    + "          \"name\": \"Nora Fund Five (DKK)\",\n"
                    + "          \"profit_loss\": -98.24,\n"
                    + "          \"profit_loss_percentage\": -0.99,\n"
                    + "          \"purchase_value\": 9883.54,\n"
                    + "          \"quantity\": 9985.0,\n"
                    + "          \"show_profit_loss\": true,\n"
                    + "          \"tags\": []\n"
                    + "        },\n"
                    + "        {\n"
                    + "          \"currency\": \"DKK\",\n"
                    + "          \"custody_key\": \"DKWRAP:1234123456\",\n"
                    + "          \"fx_rate\": 1.0,\n"
                    + "          \"id\": \"DKWRAP:1234123456+IMC-DKK-DKK-DKK\",\n"
                    + "          \"instrument\": {\n"
                    + "            \"buy_allowed\": false,\n"
                    + "            \"currency\": \"DKK\",\n"
                    + "            \"details_available\": false,\n"
                    + "            \"flag_code\": \"\",\n"
                    + "            \"id\": \"IMC-DKK-DKK-DKK\",\n"
                    + "            \"instrument_name\": \"Kontant beholdning 1234 123 456 DKK\",\n"
                    + "            \"instrument_type\": \"CASH\",\n"
                    + "            \"isin\": \"DKK\",\n"
                    + "            \"issuer\": \"-\",\n"
                    + "            \"main_sector_code\": \"GICS0\",\n"
                    + "            \"price_precision\": 2,\n"
                    + "            \"region_allocation\": [],\n"
                    + "            \"sector_allocation\": [\n"
                    + "              {\n"
                    + "                \"code\": \"GICS0\",\n"
                    + "                \"value\": 100.0\n"
                    + "              }\n"
                    + "            ],\n"
                    + "            \"sell_allowed\": false,\n"
                    + "            \"switch_allowed\": false,\n"
                    + "            \"use_native_trading_flow\": false\n"
                    + "          },\n"
                    + "          \"market_value\": 0.32,\n"
                    + "          \"name\": \"Kontant beholdning 1234 123 456 DKK\",\n"
                    + "          \"quantity\": 0.32,\n"
                    + "          \"show_profit_loss\": false,\n"
                    + "          \"tags\": []\n"
                    + "        }\n"
                    + "      ],\n"
                    + "      \"id\": \"DKWRAP:1234123456\",\n"
                    + "      \"market_value\": 9785.62,\n"
                    + "      \"market_value_in_local_currrency\": 9785.62,\n"
                    + "      \"name\": \"NORA depot\",\n"
                    + "      \"owner_id\": \"7894561230\",\n"
                    + "      \"owner_name\": \"TEST USER\",\n"
                    + "      \"profit_loss\": -98.24,\n"
                    + "      \"profit_loss_applicable\": true,\n"
                    + "      \"profit_loss_percentage\": -0.99,\n"
                    + "      \"profit_loss_valid\": true,\n"
                    + "      \"tags\": [],\n"
                    + "      \"todays_change\": 0.0,\n"
                    + "      \"todays_change_percentage\": 0.0,\n"
                    + "      \"todays_change_valid\": false,\n"
                    + "      \"todays_changes_applicable\": true,\n"
                    + "      \"type\": \"CUSTODY\",\n"
                    + "      \"wrapper\": false\n"
                    + "    }\n"
                    + "  ],\n"
                    + "  \"legacy_errors\": [],\n"
                    + "  \"read_only_access\": false,\n"
                    + "  \"totals\": {\n"
                    + "    \"todays_change\": 0.0,\n"
                    + "    \"todays_change_pct\": 0.0,\n"
                    + "    \"todays_change_valid\": false\n"
                    + "  }\n"
                    + "}";
}
