java_library(
    name = "provider",
    srcs = glob(["*.java"]),
    data = [
    ],
    visibility = ["//visibility:public"],
    runtime_deps = [
    ],
    deps = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/agents/framework/wiremock/configuration",
        "//third_party:com_google_inject_guice",
        "//third_party:javax_inject_javax_inject",
    ],
)
