java_library(
    name = "random",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//third_party:commons_codec_commons_codec",
        "//third_party:org_apache_commons_commons_lang3",
    ],
)
