java_library(
    name = "eidas",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/lib/src/main/java/se/tink/backend/aggregation/agents/utils/crypto/parser",
        "//third_party:com_google_guava_guava",
    ],
)
