kind: RuleGroup
apiVersion: monitoring.tink.se/v1
metadata:
  name: alerts-gb-volumes
  namespace: agents
spec:
  rules:

    - alert: LoginVolumeDropOver20%_GB
      expr: |
        (sum(increase(tink_agent_login_total{market="GB", provider_type!="test"}[1d])) by (market)
        / (sum(increase(tink_agent_login_total{market="GB", provider_type!="test"}[2d])) by (market)
        - sum(increase(tink_agent_login_total{market="GB", provider_type!="test"}[1d])) by (market)) - 1) < -0.20
      for: 4h
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaMarketUKLink }}
          {{ .Values.grafanaMarketLink }}
        summary: Login volume dropped significantly
        tags: {{ .Values.fluffyTags }}

    - alert: LoginVolumeDropOver20%ForSpecificAction_GB
      expr: |
        (sum(increase(tink_agent_login_total{market="GB", provider_type!="test"}[1d])) by (market,action)
        / (sum(increase(tink_agent_login_total{market="GB", provider_type!="test"}[2d])) by (market,action)
        - sum(increase(tink_agent_login_total{market="GB", provider_type!="test"}[1d])) by (market,action)) - 1) < -0.20
      for: 4h
      labels:
        severity: urgent
        priority: P1
        who: integration-fluffy
      annotations:
        description: {{ .Values.kibanaMarketUKLink }}
          {{ .Values.grafanaMarketLink }}
        summary: Login volume dropped significantly for <{ $labels.action }>
        tags: {{ .Values.fluffyTags }}
