server:
  shutdownGracePeriod: 20s
  applicationConnectors:
    - type: http
      port: 9091
    - type: https
      port: 9101
      keyStorePath: data/security/developer.keystore
      keyStorePassword: changeme
      certAlias: developer.internal.tink.se
      trustStorePath: data/security/TinkCA.truststore
      trustStorePassword: changeme
      # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8091

endpoints:
  main:
    url: http://localhost:9090/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  system:
    url: http://localhost:9091/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  aggregation:
    url: http://localhost:9095/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  analytics:
    url: http://localhost:9093/
  encryption:
    url: http://localhost:9094/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  connector:
    url: http://localhost:9098/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"

taskQueue:
  workers: 1
  mode: enabled
  hosts:
    - kafka:9092
  firehoseEnabled: true

cluster: TEST_PARTNER

serviceAuthentication:
  serverTokens:
    - devtoken

administrativeMode: ["ccccccelgiev", "ccccccflgngc"]

developmentMode: true

distributedDatabase:
  seeds:
    - cassandra
  enabled: true
  datacenter: TestDatacenter

database:
  driverClass: com.mysql.jdbc.Driver
  username: tink
  password: tink
  url: jdbc:mysql://mysql/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: false
  persistenceUnitName: tink-main-api
  generateDdl: true

scheduler:
  enabled: true

coordination:
  hosts: zookeeper:2181

idcontrol:
  dryRunDataRefresh: true
  daysToFetchChangesFor: 2

cache:
  hosts: memcached:11211
  enabled: true

search:
  clusterName: elasticsearch
  hosts: elasticsearch:9300
  enabled: true

facebook:
  appId: 1482993025252778
  appSecret: f45f41de51bc7075b712e88ed270c93e

notifications:
  startHourOfDay: 9
  endHourOfDay: 22
  applications:
    se.tink.frontend.mobile:
      apple:
        topic: se.tink.iphone
        keystore:
          filename: enterprise.p12
          password: AgtZfUBuvQhF9Cr9nHsbqx]RBLfat2CH
      google:
        apiKey: AIzaSyBbD-9t5m3EnL9U8vxD-3qrg9OKUrVZ92g

analytics:
  intercom:
    enabled: false

reprocessTransactions:
  categoryCodes: ["expenses:misc.uncategorized", "income:other.other"]
  description:
  includeModifiedByUser: false

logging:
  level: INFO
  loggers:
    se.tink: TRACE
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} %blue(%logger) %message%n%xException'
    - type: file
      threshold: INFO
      currentLogFilename: /usr/share/tink-backend-system/log/tink-backend-system.log
      archive: true
      archivedLogFilenamePattern: /usr/share/tink-backend-system/log/tink-backend-system-%d.log.gz
      archivedFileCount: 5
      timeZone: Europe/Stockholm
      logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %message%n%xException'

template:
  enabled: false

connector:
  defaultProviderName: "se-testpartner-abstract"
