server:
  shutdownGracePeriod: 30s
  applicationConnectors:
    - type: http
      port: 9095
    - type: https
      port: 9105
      keyStorePath: data/security/developer.keystore
      keyStorePassword: changeme
      certAlias: developer.internal.tink.se
      trustStorePath: data/security/TinkCA.truststore
      trustStorePassword: changeme
      # Validation disabled since Dropwizard/Jetty tries to check revocation of our homebrewed certs, which fails.
      validateCerts: false
  adminConnectors:
    - type: http
      port: 8095

grpc:
  port: 9995

endpoints:
  main:
    url: http://localhost:9090/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  system:
    url: http://localhost:9091/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  aggregation:
    url: http://localhost:9095/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  analytics:
    url: http://localhost:9093/
  encryption:
    url: http://localhost:9094/
    accessToken: devtoken
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"
  connector:
    url: http://localhost:9098/
    pinnedCertificates:
      - "CERTSHA256:C050C78642605EE54DDBF2B38F7700EFAC77D19DC5388B807550D325574220E7"

cluster: NEWPORT

serviceAuthentication:
  serverTokens:
    - devtoken

developmentMode: true

distributedDatabase:
  seeds:
    - 172.16.42.2
  enabled: true

database:
  driverClass: com.mysql.jdbc.Driver
  username: tink
  password: tink
  url: jdbc:mysql://172.16.42.2/tink?useLocalSessionState=true&rewriteBatchedStatements=true&useSSL=true&verifyServerCertificate=false
  showSql: false
  persistenceUnitName: tink-aggregation-api
  generateDdl: true

scheduler:
  enabled: false

coordination:
  hosts: 172.16.42.2:2181

cache:
  hosts: 172.16.42.2:11211
  enabled: true

search:
  clusterName: elasticsearch
  hosts: 172.16.42.2:9300
  enabled: true

analytics:
  intercom:
    enabled: false

logging:
  level: INFO
  loggers:
    se.tink: TRACE
    se.tink.org.eclipse: INFO
    org.hibernate: WARN
  appenders:
    - type: console
      threshold: ALL
      timeZone: Europe/Stockholm
      logFormat: '%magenta(%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"}) %highlight(%level) [%thread] R:%X{requestId} %blue(%logger) %message%n%xException'
    - type: file
      threshold: INFO
      currentLogFilename: /usr/share/tink-backend-aggregation/log/tink-backend-aggregation.log
      archive: true
      archivedLogFilenamePattern: /usr/share/tink-backend-aggregation/log/tink-backend-aggregation-%d.log.gz
      archivedFileCount: 5
      timeZone: Europe/Stockholm
      logFormat: '%date{"yyyy-MM-dd HH:mm:ss,SSSXXX"} %level [%thread] R:%X{requestId} %logger %message%n%xException'

template:
  enabled: false
