java_library(
    name = "configuration",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/integration/api",
        "//src/integration/lib",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//third_party:io_dropwizard_dropwizard_configuration",
        "//third_party:io_dropwizard_dropwizard_core",
        "//third_party:io_dropwizard_dropwizard_jersey",
        "//third_party:javax_validation_validation_api",
        "@aggregation//:com_fasterxml_jackson_core_jackson_annotations",
    ],
)
